In [1]:
# Connect to DB

host="localhost"
user="root"

# host="192.168.100.3"
# user="rootx"

import mysql.connector
mydb = mysql.connector.connect(
    host=host,
    user=user,
    password="",
    database="pr_scraping_job_vacancy_indonesia_2022_04"
)
mycursor = mydb.cursor()
print('connect')

entity = 'domain'

# set query 1
select = ' id, created_at, ' + entity
fromdb = 'jobstreet_raws'
where = ' '
group = ' ' 

# ALTER TABLE `job_vacancies` ADD `salary_type_id` INT NULL DEFAULT NULL AFTER `experience`;

connect

In [2]:
# insert new job_vacancies 

# set query 1
select = ' id, ' + entity
fromdb = 'jobstreet_raws_v2'
where = ' '
group = ' ' 
 
# query 1
mycursor = mydb.cursor()
mycursor.execute("SELECT " + select + " FROM `" + fromdb + "` " + where + group  )
myresult = mycursor.fetchall()
  
print('Start and Please Wait..')
# loop query 1
for x in myresult:  
    idx = str(x[0])
    word = x[1]  
    
    words = ' id: ' + idx + ' // word: ' + word
    print(words)

    query3 = "UPDATE job_vacancies SET "+entity+"_id =  '" + word + "' where raw_id = '" + idx + "'"
    print(query3)
    mycursor.execute(query3)
    mydb.commit()  

    query4 = "UPDATE jobstreet_raws_rc SET "+entity+" = '--extracted--'   " 
    where4 = "  where id = '" + idx + "'"  
    print(query4 + where4)
    mycursor.execute(query4 + where4)
    mydb.commit()  
         
print('Done : ' + str(len(myresult)) + ' row(s)')

Start and Please Wait..
 id: 1 // word: Akuntansi / Keuangan, Akuntansi Umum / Pembiayaan
UPDATE job_vacancies SET domain_id =  'Akuntansi / Keuangan, Akuntansi Umum / Pembiayaan ' where raw_id = '1'

ProgrammingError: 1054 (42S22): Unknown column 'domain_id' in 'field list'

In [4]:
# insert new job_vacancies 
entity = 'domain_id'
# set query 1
select = ' id, ' + entity
fromdb = 'jobstreet_raws_v2'
where = ' '
group = ' ' 
 
# query 1
mycursor = mydb.cursor()
mycursor.execute("SELECT " + select + " FROM `" + fromdb + "` " + where + group  )
myresult = mycursor.fetchall()
  
print('Start and Please Wait..')
# loop query 1
for x in myresult:  
    idx = str(x[0])
    word = str(x[1])  
    
    words = ' id: ' + idx + ' // word: ' + word
    print(words)

    query3 = "UPDATE job_vacancies SET "+entity+" =  '" + word + "' where raw_id = '" + idx + "'"
    print(query3)
    mycursor.execute(query3)
    mydb.commit()  

    query4 = "UPDATE jobstreet_raws_rc SET domain = '--extracted--'   " 
    where4 = "  where id = '" + idx + "'"  
    print(query4 + where4)
    mycursor.execute(query4 + where4)
    mydb.commit()  
         
print('Done : ' + str(len(myresult)) + ' row(s)')

Start and Please Wait..
 id: 1 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1'
 id: 2 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2'
 id: 3 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3'
 id: 4 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4'
 id: 5 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '5'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5'
 id: 6 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '6'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6'
 id: 7 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '7'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7'
 id: 8 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8'
 id: 9 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '9'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9'
 id: 10 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10'
 id: 11 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '11'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11'
 id: 12 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12'
 id: 13 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '13'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13'
 id: 14 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14'
 id: 15 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '15'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15'
 id: 16 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16'
 id: 17 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '17'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17'
 id: 18 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '18'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18'
 id: 19 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19'
 id: 20 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '20'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20'
 id: 21 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '21'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '21'
 id: 22 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '22'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '22'
 id: 23 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '23'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '23'
 id: 24 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '24'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '24'
 id: 25 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '25'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '25'
 id: 26 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '26'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '26'
 id: 27 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '27'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '27'
 id: 28 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '28'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '28'
 id: 29 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '29'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '29'
 id: 30 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '30'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '30'
 id: 31 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '31'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '31'
 id: 32 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '32'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '32'
 id: 33 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '33'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '33'
 id: 34 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '34'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '34'
 id: 35 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '35'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '35'
 id: 36 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '36'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '36'
 id: 37 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '37'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '37'
 id: 38 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '38'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '38'
 id: 39 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '39'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '39'
 id: 40 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '40'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '40'
 id: 41 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '41'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '41'
 id: 42 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '42'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '42'
 id: 43 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '43'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '43'
 id: 44 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '44'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '44'
 id: 45 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '45'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '45'
 id: 46 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '46'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '46'
 id: 47 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '47'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '47'
 id: 48 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '48'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '48'
 id: 49 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '49'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '49'
 id: 50 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '50'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '50'
 id: 51 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '51'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '51'
 id: 52 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '52'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '52'
 id: 53 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '53'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '53'
 id: 54 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '54'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '54'
 id: 55 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '55'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '55'
 id: 56 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '56'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '56'
 id: 57 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '57'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '57'
 id: 58 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '58'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '58'
 id: 59 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '59'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '59'
 id: 60 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '60'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '60'
 id: 61 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '61'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '61'
 id: 62 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '62'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '62'
 id: 63 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '63'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '63'
 id: 64 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '64'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '64'
 id: 65 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '65'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '65'
 id: 66 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '66'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '66'
 id: 67 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '67'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '67'
 id: 68 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '68'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '68'
 id: 69 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '69'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '69'
 id: 70 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '70'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '70'
 id: 71 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '71'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '71'
 id: 72 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '72'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '72'
 id: 73 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '73'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '73'
 id: 74 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '74'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '74'
 id: 75 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '75'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '75'
 id: 76 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '76'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '76'
 id: 77 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '77'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '77'
 id: 78 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '78'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '78'
 id: 79 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '79'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '79'
 id: 80 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '80'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '80'
 id: 81 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '81'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '81'
 id: 82 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '82'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '82'
 id: 83 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '83'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '83'
 id: 84 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '84'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '84'
 id: 85 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '85'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '85'
 id: 86 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '86'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '86'
 id: 87 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '87'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '87'
 id: 88 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '88'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '88'
 id: 89 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '89'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '89'
 id: 90 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '90'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '90'
 id: 91 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '91'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '91'
 id: 92 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '92'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '92'
 id: 93 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '93'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '93'
 id: 94 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '94'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '94'
 id: 95 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '95'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '95'
 id: 96 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '96'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '96'
 id: 97 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '97'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '97'
 id: 98 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '98'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '98'
 id: 99 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '99'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '99'
 id: 100 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '100'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '100'
 id: 101 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '101'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '101'
 id: 102 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '102'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '102'
 id: 103 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '103'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '103'
 id: 104 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '104'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '104'
 id: 105 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '105'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '105'
 id: 106 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '106'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '106'
 id: 107 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '107'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '107'
 id: 108 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '108'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '108'

 id: 109 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '109'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '109'
 id: 110 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '110'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '110'
 id: 111 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '111'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '111'
 id: 112 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '112'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '112'
 id: 113 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '113'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '113'
 id: 114 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '114'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '114'
 id: 115 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '115'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '115'
 id: 116 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '116'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '116'
 id: 117 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '117'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '117'
 id: 118 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '118'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '118'
 id: 119 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '119'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '119'
 id: 120 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '120'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '120'
 id: 121 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '121'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '121'
 id: 122 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '122'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '122'
 id: 123 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '123'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '123'
 id: 124 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '124'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '124'
 id: 125 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '125'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '125'
 id: 126 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '126'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '126'
 id: 127 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '127'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '127'
 id: 128 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '128'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '128'
 id: 129 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '129'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '129'
 id: 130 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '130'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '130'
 id: 131 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '131'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '131'
 id: 132 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '132'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '132'
 id: 133 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '133'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '133'
 id: 134 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '134'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '134'
 id: 135 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '135'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '135'
 id: 136 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '136'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '136'
 id: 137 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '137'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '137'
 id: 138 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '138'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '138'
 id: 139 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '139'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '139'
 id: 140 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '140'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '140'
 id: 141 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '141'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '141'
 id: 142 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '142'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '142'
 id: 143 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '143'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '143'
 id: 144 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '144'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '144'
 id: 145 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '145'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '145'
 id: 146 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '146'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '146'
 id: 147 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '147'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '147'
 id: 148 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '148'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '148'
 id: 149 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '149'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '149'
 id: 150 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '150'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '150'
 id: 151 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '151'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '151'
 id: 152 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '152'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '152'
 id: 153 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '153'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '153'
 id: 154 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '154'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '154'
 id: 155 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '155'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '155'
 id: 156 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '156'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '156'
 id: 157 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '157'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '157'
 id: 158 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '158'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '158'
 id: 159 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '159'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '159'
 id: 160 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '160'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '160'

 id: 161 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '161'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '161'
 id: 162 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '162'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '162'
 id: 163 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '163'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '163'
 id: 164 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '164'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '164'
 id: 165 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '165'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '165'
 id: 166 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '166'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '166'
 id: 167 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '167'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '167'
 id: 168 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '168'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '168'
 id: 169 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '169'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '169'
 id: 170 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '170'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '170'
 id: 171 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '171'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '171'
 id: 172 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '172'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '172'
 id: 173 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '173'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '173'
 id: 174 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '174'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '174'
 id: 175 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '175'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '175'
 id: 176 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '176'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '176'
 id: 177 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '177'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '177'
 id: 178 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '178'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '178'
 id: 179 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '179'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '179'
 id: 180 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '180'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '180'
 id: 181 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '181'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '181'
 id: 182 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '182'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '182'
 id: 183 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '183'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '183'
 id: 184 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '184'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '184'
 id: 185 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '185'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '185'
 id: 186 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '186'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '186'
 id: 187 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '187'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '187'
 id: 188 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '188'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '188'
 id: 189 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '189'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '189'
 id: 190 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '190'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '190'
 id: 191 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '191'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '191'
 id: 192 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '192'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '192'
 id: 193 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '193'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '193'
 id: 194 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '194'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '194'
 id: 195 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '195'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '195'
 id: 196 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '196'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '196'
 id: 197 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '197'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '197'
 id: 198 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '198'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '198'
 id: 199 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '199'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '199'
 id: 200 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '200'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '200'
 id: 201 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '201'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '201'
 id: 202 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '202'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '202'
 id: 203 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '203'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '203'
 id: 204 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '204'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '204'
 id: 205 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '205'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '205'
 id: 206 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '206'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '206'
 id: 207 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '207'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '207'
 id: 208 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '208'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '208'
 id: 209 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '209'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '209'
 id: 210 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '210'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '210'
 id: 211 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '211'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '211'
 id: 212 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '212'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '212'
 id: 213 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '213'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '213'
 id: 214 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '214'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '214'
 id: 215 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '215'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '215'
 id: 216 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '216'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '216'
 id: 217 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '217'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '217'
 id: 218 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '218'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '218'
 id: 219 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '219'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '219'
 id: 220 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '220'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '220'
 id: 221 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '221'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '221'
 id: 222 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '222'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '222'
 id: 223 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '223'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '223'
 id: 224 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '224'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '224'
 id: 225 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '225'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '225'
 id: 226 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '226'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '226'
 id: 227 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '227'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '227'
 id: 228 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '228'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '228'
 id: 229 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '229'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '229'
 id: 230 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '230'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '230'
 id: 231 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '231'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '231'
 id: 232 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '232'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '232'
 id: 233 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '233'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '233'
 id: 234 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '234'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '234'
 id: 235 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '235'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '235'
 id: 236 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '236'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '236'
 id: 237 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '237'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '237'
 id: 238 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '238'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '238'
 id: 239 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '239'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '239'
 id: 240 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '240'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '240'
 id: 241 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '241'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '241'
 id: 242 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '242'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '242'
 id: 243 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '243'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '243'
 id: 244 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '244'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '244'
 id: 245 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '245'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '245'
 id: 246 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '246'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '246'
 id: 247 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '247'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '247'
 id: 248 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '248'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '248'
 id: 249 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '249'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '249'
 id: 250 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '250'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '250'
 id: 251 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '251'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '251'
 id: 252 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '252'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '252'
 id: 253 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '253'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '253'
 id: 254 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '254'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '254'
 id: 255 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '255'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '255'
 id: 256 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '256'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '256'
 id: 257 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '257'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '257'
 id: 258 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '258'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '258'
 id: 259 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '259'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '259'
 id: 260 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '260'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '260'
 id: 261 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '261'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '261'
 id: 262 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '262'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '262'
 id: 263 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '263'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '263'
 id: 264 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '264'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '264'
 id: 265 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '265'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '265'
 id: 266 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '266'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '266'
 id: 267 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '267'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '267'
 id: 268 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '268'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '268'
 id: 269 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '269'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '269'
 id: 270 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '270'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '270'
 id: 271 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '271'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '271'
 id: 272 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '272'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '272'
 id: 273 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '273'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '273'
 id: 274 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '274'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '274'
 id: 275 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '275'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '275'
 id: 276 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '276'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '276'
 id: 277 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '277'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '277'
 id: 278 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '278'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '278'
 id: 279 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '279'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '279'
 id: 280 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '280'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '280'
 id: 281 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '281'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '281'
 id: 282 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '282'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '282'
 id: 283 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '283'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '283'
 id: 284 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '284'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '284'
 id: 285 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '285'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '285'
 id: 286 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '286'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '286'
 id: 287 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '287'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '287'
 id: 288 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '288'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '288'
 id: 289 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '289'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '289'
 id: 290 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '290'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '290'
 id: 291 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '291'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '291'
 id: 292 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '292'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '292'
 id: 293 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '293'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '293'
 id: 294 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '294'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '294'
 id: 295 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '295'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '295'
 id: 296 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '296'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '296'
 id: 297 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '297'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '297'
 id: 298 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '298'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '298'
 id: 299 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '299'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '299'
 id: 300 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '300'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '300'
 id: 301 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '301'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '301'
 id: 302 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '302'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '302'
 id: 303 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '303'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '303'
 id: 304 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '304'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '304'
 id: 305 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '305'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '305'
 id: 306 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '306'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '306'
 id: 307 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '307'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '307'
 id: 308 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '308'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '308'
 id: 309 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '309'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '309'
 id: 310 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '310'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '310'
 id: 311 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '311'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '311'
 id: 312 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '312'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '312'
 id: 313 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '313'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '313'
 id: 314 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '314'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '314'
 id: 315 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '315'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '315'
 id: 316 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '316'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '316'
 id: 317 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '317'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '317'
 id: 318 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '318'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '318'
 id: 319 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '319'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '319'
 id: 320 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '320'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '320'
 id: 321 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '321'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '321'
 id: 322 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '322'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '322'
 id: 323 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '323'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '323'
 id: 324 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '324'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '324'
 id: 325 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '325'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '325'
 id: 326 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '326'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '326'
 id: 327 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '327'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '327'
 id: 328 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '328'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '328'
 id: 329 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '329'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '329'
 id: 330 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '330'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '330'
 id: 331 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '331'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '331'
 id: 332 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '332'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '332'
 id: 333 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '333'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '333'
 id: 334 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '334'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '334'
 id: 335 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '335'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '335'
 id: 336 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '336'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '336'
 id: 337 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '337'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '337'
 id: 338 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '338'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '338'
 id: 339 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '339'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '339'
 id: 340 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '340'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '340'
 id: 341 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '341'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '341'
 id: 342 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '342'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '342'
 id: 343 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '343'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '343'
 id: 344 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '344'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '344'
 id: 345 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '345'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '345'
 id: 346 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '346'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '346'
 id: 347 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '347'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '347'
 id: 348 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '348'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '348'
 id: 349 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '349'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '349'
 id: 350 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '350'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '350'
 id: 351 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '351'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '351'
 id: 352 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '352'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '352'
 id: 353 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '353'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '353'
 id: 354 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '354'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '354'
 id: 355 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '355'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '355'
 id: 356 // word: 57
UPDATE job_vacancies SET domain_id =  '57' where raw_id = '356'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '356'
 id: 357 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '357'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '357'
 id: 358 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '358'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '358'
 id: 359 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '359'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '359'
 id: 360 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '360'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '360'
 id: 361 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '361'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '361'
 id: 362 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '362'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '362'
 id: 363 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '363'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '363'
 id: 364 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '364'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '364'
 id: 365 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '365'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '365'
 id: 366 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '366'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '366'
 id: 367 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '367'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '367'
 id: 368 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '368'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '368'
 id: 369 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '369'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '369'
 id: 370 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '370'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '370'
 id: 371 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '371'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '371'
 id: 372 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '372'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '372'
 id: 373 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '373'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '373'

 id: 374 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '374'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '374'
 id: 375 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '375'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '375'
 id: 376 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '376'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '376'
 id: 377 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '377'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '377'
 id: 378 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '378'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '378'
 id: 379 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '379'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '379'
 id: 380 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '380'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '380'
 id: 381 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '381'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '381'
 id: 382 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '382'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '382'
 id: 383 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '383'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '383'
 id: 384 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '384'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '384'
 id: 385 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '385'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '385'
 id: 386 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '386'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '386'
 id: 387 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '387'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '387'
 id: 388 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '388'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '388'
 id: 389 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '389'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '389'
 id: 390 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '390'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '390'
 id: 391 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '391'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '391'
 id: 392 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '392'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '392'
 id: 393 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '393'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '393'
 id: 394 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '394'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '394'
 id: 395 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '395'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '395'
 id: 396 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '396'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '396'
 id: 397 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '397'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '397'
 id: 398 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '398'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '398'
 id: 399 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '399'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '399'
 id: 400 // word: 66
UPDATE job_vacancies SET domain_id =  '66' where raw_id = '400'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '400'
 id: 401 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '401'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '401'
 id: 402 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '402'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '402'
 id: 403 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '403'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '403'
 id: 404 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '404'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '404'
 id: 405 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '405'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '405'
 id: 406 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '406'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '406'
 id: 407 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '407'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '407'
 id: 408 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '408'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '408'
 id: 409 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '409'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '409'
 id: 410 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '410'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '410'
 id: 411 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '411'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '411'
 id: 412 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '412'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '412'
 id: 413 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '413'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '413'
 id: 414 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '414'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '414'
 id: 415 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '415'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '415'
 id: 416 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '416'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '416'
 id: 417 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '417'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '417'
 id: 418 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '418'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '418'
 id: 419 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '419'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '419'
 id: 420 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '420'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '420'
 id: 421 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '421'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '421'
 id: 422 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '422'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '422'
 id: 423 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '423'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '423'
 id: 424 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '424'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '424'
 id: 425 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '425'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '425'
 id: 426 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '426'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '426'
 id: 427 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '427'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '427'
 id: 428 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '428'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '428'
 id: 429 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '429'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '429'
 id: 430 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '430'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '430'
 id: 431 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '431'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '431'
 id: 432 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '432'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '432'
 id: 433 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '433'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '433'
 id: 434 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '434'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '434'
 id: 435 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '435'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '435'
 id: 436 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '436'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '436'
 id: 437 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '437'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '437'
 id: 438 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '438'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '438'
 id: 439 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '439'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '439'
 id: 440 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '440'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '440'
 id: 441 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '441'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '441'
 id: 442 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '442'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '442'
 id: 443 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '443'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '443'
 id: 444 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '444'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '444'
 id: 445 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '445'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '445'
 id: 446 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '446'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '446'
 id: 447 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '447'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '447'
 id: 448 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '448'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '448'
 id: 449 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '449'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '449'
 id: 450 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '450'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '450'
 id: 451 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '451'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '451'
 id: 452 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '452'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '452'
 id: 453 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '453'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '453'
 id: 454 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '454'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '454'
 id: 455 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '455'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '455'
 id: 456 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '456'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '456'
 id: 457 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '457'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '457'
 id: 458 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '458'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '458'
 id: 459 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '459'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '459'
 id: 460 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '460'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '460'
 id: 461 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '461'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '461'
 id: 462 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '462'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '462'
 id: 463 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '463'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '463'
 id: 464 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '464'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '464'
 id: 465 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '465'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '465'
 id: 466 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '466'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '466'
 id: 467 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '467'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '467'
 id: 468 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '468'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '468'
 id: 469 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '469'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '469'
 id: 470 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '470'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '470'
 id: 471 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '471'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '471'
 id: 472 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '472'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '472'
 id: 473 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '473'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '473'
 id: 474 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '474'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '474'
 id: 475 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '475'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '475'
 id: 476 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '476'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '476'
 id: 477 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '477'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '477'
 id: 478 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '478'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '478'
 id: 479 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '479'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '479'

 id: 480 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '480'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '480'
 id: 481 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '481'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '481'
 id: 482 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '482'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '482'
 id: 483 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '483'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '483'
 id: 484 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '484'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '484'
 id: 485 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '485'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '485'
 id: 486 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '486'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '486'
 id: 487 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '487'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '487'
 id: 488 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '488'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '488'
 id: 489 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '489'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '489'
 id: 490 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '490'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '490'
 id: 491 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '491'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '491'
 id: 492 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '492'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '492'
 id: 493 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '493'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '493'
 id: 494 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '494'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '494'
 id: 495 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '495'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '495'
 id: 496 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '496'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '496'
 id: 497 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '497'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '497'
 id: 498 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '498'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '498'
 id: 499 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '499'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '499'
 id: 500 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '500'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '500'
 id: 501 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '501'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '501'
 id: 502 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '502'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '502'
 id: 503 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '503'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '503'
 id: 504 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '504'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '504'
 id: 505 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '505'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '505'
 id: 506 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '506'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '506'
 id: 507 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '507'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '507'
 id: 508 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '508'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '508'
 id: 509 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '509'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '509'
 id: 510 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '510'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '510'
 id: 511 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '511'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '511'
 id: 512 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '512'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '512'
 id: 513 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '513'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '513'
 id: 514 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '514'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '514'
 id: 515 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '515'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '515'
 id: 516 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '516'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '516'
 id: 517 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '517'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '517'
 id: 518 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '518'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '518'
 id: 519 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '519'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '519'
 id: 520 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '520'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '520'
 id: 521 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '521'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '521'
 id: 522 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '522'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '522'
 id: 523 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '523'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '523'
 id: 524 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '524'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '524'
 id: 525 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '525'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '525'
 id: 526 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '526'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '526'
 id: 527 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '527'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '527'
 id: 528 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '528'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '528'
 id: 529 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '529'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '529'
 id: 530 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '530'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '530'
 id: 531 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '531'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '531'
 id: 532 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '532'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '532'
 id: 533 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '533'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '533'
 id: 534 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '534'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '534'

 id: 535 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '535'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '535'
 id: 536 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '536'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '536'
 id: 537 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '537'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '537'
 id: 538 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '538'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '538'
 id: 539 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '539'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '539'
 id: 540 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '540'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '540'
 id: 541 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '541'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '541'
 id: 542 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '542'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '542'
 id: 543 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '543'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '543'
 id: 544 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '544'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '544'
 id: 545 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '545'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '545'
 id: 546 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '546'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '546'
 id: 547 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '547'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '547'
 id: 548 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '548'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '548'
 id: 549 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '549'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '549'
 id: 550 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '550'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '550'
 id: 551 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '551'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '551'
 id: 552 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '552'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '552'
 id: 553 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '553'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '553'
 id: 554 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '554'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '554'
 id: 555 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '555'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '555'
 id: 556 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '556'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '556'
 id: 557 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '557'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '557'
 id: 558 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '558'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '558'
 id: 559 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '559'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '559'
 id: 560 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '560'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '560'
 id: 561 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '561'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '561'
 id: 562 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '562'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '562'
 id: 563 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '563'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '563'
 id: 564 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '564'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '564'
 id: 565 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '565'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '565'
 id: 566 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '566'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '566'
 id: 567 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '567'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '567'
 id: 568 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '568'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '568'
 id: 569 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '569'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '569'
 id: 570 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '570'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '570'
 id: 571 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '571'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '571'
 id: 572 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '572'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '572'
 id: 573 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '573'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '573'
 id: 574 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '574'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '574'
 id: 575 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '575'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '575'
 id: 576 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '576'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '576'
 id: 577 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '577'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '577'
 id: 578 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '578'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '578'
 id: 579 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '579'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '579'
 id: 580 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '580'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '580'
 id: 581 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '581'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '581'
 id: 582 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '582'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '582'
 id: 583 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '583'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '583'
 id: 584 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '584'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '584'
 id: 585 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '585'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '585'
 id: 586 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '586'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '586'
 id: 587 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '587'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '587'
 id: 588 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '588'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '588'
 id: 589 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '589'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '589'
 id: 590 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '590'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '590'
 id: 591 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '591'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '591'
 id: 592 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '592'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '592'
 id: 593 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '593'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '593'
 id: 594 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '594'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '594'
 id: 595 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '595'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '595'
 id: 596 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '596'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '596'
 id: 597 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '597'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '597'
 id: 598 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '598'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '598'
 id: 599 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '599'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '599'
 id: 600 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '600'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '600'
 id: 601 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '601'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '601'
 id: 602 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '602'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '602'
 id: 603 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '603'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '603'
 id: 604 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '604'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '604'
 id: 605 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '605'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '605'
 id: 606 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '606'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '606'
 id: 607 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '607'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '607'
 id: 608 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '608'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '608'
 id: 609 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '609'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '609'
 id: 610 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '610'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '610'
 id: 611 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '611'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '611'
 id: 612 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '612'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '612'
 id: 613 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '613'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '613'
 id: 614 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '614'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '614'
 id: 615 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '615'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '615'
 id: 616 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '616'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '616'
 id: 617 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '617'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '617'
 id: 618 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '618'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '618'
 id: 619 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '619'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '619'
 id: 620 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '620'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '620'
 id: 621 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '621'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '621'
 id: 622 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '622'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '622'
 id: 623 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '623'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '623'
 id: 624 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '624'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '624'
 id: 625 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '625'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '625'
 id: 626 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '626'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '626'
 id: 627 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '627'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '627'
 id: 628 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '628'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '628'
 id: 629 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '629'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '629'
 id: 630 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '630'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '630'
 id: 631 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '631'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '631'
 id: 632 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '632'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '632'
 id: 633 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '633'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '633'
 id: 634 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '634'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '634'
 id: 635 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '635'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '635'
 id: 636 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '636'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '636'
 id: 637 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '637'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '637'
 id: 638 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '638'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '638'
 id: 639 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '639'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '639'
 id: 640 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '640'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '640'
 id: 641 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '641'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '641'
 id: 642 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '642'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '642'
 id: 643 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '643'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '643'
 id: 644 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '644'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '644'
 id: 645 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '645'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '645'
 id: 646 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '646'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '646'
 id: 647 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '647'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '647'
 id: 648 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '648'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '648'
 id: 649 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '649'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '649'
 id: 650 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '650'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '650'
 id: 651 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '651'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '651'
 id: 652 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '652'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '652'
 id: 653 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '653'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '653'
 id: 654 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '654'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '654'
 id: 655 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '655'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '655'
 id: 656 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '656'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '656'
 id: 657 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '657'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '657'
 id: 658 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '658'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '658'
 id: 659 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '659'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '659'
 id: 660 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '660'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '660'
 id: 661 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '661'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '661'
 id: 662 // word: 28
UPDATE job_vacancies SET domain_id =  '28' where raw_id = '662'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '662'
 id: 663 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '663'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '663'
 id: 664 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '664'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '664'
 id: 665 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '665'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '665'
 id: 666 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '666'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '666'
 id: 667 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '667'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '667'
 id: 668 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '668'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '668'
 id: 669 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '669'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '669'
 id: 670 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '670'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '670'
 id: 671 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '671'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '671'
 id: 672 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '672'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '672'
 id: 673 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '673'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '673'
 id: 674 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '674'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '674'
 id: 675 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '675'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '675'
 id: 676 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '676'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '676'
 id: 677 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '677'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '677'
 id: 678 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '678'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '678'
 id: 679 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '679'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '679'
 id: 680 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '680'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '680'
 id: 681 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '681'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '681'
 id: 682 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '682'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '682'
 id: 683 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '683'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '683'
 id: 684 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '684'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '684'
 id: 685 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '685'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '685'
 id: 686 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '686'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '686'
 id: 687 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '687'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '687'
 id: 688 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '688'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '688'
 id: 689 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '689'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '689'
 id: 690 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '690'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '690'
 id: 691 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '691'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '691'
 id: 692 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '692'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '692'
 id: 693 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '693'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '693'
 id: 694 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '694'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '694'

 id: 695 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '695'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '695'
 id: 696 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '696'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '696'
 id: 697 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '697'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '697'
 id: 698 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '698'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '698'
 id: 699 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '699'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '699'
 id: 700 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '700'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '700'
 id: 701 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '701'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '701'
 id: 702 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '702'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '702'
 id: 703 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '703'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '703'
 id: 704 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '704'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '704'
 id: 705 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '705'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '705'
 id: 706 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '706'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '706'
 id: 707 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '707'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '707'
 id: 708 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '708'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '708'
 id: 709 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '709'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '709'
 id: 710 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '710'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '710'
 id: 711 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '711'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '711'
 id: 712 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '712'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '712'
 id: 713 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '713'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '713'
 id: 714 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '714'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '714'
 id: 715 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '715'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '715'
 id: 716 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '716'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '716'
 id: 717 // word: 52
UPDATE job_vacancies SET domain_id =  '52' where raw_id = '717'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '717'
 id: 718 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '718'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '718'
 id: 719 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '719'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '719'
 id: 720 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '720'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '720'
 id: 721 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '721'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '721'
 id: 722 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '722'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '722'
 id: 723 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '723'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '723'
 id: 724 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '724'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '724'
 id: 725 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '725'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '725'
 id: 726 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '726'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '726'
 id: 727 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '727'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '727'
 id: 728 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '728'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '728'
 id: 729 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '729'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '729'
 id: 730 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '730'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '730'
 id: 731 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '731'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '731'
 id: 732 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '732'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '732'
 id: 733 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '733'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '733'
 id: 734 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '734'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '734'
 id: 735 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '735'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '735'
 id: 736 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '736'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '736'
 id: 737 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '737'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '737'
 id: 738 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '738'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '738'
 id: 739 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '739'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '739'
 id: 740 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '740'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '740'
 id: 741 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '741'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '741'
 id: 742 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '742'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '742'
 id: 743 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '743'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '743'
 id: 744 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '744'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '744'
 id: 745 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '745'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '745'
 id: 746 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '746'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '746'
 id: 747 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '747'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '747'

 id: 748 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '748'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '748'
 id: 749 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '749'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '749'
 id: 750 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '750'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '750'
 id: 751 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '751'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '751'
 id: 752 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '752'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '752'
 id: 753 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '753'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '753'
 id: 754 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '754'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '754'
 id: 755 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '755'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '755'
 id: 756 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '756'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '756'
 id: 757 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '757'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '757'
 id: 758 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '758'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '758'
 id: 759 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '759'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '759'
 id: 760 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '760'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '760'
 id: 761 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '761'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '761'
 id: 762 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '762'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '762'
 id: 763 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '763'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '763'
 id: 764 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '764'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '764'
 id: 765 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '765'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '765'
 id: 766 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '766'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '766'
 id: 767 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '767'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '767'
 id: 768 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '768'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '768'
 id: 769 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '769'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '769'
 id: 770 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '770'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '770'
 id: 771 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '771'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '771'
 id: 772 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '772'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '772'
 id: 773 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '773'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '773'
 id: 774 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '774'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '774'
 id: 775 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '775'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '775'
 id: 776 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '776'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '776'
 id: 777 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '777'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '777'
 id: 778 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '778'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '778'
 id: 779 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '779'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '779'
 id: 780 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '780'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '780'
 id: 781 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '781'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '781'
 id: 782 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '782'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '782'
 id: 783 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '783'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '783'
 id: 784 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '784'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '784'
 id: 785 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '785'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '785'
 id: 786 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '786'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '786'
 id: 787 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '787'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '787'
 id: 788 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '788'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '788'
 id: 789 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '789'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '789'
 id: 790 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '790'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '790'
 id: 791 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '791'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '791'
 id: 792 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '792'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '792'
 id: 793 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '793'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '793'
 id: 794 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '794'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '794'
 id: 795 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '795'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '795'
 id: 796 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '796'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '796'
 id: 797 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '797'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '797'
 id: 798 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '798'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '798'
 id: 799 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '799'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '799'
 id: 800 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '800'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '800'
 id: 801 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '801'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '801'

 id: 802 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '802'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '802'
 id: 803 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '803'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '803'
 id: 804 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '804'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '804'
 id: 805 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '805'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '805'
 id: 806 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '806'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '806'
 id: 807 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '807'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '807'
 id: 808 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '808'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '808'
 id: 809 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '809'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '809'
 id: 810 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '810'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '810'
 id: 811 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '811'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '811'
 id: 812 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '812'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '812'
 id: 813 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '813'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '813'
 id: 814 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '814'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '814'
 id: 815 // word: 66
UPDATE job_vacancies SET domain_id =  '66' where raw_id = '815'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '815'
 id: 816 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '816'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '816'
 id: 817 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '817'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '817'
 id: 818 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '818'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '818'
 id: 819 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '819'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '819'
 id: 820 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '820'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '820'
 id: 821 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '821'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '821'
 id: 822 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '822'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '822'
 id: 823 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '823'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '823'
 id: 824 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '824'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '824'
 id: 825 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '825'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '825'
 id: 826 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '826'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '826'
 id: 827 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '827'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '827'
 id: 828 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '828'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '828'
 id: 829 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '829'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '829'
 id: 830 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '830'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '830'
 id: 831 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '831'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '831'
 id: 832 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '832'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '832'
 id: 833 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '833'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '833'
 id: 834 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '834'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '834'
 id: 835 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '835'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '835'
 id: 836 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '836'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '836'
 id: 837 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '837'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '837'
 id: 838 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '838'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '838'
 id: 839 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '839'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '839'
 id: 840 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '840'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '840'
 id: 841 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '841'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '841'
 id: 842 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '842'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '842'
 id: 843 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '843'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '843'
 id: 844 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '844'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '844'
 id: 845 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '845'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '845'
 id: 846 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '846'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '846'
 id: 847 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '847'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '847'
 id: 848 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '848'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '848'
 id: 849 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '849'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '849'
 id: 850 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '850'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '850'
 id: 851 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '851'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '851'
 id: 852 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '852'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '852'
 id: 853 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '853'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '853'
 id: 854 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '854'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '854'
 id: 855 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '855'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '855'
 id: 856 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '856'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '856'
 id: 857 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '857'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '857'
 id: 858 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '858'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '858'
 id: 859 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '859'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '859'
 id: 860 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '860'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '860'
 id: 861 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '861'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '861'
 id: 862 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '862'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '862'
 id: 863 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '863'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '863'
 id: 864 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '864'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '864'
 id: 865 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '865'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '865'
 id: 866 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '866'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '866'
 id: 867 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '867'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '867'
 id: 868 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '868'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '868'
 id: 869 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '869'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '869'
 id: 870 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '870'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '870'
 id: 871 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '871'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '871'
 id: 872 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '872'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '872'
 id: 873 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '873'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '873'
 id: 874 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '874'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '874'
 id: 875 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '875'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '875'
 id: 876 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '876'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '876'
 id: 877 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '877'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '877'
 id: 878 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '878'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '878'
 id: 879 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '879'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '879'
 id: 880 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '880'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '880'
 id: 881 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '881'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '881'
 id: 882 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '882'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '882'
 id: 883 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '883'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '883'
 id: 884 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '884'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '884'
 id: 885 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '885'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '885'
 id: 886 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '886'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '886'
 id: 887 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '887'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '887'
 id: 888 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '888'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '888'
 id: 889 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '889'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '889'
 id: 890 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '890'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '890'
 id: 891 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '891'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '891'
 id: 892 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '892'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '892'
 id: 893 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '893'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '893'
 id: 894 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '894'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '894'
 id: 895 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '895'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '895'
 id: 896 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '896'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '896'
 id: 897 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '897'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '897'
 id: 898 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '898'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '898'
 id: 899 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '899'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '899'
 id: 900 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '900'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '900'
 id: 901 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '901'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '901'
 id: 902 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '902'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '902'
 id: 903 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '903'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '903'
 id: 904 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '904'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '904'
 id: 905 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '905'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '905'
 id: 906 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '906'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '906'
 id: 907 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '907'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '907'
 id: 908 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '908'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '908'
 id: 909 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '909'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '909'
 id: 910 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '910'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '910'

 id: 911 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '911'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '911'
 id: 912 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '912'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '912'
 id: 913 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '913'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '913'
 id: 914 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '914'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '914'
 id: 915 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '915'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '915'
 id: 916 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '916'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '916'
 id: 917 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '917'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '917'
 id: 918 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '918'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '918'
 id: 919 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '919'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '919'
 id: 920 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '920'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '920'
 id: 921 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '921'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '921'
 id: 922 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '922'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '922'
 id: 923 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '923'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '923'
 id: 924 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '924'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '924'
 id: 925 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '925'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '925'
 id: 926 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '926'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '926'
 id: 927 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '927'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '927'
 id: 928 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '928'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '928'
 id: 929 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '929'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '929'
 id: 930 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '930'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '930'
 id: 931 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '931'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '931'
 id: 932 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '932'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '932'
 id: 933 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '933'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '933'
 id: 934 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '934'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '934'
 id: 935 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '935'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '935'
 id: 936 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '936'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '936'
 id: 937 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '937'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '937'
 id: 938 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '938'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '938'
 id: 939 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '939'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '939'
 id: 940 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '940'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '940'
 id: 941 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '941'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '941'
 id: 942 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '942'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '942'
 id: 943 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '943'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '943'
 id: 944 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '944'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '944'
 id: 945 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '945'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '945'
 id: 946 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '946'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '946'
 id: 947 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '947'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '947'
 id: 948 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '948'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '948'
 id: 949 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '949'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '949'
 id: 950 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '950'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '950'
 id: 951 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '951'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '951'
 id: 952 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '952'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '952'
 id: 953 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '953'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '953'
 id: 954 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '954'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '954'
 id: 955 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '955'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '955'
 id: 956 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '956'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '956'
 id: 957 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '957'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '957'
 id: 958 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '958'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '958'
 id: 959 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '959'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '959'
 id: 960 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '960'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '960'
 id: 961 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '961'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '961'
 id: 962 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '962'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '962'
 id: 963 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '963'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '963'
 id: 964 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '964'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '964'
 id: 965 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '965'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '965'
 id: 966 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '966'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '966'
 id: 967 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '967'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '967'
 id: 968 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '968'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '968'
 id: 969 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '969'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '969'
 id: 970 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '970'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '970'
 id: 971 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '971'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '971'
 id: 972 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '972'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '972'
 id: 973 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '973'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '973'
 id: 974 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '974'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '974'
 id: 975 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '975'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '975'
 id: 976 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '976'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '976'
 id: 977 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '977'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '977'
 id: 978 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '978'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '978'
 id: 979 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '979'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '979'
 id: 980 // word: 52
UPDATE job_vacancies SET domain_id =  '52' where raw_id = '980'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '980'
 id: 981 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '981'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '981'
 id: 982 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '982'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '982'
 id: 983 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '983'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '983'
 id: 984 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '984'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '984'
 id: 985 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '985'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '985'
 id: 986 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '986'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '986'
 id: 987 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '987'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '987'
 id: 988 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '988'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '988'
 id: 989 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '989'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '989'
 id: 990 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '990'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '990'
 id: 991 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '991'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '991'
 id: 992 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '992'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '992'
 id: 993 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '993'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '993'
 id: 994 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '994'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '994'
 id: 995 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '995'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '995'
 id: 996 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '996'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '996'
 id: 997 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '997'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '997'
 id: 998 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '998'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '998'
 id: 999 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '999'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '999'
 id: 1000 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '1000'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1000'
 id: 1001 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '1001'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1001'
 id: 1002 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1002'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1002'
 id: 1003 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1003'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1003'
 id: 1004 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '1004'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1004'
 id: 1005 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '1005'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1005'
 id: 1006 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1006'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1006'
 id: 1007 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1007'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1007'
 id: 1008 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '1008'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1008'
 id: 1009 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '1009'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1009'
 id: 1010 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1010'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1010'
 id: 1011 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1011'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1011'
 id: 1012 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1012'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1012'
 id: 1013 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '1013'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1013'
 id: 1014 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1014'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1014'
 id: 1015 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '1015'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1015'
 id: 1016 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '1016'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1016'
 id: 1017 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '1017'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1017'
 id: 1018 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1018'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1018'
 id: 1019 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1019'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1019'

 id: 1020 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '1020'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1020'
 id: 1021 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '1021'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1021'
 id: 1022 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '1022'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1022'
 id: 1023 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '1023'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1023'
 id: 1024 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '1024'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1024'
 id: 1025 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1025'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1025'
 id: 1026 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1026'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1026'
 id: 1027 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1027'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1027'
 id: 1028 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '1028'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1028'
 id: 1029 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '1029'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1029'
 id: 1030 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1030'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1030'
 id: 1031 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1031'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1031'
 id: 1032 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1032'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1032'
 id: 1033 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '1033'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1033'
 id: 1034 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '1034'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1034'
 id: 1035 // word: 52
UPDATE job_vacancies SET domain_id =  '52' where raw_id = '1035'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1035'
 id: 1036 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1036'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1036'
 id: 1037 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '1037'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1037'
 id: 1038 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1038'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1038'
 id: 1039 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1039'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1039'
 id: 1040 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '1040'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1040'
 id: 1041 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1041'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1041'
 id: 1042 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1042'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1042'
 id: 1043 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '1043'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1043'
 id: 1044 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1044'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1044'
 id: 1045 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '1045'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1045'
 id: 1046 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '1046'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1046'
 id: 1047 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1047'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1047'
 id: 1048 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1048'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1048'
 id: 1049 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '1049'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1049'
 id: 1050 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1050'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1050'
 id: 1051 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1051'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1051'
 id: 1052 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '1052'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1052'
 id: 1053 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1053'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1053'
 id: 1054 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1054'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1054'
 id: 1055 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1055'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1055'
 id: 1056 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1056'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1056'
 id: 1057 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '1057'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1057'
 id: 1058 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1058'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1058'
 id: 1059 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1059'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1059'
 id: 1060 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1060'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1060'
 id: 1061 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '1061'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1061'
 id: 1062 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '1062'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1062'
 id: 1063 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '1063'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1063'
 id: 1064 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1064'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1064'
 id: 1065 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '1065'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1065'
 id: 1066 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '1066'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1066'
 id: 1067 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '1067'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1067'
 id: 1068 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1068'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1068'
 id: 1069 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '1069'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1069'
 id: 1070 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '1070'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1070'
 id: 1071 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1071'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1071'
 id: 1072 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '1072'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1072'
 id: 1073 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1073'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1073'
 id: 1074 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '1074'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1074'
 id: 1075 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1075'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1075'
 id: 1076 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '1076'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1076'
 id: 1077 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1077'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1077'
 id: 1078 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1078'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1078'
 id: 1079 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '1079'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1079'
 id: 1080 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1080'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1080'
 id: 1081 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '1081'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1081'
 id: 1082 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '1082'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1082'
 id: 1083 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1083'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1083'
 id: 1084 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '1084'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1084'
 id: 1085 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1085'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1085'
 id: 1086 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '1086'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1086'
 id: 1087 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '1087'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1087'
 id: 1088 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '1088'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1088'
 id: 1089 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '1089'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1089'
 id: 1090 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '1090'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1090'
 id: 1091 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '1091'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1091'
 id: 1092 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1092'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1092'
 id: 1093 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1093'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1093'
 id: 1094 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1094'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1094'
 id: 1095 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '1095'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1095'
 id: 1096 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '1096'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1096'
 id: 1097 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '1097'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1097'
 id: 1098 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '1098'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1098'
 id: 1099 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1099'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1099'
 id: 1100 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '1100'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1100'
 id: 1101 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1101'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1101'
 id: 1102 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '1102'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1102'
 id: 1103 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1103'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1103'
 id: 1104 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '1104'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1104'
 id: 1105 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '1105'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1105'
 id: 1106 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '1106'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1106'
 id: 1107 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '1107'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1107'
 id: 1108 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1108'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1108'
 id: 1109 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1109'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1109'
 id: 1110 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '1110'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1110'
 id: 1111 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1111'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1111'
 id: 1112 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1112'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1112'
 id: 1113 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '1113'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1113'
 id: 1114 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '1114'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1114'
 id: 1115 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '1115'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1115'
 id: 1116 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '1116'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1116'
 id: 1117 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1117'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1117'
 id: 1118 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1118'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1118'
 id: 1119 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '1119'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1119'
 id: 1120 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '1120'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1120'
 id: 1121 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1121'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1121'
 id: 1122 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1122'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1122'
 id: 1123 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1123'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1123'
 id: 1124 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '1124'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1124'
 id: 1125 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '1125'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1125'
 id: 1126 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '1126'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1126'
 id: 1127 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '1127'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1127'
 id: 1128 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1128'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1128'
 id: 1129 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1129'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1129'
 id: 1130 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '1130'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1130'
 id: 1131 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1131'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1131'
 id: 1132 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1132'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1132'
 id: 1133 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '1133'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1133'
 id: 1134 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1134'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1134'
 id: 1135 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '1135'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1135'
 id: 1136 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '1136'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1136'
 id: 1137 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1137'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1137'
 id: 1138 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1138'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1138'
 id: 1139 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '1139'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1139'
 id: 1140 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '1140'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1140'
 id: 1141 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1141'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1141'
 id: 1142 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '1142'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1142'
 id: 1143 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1143'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1143'
 id: 1144 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1144'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1144'
 id: 1145 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '1145'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1145'
 id: 1146 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1146'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1146'
 id: 1147 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1147'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1147'
 id: 1148 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '1148'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1148'
 id: 1149 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '1149'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1149'
 id: 1150 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '1150'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1150'
 id: 1151 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1151'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1151'
 id: 1152 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '1152'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1152'
 id: 1153 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '1153'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1153'
 id: 1154 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1154'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1154'
 id: 1155 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '1155'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1155'
 id: 1156 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1156'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1156'
 id: 1157 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '1157'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1157'
 id: 1158 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '1158'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1158'
 id: 1159 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '1159'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1159'
 id: 1160 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '1160'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1160'
 id: 1161 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1161'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1161'
 id: 1162 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '1162'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1162'
 id: 1163 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1163'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1163'
 id: 1164 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '1164'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1164'
 id: 1165 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '1165'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1165'
 id: 1166 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1166'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1166'
 id: 1167 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '1167'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1167'
 id: 1168 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1168'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1168'
 id: 1169 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1169'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1169'
 id: 1170 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '1170'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1170'
 id: 1171 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '1171'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1171'
 id: 1172 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1172'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1172'
 id: 1173 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '1173'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1173'
 id: 1174 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1174'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1174'
 id: 1175 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '1175'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1175'

 id: 1176 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '1176'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1176'
 id: 1177 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '1177'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1177'
 id: 1178 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '1178'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1178'
 id: 1179 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1179'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1179'
 id: 1180 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1180'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1180'
 id: 1181 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '1181'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1181'
 id: 1182 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '1182'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1182'
 id: 1183 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '1183'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1183'
 id: 1184 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '1184'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1184'
 id: 1185 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '1185'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1185'
 id: 1186 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '1186'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1186'
 id: 1187 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1187'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1187'
 id: 1188 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '1188'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1188'
 id: 1189 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '1189'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1189'
 id: 1190 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1190'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1190'
 id: 1191 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1191'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1191'
 id: 1192 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '1192'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1192'
 id: 1193 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '1193'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1193'
 id: 1194 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '1194'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1194'
 id: 1195 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '1195'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1195'
 id: 1196 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1196'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1196'
 id: 1197 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '1197'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1197'
 id: 1198 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '1198'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1198'
 id: 1199 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1199'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1199'
 id: 1200 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '1200'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1200'
 id: 1201 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '1201'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1201'
 id: 1202 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1202'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1202'
 id: 1203 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '1203'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1203'
 id: 1204 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '1204'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1204'
 id: 1205 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '1205'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1205'
 id: 1206 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '1206'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1206'
 id: 1207 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '1207'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1207'
 id: 1208 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '1208'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1208'
 id: 1209 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '1209'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1209'
 id: 1210 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '1210'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1210'
 id: 1211 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '1211'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1211'
 id: 1212 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '1212'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1212'
 id: 1213 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '1213'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1213'
 id: 1214 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '1214'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1214'
 id: 1215 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '1215'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1215'
 id: 1216 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '1216'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1216'
 id: 1217 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '1217'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1217'
 id: 1218 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '1218'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1218'
 id: 1219 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '1219'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1219'
 id: 1220 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1220'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1220'
 id: 1221 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '1221'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1221'
 id: 1222 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1222'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1222'
 id: 1223 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1223'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1223'
 id: 1224 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '1224'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1224'
 id: 1225 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '1225'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1225'
 id: 1226 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '1226'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1226'
 id: 1227 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '1227'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1227'
 id: 1228 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '1228'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1228'
 id: 1229 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '1229'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1229'
 id: 1230 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '1230'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1230'
 id: 1231 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1231'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1231'
 id: 1232 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '1232'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1232'
 id: 1233 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '1233'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1233'
 id: 1234 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '1234'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1234'
 id: 1235 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '1235'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1235'
 id: 1236 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1236'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1236'
 id: 1237 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1237'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1237'
 id: 1238 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1238'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1238'
 id: 1239 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1239'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1239'
 id: 1240 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '1240'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1240'
 id: 1241 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '1241'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1241'
 id: 1242 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1242'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1242'
 id: 1243 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '1243'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1243'
 id: 1244 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '1244'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1244'
 id: 1245 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '1245'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1245'
 id: 1246 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1246'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1246'
 id: 1247 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1247'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1247'
 id: 1248 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1248'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1248'
 id: 1249 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '1249'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1249'
 id: 1250 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1250'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1250'
 id: 1251 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1251'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1251'
 id: 1252 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '1252'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1252'
 id: 1253 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '1253'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1253'
 id: 1254 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1254'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1254'
 id: 1255 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1255'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1255'
 id: 1256 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1256'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1256'
 id: 1257 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1257'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1257'
 id: 1258 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '1258'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1258'
 id: 1259 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1259'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1259'
 id: 1260 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1260'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1260'
 id: 1261 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1261'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1261'
 id: 1262 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '1262'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1262'
 id: 1263 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '1263'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1263'
 id: 1264 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1264'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1264'
 id: 1265 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '1265'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1265'
 id: 1266 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '1266'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1266'
 id: 1267 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '1267'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1267'
 id: 1268 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1268'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1268'
 id: 1269 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1269'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1269'
 id: 1270 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '1270'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1270'
 id: 1271 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '1271'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1271'
 id: 1272 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1272'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1272'
 id: 1273 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '1273'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1273'
 id: 1274 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1274'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1274'
 id: 1275 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '1275'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1275'
 id: 1276 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1276'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1276'
 id: 1277 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '1277'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1277'

 id: 1278 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '1278'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1278'
 id: 1279 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '1279'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1279'
 id: 1280 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '1280'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1280'
 id: 1281 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '1281'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1281'
 id: 1282 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '1282'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1282'
 id: 1283 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '1283'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1283'
 id: 1284 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '1284'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1284'
 id: 1285 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1285'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1285'
 id: 1286 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '1286'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1286'
 id: 1287 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1287'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1287'
 id: 1288 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '1288'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1288'
 id: 1289 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '1289'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1289'
 id: 1290 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1290'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1290'
 id: 1291 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1291'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1291'
 id: 1292 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '1292'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1292'
 id: 1293 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '1293'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1293'
 id: 1294 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1294'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1294'
 id: 1295 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '1295'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1295'
 id: 1296 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '1296'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1296'
 id: 1297 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1297'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1297'
 id: 1298 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '1298'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1298'
 id: 1299 // word: 66
UPDATE job_vacancies SET domain_id =  '66' where raw_id = '1299'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1299'
 id: 1300 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '1300'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1300'
 id: 1301 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1301'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1301'
 id: 1302 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '1302'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1302'
 id: 1303 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '1303'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1303'
 id: 1304 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1304'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1304'
 id: 1305 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1305'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1305'
 id: 1306 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1306'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1306'
 id: 1307 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '1307'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1307'
 id: 1308 // word: 66
UPDATE job_vacancies SET domain_id =  '66' where raw_id = '1308'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1308'
 id: 1309 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1309'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1309'
 id: 1310 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1310'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1310'
 id: 1311 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '1311'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1311'
 id: 1312 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '1312'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1312'
 id: 1313 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1313'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1313'
 id: 1314 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '1314'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1314'
 id: 1315 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '1315'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1315'
 id: 1316 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '1316'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1316'
 id: 1317 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '1317'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1317'
 id: 1318 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1318'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1318'
 id: 1319 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1319'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1319'
 id: 1320 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1320'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1320'
 id: 1321 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '1321'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1321'
 id: 1322 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1322'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1322'
 id: 1323 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1323'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1323'
 id: 1324 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '1324'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1324'
 id: 1325 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1325'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1325'
 id: 1326 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '1326'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1326'
 id: 1327 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '1327'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1327'
 id: 1328 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '1328'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1328'
 id: 1329 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1329'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1329'
 id: 1330 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1330'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1330'
 id: 1331 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1331'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1331'
 id: 1332 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '1332'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1332'
 id: 1333 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1333'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1333'
 id: 1334 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '1334'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1334'
 id: 1335 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '1335'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1335'
 id: 1336 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1336'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1336'
 id: 1337 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '1337'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1337'
 id: 1338 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1338'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1338'
 id: 1339 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '1339'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1339'
 id: 1340 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1340'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1340'
 id: 1341 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1341'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1341'
 id: 1342 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1342'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1342'
 id: 1343 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1343'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1343'
 id: 1344 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '1344'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1344'
 id: 1345 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1345'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1345'
 id: 1346 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1346'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1346'
 id: 1347 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1347'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1347'
 id: 1348 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '1348'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1348'
 id: 1349 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '1349'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1349'
 id: 1350 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1350'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1350'
 id: 1351 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '1351'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1351'
 id: 1352 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1352'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1352'
 id: 1353 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1353'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1353'
 id: 1354 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1354'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1354'
 id: 1355 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '1355'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1355'
 id: 1356 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '1356'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1356'
 id: 1357 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1357'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1357'
 id: 1358 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1358'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1358'
 id: 1359 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1359'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1359'
 id: 1360 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '1360'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1360'
 id: 1361 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1361'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1361'
 id: 1362 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1362'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1362'
 id: 1363 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1363'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1363'
 id: 1364 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1364'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1364'
 id: 1365 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '1365'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1365'
 id: 1366 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '1366'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1366'
 id: 1367 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '1367'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1367'
 id: 1368 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1368'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1368'
 id: 1369 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1369'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1369'
 id: 1370 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1370'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1370'
 id: 1371 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1371'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1371'
 id: 1372 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '1372'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1372'
 id: 1373 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '1373'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1373'
 id: 1374 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1374'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1374'
 id: 1375 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '1375'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1375'
 id: 1376 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1376'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1376'
 id: 1377 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1377'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1377'
 id: 1378 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '1378'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1378'
 id: 1379 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '1379'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1379'
 id: 1380 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1380'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1380'
 id: 1381 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1381'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1381'
 id: 1382 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '1382'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1382'
 id: 1383 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1383'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1383'
 id: 1384 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '1384'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1384'
 id: 1385 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1385'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1385'
 id: 1386 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '1386'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1386'
 id: 1387 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1387'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1387'
 id: 1388 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1388'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1388'
 id: 1389 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1389'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1389'
 id: 1390 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '1390'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1390'
 id: 1391 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1391'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1391'
 id: 1392 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1392'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1392'
 id: 1393 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1393'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1393'
 id: 1394 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1394'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1394'
 id: 1395 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '1395'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1395'
 id: 1396 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1396'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1396'
 id: 1397 // word: 52
UPDATE job_vacancies SET domain_id =  '52' where raw_id = '1397'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1397'
 id: 1398 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '1398'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1398'
 id: 1399 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '1399'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1399'
 id: 1400 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1400'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1400'
 id: 1401 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '1401'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1401'
 id: 1402 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '1402'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1402'
 id: 1403 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1403'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1403'
 id: 1404 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '1404'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1404'
 id: 1405 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '1405'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1405'
 id: 1406 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1406'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1406'
 id: 1407 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1407'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1407'
 id: 1408 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1408'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1408'
 id: 1409 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1409'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1409'
 id: 1410 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '1410'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1410'
 id: 1411 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1411'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1411'
 id: 1412 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '1412'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1412'
 id: 1413 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '1413'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1413'
 id: 1414 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1414'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1414'
 id: 1415 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1415'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1415'
 id: 1416 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1416'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1416'
 id: 1417 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1417'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1417'
 id: 1418 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1418'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1418'
 id: 1419 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '1419'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1419'
 id: 1420 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '1420'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1420'
 id: 1421 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '1421'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1421'
 id: 1422 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '1422'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1422'
 id: 1423 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1423'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1423'
 id: 1424 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1424'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1424'
 id: 1425 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1425'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1425'
 id: 1426 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1426'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1426'
 id: 1427 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1427'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1427'
 id: 1428 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '1428'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1428'
 id: 1429 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '1429'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1429'
 id: 1430 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '1430'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1430'
 id: 1431 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1431'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1431'
 id: 1432 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1432'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1432'
 id: 1433 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1433'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1433'
 id: 1434 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1434'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1434'
 id: 1435 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '1435'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1435'
 id: 1436 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '1436'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1436'
 id: 1437 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1437'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1437'
 id: 1438 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '1438'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1438'
 id: 1439 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '1439'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1439'
 id: 1440 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1440'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1440'
 id: 1441 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1441'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1441'
 id: 1442 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1442'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1442'
 id: 1443 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1443'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1443'
 id: 1444 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '1444'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1444'
 id: 1445 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1445'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1445'
 id: 1446 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1446'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1446'
 id: 1447 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1447'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1447'
 id: 1448 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1448'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1448'
 id: 1449 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1449'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1449'
 id: 1450 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '1450'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1450'
 id: 1451 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1451'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1451'
 id: 1452 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1452'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1452'
 id: 1453 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1453'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1453'
 id: 1454 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1454'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1454'
 id: 1455 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '1455'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1455'
 id: 1456 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '1456'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1456'
 id: 1457 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '1457'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1457'
 id: 1458 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1458'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1458'
 id: 1459 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1459'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1459'
 id: 1460 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1460'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1460'
 id: 1461 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '1461'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1461'
 id: 1462 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '1462'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1462'
 id: 1463 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '1463'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1463'
 id: 1464 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1464'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1464'
 id: 1465 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '1465'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1465'
 id: 1466 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '1466'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1466'
 id: 1467 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1467'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1467'
 id: 1468 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '1468'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1468'
 id: 1469 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '1469'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1469'
 id: 1470 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '1470'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1470'
 id: 1471 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1471'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1471'
 id: 1472 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1472'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1472'
 id: 1473 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1473'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1473'
 id: 1474 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1474'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1474'
 id: 1475 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1475'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1475'
 id: 1476 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '1476'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1476'
 id: 1477 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1477'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1477'
 id: 1478 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1478'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1478'
 id: 1479 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1479'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1479'
 id: 1480 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1480'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1480'
 id: 1481 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1481'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1481'
 id: 1482 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1482'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1482'
 id: 1483 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1483'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1483'
 id: 1484 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1484'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1484'
 id: 1485 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '1485'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1485'
 id: 1486 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1486'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1486'

 id: 1487 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1487'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1487'
 id: 1488 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '1488'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1488'
 id: 1489 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1489'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1489'
 id: 1490 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '1490'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1490'
 id: 1491 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1491'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1491'
 id: 1492 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '1492'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1492'
 id: 1493 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '1493'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1493'
 id: 1494 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1494'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1494'
 id: 1495 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1495'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1495'
 id: 1496 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1496'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1496'
 id: 1497 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '1497'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1497'
 id: 1498 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '1498'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1498'
 id: 1499 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1499'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1499'
 id: 1500 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '1500'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1500'
 id: 1501 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '1501'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1501'
 id: 1502 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '1502'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1502'
 id: 1503 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '1503'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1503'
 id: 1504 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1504'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1504'
 id: 1505 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1505'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1505'
 id: 1506 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1506'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1506'
 id: 1507 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '1507'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1507'
 id: 1508 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '1508'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1508'
 id: 1509 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1509'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1509'
 id: 1510 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '1510'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1510'
 id: 1511 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1511'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1511'
 id: 1512 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '1512'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1512'
 id: 1513 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '1513'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1513'
 id: 1514 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1514'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1514'
 id: 1515 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '1515'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1515'
 id: 1516 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '1516'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1516'
 id: 1517 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '1517'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1517'
 id: 1518 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '1518'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1518'
 id: 1519 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '1519'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1519'
 id: 1520 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '1520'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1520'
 id: 1521 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1521'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1521'
 id: 1522 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1522'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1522'
 id: 1523 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '1523'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1523'
 id: 1524 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1524'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1524'
 id: 1525 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '1525'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1525'
 id: 1526 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1526'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1526'
 id: 1527 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '1527'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1527'
 id: 1528 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '1528'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1528'
 id: 1529 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1529'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1529'
 id: 1530 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1530'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1530'
 id: 1531 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '1531'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1531'
 id: 1532 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1532'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1532'
 id: 1533 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1533'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1533'
 id: 1534 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '1534'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1534'
 id: 1535 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1535'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1535'
 id: 1536 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '1536'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1536'
 id: 1537 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1537'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1537'
 id: 1538 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '1538'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1538'
 id: 1539 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '1539'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1539'
 id: 1540 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '1540'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1540'
 id: 1541 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '1541'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1541'
 id: 1542 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '1542'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1542'
 id: 1543 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1543'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1543'
 id: 1544 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1544'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1544'
 id: 1545 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '1545'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1545'
 id: 1546 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1546'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1546'
 id: 1547 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '1547'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1547'
 id: 1548 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1548'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1548'
 id: 1549 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '1549'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1549'
 id: 1550 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '1550'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1550'
 id: 1551 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '1551'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1551'
 id: 1552 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '1552'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1552'
 id: 1553 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1553'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1553'
 id: 1554 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1554'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1554'
 id: 1555 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '1555'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1555'
 id: 1556 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '1556'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1556'
 id: 1557 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '1557'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1557'
 id: 1558 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '1558'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1558'
 id: 1559 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '1559'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1559'
 id: 1560 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1560'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1560'
 id: 1561 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '1561'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1561'
 id: 1562 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '1562'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1562'
 id: 1563 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1563'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1563'
 id: 1564 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1564'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1564'
 id: 1565 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1565'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1565'
 id: 1566 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '1566'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1566'
 id: 1567 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '1567'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1567'
 id: 1568 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '1568'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1568'
 id: 1569 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1569'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1569'
 id: 1570 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '1570'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1570'
 id: 1571 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1571'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1571'
 id: 1572 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1572'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1572'
 id: 1573 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '1573'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1573'
 id: 1574 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '1574'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1574'
 id: 1575 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1575'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1575'
 id: 1576 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '1576'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1576'
 id: 1577 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1577'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1577'
 id: 1578 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1578'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1578'
 id: 1579 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1579'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1579'
 id: 1580 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '1580'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1580'
 id: 1581 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '1581'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1581'
 id: 1582 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1582'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1582'
 id: 1583 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '1583'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1583'
 id: 1584 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1584'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1584'
 id: 1585 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '1585'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1585'
 id: 1586 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '1586'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1586'
 id: 1587 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1587'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1587'
 id: 1588 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '1588'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1588'
 id: 1589 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1589'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1589'
 id: 1590 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1590'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1590'
 id: 1591 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '1591'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1591'
 id: 1592 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '1592'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1592'
 id: 1593 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '1593'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1593'
 id: 1594 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '1594'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1594'
 id: 1595 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '1595'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1595'
 id: 1596 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '1596'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1596'
 id: 1597 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '1597'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1597'
 id: 1598 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1598'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1598'
 id: 1599 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '1599'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1599'
 id: 1600 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1600'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1600'
 id: 1601 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '1601'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1601'
 id: 1602 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '1602'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1602'
 id: 1603 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '1603'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1603'
 id: 1604 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '1604'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1604'
 id: 1605 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1605'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1605'
 id: 1606 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1606'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1606'
 id: 1607 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '1607'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1607'
 id: 1608 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1608'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1608'
 id: 1609 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1609'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1609'
 id: 1610 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '1610'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1610'
 id: 1611 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '1611'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1611'
 id: 1612 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '1612'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1612'
 id: 1613 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1613'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1613'
 id: 1614 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '1614'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1614'
 id: 1615 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1615'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1615'
 id: 1616 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1616'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1616'
 id: 1617 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1617'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1617'
 id: 1618 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1618'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1618'
 id: 1619 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '1619'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1619'
 id: 1620 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '1620'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1620'
 id: 1621 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '1621'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1621'
 id: 1622 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1622'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1622'
 id: 1623 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1623'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1623'
 id: 1624 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1624'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1624'
 id: 1625 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '1625'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1625'
 id: 1626 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1626'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1626'
 id: 1627 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1627'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1627'
 id: 1628 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '1628'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1628'
 id: 1629 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '1629'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1629'
 id: 1630 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '1630'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1630'
 id: 1631 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1631'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1631'
 id: 1632 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1632'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1632'
 id: 1633 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1633'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1633'
 id: 1634 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '1634'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1634'
 id: 1635 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '1635'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1635'
 id: 1636 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1636'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1636'
 id: 1637 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '1637'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1637'
 id: 1638 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1638'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1638'
 id: 1639 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1639'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1639'
 id: 1640 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '1640'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1640'
 id: 1641 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '1641'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1641'
 id: 1642 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1642'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1642'
 id: 1643 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '1643'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1643'
 id: 1644 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '1644'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1644'
 id: 1645 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '1645'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1645'
 id: 1646 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '1646'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1646'
 id: 1647 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1647'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1647'
 id: 1648 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '1648'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1648'
 id: 1649 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '1649'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1649'
 id: 1650 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '1650'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1650'
 id: 1651 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1651'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1651'
 id: 1652 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1652'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1652'
 id: 1653 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1653'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1653'
 id: 1654 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1654'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1654'
 id: 1655 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '1655'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1655'
 id: 1656 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '1656'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1656'
 id: 1657 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '1657'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1657'
 id: 1658 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1658'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1658'
 id: 1659 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '1659'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1659'
 id: 1660 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '1660'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1660'
 id: 1661 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1661'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1661'
 id: 1662 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '1662'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1662'
 id: 1663 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1663'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1663'
 id: 1664 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '1664'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1664'
 id: 1665 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1665'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1665'
 id: 1666 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '1666'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1666'
 id: 1667 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '1667'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1667'
 id: 1668 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '1668'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1668'
 id: 1669 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '1669'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1669'
 id: 1670 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1670'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1670'
 id: 1671 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '1671'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1671'
 id: 1672 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1672'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1672'
 id: 1673 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '1673'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1673'
 id: 1674 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '1674'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1674'
 id: 1675 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '1675'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1675'
 id: 1676 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '1676'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1676'
 id: 1677 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1677'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1677'
 id: 1678 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '1678'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1678'
 id: 1679 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1679'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1679'
 id: 1680 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1680'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1680'
 id: 1681 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '1681'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1681'
 id: 1682 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '1682'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1682'
 id: 1683 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '1683'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1683'
 id: 1684 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1684'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1684'
 id: 1685 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1685'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1685'
 id: 1686 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1686'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1686'
 id: 1687 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '1687'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1687'
 id: 1688 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '1688'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1688'
 id: 1689 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '1689'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1689'
 id: 1690 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1690'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1690'
 id: 1691 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1691'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1691'
 id: 1692 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '1692'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1692'
 id: 1693 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1693'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1693'
 id: 1694 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '1694'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1694'
 id: 1695 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '1695'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1695'
 id: 1696 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1696'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1696'
 id: 1697 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '1697'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1697'
 id: 1698 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '1698'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1698'
 id: 1699 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1699'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1699'
 id: 1700 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '1700'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1700'
 id: 1701 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1701'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1701'
 id: 1702 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '1702'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1702'
 id: 1703 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1703'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1703'
 id: 1704 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1704'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1704'
 id: 1705 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '1705'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1705'
 id: 1706 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '1706'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1706'
 id: 1707 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '1707'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1707'
 id: 1708 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1708'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1708'
 id: 1709 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1709'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1709'
 id: 1710 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '1710'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1710'
 id: 1711 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1711'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1711'
 id: 1712 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1712'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1712'
 id: 1713 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '1713'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1713'
 id: 1714 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1714'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1714'
 id: 1715 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1715'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1715'
 id: 1716 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '1716'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1716'
 id: 1717 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1717'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1717'
 id: 1718 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '1718'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1718'
 id: 1719 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1719'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1719'
 id: 1720 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '1720'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1720'
 id: 1721 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '1721'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1721'
 id: 1722 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '1722'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1722'
 id: 1723 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '1723'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1723'
 id: 1724 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '1724'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1724'
 id: 1725 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '1725'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1725'
 id: 1726 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '1726'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1726'
 id: 1727 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '1727'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1727'
 id: 1728 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '1728'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1728'
 id: 1729 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1729'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1729'
 id: 1730 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1730'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1730'
 id: 1731 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1731'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1731'
 id: 1732 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '1732'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1732'
 id: 1733 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1733'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1733'
 id: 1734 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1734'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1734'
 id: 1735 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1735'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1735'
 id: 1736 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '1736'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1736'
 id: 1737 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '1737'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1737'
 id: 1738 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '1738'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1738'
 id: 1739 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1739'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1739'
 id: 1740 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '1740'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1740'
 id: 1741 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1741'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1741'
 id: 1742 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '1742'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1742'
 id: 1743 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '1743'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1743'
 id: 1744 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1744'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1744'
 id: 1745 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1745'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1745'
 id: 1746 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '1746'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1746'
 id: 1747 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '1747'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1747'
 id: 1748 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '1748'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1748'
 id: 1749 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1749'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1749'
 id: 1750 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '1750'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1750'
 id: 1751 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1751'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1751'
 id: 1752 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1752'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1752'
 id: 1753 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '1753'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1753'
 id: 1754 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1754'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1754'
 id: 1755 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1755'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1755'
 id: 1756 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1756'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1756'
 id: 1757 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '1757'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1757'
 id: 1758 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1758'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1758'
 id: 1759 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1759'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1759'
 id: 1760 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '1760'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1760'
 id: 1761 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1761'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1761'
 id: 1762 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '1762'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1762'
 id: 1763 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1763'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1763'
 id: 1764 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1764'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1764'
 id: 1765 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '1765'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1765'
 id: 1766 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1766'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1766'
 id: 1767 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1767'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1767'
 id: 1768 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '1768'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1768'
 id: 1769 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1769'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1769'
 id: 1770 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '1770'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1770'
 id: 1771 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '1771'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1771'
 id: 1772 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1772'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1772'
 id: 1773 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1773'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1773'
 id: 1774 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1774'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1774'
 id: 1775 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1775'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1775'
 id: 1776 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '1776'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1776'
 id: 1777 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1777'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1777'
 id: 1778 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1778'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1778'
 id: 1779 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1779'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1779'
 id: 1780 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '1780'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1780'
 id: 1781 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '1781'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1781'
 id: 1782 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1782'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1782'
 id: 1783 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1783'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1783'
 id: 1784 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1784'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1784'
 id: 1785 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1785'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1785'
 id: 1786 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1786'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1786'
 id: 1787 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1787'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1787'
 id: 1788 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1788'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1788'
 id: 1789 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '1789'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1789'
 id: 1790 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '1790'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1790'
 id: 1791 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '1791'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1791'
 id: 1792 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '1792'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1792'
 id: 1793 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1793'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1793'
 id: 1794 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1794'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1794'
 id: 1795 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1795'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1795'
 id: 1796 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1796'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1796'
 id: 1797 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '1797'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1797'
 id: 1798 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '1798'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1798'
 id: 1799 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1799'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1799'
 id: 1800 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '1800'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1800'
 id: 1801 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1801'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1801'
 id: 1802 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '1802'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1802'
 id: 1803 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1803'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1803'
 id: 1804 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '1804'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1804'
 id: 1805 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '1805'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1805'
 id: 1806 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1806'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1806'
 id: 1807 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1807'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1807'
 id: 1808 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1808'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1808'
 id: 1809 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '1809'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1809'
 id: 1810 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '1810'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1810'
 id: 1811 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1811'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1811'
 id: 1812 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1812'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1812'
 id: 1813 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '1813'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1813'
 id: 1814 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1814'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1814'
 id: 1815 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1815'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1815'
 id: 1816 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1816'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1816'
 id: 1817 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1817'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1817'
 id: 1818 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1818'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1818'
 id: 1819 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1819'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1819'
 id: 1820 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '1820'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1820'
 id: 1821 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '1821'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1821'
 id: 1822 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1822'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1822'
 id: 1823 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '1823'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1823'
 id: 1824 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1824'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1824'
 id: 1825 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1825'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1825'
 id: 1826 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1826'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1826'
 id: 1827 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '1827'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1827'
 id: 1828 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1828'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1828'
 id: 1829 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1829'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1829'
 id: 1830 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '1830'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1830'
 id: 1831 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1831'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1831'
 id: 1832 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1832'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1832'
 id: 1833 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1833'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1833'
 id: 1834 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1834'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1834'
 id: 1835 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1835'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1835'
 id: 1836 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1836'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1836'
 id: 1837 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '1837'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1837'
 id: 1838 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1838'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1838'
 id: 1839 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '1839'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1839'
 id: 1840 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1840'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1840'
 id: 1841 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1841'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1841'
 id: 1842 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '1842'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1842'
 id: 1843 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1843'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1843'
 id: 1844 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1844'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1844'
 id: 1845 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1845'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1845'
 id: 1846 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '1846'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1846'
 id: 1847 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '1847'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1847'
 id: 1848 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1848'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1848'

 id: 1849 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1849'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1849'
 id: 1850 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1850'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1850'
 id: 1851 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1851'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1851'
 id: 1852 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '1852'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1852'
 id: 1853 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1853'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1853'
 id: 1854 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '1854'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1854'
 id: 1855 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '1855'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1855'
 id: 1856 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '1856'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1856'
 id: 1857 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '1857'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1857'
 id: 1858 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1858'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1858'
 id: 1859 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1859'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1859'
 id: 1860 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1860'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1860'
 id: 1861 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1861'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1861'
 id: 1862 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '1862'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1862'
 id: 1863 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1863'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1863'
 id: 1864 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1864'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1864'
 id: 1865 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '1865'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1865'
 id: 1866 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '1866'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1866'
 id: 1867 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1867'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1867'
 id: 1868 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '1868'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1868'
 id: 1869 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1869'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1869'
 id: 1870 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '1870'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1870'
 id: 1871 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1871'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1871'
 id: 1872 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '1872'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1872'
 id: 1873 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '1873'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1873'
 id: 1874 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1874'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1874'
 id: 1875 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '1875'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1875'
 id: 1876 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1876'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1876'
 id: 1877 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '1877'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1877'
 id: 1878 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '1878'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1878'
 id: 1879 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '1879'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1879'
 id: 1880 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '1880'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1880'
 id: 1881 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1881'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1881'
 id: 1882 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '1882'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1882'
 id: 1883 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '1883'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1883'
 id: 1884 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '1884'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1884'
 id: 1885 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '1885'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1885'
 id: 1886 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1886'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1886'
 id: 1887 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '1887'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1887'
 id: 1888 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1888'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1888'
 id: 1889 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '1889'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1889'
 id: 1890 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1890'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1890'
 id: 1891 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1891'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1891'
 id: 1892 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '1892'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1892'
 id: 1893 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1893'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1893'
 id: 1894 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1894'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1894'
 id: 1895 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '1895'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1895'
 id: 1896 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '1896'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1896'
 id: 1897 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1897'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1897'
 id: 1898 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '1898'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1898'
 id: 1899 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1899'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1899'
 id: 1900 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '1900'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1900'
 id: 1901 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '1901'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1901'
 id: 1902 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1902'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1902'
 id: 1903 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '1903'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1903'
 id: 1904 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1904'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1904'
 id: 1905 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1905'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1905'
 id: 1906 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '1906'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1906'
 id: 1907 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1907'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1907'
 id: 1908 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1908'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1908'
 id: 1909 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1909'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1909'
 id: 1910 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '1910'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1910'
 id: 1911 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '1911'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1911'
 id: 1912 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1912'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1912'
 id: 1913 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1913'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1913'
 id: 1914 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '1914'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1914'
 id: 1915 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1915'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1915'
 id: 1916 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '1916'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1916'
 id: 1917 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '1917'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1917'
 id: 1918 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '1918'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1918'
 id: 1919 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '1919'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1919'
 id: 1920 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1920'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1920'
 id: 1921 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '1921'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1921'
 id: 1922 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1922'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1922'
 id: 1923 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1923'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1923'
 id: 1924 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '1924'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1924'
 id: 1925 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1925'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1925'
 id: 1926 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1926'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1926'
 id: 1927 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1927'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1927'
 id: 1928 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1928'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1928'
 id: 1929 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '1929'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1929'
 id: 1930 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '1930'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1930'
 id: 1931 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1931'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1931'
 id: 1932 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1932'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1932'
 id: 1933 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1933'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1933'
 id: 1934 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1934'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1934'
 id: 1935 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1935'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1935'
 id: 1936 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1936'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1936'
 id: 1937 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1937'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1937'
 id: 1938 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1938'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1938'
 id: 1939 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1939'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1939'
 id: 1940 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1940'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1940'
 id: 1941 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '1941'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1941'
 id: 1942 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '1942'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1942'
 id: 1943 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '1943'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1943'
 id: 1944 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '1944'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1944'
 id: 1945 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1945'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1945'
 id: 1946 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1946'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1946'
 id: 1947 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '1947'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1947'
 id: 1948 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1948'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1948'
 id: 1949 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '1949'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1949'
 id: 1950 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1950'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1950'
 id: 1951 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '1951'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1951'
 id: 1952 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1952'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1952'
 id: 1953 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1953'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1953'
 id: 1954 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1954'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1954'
 id: 1955 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1955'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1955'
 id: 1956 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '1956'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1956'
 id: 1957 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1957'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1957'
 id: 1958 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1958'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1958'
 id: 1959 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1959'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1959'
 id: 1960 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '1960'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1960'
 id: 1961 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '1961'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1961'
 id: 1962 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1962'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1962'
 id: 1963 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '1963'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1963'
 id: 1964 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '1964'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1964'
 id: 1965 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1965'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1965'
 id: 1966 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '1966'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1966'
 id: 1967 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '1967'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1967'
 id: 1968 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '1968'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1968'
 id: 1969 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1969'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1969'
 id: 1970 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '1970'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1970'
 id: 1971 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '1971'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1971'
 id: 1972 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1972'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1972'
 id: 1973 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '1973'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1973'
 id: 1974 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '1974'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1974'
 id: 1975 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1975'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1975'
 id: 1976 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '1976'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1976'
 id: 1977 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1977'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1977'
 id: 1978 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '1978'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1978'
 id: 1979 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1979'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1979'
 id: 1980 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '1980'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1980'
 id: 1981 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '1981'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1981'
 id: 1982 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1982'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1982'
 id: 1983 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '1983'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1983'
 id: 1984 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1984'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1984'
 id: 1985 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '1985'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1985'
 id: 1986 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1986'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1986'
 id: 1987 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '1987'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1987'
 id: 1988 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '1988'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1988'
 id: 1989 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '1989'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1989'
 id: 1990 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '1990'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1990'
 id: 1991 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '1991'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1991'
 id: 1992 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1992'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1992'
 id: 1993 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '1993'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1993'
 id: 1994 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '1994'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1994'
 id: 1995 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '1995'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1995'
 id: 1996 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '1996'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1996'
 id: 1997 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '1997'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1997'
 id: 1998 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '1998'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1998'
 id: 1999 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '1999'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '1999'
 id: 2000 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '2000'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2000'
 id: 2001 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '2001'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2001'
 id: 2002 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2002'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2002'
 id: 2003 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2003'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2003'
 id: 2004 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '2004'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2004'
 id: 2005 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2005'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2005'
 id: 2006 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2006'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2006'
 id: 2007 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2007'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2007'
 id: 2008 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2008'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2008'
 id: 2009 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2009'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2009'
 id: 2010 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '2010'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2010'
 id: 2011 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2011'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2011'
 id: 2012 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2012'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2012'
 id: 2013 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2013'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2013'
 id: 2014 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2014'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2014'
 id: 2015 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2015'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2015'
 id: 2016 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '2016'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2016'
 id: 2017 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2017'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2017'
 id: 2018 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '2018'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2018'
 id: 2019 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2019'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2019'
 id: 2020 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '2020'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2020'
 id: 2021 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2021'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2021'
 id: 2022 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2022'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2022'
 id: 2023 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2023'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2023'
 id: 2024 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '2024'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2024'
 id: 2025 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2025'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2025'
 id: 2026 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '2026'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2026'
 id: 2027 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '2027'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2027'
 id: 2028 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '2028'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2028'
 id: 2029 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '2029'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2029'
 id: 2030 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '2030'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2030'
 id: 2031 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2031'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2031'
 id: 2032 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '2032'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2032'
 id: 2033 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2033'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2033'
 id: 2034 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2034'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2034'
 id: 2035 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '2035'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2035'
 id: 2036 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2036'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2036'
 id: 2037 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2037'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2037'
 id: 2038 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2038'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2038'
 id: 2039 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2039'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2039'
 id: 2040 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2040'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2040'
 id: 2041 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2041'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2041'
 id: 2042 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2042'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2042'
 id: 2043 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2043'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2043'
 id: 2044 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '2044'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2044'
 id: 2045 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2045'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2045'
 id: 2046 // word: 16
UPDATE job_vacancies SET domain_id =  '16' where raw_id = '2046'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2046'
 id: 2047 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2047'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2047'
 id: 2048 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2048'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2048'
 id: 2049 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '2049'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2049'
 id: 2050 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2050'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2050'
 id: 2051 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2051'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2051'
 id: 2052 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '2052'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2052'
 id: 2053 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2053'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2053'
 id: 2054 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '2054'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2054'
 id: 2055 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2055'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2055'
 id: 2056 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2056'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2056'
 id: 2057 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2057'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2057'

 id: 2058 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '2058'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2058'
 id: 2059 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '2059'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2059'
 id: 2060 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2060'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2060'
 id: 2061 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2061'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2061'
 id: 2062 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '2062'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2062'
 id: 2063 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2063'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2063'
 id: 2064 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2064'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2064'
 id: 2065 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '2065'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2065'
 id: 2066 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '2066'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2066'
 id: 2067 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2067'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2067'
 id: 2068 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2068'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2068'
 id: 2069 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '2069'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2069'
 id: 2070 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '2070'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2070'
 id: 2071 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2071'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2071'
 id: 2072 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '2072'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2072'
 id: 2073 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2073'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2073'
 id: 2074 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2074'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2074'
 id: 2075 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2075'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2075'
 id: 2076 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '2076'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2076'
 id: 2077 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2077'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2077'
 id: 2078 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2078'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2078'
 id: 2079 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2079'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2079'
 id: 2080 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2080'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2080'
 id: 2081 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '2081'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2081'
 id: 2082 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2082'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2082'
 id: 2083 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2083'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2083'
 id: 2084 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2084'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2084'
 id: 2085 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2085'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2085'
 id: 2086 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2086'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2086'
 id: 2087 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2087'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2087'
 id: 2088 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '2088'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2088'
 id: 2089 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2089'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2089'
 id: 2090 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2090'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2090'
 id: 2091 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2091'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2091'
 id: 2092 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '2092'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2092'
 id: 2093 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2093'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2093'
 id: 2094 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '2094'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2094'
 id: 2095 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2095'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2095'
 id: 2096 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2096'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2096'
 id: 2097 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '2097'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2097'
 id: 2098 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2098'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2098'
 id: 2099 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '2099'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2099'
 id: 2100 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2100'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2100'
 id: 2101 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '2101'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2101'
 id: 2102 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2102'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2102'
 id: 2103 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2103'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2103'
 id: 2104 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '2104'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2104'
 id: 2105 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2105'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2105'
 id: 2106 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2106'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2106'
 id: 2107 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2107'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2107'
 id: 2108 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '2108'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2108'
 id: 2109 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2109'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2109'
 id: 2110 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2110'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2110'
 id: 2111 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2111'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2111'
 id: 2112 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '2112'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2112'
 id: 2113 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2113'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2113'
 id: 2114 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2114'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2114'
 id: 2115 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2115'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2115'
 id: 2116 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '2116'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2116'
 id: 2117 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '2117'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2117'
 id: 2118 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2118'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2118'
 id: 2119 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2119'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2119'
 id: 2120 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '2120'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2120'
 id: 2121 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2121'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2121'
 id: 2122 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '2122'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2122'
 id: 2123 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2123'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2123'
 id: 2124 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '2124'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2124'
 id: 2125 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '2125'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2125'
 id: 2126 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '2126'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2126'
 id: 2127 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2127'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2127'
 id: 2128 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '2128'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2128'
 id: 2129 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '2129'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2129'
 id: 2130 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2130'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2130'
 id: 2131 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2131'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2131'
 id: 2132 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '2132'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2132'
 id: 2133 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2133'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2133'
 id: 2134 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2134'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2134'
 id: 2135 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2135'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2135'
 id: 2136 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '2136'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2136'
 id: 2137 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2137'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2137'
 id: 2138 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '2138'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2138'
 id: 2139 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2139'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2139'
 id: 2140 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2140'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2140'
 id: 2141 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2141'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2141'
 id: 2142 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2142'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2142'
 id: 2143 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2143'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2143'
 id: 2144 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '2144'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2144'
 id: 2145 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '2145'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2145'
 id: 2146 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2146'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2146'
 id: 2147 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2147'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2147'
 id: 2148 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '2148'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2148'
 id: 2149 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2149'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2149'
 id: 2150 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '2150'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2150'
 id: 2151 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '2151'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2151'
 id: 2152 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2152'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2152'
 id: 2153 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2153'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2153'
 id: 2154 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '2154'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2154'
 id: 2155 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '2155'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2155'
 id: 2156 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2156'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2156'
 id: 2157 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2157'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2157'
 id: 2158 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2158'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2158'
 id: 2159 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2159'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2159'
 id: 2160 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2160'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2160'
 id: 2161 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2161'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2161'

 id: 2162 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '2162'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2162'
 id: 2163 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2163'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2163'
 id: 2164 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '2164'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2164'
 id: 2165 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2165'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2165'
 id: 2166 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2166'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2166'
 id: 2167 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '2167'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2167'
 id: 2168 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2168'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2168'
 id: 2169 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2169'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2169'
 id: 2170 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '2170'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2170'
 id: 2171 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '2171'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2171'
 id: 2172 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2172'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2172'
 id: 2173 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2173'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2173'
 id: 2174 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2174'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2174'
 id: 2175 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2175'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2175'
 id: 2176 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '2176'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2176'
 id: 2177 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2177'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2177'
 id: 2178 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2178'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2178'
 id: 2179 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2179'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2179'
 id: 2180 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2180'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2180'
 id: 2181 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2181'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2181'
 id: 2182 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '2182'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2182'
 id: 2183 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '2183'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2183'
 id: 2184 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2184'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2184'
 id: 2185 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2185'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2185'
 id: 2186 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2186'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2186'
 id: 2187 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '2187'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2187'
 id: 2188 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '2188'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2188'
 id: 2189 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2189'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2189'
 id: 2190 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2190'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2190'
 id: 2191 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2191'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2191'
 id: 2192 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '2192'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2192'
 id: 2193 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2193'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2193'
 id: 2194 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '2194'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2194'
 id: 2195 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '2195'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2195'
 id: 2196 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2196'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2196'
 id: 2197 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2197'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2197'
 id: 2198 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '2198'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2198'
 id: 2199 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '2199'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2199'
 id: 2200 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '2200'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2200'
 id: 2201 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2201'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2201'
 id: 2202 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '2202'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2202'
 id: 2203 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2203'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2203'
 id: 2204 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2204'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2204'
 id: 2205 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '2205'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2205'
 id: 2206 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '2206'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2206'
 id: 2207 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '2207'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2207'
 id: 2208 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '2208'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2208'
 id: 2209 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2209'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2209'
 id: 2210 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2210'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2210'
 id: 2211 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '2211'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2211'
 id: 2212 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '2212'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2212'
 id: 2213 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '2213'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2213'
 id: 2214 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2214'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2214'
 id: 2215 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2215'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2215'
 id: 2216 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '2216'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2216'
 id: 2217 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '2217'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2217'
 id: 2218 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2218'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2218'
 id: 2219 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2219'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2219'
 id: 2220 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2220'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2220'
 id: 2221 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '2221'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2221'
 id: 2222 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2222'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2222'
 id: 2223 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2223'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2223'
 id: 2224 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2224'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2224'
 id: 2225 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '2225'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2225'
 id: 2226 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2226'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2226'
 id: 2227 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '2227'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2227'
 id: 2228 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2228'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2228'
 id: 2229 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2229'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2229'
 id: 2230 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2230'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2230'
 id: 2231 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '2231'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2231'
 id: 2232 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2232'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2232'
 id: 2233 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2233'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2233'
 id: 2234 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2234'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2234'
 id: 2235 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2235'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2235'
 id: 2236 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2236'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2236'
 id: 2237 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2237'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2237'
 id: 2238 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2238'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2238'
 id: 2239 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2239'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2239'
 id: 2240 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2240'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2240'
 id: 2241 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2241'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2241'
 id: 2242 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2242'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2242'
 id: 2243 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2243'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2243'
 id: 2244 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2244'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2244'
 id: 2245 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2245'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2245'
 id: 2246 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2246'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2246'
 id: 2247 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '2247'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2247'
 id: 2248 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2248'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2248'
 id: 2249 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2249'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2249'
 id: 2250 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '2250'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2250'
 id: 2251 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '2251'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2251'
 id: 2252 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2252'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2252'
 id: 2253 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2253'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2253'
 id: 2254 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '2254'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2254'
 id: 2255 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '2255'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2255'
 id: 2256 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '2256'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2256'
 id: 2257 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2257'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2257'
 id: 2258 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2258'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2258'
 id: 2259 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2259'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2259'
 id: 2260 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2260'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2260'
 id: 2261 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2261'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2261'
 id: 2262 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2262'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2262'
 id: 2263 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2263'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2263'
 id: 2264 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2264'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2264'
 id: 2265 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '2265'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2265'
 id: 2266 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2266'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2266'
 id: 2267 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '2267'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2267'
 id: 2268 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2268'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2268'
 id: 2269 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2269'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2269'
 id: 2270 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '2270'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2270'
 id: 2271 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2271'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2271'
 id: 2272 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2272'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2272'
 id: 2273 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2273'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2273'
 id: 2274 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2274'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2274'
 id: 2275 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '2275'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2275'
 id: 2276 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2276'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2276'
 id: 2277 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2277'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2277'
 id: 2278 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2278'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2278'
 id: 2279 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '2279'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2279'
 id: 2280 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '2280'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2280'
 id: 2281 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '2281'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2281'
 id: 2282 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2282'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2282'
 id: 2283 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2283'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2283'
 id: 2284 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2284'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2284'
 id: 2285 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '2285'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2285'
 id: 2286 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2286'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2286'
 id: 2287 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2287'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2287'
 id: 2288 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2288'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2288'
 id: 2289 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2289'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2289'
 id: 2290 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2290'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2290'
 id: 2291 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2291'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2291'
 id: 2292 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '2292'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2292'
 id: 2293 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2293'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2293'
 id: 2294 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2294'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2294'
 id: 2295 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2295'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2295'
 id: 2296 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2296'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2296'
 id: 2297 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2297'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2297'
 id: 2298 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2298'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2298'
 id: 2299 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2299'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2299'
 id: 2300 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2300'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2300'
 id: 2301 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2301'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2301'
 id: 2302 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2302'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2302'
 id: 2303 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2303'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2303'
 id: 2304 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2304'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2304'
 id: 2305 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '2305'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2305'
 id: 2306 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '2306'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2306'
 id: 2307 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2307'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2307'
 id: 2308 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2308'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2308'
 id: 2309 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2309'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2309'
 id: 2310 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '2310'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2310'
 id: 2311 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2311'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2311'
 id: 2312 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2312'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2312'
 id: 2313 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2313'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2313'
 id: 2314 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2314'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2314'
 id: 2315 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2315'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2315'
 id: 2316 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2316'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2316'
 id: 2317 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2317'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2317'
 id: 2318 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '2318'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2318'
 id: 2319 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2319'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2319'
 id: 2320 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2320'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2320'
 id: 2321 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '2321'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2321'
 id: 2322 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2322'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2322'
 id: 2323 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2323'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2323'
 id: 2324 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '2324'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2324'
 id: 2325 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2325'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2325'
 id: 2326 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2326'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2326'
 id: 2327 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2327'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2327'
 id: 2328 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2328'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2328'
 id: 2329 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2329'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2329'
 id: 2330 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2330'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2330'
 id: 2331 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2331'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2331'
 id: 2332 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2332'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2332'
 id: 2333 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '2333'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2333'
 id: 2334 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2334'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2334'
 id: 2335 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '2335'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2335'
 id: 2336 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '2336'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2336'
 id: 2337 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '2337'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2337'
 id: 2338 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2338'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2338'
 id: 2339 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2339'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2339'
 id: 2340 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2340'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2340'
 id: 2341 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2341'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2341'
 id: 2342 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2342'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2342'
 id: 2343 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '2343'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2343'
 id: 2344 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2344'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2344'
 id: 2345 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2345'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2345'
 id: 2346 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2346'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2346'
 id: 2347 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2347'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2347'
 id: 2348 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '2348'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2348'
 id: 2349 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '2349'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2349'
 id: 2350 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2350'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2350'
 id: 2351 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2351'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2351'
 id: 2352 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2352'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2352'
 id: 2353 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '2353'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2353'
 id: 2354 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2354'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2354'
 id: 2355 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '2355'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2355'
 id: 2356 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2356'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2356'
 id: 2357 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2357'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2357'
 id: 2358 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2358'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2358'
 id: 2359 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2359'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2359'
 id: 2360 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2360'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2360'
 id: 2361 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '2361'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2361'
 id: 2362 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2362'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2362'
 id: 2363 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '2363'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2363'
 id: 2364 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2364'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2364'
 id: 2365 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2365'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2365'
 id: 2366 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2366'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2366'
 id: 2367 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2367'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2367'
 id: 2368 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2368'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2368'
 id: 2369 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '2369'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2369'
 id: 2370 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2370'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2370'
 id: 2371 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '2371'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2371'
 id: 2372 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2372'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2372'
 id: 2373 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2373'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2373'
 id: 2374 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2374'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2374'
 id: 2375 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '2375'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2375'
 id: 2376 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2376'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2376'
 id: 2377 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '2377'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2377'
 id: 2378 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '2378'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2378'
 id: 2379 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '2379'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2379'
 id: 2380 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2380'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2380'
 id: 2381 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2381'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2381'
 id: 2382 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2382'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2382'
 id: 2383 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2383'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2383'
 id: 2384 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2384'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2384'
 id: 2385 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '2385'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2385'
 id: 2386 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '2386'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2386'
 id: 2387 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2387'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2387'
 id: 2388 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2388'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2388'
 id: 2389 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2389'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2389'
 id: 2390 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2390'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2390'
 id: 2391 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '2391'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2391'
 id: 2392 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '2392'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2392'
 id: 2393 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '2393'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2393'
 id: 2394 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2394'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2394'
 id: 2395 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2395'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2395'
 id: 2396 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2396'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2396'
 id: 2397 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2397'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2397'
 id: 2398 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '2398'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2398'
 id: 2399 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2399'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2399'
 id: 2400 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2400'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2400'
 id: 2401 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2401'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2401'
 id: 2402 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '2402'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2402'
 id: 2403 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '2403'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2403'
 id: 2404 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2404'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2404'
 id: 2405 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '2405'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2405'
 id: 2406 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2406'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2406'
 id: 2407 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2407'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2407'
 id: 2408 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2408'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2408'
 id: 2409 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2409'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2409'
 id: 2410 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2410'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2410'
 id: 2411 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2411'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2411'
 id: 2412 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2412'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2412'
 id: 2413 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '2413'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2413'
 id: 2414 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2414'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2414'
 id: 2415 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2415'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2415'
 id: 2416 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2416'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2416'
 id: 2417 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '2417'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2417'
 id: 2418 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2418'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2418'
 id: 2419 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '2419'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2419'
 id: 2420 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2420'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2420'
 id: 2421 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '2421'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2421'
 id: 2422 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '2422'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2422'
 id: 2423 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2423'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2423'
 id: 2424 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '2424'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2424'
 id: 2425 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2425'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2425'
 id: 2426 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '2426'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2426'
 id: 2427 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '2427'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2427'
 id: 2428 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2428'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2428'
 id: 2429 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '2429'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2429'
 id: 2430 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2430'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2430'
 id: 2431 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '2431'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2431'
 id: 2432 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '2432'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2432'
 id: 2433 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2433'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2433'
 id: 2434 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2434'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2434'
 id: 2435 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2435'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2435'
 id: 2436 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '2436'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2436'
 id: 2437 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '2437'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2437'
 id: 2438 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2438'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2438'
 id: 2439 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2439'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2439'
 id: 2440 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2440'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2440'
 id: 2441 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2441'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2441'
 id: 2442 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '2442'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2442'
 id: 2443 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2443'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2443'
 id: 2444 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2444'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2444'
 id: 2445 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2445'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2445'
 id: 2446 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2446'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2446'
 id: 2447 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '2447'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2447'
 id: 2448 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '2448'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2448'
 id: 2449 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2449'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2449'
 id: 2450 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '2450'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2450'
 id: 2451 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '2451'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2451'
 id: 2452 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '2452'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2452'
 id: 2453 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2453'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2453'
 id: 2454 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2454'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2454'
 id: 2455 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2455'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2455'
 id: 2456 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2456'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2456'
 id: 2457 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2457'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2457'
 id: 2458 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2458'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2458'
 id: 2459 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '2459'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2459'
 id: 2460 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '2460'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2460'
 id: 2461 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2461'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2461'
 id: 2462 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2462'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2462'
 id: 2463 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '2463'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2463'
 id: 2464 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2464'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2464'
 id: 2465 // word: 66
UPDATE job_vacancies SET domain_id =  '66' where raw_id = '2465'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2465'
 id: 2466 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2466'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2466'
 id: 2467 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2467'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2467'
 id: 2468 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2468'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2468'
 id: 2469 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2469'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2469'
 id: 2470 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2470'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2470'
 id: 2471 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '2471'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2471'
 id: 2472 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2472'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2472'
 id: 2473 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2473'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2473'
 id: 2474 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '2474'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2474'
 id: 2475 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '2475'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2475'
 id: 2476 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2476'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2476'
 id: 2477 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2477'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2477'
 id: 2478 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2478'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2478'
 id: 2479 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2479'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2479'
 id: 2480 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2480'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2480'
 id: 2481 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '2481'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2481'
 id: 2482 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2482'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2482'
 id: 2483 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '2483'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2483'
 id: 2484 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '2484'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2484'
 id: 2485 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2485'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2485'
 id: 2486 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '2486'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2486'
 id: 2487 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2487'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2487'
 id: 2488 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2488'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2488'
 id: 2489 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '2489'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2489'
 id: 2490 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '2490'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2490'
 id: 2491 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2491'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2491'
 id: 2492 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2492'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2492'
 id: 2493 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '2493'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2493'
 id: 2494 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2494'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2494'
 id: 2495 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2495'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2495'
 id: 2496 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '2496'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2496'
 id: 2497 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '2497'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2497'
 id: 2498 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2498'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2498'
 id: 2499 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2499'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2499'
 id: 2500 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2500'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2500'
 id: 2501 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '2501'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2501'
 id: 2502 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '2502'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2502'
 id: 2503 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2503'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2503'
 id: 2504 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2504'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2504'
 id: 2505 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2505'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2505'
 id: 2506 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '2506'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2506'
 id: 2507 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2507'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2507'
 id: 2508 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2508'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2508'
 id: 2509 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2509'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2509'
 id: 2510 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2510'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2510'
 id: 2511 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2511'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2511'
 id: 2512 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '2512'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2512'
 id: 2513 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2513'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2513'
 id: 2514 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '2514'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2514'
 id: 2515 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2515'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2515'
 id: 2516 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '2516'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2516'
 id: 2517 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2517'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2517'
 id: 2518 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2518'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2518'
 id: 2519 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '2519'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2519'
 id: 2520 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '2520'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2520'
 id: 2521 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2521'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2521'
 id: 2522 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2522'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2522'
 id: 2523 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2523'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2523'
 id: 2524 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2524'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2524'
 id: 2525 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2525'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2525'
 id: 2526 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '2526'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2526'
 id: 2527 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2527'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2527'
 id: 2528 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2528'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2528'
 id: 2529 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '2529'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2529'
 id: 2530 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2530'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2530'
 id: 2531 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2531'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2531'
 id: 2532 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2532'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2532'
 id: 2533 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2533'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2533'
 id: 2534 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '2534'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2534'
 id: 2535 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2535'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2535'
 id: 2536 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2536'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2536'
 id: 2537 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '2537'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2537'
 id: 2538 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '2538'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2538'
 id: 2539 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '2539'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2539'
 id: 2540 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '2540'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2540'
 id: 2541 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '2541'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2541'
 id: 2542 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '2542'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2542'
 id: 2543 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2543'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2543'
 id: 2544 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '2544'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2544'
 id: 2545 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2545'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2545'
 id: 2546 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2546'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2546'
 id: 2547 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2547'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2547'
 id: 2548 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '2548'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2548'
 id: 2549 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2549'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2549'
 id: 2550 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2550'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2550'
 id: 2551 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2551'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2551'
 id: 2552 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2552'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2552'
 id: 2553 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2553'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2553'
 id: 2554 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '2554'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2554'
 id: 2555 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '2555'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2555'
 id: 2556 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2556'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2556'
 id: 2557 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2557'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2557'
 id: 2558 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2558'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2558'
 id: 2559 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '2559'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2559'
 id: 2560 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '2560'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2560'
 id: 2561 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2561'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2561'
 id: 2562 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '2562'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2562'
 id: 2563 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2563'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2563'
 id: 2564 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '2564'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2564'
 id: 2565 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2565'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2565'
 id: 2566 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2566'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2566'
 id: 2567 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2567'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2567'
 id: 2568 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2568'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2568'
 id: 2569 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '2569'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2569'
 id: 2570 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '2570'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2570'
 id: 2571 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '2571'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2571'
 id: 2572 // word: 22
UPDATE job_vacancies SET domain_id =  '22' where raw_id = '2572'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2572'
 id: 2573 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '2573'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2573'
 id: 2574 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2574'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2574'
 id: 2575 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2575'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2575'
 id: 2576 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2576'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2576'
 id: 2577 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '2577'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2577'
 id: 2578 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2578'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2578'

 id: 2579 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '2579'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2579'
 id: 2580 // word: 40
UPDATE job_vacancies SET domain_id =  '40' where raw_id = '2580'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2580'
 id: 2581 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2581'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2581'
 id: 2582 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '2582'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2582'
 id: 2583 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '2583'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2583'
 id: 2584 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2584'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2584'
 id: 2585 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2585'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2585'
 id: 2586 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2586'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2586'
 id: 2587 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2587'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2587'
 id: 2588 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '2588'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2588'
 id: 2589 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2589'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2589'
 id: 2590 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2590'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2590'
 id: 2591 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2591'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2591'
 id: 2592 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '2592'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2592'
 id: 2593 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2593'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2593'
 id: 2594 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2594'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2594'
 id: 2595 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '2595'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2595'
 id: 2596 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '2596'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2596'
 id: 2597 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2597'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2597'
 id: 2598 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2598'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2598'
 id: 2599 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2599'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2599'
 id: 2600 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2600'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2600'
 id: 2601 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '2601'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2601'
 id: 2602 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '2602'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2602'
 id: 2603 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2603'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2603'
 id: 2604 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2604'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2604'
 id: 2605 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2605'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2605'
 id: 2606 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2606'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2606'
 id: 2607 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2607'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2607'
 id: 2608 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2608'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2608'
 id: 2609 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2609'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2609'
 id: 2610 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2610'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2610'
 id: 2611 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2611'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2611'
 id: 2612 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2612'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2612'
 id: 2613 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2613'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2613'
 id: 2614 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2614'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2614'
 id: 2615 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2615'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2615'
 id: 2616 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2616'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2616'
 id: 2617 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2617'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2617'
 id: 2618 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2618'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2618'
 id: 2619 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2619'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2619'
 id: 2620 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '2620'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2620'
 id: 2621 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2621'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2621'
 id: 2622 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2622'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2622'
 id: 2623 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '2623'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2623'
 id: 2624 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2624'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2624'
 id: 2625 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2625'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2625'
 id: 2626 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2626'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2626'
 id: 2627 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '2627'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2627'
 id: 2628 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2628'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2628'
 id: 2629 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2629'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2629'
 id: 2630 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2630'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2630'
 id: 2631 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2631'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2631'
 id: 2632 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '2632'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2632'
 id: 2633 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '2633'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2633'
 id: 2634 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2634'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2634'
 id: 2635 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2635'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2635'
 id: 2636 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '2636'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2636'
 id: 2637 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2637'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2637'
 id: 2638 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2638'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2638'
 id: 2639 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '2639'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2639'
 id: 2640 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2640'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2640'
 id: 2641 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '2641'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2641'
 id: 2642 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2642'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2642'
 id: 2643 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2643'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2643'
 id: 2644 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2644'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2644'
 id: 2645 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '2645'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2645'
 id: 2646 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2646'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2646'
 id: 2647 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2647'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2647'
 id: 2648 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2648'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2648'
 id: 2649 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2649'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2649'
 id: 2650 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '2650'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2650'
 id: 2651 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2651'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2651'
 id: 2652 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '2652'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2652'
 id: 2653 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2653'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2653'
 id: 2654 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2654'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2654'
 id: 2655 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2655'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2655'
 id: 2656 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2656'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2656'
 id: 2657 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2657'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2657'
 id: 2658 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '2658'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2658'
 id: 2659 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2659'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2659'
 id: 2660 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '2660'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2660'
 id: 2661 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '2661'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2661'
 id: 2662 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '2662'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2662'
 id: 2663 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2663'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2663'
 id: 2664 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2664'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2664'
 id: 2665 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '2665'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2665'
 id: 2666 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2666'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2666'
 id: 2667 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2667'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2667'
 id: 2668 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '2668'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2668'
 id: 2669 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2669'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2669'
 id: 2670 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2670'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2670'
 id: 2671 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2671'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2671'
 id: 2672 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '2672'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2672'
 id: 2673 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '2673'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2673'
 id: 2674 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '2674'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2674'
 id: 2675 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '2675'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2675'
 id: 2676 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '2676'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2676'
 id: 2677 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2677'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2677'
 id: 2678 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2678'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2678'
 id: 2679 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2679'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2679'
 id: 2680 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2680'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2680'
 id: 2681 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2681'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2681'
 id: 2682 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '2682'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2682'
 id: 2683 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '2683'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2683'
 id: 2684 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2684'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2684'
 id: 2685 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2685'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2685'
 id: 2686 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2686'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2686'
 id: 2687 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2687'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2687'
 id: 2688 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '2688'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2688'
 id: 2689 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '2689'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2689'
 id: 2690 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2690'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2690'
 id: 2691 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2691'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2691'
 id: 2692 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2692'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2692'
 id: 2693 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '2693'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2693'
 id: 2694 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2694'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2694'
 id: 2695 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2695'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2695'
 id: 2696 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '2696'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2696'
 id: 2697 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2697'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2697'
 id: 2698 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '2698'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2698'
 id: 2699 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2699'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2699'
 id: 2700 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2700'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2700'
 id: 2701 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2701'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2701'
 id: 2702 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2702'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2702'
 id: 2703 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '2703'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2703'
 id: 2704 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2704'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2704'
 id: 2705 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2705'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2705'
 id: 2706 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2706'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2706'
 id: 2707 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2707'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2707'
 id: 2708 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2708'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2708'
 id: 2709 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2709'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2709'
 id: 2710 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2710'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2710'
 id: 2711 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2711'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2711'
 id: 2712 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '2712'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2712'
 id: 2713 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '2713'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2713'
 id: 2714 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2714'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2714'
 id: 2715 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '2715'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2715'
 id: 2716 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2716'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2716'
 id: 2717 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '2717'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2717'
 id: 2718 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2718'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2718'
 id: 2719 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2719'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2719'
 id: 2720 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '2720'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2720'
 id: 2721 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2721'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2721'
 id: 2722 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '2722'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2722'
 id: 2723 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2723'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2723'
 id: 2724 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2724'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2724'
 id: 2725 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2725'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2725'
 id: 2726 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2726'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2726'
 id: 2727 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '2727'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2727'
 id: 2728 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2728'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2728'
 id: 2729 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2729'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2729'
 id: 2730 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '2730'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2730'
 id: 2731 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2731'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2731'
 id: 2732 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2732'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2732'

 id: 2733 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2733'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2733'
 id: 2734 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2734'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2734'
 id: 2735 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2735'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2735'
 id: 2736 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2736'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2736'
 id: 2737 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2737'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2737'
 id: 2738 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2738'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2738'
 id: 2739 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2739'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2739'
 id: 2740 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2740'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2740'
 id: 2741 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '2741'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2741'
 id: 2742 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '2742'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2742'
 id: 2743 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '2743'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2743'
 id: 2744 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '2744'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2744'
 id: 2745 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2745'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2745'
 id: 2746 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2746'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2746'
 id: 2747 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2747'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2747'
 id: 2748 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2748'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2748'
 id: 2749 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2749'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2749'
 id: 2750 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '2750'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2750'
 id: 2751 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '2751'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2751'
 id: 2752 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '2752'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2752'
 id: 2753 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2753'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2753'
 id: 2754 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2754'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2754'
 id: 2755 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2755'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2755'
 id: 2756 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2756'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2756'
 id: 2757 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2757'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2757'
 id: 2758 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2758'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2758'
 id: 2759 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '2759'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2759'
 id: 2760 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2760'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2760'
 id: 2761 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '2761'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2761'
 id: 2762 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '2762'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2762'
 id: 2763 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '2763'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2763'
 id: 2764 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2764'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2764'
 id: 2765 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2765'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2765'
 id: 2766 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2766'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2766'
 id: 2767 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2767'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2767'
 id: 2768 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2768'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2768'
 id: 2769 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2769'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2769'
 id: 2770 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '2770'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2770'
 id: 2771 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2771'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2771'
 id: 2772 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '2772'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2772'
 id: 2773 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2773'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2773'
 id: 2774 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2774'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2774'
 id: 2775 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '2775'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2775'
 id: 2776 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2776'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2776'
 id: 2777 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2777'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2777'
 id: 2778 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2778'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2778'
 id: 2779 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '2779'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2779'
 id: 2780 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2780'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2780'
 id: 2781 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '2781'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2781'
 id: 2782 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2782'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2782'
 id: 2783 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2783'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2783'
 id: 2784 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '2784'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2784'
 id: 2785 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '2785'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2785'
 id: 2786 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2786'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2786'
 id: 2787 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '2787'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2787'
 id: 2788 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2788'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2788'
 id: 2789 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '2789'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2789'
 id: 2790 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2790'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2790'
 id: 2791 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '2791'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2791'
 id: 2792 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2792'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2792'
 id: 2793 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2793'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2793'
 id: 2794 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2794'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2794'
 id: 2795 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2795'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2795'
 id: 2796 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2796'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2796'
 id: 2797 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '2797'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2797'
 id: 2798 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '2798'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2798'
 id: 2799 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2799'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2799'
 id: 2800 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '2800'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2800'
 id: 2801 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '2801'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2801'
 id: 2802 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '2802'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2802'
 id: 2803 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2803'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2803'
 id: 2804 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2804'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2804'
 id: 2805 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '2805'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2805'
 id: 2806 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2806'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2806'
 id: 2807 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2807'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2807'
 id: 2808 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '2808'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2808'
 id: 2809 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2809'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2809'
 id: 2810 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '2810'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2810'
 id: 2811 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2811'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2811'
 id: 2812 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2812'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2812'
 id: 2813 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2813'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2813'
 id: 2814 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2814'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2814'
 id: 2815 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2815'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2815'
 id: 2816 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2816'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2816'
 id: 2817 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2817'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2817'
 id: 2818 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2818'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2818'
 id: 2819 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2819'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2819'
 id: 2820 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2820'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2820'
 id: 2821 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2821'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2821'
 id: 2822 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2822'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2822'
 id: 2823 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2823'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2823'
 id: 2824 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '2824'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2824'
 id: 2825 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '2825'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2825'
 id: 2826 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2826'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2826'
 id: 2827 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2827'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2827'
 id: 2828 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2828'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2828'
 id: 2829 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '2829'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2829'
 id: 2830 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2830'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2830'
 id: 2831 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '2831'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2831'
 id: 2832 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '2832'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2832'
 id: 2833 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '2833'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2833'
 id: 2834 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '2834'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2834'
 id: 2835 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '2835'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2835'
 id: 2836 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2836'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2836'
 id: 2837 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2837'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2837'
 id: 2838 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '2838'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2838'
 id: 2839 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '2839'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2839'
 id: 2840 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '2840'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2840'
 id: 2841 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2841'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2841'
 id: 2842 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2842'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2842'
 id: 2843 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2843'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2843'
 id: 2844 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2844'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2844'
 id: 2845 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2845'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2845'
 id: 2846 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2846'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2846'
 id: 2847 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2847'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2847'
 id: 2848 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2848'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2848'
 id: 2849 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2849'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2849'
 id: 2850 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2850'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2850'
 id: 2851 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2851'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2851'
 id: 2852 // word: 49
UPDATE job_vacancies SET domain_id =  '49' where raw_id = '2852'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2852'
 id: 2853 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '2853'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2853'
 id: 2854 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2854'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2854'
 id: 2855 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '2855'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2855'
 id: 2856 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2856'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2856'
 id: 2857 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '2857'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2857'
 id: 2858 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '2858'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2858'
 id: 2859 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '2859'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2859'
 id: 2860 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2860'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2860'
 id: 2861 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2861'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2861'
 id: 2862 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2862'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2862'
 id: 2863 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '2863'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2863'
 id: 2864 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2864'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2864'
 id: 2865 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2865'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2865'
 id: 2866 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '2866'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2866'
 id: 2867 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '2867'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2867'
 id: 2868 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '2868'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2868'
 id: 2869 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2869'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2869'
 id: 2870 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2870'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2870'
 id: 2871 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2871'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2871'
 id: 2872 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2872'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2872'
 id: 2873 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '2873'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2873'
 id: 2874 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '2874'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2874'
 id: 2875 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2875'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2875'
 id: 2876 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2876'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2876'
 id: 2877 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2877'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2877'
 id: 2878 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '2878'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2878'
 id: 2879 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2879'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2879'
 id: 2880 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '2880'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2880'
 id: 2881 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2881'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2881'
 id: 2882 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '2882'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2882'
 id: 2883 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2883'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2883'
 id: 2884 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '2884'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2884'
 id: 2885 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2885'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2885'
 id: 2886 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '2886'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2886'
 id: 2887 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2887'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2887'
 id: 2888 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2888'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2888'
 id: 2889 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2889'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2889'
 id: 2890 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2890'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2890'
 id: 2891 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2891'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2891'
 id: 2892 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '2892'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2892'
 id: 2893 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '2893'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2893'
 id: 2894 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2894'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2894'
 id: 2895 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2895'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2895'
 id: 2896 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '2896'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2896'
 id: 2897 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '2897'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2897'
 id: 2898 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2898'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2898'
 id: 2899 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '2899'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2899'
 id: 2900 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '2900'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2900'
 id: 2901 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2901'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2901'
 id: 2902 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2902'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2902'
 id: 2903 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '2903'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2903'
 id: 2904 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2904'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2904'
 id: 2905 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '2905'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2905'
 id: 2906 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2906'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2906'
 id: 2907 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2907'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2907'
 id: 2908 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '2908'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2908'
 id: 2909 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2909'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2909'
 id: 2910 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '2910'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2910'
 id: 2911 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '2911'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2911'
 id: 2912 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2912'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2912'
 id: 2913 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2913'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2913'
 id: 2914 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2914'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2914'
 id: 2915 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2915'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2915'
 id: 2916 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '2916'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2916'
 id: 2917 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '2917'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2917'
 id: 2918 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2918'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2918'
 id: 2919 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2919'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2919'
 id: 2920 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2920'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2920'
 id: 2921 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2921'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2921'
 id: 2922 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '2922'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2922'
 id: 2923 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2923'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2923'
 id: 2924 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2924'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2924'
 id: 2925 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '2925'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2925'
 id: 2926 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2926'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2926'
 id: 2927 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '2927'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2927'
 id: 2928 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '2928'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2928'
 id: 2929 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '2929'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2929'
 id: 2930 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '2930'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2930'
 id: 2931 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '2931'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2931'
 id: 2932 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '2932'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2932'
 id: 2933 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2933'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2933'
 id: 2934 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2934'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2934'
 id: 2935 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '2935'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2935'
 id: 2936 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2936'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2936'
 id: 2937 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2937'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2937'
 id: 2938 // word: 52
UPDATE job_vacancies SET domain_id =  '52' where raw_id = '2938'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2938'
 id: 2939 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2939'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2939'
 id: 2940 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '2940'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2940'
 id: 2941 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2941'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2941'
 id: 2942 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '2942'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2942'
 id: 2943 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2943'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2943'
 id: 2944 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2944'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2944'
 id: 2945 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '2945'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2945'
 id: 2946 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '2946'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2946'
 id: 2947 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2947'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2947'
 id: 2948 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2948'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2948'
 id: 2949 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '2949'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2949'
 id: 2950 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2950'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2950'
 id: 2951 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2951'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2951'
 id: 2952 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2952'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2952'
 id: 2953 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2953'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2953'
 id: 2954 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2954'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2954'
 id: 2955 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2955'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2955'
 id: 2956 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2956'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2956'
 id: 2957 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2957'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2957'
 id: 2958 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '2958'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2958'
 id: 2959 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2959'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2959'
 id: 2960 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '2960'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2960'
 id: 2961 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2961'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2961'
 id: 2962 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '2962'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2962'
 id: 2963 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '2963'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2963'
 id: 2964 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '2964'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2964'
 id: 2965 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '2965'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2965'
 id: 2966 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '2966'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2966'
 id: 2967 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2967'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2967'
 id: 2968 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '2968'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2968'
 id: 2969 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '2969'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2969'
 id: 2970 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '2970'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2970'
 id: 2971 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2971'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2971'
 id: 2972 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '2972'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2972'
 id: 2973 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '2973'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2973'
 id: 2974 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '2974'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2974'
 id: 2975 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2975'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2975'
 id: 2976 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '2976'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2976'
 id: 2977 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2977'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2977'
 id: 2978 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2978'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2978'
 id: 2979 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2979'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2979'
 id: 2980 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '2980'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2980'
 id: 2981 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2981'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2981'
 id: 2982 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '2982'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2982'
 id: 2983 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '2983'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2983'
 id: 2984 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '2984'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2984'
 id: 2985 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '2985'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2985'
 id: 2986 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '2986'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2986'
 id: 2987 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2987'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2987'
 id: 2988 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '2988'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2988'
 id: 2989 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '2989'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2989'
 id: 2990 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '2990'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2990'
 id: 2991 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '2991'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2991'
 id: 2992 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '2992'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2992'
 id: 2993 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '2993'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2993'
 id: 2994 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '2994'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2994'
 id: 2995 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2995'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2995'
 id: 2996 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '2996'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2996'
 id: 2997 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '2997'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2997'
 id: 2998 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '2998'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2998'
 id: 2999 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '2999'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '2999'
 id: 3000 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '3000'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3000'
 id: 3001 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3001'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3001'
 id: 3002 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '3002'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3002'
 id: 3003 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3003'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3003'
 id: 3004 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3004'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3004'
 id: 3005 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '3005'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3005'
 id: 3006 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '3006'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3006'
 id: 3007 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '3007'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3007'
 id: 3008 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3008'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3008'
 id: 3009 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3009'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3009'
 id: 3010 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3010'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3010'
 id: 3011 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '3011'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3011'
 id: 3012 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3012'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3012'
 id: 3013 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '3013'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3013'
 id: 3014 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3014'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3014'
 id: 3015 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3015'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3015'
 id: 3016 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '3016'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3016'
 id: 3017 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '3017'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3017'
 id: 3018 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '3018'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3018'
 id: 3019 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '3019'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3019'
 id: 3020 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3020'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3020'
 id: 3021 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '3021'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3021'
 id: 3022 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '3022'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3022'
 id: 3023 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '3023'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3023'
 id: 3024 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3024'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3024'
 id: 3025 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '3025'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3025'
 id: 3026 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3026'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3026'
 id: 3027 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3027'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3027'
 id: 3028 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3028'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3028'
 id: 3029 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3029'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3029'
 id: 3030 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3030'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3030'
 id: 3031 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3031'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3031'
 id: 3032 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '3032'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3032'
 id: 3033 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3033'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3033'
 id: 3034 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3034'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3034'
 id: 3035 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '3035'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3035'
 id: 3036 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3036'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3036'
 id: 3037 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3037'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3037'
 id: 3038 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3038'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3038'
 id: 3039 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '3039'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3039'
 id: 3040 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3040'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3040'
 id: 3041 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3041'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3041'
 id: 3042 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3042'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3042'
 id: 3043 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3043'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3043'
 id: 3044 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3044'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3044'
 id: 3045 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '3045'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3045'

 id: 3046 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3046'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3046'
 id: 3047 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3047'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3047'
 id: 3048 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3048'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3048'
 id: 3049 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3049'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3049'
 id: 3050 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '3050'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3050'
 id: 3051 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '3051'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3051'
 id: 3052 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3052'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3052'
 id: 3053 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3053'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3053'
 id: 3054 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3054'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3054'
 id: 3055 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3055'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3055'
 id: 3056 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '3056'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3056'
 id: 3057 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '3057'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3057'
 id: 3058 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3058'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3058'
 id: 3059 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '3059'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3059'
 id: 3060 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3060'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3060'
 id: 3061 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3061'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3061'
 id: 3062 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '3062'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3062'
 id: 3063 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3063'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3063'
 id: 3064 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3064'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3064'
 id: 3065 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '3065'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3065'
 id: 3066 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3066'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3066'
 id: 3067 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3067'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3067'
 id: 3068 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '3068'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3068'
 id: 3069 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '3069'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3069'
 id: 3070 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '3070'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3070'
 id: 3071 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '3071'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3071'
 id: 3072 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '3072'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3072'
 id: 3073 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '3073'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3073'
 id: 3074 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3074'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3074'
 id: 3075 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3075'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3075'
 id: 3076 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '3076'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3076'
 id: 3077 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3077'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3077'
 id: 3078 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '3078'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3078'
 id: 3079 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '3079'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3079'
 id: 3080 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '3080'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3080'
 id: 3081 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3081'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3081'
 id: 3082 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3082'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3082'
 id: 3083 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '3083'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3083'
 id: 3084 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '3084'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3084'
 id: 3085 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '3085'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3085'
 id: 3086 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3086'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3086'
 id: 3087 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3087'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3087'
 id: 3088 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '3088'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3088'
 id: 3089 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '3089'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3089'
 id: 3090 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '3090'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3090'
 id: 3091 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3091'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3091'
 id: 3092 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3092'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3092'
 id: 3093 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '3093'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3093'
 id: 3094 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '3094'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3094'
 id: 3095 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '3095'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3095'
 id: 3096 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3096'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3096'
 id: 3097 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3097'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3097'
 id: 3098 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3098'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3098'
 id: 3099 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3099'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3099'
 id: 3100 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3100'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3100'
 id: 3101 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3101'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3101'
 id: 3102 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '3102'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3102'
 id: 3103 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '3103'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3103'
 id: 3104 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3104'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3104'
 id: 3105 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '3105'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3105'
 id: 3106 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3106'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3106'
 id: 3107 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '3107'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3107'
 id: 3108 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3108'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3108'
 id: 3109 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '3109'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3109'
 id: 3110 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3110'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3110'
 id: 3111 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '3111'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3111'
 id: 3112 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '3112'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3112'
 id: 3113 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3113'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3113'
 id: 3114 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '3114'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3114'
 id: 3115 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3115'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3115'
 id: 3116 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3116'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3116'
 id: 3117 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3117'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3117'
 id: 3118 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3118'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3118'
 id: 3119 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3119'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3119'
 id: 3120 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3120'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3120'
 id: 3121 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3121'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3121'
 id: 3122 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3122'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3122'
 id: 3123 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '3123'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3123'
 id: 3124 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3124'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3124'
 id: 3125 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '3125'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3125'
 id: 3126 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3126'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3126'
 id: 3127 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '3127'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3127'
 id: 3128 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3128'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3128'
 id: 3129 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3129'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3129'
 id: 3130 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '3130'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3130'
 id: 3131 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '3131'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3131'
 id: 3132 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '3132'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3132'
 id: 3133 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3133'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3133'
 id: 3134 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3134'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3134'
 id: 3135 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3135'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3135'
 id: 3136 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3136'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3136'
 id: 3137 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3137'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3137'
 id: 3138 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '3138'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3138'
 id: 3139 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3139'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3139'
 id: 3140 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '3140'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3140'
 id: 3141 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3141'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3141'
 id: 3142 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3142'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3142'
 id: 3143 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '3143'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3143'
 id: 3144 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '3144'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3144'
 id: 3145 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3145'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3145'
 id: 3146 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '3146'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3146'
 id: 3147 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '3147'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3147'
 id: 3148 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3148'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3148'
 id: 3149 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '3149'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3149'
 id: 3150 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '3150'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3150'
 id: 3151 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '3151'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3151'
 id: 3152 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3152'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3152'
 id: 3153 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '3153'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3153'
 id: 3154 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '3154'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3154'
 id: 3155 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3155'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3155'
 id: 3156 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3156'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3156'
 id: 3157 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3157'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3157'
 id: 3158 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '3158'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3158'
 id: 3159 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '3159'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3159'
 id: 3160 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3160'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3160'
 id: 3161 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3161'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3161'
 id: 3162 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '3162'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3162'
 id: 3163 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3163'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3163'
 id: 3164 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3164'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3164'
 id: 3165 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '3165'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3165'
 id: 3166 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '3166'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3166'
 id: 3167 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3167'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3167'
 id: 3168 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3168'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3168'
 id: 3169 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '3169'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3169'
 id: 3170 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3170'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3170'
 id: 3171 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3171'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3171'
 id: 3172 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3172'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3172'
 id: 3173 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3173'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3173'
 id: 3174 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3174'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3174'
 id: 3175 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3175'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3175'
 id: 3176 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '3176'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3176'
 id: 3177 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3177'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3177'
 id: 3178 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3178'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3178'
 id: 3179 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3179'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3179'
 id: 3180 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3180'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3180'
 id: 3181 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3181'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3181'
 id: 3182 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3182'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3182'
 id: 3183 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3183'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3183'
 id: 3184 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3184'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3184'
 id: 3185 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3185'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3185'
 id: 3186 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3186'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3186'
 id: 3187 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '3187'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3187'
 id: 3188 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '3188'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3188'
 id: 3189 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '3189'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3189'
 id: 3190 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3190'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3190'
 id: 3191 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3191'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3191'
 id: 3192 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '3192'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3192'
 id: 3193 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '3193'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3193'
 id: 3194 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3194'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3194'
 id: 3195 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3195'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3195'
 id: 3196 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3196'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3196'
 id: 3197 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '3197'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3197'
 id: 3198 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3198'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3198'
 id: 3199 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3199'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3199'
 id: 3200 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '3200'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3200'
 id: 3201 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3201'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3201'

 id: 3202 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '3202'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3202'
 id: 3203 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '3203'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3203'
 id: 3204 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3204'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3204'
 id: 3205 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3205'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3205'
 id: 3206 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3206'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3206'
 id: 3207 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3207'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3207'
 id: 3208 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '3208'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3208'
 id: 3209 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '3209'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3209'
 id: 3210 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3210'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3210'
 id: 3211 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '3211'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3211'
 id: 3212 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '3212'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3212'
 id: 3213 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3213'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3213'
 id: 3214 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '3214'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3214'
 id: 3215 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '3215'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3215'
 id: 3216 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3216'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3216'
 id: 3217 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3217'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3217'
 id: 3218 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '3218'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3218'
 id: 3219 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3219'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3219'
 id: 3220 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3220'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3220'
 id: 3221 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3221'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3221'
 id: 3222 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '3222'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3222'
 id: 3223 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3223'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3223'
 id: 3224 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3224'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3224'
 id: 3225 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '3225'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3225'
 id: 3226 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3226'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3226'
 id: 3227 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3227'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3227'
 id: 3228 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '3228'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3228'
 id: 3229 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3229'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3229'
 id: 3230 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3230'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3230'
 id: 3231 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3231'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3231'
 id: 3232 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3232'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3232'
 id: 3233 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '3233'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3233'
 id: 3234 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '3234'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3234'
 id: 3235 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '3235'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3235'
 id: 3236 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3236'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3236'
 id: 3237 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3237'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3237'
 id: 3238 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3238'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3238'
 id: 3239 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '3239'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3239'
 id: 3240 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3240'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3240'
 id: 3241 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3241'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3241'
 id: 3242 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3242'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3242'
 id: 3243 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '3243'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3243'
 id: 3244 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3244'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3244'
 id: 3245 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3245'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3245'
 id: 3246 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '3246'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3246'
 id: 3247 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3247'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3247'
 id: 3248 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3248'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3248'
 id: 3249 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3249'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3249'
 id: 3250 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '3250'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3250'
 id: 3251 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3251'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3251'
 id: 3252 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3252'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3252'
 id: 3253 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3253'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3253'
 id: 3254 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3254'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3254'
 id: 3255 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3255'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3255'
 id: 3256 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3256'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3256'
 id: 3257 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '3257'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3257'
 id: 3258 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3258'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3258'
 id: 3259 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '3259'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3259'
 id: 3260 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '3260'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3260'
 id: 3261 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3261'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3261'
 id: 3262 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3262'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3262'
 id: 3263 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3263'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3263'
 id: 3264 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3264'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3264'
 id: 3265 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3265'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3265'
 id: 3266 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '3266'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3266'
 id: 3267 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '3267'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3267'
 id: 3268 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '3268'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3268'
 id: 3269 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3269'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3269'
 id: 3270 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '3270'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3270'
 id: 3271 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3271'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3271'
 id: 3272 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3272'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3272'
 id: 3273 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '3273'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3273'
 id: 3274 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '3274'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3274'
 id: 3275 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3275'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3275'
 id: 3276 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '3276'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3276'
 id: 3277 // word: 66
UPDATE job_vacancies SET domain_id =  '66' where raw_id = '3277'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3277'
 id: 3278 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '3278'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3278'
 id: 3279 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3279'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3279'
 id: 3280 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '3280'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3280'
 id: 3281 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3281'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3281'
 id: 3282 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3282'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3282'
 id: 3283 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '3283'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3283'
 id: 3284 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '3284'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3284'
 id: 3285 // word: 66
UPDATE job_vacancies SET domain_id =  '66' where raw_id = '3285'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3285'
 id: 3286 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3286'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3286'
 id: 3287 // word: 40
UPDATE job_vacancies SET domain_id =  '40' where raw_id = '3287'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3287'
 id: 3288 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '3288'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3288'
 id: 3289 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3289'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3289'
 id: 3290 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '3290'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3290'
 id: 3291 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3291'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3291'
 id: 3292 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3292'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3292'
 id: 3293 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3293'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3293'
 id: 3294 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '3294'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3294'
 id: 3295 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3295'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3295'
 id: 3296 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '3296'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3296'
 id: 3297 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '3297'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3297'
 id: 3298 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3298'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3298'
 id: 3299 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3299'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3299'
 id: 3300 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '3300'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3300'
 id: 3301 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3301'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3301'
 id: 3302 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3302'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3302'
 id: 3303 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3303'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3303'
 id: 3304 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3304'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3304'
 id: 3305 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3305'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3305'
 id: 3306 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '3306'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3306'
 id: 3307 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3307'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3307'
 id: 3308 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3308'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3308'
 id: 3309 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '3309'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3309'
 id: 3310 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '3310'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3310'
 id: 3311 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '3311'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3311'
 id: 3312 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '3312'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3312'
 id: 3313 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '3313'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3313'
 id: 3314 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3314'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3314'
 id: 3315 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3315'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3315'
 id: 3316 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3316'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3316'
 id: 3317 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3317'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3317'
 id: 3318 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '3318'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3318'
 id: 3319 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3319'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3319'
 id: 3320 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '3320'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3320'
 id: 3321 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '3321'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3321'
 id: 3322 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3322'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3322'
 id: 3323 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3323'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3323'
 id: 3324 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3324'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3324'
 id: 3325 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3325'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3325'
 id: 3326 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '3326'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3326'
 id: 3327 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3327'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3327'
 id: 3328 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '3328'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3328'
 id: 3329 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '3329'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3329'
 id: 3330 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3330'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3330'
 id: 3331 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3331'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3331'
 id: 3332 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3332'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3332'
 id: 3333 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '3333'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3333'
 id: 3334 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '3334'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3334'
 id: 3335 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '3335'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3335'
 id: 3336 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3336'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3336'
 id: 3337 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3337'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3337'
 id: 3338 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3338'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3338'
 id: 3339 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '3339'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3339'
 id: 3340 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '3340'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3340'
 id: 3341 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '3341'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3341'
 id: 3342 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3342'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3342'
 id: 3343 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3343'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3343'
 id: 3344 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3344'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3344'
 id: 3345 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '3345'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3345'
 id: 3346 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '3346'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3346'
 id: 3347 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '3347'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3347'
 id: 3348 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3348'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3348'
 id: 3349 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '3349'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3349'
 id: 3350 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '3350'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3350'
 id: 3351 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3351'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3351'
 id: 3352 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3352'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3352'
 id: 3353 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3353'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3353'
 id: 3354 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '3354'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3354'
 id: 3355 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '3355'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3355'
 id: 3356 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3356'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3356'
 id: 3357 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3357'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3357'
 id: 3358 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3358'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3358'
 id: 3359 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '3359'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3359'
 id: 3360 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '3360'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3360'
 id: 3361 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3361'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3361'
 id: 3362 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3362'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3362'
 id: 3363 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '3363'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3363'
 id: 3364 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3364'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3364'
 id: 3365 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3365'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3365'
 id: 3366 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3366'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3366'
 id: 3367 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '3367'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3367'
 id: 3368 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3368'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3368'
 id: 3369 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '3369'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3369'
 id: 3370 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3370'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3370'
 id: 3371 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3371'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3371'
 id: 3372 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3372'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3372'
 id: 3373 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '3373'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3373'
 id: 3374 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '3374'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3374'
 id: 3375 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3375'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3375'
 id: 3376 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3376'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3376'
 id: 3377 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '3377'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3377'
 id: 3378 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3378'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3378'
 id: 3379 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '3379'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3379'
 id: 3380 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '3380'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3380'
 id: 3381 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3381'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3381'
 id: 3382 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '3382'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3382'
 id: 3383 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3383'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3383'
 id: 3384 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3384'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3384'
 id: 3385 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3385'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3385'
 id: 3386 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '3386'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3386'
 id: 3387 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '3387'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3387'
 id: 3388 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '3388'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3388'
 id: 3389 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '3389'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3389'
 id: 3390 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '3390'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3390'
 id: 3391 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3391'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3391'
 id: 3392 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3392'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3392'
 id: 3393 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3393'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3393'
 id: 3394 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3394'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3394'
 id: 3395 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3395'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3395'
 id: 3396 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3396'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3396'
 id: 3397 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3397'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3397'
 id: 3398 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '3398'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3398'
 id: 3399 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3399'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3399'
 id: 3400 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3400'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3400'
 id: 3401 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '3401'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3401'
 id: 3402 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '3402'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3402'
 id: 3403 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3403'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3403'
 id: 3404 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3404'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3404'
 id: 3405 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '3405'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3405'
 id: 3406 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3406'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3406'
 id: 3407 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '3407'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3407'
 id: 3408 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '3408'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3408'

 id: 3409 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3409'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3409'
 id: 3410 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3410'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3410'
 id: 3411 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3411'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3411'
 id: 3412 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3412'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3412'
 id: 3413 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '3413'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3413'
 id: 3414 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '3414'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3414'
 id: 3415 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3415'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3415'
 id: 3416 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3416'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3416'
 id: 3417 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3417'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3417'
 id: 3418 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3418'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3418'
 id: 3419 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3419'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3419'
 id: 3420 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '3420'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3420'
 id: 3421 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '3421'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3421'
 id: 3422 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3422'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3422'
 id: 3423 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '3423'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3423'
 id: 3424 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '3424'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3424'
 id: 3425 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '3425'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3425'
 id: 3426 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3426'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3426'
 id: 3427 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '3427'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3427'
 id: 3428 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3428'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3428'
 id: 3429 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '3429'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3429'
 id: 3430 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3430'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3430'
 id: 3431 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3431'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3431'
 id: 3432 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3432'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3432'
 id: 3433 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '3433'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3433'
 id: 3434 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3434'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3434'
 id: 3435 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '3435'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3435'
 id: 3436 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '3436'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3436'
 id: 3437 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3437'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3437'
 id: 3438 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '3438'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3438'
 id: 3439 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3439'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3439'
 id: 3440 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '3440'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3440'
 id: 3441 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3441'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3441'
 id: 3442 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '3442'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3442'
 id: 3443 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3443'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3443'
 id: 3444 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3444'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3444'
 id: 3445 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '3445'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3445'
 id: 3446 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '3446'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3446'
 id: 3447 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3447'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3447'
 id: 3448 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '3448'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3448'
 id: 3449 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3449'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3449'
 id: 3450 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '3450'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3450'
 id: 3451 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3451'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3451'
 id: 3452 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3452'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3452'
 id: 3453 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '3453'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3453'
 id: 3454 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '3454'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3454'
 id: 3455 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3455'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3455'
 id: 3456 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3456'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3456'
 id: 3457 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3457'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3457'
 id: 3458 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '3458'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3458'
 id: 3459 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3459'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3459'

 id: 3460 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3460'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3460'
 id: 3461 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3461'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3461'
 id: 3462 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3462'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3462'
 id: 3463 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3463'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3463'
 id: 3464 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '3464'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3464'
 id: 3465 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3465'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3465'
 id: 3466 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '3466'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3466'
 id: 3467 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '3467'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3467'
 id: 3468 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3468'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3468'
 id: 3469 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '3469'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3469'
 id: 3470 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '3470'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3470'
 id: 3471 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3471'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3471'
 id: 3472 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3472'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3472'
 id: 3473 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '3473'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3473'
 id: 3474 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '3474'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3474'
 id: 3475 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3475'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3475'
 id: 3476 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '3476'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3476'
 id: 3477 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3477'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3477'
 id: 3478 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3478'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3478'
 id: 3479 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3479'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3479'
 id: 3480 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3480'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3480'
 id: 3481 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3481'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3481'
 id: 3482 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3482'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3482'
 id: 3483 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '3483'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3483'
 id: 3484 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '3484'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3484'
 id: 3485 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3485'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3485'
 id: 3486 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '3486'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3486'
 id: 3487 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '3487'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3487'
 id: 3488 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '3488'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3488'
 id: 3489 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '3489'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3489'
 id: 3490 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '3490'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3490'
 id: 3491 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3491'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3491'
 id: 3492 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3492'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3492'
 id: 3493 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '3493'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3493'
 id: 3494 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3494'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3494'
 id: 3495 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3495'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3495'
 id: 3496 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3496'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3496'
 id: 3497 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3497'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3497'
 id: 3498 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3498'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3498'
 id: 3499 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '3499'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3499'
 id: 3500 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3500'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3500'
 id: 3501 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3501'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3501'
 id: 3502 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3502'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3502'
 id: 3503 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3503'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3503'
 id: 3504 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '3504'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3504'
 id: 3505 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3505'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3505'
 id: 3506 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '3506'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3506'
 id: 3507 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '3507'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3507'
 id: 3508 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '3508'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3508'
 id: 3509 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '3509'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3509'
 id: 3510 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3510'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3510'
 id: 3511 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3511'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3511'
 id: 3512 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3512'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3512'
 id: 3513 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '3513'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3513'
 id: 3514 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3514'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3514'
 id: 3515 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '3515'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3515'
 id: 3516 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3516'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3516'
 id: 3517 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '3517'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3517'
 id: 3518 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '3518'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3518'
 id: 3519 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3519'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3519'
 id: 3520 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3520'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3520'
 id: 3521 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3521'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3521'
 id: 3522 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '3522'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3522'
 id: 3523 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3523'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3523'
 id: 3524 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '3524'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3524'
 id: 3525 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '3525'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3525'
 id: 3526 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3526'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3526'
 id: 3527 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3527'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3527'
 id: 3528 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '3528'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3528'
 id: 3529 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3529'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3529'
 id: 3530 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '3530'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3530'
 id: 3531 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3531'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3531'
 id: 3532 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3532'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3532'
 id: 3533 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3533'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3533'
 id: 3534 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '3534'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3534'
 id: 3535 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3535'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3535'
 id: 3536 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3536'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3536'
 id: 3537 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3537'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3537'
 id: 3538 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '3538'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3538'
 id: 3539 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '3539'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3539'
 id: 3540 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3540'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3540'
 id: 3541 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '3541'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3541'
 id: 3542 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3542'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3542'
 id: 3543 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '3543'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3543'
 id: 3544 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '3544'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3544'
 id: 3545 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3545'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3545'
 id: 3546 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3546'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3546'
 id: 3547 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3547'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3547'
 id: 3548 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3548'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3548'
 id: 3549 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '3549'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3549'
 id: 3550 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3550'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3550'
 id: 3551 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3551'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3551'
 id: 3552 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3552'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3552'
 id: 3553 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3553'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3553'
 id: 3554 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '3554'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3554'
 id: 3555 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3555'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3555'
 id: 3556 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '3556'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3556'
 id: 3557 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3557'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3557'
 id: 3558 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3558'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3558'
 id: 3559 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3559'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3559'
 id: 3560 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3560'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3560'
 id: 3561 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '3561'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3561'
 id: 3562 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3562'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3562'
 id: 3563 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3563'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3563'
 id: 3564 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '3564'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3564'
 id: 3565 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3565'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3565'
 id: 3566 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3566'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3566'
 id: 3567 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '3567'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3567'
 id: 3568 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3568'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3568'
 id: 3569 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3569'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3569'
 id: 3570 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '3570'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3570'
 id: 3571 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3571'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3571'
 id: 3572 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3572'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3572'
 id: 3573 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '3573'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3573'
 id: 3574 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3574'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3574'
 id: 3575 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3575'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3575'
 id: 3576 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3576'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3576'
 id: 3577 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3577'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3577'
 id: 3578 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3578'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3578'
 id: 3579 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '3579'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3579'
 id: 3580 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3580'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3580'
 id: 3581 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3581'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3581'
 id: 3582 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3582'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3582'
 id: 3583 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3583'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3583'
 id: 3584 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3584'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3584'
 id: 3585 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '3585'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3585'
 id: 3586 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3586'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3586'
 id: 3587 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '3587'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3587'
 id: 3588 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3588'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3588'
 id: 3589 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3589'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3589'
 id: 3590 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '3590'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3590'
 id: 3591 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '3591'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3591'
 id: 3592 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3592'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3592'
 id: 3593 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3593'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3593'
 id: 3594 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3594'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3594'
 id: 3595 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3595'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3595'
 id: 3596 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '3596'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3596'
 id: 3597 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '3597'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3597'
 id: 3598 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '3598'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3598'
 id: 3599 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '3599'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3599'
 id: 3600 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3600'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3600'
 id: 3601 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3601'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3601'
 id: 3602 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '3602'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3602'
 id: 3603 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '3603'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3603'
 id: 3604 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3604'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3604'
 id: 3605 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '3605'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3605'
 id: 3606 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3606'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3606'
 id: 3607 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3607'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3607'
 id: 3608 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3608'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3608'
 id: 3609 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '3609'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3609'
 id: 3610 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3610'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3610'
 id: 3611 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '3611'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3611'
 id: 3612 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '3612'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3612'
 id: 3613 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3613'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3613'
 id: 3614 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3614'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3614'
 id: 3615 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3615'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3615'
 id: 3616 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3616'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3616'
 id: 3617 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3617'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3617'
 id: 3618 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3618'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3618'
 id: 3619 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '3619'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3619'
 id: 3620 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '3620'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3620'
 id: 3621 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3621'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3621'
 id: 3622 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3622'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3622'
 id: 3623 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3623'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3623'
 id: 3624 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3624'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3624'
 id: 3625 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3625'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3625'
 id: 3626 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '3626'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3626'
 id: 3627 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '3627'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3627'
 id: 3628 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3628'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3628'
 id: 3629 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3629'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3629'
 id: 3630 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3630'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3630'
 id: 3631 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3631'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3631'
 id: 3632 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3632'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3632'
 id: 3633 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3633'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3633'
 id: 3634 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3634'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3634'
 id: 3635 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '3635'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3635'
 id: 3636 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '3636'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3636'
 id: 3637 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '3637'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3637'
 id: 3638 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '3638'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3638'
 id: 3639 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3639'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3639'
 id: 3640 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3640'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3640'
 id: 3641 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '3641'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3641'
 id: 3642 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3642'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3642'
 id: 3643 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3643'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3643'
 id: 3644 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '3644'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3644'
 id: 3645 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3645'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3645'
 id: 3646 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '3646'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3646'
 id: 3647 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3647'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3647'
 id: 3648 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3648'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3648'
 id: 3649 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '3649'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3649'
 id: 3650 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '3650'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3650'
 id: 3651 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3651'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3651'
 id: 3652 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '3652'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3652'
 id: 3653 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3653'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3653'
 id: 3654 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3654'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3654'
 id: 3655 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3655'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3655'
 id: 3656 // word: 28
UPDATE job_vacancies SET domain_id =  '28' where raw_id = '3656'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3656'
 id: 3657 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '3657'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3657'
 id: 3658 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '3658'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3658'
 id: 3659 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '3659'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3659'
 id: 3660 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '3660'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3660'
 id: 3661 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3661'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3661'
 id: 3662 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3662'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3662'

 id: 3663 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '3663'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3663'
 id: 3664 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '3664'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3664'
 id: 3665 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3665'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3665'
 id: 3666 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3666'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3666'
 id: 3667 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3667'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3667'
 id: 3668 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3668'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3668'
 id: 3669 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3669'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3669'
 id: 3670 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3670'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3670'
 id: 3671 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '3671'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3671'
 id: 3672 // word: 49
UPDATE job_vacancies SET domain_id =  '49' where raw_id = '3672'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3672'
 id: 3673 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3673'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3673'
 id: 3674 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '3674'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3674'
 id: 3675 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '3675'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3675'
 id: 3676 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '3676'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3676'
 id: 3677 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '3677'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3677'
 id: 3678 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '3678'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3678'
 id: 3679 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '3679'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3679'
 id: 3680 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3680'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3680'
 id: 3681 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3681'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3681'
 id: 3682 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '3682'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3682'
 id: 3683 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '3683'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3683'
 id: 3684 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3684'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3684'
 id: 3685 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3685'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3685'
 id: 3686 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '3686'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3686'
 id: 3687 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3687'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3687'
 id: 3688 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '3688'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3688'
 id: 3689 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '3689'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3689'
 id: 3690 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '3690'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3690'
 id: 3691 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3691'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3691'
 id: 3692 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '3692'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3692'
 id: 3693 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '3693'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3693'
 id: 3694 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3694'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3694'
 id: 3695 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '3695'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3695'
 id: 3696 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3696'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3696'
 id: 3697 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3697'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3697'
 id: 3698 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '3698'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3698'
 id: 3699 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3699'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3699'
 id: 3700 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3700'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3700'
 id: 3701 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3701'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3701'
 id: 3702 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3702'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3702'
 id: 3703 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '3703'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3703'
 id: 3704 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3704'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3704'
 id: 3705 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3705'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3705'
 id: 3706 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3706'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3706'
 id: 3707 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '3707'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3707'
 id: 3708 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '3708'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3708'
 id: 3709 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3709'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3709'
 id: 3710 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3710'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3710'
 id: 3711 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '3711'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3711'
 id: 3712 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '3712'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3712'
 id: 3713 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3713'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3713'

 id: 3714 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3714'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3714'
 id: 3715 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3715'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3715'
 id: 3716 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '3716'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3716'
 id: 3717 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '3717'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3717'
 id: 3718 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '3718'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3718'
 id: 3719 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3719'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3719'
 id: 3720 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '3720'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3720'
 id: 3721 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3721'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3721'
 id: 3722 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3722'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3722'
 id: 3723 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3723'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3723'
 id: 3724 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3724'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3724'
 id: 3725 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3725'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3725'
 id: 3726 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3726'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3726'
 id: 3727 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3727'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3727'
 id: 3728 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3728'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3728'
 id: 3729 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3729'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3729'
 id: 3730 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3730'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3730'
 id: 3731 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3731'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3731'
 id: 3732 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3732'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3732'
 id: 3733 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '3733'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3733'
 id: 3734 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3734'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3734'
 id: 3735 // word: 28
UPDATE job_vacancies SET domain_id =  '28' where raw_id = '3735'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3735'
 id: 3736 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3736'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3736'
 id: 3737 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3737'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3737'
 id: 3738 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3738'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3738'
 id: 3739 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '3739'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3739'
 id: 3740 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3740'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3740'
 id: 3741 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '3741'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3741'
 id: 3742 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '3742'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3742'
 id: 3743 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3743'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3743'
 id: 3744 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3744'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3744'
 id: 3745 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3745'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3745'
 id: 3746 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3746'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3746'
 id: 3747 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '3747'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3747'
 id: 3748 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '3748'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3748'
 id: 3749 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '3749'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3749'
 id: 3750 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '3750'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3750'
 id: 3751 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '3751'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3751'
 id: 3752 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3752'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3752'
 id: 3753 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3753'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3753'
 id: 3754 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3754'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3754'
 id: 3755 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3755'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3755'
 id: 3756 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3756'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3756'
 id: 3757 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3757'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3757'
 id: 3758 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3758'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3758'
 id: 3759 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3759'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3759'
 id: 3760 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '3760'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3760'
 id: 3761 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3761'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3761'
 id: 3762 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3762'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3762'
 id: 3763 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3763'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3763'
 id: 3764 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3764'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3764'
 id: 3765 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3765'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3765'

 id: 3766 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3766'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3766'
 id: 3767 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '3767'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3767'
 id: 3768 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3768'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3768'
 id: 3769 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '3769'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3769'
 id: 3770 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '3770'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3770'
 id: 3771 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3771'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3771'
 id: 3772 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '3772'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3772'
 id: 3773 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3773'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3773'
 id: 3774 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '3774'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3774'
 id: 3775 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3775'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3775'
 id: 3776 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3776'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3776'
 id: 3777 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3777'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3777'
 id: 3778 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '3778'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3778'
 id: 3779 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '3779'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3779'
 id: 3780 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '3780'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3780'
 id: 3781 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3781'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3781'
 id: 3782 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3782'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3782'
 id: 3783 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3783'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3783'
 id: 3784 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '3784'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3784'
 id: 3785 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3785'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3785'
 id: 3786 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3786'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3786'
 id: 3787 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3787'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3787'
 id: 3788 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3788'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3788'
 id: 3789 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3789'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3789'
 id: 3790 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3790'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3790'
 id: 3791 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3791'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3791'
 id: 3792 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '3792'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3792'
 id: 3793 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3793'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3793'
 id: 3794 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3794'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3794'
 id: 3795 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '3795'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3795'
 id: 3796 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '3796'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3796'
 id: 3797 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3797'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3797'
 id: 3798 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3798'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3798'
 id: 3799 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3799'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3799'
 id: 3800 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3800'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3800'
 id: 3801 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3801'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3801'
 id: 3802 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3802'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3802'
 id: 3803 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3803'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3803'
 id: 3804 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3804'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3804'
 id: 3805 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3805'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3805'
 id: 3806 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '3806'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3806'
 id: 3807 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '3807'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3807'
 id: 3808 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '3808'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3808'
 id: 3809 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3809'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3809'
 id: 3810 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '3810'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3810'
 id: 3811 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '3811'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3811'
 id: 3812 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3812'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3812'
 id: 3813 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '3813'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3813'
 id: 3814 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '3814'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3814'
 id: 3815 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3815'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3815'
 id: 3816 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3816'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3816'
 id: 3817 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3817'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3817'
 id: 3818 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '3818'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3818'
 id: 3819 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '3819'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3819'
 id: 3820 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '3820'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3820'
 id: 3821 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '3821'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3821'
 id: 3822 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3822'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3822'
 id: 3823 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '3823'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3823'
 id: 3824 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3824'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3824'
 id: 3825 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '3825'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3825'
 id: 3826 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3826'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3826'
 id: 3827 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3827'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3827'
 id: 3828 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3828'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3828'
 id: 3829 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '3829'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3829'
 id: 3830 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3830'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3830'
 id: 3831 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '3831'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3831'
 id: 3832 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3832'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3832'
 id: 3833 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3833'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3833'
 id: 3834 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '3834'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3834'
 id: 3835 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '3835'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3835'
 id: 3836 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '3836'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3836'
 id: 3837 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '3837'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3837'
 id: 3838 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '3838'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3838'
 id: 3839 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '3839'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3839'
 id: 3840 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3840'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3840'
 id: 3841 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '3841'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3841'
 id: 3842 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3842'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3842'
 id: 3843 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3843'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3843'
 id: 3844 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3844'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3844'
 id: 3845 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3845'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3845'
 id: 3846 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '3846'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3846'
 id: 3847 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3847'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3847'
 id: 3848 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3848'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3848'
 id: 3849 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '3849'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3849'
 id: 3850 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '3850'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3850'
 id: 3851 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3851'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3851'
 id: 3852 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '3852'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3852'
 id: 3853 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '3853'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3853'
 id: 3854 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3854'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3854'
 id: 3855 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3855'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3855'
 id: 3856 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '3856'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3856'
 id: 3857 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '3857'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3857'
 id: 3858 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3858'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3858'
 id: 3859 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3859'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3859'
 id: 3860 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3860'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3860'
 id: 3861 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '3861'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3861'
 id: 3862 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3862'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3862'
 id: 3863 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '3863'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3863'
 id: 3864 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '3864'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3864'
 id: 3865 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '3865'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3865'
 id: 3866 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '3866'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3866'
 id: 3867 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '3867'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3867'
 id: 3868 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '3868'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3868'
 id: 3869 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3869'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3869'
 id: 3870 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '3870'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3870'
 id: 3871 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3871'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3871'
 id: 3872 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3872'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3872'
 id: 3873 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '3873'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3873'
 id: 3874 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '3874'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3874'
 id: 3875 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '3875'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3875'
 id: 3876 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '3876'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3876'
 id: 3877 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3877'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3877'
 id: 3878 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '3878'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3878'
 id: 3879 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3879'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3879'
 id: 3880 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3880'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3880'
 id: 3881 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3881'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3881'
 id: 3882 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3882'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3882'
 id: 3883 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '3883'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3883'
 id: 3884 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3884'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3884'
 id: 3885 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3885'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3885'
 id: 3886 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3886'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3886'
 id: 3887 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3887'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3887'
 id: 3888 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '3888'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3888'
 id: 3889 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '3889'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3889'
 id: 3890 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '3890'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3890'
 id: 3891 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3891'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3891'
 id: 3892 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3892'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3892'
 id: 3893 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '3893'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3893'
 id: 3894 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '3894'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3894'
 id: 3895 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3895'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3895'
 id: 3896 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '3896'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3896'
 id: 3897 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '3897'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3897'
 id: 3898 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '3898'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3898'
 id: 3899 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '3899'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3899'
 id: 3900 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '3900'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3900'
 id: 3901 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3901'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3901'
 id: 3902 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '3902'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3902'
 id: 3903 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '3903'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3903'
 id: 3904 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3904'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3904'
 id: 3905 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3905'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3905'
 id: 3906 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3906'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3906'
 id: 3907 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3907'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3907'
 id: 3908 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '3908'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3908'
 id: 3909 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3909'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3909'
 id: 3910 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3910'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3910'
 id: 3911 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3911'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3911'
 id: 3912 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3912'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3912'
 id: 3913 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '3913'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3913'
 id: 3914 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3914'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3914'
 id: 3915 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3915'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3915'
 id: 3916 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3916'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3916'
 id: 3917 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '3917'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3917'
 id: 3918 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3918'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3918'
 id: 3919 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3919'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3919'
 id: 3920 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '3920'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3920'
 id: 3921 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3921'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3921'
 id: 3922 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3922'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3922'
 id: 3923 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '3923'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3923'
 id: 3924 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3924'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3924'
 id: 3925 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '3925'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3925'
 id: 3926 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3926'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3926'
 id: 3927 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '3927'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3927'
 id: 3928 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3928'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3928'
 id: 3929 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '3929'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3929'
 id: 3930 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3930'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3930'
 id: 3931 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '3931'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3931'
 id: 3932 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3932'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3932'
 id: 3933 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3933'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3933'
 id: 3934 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '3934'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3934'
 id: 3935 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3935'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3935'
 id: 3936 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '3936'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3936'
 id: 3937 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3937'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3937'
 id: 3938 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '3938'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3938'
 id: 3939 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3939'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3939'
 id: 3940 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '3940'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3940'
 id: 3941 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3941'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3941'
 id: 3942 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '3942'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3942'
 id: 3943 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '3943'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3943'
 id: 3944 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3944'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3944'
 id: 3945 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '3945'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3945'
 id: 3946 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3946'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3946'
 id: 3947 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3947'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3947'
 id: 3948 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '3948'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3948'
 id: 3949 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3949'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3949'
 id: 3950 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3950'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3950'
 id: 3951 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '3951'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3951'
 id: 3952 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3952'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3952'
 id: 3953 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3953'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3953'
 id: 3954 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '3954'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3954'
 id: 3955 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3955'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3955'
 id: 3956 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '3956'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3956'
 id: 3957 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3957'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3957'
 id: 3958 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3958'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3958'
 id: 3959 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '3959'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3959'
 id: 3960 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3960'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3960'
 id: 3961 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3961'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3961'
 id: 3962 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '3962'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3962'
 id: 3963 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3963'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3963'
 id: 3964 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3964'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3964'
 id: 3965 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3965'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3965'
 id: 3966 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '3966'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3966'
 id: 3967 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3967'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3967'
 id: 3968 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '3968'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3968'
 id: 3969 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '3969'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3969'
 id: 3970 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3970'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3970'
 id: 3971 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3971'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3971'
 id: 3972 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '3972'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3972'

 id: 3973 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3973'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3973'
 id: 3974 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '3974'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3974'
 id: 3975 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '3975'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3975'
 id: 3976 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '3976'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3976'
 id: 3977 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '3977'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3977'
 id: 3978 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3978'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3978'
 id: 3979 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '3979'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3979'
 id: 3980 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '3980'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3980'
 id: 3981 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3981'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3981'
 id: 3982 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '3982'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3982'
 id: 3983 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '3983'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3983'
 id: 3984 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3984'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3984'
 id: 3985 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '3985'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3985'
 id: 3986 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '3986'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3986'
 id: 3987 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3987'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3987'
 id: 3988 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '3988'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3988'
 id: 3989 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3989'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3989'
 id: 3990 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3990'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3990'
 id: 3991 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '3991'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3991'
 id: 3992 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '3992'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3992'
 id: 3993 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '3993'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3993'
 id: 3994 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '3994'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3994'
 id: 3995 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '3995'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3995'
 id: 3996 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '3996'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3996'
 id: 3997 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '3997'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3997'
 id: 3998 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '3998'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3998'
 id: 3999 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '3999'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '3999'
 id: 4000 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '4000'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4000'
 id: 4001 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4001'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4001'
 id: 4002 // word: 28
UPDATE job_vacancies SET domain_id =  '28' where raw_id = '4002'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4002'
 id: 4003 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4003'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4003'
 id: 4004 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '4004'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4004'
 id: 4005 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '4005'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4005'
 id: 4006 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '4006'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4006'
 id: 4007 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '4007'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4007'
 id: 4008 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '4008'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4008'
 id: 4009 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '4009'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4009'
 id: 4010 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4010'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4010'
 id: 4011 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '4011'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4011'
 id: 4012 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4012'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4012'
 id: 4013 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '4013'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4013'
 id: 4014 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4014'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4014'
 id: 4015 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '4015'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4015'
 id: 4016 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '4016'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4016'
 id: 4017 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4017'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4017'
 id: 4018 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '4018'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4018'
 id: 4019 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4019'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4019'
 id: 4020 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4020'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4020'
 id: 4021 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4021'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4021'
 id: 4022 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4022'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4022'
 id: 4023 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '4023'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4023'
 id: 4024 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '4024'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4024'
 id: 4025 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4025'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4025'
 id: 4026 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '4026'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4026'
 id: 4027 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4027'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4027'
 id: 4028 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4028'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4028'
 id: 4029 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '4029'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4029'
 id: 4030 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '4030'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4030'
 id: 4031 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4031'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4031'
 id: 4032 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4032'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4032'
 id: 4033 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4033'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4033'
 id: 4034 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4034'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4034'
 id: 4035 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4035'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4035'
 id: 4036 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4036'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4036'
 id: 4037 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4037'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4037'
 id: 4038 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4038'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4038'
 id: 4039 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4039'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4039'
 id: 4040 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4040'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4040'
 id: 4041 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4041'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4041'
 id: 4042 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '4042'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4042'
 id: 4043 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4043'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4043'
 id: 4044 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4044'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4044'
 id: 4045 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4045'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4045'
 id: 4046 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4046'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4046'
 id: 4047 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '4047'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4047'
 id: 4048 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4048'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4048'
 id: 4049 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4049'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4049'
 id: 4050 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4050'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4050'
 id: 4051 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '4051'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4051'
 id: 4052 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '4052'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4052'
 id: 4053 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4053'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4053'
 id: 4054 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4054'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4054'
 id: 4055 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '4055'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4055'
 id: 4056 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4056'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4056'
 id: 4057 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4057'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4057'
 id: 4058 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4058'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4058'
 id: 4059 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4059'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4059'
 id: 4060 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '4060'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4060'
 id: 4061 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4061'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4061'
 id: 4062 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4062'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4062'
 id: 4063 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4063'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4063'
 id: 4064 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4064'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4064'
 id: 4065 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4065'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4065'
 id: 4066 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '4066'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4066'
 id: 4067 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '4067'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4067'
 id: 4068 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4068'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4068'
 id: 4069 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4069'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4069'
 id: 4070 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '4070'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4070'
 id: 4071 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '4071'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4071'
 id: 4072 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4072'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4072'
 id: 4073 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '4073'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4073'
 id: 4074 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '4074'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4074'
 id: 4075 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '4075'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4075'
 id: 4076 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4076'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4076'
 id: 4077 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4077'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4077'
 id: 4078 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4078'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4078'
 id: 4079 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '4079'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4079'
 id: 4080 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4080'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4080'
 id: 4081 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '4081'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4081'
 id: 4082 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '4082'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4082'
 id: 4083 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4083'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4083'
 id: 4084 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '4084'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4084'
 id: 4085 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '4085'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4085'
 id: 4086 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '4086'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4086'
 id: 4087 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4087'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4087'
 id: 4088 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4088'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4088'
 id: 4089 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '4089'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4089'
 id: 4090 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4090'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4090'
 id: 4091 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4091'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4091'
 id: 4092 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4092'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4092'
 id: 4093 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '4093'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4093'
 id: 4094 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4094'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4094'
 id: 4095 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4095'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4095'
 id: 4096 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4096'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4096'
 id: 4097 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4097'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4097'
 id: 4098 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '4098'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4098'
 id: 4099 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4099'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4099'
 id: 4100 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4100'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4100'
 id: 4101 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '4101'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4101'
 id: 4102 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '4102'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4102'
 id: 4103 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4103'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4103'
 id: 4104 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '4104'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4104'
 id: 4105 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '4105'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4105'
 id: 4106 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4106'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4106'
 id: 4107 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4107'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4107'
 id: 4108 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4108'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4108'
 id: 4109 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '4109'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4109'
 id: 4110 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '4110'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4110'
 id: 4111 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4111'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4111'
 id: 4112 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '4112'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4112'
 id: 4113 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '4113'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4113'
 id: 4114 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4114'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4114'
 id: 4115 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4115'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4115'
 id: 4116 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '4116'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4116'
 id: 4117 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '4117'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4117'
 id: 4118 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4118'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4118'
 id: 4119 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '4119'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4119'
 id: 4120 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '4120'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4120'
 id: 4121 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '4121'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4121'
 id: 4122 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4122'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4122'
 id: 4123 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4123'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4123'
 id: 4124 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '4124'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4124'
 id: 4125 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4125'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4125'
 id: 4126 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4126'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4126'
 id: 4127 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4127'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4127'
 id: 4128 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4128'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4128'
 id: 4129 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4129'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4129'
 id: 4130 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4130'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4130'

 id: 4131 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4131'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4131'
 id: 4132 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '4132'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4132'
 id: 4133 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4133'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4133'
 id: 4134 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4134'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4134'
 id: 4135 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4135'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4135'
 id: 4136 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '4136'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4136'
 id: 4137 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '4137'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4137'
 id: 4138 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4138'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4138'
 id: 4139 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4139'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4139'
 id: 4140 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4140'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4140'
 id: 4141 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '4141'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4141'
 id: 4142 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4142'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4142'
 id: 4143 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4143'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4143'
 id: 4144 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4144'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4144'
 id: 4145 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4145'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4145'
 id: 4146 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4146'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4146'
 id: 4147 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '4147'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4147'
 id: 4148 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4148'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4148'
 id: 4149 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '4149'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4149'
 id: 4150 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '4150'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4150'
 id: 4151 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4151'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4151'
 id: 4152 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '4152'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4152'
 id: 4153 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4153'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4153'
 id: 4154 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4154'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4154'
 id: 4155 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4155'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4155'
 id: 4156 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '4156'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4156'
 id: 4157 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4157'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4157'
 id: 4158 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '4158'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4158'
 id: 4159 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4159'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4159'
 id: 4160 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4160'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4160'
 id: 4161 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '4161'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4161'
 id: 4162 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '4162'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4162'
 id: 4163 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4163'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4163'
 id: 4164 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '4164'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4164'
 id: 4165 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '4165'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4165'
 id: 4166 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '4166'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4166'
 id: 4167 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4167'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4167'
 id: 4168 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4168'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4168'
 id: 4169 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4169'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4169'
 id: 4170 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4170'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4170'
 id: 4171 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '4171'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4171'
 id: 4172 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '4172'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4172'
 id: 4173 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '4173'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4173'
 id: 4174 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4174'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4174'
 id: 4175 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4175'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4175'
 id: 4176 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '4176'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4176'
 id: 4177 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '4177'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4177'
 id: 4178 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4178'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4178'
 id: 4179 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4179'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4179'
 id: 4180 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '4180'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4180'
 id: 4181 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '4181'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4181'
 id: 4182 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4182'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4182'

 id: 4183 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '4183'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4183'
 id: 4184 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4184'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4184'
 id: 4185 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4185'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4185'
 id: 4186 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4186'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4186'
 id: 4187 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4187'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4187'
 id: 4188 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '4188'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4188'
 id: 4189 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4189'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4189'
 id: 4190 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4190'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4190'
 id: 4191 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '4191'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4191'
 id: 4192 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '4192'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4192'
 id: 4193 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4193'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4193'
 id: 4194 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '4194'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4194'
 id: 4195 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '4195'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4195'
 id: 4196 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '4196'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4196'
 id: 4197 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4197'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4197'
 id: 4198 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '4198'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4198'
 id: 4199 // word: 14
UPDATE job_vacancies SET domain_id =  '14' where raw_id = '4199'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4199'
 id: 4200 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4200'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4200'
 id: 4201 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '4201'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4201'
 id: 4202 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '4202'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4202'
 id: 4203 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4203'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4203'
 id: 4204 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4204'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4204'
 id: 4205 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4205'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4205'
 id: 4206 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '4206'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4206'
 id: 4207 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4207'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4207'
 id: 4208 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4208'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4208'
 id: 4209 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4209'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4209'
 id: 4210 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '4210'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4210'
 id: 4211 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4211'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4211'
 id: 4212 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '4212'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4212'
 id: 4213 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4213'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4213'
 id: 4214 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4214'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4214'
 id: 4215 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '4215'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4215'
 id: 4216 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4216'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4216'
 id: 4217 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '4217'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4217'
 id: 4218 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4218'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4218'
 id: 4219 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4219'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4219'
 id: 4220 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4220'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4220'
 id: 4221 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4221'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4221'
 id: 4222 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4222'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4222'
 id: 4223 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4223'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4223'
 id: 4224 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4224'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4224'
 id: 4225 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4225'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4225'
 id: 4226 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '4226'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4226'
 id: 4227 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4227'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4227'
 id: 4228 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4228'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4228'
 id: 4229 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4229'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4229'
 id: 4230 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4230'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4230'
 id: 4231 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '4231'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4231'
 id: 4232 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '4232'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4232'
 id: 4233 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4233'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4233'
 id: 4234 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '4234'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4234'
 id: 4235 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '4235'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4235'

 id: 4236 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4236'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4236'
 id: 4237 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '4237'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4237'
 id: 4238 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '4238'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4238'
 id: 4239 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4239'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4239'
 id: 4240 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '4240'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4240'
 id: 4241 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4241'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4241'
 id: 4242 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4242'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4242'
 id: 4243 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4243'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4243'
 id: 4244 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4244'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4244'
 id: 4245 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4245'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4245'
 id: 4246 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '4246'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4246'
 id: 4247 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4247'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4247'
 id: 4248 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4248'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4248'
 id: 4249 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '4249'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4249'
 id: 4250 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4250'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4250'
 id: 4251 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4251'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4251'
 id: 4252 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4252'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4252'
 id: 4253 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4253'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4253'
 id: 4254 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '4254'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4254'
 id: 4255 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4255'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4255'
 id: 4256 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4256'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4256'
 id: 4257 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4257'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4257'
 id: 4258 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4258'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4258'
 id: 4259 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4259'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4259'
 id: 4260 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4260'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4260'
 id: 4261 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4261'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4261'
 id: 4262 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4262'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4262'
 id: 4263 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '4263'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4263'
 id: 4264 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4264'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4264'
 id: 4265 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4265'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4265'
 id: 4266 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '4266'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4266'
 id: 4267 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4267'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4267'
 id: 4268 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '4268'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4268'
 id: 4269 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4269'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4269'
 id: 4270 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '4270'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4270'
 id: 4271 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4271'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4271'
 id: 4272 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4272'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4272'
 id: 4273 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4273'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4273'
 id: 4274 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4274'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4274'
 id: 4275 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '4275'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4275'
 id: 4276 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4276'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4276'
 id: 4277 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4277'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4277'
 id: 4278 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4278'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4278'
 id: 4279 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4279'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4279'
 id: 4280 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4280'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4280'
 id: 4281 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4281'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4281'
 id: 4282 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '4282'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4282'
 id: 4283 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4283'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4283'
 id: 4284 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '4284'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4284'
 id: 4285 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4285'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4285'
 id: 4286 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '4286'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4286'
 id: 4287 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4287'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4287'
 id: 4288 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4288'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4288'
 id: 4289 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '4289'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4289'
 id: 4290 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4290'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4290'
 id: 4291 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '4291'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4291'
 id: 4292 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '4292'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4292'
 id: 4293 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '4293'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4293'
 id: 4294 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4294'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4294'
 id: 4295 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '4295'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4295'
 id: 4296 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4296'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4296'
 id: 4297 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4297'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4297'
 id: 4298 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '4298'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4298'
 id: 4299 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4299'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4299'
 id: 4300 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '4300'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4300'
 id: 4301 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4301'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4301'
 id: 4302 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4302'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4302'
 id: 4303 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '4303'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4303'
 id: 4304 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '4304'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4304'
 id: 4305 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '4305'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4305'
 id: 4306 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '4306'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4306'
 id: 4307 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4307'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4307'
 id: 4308 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '4308'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4308'
 id: 4309 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4309'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4309'
 id: 4310 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '4310'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4310'
 id: 4311 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4311'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4311'
 id: 4312 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4312'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4312'
 id: 4313 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '4313'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4313'
 id: 4314 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '4314'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4314'
 id: 4315 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '4315'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4315'
 id: 4316 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '4316'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4316'
 id: 4317 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4317'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4317'
 id: 4318 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4318'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4318'
 id: 4319 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4319'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4319'
 id: 4320 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '4320'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4320'
 id: 4321 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '4321'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4321'
 id: 4322 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '4322'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4322'
 id: 4323 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4323'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4323'
 id: 4324 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4324'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4324'
 id: 4325 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '4325'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4325'
 id: 4326 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4326'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4326'
 id: 4327 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4327'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4327'
 id: 4328 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '4328'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4328'
 id: 4329 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4329'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4329'
 id: 4330 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4330'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4330'
 id: 4331 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4331'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4331'
 id: 4332 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '4332'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4332'
 id: 4333 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4333'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4333'
 id: 4334 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4334'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4334'
 id: 4335 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4335'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4335'
 id: 4336 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4336'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4336'
 id: 4337 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4337'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4337'
 id: 4338 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4338'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4338'
 id: 4339 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '4339'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4339'
 id: 4340 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '4340'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4340'
 id: 4341 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4341'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4341'
 id: 4342 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4342'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4342'
 id: 4343 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4343'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4343'
 id: 4344 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '4344'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4344'
 id: 4345 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4345'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4345'
 id: 4346 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4346'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4346'
 id: 4347 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4347'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4347'
 id: 4348 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4348'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4348'
 id: 4349 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '4349'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4349'
 id: 4350 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4350'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4350'
 id: 4351 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4351'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4351'
 id: 4352 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4352'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4352'
 id: 4353 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '4353'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4353'
 id: 4354 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4354'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4354'
 id: 4355 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '4355'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4355'
 id: 4356 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4356'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4356'
 id: 4357 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4357'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4357'
 id: 4358 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4358'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4358'
 id: 4359 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '4359'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4359'
 id: 4360 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '4360'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4360'
 id: 4361 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '4361'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4361'
 id: 4362 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4362'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4362'
 id: 4363 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4363'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4363'
 id: 4364 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '4364'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4364'
 id: 4365 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '4365'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4365'
 id: 4366 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '4366'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4366'
 id: 4367 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4367'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4367'
 id: 4368 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '4368'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4368'
 id: 4369 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4369'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4369'
 id: 4370 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '4370'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4370'
 id: 4371 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4371'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4371'
 id: 4372 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4372'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4372'
 id: 4373 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '4373'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4373'
 id: 4374 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '4374'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4374'
 id: 4375 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '4375'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4375'
 id: 4376 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '4376'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4376'
 id: 4377 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4377'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4377'
 id: 4378 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4378'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4378'
 id: 4379 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4379'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4379'
 id: 4380 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4380'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4380'
 id: 4381 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '4381'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4381'
 id: 4382 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '4382'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4382'
 id: 4383 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '4383'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4383'
 id: 4384 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4384'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4384'
 id: 4385 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '4385'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4385'
 id: 4386 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '4386'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4386'
 id: 4387 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '4387'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4387'
 id: 4388 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4388'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4388'
 id: 4389 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4389'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4389'
 id: 4390 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4390'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4390'
 id: 4391 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4391'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4391'
 id: 4392 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4392'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4392'
 id: 4393 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '4393'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4393'
 id: 4394 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4394'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4394'
 id: 4395 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4395'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4395'
 id: 4396 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '4396'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4396'
 id: 4397 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '4397'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4397'
 id: 4398 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '4398'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4398'
 id: 4399 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '4399'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4399'
 id: 4400 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4400'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4400'
 id: 4401 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4401'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4401'
 id: 4402 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4402'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4402'
 id: 4403 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '4403'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4403'
 id: 4404 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '4404'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4404'
 id: 4405 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '4405'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4405'
 id: 4406 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4406'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4406'
 id: 4407 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4407'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4407'
 id: 4408 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '4408'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4408'
 id: 4409 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '4409'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4409'
 id: 4410 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4410'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4410'
 id: 4411 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '4411'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4411'
 id: 4412 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4412'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4412'
 id: 4413 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '4413'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4413'
 id: 4414 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4414'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4414'
 id: 4415 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4415'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4415'
 id: 4416 // word: 52
UPDATE job_vacancies SET domain_id =  '52' where raw_id = '4416'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4416'
 id: 4417 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4417'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4417'
 id: 4418 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '4418'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4418'
 id: 4419 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4419'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4419'
 id: 4420 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '4420'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4420'
 id: 4421 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4421'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4421'
 id: 4422 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4422'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4422'
 id: 4423 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '4423'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4423'
 id: 4424 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4424'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4424'
 id: 4425 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4425'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4425'
 id: 4426 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '4426'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4426'
 id: 4427 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '4427'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4427'
 id: 4428 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '4428'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4428'
 id: 4429 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4429'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4429'
 id: 4430 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4430'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4430'
 id: 4431 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '4431'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4431'
 id: 4432 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4432'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4432'
 id: 4433 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '4433'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4433'
 id: 4434 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '4434'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4434'
 id: 4435 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '4435'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4435'
 id: 4436 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '4436'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4436'
 id: 4437 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4437'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4437'
 id: 4438 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4438'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4438'
 id: 4439 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4439'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4439'
 id: 4440 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4440'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4440'
 id: 4441 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4441'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4441'
 id: 4442 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4442'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4442'
 id: 4443 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '4443'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4443'
 id: 4444 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4444'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4444'
 id: 4445 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4445'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4445'
 id: 4446 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '4446'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4446'
 id: 4447 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4447'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4447'
 id: 4448 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '4448'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4448'
 id: 4449 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '4449'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4449'
 id: 4450 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4450'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4450'
 id: 4451 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4451'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4451'
 id: 4452 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '4452'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4452'
 id: 4453 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '4453'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4453'
 id: 4454 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '4454'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4454'
 id: 4455 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4455'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4455'
 id: 4456 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '4456'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4456'
 id: 4457 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '4457'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4457'
 id: 4458 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '4458'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4458'
 id: 4459 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '4459'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4459'
 id: 4460 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4460'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4460'
 id: 4461 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '4461'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4461'
 id: 4462 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '4462'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4462'
 id: 4463 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4463'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4463'
 id: 4464 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4464'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4464'
 id: 4465 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '4465'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4465'
 id: 4466 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4466'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4466'
 id: 4467 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4467'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4467'
 id: 4468 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '4468'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4468'
 id: 4469 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '4469'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4469'
 id: 4470 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '4470'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4470'
 id: 4471 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4471'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4471'
 id: 4472 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4472'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4472'
 id: 4473 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4473'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4473'
 id: 4474 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4474'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4474'
 id: 4475 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '4475'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4475'
 id: 4476 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4476'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4476'
 id: 4477 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4477'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4477'
 id: 4478 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '4478'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4478'
 id: 4479 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4479'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4479'
 id: 4480 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4480'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4480'
 id: 4481 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '4481'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4481'
 id: 4482 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4482'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4482'
 id: 4483 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4483'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4483'
 id: 4484 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4484'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4484'
 id: 4485 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '4485'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4485'
 id: 4486 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4486'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4486'
 id: 4487 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4487'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4487'
 id: 4488 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4488'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4488'
 id: 4489 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '4489'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4489'
 id: 4490 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4490'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4490'
 id: 4491 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4491'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4491'
 id: 4492 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4492'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4492'
 id: 4493 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4493'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4493'
 id: 4494 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4494'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4494'
 id: 4495 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4495'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4495'
 id: 4496 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4496'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4496'
 id: 4497 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4497'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4497'
 id: 4498 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4498'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4498'
 id: 4499 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4499'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4499'
 id: 4500 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4500'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4500'
 id: 4501 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4501'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4501'
 id: 4502 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4502'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4502'
 id: 4503 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '4503'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4503'
 id: 4504 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '4504'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4504'
 id: 4505 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4505'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4505'
 id: 4506 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4506'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4506'
 id: 4507 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '4507'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4507'
 id: 4508 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '4508'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4508'
 id: 4509 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4509'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4509'
 id: 4510 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '4510'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4510'
 id: 4511 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4511'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4511'
 id: 4512 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4512'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4512'
 id: 4513 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4513'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4513'
 id: 4514 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4514'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4514'
 id: 4515 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4515'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4515'
 id: 4516 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4516'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4516'
 id: 4517 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '4517'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4517'
 id: 4518 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4518'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4518'
 id: 4519 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4519'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4519'
 id: 4520 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4520'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4520'
 id: 4521 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4521'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4521'
 id: 4522 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4522'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4522'
 id: 4523 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '4523'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4523'
 id: 4524 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '4524'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4524'
 id: 4525 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4525'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4525'
 id: 4526 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4526'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4526'
 id: 4527 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '4527'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4527'
 id: 4528 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4528'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4528'
 id: 4529 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4529'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4529'
 id: 4530 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4530'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4530'
 id: 4531 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4531'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4531'
 id: 4532 // word: 53
UPDATE job_vacancies SET domain_id =  '53' where raw_id = '4532'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4532'
 id: 4533 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '4533'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4533'
 id: 4534 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '4534'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4534'
 id: 4535 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4535'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4535'
 id: 4536 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '4536'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4536'
 id: 4537 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4537'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4537'
 id: 4538 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '4538'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4538'
 id: 4539 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '4539'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4539'
 id: 4540 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4540'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4540'
 id: 4541 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '4541'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4541'
 id: 4542 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '4542'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4542'
 id: 4543 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '4543'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4543'
 id: 4544 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4544'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4544'
 id: 4545 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4545'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4545'
 id: 4546 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4546'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4546'
 id: 4547 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4547'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4547'
 id: 4548 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '4548'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4548'
 id: 4549 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4549'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4549'
 id: 4550 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4550'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4550'
 id: 4551 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '4551'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4551'
 id: 4552 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4552'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4552'
 id: 4553 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4553'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4553'
 id: 4554 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '4554'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4554'
 id: 4555 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4555'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4555'
 id: 4556 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '4556'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4556'
 id: 4557 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '4557'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4557'
 id: 4558 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4558'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4558'
 id: 4559 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4559'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4559'
 id: 4560 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '4560'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4560'
 id: 4561 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4561'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4561'
 id: 4562 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4562'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4562'
 id: 4563 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '4563'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4563'
 id: 4564 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4564'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4564'
 id: 4565 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4565'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4565'
 id: 4566 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4566'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4566'
 id: 4567 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4567'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4567'
 id: 4568 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4568'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4568'
 id: 4569 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '4569'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4569'
 id: 4570 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4570'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4570'
 id: 4571 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '4571'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4571'
 id: 4572 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4572'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4572'
 id: 4573 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4573'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4573'
 id: 4574 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '4574'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4574'
 id: 4575 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4575'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4575'
 id: 4576 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4576'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4576'
 id: 4577 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '4577'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4577'
 id: 4578 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4578'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4578'
 id: 4579 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4579'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4579'
 id: 4580 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4580'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4580'
 id: 4581 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4581'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4581'
 id: 4582 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4582'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4582'
 id: 4583 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4583'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4583'
 id: 4584 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4584'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4584'
 id: 4585 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4585'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4585'
 id: 4586 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4586'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4586'
 id: 4587 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4587'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4587'
 id: 4588 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4588'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4588'
 id: 4589 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4589'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4589'
 id: 4590 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4590'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4590'
 id: 4591 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4591'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4591'
 id: 4592 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '4592'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4592'
 id: 4593 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4593'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4593'
 id: 4594 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4594'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4594'
 id: 4595 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4595'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4595'
 id: 4596 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4596'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4596'
 id: 4597 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4597'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4597'

 id: 4598 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '4598'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4598'
 id: 4599 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '4599'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4599'
 id: 4600 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4600'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4600'
 id: 4601 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4601'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4601'
 id: 4602 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '4602'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4602'
 id: 4603 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4603'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4603'
 id: 4604 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '4604'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4604'
 id: 4605 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4605'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4605'
 id: 4606 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4606'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4606'
 id: 4607 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4607'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4607'
 id: 4608 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4608'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4608'
 id: 4609 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4609'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4609'
 id: 4610 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '4610'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4610'
 id: 4611 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4611'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4611'
 id: 4612 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4612'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4612'
 id: 4613 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4613'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4613'
 id: 4614 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4614'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4614'
 id: 4615 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4615'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4615'
 id: 4616 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4616'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4616'
 id: 4617 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4617'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4617'
 id: 4618 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4618'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4618'
 id: 4619 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '4619'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4619'
 id: 4620 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4620'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4620'
 id: 4621 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4621'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4621'
 id: 4622 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '4622'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4622'
 id: 4623 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4623'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4623'
 id: 4624 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4624'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4624'
 id: 4625 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4625'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4625'
 id: 4626 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4626'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4626'
 id: 4627 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4627'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4627'
 id: 4628 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '4628'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4628'
 id: 4629 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4629'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4629'
 id: 4630 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '4630'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4630'
 id: 4631 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4631'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4631'
 id: 4632 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4632'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4632'
 id: 4633 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4633'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4633'
 id: 4634 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4634'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4634'
 id: 4635 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4635'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4635'
 id: 4636 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4636'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4636'
 id: 4637 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4637'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4637'
 id: 4638 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '4638'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4638'
 id: 4639 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '4639'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4639'
 id: 4640 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '4640'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4640'
 id: 4641 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4641'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4641'
 id: 4642 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '4642'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4642'
 id: 4643 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4643'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4643'
 id: 4644 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '4644'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4644'
 id: 4645 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4645'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4645'
 id: 4646 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4646'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4646'
 id: 4647 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4647'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4647'
 id: 4648 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4648'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4648'
 id: 4649 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4649'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4649'
 id: 4650 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4650'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4650'
 id: 4651 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4651'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4651'
 id: 4652 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4652'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4652'
 id: 4653 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '4653'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4653'
 id: 4654 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4654'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4654'
 id: 4655 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4655'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4655'
 id: 4656 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '4656'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4656'
 id: 4657 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4657'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4657'
 id: 4658 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4658'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4658'
 id: 4659 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '4659'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4659'
 id: 4660 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '4660'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4660'
 id: 4661 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4661'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4661'
 id: 4662 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4662'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4662'
 id: 4663 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '4663'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4663'
 id: 4664 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '4664'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4664'
 id: 4665 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '4665'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4665'
 id: 4666 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4666'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4666'
 id: 4667 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4667'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4667'
 id: 4668 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4668'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4668'
 id: 4669 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4669'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4669'
 id: 4670 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4670'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4670'
 id: 4671 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4671'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4671'
 id: 4672 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4672'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4672'
 id: 4673 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '4673'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4673'
 id: 4674 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4674'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4674'
 id: 4675 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '4675'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4675'
 id: 4676 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4676'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4676'
 id: 4677 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '4677'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4677'
 id: 4678 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4678'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4678'
 id: 4679 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '4679'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4679'
 id: 4680 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '4680'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4680'
 id: 4681 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4681'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4681'
 id: 4682 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '4682'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4682'
 id: 4683 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4683'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4683'
 id: 4684 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4684'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4684'
 id: 4685 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '4685'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4685'
 id: 4686 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '4686'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4686'
 id: 4687 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '4687'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4687'
 id: 4688 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4688'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4688'
 id: 4689 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4689'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4689'
 id: 4690 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4690'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4690'
 id: 4691 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4691'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4691'
 id: 4692 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4692'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4692'
 id: 4693 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '4693'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4693'
 id: 4694 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4694'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4694'
 id: 4695 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4695'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4695'
 id: 4696 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4696'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4696'
 id: 4697 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4697'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4697'
 id: 4698 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '4698'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4698'
 id: 4699 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '4699'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4699'
 id: 4700 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4700'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4700'
 id: 4701 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4701'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4701'
 id: 4702 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '4702'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4702'
 id: 4703 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4703'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4703'
 id: 4704 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4704'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4704'
 id: 4705 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4705'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4705'
 id: 4706 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '4706'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4706'
 id: 4707 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4707'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4707'
 id: 4708 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '4708'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4708'
 id: 4709 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4709'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4709'
 id: 4710 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4710'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4710'
 id: 4711 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4711'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4711'
 id: 4712 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '4712'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4712'
 id: 4713 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4713'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4713'
 id: 4714 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4714'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4714'
 id: 4715 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4715'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4715'
 id: 4716 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4716'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4716'
 id: 4717 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4717'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4717'
 id: 4718 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4718'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4718'
 id: 4719 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4719'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4719'
 id: 4720 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '4720'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4720'
 id: 4721 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4721'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4721'
 id: 4722 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4722'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4722'
 id: 4723 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4723'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4723'
 id: 4724 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4724'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4724'
 id: 4725 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4725'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4725'
 id: 4726 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4726'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4726'
 id: 4727 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4727'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4727'
 id: 4728 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4728'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4728'
 id: 4729 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '4729'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4729'
 id: 4730 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '4730'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4730'
 id: 4731 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '4731'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4731'
 id: 4732 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4732'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4732'
 id: 4733 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4733'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4733'
 id: 4734 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4734'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4734'
 id: 4735 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4735'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4735'
 id: 4736 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4736'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4736'
 id: 4737 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4737'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4737'
 id: 4738 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4738'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4738'
 id: 4739 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '4739'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4739'
 id: 4740 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4740'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4740'
 id: 4741 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '4741'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4741'
 id: 4742 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4742'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4742'
 id: 4743 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4743'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4743'
 id: 4744 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '4744'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4744'
 id: 4745 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4745'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4745'
 id: 4746 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '4746'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4746'
 id: 4747 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4747'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4747'
 id: 4748 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '4748'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4748'
 id: 4749 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4749'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4749'
 id: 4750 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4750'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4750'
 id: 4751 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '4751'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4751'

 id: 4752 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '4752'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4752'
 id: 4753 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4753'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4753'
 id: 4754 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4754'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4754'
 id: 4755 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '4755'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4755'
 id: 4756 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4756'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4756'
 id: 4757 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '4757'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4757'
 id: 4758 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4758'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4758'
 id: 4759 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '4759'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4759'
 id: 4760 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '4760'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4760'
 id: 4761 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4761'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4761'
 id: 4762 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4762'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4762'
 id: 4763 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '4763'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4763'
 id: 4764 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '4764'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4764'
 id: 4765 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4765'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4765'
 id: 4766 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4766'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4766'
 id: 4767 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4767'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4767'
 id: 4768 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4768'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4768'
 id: 4769 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4769'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4769'
 id: 4770 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4770'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4770'
 id: 4771 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '4771'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4771'
 id: 4772 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4772'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4772'
 id: 4773 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '4773'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4773'
 id: 4774 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4774'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4774'
 id: 4775 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4775'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4775'
 id: 4776 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '4776'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4776'
 id: 4777 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '4777'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4777'
 id: 4778 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '4778'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4778'
 id: 4779 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '4779'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4779'
 id: 4780 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '4780'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4780'
 id: 4781 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '4781'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4781'
 id: 4782 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4782'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4782'
 id: 4783 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '4783'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4783'
 id: 4784 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4784'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4784'
 id: 4785 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4785'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4785'
 id: 4786 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '4786'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4786'
 id: 4787 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4787'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4787'
 id: 4788 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4788'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4788'
 id: 4789 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4789'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4789'
 id: 4790 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4790'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4790'
 id: 4791 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4791'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4791'
 id: 4792 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '4792'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4792'
 id: 4793 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '4793'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4793'
 id: 4794 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '4794'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4794'
 id: 4795 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '4795'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4795'
 id: 4796 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4796'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4796'
 id: 4797 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4797'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4797'
 id: 4798 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4798'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4798'
 id: 4799 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4799'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4799'
 id: 4800 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '4800'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4800'
 id: 4801 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4801'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4801'
 id: 4802 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4802'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4802'
 id: 4803 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4803'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4803'
 id: 4804 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4804'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4804'
 id: 4805 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4805'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4805'
 id: 4806 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '4806'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4806'
 id: 4807 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '4807'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4807'
 id: 4808 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4808'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4808'
 id: 4809 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '4809'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4809'
 id: 4810 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '4810'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4810'
 id: 4811 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '4811'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4811'
 id: 4812 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4812'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4812'
 id: 4813 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4813'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4813'
 id: 4814 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4814'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4814'
 id: 4815 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '4815'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4815'
 id: 4816 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4816'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4816'
 id: 4817 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4817'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4817'
 id: 4818 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4818'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4818'
 id: 4819 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4819'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4819'
 id: 4820 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '4820'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4820'
 id: 4821 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '4821'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4821'
 id: 4822 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4822'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4822'
 id: 4823 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '4823'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4823'
 id: 4824 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4824'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4824'
 id: 4825 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4825'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4825'
 id: 4826 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '4826'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4826'
 id: 4827 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '4827'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4827'
 id: 4828 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '4828'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4828'
 id: 4829 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4829'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4829'
 id: 4830 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '4830'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4830'
 id: 4831 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '4831'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4831'
 id: 4832 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '4832'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4832'
 id: 4833 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4833'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4833'
 id: 4834 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '4834'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4834'
 id: 4835 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4835'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4835'
 id: 4836 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4836'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4836'
 id: 4837 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4837'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4837'
 id: 4838 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '4838'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4838'
 id: 4839 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '4839'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4839'
 id: 4840 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4840'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4840'
 id: 4841 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '4841'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4841'
 id: 4842 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '4842'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4842'
 id: 4843 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '4843'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4843'
 id: 4844 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4844'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4844'
 id: 4845 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '4845'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4845'
 id: 4846 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4846'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4846'
 id: 4847 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '4847'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4847'
 id: 4848 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4848'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4848'
 id: 4849 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '4849'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4849'
 id: 4850 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '4850'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4850'
 id: 4851 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '4851'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4851'
 id: 4852 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '4852'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4852'
 id: 4853 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '4853'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4853'
 id: 4854 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4854'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4854'
 id: 4855 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4855'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4855'
 id: 4856 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4856'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4856'

 id: 4857 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '4857'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4857'
 id: 4858 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4858'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4858'
 id: 4859 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4859'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4859'
 id: 4860 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '4860'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4860'
 id: 4861 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4861'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4861'
 id: 4862 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '4862'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4862'
 id: 4863 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4863'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4863'
 id: 4864 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4864'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4864'
 id: 4865 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '4865'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4865'
 id: 4866 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4866'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4866'
 id: 4867 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4867'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4867'
 id: 4868 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '4868'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4868'
 id: 4869 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4869'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4869'
 id: 4870 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4870'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4870'
 id: 4871 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '4871'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4871'
 id: 4872 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4872'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4872'
 id: 4873 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4873'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4873'
 id: 4874 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4874'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4874'
 id: 4875 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4875'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4875'
 id: 4876 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4876'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4876'
 id: 4877 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4877'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4877'
 id: 4878 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4878'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4878'
 id: 4879 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4879'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4879'
 id: 4880 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '4880'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4880'
 id: 4881 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4881'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4881'
 id: 4882 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '4882'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4882'
 id: 4883 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '4883'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4883'
 id: 4884 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4884'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4884'
 id: 4885 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '4885'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4885'
 id: 4886 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '4886'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4886'
 id: 4887 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '4887'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4887'
 id: 4888 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4888'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4888'
 id: 4889 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4889'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4889'
 id: 4890 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4890'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4890'
 id: 4891 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4891'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4891'
 id: 4892 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4892'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4892'
 id: 4893 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4893'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4893'
 id: 4894 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '4894'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4894'
 id: 4895 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4895'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4895'
 id: 4896 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4896'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4896'
 id: 4897 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '4897'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4897'
 id: 4898 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '4898'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4898'
 id: 4899 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '4899'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4899'
 id: 4900 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4900'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4900'
 id: 4901 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4901'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4901'
 id: 4902 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4902'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4902'
 id: 4903 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '4903'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4903'
 id: 4904 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4904'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4904'
 id: 4905 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '4905'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4905'
 id: 4906 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '4906'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4906'
 id: 4907 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '4907'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4907'
 id: 4908 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '4908'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4908'
 id: 4909 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4909'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4909'
 id: 4910 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4910'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4910'
 id: 4911 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4911'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4911'
 id: 4912 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '4912'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4912'
 id: 4913 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '4913'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4913'
 id: 4914 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4914'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4914'
 id: 4915 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '4915'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4915'
 id: 4916 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4916'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4916'
 id: 4917 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4917'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4917'
 id: 4918 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '4918'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4918'
 id: 4919 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4919'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4919'
 id: 4920 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4920'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4920'
 id: 4921 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4921'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4921'
 id: 4922 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4922'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4922'
 id: 4923 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4923'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4923'
 id: 4924 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '4924'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4924'
 id: 4925 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4925'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4925'
 id: 4926 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4926'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4926'
 id: 4927 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '4927'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4927'
 id: 4928 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '4928'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4928'
 id: 4929 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4929'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4929'
 id: 4930 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4930'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4930'
 id: 4931 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '4931'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4931'
 id: 4932 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '4932'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4932'
 id: 4933 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '4933'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4933'
 id: 4934 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4934'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4934'
 id: 4935 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '4935'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4935'
 id: 4936 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '4936'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4936'
 id: 4937 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4937'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4937'
 id: 4938 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4938'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4938'
 id: 4939 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '4939'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4939'
 id: 4940 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '4940'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4940'
 id: 4941 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4941'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4941'
 id: 4942 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4942'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4942'
 id: 4943 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4943'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4943'
 id: 4944 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4944'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4944'
 id: 4945 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '4945'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4945'
 id: 4946 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '4946'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4946'
 id: 4947 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4947'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4947'
 id: 4948 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '4948'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4948'
 id: 4949 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '4949'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4949'
 id: 4950 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4950'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4950'
 id: 4951 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '4951'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4951'
 id: 4952 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4952'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4952'
 id: 4953 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4953'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4953'
 id: 4954 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4954'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4954'
 id: 4955 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4955'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4955'
 id: 4956 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4956'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4956'
 id: 4957 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '4957'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4957'
 id: 4958 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4958'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4958'

 id: 4959 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4959'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4959'
 id: 4960 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4960'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4960'
 id: 4961 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4961'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4961'
 id: 4962 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '4962'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4962'
 id: 4963 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '4963'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4963'
 id: 4964 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '4964'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4964'
 id: 4965 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '4965'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4965'
 id: 4966 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '4966'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4966'
 id: 4967 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4967'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4967'
 id: 4968 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '4968'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4968'
 id: 4969 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4969'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4969'
 id: 4970 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '4970'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4970'
 id: 4971 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '4971'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4971'
 id: 4972 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4972'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4972'
 id: 4973 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4973'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4973'
 id: 4974 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4974'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4974'
 id: 4975 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4975'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4975'
 id: 4976 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '4976'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4976'
 id: 4977 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '4977'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4977'
 id: 4978 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '4978'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4978'
 id: 4979 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '4979'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4979'
 id: 4980 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4980'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4980'
 id: 4981 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '4981'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4981'
 id: 4982 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '4982'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4982'
 id: 4983 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '4983'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4983'
 id: 4984 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4984'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4984'
 id: 4985 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4985'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4985'
 id: 4986 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '4986'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4986'
 id: 4987 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '4987'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4987'
 id: 4988 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '4988'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4988'
 id: 4989 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '4989'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4989'
 id: 4990 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '4990'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4990'
 id: 4991 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '4991'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4991'
 id: 4992 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4992'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4992'
 id: 4993 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4993'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4993'
 id: 4994 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '4994'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4994'
 id: 4995 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '4995'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4995'
 id: 4996 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4996'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4996'
 id: 4997 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '4997'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4997'
 id: 4998 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '4998'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4998'
 id: 4999 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '4999'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '4999'
 id: 5000 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '5000'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5000'
 id: 5001 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5001'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5001'
 id: 5002 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5002'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5002'
 id: 5003 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5003'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5003'
 id: 5004 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5004'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5004'
 id: 5005 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5005'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5005'
 id: 5006 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5006'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5006'
 id: 5007 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5007'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5007'
 id: 5008 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5008'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5008'
 id: 5009 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '5009'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5009'
 id: 5010 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '5010'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5010'
 id: 5011 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5011'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5011'
 id: 5012 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '5012'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5012'
 id: 5013 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5013'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5013'
 id: 5014 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5014'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5014'
 id: 5015 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '5015'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5015'
 id: 5016 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5016'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5016'
 id: 5017 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '5017'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5017'
 id: 5018 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5018'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5018'
 id: 5019 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5019'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5019'
 id: 5020 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '5020'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5020'
 id: 5021 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5021'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5021'
 id: 5022 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '5022'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5022'
 id: 5023 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5023'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5023'
 id: 5024 // word: 57
UPDATE job_vacancies SET domain_id =  '57' where raw_id = '5024'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5024'
 id: 5025 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '5025'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5025'
 id: 5026 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '5026'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5026'
 id: 5027 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5027'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5027'
 id: 5028 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '5028'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5028'
 id: 5029 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5029'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5029'
 id: 5030 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5030'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5030'
 id: 5031 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '5031'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5031'
 id: 5032 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5032'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5032'
 id: 5033 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '5033'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5033'
 id: 5034 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '5034'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5034'
 id: 5035 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5035'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5035'
 id: 5036 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5036'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5036'
 id: 5037 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '5037'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5037'
 id: 5038 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5038'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5038'
 id: 5039 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '5039'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5039'
 id: 5040 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '5040'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5040'
 id: 5041 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5041'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5041'
 id: 5042 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5042'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5042'
 id: 5043 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5043'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5043'
 id: 5044 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5044'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5044'
 id: 5045 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5045'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5045'
 id: 5046 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5046'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5046'
 id: 5047 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5047'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5047'
 id: 5048 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5048'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5048'
 id: 5049 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5049'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5049'
 id: 5050 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '5050'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5050'
 id: 5051 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5051'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5051'
 id: 5052 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '5052'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5052'
 id: 5053 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5053'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5053'
 id: 5054 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '5054'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5054'
 id: 5055 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '5055'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5055'
 id: 5056 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '5056'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5056'
 id: 5057 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5057'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5057'
 id: 5058 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5058'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5058'
 id: 5059 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '5059'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5059'
 id: 5060 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '5060'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5060'
 id: 5061 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '5061'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5061'
 id: 5062 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5062'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5062'
 id: 5063 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5063'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5063'
 id: 5064 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5064'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5064'
 id: 5065 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5065'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5065'
 id: 5066 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5066'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5066'
 id: 5067 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '5067'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5067'
 id: 5068 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5068'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5068'
 id: 5069 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5069'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5069'
 id: 5070 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '5070'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5070'
 id: 5071 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5071'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5071'
 id: 5072 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5072'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5072'
 id: 5073 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '5073'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5073'
 id: 5074 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '5074'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5074'
 id: 5075 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5075'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5075'
 id: 5076 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '5076'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5076'
 id: 5077 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5077'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5077'
 id: 5078 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '5078'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5078'
 id: 5079 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '5079'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5079'
 id: 5080 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5080'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5080'
 id: 5081 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '5081'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5081'
 id: 5082 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5082'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5082'
 id: 5083 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5083'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5083'
 id: 5084 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '5084'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5084'
 id: 5085 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5085'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5085'
 id: 5086 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5086'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5086'
 id: 5087 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5087'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5087'
 id: 5088 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '5088'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5088'
 id: 5089 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '5089'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5089'
 id: 5090 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '5090'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5090'
 id: 5091 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5091'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5091'
 id: 5092 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5092'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5092'
 id: 5093 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '5093'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5093'
 id: 5094 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '5094'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5094'
 id: 5095 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5095'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5095'
 id: 5096 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '5096'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5096'
 id: 5097 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5097'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5097'
 id: 5098 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '5098'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5098'
 id: 5099 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '5099'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5099'
 id: 5100 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5100'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5100'
 id: 5101 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5101'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5101'
 id: 5102 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '5102'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5102'
 id: 5103 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '5103'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5103'
 id: 5104 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '5104'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5104'
 id: 5105 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '5105'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5105'
 id: 5106 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '5106'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5106'
 id: 5107 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '5107'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5107'
 id: 5108 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '5108'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5108'
 id: 5109 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5109'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5109'
 id: 5110 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '5110'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5110'
 id: 5111 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5111'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5111'
 id: 5112 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '5112'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5112'
 id: 5113 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5113'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5113'
 id: 5114 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5114'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5114'
 id: 5115 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5115'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5115'
 id: 5116 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '5116'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5116'
 id: 5117 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '5117'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5117'
 id: 5118 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '5118'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5118'
 id: 5119 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5119'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5119'
 id: 5120 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '5120'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5120'
 id: 5121 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5121'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5121'
 id: 5122 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '5122'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5122'
 id: 5123 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5123'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5123'
 id: 5124 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5124'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5124'
 id: 5125 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '5125'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5125'
 id: 5126 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5126'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5126'
 id: 5127 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5127'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5127'
 id: 5128 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5128'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5128'
 id: 5129 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5129'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5129'
 id: 5130 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '5130'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5130'
 id: 5131 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5131'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5131'
 id: 5132 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5132'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5132'
 id: 5133 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5133'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5133'
 id: 5134 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '5134'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5134'
 id: 5135 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5135'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5135'
 id: 5136 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '5136'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5136'
 id: 5137 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5137'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5137'
 id: 5138 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '5138'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5138'
 id: 5139 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5139'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5139'
 id: 5140 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5140'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5140'
 id: 5141 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '5141'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5141'
 id: 5142 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5142'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5142'
 id: 5143 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5143'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5143'
 id: 5144 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '5144'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5144'
 id: 5145 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5145'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5145'
 id: 5146 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5146'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5146'
 id: 5147 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '5147'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5147'
 id: 5148 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5148'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5148'
 id: 5149 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5149'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5149'
 id: 5150 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5150'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5150'
 id: 5151 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5151'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5151'
 id: 5152 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '5152'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5152'
 id: 5153 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '5153'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5153'
 id: 5154 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '5154'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5154'
 id: 5155 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '5155'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5155'
 id: 5156 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '5156'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5156'
 id: 5157 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5157'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5157'
 id: 5158 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5158'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5158'
 id: 5159 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5159'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5159'
 id: 5160 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5160'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5160'
 id: 5161 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5161'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5161'
 id: 5162 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5162'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5162'
 id: 5163 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5163'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5163'
 id: 5164 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '5164'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5164'
 id: 5165 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5165'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5165'
 id: 5166 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5166'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5166'
 id: 5167 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '5167'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5167'
 id: 5168 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '5168'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5168'
 id: 5169 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5169'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5169'
 id: 5170 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5170'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5170'
 id: 5171 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '5171'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5171'
 id: 5172 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5172'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5172'
 id: 5173 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5173'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5173'
 id: 5174 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5174'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5174'
 id: 5175 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5175'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5175'
 id: 5176 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '5176'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5176'
 id: 5177 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5177'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5177'
 id: 5178 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5178'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5178'
 id: 5179 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '5179'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5179'
 id: 5180 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '5180'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5180'
 id: 5181 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5181'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5181'
 id: 5182 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5182'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5182'
 id: 5183 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '5183'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5183'
 id: 5184 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5184'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5184'
 id: 5185 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5185'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5185'
 id: 5186 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '5186'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5186'
 id: 5187 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '5187'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5187'
 id: 5188 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5188'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5188'
 id: 5189 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5189'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5189'
 id: 5190 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '5190'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5190'
 id: 5191 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5191'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5191'
 id: 5192 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '5192'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5192'
 id: 5193 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5193'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5193'
 id: 5194 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5194'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5194'
 id: 5195 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '5195'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5195'
 id: 5196 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5196'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5196'
 id: 5197 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5197'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5197'
 id: 5198 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '5198'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5198'
 id: 5199 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5199'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5199'
 id: 5200 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '5200'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5200'
 id: 5201 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5201'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5201'
 id: 5202 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '5202'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5202'
 id: 5203 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '5203'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5203'
 id: 5204 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5204'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5204'
 id: 5205 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5205'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5205'
 id: 5206 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5206'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5206'
 id: 5207 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5207'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5207'
 id: 5208 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '5208'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5208'
 id: 5209 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5209'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5209'
 id: 5210 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5210'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5210'
 id: 5211 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5211'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5211'
 id: 5212 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5212'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5212'
 id: 5213 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5213'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5213'
 id: 5214 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '5214'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5214'
 id: 5215 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5215'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5215'
 id: 5216 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '5216'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5216'
 id: 5217 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5217'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5217'
 id: 5218 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5218'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5218'
 id: 5219 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '5219'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5219'
 id: 5220 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '5220'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5220'
 id: 5221 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '5221'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5221'
 id: 5222 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5222'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5222'
 id: 5223 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5223'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5223'
 id: 5224 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5224'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5224'
 id: 5225 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5225'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5225'
 id: 5226 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '5226'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5226'
 id: 5227 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5227'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5227'
 id: 5228 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5228'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5228'
 id: 5229 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5229'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5229'
 id: 5230 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '5230'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5230'
 id: 5231 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '5231'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5231'
 id: 5232 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '5232'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5232'
 id: 5233 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5233'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5233'
 id: 5234 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '5234'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5234'
 id: 5235 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5235'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5235'
 id: 5236 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5236'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5236'
 id: 5237 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5237'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5237'
 id: 5238 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5238'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5238'
 id: 5239 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5239'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5239'
 id: 5240 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '5240'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5240'
 id: 5241 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '5241'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5241'
 id: 5242 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5242'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5242'
 id: 5243 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '5243'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5243'
 id: 5244 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5244'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5244'
 id: 5245 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5245'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5245'
 id: 5246 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5246'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5246'
 id: 5247 // word: 52
UPDATE job_vacancies SET domain_id =  '52' where raw_id = '5247'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5247'
 id: 5248 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5248'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5248'
 id: 5249 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5249'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5249'
 id: 5250 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '5250'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5250'
 id: 5251 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '5251'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5251'
 id: 5252 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5252'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5252'
 id: 5253 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5253'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5253'
 id: 5254 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5254'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5254'
 id: 5255 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5255'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5255'
 id: 5256 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '5256'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5256'
 id: 5257 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '5257'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5257'
 id: 5258 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5258'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5258'
 id: 5259 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '5259'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5259'
 id: 5260 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '5260'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5260'
 id: 5261 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '5261'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5261'
 id: 5262 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '5262'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5262'
 id: 5263 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5263'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5263'
 id: 5264 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5264'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5264'
 id: 5265 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5265'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5265'
 id: 5266 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5266'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5266'
 id: 5267 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '5267'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5267'
 id: 5268 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5268'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5268'
 id: 5269 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '5269'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5269'
 id: 5270 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5270'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5270'
 id: 5271 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5271'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5271'
 id: 5272 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '5272'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5272'
 id: 5273 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '5273'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5273'
 id: 5274 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5274'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5274'
 id: 5275 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5275'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5275'
 id: 5276 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5276'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5276'
 id: 5277 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '5277'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5277'
 id: 5278 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5278'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5278'
 id: 5279 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '5279'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5279'
 id: 5280 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5280'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5280'
 id: 5281 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5281'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5281'
 id: 5282 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5282'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5282'
 id: 5283 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5283'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5283'
 id: 5284 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5284'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5284'
 id: 5285 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5285'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5285'
 id: 5286 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5286'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5286'
 id: 5287 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5287'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5287'
 id: 5288 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '5288'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5288'
 id: 5289 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5289'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5289'
 id: 5290 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5290'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5290'
 id: 5291 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5291'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5291'
 id: 5292 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5292'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5292'
 id: 5293 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5293'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5293'
 id: 5294 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5294'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5294'
 id: 5295 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '5295'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5295'
 id: 5296 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '5296'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5296'
 id: 5297 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '5297'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5297'
 id: 5298 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5298'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5298'
 id: 5299 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '5299'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5299'
 id: 5300 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5300'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5300'
 id: 5301 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5301'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5301'
 id: 5302 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '5302'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5302'
 id: 5303 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5303'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5303'
 id: 5304 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5304'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5304'
 id: 5305 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5305'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5305'
 id: 5306 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5306'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5306'
 id: 5307 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5307'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5307'
 id: 5308 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5308'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5308'
 id: 5309 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5309'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5309'
 id: 5310 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5310'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5310'
 id: 5311 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5311'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5311'
 id: 5312 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5312'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5312'
 id: 5313 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5313'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5313'
 id: 5314 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5314'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5314'
 id: 5315 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '5315'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5315'
 id: 5316 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5316'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5316'
 id: 5317 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5317'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5317'
 id: 5318 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5318'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5318'

 id: 5319 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '5319'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5319'
 id: 5320 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '5320'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5320'
 id: 5321 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5321'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5321'
 id: 5322 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5322'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5322'
 id: 5323 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5323'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5323'
 id: 5324 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '5324'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5324'
 id: 5325 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '5325'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5325'
 id: 5326 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '5326'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5326'
 id: 5327 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '5327'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5327'
 id: 5328 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '5328'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5328'
 id: 5329 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5329'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5329'
 id: 5330 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5330'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5330'
 id: 5331 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5331'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5331'
 id: 5332 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5332'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5332'
 id: 5333 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '5333'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5333'
 id: 5334 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5334'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5334'
 id: 5335 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5335'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5335'
 id: 5336 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5336'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5336'
 id: 5337 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5337'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5337'
 id: 5338 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '5338'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5338'
 id: 5339 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5339'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5339'
 id: 5340 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '5340'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5340'
 id: 5341 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5341'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5341'
 id: 5342 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '5342'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5342'
 id: 5343 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5343'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5343'
 id: 5344 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '5344'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5344'
 id: 5345 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '5345'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5345'
 id: 5346 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5346'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5346'
 id: 5347 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5347'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5347'
 id: 5348 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5348'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5348'
 id: 5349 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5349'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5349'
 id: 5350 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '5350'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5350'
 id: 5351 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5351'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5351'
 id: 5352 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5352'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5352'
 id: 5353 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5353'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5353'
 id: 5354 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5354'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5354'
 id: 5355 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '5355'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5355'
 id: 5356 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '5356'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5356'
 id: 5357 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5357'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5357'
 id: 5358 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5358'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5358'
 id: 5359 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '5359'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5359'
 id: 5360 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5360'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5360'
 id: 5361 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5361'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5361'
 id: 5362 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '5362'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5362'
 id: 5363 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5363'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5363'
 id: 5364 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '5364'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5364'
 id: 5365 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '5365'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5365'
 id: 5366 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5366'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5366'
 id: 5367 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '5367'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5367'
 id: 5368 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5368'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5368'
 id: 5369 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '5369'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5369'

 id: 5370 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5370'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5370'
 id: 5371 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '5371'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5371'
 id: 5372 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '5372'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5372'
 id: 5373 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '5373'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5373'
 id: 5374 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '5374'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5374'
 id: 5375 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '5375'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5375'
 id: 5376 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5376'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5376'
 id: 5377 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5377'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5377'
 id: 5378 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5378'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5378'
 id: 5379 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5379'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5379'
 id: 5380 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '5380'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5380'
 id: 5381 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '5381'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5381'
 id: 5382 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5382'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5382'
 id: 5383 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '5383'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5383'
 id: 5384 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5384'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5384'
 id: 5385 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5385'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5385'
 id: 5386 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '5386'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5386'
 id: 5387 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5387'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5387'
 id: 5388 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5388'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5388'
 id: 5389 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5389'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5389'
 id: 5390 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5390'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5390'
 id: 5391 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '5391'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5391'
 id: 5392 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5392'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5392'
 id: 5393 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '5393'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5393'
 id: 5394 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '5394'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5394'
 id: 5395 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '5395'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5395'
 id: 5396 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5396'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5396'
 id: 5397 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '5397'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5397'
 id: 5398 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5398'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5398'
 id: 5399 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5399'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5399'
 id: 5400 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '5400'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5400'
 id: 5401 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '5401'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5401'
 id: 5402 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5402'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5402'
 id: 5403 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5403'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5403'
 id: 5404 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '5404'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5404'
 id: 5405 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5405'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5405'
 id: 5406 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '5406'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5406'
 id: 5407 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5407'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5407'
 id: 5408 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5408'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5408'
 id: 5409 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5409'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5409'
 id: 5410 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '5410'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5410'
 id: 5411 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '5411'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5411'
 id: 5412 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5412'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5412'
 id: 5413 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5413'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5413'
 id: 5414 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5414'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5414'
 id: 5415 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '5415'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5415'
 id: 5416 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '5416'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5416'
 id: 5417 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5417'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5417'
 id: 5418 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5418'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5418'
 id: 5419 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5419'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5419'
 id: 5420 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '5420'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5420'
 id: 5421 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5421'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5421'
 id: 5422 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5422'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5422'
 id: 5423 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5423'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5423'
 id: 5424 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5424'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5424'
 id: 5425 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5425'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5425'
 id: 5426 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5426'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5426'
 id: 5427 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5427'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5427'
 id: 5428 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5428'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5428'
 id: 5429 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '5429'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5429'
 id: 5430 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5430'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5430'
 id: 5431 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5431'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5431'
 id: 5432 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '5432'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5432'
 id: 5433 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5433'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5433'
 id: 5434 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5434'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5434'
 id: 5435 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '5435'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5435'
 id: 5436 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5436'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5436'
 id: 5437 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '5437'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5437'
 id: 5438 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5438'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5438'
 id: 5439 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5439'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5439'
 id: 5440 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5440'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5440'
 id: 5441 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5441'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5441'
 id: 5442 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5442'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5442'
 id: 5443 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5443'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5443'
 id: 5444 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5444'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5444'
 id: 5445 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5445'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5445'
 id: 5446 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5446'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5446'
 id: 5447 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '5447'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5447'
 id: 5448 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '5448'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5448'
 id: 5449 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5449'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5449'
 id: 5450 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5450'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5450'
 id: 5451 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '5451'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5451'
 id: 5452 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5452'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5452'
 id: 5453 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5453'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5453'
 id: 5454 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5454'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5454'
 id: 5455 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '5455'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5455'
 id: 5456 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5456'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5456'
 id: 5457 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '5457'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5457'
 id: 5458 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5458'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5458'
 id: 5459 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5459'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5459'
 id: 5460 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5460'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5460'
 id: 5461 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5461'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5461'
 id: 5462 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5462'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5462'
 id: 5463 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5463'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5463'
 id: 5464 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5464'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5464'
 id: 5465 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '5465'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5465'
 id: 5466 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '5466'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5466'
 id: 5467 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '5467'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5467'
 id: 5468 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '5468'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5468'
 id: 5469 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5469'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5469'
 id: 5470 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5470'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5470'
 id: 5471 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5471'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5471'

 id: 5472 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '5472'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5472'
 id: 5473 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '5473'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5473'
 id: 5474 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5474'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5474'
 id: 5475 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5475'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5475'
 id: 5476 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5476'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5476'
 id: 5477 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5477'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5477'
 id: 5478 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5478'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5478'
 id: 5479 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5479'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5479'
 id: 5480 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5480'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5480'
 id: 5481 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '5481'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5481'
 id: 5482 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5482'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5482'
 id: 5483 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5483'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5483'
 id: 5484 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5484'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5484'
 id: 5485 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5485'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5485'
 id: 5486 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '5486'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5486'
 id: 5487 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5487'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5487'
 id: 5488 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '5488'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5488'
 id: 5489 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5489'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5489'
 id: 5490 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5490'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5490'
 id: 5491 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5491'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5491'
 id: 5492 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5492'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5492'
 id: 5493 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '5493'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5493'
 id: 5494 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5494'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5494'
 id: 5495 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5495'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5495'
 id: 5496 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '5496'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5496'
 id: 5497 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '5497'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5497'
 id: 5498 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5498'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5498'
 id: 5499 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5499'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5499'
 id: 5500 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '5500'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5500'
 id: 5501 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5501'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5501'
 id: 5502 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5502'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5502'
 id: 5503 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5503'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5503'
 id: 5504 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5504'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5504'
 id: 5505 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5505'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5505'
 id: 5506 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5506'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5506'
 id: 5507 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5507'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5507'
 id: 5508 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5508'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5508'
 id: 5509 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '5509'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5509'
 id: 5510 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '5510'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5510'
 id: 5511 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '5511'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5511'
 id: 5512 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5512'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5512'
 id: 5513 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5513'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5513'
 id: 5514 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '5514'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5514'
 id: 5515 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5515'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5515'
 id: 5516 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '5516'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5516'
 id: 5517 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '5517'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5517'
 id: 5518 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '5518'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5518'
 id: 5519 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5519'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5519'
 id: 5520 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '5520'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5520'
 id: 5521 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5521'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5521'
 id: 5522 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '5522'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5522'
 id: 5523 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '5523'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5523'
 id: 5524 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5524'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5524'
 id: 5525 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5525'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5525'
 id: 5526 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '5526'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5526'
 id: 5527 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5527'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5527'
 id: 5528 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5528'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5528'
 id: 5529 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5529'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5529'
 id: 5530 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '5530'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5530'
 id: 5531 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5531'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5531'
 id: 5532 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '5532'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5532'
 id: 5533 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5533'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5533'
 id: 5534 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5534'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5534'
 id: 5535 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '5535'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5535'
 id: 5536 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5536'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5536'
 id: 5537 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '5537'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5537'
 id: 5538 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5538'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5538'
 id: 5539 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5539'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5539'
 id: 5540 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5540'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5540'
 id: 5541 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5541'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5541'
 id: 5542 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5542'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5542'
 id: 5543 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5543'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5543'
 id: 5544 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '5544'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5544'
 id: 5545 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '5545'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5545'
 id: 5546 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5546'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5546'
 id: 5547 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5547'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5547'
 id: 5548 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5548'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5548'
 id: 5549 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5549'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5549'
 id: 5550 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5550'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5550'
 id: 5551 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5551'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5551'
 id: 5552 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5552'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5552'
 id: 5553 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '5553'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5553'
 id: 5554 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '5554'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5554'
 id: 5555 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '5555'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5555'
 id: 5556 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '5556'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5556'
 id: 5557 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5557'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5557'
 id: 5558 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '5558'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5558'
 id: 5559 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5559'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5559'
 id: 5560 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5560'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5560'
 id: 5561 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5561'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5561'
 id: 5562 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5562'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5562'
 id: 5563 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5563'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5563'
 id: 5564 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5564'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5564'
 id: 5565 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '5565'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5565'
 id: 5566 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '5566'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5566'
 id: 5567 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '5567'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5567'
 id: 5568 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5568'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5568'
 id: 5569 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5569'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5569'
 id: 5570 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5570'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5570'
 id: 5571 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '5571'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5571'
 id: 5572 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '5572'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5572'
 id: 5573 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '5573'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5573'
 id: 5574 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5574'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5574'
 id: 5575 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5575'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5575'
 id: 5576 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5576'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5576'
 id: 5577 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5577'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5577'
 id: 5578 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5578'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5578'
 id: 5579 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '5579'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5579'
 id: 5580 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5580'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5580'
 id: 5581 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5581'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5581'
 id: 5582 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5582'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5582'
 id: 5583 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '5583'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5583'
 id: 5584 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5584'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5584'
 id: 5585 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '5585'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5585'
 id: 5586 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '5586'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5586'
 id: 5587 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '5587'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5587'
 id: 5588 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5588'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5588'
 id: 5589 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '5589'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5589'
 id: 5590 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '5590'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5590'
 id: 5591 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5591'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5591'
 id: 5592 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5592'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5592'
 id: 5593 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '5593'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5593'
 id: 5594 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '5594'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5594'
 id: 5595 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5595'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5595'
 id: 5596 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '5596'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5596'
 id: 5597 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5597'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5597'
 id: 5598 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '5598'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5598'
 id: 5599 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '5599'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5599'
 id: 5600 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '5600'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5600'
 id: 5601 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5601'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5601'
 id: 5602 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5602'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5602'
 id: 5603 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '5603'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5603'
 id: 5604 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5604'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5604'
 id: 5605 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5605'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5605'
 id: 5606 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5606'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5606'
 id: 5607 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5607'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5607'
 id: 5608 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5608'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5608'
 id: 5609 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '5609'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5609'
 id: 5610 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5610'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5610'
 id: 5611 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5611'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5611'
 id: 5612 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '5612'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5612'
 id: 5613 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5613'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5613'
 id: 5614 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5614'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5614'
 id: 5615 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5615'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5615'
 id: 5616 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '5616'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5616'
 id: 5617 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5617'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5617'
 id: 5618 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5618'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5618'
 id: 5619 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5619'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5619'
 id: 5620 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5620'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5620'
 id: 5621 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '5621'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5621'
 id: 5622 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5622'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5622'
 id: 5623 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '5623'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5623'
 id: 5624 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5624'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5624'
 id: 5625 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5625'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5625'
 id: 5626 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '5626'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5626'
 id: 5627 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5627'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5627'
 id: 5628 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5628'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5628'
 id: 5629 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5629'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5629'
 id: 5630 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '5630'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5630'
 id: 5631 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5631'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5631'
 id: 5632 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5632'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5632'
 id: 5633 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5633'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5633'
 id: 5634 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5634'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5634'
 id: 5635 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5635'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5635'
 id: 5636 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5636'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5636'
 id: 5637 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5637'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5637'
 id: 5638 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '5638'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5638'
 id: 5639 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5639'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5639'
 id: 5640 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5640'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5640'
 id: 5641 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5641'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5641'
 id: 5642 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5642'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5642'
 id: 5643 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '5643'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5643'
 id: 5644 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5644'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5644'
 id: 5645 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '5645'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5645'
 id: 5646 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5646'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5646'
 id: 5647 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5647'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5647'
 id: 5648 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5648'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5648'
 id: 5649 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5649'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5649'
 id: 5650 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5650'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5650'
 id: 5651 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5651'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5651'
 id: 5652 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5652'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5652'
 id: 5653 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5653'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5653'
 id: 5654 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '5654'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5654'
 id: 5655 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5655'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5655'
 id: 5656 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5656'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5656'
 id: 5657 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5657'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5657'
 id: 5658 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5658'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5658'
 id: 5659 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '5659'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5659'
 id: 5660 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5660'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5660'
 id: 5661 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5661'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5661'
 id: 5662 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '5662'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5662'
 id: 5663 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5663'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5663'
 id: 5664 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5664'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5664'
 id: 5665 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '5665'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5665'
 id: 5666 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5666'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5666'
 id: 5667 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5667'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5667'
 id: 5668 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5668'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5668'
 id: 5669 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '5669'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5669'
 id: 5670 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5670'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5670'
 id: 5671 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5671'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5671'
 id: 5672 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5672'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5672'
 id: 5673 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5673'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5673'
 id: 5674 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '5674'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5674'
 id: 5675 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '5675'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5675'
 id: 5676 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5676'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5676'
 id: 5677 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '5677'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5677'
 id: 5678 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '5678'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5678'
 id: 5679 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5679'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5679'
 id: 5680 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5680'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5680'
 id: 5681 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5681'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5681'
 id: 5682 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5682'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5682'
 id: 5683 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5683'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5683'
 id: 5684 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5684'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5684'
 id: 5685 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5685'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5685'
 id: 5686 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '5686'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5686'
 id: 5687 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5687'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5687'
 id: 5688 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '5688'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5688'
 id: 5689 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5689'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5689'
 id: 5690 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '5690'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5690'
 id: 5691 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5691'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5691'
 id: 5692 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5692'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5692'
 id: 5693 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '5693'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5693'
 id: 5694 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5694'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5694'
 id: 5695 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5695'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5695'
 id: 5696 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5696'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5696'
 id: 5697 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5697'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5697'
 id: 5698 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5698'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5698'
 id: 5699 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '5699'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5699'
 id: 5700 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5700'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5700'
 id: 5701 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5701'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5701'
 id: 5702 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5702'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5702'
 id: 5703 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5703'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5703'
 id: 5704 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5704'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5704'
 id: 5705 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '5705'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5705'
 id: 5706 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5706'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5706'
 id: 5707 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '5707'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5707'
 id: 5708 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5708'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5708'
 id: 5709 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5709'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5709'
 id: 5710 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5710'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5710'
 id: 5711 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5711'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5711'
 id: 5712 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '5712'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5712'
 id: 5713 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5713'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5713'
 id: 5714 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '5714'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5714'
 id: 5715 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5715'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5715'
 id: 5716 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5716'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5716'
 id: 5717 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '5717'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5717'
 id: 5718 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '5718'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5718'
 id: 5719 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5719'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5719'
 id: 5720 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '5720'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5720'
 id: 5721 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5721'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5721'
 id: 5722 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5722'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5722'
 id: 5723 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5723'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5723'
 id: 5724 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '5724'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5724'
 id: 5725 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5725'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5725'
 id: 5726 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '5726'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5726'
 id: 5727 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '5727'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5727'
 id: 5728 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5728'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5728'
 id: 5729 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5729'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5729'
 id: 5730 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5730'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5730'
 id: 5731 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5731'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5731'
 id: 5732 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5732'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5732'
 id: 5733 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5733'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5733'
 id: 5734 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5734'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5734'
 id: 5735 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5735'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5735'
 id: 5736 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5736'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5736'
 id: 5737 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '5737'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5737'
 id: 5738 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5738'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5738'
 id: 5739 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5739'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5739'
 id: 5740 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5740'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5740'
 id: 5741 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5741'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5741'
 id: 5742 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '5742'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5742'
 id: 5743 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5743'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5743'
 id: 5744 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5744'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5744'
 id: 5745 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '5745'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5745'
 id: 5746 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5746'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5746'
 id: 5747 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5747'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5747'
 id: 5748 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5748'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5748'
 id: 5749 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5749'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5749'
 id: 5750 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '5750'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5750'
 id: 5751 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '5751'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5751'
 id: 5752 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '5752'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5752'
 id: 5753 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5753'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5753'
 id: 5754 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5754'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5754'
 id: 5755 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5755'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5755'
 id: 5756 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5756'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5756'
 id: 5757 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5757'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5757'
 id: 5758 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5758'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5758'
 id: 5759 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '5759'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5759'
 id: 5760 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5760'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5760'
 id: 5761 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5761'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5761'
 id: 5762 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '5762'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5762'
 id: 5763 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5763'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5763'
 id: 5764 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5764'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5764'
 id: 5765 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5765'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5765'
 id: 5766 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5766'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5766'
 id: 5767 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5767'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5767'
 id: 5768 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5768'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5768'
 id: 5769 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '5769'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5769'
 id: 5770 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '5770'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5770'
 id: 5771 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '5771'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5771'
 id: 5772 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '5772'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5772'
 id: 5773 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '5773'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5773'
 id: 5774 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '5774'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5774'
 id: 5775 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5775'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5775'
 id: 5776 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5776'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5776'
 id: 5777 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5777'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5777'
 id: 5778 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5778'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5778'
 id: 5779 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '5779'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5779'
 id: 5780 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5780'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5780'
 id: 5781 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5781'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5781'
 id: 5782 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5782'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5782'
 id: 5783 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5783'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5783'
 id: 5784 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5784'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5784'
 id: 5785 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5785'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5785'

 id: 5786 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '5786'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5786'
 id: 5787 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '5787'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5787'
 id: 5788 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5788'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5788'
 id: 5789 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5789'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5789'
 id: 5790 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '5790'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5790'
 id: 5791 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5791'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5791'
 id: 5792 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '5792'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5792'
 id: 5793 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5793'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5793'
 id: 5794 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5794'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5794'
 id: 5795 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5795'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5795'
 id: 5796 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '5796'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5796'
 id: 5797 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '5797'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5797'
 id: 5798 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5798'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5798'
 id: 5799 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5799'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5799'
 id: 5800 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5800'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5800'
 id: 5801 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5801'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5801'
 id: 5802 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '5802'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5802'
 id: 5803 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5803'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5803'
 id: 5804 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '5804'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5804'
 id: 5805 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5805'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5805'
 id: 5806 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '5806'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5806'
 id: 5807 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5807'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5807'
 id: 5808 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '5808'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5808'
 id: 5809 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '5809'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5809'
 id: 5810 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5810'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5810'
 id: 5811 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '5811'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5811'
 id: 5812 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '5812'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5812'
 id: 5813 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '5813'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5813'
 id: 5814 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5814'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5814'
 id: 5815 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '5815'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5815'
 id: 5816 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5816'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5816'
 id: 5817 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5817'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5817'
 id: 5818 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5818'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5818'
 id: 5819 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5819'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5819'
 id: 5820 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5820'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5820'
 id: 5821 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '5821'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5821'
 id: 5822 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '5822'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5822'
 id: 5823 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5823'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5823'
 id: 5824 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '5824'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5824'
 id: 5825 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5825'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5825'
 id: 5826 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5826'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5826'
 id: 5827 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '5827'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5827'
 id: 5828 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5828'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5828'
 id: 5829 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '5829'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5829'
 id: 5830 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '5830'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5830'
 id: 5831 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '5831'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5831'
 id: 5832 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5832'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5832'
 id: 5833 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5833'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5833'
 id: 5834 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '5834'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5834'
 id: 5835 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5835'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5835'
 id: 5836 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '5836'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5836'

 id: 5837 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5837'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5837'
 id: 5838 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5838'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5838'
 id: 5839 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5839'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5839'
 id: 5840 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '5840'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5840'
 id: 5841 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '5841'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5841'
 id: 5842 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5842'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5842'
 id: 5843 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5843'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5843'
 id: 5844 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5844'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5844'
 id: 5845 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5845'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5845'
 id: 5846 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5846'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5846'
 id: 5847 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '5847'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5847'
 id: 5848 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5848'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5848'
 id: 5849 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '5849'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5849'
 id: 5850 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5850'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5850'
 id: 5851 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5851'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5851'
 id: 5852 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5852'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5852'
 id: 5853 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5853'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5853'
 id: 5854 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '5854'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5854'
 id: 5855 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5855'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5855'
 id: 5856 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '5856'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5856'
 id: 5857 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5857'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5857'
 id: 5858 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5858'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5858'
 id: 5859 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5859'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5859'
 id: 5860 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '5860'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5860'
 id: 5861 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5861'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5861'
 id: 5862 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5862'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5862'
 id: 5863 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5863'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5863'
 id: 5864 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5864'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5864'
 id: 5865 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5865'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5865'
 id: 5866 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5866'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5866'
 id: 5867 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '5867'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5867'
 id: 5868 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5868'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5868'
 id: 5869 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5869'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5869'
 id: 5870 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '5870'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5870'
 id: 5871 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5871'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5871'
 id: 5872 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '5872'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5872'
 id: 5873 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5873'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5873'
 id: 5874 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5874'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5874'
 id: 5875 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '5875'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5875'
 id: 5876 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '5876'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5876'
 id: 5877 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '5877'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5877'
 id: 5878 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5878'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5878'
 id: 5879 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '5879'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5879'
 id: 5880 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '5880'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5880'
 id: 5881 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5881'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5881'
 id: 5882 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5882'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5882'
 id: 5883 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '5883'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5883'
 id: 5884 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '5884'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5884'
 id: 5885 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5885'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5885'
 id: 5886 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5886'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5886'
 id: 5887 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5887'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5887'
 id: 5888 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '5888'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5888'

 id: 5889 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5889'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5889'
 id: 5890 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '5890'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5890'
 id: 5891 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5891'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5891'
 id: 5892 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5892'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5892'
 id: 5893 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '5893'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5893'
 id: 5894 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '5894'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5894'
 id: 5895 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '5895'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5895'
 id: 5896 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5896'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5896'
 id: 5897 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5897'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5897'
 id: 5898 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5898'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5898'
 id: 5899 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5899'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5899'
 id: 5900 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5900'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5900'
 id: 5901 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5901'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5901'
 id: 5902 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5902'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5902'
 id: 5903 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '5903'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5903'
 id: 5904 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '5904'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5904'
 id: 5905 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5905'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5905'
 id: 5906 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '5906'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5906'
 id: 5907 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '5907'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5907'
 id: 5908 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '5908'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5908'
 id: 5909 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5909'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5909'
 id: 5910 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '5910'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5910'
 id: 5911 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '5911'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5911'
 id: 5912 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5912'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5912'
 id: 5913 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5913'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5913'
 id: 5914 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5914'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5914'
 id: 5915 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5915'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5915'
 id: 5916 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5916'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5916'
 id: 5917 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '5917'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5917'
 id: 5918 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5918'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5918'
 id: 5919 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5919'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5919'
 id: 5920 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '5920'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5920'
 id: 5921 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '5921'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5921'
 id: 5922 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '5922'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5922'
 id: 5923 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '5923'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5923'
 id: 5924 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '5924'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5924'
 id: 5925 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5925'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5925'
 id: 5926 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5926'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5926'
 id: 5927 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5927'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5927'
 id: 5928 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5928'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5928'
 id: 5929 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5929'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5929'
 id: 5930 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5930'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5930'
 id: 5931 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '5931'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5931'
 id: 5932 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5932'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5932'
 id: 5933 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '5933'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5933'
 id: 5934 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5934'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5934'
 id: 5935 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '5935'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5935'
 id: 5936 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5936'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5936'
 id: 5937 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5937'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5937'
 id: 5938 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5938'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5938'
 id: 5939 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '5939'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5939'
 id: 5940 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5940'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5940'
 id: 5941 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5941'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5941'
 id: 5942 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5942'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5942'
 id: 5943 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5943'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5943'
 id: 5944 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '5944'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5944'
 id: 5945 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5945'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5945'
 id: 5946 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '5946'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5946'
 id: 5947 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5947'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5947'
 id: 5948 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5948'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5948'
 id: 5949 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5949'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5949'
 id: 5950 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '5950'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5950'
 id: 5951 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5951'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5951'
 id: 5952 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '5952'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5952'
 id: 5953 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5953'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5953'
 id: 5954 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5954'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5954'
 id: 5955 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5955'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5955'
 id: 5956 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5956'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5956'
 id: 5957 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5957'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5957'
 id: 5958 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '5958'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5958'
 id: 5959 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5959'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5959'
 id: 5960 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '5960'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5960'
 id: 5961 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5961'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5961'
 id: 5962 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '5962'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5962'
 id: 5963 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5963'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5963'
 id: 5964 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '5964'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5964'
 id: 5965 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5965'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5965'
 id: 5966 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '5966'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5966'
 id: 5967 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '5967'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5967'
 id: 5968 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '5968'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5968'
 id: 5969 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '5969'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5969'
 id: 5970 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5970'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5970'
 id: 5971 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5971'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5971'
 id: 5972 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '5972'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5972'
 id: 5973 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '5973'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5973'
 id: 5974 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5974'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5974'
 id: 5975 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5975'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5975'
 id: 5976 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5976'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5976'
 id: 5977 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '5977'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5977'
 id: 5978 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5978'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5978'
 id: 5979 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5979'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5979'
 id: 5980 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '5980'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5980'
 id: 5981 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5981'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5981'
 id: 5982 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '5982'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5982'
 id: 5983 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '5983'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5983'
 id: 5984 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '5984'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5984'
 id: 5985 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '5985'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5985'
 id: 5986 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '5986'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5986'
 id: 5987 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '5987'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5987'
 id: 5988 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5988'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5988'
 id: 5989 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5989'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5989'
 id: 5990 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '5990'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5990'
 id: 5991 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '5991'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5991'
 id: 5992 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '5992'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5992'
 id: 5993 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '5993'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5993'

 id: 5994 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '5994'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5994'
 id: 5995 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '5995'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5995'
 id: 5996 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '5996'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5996'
 id: 5997 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '5997'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5997'
 id: 5998 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '5998'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5998'
 id: 5999 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '5999'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '5999'
 id: 6000 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '6000'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6000'
 id: 6001 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6001'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6001'
 id: 6002 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '6002'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6002'
 id: 6003 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6003'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6003'
 id: 6004 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '6004'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6004'
 id: 6005 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6005'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6005'
 id: 6006 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6006'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6006'
 id: 6007 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6007'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6007'
 id: 6008 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6008'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6008'
 id: 6009 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '6009'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6009'
 id: 6010 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6010'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6010'
 id: 6011 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '6011'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6011'
 id: 6012 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6012'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6012'
 id: 6013 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '6013'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6013'
 id: 6014 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6014'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6014'
 id: 6015 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6015'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6015'
 id: 6016 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6016'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6016'
 id: 6017 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6017'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6017'
 id: 6018 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6018'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6018'
 id: 6019 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6019'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6019'
 id: 6020 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6020'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6020'
 id: 6021 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6021'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6021'
 id: 6022 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6022'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6022'
 id: 6023 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '6023'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6023'
 id: 6024 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '6024'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6024'
 id: 6025 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '6025'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6025'
 id: 6026 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '6026'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6026'
 id: 6027 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6027'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6027'
 id: 6028 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '6028'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6028'
 id: 6029 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '6029'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6029'
 id: 6030 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6030'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6030'
 id: 6031 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '6031'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6031'
 id: 6032 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6032'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6032'
 id: 6033 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6033'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6033'
 id: 6034 // word: 52
UPDATE job_vacancies SET domain_id =  '52' where raw_id = '6034'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6034'
 id: 6035 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '6035'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6035'
 id: 6036 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6036'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6036'
 id: 6037 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6037'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6037'
 id: 6038 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '6038'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6038'
 id: 6039 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6039'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6039'
 id: 6040 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6040'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6040'
 id: 6041 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6041'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6041'
 id: 6042 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6042'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6042'
 id: 6043 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6043'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6043'
 id: 6044 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6044'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6044'
 id: 6045 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6045'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6045'
 id: 6046 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6046'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6046'
 id: 6047 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '6047'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6047'
 id: 6048 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '6048'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6048'
 id: 6049 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '6049'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6049'
 id: 6050 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '6050'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6050'
 id: 6051 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '6051'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6051'
 id: 6052 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '6052'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6052'
 id: 6053 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '6053'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6053'
 id: 6054 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6054'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6054'
 id: 6055 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '6055'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6055'
 id: 6056 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '6056'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6056'
 id: 6057 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '6057'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6057'
 id: 6058 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6058'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6058'
 id: 6059 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6059'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6059'
 id: 6060 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '6060'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6060'
 id: 6061 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '6061'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6061'
 id: 6062 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6062'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6062'
 id: 6063 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '6063'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6063'
 id: 6064 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6064'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6064'
 id: 6065 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '6065'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6065'
 id: 6066 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6066'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6066'
 id: 6067 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '6067'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6067'
 id: 6068 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6068'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6068'
 id: 6069 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6069'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6069'
 id: 6070 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6070'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6070'
 id: 6071 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '6071'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6071'
 id: 6072 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6072'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6072'
 id: 6073 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6073'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6073'
 id: 6074 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '6074'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6074'
 id: 6075 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '6075'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6075'
 id: 6076 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6076'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6076'
 id: 6077 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6077'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6077'
 id: 6078 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '6078'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6078'
 id: 6079 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6079'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6079'
 id: 6080 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6080'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6080'
 id: 6081 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6081'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6081'
 id: 6082 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '6082'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6082'
 id: 6083 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6083'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6083'
 id: 6084 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6084'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6084'
 id: 6085 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '6085'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6085'
 id: 6086 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '6086'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6086'
 id: 6087 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '6087'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6087'
 id: 6088 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '6088'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6088'
 id: 6089 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '6089'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6089'
 id: 6090 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '6090'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6090'
 id: 6091 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6091'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6091'
 id: 6092 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6092'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6092'
 id: 6093 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '6093'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6093'
 id: 6094 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '6094'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6094'
 id: 6095 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6095'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6095'
 id: 6096 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '6096'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6096'

 id: 6097 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6097'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6097'
 id: 6098 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6098'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6098'
 id: 6099 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '6099'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6099'
 id: 6100 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6100'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6100'
 id: 6101 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6101'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6101'
 id: 6102 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '6102'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6102'
 id: 6103 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '6103'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6103'
 id: 6104 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6104'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6104'
 id: 6105 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '6105'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6105'
 id: 6106 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '6106'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6106'
 id: 6107 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '6107'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6107'
 id: 6108 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6108'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6108'
 id: 6109 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '6109'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6109'
 id: 6110 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6110'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6110'
 id: 6111 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6111'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6111'
 id: 6112 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6112'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6112'
 id: 6113 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6113'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6113'
 id: 6114 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6114'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6114'
 id: 6115 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6115'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6115'
 id: 6116 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '6116'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6116'
 id: 6117 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6117'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6117'
 id: 6118 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6118'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6118'
 id: 6119 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '6119'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6119'
 id: 6120 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '6120'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6120'
 id: 6121 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '6121'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6121'
 id: 6122 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6122'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6122'
 id: 6123 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '6123'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6123'
 id: 6124 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6124'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6124'
 id: 6125 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '6125'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6125'
 id: 6126 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6126'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6126'
 id: 6127 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '6127'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6127'
 id: 6128 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6128'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6128'
 id: 6129 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6129'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6129'
 id: 6130 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6130'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6130'
 id: 6131 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '6131'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6131'
 id: 6132 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6132'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6132'
 id: 6133 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '6133'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6133'
 id: 6134 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6134'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6134'
 id: 6135 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '6135'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6135'
 id: 6136 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6136'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6136'
 id: 6137 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6137'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6137'
 id: 6138 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '6138'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6138'
 id: 6139 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6139'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6139'
 id: 6140 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6140'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6140'
 id: 6141 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6141'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6141'
 id: 6142 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6142'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6142'
 id: 6143 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6143'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6143'
 id: 6144 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6144'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6144'
 id: 6145 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '6145'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6145'
 id: 6146 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '6146'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6146'
 id: 6147 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6147'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6147'

 id: 6148 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6148'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6148'
 id: 6149 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '6149'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6149'
 id: 6150 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '6150'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6150'
 id: 6151 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '6151'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6151'
 id: 6152 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '6152'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6152'
 id: 6153 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6153'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6153'
 id: 6154 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '6154'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6154'
 id: 6155 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '6155'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6155'
 id: 6156 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '6156'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6156'
 id: 6157 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '6157'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6157'
 id: 6158 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '6158'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6158'
 id: 6159 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6159'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6159'
 id: 6160 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6160'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6160'
 id: 6161 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6161'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6161'
 id: 6162 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6162'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6162'
 id: 6163 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6163'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6163'
 id: 6164 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '6164'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6164'
 id: 6165 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6165'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6165'
 id: 6166 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6166'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6166'
 id: 6167 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6167'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6167'
 id: 6168 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '6168'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6168'
 id: 6169 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6169'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6169'
 id: 6170 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '6170'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6170'
 id: 6171 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '6171'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6171'
 id: 6172 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '6172'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6172'
 id: 6173 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6173'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6173'
 id: 6174 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '6174'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6174'
 id: 6175 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6175'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6175'
 id: 6176 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '6176'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6176'
 id: 6177 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '6177'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6177'
 id: 6178 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6178'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6178'
 id: 6179 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6179'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6179'
 id: 6180 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '6180'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6180'
 id: 6181 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6181'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6181'
 id: 6182 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6182'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6182'
 id: 6183 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6183'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6183'
 id: 6184 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '6184'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6184'
 id: 6185 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6185'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6185'
 id: 6186 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '6186'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6186'
 id: 6187 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '6187'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6187'
 id: 6188 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6188'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6188'
 id: 6189 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '6189'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6189'
 id: 6190 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6190'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6190'
 id: 6191 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '6191'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6191'
 id: 6192 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '6192'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6192'
 id: 6193 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6193'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6193'
 id: 6194 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '6194'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6194'
 id: 6195 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6195'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6195'
 id: 6196 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '6196'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6196'
 id: 6197 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '6197'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6197'
 id: 6198 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '6198'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6198'
 id: 6199 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6199'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6199'
 id: 6200 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6200'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6200'
 id: 6201 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '6201'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6201'
 id: 6202 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6202'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6202'
 id: 6203 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6203'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6203'
 id: 6204 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6204'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6204'
 id: 6205 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '6205'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6205'
 id: 6206 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6206'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6206'
 id: 6207 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '6207'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6207'
 id: 6208 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6208'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6208'
 id: 6209 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '6209'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6209'
 id: 6210 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '6210'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6210'
 id: 6211 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '6211'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6211'
 id: 6212 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '6212'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6212'
 id: 6213 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6213'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6213'
 id: 6214 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6214'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6214'
 id: 6215 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6215'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6215'
 id: 6216 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '6216'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6216'
 id: 6217 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '6217'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6217'
 id: 6218 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '6218'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6218'
 id: 6219 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '6219'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6219'
 id: 6220 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '6220'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6220'
 id: 6221 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '6221'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6221'
 id: 6222 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6222'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6222'
 id: 6223 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6223'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6223'
 id: 6224 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '6224'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6224'
 id: 6225 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6225'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6225'
 id: 6226 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6226'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6226'
 id: 6227 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '6227'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6227'
 id: 6228 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '6228'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6228'
 id: 6229 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6229'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6229'
 id: 6230 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '6230'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6230'
 id: 6231 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6231'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6231'
 id: 6232 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6232'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6232'
 id: 6233 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '6233'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6233'
 id: 6234 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6234'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6234'
 id: 6235 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '6235'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6235'
 id: 6236 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '6236'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6236'
 id: 6237 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '6237'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6237'
 id: 6238 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '6238'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6238'
 id: 6239 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6239'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6239'
 id: 6240 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6240'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6240'
 id: 6241 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6241'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6241'
 id: 6242 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '6242'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6242'
 id: 6243 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6243'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6243'
 id: 6244 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '6244'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6244'
 id: 6245 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6245'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6245'
 id: 6246 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6246'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6246'
 id: 6247 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '6247'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6247'
 id: 6248 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '6248'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6248'
 id: 6249 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '6249'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6249'
 id: 6250 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '6250'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6250'
 id: 6251 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6251'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6251'
 id: 6252 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6252'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6252'
 id: 6253 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '6253'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6253'
 id: 6254 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '6254'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6254'
 id: 6255 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6255'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6255'
 id: 6256 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '6256'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6256'
 id: 6257 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '6257'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6257'
 id: 6258 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '6258'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6258'
 id: 6259 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6259'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6259'
 id: 6260 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '6260'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6260'
 id: 6261 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '6261'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6261'
 id: 6262 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6262'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6262'
 id: 6263 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6263'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6263'
 id: 6264 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6264'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6264'
 id: 6265 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '6265'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6265'
 id: 6266 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6266'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6266'
 id: 6267 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6267'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6267'
 id: 6268 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6268'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6268'
 id: 6269 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '6269'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6269'
 id: 6270 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '6270'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6270'
 id: 6271 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '6271'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6271'
 id: 6272 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '6272'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6272'
 id: 6273 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6273'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6273'
 id: 6274 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6274'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6274'
 id: 6275 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '6275'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6275'
 id: 6276 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6276'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6276'
 id: 6277 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '6277'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6277'
 id: 6278 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6278'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6278'
 id: 6279 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '6279'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6279'
 id: 6280 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6280'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6280'
 id: 6281 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '6281'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6281'
 id: 6282 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '6282'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6282'
 id: 6283 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6283'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6283'
 id: 6284 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '6284'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6284'
 id: 6285 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6285'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6285'
 id: 6286 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '6286'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6286'
 id: 6287 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '6287'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6287'
 id: 6288 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '6288'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6288'
 id: 6289 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6289'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6289'
 id: 6290 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '6290'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6290'
 id: 6291 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '6291'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6291'
 id: 6292 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6292'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6292'
 id: 6293 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '6293'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6293'
 id: 6294 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6294'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6294'
 id: 6295 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '6295'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6295'
 id: 6296 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6296'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6296'
 id: 6297 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6297'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6297'
 id: 6298 // word: 22
UPDATE job_vacancies SET domain_id =  '22' where raw_id = '6298'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6298'
 id: 6299 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6299'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6299'
 id: 6300 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6300'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6300'
 id: 6301 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6301'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6301'
 id: 6302 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6302'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6302'
 id: 6303 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6303'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6303'
 id: 6304 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '6304'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6304'
 id: 6305 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '6305'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6305'
 id: 6306 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6306'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6306'
 id: 6307 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '6307'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6307'
 id: 6308 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6308'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6308'
 id: 6309 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6309'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6309'
 id: 6310 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6310'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6310'
 id: 6311 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6311'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6311'
 id: 6312 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6312'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6312'
 id: 6313 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '6313'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6313'
 id: 6314 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '6314'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6314'
 id: 6315 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6315'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6315'
 id: 6316 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6316'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6316'
 id: 6317 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6317'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6317'
 id: 6318 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '6318'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6318'
 id: 6319 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6319'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6319'
 id: 6320 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '6320'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6320'
 id: 6321 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '6321'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6321'
 id: 6322 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '6322'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6322'
 id: 6323 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '6323'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6323'
 id: 6324 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '6324'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6324'
 id: 6325 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6325'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6325'
 id: 6326 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6326'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6326'
 id: 6327 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6327'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6327'
 id: 6328 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '6328'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6328'
 id: 6329 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '6329'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6329'
 id: 6330 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6330'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6330'
 id: 6331 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '6331'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6331'
 id: 6332 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6332'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6332'
 id: 6333 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6333'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6333'
 id: 6334 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6334'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6334'
 id: 6335 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '6335'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6335'
 id: 6336 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '6336'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6336'
 id: 6337 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '6337'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6337'
 id: 6338 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6338'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6338'
 id: 6339 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6339'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6339'
 id: 6340 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6340'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6340'
 id: 6341 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '6341'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6341'
 id: 6342 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '6342'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6342'
 id: 6343 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6343'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6343'
 id: 6344 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6344'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6344'
 id: 6345 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '6345'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6345'
 id: 6346 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '6346'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6346'
 id: 6347 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '6347'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6347'
 id: 6348 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6348'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6348'
 id: 6349 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '6349'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6349'
 id: 6350 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6350'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6350'
 id: 6351 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6351'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6351'
 id: 6352 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6352'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6352'
 id: 6353 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '6353'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6353'
 id: 6354 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6354'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6354'
 id: 6355 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6355'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6355'
 id: 6356 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6356'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6356'
 id: 6357 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '6357'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6357'
 id: 6358 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6358'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6358'
 id: 6359 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '6359'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6359'
 id: 6360 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6360'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6360'
 id: 6361 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6361'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6361'
 id: 6362 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '6362'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6362'
 id: 6363 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '6363'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6363'
 id: 6364 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6364'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6364'
 id: 6365 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6365'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6365'
 id: 6366 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6366'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6366'
 id: 6367 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '6367'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6367'
 id: 6368 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6368'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6368'
 id: 6369 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6369'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6369'
 id: 6370 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6370'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6370'
 id: 6371 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6371'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6371'
 id: 6372 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '6372'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6372'
 id: 6373 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6373'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6373'
 id: 6374 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6374'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6374'
 id: 6375 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6375'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6375'
 id: 6376 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6376'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6376'
 id: 6377 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6377'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6377'
 id: 6378 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6378'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6378'
 id: 6379 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6379'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6379'
 id: 6380 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '6380'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6380'
 id: 6381 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '6381'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6381'
 id: 6382 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6382'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6382'
 id: 6383 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6383'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6383'
 id: 6384 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6384'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6384'
 id: 6385 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '6385'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6385'
 id: 6386 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6386'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6386'
 id: 6387 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '6387'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6387'
 id: 6388 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6388'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6388'
 id: 6389 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '6389'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6389'
 id: 6390 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6390'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6390'
 id: 6391 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6391'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6391'
 id: 6392 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '6392'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6392'
 id: 6393 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6393'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6393'
 id: 6394 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '6394'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6394'
 id: 6395 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '6395'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6395'
 id: 6396 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '6396'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6396'
 id: 6397 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6397'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6397'
 id: 6398 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6398'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6398'
 id: 6399 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6399'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6399'
 id: 6400 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6400'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6400'
 id: 6401 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6401'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6401'
 id: 6402 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '6402'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6402'
 id: 6403 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6403'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6403'
 id: 6404 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6404'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6404'
 id: 6405 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '6405'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6405'
 id: 6406 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '6406'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6406'
 id: 6407 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6407'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6407'

 id: 6408 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '6408'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6408'
 id: 6409 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6409'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6409'
 id: 6410 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '6410'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6410'
 id: 6411 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6411'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6411'
 id: 6412 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6412'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6412'
 id: 6413 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6413'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6413'
 id: 6414 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '6414'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6414'
 id: 6415 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '6415'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6415'
 id: 6416 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '6416'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6416'
 id: 6417 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6417'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6417'
 id: 6418 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '6418'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6418'
 id: 6419 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6419'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6419'
 id: 6420 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '6420'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6420'
 id: 6421 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '6421'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6421'
 id: 6422 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6422'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6422'
 id: 6423 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6423'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6423'
 id: 6424 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '6424'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6424'
 id: 6425 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '6425'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6425'
 id: 6426 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6426'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6426'
 id: 6427 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6427'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6427'
 id: 6428 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '6428'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6428'
 id: 6429 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6429'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6429'
 id: 6430 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6430'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6430'
 id: 6431 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '6431'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6431'
 id: 6432 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6432'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6432'
 id: 6433 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '6433'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6433'
 id: 6434 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '6434'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6434'
 id: 6435 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6435'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6435'
 id: 6436 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6436'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6436'
 id: 6437 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '6437'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6437'
 id: 6438 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6438'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6438'
 id: 6439 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '6439'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6439'
 id: 6440 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '6440'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6440'
 id: 6441 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6441'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6441'
 id: 6442 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6442'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6442'
 id: 6443 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '6443'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6443'
 id: 6444 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6444'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6444'
 id: 6445 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '6445'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6445'
 id: 6446 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '6446'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6446'
 id: 6447 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '6447'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6447'
 id: 6448 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6448'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6448'
 id: 6449 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '6449'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6449'
 id: 6450 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6450'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6450'
 id: 6451 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '6451'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6451'
 id: 6452 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '6452'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6452'
 id: 6453 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '6453'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6453'
 id: 6454 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6454'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6454'
 id: 6455 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6455'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6455'
 id: 6456 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6456'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6456'
 id: 6457 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6457'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6457'
 id: 6458 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '6458'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6458'
 id: 6459 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6459'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6459'
 id: 6460 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '6460'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6460'
 id: 6461 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '6461'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6461'
 id: 6462 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6462'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6462'
 id: 6463 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '6463'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6463'
 id: 6464 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6464'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6464'
 id: 6465 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6465'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6465'
 id: 6466 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '6466'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6466'
 id: 6467 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6467'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6467'
 id: 6468 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6468'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6468'
 id: 6469 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '6469'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6469'
 id: 6470 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6470'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6470'
 id: 6471 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '6471'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6471'
 id: 6472 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6472'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6472'
 id: 6473 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '6473'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6473'
 id: 6474 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '6474'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6474'
 id: 6475 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '6475'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6475'
 id: 6476 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '6476'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6476'
 id: 6477 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6477'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6477'
 id: 6478 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6478'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6478'
 id: 6479 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '6479'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6479'
 id: 6480 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6480'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6480'
 id: 6481 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6481'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6481'
 id: 6482 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '6482'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6482'
 id: 6483 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6483'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6483'
 id: 6484 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6484'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6484'
 id: 6485 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '6485'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6485'
 id: 6486 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6486'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6486'
 id: 6487 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '6487'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6487'
 id: 6488 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6488'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6488'
 id: 6489 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6489'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6489'
 id: 6490 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '6490'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6490'
 id: 6491 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '6491'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6491'
 id: 6492 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6492'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6492'
 id: 6493 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '6493'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6493'
 id: 6494 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '6494'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6494'
 id: 6495 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6495'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6495'
 id: 6496 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6496'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6496'
 id: 6497 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6497'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6497'
 id: 6498 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '6498'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6498'
 id: 6499 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '6499'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6499'
 id: 6500 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6500'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6500'
 id: 6501 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '6501'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6501'
 id: 6502 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '6502'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6502'
 id: 6503 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6503'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6503'
 id: 6504 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '6504'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6504'
 id: 6505 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '6505'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6505'
 id: 6506 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6506'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6506'
 id: 6507 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '6507'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6507'
 id: 6508 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6508'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6508'
 id: 6509 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '6509'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6509'
 id: 6510 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '6510'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6510'
 id: 6511 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6511'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6511'
 id: 6512 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6512'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6512'
 id: 6513 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6513'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6513'
 id: 6514 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '6514'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6514'
 id: 6515 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '6515'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6515'
 id: 6516 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6516'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6516'
 id: 6517 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6517'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6517'
 id: 6518 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '6518'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6518'
 id: 6519 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '6519'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6519'
 id: 6520 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '6520'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6520'
 id: 6521 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6521'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6521'
 id: 6522 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6522'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6522'
 id: 6523 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '6523'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6523'
 id: 6524 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '6524'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6524'
 id: 6525 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '6525'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6525'
 id: 6526 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '6526'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6526'
 id: 6527 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '6527'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6527'
 id: 6528 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6528'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6528'
 id: 6529 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '6529'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6529'
 id: 6530 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6530'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6530'
 id: 6531 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '6531'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6531'
 id: 6532 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6532'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6532'
 id: 6533 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6533'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6533'
 id: 6534 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6534'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6534'
 id: 6535 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '6535'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6535'
 id: 6536 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6536'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6536'
 id: 6537 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6537'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6537'
 id: 6538 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '6538'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6538'
 id: 6539 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6539'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6539'
 id: 6540 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '6540'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6540'
 id: 6541 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6541'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6541'
 id: 6542 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6542'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6542'
 id: 6543 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6543'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6543'
 id: 6544 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '6544'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6544'
 id: 6545 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '6545'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6545'
 id: 6546 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6546'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6546'
 id: 6547 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '6547'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6547'
 id: 6548 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6548'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6548'
 id: 6549 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '6549'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6549'
 id: 6550 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6550'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6550'
 id: 6551 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '6551'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6551'
 id: 6552 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '6552'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6552'
 id: 6553 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6553'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6553'
 id: 6554 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6554'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6554'
 id: 6555 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6555'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6555'
 id: 6556 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '6556'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6556'
 id: 6557 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6557'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6557'
 id: 6558 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6558'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6558'
 id: 6559 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '6559'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6559'
 id: 6560 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6560'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6560'
 id: 6561 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '6561'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6561'
 id: 6562 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6562'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6562'
 id: 6563 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '6563'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6563'
 id: 6564 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6564'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6564'
 id: 6565 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '6565'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6565'
 id: 6566 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6566'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6566'
 id: 6567 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '6567'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6567'
 id: 6568 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '6568'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6568'
 id: 6569 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '6569'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6569'
 id: 6570 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '6570'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6570'
 id: 6571 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6571'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6571'
 id: 6572 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6572'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6572'
 id: 6573 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6573'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6573'
 id: 6574 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '6574'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6574'
 id: 6575 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '6575'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6575'
 id: 6576 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '6576'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6576'
 id: 6577 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6577'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6577'
 id: 6578 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '6578'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6578'
 id: 6579 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '6579'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6579'
 id: 6580 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6580'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6580'
 id: 6581 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6581'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6581'
 id: 6582 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '6582'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6582'
 id: 6583 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '6583'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6583'
 id: 6584 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6584'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6584'
 id: 6585 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6585'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6585'
 id: 6586 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '6586'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6586'
 id: 6587 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '6587'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6587'
 id: 6588 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '6588'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6588'
 id: 6589 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6589'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6589'
 id: 6590 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '6590'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6590'
 id: 6591 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '6591'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6591'
 id: 6592 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6592'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6592'
 id: 6593 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6593'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6593'
 id: 6594 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '6594'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6594'
 id: 6595 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6595'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6595'
 id: 6596 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '6596'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6596'
 id: 6597 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6597'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6597'
 id: 6598 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6598'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6598'
 id: 6599 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '6599'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6599'
 id: 6600 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '6600'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6600'
 id: 6601 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6601'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6601'
 id: 6602 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6602'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6602'
 id: 6603 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6603'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6603'
 id: 6604 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '6604'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6604'
 id: 6605 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6605'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6605'
 id: 6606 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6606'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6606'
 id: 6607 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6607'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6607'
 id: 6608 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6608'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6608'
 id: 6609 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6609'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6609'
 id: 6610 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6610'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6610'
 id: 6611 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6611'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6611'

 id: 6612 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6612'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6612'
 id: 6613 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6613'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6613'
 id: 6614 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6614'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6614'
 id: 6615 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6615'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6615'
 id: 6616 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6616'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6616'
 id: 6617 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6617'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6617'
 id: 6618 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '6618'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6618'
 id: 6619 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6619'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6619'
 id: 6620 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6620'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6620'
 id: 6621 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '6621'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6621'
 id: 6622 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6622'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6622'
 id: 6623 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6623'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6623'
 id: 6624 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '6624'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6624'
 id: 6625 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6625'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6625'
 id: 6626 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6626'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6626'
 id: 6627 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6627'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6627'
 id: 6628 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6628'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6628'
 id: 6629 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '6629'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6629'
 id: 6630 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6630'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6630'
 id: 6631 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6631'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6631'
 id: 6632 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6632'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6632'
 id: 6633 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6633'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6633'
 id: 6634 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '6634'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6634'
 id: 6635 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6635'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6635'
 id: 6636 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6636'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6636'
 id: 6637 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6637'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6637'
 id: 6638 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '6638'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6638'
 id: 6639 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '6639'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6639'
 id: 6640 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6640'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6640'
 id: 6641 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6641'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6641'
 id: 6642 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '6642'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6642'
 id: 6643 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '6643'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6643'
 id: 6644 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6644'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6644'
 id: 6645 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6645'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6645'
 id: 6646 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '6646'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6646'
 id: 6647 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '6647'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6647'
 id: 6648 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6648'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6648'
 id: 6649 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6649'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6649'
 id: 6650 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '6650'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6650'
 id: 6651 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '6651'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6651'
 id: 6652 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '6652'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6652'
 id: 6653 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '6653'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6653'
 id: 6654 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6654'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6654'
 id: 6655 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6655'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6655'
 id: 6656 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '6656'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6656'
 id: 6657 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6657'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6657'
 id: 6658 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6658'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6658'
 id: 6659 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6659'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6659'
 id: 6660 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '6660'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6660'
 id: 6661 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6661'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6661'
 id: 6662 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6662'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6662'
 id: 6663 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '6663'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6663'
 id: 6664 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '6664'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6664'
 id: 6665 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '6665'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6665'
 id: 6666 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6666'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6666'
 id: 6667 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '6667'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6667'
 id: 6668 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '6668'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6668'
 id: 6669 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6669'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6669'
 id: 6670 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '6670'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6670'
 id: 6671 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6671'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6671'
 id: 6672 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6672'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6672'
 id: 6673 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '6673'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6673'
 id: 6674 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6674'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6674'
 id: 6675 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6675'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6675'
 id: 6676 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6676'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6676'
 id: 6677 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6677'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6677'
 id: 6678 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '6678'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6678'
 id: 6679 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '6679'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6679'
 id: 6680 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '6680'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6680'
 id: 6681 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '6681'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6681'
 id: 6682 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '6682'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6682'
 id: 6683 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '6683'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6683'
 id: 6684 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6684'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6684'
 id: 6685 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '6685'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6685'
 id: 6686 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6686'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6686'
 id: 6687 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '6687'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6687'
 id: 6688 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '6688'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6688'
 id: 6689 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6689'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6689'
 id: 6690 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '6690'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6690'
 id: 6691 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6691'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6691'
 id: 6692 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6692'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6692'
 id: 6693 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '6693'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6693'
 id: 6694 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6694'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6694'
 id: 6695 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6695'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6695'
 id: 6696 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '6696'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6696'
 id: 6697 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6697'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6697'
 id: 6698 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6698'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6698'
 id: 6699 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '6699'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6699'
 id: 6700 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '6700'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6700'
 id: 6701 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6701'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6701'
 id: 6702 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '6702'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6702'
 id: 6703 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '6703'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6703'
 id: 6704 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6704'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6704'
 id: 6705 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6705'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6705'
 id: 6706 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '6706'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6706'
 id: 6707 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6707'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6707'
 id: 6708 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6708'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6708'
 id: 6709 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '6709'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6709'
 id: 6710 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '6710'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6710'
 id: 6711 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '6711'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6711'
 id: 6712 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '6712'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6712'
 id: 6713 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '6713'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6713'
 id: 6714 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '6714'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6714'
 id: 6715 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '6715'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6715'
 id: 6716 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6716'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6716'
 id: 6717 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6717'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6717'
 id: 6718 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '6718'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6718'
 id: 6719 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '6719'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6719'
 id: 6720 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '6720'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6720'
 id: 6721 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '6721'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6721'
 id: 6722 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '6722'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6722'
 id: 6723 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6723'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6723'
 id: 6724 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '6724'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6724'
 id: 6725 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6725'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6725'
 id: 6726 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '6726'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6726'
 id: 6727 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6727'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6727'
 id: 6728 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6728'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6728'
 id: 6729 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '6729'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6729'
 id: 6730 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6730'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6730'
 id: 6731 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '6731'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6731'
 id: 6732 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6732'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6732'
 id: 6733 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '6733'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6733'
 id: 6734 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6734'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6734'
 id: 6735 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6735'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6735'
 id: 6736 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '6736'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6736'
 id: 6737 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '6737'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6737'
 id: 6738 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6738'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6738'
 id: 6739 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6739'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6739'
 id: 6740 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6740'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6740'
 id: 6741 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6741'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6741'
 id: 6742 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6742'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6742'
 id: 6743 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '6743'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6743'
 id: 6744 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '6744'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6744'
 id: 6745 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '6745'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6745'
 id: 6746 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6746'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6746'
 id: 6747 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6747'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6747'
 id: 6748 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6748'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6748'
 id: 6749 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6749'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6749'
 id: 6750 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6750'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6750'
 id: 6751 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '6751'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6751'
 id: 6752 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6752'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6752'
 id: 6753 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6753'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6753'
 id: 6754 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6754'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6754'
 id: 6755 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6755'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6755'
 id: 6756 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '6756'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6756'
 id: 6757 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6757'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6757'
 id: 6758 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '6758'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6758'
 id: 6759 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '6759'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6759'
 id: 6760 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '6760'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6760'
 id: 6761 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6761'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6761'
 id: 6762 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6762'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6762'
 id: 6763 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6763'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6763'
 id: 6764 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6764'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6764'
 id: 6765 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '6765'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6765'

 id: 6766 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6766'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6766'
 id: 6767 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6767'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6767'
 id: 6768 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6768'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6768'
 id: 6769 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6769'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6769'
 id: 6770 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6770'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6770'
 id: 6771 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '6771'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6771'
 id: 6772 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6772'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6772'
 id: 6773 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '6773'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6773'
 id: 6774 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '6774'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6774'
 id: 6775 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '6775'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6775'
 id: 6776 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6776'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6776'
 id: 6777 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6777'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6777'
 id: 6778 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6778'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6778'
 id: 6779 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '6779'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6779'
 id: 6780 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6780'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6780'
 id: 6781 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6781'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6781'
 id: 6782 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6782'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6782'
 id: 6783 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '6783'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6783'
 id: 6784 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '6784'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6784'
 id: 6785 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6785'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6785'
 id: 6786 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6786'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6786'
 id: 6787 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '6787'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6787'
 id: 6788 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6788'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6788'
 id: 6789 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '6789'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6789'
 id: 6790 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6790'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6790'
 id: 6791 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6791'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6791'
 id: 6792 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6792'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6792'
 id: 6793 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '6793'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6793'
 id: 6794 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6794'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6794'
 id: 6795 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '6795'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6795'
 id: 6796 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '6796'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6796'
 id: 6797 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6797'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6797'
 id: 6798 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6798'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6798'
 id: 6799 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '6799'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6799'
 id: 6800 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6800'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6800'
 id: 6801 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6801'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6801'
 id: 6802 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '6802'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6802'
 id: 6803 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6803'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6803'
 id: 6804 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6804'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6804'
 id: 6805 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6805'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6805'
 id: 6806 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6806'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6806'
 id: 6807 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '6807'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6807'
 id: 6808 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '6808'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6808'
 id: 6809 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6809'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6809'
 id: 6810 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '6810'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6810'
 id: 6811 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '6811'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6811'
 id: 6812 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6812'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6812'
 id: 6813 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6813'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6813'
 id: 6814 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6814'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6814'
 id: 6815 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6815'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6815'
 id: 6816 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '6816'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6816'

 id: 6817 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '6817'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6817'
 id: 6818 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6818'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6818'
 id: 6819 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6819'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6819'
 id: 6820 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6820'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6820'
 id: 6821 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6821'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6821'
 id: 6822 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '6822'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6822'
 id: 6823 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '6823'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6823'
 id: 6824 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6824'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6824'
 id: 6825 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '6825'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6825'
 id: 6826 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '6826'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6826'
 id: 6827 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '6827'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6827'
 id: 6828 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '6828'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6828'
 id: 6829 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6829'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6829'
 id: 6830 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '6830'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6830'
 id: 6831 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '6831'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6831'
 id: 6832 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6832'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6832'
 id: 6833 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '6833'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6833'
 id: 6834 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '6834'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6834'
 id: 6835 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '6835'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6835'
 id: 6836 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6836'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6836'
 id: 6837 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '6837'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6837'
 id: 6838 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6838'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6838'
 id: 6839 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6839'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6839'
 id: 6840 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '6840'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6840'
 id: 6841 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6841'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6841'
 id: 6842 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '6842'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6842'
 id: 6843 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6843'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6843'
 id: 6844 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '6844'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6844'
 id: 6845 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '6845'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6845'
 id: 6846 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '6846'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6846'
 id: 6847 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '6847'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6847'
 id: 6848 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6848'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6848'
 id: 6849 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6849'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6849'
 id: 6850 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6850'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6850'
 id: 6851 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '6851'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6851'
 id: 6852 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6852'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6852'
 id: 6853 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6853'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6853'
 id: 6854 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6854'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6854'
 id: 6855 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '6855'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6855'
 id: 6856 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6856'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6856'
 id: 6857 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '6857'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6857'
 id: 6858 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '6858'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6858'
 id: 6859 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '6859'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6859'
 id: 6860 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6860'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6860'
 id: 6861 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '6861'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6861'
 id: 6862 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6862'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6862'
 id: 6863 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '6863'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6863'
 id: 6864 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6864'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6864'
 id: 6865 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '6865'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6865'
 id: 6866 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6866'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6866'
 id: 6867 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '6867'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6867'
 id: 6868 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6868'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6868'
 id: 6869 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6869'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6869'
 id: 6870 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '6870'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6870'
 id: 6871 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6871'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6871'
 id: 6872 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '6872'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6872'
 id: 6873 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '6873'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6873'
 id: 6874 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '6874'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6874'
 id: 6875 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6875'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6875'
 id: 6876 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '6876'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6876'
 id: 6877 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6877'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6877'
 id: 6878 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '6878'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6878'
 id: 6879 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6879'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6879'
 id: 6880 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6880'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6880'
 id: 6881 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '6881'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6881'
 id: 6882 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '6882'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6882'
 id: 6883 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6883'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6883'
 id: 6884 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '6884'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6884'
 id: 6885 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '6885'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6885'
 id: 6886 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '6886'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6886'
 id: 6887 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '6887'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6887'
 id: 6888 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6888'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6888'
 id: 6889 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6889'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6889'
 id: 6890 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '6890'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6890'
 id: 6891 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '6891'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6891'
 id: 6892 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '6892'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6892'
 id: 6893 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '6893'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6893'
 id: 6894 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6894'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6894'
 id: 6895 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6895'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6895'
 id: 6896 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '6896'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6896'
 id: 6897 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6897'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6897'
 id: 6898 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6898'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6898'
 id: 6899 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6899'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6899'
 id: 6900 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6900'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6900'
 id: 6901 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '6901'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6901'
 id: 6902 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '6902'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6902'
 id: 6903 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '6903'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6903'
 id: 6904 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '6904'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6904'
 id: 6905 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6905'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6905'
 id: 6906 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6906'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6906'
 id: 6907 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '6907'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6907'
 id: 6908 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6908'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6908'
 id: 6909 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '6909'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6909'
 id: 6910 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '6910'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6910'
 id: 6911 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '6911'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6911'
 id: 6912 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '6912'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6912'
 id: 6913 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '6913'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6913'
 id: 6914 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6914'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6914'
 id: 6915 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6915'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6915'
 id: 6916 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6916'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6916'
 id: 6917 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6917'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6917'
 id: 6918 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '6918'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6918'
 id: 6919 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6919'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6919'
 id: 6920 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '6920'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6920'
 id: 6921 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '6921'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6921'
 id: 6922 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '6922'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6922'
 id: 6923 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '6923'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6923'
 id: 6924 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6924'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6924'
 id: 6925 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6925'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6925'
 id: 6926 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6926'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6926'
 id: 6927 // word: 66
UPDATE job_vacancies SET domain_id =  '66' where raw_id = '6927'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6927'
 id: 6928 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '6928'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6928'
 id: 6929 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '6929'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6929'
 id: 6930 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6930'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6930'
 id: 6931 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '6931'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6931'
 id: 6932 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '6932'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6932'
 id: 6933 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '6933'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6933'
 id: 6934 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '6934'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6934'
 id: 6935 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6935'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6935'
 id: 6936 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '6936'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6936'
 id: 6937 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6937'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6937'
 id: 6938 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '6938'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6938'
 id: 6939 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '6939'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6939'
 id: 6940 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6940'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6940'
 id: 6941 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6941'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6941'
 id: 6942 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6942'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6942'
 id: 6943 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '6943'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6943'
 id: 6944 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '6944'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6944'
 id: 6945 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6945'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6945'
 id: 6946 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '6946'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6946'
 id: 6947 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '6947'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6947'
 id: 6948 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6948'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6948'
 id: 6949 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6949'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6949'
 id: 6950 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6950'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6950'
 id: 6951 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6951'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6951'
 id: 6952 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '6952'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6952'
 id: 6953 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6953'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6953'
 id: 6954 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '6954'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6954'
 id: 6955 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6955'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6955'
 id: 6956 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '6956'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6956'
 id: 6957 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '6957'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6957'
 id: 6958 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6958'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6958'
 id: 6959 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '6959'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6959'
 id: 6960 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6960'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6960'
 id: 6961 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6961'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6961'
 id: 6962 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '6962'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6962'
 id: 6963 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6963'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6963'
 id: 6964 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6964'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6964'
 id: 6965 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '6965'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6965'
 id: 6966 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6966'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6966'
 id: 6967 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '6967'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6967'
 id: 6968 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '6968'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6968'
 id: 6969 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6969'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6969'
 id: 6970 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '6970'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6970'
 id: 6971 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6971'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6971'
 id: 6972 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6972'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6972'
 id: 6973 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6973'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6973'
 id: 6974 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6974'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6974'
 id: 6975 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6975'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6975'
 id: 6976 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '6976'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6976'
 id: 6977 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '6977'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6977'
 id: 6978 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6978'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6978'
 id: 6979 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '6979'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6979'
 id: 6980 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '6980'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6980'
 id: 6981 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '6981'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6981'
 id: 6982 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '6982'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6982'
 id: 6983 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6983'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6983'
 id: 6984 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6984'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6984'
 id: 6985 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '6985'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6985'
 id: 6986 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6986'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6986'
 id: 6987 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '6987'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6987'
 id: 6988 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '6988'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6988'
 id: 6989 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6989'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6989'
 id: 6990 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '6990'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6990'
 id: 6991 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6991'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6991'
 id: 6992 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6992'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6992'
 id: 6993 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '6993'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6993'
 id: 6994 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '6994'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6994'
 id: 6995 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '6995'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6995'
 id: 6996 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '6996'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6996'
 id: 6997 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '6997'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6997'
 id: 6998 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '6998'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6998'
 id: 6999 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '6999'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '6999'
 id: 7000 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '7000'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7000'
 id: 7001 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '7001'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7001'
 id: 7002 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '7002'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7002'
 id: 7003 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7003'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7003'
 id: 7004 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '7004'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7004'
 id: 7005 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '7005'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7005'
 id: 7006 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7006'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7006'
 id: 7007 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7007'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7007'
 id: 7008 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7008'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7008'
 id: 7009 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '7009'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7009'
 id: 7010 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '7010'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7010'
 id: 7011 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '7011'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7011'
 id: 7012 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '7012'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7012'
 id: 7013 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7013'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7013'
 id: 7014 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '7014'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7014'
 id: 7015 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '7015'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7015'
 id: 7016 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7016'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7016'
 id: 7017 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '7017'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7017'
 id: 7018 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '7018'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7018'
 id: 7019 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '7019'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7019'
 id: 7020 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7020'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7020'
 id: 7021 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '7021'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7021'
 id: 7022 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7022'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7022'
 id: 7023 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7023'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7023'
 id: 7024 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7024'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7024'
 id: 7025 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7025'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7025'
 id: 7026 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '7026'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7026'
 id: 7027 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7027'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7027'
 id: 7028 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7028'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7028'
 id: 7029 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7029'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7029'
 id: 7030 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7030'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7030'
 id: 7031 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '7031'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7031'
 id: 7032 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '7032'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7032'
 id: 7033 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '7033'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7033'
 id: 7034 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '7034'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7034'
 id: 7035 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7035'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7035'
 id: 7036 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7036'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7036'
 id: 7037 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7037'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7037'
 id: 7038 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '7038'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7038'
 id: 7039 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7039'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7039'
 id: 7040 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7040'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7040'
 id: 7041 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7041'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7041'
 id: 7042 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7042'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7042'
 id: 7043 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7043'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7043'
 id: 7044 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '7044'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7044'
 id: 7045 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7045'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7045'
 id: 7046 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7046'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7046'
 id: 7047 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7047'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7047'
 id: 7048 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '7048'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7048'
 id: 7049 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7049'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7049'
 id: 7050 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7050'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7050'
 id: 7051 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7051'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7051'
 id: 7052 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7052'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7052'
 id: 7053 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7053'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7053'
 id: 7054 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '7054'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7054'
 id: 7055 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '7055'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7055'
 id: 7056 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7056'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7056'
 id: 7057 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7057'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7057'
 id: 7058 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '7058'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7058'
 id: 7059 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7059'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7059'
 id: 7060 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '7060'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7060'
 id: 7061 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7061'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7061'
 id: 7062 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '7062'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7062'
 id: 7063 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '7063'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7063'
 id: 7064 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '7064'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7064'
 id: 7065 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7065'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7065'
 id: 7066 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '7066'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7066'
 id: 7067 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7067'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7067'
 id: 7068 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7068'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7068'
 id: 7069 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7069'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7069'
 id: 7070 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '7070'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7070'
 id: 7071 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7071'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7071'
 id: 7072 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7072'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7072'
 id: 7073 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '7073'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7073'
 id: 7074 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7074'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7074'

 id: 7075 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '7075'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7075'
 id: 7076 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '7076'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7076'
 id: 7077 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7077'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7077'
 id: 7078 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7078'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7078'
 id: 7079 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '7079'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7079'
 id: 7080 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '7080'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7080'
 id: 7081 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '7081'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7081'
 id: 7082 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7082'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7082'
 id: 7083 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '7083'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7083'
 id: 7084 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '7084'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7084'
 id: 7085 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '7085'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7085'
 id: 7086 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7086'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7086'
 id: 7087 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '7087'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7087'
 id: 7088 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7088'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7088'
 id: 7089 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7089'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7089'
 id: 7090 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '7090'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7090'
 id: 7091 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7091'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7091'
 id: 7092 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7092'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7092'
 id: 7093 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '7093'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7093'
 id: 7094 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '7094'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7094'
 id: 7095 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '7095'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7095'
 id: 7096 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7096'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7096'
 id: 7097 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7097'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7097'
 id: 7098 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '7098'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7098'
 id: 7099 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7099'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7099'
 id: 7100 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7100'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7100'
 id: 7101 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7101'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7101'
 id: 7102 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7102'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7102'
 id: 7103 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '7103'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7103'
 id: 7104 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '7104'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7104'
 id: 7105 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7105'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7105'
 id: 7106 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7106'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7106'
 id: 7107 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7107'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7107'
 id: 7108 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '7108'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7108'
 id: 7109 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7109'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7109'
 id: 7110 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7110'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7110'
 id: 7111 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7111'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7111'
 id: 7112 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '7112'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7112'
 id: 7113 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '7113'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7113'
 id: 7114 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '7114'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7114'
 id: 7115 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7115'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7115'
 id: 7116 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '7116'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7116'
 id: 7117 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7117'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7117'
 id: 7118 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '7118'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7118'
 id: 7119 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '7119'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7119'
 id: 7120 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7120'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7120'
 id: 7121 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7121'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7121'
 id: 7122 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '7122'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7122'
 id: 7123 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7123'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7123'
 id: 7124 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '7124'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7124'
 id: 7125 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '7125'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7125'
 id: 7126 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '7126'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7126'
 id: 7127 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7127'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7127'
 id: 7128 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7128'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7128'
 id: 7129 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '7129'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7129'
 id: 7130 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '7130'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7130'
 id: 7131 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7131'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7131'
 id: 7132 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '7132'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7132'
 id: 7133 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '7133'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7133'
 id: 7134 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7134'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7134'
 id: 7135 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '7135'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7135'
 id: 7136 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7136'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7136'
 id: 7137 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7137'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7137'
 id: 7138 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '7138'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7138'
 id: 7139 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '7139'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7139'
 id: 7140 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7140'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7140'
 id: 7141 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7141'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7141'
 id: 7142 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7142'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7142'
 id: 7143 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '7143'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7143'
 id: 7144 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '7144'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7144'
 id: 7145 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '7145'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7145'
 id: 7146 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7146'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7146'
 id: 7147 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7147'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7147'
 id: 7148 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7148'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7148'
 id: 7149 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '7149'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7149'
 id: 7150 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7150'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7150'
 id: 7151 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7151'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7151'
 id: 7152 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7152'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7152'
 id: 7153 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7153'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7153'
 id: 7154 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7154'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7154'
 id: 7155 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '7155'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7155'
 id: 7156 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7156'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7156'
 id: 7157 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '7157'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7157'
 id: 7158 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7158'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7158'
 id: 7159 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '7159'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7159'
 id: 7160 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7160'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7160'
 id: 7161 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7161'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7161'
 id: 7162 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '7162'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7162'
 id: 7163 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '7163'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7163'
 id: 7164 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7164'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7164'
 id: 7165 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '7165'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7165'
 id: 7166 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7166'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7166'
 id: 7167 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '7167'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7167'
 id: 7168 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '7168'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7168'
 id: 7169 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7169'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7169'
 id: 7170 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7170'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7170'
 id: 7171 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '7171'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7171'
 id: 7172 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7172'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7172'
 id: 7173 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7173'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7173'
 id: 7174 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '7174'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7174'
 id: 7175 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7175'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7175'
 id: 7176 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7176'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7176'
 id: 7177 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7177'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7177'
 id: 7178 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7178'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7178'

 id: 7179 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7179'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7179'
 id: 7180 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7180'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7180'
 id: 7181 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '7181'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7181'
 id: 7182 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '7182'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7182'
 id: 7183 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7183'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7183'
 id: 7184 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7184'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7184'
 id: 7185 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7185'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7185'
 id: 7186 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '7186'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7186'
 id: 7187 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7187'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7187'
 id: 7188 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7188'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7188'
 id: 7189 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '7189'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7189'
 id: 7190 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7190'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7190'
 id: 7191 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '7191'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7191'
 id: 7192 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7192'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7192'
 id: 7193 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '7193'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7193'
 id: 7194 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '7194'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7194'
 id: 7195 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '7195'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7195'
 id: 7196 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7196'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7196'
 id: 7197 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '7197'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7197'
 id: 7198 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '7198'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7198'
 id: 7199 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '7199'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7199'
 id: 7200 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '7200'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7200'
 id: 7201 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '7201'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7201'
 id: 7202 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7202'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7202'
 id: 7203 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '7203'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7203'
 id: 7204 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '7204'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7204'
 id: 7205 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7205'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7205'
 id: 7206 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7206'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7206'
 id: 7207 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7207'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7207'
 id: 7208 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '7208'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7208'
 id: 7209 // word: 22
UPDATE job_vacancies SET domain_id =  '22' where raw_id = '7209'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7209'
 id: 7210 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '7210'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7210'
 id: 7211 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7211'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7211'
 id: 7212 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '7212'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7212'
 id: 7213 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '7213'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7213'
 id: 7214 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7214'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7214'
 id: 7215 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7215'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7215'
 id: 7216 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7216'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7216'
 id: 7217 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '7217'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7217'
 id: 7218 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7218'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7218'
 id: 7219 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7219'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7219'
 id: 7220 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7220'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7220'
 id: 7221 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '7221'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7221'
 id: 7222 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7222'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7222'
 id: 7223 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '7223'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7223'
 id: 7224 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '7224'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7224'
 id: 7225 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '7225'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7225'
 id: 7226 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7226'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7226'
 id: 7227 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7227'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7227'
 id: 7228 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7228'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7228'
 id: 7229 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7229'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7229'
 id: 7230 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '7230'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7230'
 id: 7231 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7231'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7231'
 id: 7232 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7232'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7232'
 id: 7233 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '7233'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7233'
 id: 7234 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '7234'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7234'
 id: 7235 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7235'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7235'
 id: 7236 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '7236'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7236'
 id: 7237 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7237'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7237'
 id: 7238 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7238'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7238'
 id: 7239 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7239'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7239'
 id: 7240 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7240'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7240'
 id: 7241 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '7241'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7241'
 id: 7242 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '7242'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7242'
 id: 7243 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '7243'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7243'
 id: 7244 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '7244'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7244'
 id: 7245 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7245'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7245'
 id: 7246 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7246'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7246'
 id: 7247 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7247'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7247'
 id: 7248 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7248'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7248'
 id: 7249 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7249'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7249'
 id: 7250 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7250'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7250'
 id: 7251 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7251'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7251'
 id: 7252 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '7252'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7252'
 id: 7253 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7253'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7253'
 id: 7254 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '7254'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7254'
 id: 7255 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7255'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7255'
 id: 7256 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '7256'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7256'
 id: 7257 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '7257'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7257'
 id: 7258 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '7258'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7258'
 id: 7259 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '7259'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7259'
 id: 7260 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7260'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7260'
 id: 7261 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7261'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7261'
 id: 7262 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '7262'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7262'
 id: 7263 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '7263'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7263'
 id: 7264 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7264'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7264'
 id: 7265 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7265'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7265'
 id: 7266 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7266'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7266'
 id: 7267 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '7267'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7267'
 id: 7268 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7268'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7268'
 id: 7269 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '7269'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7269'
 id: 7270 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7270'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7270'
 id: 7271 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7271'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7271'
 id: 7272 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '7272'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7272'
 id: 7273 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '7273'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7273'
 id: 7274 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7274'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7274'
 id: 7275 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '7275'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7275'
 id: 7276 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7276'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7276'
 id: 7277 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7277'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7277'
 id: 7278 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '7278'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7278'
 id: 7279 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7279'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7279'
 id: 7280 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '7280'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7280'

 id: 7281 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7281'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7281'
 id: 7282 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '7282'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7282'
 id: 7283 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '7283'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7283'
 id: 7284 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7284'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7284'
 id: 7285 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '7285'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7285'
 id: 7286 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '7286'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7286'
 id: 7287 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7287'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7287'
 id: 7288 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7288'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7288'
 id: 7289 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7289'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7289'
 id: 7290 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '7290'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7290'
 id: 7291 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7291'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7291'
 id: 7292 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7292'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7292'
 id: 7293 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7293'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7293'
 id: 7294 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '7294'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7294'
 id: 7295 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7295'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7295'
 id: 7296 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '7296'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7296'
 id: 7297 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7297'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7297'
 id: 7298 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7298'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7298'
 id: 7299 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '7299'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7299'
 id: 7300 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '7300'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7300'
 id: 7301 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '7301'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7301'
 id: 7302 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '7302'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7302'
 id: 7303 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '7303'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7303'
 id: 7304 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7304'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7304'
 id: 7305 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7305'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7305'
 id: 7306 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7306'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7306'
 id: 7307 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7307'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7307'
 id: 7308 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7308'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7308'
 id: 7309 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7309'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7309'
 id: 7310 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7310'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7310'
 id: 7311 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '7311'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7311'
 id: 7312 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '7312'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7312'
 id: 7313 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '7313'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7313'
 id: 7314 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '7314'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7314'
 id: 7315 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '7315'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7315'
 id: 7316 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7316'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7316'
 id: 7317 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '7317'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7317'
 id: 7318 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7318'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7318'
 id: 7319 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '7319'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7319'
 id: 7320 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7320'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7320'
 id: 7321 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7321'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7321'
 id: 7322 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7322'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7322'
 id: 7323 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '7323'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7323'
 id: 7324 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '7324'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7324'
 id: 7325 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7325'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7325'
 id: 7326 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7326'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7326'
 id: 7327 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '7327'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7327'
 id: 7328 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '7328'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7328'
 id: 7329 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7329'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7329'
 id: 7330 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7330'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7330'
 id: 7331 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7331'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7331'
 id: 7332 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7332'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7332'
 id: 7333 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7333'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7333'
 id: 7334 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '7334'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7334'
 id: 7335 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7335'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7335'
 id: 7336 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '7336'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7336'
 id: 7337 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '7337'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7337'
 id: 7338 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7338'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7338'
 id: 7339 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7339'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7339'
 id: 7340 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7340'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7340'
 id: 7341 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '7341'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7341'
 id: 7342 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7342'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7342'
 id: 7343 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7343'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7343'
 id: 7344 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7344'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7344'
 id: 7345 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '7345'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7345'
 id: 7346 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7346'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7346'
 id: 7347 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '7347'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7347'
 id: 7348 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '7348'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7348'
 id: 7349 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7349'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7349'
 id: 7350 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7350'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7350'
 id: 7351 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7351'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7351'
 id: 7352 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7352'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7352'
 id: 7353 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7353'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7353'
 id: 7354 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7354'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7354'
 id: 7355 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7355'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7355'
 id: 7356 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '7356'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7356'
 id: 7357 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7357'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7357'
 id: 7358 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '7358'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7358'
 id: 7359 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7359'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7359'
 id: 7360 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '7360'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7360'
 id: 7361 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '7361'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7361'
 id: 7362 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '7362'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7362'
 id: 7363 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '7363'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7363'
 id: 7364 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7364'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7364'
 id: 7365 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '7365'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7365'
 id: 7366 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '7366'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7366'
 id: 7367 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '7367'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7367'
 id: 7368 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7368'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7368'
 id: 7369 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '7369'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7369'
 id: 7370 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '7370'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7370'
 id: 7371 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7371'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7371'
 id: 7372 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7372'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7372'
 id: 7373 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '7373'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7373'
 id: 7374 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7374'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7374'
 id: 7375 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '7375'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7375'
 id: 7376 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7376'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7376'
 id: 7377 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7377'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7377'
 id: 7378 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7378'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7378'
 id: 7379 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7379'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7379'
 id: 7380 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '7380'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7380'
 id: 7381 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7381'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7381'
 id: 7382 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7382'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7382'
 id: 7383 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '7383'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7383'
 id: 7384 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '7384'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7384'
 id: 7385 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7385'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7385'
 id: 7386 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7386'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7386'
 id: 7387 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7387'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7387'
 id: 7388 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7388'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7388'
 id: 7389 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7389'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7389'
 id: 7390 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7390'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7390'
 id: 7391 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '7391'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7391'
 id: 7392 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7392'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7392'
 id: 7393 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '7393'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7393'
 id: 7394 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '7394'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7394'
 id: 7395 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7395'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7395'
 id: 7396 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7396'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7396'
 id: 7397 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '7397'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7397'
 id: 7398 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7398'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7398'
 id: 7399 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7399'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7399'
 id: 7400 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7400'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7400'
 id: 7401 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7401'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7401'
 id: 7402 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '7402'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7402'
 id: 7403 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7403'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7403'
 id: 7404 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7404'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7404'
 id: 7405 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7405'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7405'
 id: 7406 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7406'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7406'
 id: 7407 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '7407'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7407'
 id: 7408 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '7408'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7408'
 id: 7409 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7409'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7409'
 id: 7410 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '7410'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7410'
 id: 7411 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '7411'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7411'
 id: 7412 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7412'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7412'
 id: 7413 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7413'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7413'
 id: 7414 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '7414'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7414'
 id: 7415 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '7415'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7415'
 id: 7416 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '7416'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7416'
 id: 7417 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '7417'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7417'
 id: 7418 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7418'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7418'
 id: 7419 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '7419'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7419'
 id: 7420 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7420'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7420'
 id: 7421 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '7421'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7421'
 id: 7422 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '7422'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7422'
 id: 7423 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7423'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7423'
 id: 7424 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7424'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7424'
 id: 7425 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '7425'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7425'
 id: 7426 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '7426'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7426'
 id: 7427 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '7427'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7427'
 id: 7428 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '7428'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7428'
 id: 7429 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7429'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7429'
 id: 7430 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '7430'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7430'
 id: 7431 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '7431'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7431'
 id: 7432 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '7432'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7432'
 id: 7433 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7433'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7433'
 id: 7434 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7434'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7434'
 id: 7435 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '7435'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7435'
 id: 7436 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '7436'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7436'
 id: 7437 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7437'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7437'
 id: 7438 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7438'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7438'
 id: 7439 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '7439'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7439'
 id: 7440 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '7440'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7440'
 id: 7441 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7441'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7441'
 id: 7442 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '7442'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7442'
 id: 7443 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '7443'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7443'
 id: 7444 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '7444'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7444'
 id: 7445 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7445'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7445'
 id: 7446 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7446'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7446'
 id: 7447 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '7447'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7447'
 id: 7448 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '7448'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7448'
 id: 7449 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7449'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7449'
 id: 7450 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7450'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7450'
 id: 7451 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '7451'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7451'
 id: 7452 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7452'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7452'
 id: 7453 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7453'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7453'
 id: 7454 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7454'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7454'
 id: 7455 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7455'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7455'
 id: 7456 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7456'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7456'
 id: 7457 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7457'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7457'
 id: 7458 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '7458'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7458'
 id: 7459 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '7459'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7459'
 id: 7460 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7460'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7460'
 id: 7461 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '7461'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7461'
 id: 7462 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '7462'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7462'
 id: 7463 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7463'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7463'
 id: 7464 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7464'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7464'
 id: 7465 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '7465'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7465'
 id: 7466 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7466'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7466'
 id: 7467 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7467'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7467'
 id: 7468 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7468'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7468'
 id: 7469 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7469'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7469'
 id: 7470 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '7470'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7470'
 id: 7471 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '7471'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7471'
 id: 7472 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '7472'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7472'
 id: 7473 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '7473'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7473'
 id: 7474 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '7474'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7474'
 id: 7475 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '7475'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7475'
 id: 7476 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7476'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7476'
 id: 7477 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7477'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7477'
 id: 7478 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7478'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7478'
 id: 7479 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '7479'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7479'
 id: 7480 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7480'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7480'
 id: 7481 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7481'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7481'
 id: 7482 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7482'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7482'
 id: 7483 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7483'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7483'
 id: 7484 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7484'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7484'
 id: 7485 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7485'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7485'
 id: 7486 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7486'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7486'
 id: 7487 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7487'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7487'
 id: 7488 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '7488'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7488'
 id: 7489 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7489'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7489'
 id: 7490 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7490'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7490'
 id: 7491 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7491'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7491'
 id: 7492 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7492'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7492'
 id: 7493 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7493'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7493'
 id: 7494 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '7494'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7494'
 id: 7495 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '7495'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7495'
 id: 7496 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '7496'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7496'
 id: 7497 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '7497'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7497'
 id: 7498 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7498'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7498'
 id: 7499 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '7499'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7499'
 id: 7500 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7500'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7500'
 id: 7501 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '7501'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7501'
 id: 7502 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7502'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7502'
 id: 7503 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7503'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7503'
 id: 7504 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '7504'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7504'
 id: 7505 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '7505'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7505'
 id: 7506 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7506'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7506'
 id: 7507 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '7507'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7507'
 id: 7508 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '7508'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7508'
 id: 7509 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7509'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7509'
 id: 7510 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7510'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7510'
 id: 7511 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7511'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7511'
 id: 7512 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '7512'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7512'
 id: 7513 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '7513'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7513'
 id: 7514 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7514'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7514'
 id: 7515 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '7515'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7515'
 id: 7516 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '7516'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7516'
 id: 7517 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '7517'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7517'
 id: 7518 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7518'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7518'
 id: 7519 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7519'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7519'
 id: 7520 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7520'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7520'
 id: 7521 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7521'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7521'
 id: 7522 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '7522'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7522'
 id: 7523 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7523'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7523'
 id: 7524 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '7524'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7524'
 id: 7525 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7525'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7525'
 id: 7526 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '7526'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7526'
 id: 7527 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '7527'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7527'
 id: 7528 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '7528'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7528'
 id: 7529 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '7529'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7529'
 id: 7530 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7530'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7530'
 id: 7531 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7531'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7531'
 id: 7532 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '7532'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7532'
 id: 7533 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7533'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7533'
 id: 7534 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7534'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7534'
 id: 7535 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7535'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7535'
 id: 7536 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '7536'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7536'
 id: 7537 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '7537'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7537'
 id: 7538 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7538'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7538'
 id: 7539 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '7539'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7539'
 id: 7540 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '7540'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7540'
 id: 7541 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7541'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7541'
 id: 7542 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '7542'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7542'
 id: 7543 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '7543'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7543'
 id: 7544 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7544'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7544'
 id: 7545 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7545'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7545'
 id: 7546 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7546'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7546'
 id: 7547 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '7547'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7547'
 id: 7548 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7548'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7548'
 id: 7549 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7549'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7549'
 id: 7550 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '7550'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7550'
 id: 7551 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7551'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7551'
 id: 7552 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7552'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7552'
 id: 7553 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '7553'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7553'
 id: 7554 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7554'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7554'
 id: 7555 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '7555'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7555'
 id: 7556 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '7556'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7556'
 id: 7557 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '7557'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7557'
 id: 7558 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7558'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7558'
 id: 7559 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7559'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7559'
 id: 7560 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7560'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7560'
 id: 7561 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7561'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7561'
 id: 7562 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7562'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7562'
 id: 7563 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7563'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7563'
 id: 7564 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7564'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7564'
 id: 7565 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '7565'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7565'
 id: 7566 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '7566'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7566'
 id: 7567 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '7567'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7567'
 id: 7568 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7568'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7568'
 id: 7569 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '7569'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7569'
 id: 7570 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7570'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7570'
 id: 7571 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7571'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7571'
 id: 7572 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7572'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7572'
 id: 7573 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7573'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7573'
 id: 7574 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7574'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7574'
 id: 7575 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7575'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7575'
 id: 7576 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '7576'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7576'
 id: 7577 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7577'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7577'
 id: 7578 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7578'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7578'
 id: 7579 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7579'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7579'
 id: 7580 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '7580'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7580'
 id: 7581 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '7581'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7581'
 id: 7582 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '7582'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7582'
 id: 7583 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7583'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7583'
 id: 7584 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7584'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7584'
 id: 7585 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7585'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7585'
 id: 7586 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7586'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7586'
 id: 7587 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7587'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7587'
 id: 7588 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '7588'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7588'
 id: 7589 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '7589'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7589'
 id: 7590 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '7590'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7590'
 id: 7591 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7591'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7591'
 id: 7592 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '7592'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7592'
 id: 7593 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7593'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7593'
 id: 7594 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '7594'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7594'
 id: 7595 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7595'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7595'
 id: 7596 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '7596'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7596'
 id: 7597 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7597'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7597'
 id: 7598 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7598'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7598'
 id: 7599 // word: 66
UPDATE job_vacancies SET domain_id =  '66' where raw_id = '7599'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7599'
 id: 7600 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '7600'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7600'
 id: 7601 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7601'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7601'
 id: 7602 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7602'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7602'
 id: 7603 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7603'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7603'
 id: 7604 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7604'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7604'
 id: 7605 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7605'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7605'
 id: 7606 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '7606'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7606'
 id: 7607 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '7607'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7607'
 id: 7608 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '7608'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7608'
 id: 7609 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7609'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7609'
 id: 7610 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7610'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7610'
 id: 7611 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '7611'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7611'
 id: 7612 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7612'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7612'
 id: 7613 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7613'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7613'
 id: 7614 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '7614'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7614'
 id: 7615 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '7615'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7615'
 id: 7616 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7616'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7616'
 id: 7617 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '7617'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7617'
 id: 7618 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7618'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7618'
 id: 7619 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '7619'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7619'
 id: 7620 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7620'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7620'
 id: 7621 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7621'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7621'
 id: 7622 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '7622'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7622'
 id: 7623 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7623'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7623'
 id: 7624 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7624'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7624'
 id: 7625 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7625'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7625'
 id: 7626 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7626'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7626'
 id: 7627 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7627'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7627'
 id: 7628 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7628'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7628'
 id: 7629 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '7629'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7629'
 id: 7630 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '7630'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7630'
 id: 7631 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7631'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7631'
 id: 7632 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '7632'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7632'
 id: 7633 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7633'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7633'
 id: 7634 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7634'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7634'
 id: 7635 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7635'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7635'
 id: 7636 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '7636'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7636'
 id: 7637 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '7637'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7637'
 id: 7638 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7638'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7638'
 id: 7639 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '7639'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7639'
 id: 7640 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7640'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7640'
 id: 7641 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '7641'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7641'
 id: 7642 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '7642'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7642'
 id: 7643 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7643'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7643'
 id: 7644 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7644'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7644'
 id: 7645 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '7645'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7645'
 id: 7646 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '7646'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7646'
 id: 7647 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7647'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7647'
 id: 7648 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7648'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7648'
 id: 7649 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7649'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7649'
 id: 7650 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7650'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7650'
 id: 7651 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7651'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7651'
 id: 7652 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '7652'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7652'
 id: 7653 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '7653'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7653'
 id: 7654 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '7654'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7654'
 id: 7655 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7655'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7655'
 id: 7656 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7656'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7656'
 id: 7657 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7657'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7657'
 id: 7658 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7658'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7658'
 id: 7659 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7659'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7659'
 id: 7660 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '7660'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7660'
 id: 7661 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '7661'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7661'
 id: 7662 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7662'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7662'
 id: 7663 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7663'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7663'
 id: 7664 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7664'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7664'
 id: 7665 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7665'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7665'
 id: 7666 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '7666'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7666'
 id: 7667 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7667'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7667'
 id: 7668 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '7668'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7668'
 id: 7669 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7669'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7669'
 id: 7670 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '7670'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7670'
 id: 7671 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7671'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7671'
 id: 7672 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7672'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7672'
 id: 7673 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '7673'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7673'
 id: 7674 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7674'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7674'
 id: 7675 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7675'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7675'
 id: 7676 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7676'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7676'
 id: 7677 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7677'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7677'
 id: 7678 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7678'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7678'
 id: 7679 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7679'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7679'
 id: 7680 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7680'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7680'
 id: 7681 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7681'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7681'
 id: 7682 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7682'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7682'
 id: 7683 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '7683'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7683'
 id: 7684 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '7684'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7684'
 id: 7685 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7685'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7685'
 id: 7686 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '7686'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7686'
 id: 7687 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7687'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7687'
 id: 7688 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7688'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7688'
 id: 7689 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7689'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7689'
 id: 7690 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '7690'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7690'
 id: 7691 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7691'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7691'
 id: 7692 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7692'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7692'
 id: 7693 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '7693'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7693'
 id: 7694 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7694'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7694'

 id: 7695 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7695'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7695'
 id: 7696 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '7696'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7696'
 id: 7697 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7697'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7697'
 id: 7698 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7698'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7698'
 id: 7699 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '7699'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7699'
 id: 7700 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7700'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7700'
 id: 7701 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '7701'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7701'
 id: 7702 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '7702'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7702'
 id: 7703 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7703'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7703'
 id: 7704 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7704'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7704'
 id: 7705 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7705'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7705'
 id: 7706 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7706'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7706'
 id: 7707 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '7707'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7707'
 id: 7708 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7708'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7708'
 id: 7709 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7709'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7709'
 id: 7710 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '7710'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7710'
 id: 7711 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '7711'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7711'
 id: 7712 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '7712'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7712'
 id: 7713 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7713'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7713'
 id: 7714 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '7714'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7714'
 id: 7715 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '7715'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7715'
 id: 7716 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '7716'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7716'
 id: 7717 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '7717'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7717'
 id: 7718 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '7718'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7718'
 id: 7719 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7719'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7719'
 id: 7720 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '7720'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7720'
 id: 7721 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7721'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7721'
 id: 7722 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '7722'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7722'
 id: 7723 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7723'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7723'
 id: 7724 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7724'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7724'
 id: 7725 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7725'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7725'
 id: 7726 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '7726'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7726'
 id: 7727 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '7727'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7727'
 id: 7728 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '7728'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7728'
 id: 7729 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7729'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7729'
 id: 7730 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7730'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7730'
 id: 7731 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7731'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7731'
 id: 7732 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '7732'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7732'
 id: 7733 // word: 57
UPDATE job_vacancies SET domain_id =  '57' where raw_id = '7733'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7733'
 id: 7734 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '7734'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7734'
 id: 7735 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '7735'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7735'
 id: 7736 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '7736'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7736'
 id: 7737 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7737'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7737'
 id: 7738 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7738'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7738'
 id: 7739 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '7739'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7739'
 id: 7740 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7740'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7740'
 id: 7741 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7741'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7741'
 id: 7742 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7742'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7742'
 id: 7743 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7743'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7743'
 id: 7744 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7744'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7744'
 id: 7745 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7745'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7745'
 id: 7746 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '7746'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7746'

 id: 7747 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '7747'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7747'
 id: 7748 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7748'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7748'
 id: 7749 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '7749'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7749'
 id: 7750 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7750'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7750'
 id: 7751 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '7751'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7751'
 id: 7752 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7752'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7752'
 id: 7753 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7753'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7753'
 id: 7754 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7754'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7754'
 id: 7755 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '7755'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7755'
 id: 7756 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7756'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7756'
 id: 7757 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7757'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7757'
 id: 7758 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7758'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7758'
 id: 7759 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7759'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7759'
 id: 7760 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '7760'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7760'
 id: 7761 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7761'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7761'
 id: 7762 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7762'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7762'
 id: 7763 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7763'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7763'
 id: 7764 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '7764'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7764'
 id: 7765 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '7765'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7765'
 id: 7766 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7766'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7766'
 id: 7767 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '7767'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7767'
 id: 7768 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7768'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7768'
 id: 7769 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7769'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7769'
 id: 7770 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7770'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7770'
 id: 7771 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '7771'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7771'
 id: 7772 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '7772'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7772'
 id: 7773 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '7773'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7773'
 id: 7774 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7774'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7774'
 id: 7775 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7775'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7775'
 id: 7776 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7776'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7776'
 id: 7777 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '7777'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7777'
 id: 7778 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7778'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7778'
 id: 7779 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '7779'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7779'
 id: 7780 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '7780'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7780'
 id: 7781 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7781'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7781'
 id: 7782 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '7782'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7782'
 id: 7783 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7783'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7783'
 id: 7784 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '7784'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7784'
 id: 7785 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7785'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7785'
 id: 7786 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '7786'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7786'
 id: 7787 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7787'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7787'
 id: 7788 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '7788'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7788'
 id: 7789 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7789'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7789'
 id: 7790 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '7790'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7790'
 id: 7791 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7791'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7791'
 id: 7792 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7792'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7792'
 id: 7793 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7793'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7793'
 id: 7794 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7794'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7794'
 id: 7795 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7795'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7795'
 id: 7796 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7796'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7796'
 id: 7797 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '7797'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7797'
 id: 7798 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '7798'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7798'
 id: 7799 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '7799'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7799'
 id: 7800 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7800'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7800'
 id: 7801 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7801'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7801'
 id: 7802 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '7802'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7802'
 id: 7803 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '7803'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7803'
 id: 7804 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7804'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7804'
 id: 7805 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7805'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7805'
 id: 7806 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7806'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7806'
 id: 7807 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '7807'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7807'
 id: 7808 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '7808'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7808'
 id: 7809 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7809'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7809'
 id: 7810 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '7810'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7810'
 id: 7811 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7811'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7811'
 id: 7812 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '7812'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7812'
 id: 7813 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7813'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7813'
 id: 7814 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7814'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7814'
 id: 7815 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7815'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7815'
 id: 7816 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7816'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7816'
 id: 7817 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '7817'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7817'
 id: 7818 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '7818'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7818'
 id: 7819 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7819'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7819'
 id: 7820 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '7820'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7820'
 id: 7821 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7821'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7821'
 id: 7822 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7822'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7822'
 id: 7823 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7823'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7823'
 id: 7824 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7824'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7824'
 id: 7825 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '7825'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7825'
 id: 7826 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '7826'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7826'
 id: 7827 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7827'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7827'
 id: 7828 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7828'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7828'
 id: 7829 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '7829'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7829'
 id: 7830 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7830'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7830'
 id: 7831 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '7831'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7831'
 id: 7832 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '7832'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7832'
 id: 7833 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7833'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7833'
 id: 7834 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7834'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7834'
 id: 7835 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7835'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7835'
 id: 7836 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '7836'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7836'
 id: 7837 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '7837'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7837'
 id: 7838 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7838'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7838'
 id: 7839 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7839'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7839'
 id: 7840 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '7840'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7840'
 id: 7841 // word: 57
UPDATE job_vacancies SET domain_id =  '57' where raw_id = '7841'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7841'
 id: 7842 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7842'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7842'
 id: 7843 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7843'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7843'
 id: 7844 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7844'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7844'
 id: 7845 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7845'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7845'
 id: 7846 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7846'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7846'
 id: 7847 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '7847'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7847'
 id: 7848 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7848'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7848'
 id: 7849 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7849'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7849'
 id: 7850 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7850'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7850'
 id: 7851 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '7851'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7851'
 id: 7852 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7852'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7852'
 id: 7853 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7853'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7853'
 id: 7854 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '7854'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7854'
 id: 7855 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7855'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7855'
 id: 7856 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7856'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7856'
 id: 7857 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '7857'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7857'
 id: 7858 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7858'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7858'
 id: 7859 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7859'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7859'
 id: 7860 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7860'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7860'
 id: 7861 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '7861'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7861'
 id: 7862 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '7862'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7862'
 id: 7863 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '7863'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7863'
 id: 7864 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '7864'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7864'
 id: 7865 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7865'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7865'
 id: 7866 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7866'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7866'
 id: 7867 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '7867'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7867'
 id: 7868 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '7868'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7868'
 id: 7869 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '7869'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7869'
 id: 7870 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '7870'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7870'
 id: 7871 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7871'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7871'
 id: 7872 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '7872'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7872'
 id: 7873 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7873'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7873'
 id: 7874 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7874'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7874'
 id: 7875 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7875'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7875'
 id: 7876 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7876'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7876'
 id: 7877 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '7877'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7877'
 id: 7878 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7878'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7878'
 id: 7879 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7879'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7879'
 id: 7880 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7880'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7880'
 id: 7881 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7881'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7881'
 id: 7882 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7882'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7882'
 id: 7883 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7883'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7883'
 id: 7884 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7884'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7884'
 id: 7885 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7885'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7885'
 id: 7886 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7886'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7886'
 id: 7887 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7887'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7887'
 id: 7888 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '7888'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7888'
 id: 7889 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7889'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7889'
 id: 7890 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7890'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7890'
 id: 7891 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '7891'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7891'
 id: 7892 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7892'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7892'
 id: 7893 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7893'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7893'
 id: 7894 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '7894'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7894'
 id: 7895 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7895'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7895'
 id: 7896 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7896'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7896'
 id: 7897 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7897'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7897'
 id: 7898 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7898'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7898'
 id: 7899 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '7899'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7899'
 id: 7900 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '7900'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7900'
 id: 7901 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7901'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7901'
 id: 7902 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '7902'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7902'
 id: 7903 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7903'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7903'
 id: 7904 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '7904'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7904'
 id: 7905 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '7905'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7905'
 id: 7906 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7906'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7906'
 id: 7907 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '7907'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7907'
 id: 7908 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '7908'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7908'
 id: 7909 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7909'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7909'
 id: 7910 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7910'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7910'
 id: 7911 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '7911'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7911'
 id: 7912 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7912'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7912'
 id: 7913 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '7913'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7913'
 id: 7914 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7914'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7914'
 id: 7915 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7915'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7915'
 id: 7916 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '7916'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7916'
 id: 7917 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7917'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7917'
 id: 7918 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7918'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7918'
 id: 7919 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '7919'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7919'
 id: 7920 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7920'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7920'
 id: 7921 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7921'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7921'
 id: 7922 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '7922'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7922'
 id: 7923 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7923'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7923'
 id: 7924 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7924'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7924'
 id: 7925 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '7925'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7925'
 id: 7926 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '7926'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7926'
 id: 7927 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7927'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7927'
 id: 7928 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7928'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7928'
 id: 7929 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7929'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7929'
 id: 7930 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7930'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7930'
 id: 7931 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '7931'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7931'
 id: 7932 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7932'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7932'
 id: 7933 // word: 57
UPDATE job_vacancies SET domain_id =  '57' where raw_id = '7933'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7933'
 id: 7934 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7934'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7934'
 id: 7935 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7935'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7935'
 id: 7936 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7936'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7936'
 id: 7937 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '7937'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7937'
 id: 7938 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '7938'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7938'
 id: 7939 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7939'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7939'
 id: 7940 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '7940'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7940'
 id: 7941 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7941'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7941'
 id: 7942 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7942'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7942'
 id: 7943 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7943'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7943'
 id: 7944 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7944'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7944'
 id: 7945 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7945'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7945'
 id: 7946 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '7946'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7946'
 id: 7947 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7947'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7947'
 id: 7948 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '7948'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7948'
 id: 7949 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '7949'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7949'
 id: 7950 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7950'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7950'
 id: 7951 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '7951'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7951'
 id: 7952 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7952'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7952'
 id: 7953 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '7953'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7953'
 id: 7954 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '7954'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7954'
 id: 7955 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '7955'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7955'
 id: 7956 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '7956'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7956'
 id: 7957 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7957'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7957'
 id: 7958 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '7958'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7958'
 id: 7959 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '7959'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7959'
 id: 7960 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7960'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7960'
 id: 7961 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '7961'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7961'
 id: 7962 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7962'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7962'
 id: 7963 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7963'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7963'
 id: 7964 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7964'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7964'
 id: 7965 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7965'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7965'
 id: 7966 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '7966'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7966'
 id: 7967 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '7967'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7967'
 id: 7968 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '7968'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7968'
 id: 7969 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '7969'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7969'
 id: 7970 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7970'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7970'
 id: 7971 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '7971'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7971'
 id: 7972 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '7972'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7972'
 id: 7973 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7973'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7973'
 id: 7974 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '7974'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7974'
 id: 7975 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '7975'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7975'
 id: 7976 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7976'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7976'
 id: 7977 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '7977'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7977'
 id: 7978 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7978'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7978'
 id: 7979 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '7979'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7979'
 id: 7980 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7980'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7980'
 id: 7981 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '7981'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7981'
 id: 7982 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7982'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7982'
 id: 7983 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '7983'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7983'
 id: 7984 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7984'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7984'
 id: 7985 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7985'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7985'
 id: 7986 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '7986'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7986'
 id: 7987 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '7987'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7987'
 id: 7988 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '7988'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7988'
 id: 7989 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '7989'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7989'
 id: 7990 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '7990'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7990'
 id: 7991 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '7991'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7991'
 id: 7992 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7992'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7992'
 id: 7993 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '7993'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7993'
 id: 7994 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '7994'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7994'
 id: 7995 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7995'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7995'
 id: 7996 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '7996'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7996'
 id: 7997 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '7997'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7997'
 id: 7998 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '7998'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7998'
 id: 7999 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '7999'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '7999'
 id: 8000 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '8000'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8000'
 id: 8001 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8001'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8001'
 id: 8002 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8002'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8002'
 id: 8003 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8003'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8003'
 id: 8004 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '8004'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8004'
 id: 8005 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8005'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8005'
 id: 8006 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '8006'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8006'
 id: 8007 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '8007'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8007'
 id: 8008 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '8008'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8008'
 id: 8009 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '8009'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8009'
 id: 8010 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '8010'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8010'
 id: 8011 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '8011'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8011'
 id: 8012 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '8012'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8012'
 id: 8013 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '8013'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8013'
 id: 8014 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8014'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8014'
 id: 8015 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8015'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8015'
 id: 8016 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8016'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8016'
 id: 8017 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8017'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8017'
 id: 8018 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8018'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8018'
 id: 8019 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8019'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8019'
 id: 8020 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8020'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8020'
 id: 8021 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8021'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8021'
 id: 8022 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8022'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8022'
 id: 8023 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '8023'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8023'
 id: 8024 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '8024'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8024'
 id: 8025 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8025'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8025'
 id: 8026 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '8026'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8026'
 id: 8027 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '8027'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8027'
 id: 8028 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '8028'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8028'
 id: 8029 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8029'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8029'
 id: 8030 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '8030'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8030'
 id: 8031 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8031'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8031'
 id: 8032 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '8032'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8032'
 id: 8033 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '8033'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8033'
 id: 8034 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8034'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8034'
 id: 8035 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8035'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8035'
 id: 8036 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8036'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8036'
 id: 8037 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '8037'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8037'
 id: 8038 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8038'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8038'
 id: 8039 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '8039'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8039'
 id: 8040 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '8040'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8040'
 id: 8041 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '8041'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8041'
 id: 8042 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8042'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8042'
 id: 8043 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '8043'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8043'
 id: 8044 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '8044'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8044'
 id: 8045 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '8045'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8045'
 id: 8046 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8046'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8046'
 id: 8047 // word: 57
UPDATE job_vacancies SET domain_id =  '57' where raw_id = '8047'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8047'
 id: 8048 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8048'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8048'
 id: 8049 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '8049'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8049'
 id: 8050 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8050'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8050'
 id: 8051 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '8051'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8051'
 id: 8052 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '8052'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8052'
 id: 8053 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8053'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8053'
 id: 8054 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '8054'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8054'

 id: 8055 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8055'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8055'
 id: 8056 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8056'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8056'
 id: 8057 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '8057'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8057'
 id: 8058 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8058'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8058'
 id: 8059 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8059'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8059'
 id: 8060 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '8060'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8060'
 id: 8061 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8061'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8061'
 id: 8062 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '8062'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8062'
 id: 8063 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8063'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8063'
 id: 8064 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '8064'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8064'
 id: 8065 // word: 49
UPDATE job_vacancies SET domain_id =  '49' where raw_id = '8065'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8065'
 id: 8066 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '8066'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8066'
 id: 8067 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8067'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8067'
 id: 8068 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8068'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8068'
 id: 8069 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8069'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8069'
 id: 8070 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8070'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8070'
 id: 8071 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '8071'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8071'
 id: 8072 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '8072'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8072'
 id: 8073 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '8073'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8073'
 id: 8074 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8074'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8074'
 id: 8075 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8075'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8075'
 id: 8076 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '8076'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8076'
 id: 8077 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8077'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8077'
 id: 8078 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '8078'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8078'
 id: 8079 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '8079'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8079'
 id: 8080 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8080'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8080'
 id: 8081 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8081'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8081'
 id: 8082 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '8082'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8082'
 id: 8083 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8083'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8083'
 id: 8084 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8084'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8084'
 id: 8085 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '8085'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8085'
 id: 8086 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8086'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8086'
 id: 8087 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '8087'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8087'
 id: 8088 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8088'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8088'
 id: 8089 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '8089'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8089'
 id: 8090 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8090'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8090'
 id: 8091 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '8091'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8091'
 id: 8092 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '8092'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8092'
 id: 8093 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8093'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8093'
 id: 8094 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '8094'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8094'
 id: 8095 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8095'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8095'
 id: 8096 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '8096'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8096'
 id: 8097 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '8097'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8097'
 id: 8098 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '8098'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8098'
 id: 8099 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8099'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8099'
 id: 8100 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '8100'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8100'
 id: 8101 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '8101'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8101'
 id: 8102 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8102'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8102'
 id: 8103 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '8103'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8103'
 id: 8104 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8104'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8104'
 id: 8105 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '8105'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8105'
 id: 8106 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '8106'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8106'
 id: 8107 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8107'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8107'
 id: 8108 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '8108'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8108'
 id: 8109 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8109'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8109'
 id: 8110 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '8110'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8110'
 id: 8111 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8111'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8111'
 id: 8112 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8112'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8112'
 id: 8113 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8113'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8113'
 id: 8114 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8114'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8114'
 id: 8115 // word: 16
UPDATE job_vacancies SET domain_id =  '16' where raw_id = '8115'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8115'
 id: 8116 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8116'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8116'
 id: 8117 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8117'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8117'
 id: 8118 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '8118'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8118'
 id: 8119 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '8119'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8119'
 id: 8120 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '8120'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8120'
 id: 8121 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '8121'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8121'
 id: 8122 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '8122'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8122'
 id: 8123 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '8123'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8123'
 id: 8124 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '8124'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8124'
 id: 8125 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8125'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8125'
 id: 8126 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8126'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8126'
 id: 8127 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8127'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8127'
 id: 8128 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8128'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8128'
 id: 8129 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '8129'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8129'
 id: 8130 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8130'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8130'
 id: 8131 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '8131'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8131'
 id: 8132 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8132'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8132'
 id: 8133 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '8133'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8133'
 id: 8134 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '8134'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8134'
 id: 8135 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8135'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8135'
 id: 8136 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8136'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8136'
 id: 8137 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '8137'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8137'
 id: 8138 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8138'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8138'
 id: 8139 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8139'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8139'
 id: 8140 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '8140'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8140'
 id: 8141 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '8141'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8141'
 id: 8142 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8142'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8142'
 id: 8143 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '8143'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8143'
 id: 8144 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8144'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8144'
 id: 8145 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8145'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8145'
 id: 8146 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8146'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8146'
 id: 8147 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '8147'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8147'
 id: 8148 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '8148'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8148'
 id: 8149 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8149'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8149'
 id: 8150 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '8150'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8150'
 id: 8151 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8151'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8151'
 id: 8152 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8152'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8152'
 id: 8153 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '8153'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8153'
 id: 8154 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8154'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8154'
 id: 8155 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '8155'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8155'
 id: 8156 // word: 57
UPDATE job_vacancies SET domain_id =  '57' where raw_id = '8156'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8156'
 id: 8157 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8157'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8157'

 id: 8158 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '8158'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8158'
 id: 8159 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8159'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8159'
 id: 8160 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '8160'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8160'
 id: 8161 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8161'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8161'
 id: 8162 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '8162'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8162'
 id: 8163 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8163'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8163'
 id: 8164 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8164'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8164'
 id: 8165 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '8165'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8165'
 id: 8166 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8166'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8166'
 id: 8167 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8167'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8167'
 id: 8168 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8168'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8168'
 id: 8169 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8169'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8169'
 id: 8170 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '8170'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8170'
 id: 8171 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8171'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8171'
 id: 8172 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8172'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8172'
 id: 8173 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '8173'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8173'
 id: 8174 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8174'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8174'
 id: 8175 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '8175'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8175'
 id: 8176 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8176'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8176'
 id: 8177 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '8177'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8177'
 id: 8178 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8178'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8178'
 id: 8179 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8179'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8179'
 id: 8180 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '8180'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8180'
 id: 8181 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '8181'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8181'
 id: 8182 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '8182'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8182'
 id: 8183 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '8183'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8183'
 id: 8184 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8184'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8184'
 id: 8185 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8185'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8185'
 id: 8186 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8186'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8186'
 id: 8187 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8187'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8187'
 id: 8188 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8188'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8188'
 id: 8189 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8189'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8189'
 id: 8190 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8190'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8190'
 id: 8191 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '8191'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8191'
 id: 8192 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '8192'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8192'
 id: 8193 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8193'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8193'
 id: 8194 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8194'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8194'
 id: 8195 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8195'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8195'
 id: 8196 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8196'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8196'
 id: 8197 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '8197'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8197'
 id: 8198 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '8198'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8198'
 id: 8199 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '8199'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8199'
 id: 8200 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8200'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8200'
 id: 8201 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8201'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8201'
 id: 8202 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8202'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8202'
 id: 8203 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8203'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8203'
 id: 8204 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8204'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8204'
 id: 8205 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8205'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8205'
 id: 8206 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8206'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8206'
 id: 8207 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8207'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8207'
 id: 8208 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '8208'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8208'
 id: 8209 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '8209'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8209'
 id: 8210 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '8210'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8210'
 id: 8211 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '8211'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8211'
 id: 8212 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8212'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8212'
 id: 8213 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '8213'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8213'
 id: 8214 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8214'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8214'
 id: 8215 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8215'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8215'
 id: 8216 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '8216'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8216'
 id: 8217 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '8217'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8217'
 id: 8218 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8218'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8218'
 id: 8219 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '8219'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8219'
 id: 8220 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8220'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8220'
 id: 8221 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '8221'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8221'
 id: 8222 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '8222'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8222'
 id: 8223 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '8223'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8223'
 id: 8224 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '8224'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8224'
 id: 8225 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8225'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8225'
 id: 8226 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '8226'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8226'
 id: 8227 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8227'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8227'
 id: 8228 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8228'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8228'
 id: 8229 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '8229'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8229'
 id: 8230 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8230'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8230'
 id: 8231 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8231'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8231'
 id: 8232 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8232'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8232'
 id: 8233 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8233'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8233'
 id: 8234 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8234'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8234'
 id: 8235 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8235'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8235'
 id: 8236 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '8236'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8236'
 id: 8237 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '8237'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8237'
 id: 8238 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '8238'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8238'
 id: 8239 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8239'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8239'
 id: 8240 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8240'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8240'
 id: 8241 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '8241'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8241'
 id: 8242 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '8242'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8242'
 id: 8243 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8243'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8243'
 id: 8244 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '8244'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8244'
 id: 8245 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8245'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8245'
 id: 8246 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8246'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8246'
 id: 8247 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8247'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8247'
 id: 8248 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '8248'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8248'
 id: 8249 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8249'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8249'
 id: 8250 // word: 57
UPDATE job_vacancies SET domain_id =  '57' where raw_id = '8250'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8250'
 id: 8251 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '8251'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8251'
 id: 8252 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8252'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8252'
 id: 8253 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '8253'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8253'
 id: 8254 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '8254'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8254'
 id: 8255 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8255'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8255'
 id: 8256 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8256'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8256'
 id: 8257 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8257'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8257'
 id: 8258 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8258'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8258'

 id: 8259 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8259'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8259'
 id: 8260 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '8260'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8260'
 id: 8261 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8261'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8261'
 id: 8262 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '8262'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8262'
 id: 8263 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '8263'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8263'
 id: 8264 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8264'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8264'
 id: 8265 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8265'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8265'
 id: 8266 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '8266'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8266'
 id: 8267 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8267'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8267'
 id: 8268 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '8268'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8268'
 id: 8269 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '8269'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8269'
 id: 8270 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '8270'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8270'
 id: 8271 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '8271'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8271'
 id: 8272 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '8272'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8272'
 id: 8273 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8273'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8273'
 id: 8274 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '8274'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8274'
 id: 8275 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8275'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8275'
 id: 8276 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8276'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8276'
 id: 8277 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8277'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8277'
 id: 8278 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8278'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8278'
 id: 8279 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '8279'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8279'
 id: 8280 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8280'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8280'
 id: 8281 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8281'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8281'
 id: 8282 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '8282'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8282'
 id: 8283 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '8283'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8283'
 id: 8284 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '8284'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8284'
 id: 8285 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '8285'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8285'
 id: 8286 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8286'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8286'
 id: 8287 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8287'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8287'
 id: 8288 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '8288'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8288'
 id: 8289 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8289'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8289'
 id: 8290 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8290'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8290'
 id: 8291 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '8291'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8291'
 id: 8292 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8292'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8292'
 id: 8293 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8293'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8293'
 id: 8294 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8294'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8294'
 id: 8295 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '8295'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8295'
 id: 8296 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8296'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8296'
 id: 8297 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '8297'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8297'
 id: 8298 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '8298'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8298'
 id: 8299 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '8299'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8299'
 id: 8300 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '8300'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8300'
 id: 8301 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '8301'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8301'
 id: 8302 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8302'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8302'
 id: 8303 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '8303'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8303'
 id: 8304 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8304'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8304'
 id: 8305 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8305'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8305'
 id: 8306 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '8306'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8306'
 id: 8307 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8307'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8307'
 id: 8308 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '8308'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8308'
 id: 8309 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8309'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8309'
 id: 8310 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '8310'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8310'
 id: 8311 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '8311'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8311'
 id: 8312 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8312'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8312'
 id: 8313 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '8313'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8313'
 id: 8314 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '8314'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8314'
 id: 8315 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '8315'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8315'
 id: 8316 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8316'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8316'
 id: 8317 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8317'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8317'
 id: 8318 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8318'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8318'
 id: 8319 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '8319'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8319'
 id: 8320 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8320'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8320'
 id: 8321 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '8321'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8321'
 id: 8322 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '8322'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8322'
 id: 8323 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '8323'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8323'
 id: 8324 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8324'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8324'
 id: 8325 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8325'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8325'
 id: 8326 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8326'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8326'
 id: 8327 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '8327'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8327'
 id: 8328 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8328'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8328'
 id: 8329 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8329'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8329'
 id: 8330 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8330'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8330'
 id: 8331 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8331'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8331'
 id: 8332 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8332'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8332'
 id: 8333 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '8333'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8333'
 id: 8334 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '8334'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8334'
 id: 8335 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '8335'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8335'
 id: 8336 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8336'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8336'
 id: 8337 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '8337'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8337'
 id: 8338 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '8338'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8338'
 id: 8339 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8339'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8339'
 id: 8340 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8340'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8340'
 id: 8341 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '8341'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8341'
 id: 8342 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8342'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8342'
 id: 8343 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8343'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8343'
 id: 8344 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8344'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8344'
 id: 8345 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '8345'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8345'
 id: 8346 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '8346'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8346'
 id: 8347 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8347'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8347'
 id: 8348 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8348'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8348'
 id: 8349 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '8349'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8349'
 id: 8350 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '8350'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8350'
 id: 8351 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8351'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8351'
 id: 8352 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8352'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8352'
 id: 8353 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8353'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8353'
 id: 8354 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '8354'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8354'
 id: 8355 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8355'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8355'
 id: 8356 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '8356'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8356'
 id: 8357 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8357'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8357'
 id: 8358 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8358'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8358'
 id: 8359 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8359'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8359'
 id: 8360 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8360'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8360'

 id: 8361 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '8361'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8361'
 id: 8362 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8362'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8362'
 id: 8363 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '8363'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8363'
 id: 8364 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8364'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8364'
 id: 8365 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8365'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8365'
 id: 8366 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '8366'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8366'
 id: 8367 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '8367'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8367'
 id: 8368 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '8368'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8368'
 id: 8369 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '8369'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8369'
 id: 8370 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '8370'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8370'
 id: 8371 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '8371'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8371'
 id: 8372 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '8372'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8372'
 id: 8373 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '8373'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8373'
 id: 8374 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8374'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8374'
 id: 8375 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '8375'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8375'
 id: 8376 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '8376'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8376'
 id: 8377 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8377'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8377'
 id: 8378 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '8378'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8378'
 id: 8379 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '8379'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8379'
 id: 8380 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '8380'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8380'
 id: 8381 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8381'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8381'
 id: 8382 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '8382'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8382'
 id: 8383 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '8383'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8383'
 id: 8384 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8384'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8384'
 id: 8385 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8385'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8385'
 id: 8386 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '8386'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8386'
 id: 8387 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8387'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8387'
 id: 8388 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '8388'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8388'
 id: 8389 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8389'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8389'
 id: 8390 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '8390'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8390'
 id: 8391 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '8391'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8391'
 id: 8392 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '8392'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8392'
 id: 8393 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '8393'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8393'
 id: 8394 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8394'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8394'
 id: 8395 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '8395'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8395'
 id: 8396 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '8396'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8396'
 id: 8397 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8397'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8397'
 id: 8398 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8398'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8398'
 id: 8399 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '8399'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8399'
 id: 8400 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8400'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8400'
 id: 8401 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8401'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8401'
 id: 8402 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '8402'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8402'
 id: 8403 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8403'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8403'
 id: 8404 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8404'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8404'
 id: 8405 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8405'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8405'
 id: 8406 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8406'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8406'
 id: 8407 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '8407'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8407'
 id: 8408 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '8408'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8408'
 id: 8409 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '8409'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8409'
 id: 8410 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8410'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8410'
 id: 8411 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '8411'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8411'

 id: 8412 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8412'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8412'
 id: 8413 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8413'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8413'
 id: 8414 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '8414'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8414'
 id: 8415 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '8415'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8415'
 id: 8416 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '8416'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8416'
 id: 8417 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8417'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8417'
 id: 8418 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '8418'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8418'
 id: 8419 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '8419'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8419'
 id: 8420 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '8420'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8420'
 id: 8421 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8421'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8421'
 id: 8422 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '8422'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8422'
 id: 8423 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '8423'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8423'
 id: 8424 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '8424'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8424'
 id: 8425 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '8425'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8425'
 id: 8426 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8426'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8426'
 id: 8427 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '8427'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8427'
 id: 8428 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8428'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8428'
 id: 8429 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '8429'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8429'
 id: 8430 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '8430'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8430'
 id: 8431 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '8431'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8431'
 id: 8432 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8432'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8432'
 id: 8433 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8433'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8433'
 id: 8434 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8434'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8434'
 id: 8435 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '8435'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8435'
 id: 8436 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '8436'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8436'
 id: 8437 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8437'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8437'
 id: 8438 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '8438'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8438'
 id: 8439 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '8439'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8439'
 id: 8440 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '8440'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8440'
 id: 8441 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '8441'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8441'
 id: 8442 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '8442'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8442'
 id: 8443 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '8443'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8443'
 id: 8444 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8444'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8444'
 id: 8445 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8445'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8445'
 id: 8446 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '8446'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8446'
 id: 8447 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '8447'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8447'
 id: 8448 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '8448'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8448'
 id: 8449 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8449'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8449'
 id: 8450 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8450'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8450'
 id: 8451 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8451'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8451'
 id: 8452 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8452'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8452'
 id: 8453 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '8453'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8453'
 id: 8454 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8454'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8454'
 id: 8455 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '8455'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8455'
 id: 8456 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '8456'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8456'
 id: 8457 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8457'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8457'
 id: 8458 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8458'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8458'
 id: 8459 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8459'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8459'
 id: 8460 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8460'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8460'
 id: 8461 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '8461'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8461'
 id: 8462 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8462'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8462'

 id: 8463 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8463'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8463'
 id: 8464 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '8464'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8464'
 id: 8465 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '8465'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8465'
 id: 8466 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '8466'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8466'
 id: 8467 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8467'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8467'
 id: 8468 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8468'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8468'
 id: 8469 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8469'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8469'
 id: 8470 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '8470'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8470'
 id: 8471 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '8471'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8471'
 id: 8472 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8472'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8472'
 id: 8473 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '8473'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8473'
 id: 8474 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '8474'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8474'
 id: 8475 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8475'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8475'
 id: 8476 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '8476'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8476'
 id: 8477 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '8477'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8477'
 id: 8478 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8478'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8478'
 id: 8479 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '8479'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8479'
 id: 8480 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '8480'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8480'
 id: 8481 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8481'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8481'
 id: 8482 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '8482'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8482'
 id: 8483 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '8483'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8483'
 id: 8484 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '8484'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8484'
 id: 8485 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '8485'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8485'
 id: 8486 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8486'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8486'
 id: 8487 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '8487'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8487'
 id: 8488 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '8488'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8488'
 id: 8489 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '8489'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8489'
 id: 8490 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '8490'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8490'
 id: 8491 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '8491'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8491'
 id: 8492 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8492'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8492'
 id: 8493 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '8493'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8493'
 id: 8494 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8494'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8494'
 id: 8495 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '8495'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8495'
 id: 8496 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '8496'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8496'
 id: 8497 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '8497'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8497'
 id: 8498 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8498'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8498'
 id: 8499 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '8499'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8499'
 id: 8500 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8500'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8500'
 id: 8501 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '8501'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8501'
 id: 8502 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '8502'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8502'
 id: 8503 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8503'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8503'
 id: 8504 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8504'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8504'
 id: 8505 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '8505'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8505'
 id: 8506 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8506'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8506'
 id: 8507 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8507'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8507'
 id: 8508 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '8508'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8508'
 id: 8509 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '8509'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8509'
 id: 8510 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '8510'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8510'
 id: 8511 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '8511'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8511'
 id: 8512 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8512'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8512'
 id: 8513 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '8513'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8513'
 id: 8514 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8514'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8514'
 id: 8515 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8515'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8515'

 id: 8516 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '8516'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8516'
 id: 8517 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8517'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8517'
 id: 8518 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '8518'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8518'
 id: 8519 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8519'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8519'
 id: 8520 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8520'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8520'
 id: 8521 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '8521'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8521'
 id: 8522 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '8522'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8522'
 id: 8523 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '8523'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8523'
 id: 8524 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '8524'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8524'
 id: 8525 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8525'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8525'
 id: 8526 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8526'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8526'
 id: 8527 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8527'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8527'
 id: 8528 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8528'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8528'
 id: 8529 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '8529'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8529'
 id: 8530 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '8530'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8530'
 id: 8531 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '8531'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8531'
 id: 8532 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '8532'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8532'
 id: 8533 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '8533'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8533'
 id: 8534 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8534'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8534'
 id: 8535 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8535'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8535'
 id: 8536 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8536'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8536'
 id: 8537 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '8537'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8537'
 id: 8538 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '8538'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8538'
 id: 8539 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8539'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8539'
 id: 8540 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8540'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8540'
 id: 8541 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '8541'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8541'
 id: 8542 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '8542'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8542'
 id: 8543 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '8543'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8543'
 id: 8544 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '8544'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8544'
 id: 8545 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '8545'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8545'
 id: 8546 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '8546'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8546'
 id: 8547 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '8547'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8547'
 id: 8548 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '8548'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8548'
 id: 8549 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '8549'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8549'
 id: 8550 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '8550'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8550'
 id: 8551 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8551'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8551'
 id: 8552 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '8552'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8552'
 id: 8553 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '8553'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8553'
 id: 8554 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '8554'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8554'
 id: 8555 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '8555'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8555'
 id: 8556 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8556'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8556'
 id: 8557 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8557'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8557'
 id: 8558 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8558'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8558'
 id: 8559 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8559'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8559'
 id: 8560 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '8560'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8560'
 id: 8561 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '8561'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8561'
 id: 8562 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8562'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8562'
 id: 8563 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '8563'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8563'
 id: 8564 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8564'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8564'
 id: 8565 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8565'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8565'
 id: 8566 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8566'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8566'
 id: 8567 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '8567'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8567'
 id: 8568 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '8568'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8568'

 id: 8569 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '8569'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8569'
 id: 8570 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8570'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8570'
 id: 8571 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '8571'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8571'
 id: 8572 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '8572'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8572'
 id: 8573 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '8573'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8573'
 id: 8574 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8574'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8574'
 id: 8575 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '8575'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8575'
 id: 8576 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '8576'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8576'
 id: 8577 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '8577'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8577'
 id: 8578 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '8578'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8578'
 id: 8579 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8579'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8579'
 id: 8580 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8580'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8580'
 id: 8581 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '8581'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8581'
 id: 8582 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8582'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8582'
 id: 8583 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8583'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8583'
 id: 8584 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8584'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8584'
 id: 8585 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8585'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8585'
 id: 8586 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '8586'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8586'
 id: 8587 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '8587'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8587'
 id: 8588 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '8588'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8588'
 id: 8589 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '8589'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8589'
 id: 8590 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '8590'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8590'
 id: 8591 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8591'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8591'
 id: 8592 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '8592'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8592'
 id: 8593 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8593'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8593'
 id: 8594 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8594'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8594'
 id: 8595 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '8595'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8595'
 id: 8596 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8596'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8596'
 id: 8597 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8597'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8597'
 id: 8598 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8598'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8598'
 id: 8599 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8599'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8599'
 id: 8600 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8600'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8600'
 id: 8601 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8601'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8601'
 id: 8602 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8602'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8602'
 id: 8603 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8603'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8603'
 id: 8604 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8604'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8604'
 id: 8605 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '8605'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8605'
 id: 8606 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '8606'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8606'
 id: 8607 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8607'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8607'
 id: 8608 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '8608'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8608'
 id: 8609 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '8609'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8609'
 id: 8610 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8610'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8610'
 id: 8611 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8611'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8611'
 id: 8612 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '8612'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8612'
 id: 8613 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8613'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8613'
 id: 8614 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '8614'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8614'
 id: 8615 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '8615'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8615'
 id: 8616 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '8616'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8616'
 id: 8617 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8617'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8617'
 id: 8618 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8618'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8618'
 id: 8619 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '8619'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8619'
 id: 8620 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8620'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8620'
 id: 8621 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8621'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8621'
 id: 8622 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '8622'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8622'
 id: 8623 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8623'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8623'
 id: 8624 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8624'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8624'
 id: 8625 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8625'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8625'
 id: 8626 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '8626'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8626'
 id: 8627 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '8627'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8627'
 id: 8628 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '8628'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8628'
 id: 8629 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '8629'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8629'
 id: 8630 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '8630'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8630'
 id: 8631 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '8631'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8631'
 id: 8632 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '8632'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8632'
 id: 8633 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8633'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8633'
 id: 8634 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '8634'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8634'
 id: 8635 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '8635'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8635'
 id: 8636 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8636'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8636'
 id: 8637 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8637'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8637'
 id: 8638 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '8638'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8638'
 id: 8639 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '8639'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8639'
 id: 8640 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8640'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8640'
 id: 8641 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '8641'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8641'
 id: 8642 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '8642'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8642'
 id: 8643 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '8643'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8643'
 id: 8644 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8644'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8644'
 id: 8645 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '8645'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8645'
 id: 8646 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8646'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8646'
 id: 8647 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '8647'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8647'
 id: 8648 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8648'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8648'
 id: 8649 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8649'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8649'
 id: 8650 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '8650'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8650'
 id: 8651 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '8651'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8651'
 id: 8652 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8652'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8652'
 id: 8653 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8653'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8653'
 id: 8654 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '8654'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8654'
 id: 8655 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8655'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8655'
 id: 8656 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '8656'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8656'
 id: 8657 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '8657'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8657'
 id: 8658 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '8658'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8658'
 id: 8659 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8659'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8659'
 id: 8660 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '8660'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8660'
 id: 8661 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8661'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8661'
 id: 8662 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8662'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8662'
 id: 8663 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '8663'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8663'
 id: 8664 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8664'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8664'
 id: 8665 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8665'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8665'
 id: 8666 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8666'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8666'
 id: 8667 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8667'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8667'
 id: 8668 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '8668'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8668'
 id: 8669 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8669'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8669'
 id: 8670 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '8670'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8670'
 id: 8671 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '8671'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8671'

 id: 8672 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '8672'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8672'
 id: 8673 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8673'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8673'
 id: 8674 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '8674'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8674'
 id: 8675 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8675'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8675'
 id: 8676 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8676'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8676'
 id: 8677 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8677'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8677'
 id: 8678 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '8678'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8678'
 id: 8679 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '8679'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8679'
 id: 8680 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '8680'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8680'
 id: 8681 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8681'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8681'
 id: 8682 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8682'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8682'
 id: 8683 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8683'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8683'
 id: 8684 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8684'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8684'
 id: 8685 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '8685'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8685'
 id: 8686 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '8686'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8686'
 id: 8687 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8687'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8687'
 id: 8688 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '8688'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8688'
 id: 8689 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8689'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8689'
 id: 8690 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8690'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8690'
 id: 8691 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '8691'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8691'
 id: 8692 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '8692'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8692'
 id: 8693 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8693'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8693'
 id: 8694 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '8694'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8694'
 id: 8695 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8695'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8695'
 id: 8696 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '8696'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8696'
 id: 8697 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8697'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8697'
 id: 8698 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '8698'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8698'
 id: 8699 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8699'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8699'
 id: 8700 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8700'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8700'
 id: 8701 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8701'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8701'
 id: 8702 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '8702'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8702'
 id: 8703 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '8703'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8703'
 id: 8704 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8704'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8704'
 id: 8705 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8705'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8705'
 id: 8706 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8706'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8706'
 id: 8707 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '8707'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8707'
 id: 8708 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '8708'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8708'
 id: 8709 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '8709'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8709'
 id: 8710 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '8710'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8710'
 id: 8711 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8711'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8711'
 id: 8712 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8712'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8712'
 id: 8713 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8713'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8713'
 id: 8714 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8714'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8714'
 id: 8715 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8715'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8715'
 id: 8716 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '8716'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8716'
 id: 8717 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8717'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8717'
 id: 8718 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8718'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8718'
 id: 8719 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '8719'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8719'
 id: 8720 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8720'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8720'
 id: 8721 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8721'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8721'
 id: 8722 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '8722'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8722'
 id: 8723 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8723'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8723'
 id: 8724 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '8724'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8724'
 id: 8725 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '8725'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8725'
 id: 8726 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8726'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8726'
 id: 8727 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '8727'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8727'
 id: 8728 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '8728'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8728'
 id: 8729 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '8729'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8729'
 id: 8730 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8730'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8730'
 id: 8731 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8731'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8731'
 id: 8732 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8732'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8732'
 id: 8733 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '8733'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8733'
 id: 8734 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '8734'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8734'
 id: 8735 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '8735'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8735'
 id: 8736 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '8736'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8736'
 id: 8737 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8737'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8737'
 id: 8738 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '8738'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8738'
 id: 8739 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8739'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8739'
 id: 8740 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8740'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8740'
 id: 8741 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '8741'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8741'
 id: 8742 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '8742'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8742'
 id: 8743 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '8743'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8743'
 id: 8744 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8744'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8744'
 id: 8745 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8745'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8745'
 id: 8746 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8746'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8746'
 id: 8747 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8747'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8747'
 id: 8748 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8748'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8748'
 id: 8749 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8749'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8749'
 id: 8750 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '8750'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8750'
 id: 8751 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '8751'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8751'
 id: 8752 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8752'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8752'
 id: 8753 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '8753'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8753'
 id: 8754 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '8754'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8754'
 id: 8755 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8755'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8755'
 id: 8756 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8756'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8756'
 id: 8757 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8757'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8757'
 id: 8758 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8758'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8758'
 id: 8759 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8759'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8759'
 id: 8760 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '8760'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8760'
 id: 8761 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8761'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8761'
 id: 8762 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '8762'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8762'
 id: 8763 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8763'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8763'
 id: 8764 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8764'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8764'
 id: 8765 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8765'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8765'
 id: 8766 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8766'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8766'
 id: 8767 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8767'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8767'
 id: 8768 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8768'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8768'
 id: 8769 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '8769'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8769'
 id: 8770 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '8770'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8770'
 id: 8771 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8771'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8771'
 id: 8772 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '8772'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8772'
 id: 8773 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '8773'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8773'

 id: 8774 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '8774'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8774'
 id: 8775 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '8775'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8775'
 id: 8776 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8776'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8776'
 id: 8777 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8777'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8777'
 id: 8778 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8778'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8778'
 id: 8779 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8779'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8779'
 id: 8780 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '8780'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8780'
 id: 8781 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '8781'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8781'
 id: 8782 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '8782'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8782'
 id: 8783 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8783'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8783'
 id: 8784 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '8784'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8784'
 id: 8785 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '8785'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8785'
 id: 8786 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8786'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8786'
 id: 8787 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '8787'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8787'
 id: 8788 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '8788'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8788'
 id: 8789 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8789'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8789'
 id: 8790 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '8790'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8790'
 id: 8791 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8791'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8791'
 id: 8792 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8792'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8792'
 id: 8793 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8793'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8793'
 id: 8794 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '8794'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8794'
 id: 8795 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8795'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8795'
 id: 8796 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8796'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8796'
 id: 8797 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8797'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8797'
 id: 8798 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '8798'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8798'
 id: 8799 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '8799'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8799'
 id: 8800 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8800'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8800'
 id: 8801 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '8801'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8801'
 id: 8802 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '8802'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8802'
 id: 8803 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '8803'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8803'
 id: 8804 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8804'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8804'
 id: 8805 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '8805'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8805'
 id: 8806 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8806'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8806'
 id: 8807 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '8807'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8807'
 id: 8808 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '8808'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8808'
 id: 8809 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '8809'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8809'
 id: 8810 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8810'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8810'
 id: 8811 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8811'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8811'
 id: 8812 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8812'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8812'
 id: 8813 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8813'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8813'
 id: 8814 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '8814'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8814'
 id: 8815 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '8815'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8815'
 id: 8816 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '8816'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8816'
 id: 8817 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '8817'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8817'
 id: 8818 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '8818'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8818'
 id: 8819 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8819'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8819'
 id: 8820 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '8820'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8820'
 id: 8821 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8821'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8821'
 id: 8822 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8822'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8822'
 id: 8823 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8823'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8823'
 id: 8824 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8824'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8824'

 id: 8825 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '8825'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8825'
 id: 8826 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '8826'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8826'
 id: 8827 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '8827'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8827'
 id: 8828 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '8828'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8828'
 id: 8829 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8829'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8829'
 id: 8830 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '8830'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8830'
 id: 8831 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8831'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8831'
 id: 8832 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8832'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8832'
 id: 8833 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8833'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8833'
 id: 8834 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '8834'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8834'
 id: 8835 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8835'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8835'
 id: 8836 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8836'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8836'
 id: 8837 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8837'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8837'
 id: 8838 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '8838'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8838'
 id: 8839 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8839'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8839'
 id: 8840 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '8840'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8840'
 id: 8841 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '8841'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8841'
 id: 8842 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '8842'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8842'
 id: 8843 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '8843'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8843'
 id: 8844 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '8844'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8844'
 id: 8845 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '8845'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8845'
 id: 8846 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '8846'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8846'
 id: 8847 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '8847'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8847'
 id: 8848 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '8848'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8848'
 id: 8849 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8849'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8849'
 id: 8850 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '8850'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8850'
 id: 8851 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8851'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8851'
 id: 8852 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '8852'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8852'
 id: 8853 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '8853'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8853'
 id: 8854 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '8854'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8854'
 id: 8855 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '8855'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8855'
 id: 8856 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '8856'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8856'
 id: 8857 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '8857'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8857'
 id: 8858 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '8858'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8858'
 id: 8859 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8859'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8859'
 id: 8860 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8860'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8860'
 id: 8861 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8861'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8861'
 id: 8862 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '8862'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8862'
 id: 8863 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8863'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8863'
 id: 8864 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8864'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8864'
 id: 8865 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '8865'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8865'
 id: 8866 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8866'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8866'
 id: 8867 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '8867'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8867'
 id: 8868 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '8868'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8868'
 id: 8869 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8869'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8869'
 id: 8870 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '8870'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8870'
 id: 8871 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8871'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8871'
 id: 8872 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8872'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8872'
 id: 8873 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8873'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8873'
 id: 8874 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8874'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8874'
 id: 8875 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '8875'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8875'
 id: 8876 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8876'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8876'
 id: 8877 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8877'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8877'
 id: 8878 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '8878'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8878'
 id: 8879 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '8879'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8879'
 id: 8880 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8880'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8880'
 id: 8881 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '8881'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8881'
 id: 8882 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8882'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8882'
 id: 8883 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '8883'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8883'
 id: 8884 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8884'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8884'
 id: 8885 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8885'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8885'
 id: 8886 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8886'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8886'
 id: 8887 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8887'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8887'
 id: 8888 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '8888'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8888'
 id: 8889 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8889'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8889'
 id: 8890 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8890'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8890'
 id: 8891 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '8891'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8891'
 id: 8892 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8892'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8892'
 id: 8893 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8893'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8893'
 id: 8894 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8894'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8894'
 id: 8895 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '8895'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8895'
 id: 8896 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8896'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8896'
 id: 8897 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8897'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8897'
 id: 8898 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8898'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8898'
 id: 8899 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '8899'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8899'
 id: 8900 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8900'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8900'
 id: 8901 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8901'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8901'
 id: 8902 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '8902'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8902'
 id: 8903 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '8903'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8903'
 id: 8904 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '8904'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8904'
 id: 8905 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8905'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8905'
 id: 8906 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '8906'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8906'
 id: 8907 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8907'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8907'
 id: 8908 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '8908'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8908'
 id: 8909 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8909'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8909'
 id: 8910 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8910'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8910'
 id: 8911 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '8911'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8911'
 id: 8912 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '8912'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8912'
 id: 8913 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8913'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8913'
 id: 8914 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8914'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8914'
 id: 8915 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '8915'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8915'
 id: 8916 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8916'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8916'
 id: 8917 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '8917'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8917'
 id: 8918 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8918'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8918'
 id: 8919 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '8919'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8919'
 id: 8920 // word: 47
UPDATE job_vacancies SET domain_id =  '47' where raw_id = '8920'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8920'
 id: 8921 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8921'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8921'
 id: 8922 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8922'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8922'
 id: 8923 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8923'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8923'
 id: 8924 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '8924'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8924'
 id: 8925 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '8925'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8925'
 id: 8926 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '8926'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8926'
 id: 8927 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '8927'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8927'
 id: 8928 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '8928'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8928'

 id: 8929 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8929'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8929'
 id: 8930 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '8930'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8930'
 id: 8931 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '8931'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8931'
 id: 8932 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8932'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8932'
 id: 8933 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '8933'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8933'
 id: 8934 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '8934'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8934'
 id: 8935 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '8935'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8935'
 id: 8936 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8936'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8936'
 id: 8937 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '8937'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8937'
 id: 8938 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8938'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8938'
 id: 8939 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8939'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8939'
 id: 8940 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8940'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8940'
 id: 8941 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '8941'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8941'
 id: 8942 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '8942'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8942'
 id: 8943 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '8943'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8943'
 id: 8944 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8944'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8944'
 id: 8945 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '8945'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8945'
 id: 8946 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '8946'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8946'
 id: 8947 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8947'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8947'
 id: 8948 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '8948'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8948'
 id: 8949 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '8949'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8949'
 id: 8950 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '8950'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8950'
 id: 8951 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '8951'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8951'
 id: 8952 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '8952'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8952'
 id: 8953 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8953'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8953'
 id: 8954 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8954'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8954'
 id: 8955 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8955'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8955'
 id: 8956 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '8956'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8956'
 id: 8957 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '8957'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8957'
 id: 8958 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '8958'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8958'
 id: 8959 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8959'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8959'
 id: 8960 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8960'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8960'
 id: 8961 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8961'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8961'
 id: 8962 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '8962'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8962'
 id: 8963 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8963'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8963'
 id: 8964 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8964'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8964'
 id: 8965 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8965'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8965'
 id: 8966 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8966'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8966'
 id: 8967 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '8967'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8967'
 id: 8968 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8968'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8968'
 id: 8969 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '8969'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8969'
 id: 8970 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '8970'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8970'
 id: 8971 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8971'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8971'
 id: 8972 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8972'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8972'
 id: 8973 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8973'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8973'
 id: 8974 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '8974'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8974'
 id: 8975 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '8975'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8975'
 id: 8976 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8976'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8976'
 id: 8977 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8977'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8977'
 id: 8978 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '8978'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8978'
 id: 8979 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '8979'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8979'
 id: 8980 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8980'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8980'
 id: 8981 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '8981'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8981'
 id: 8982 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '8982'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8982'
 id: 8983 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '8983'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8983'
 id: 8984 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '8984'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8984'
 id: 8985 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '8985'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8985'
 id: 8986 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '8986'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8986'
 id: 8987 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '8987'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8987'
 id: 8988 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8988'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8988'
 id: 8989 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '8989'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8989'
 id: 8990 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8990'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8990'
 id: 8991 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '8991'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8991'
 id: 8992 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '8992'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8992'
 id: 8993 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '8993'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8993'
 id: 8994 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '8994'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8994'
 id: 8995 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '8995'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8995'
 id: 8996 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8996'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8996'
 id: 8997 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '8997'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8997'
 id: 8998 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '8998'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8998'
 id: 8999 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '8999'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '8999'
 id: 9000 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9000'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9000'
 id: 9001 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '9001'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9001'
 id: 9002 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9002'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9002'
 id: 9003 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '9003'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9003'
 id: 9004 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '9004'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9004'
 id: 9005 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '9005'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9005'
 id: 9006 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '9006'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9006'
 id: 9007 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '9007'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9007'
 id: 9008 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9008'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9008'
 id: 9009 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '9009'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9009'
 id: 9010 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '9010'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9010'
 id: 9011 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9011'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9011'
 id: 9012 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9012'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9012'
 id: 9013 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '9013'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9013'
 id: 9014 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9014'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9014'
 id: 9015 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '9015'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9015'
 id: 9016 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '9016'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9016'
 id: 9017 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9017'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9017'
 id: 9018 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9018'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9018'
 id: 9019 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9019'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9019'
 id: 9020 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9020'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9020'
 id: 9021 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9021'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9021'
 id: 9022 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9022'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9022'
 id: 9023 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9023'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9023'
 id: 9024 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9024'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9024'
 id: 9025 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9025'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9025'
 id: 9026 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9026'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9026'
 id: 9027 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9027'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9027'
 id: 9028 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '9028'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9028'
 id: 9029 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '9029'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9029'
 id: 9030 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9030'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9030'
 id: 9031 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9031'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9031'
 id: 9032 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '9032'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9032'
 id: 9033 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9033'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9033'
 id: 9034 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9034'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9034'
 id: 9035 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9035'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9035'
 id: 9036 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '9036'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9036'
 id: 9037 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '9037'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9037'
 id: 9038 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9038'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9038'
 id: 9039 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '9039'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9039'
 id: 9040 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9040'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9040'
 id: 9041 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9041'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9041'
 id: 9042 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '9042'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9042'
 id: 9043 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '9043'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9043'
 id: 9044 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9044'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9044'
 id: 9045 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '9045'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9045'
 id: 9046 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '9046'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9046'
 id: 9047 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '9047'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9047'
 id: 9048 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9048'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9048'
 id: 9049 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9049'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9049'
 id: 9050 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '9050'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9050'
 id: 9051 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '9051'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9051'
 id: 9052 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '9052'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9052'
 id: 9053 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9053'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9053'
 id: 9054 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9054'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9054'
 id: 9055 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '9055'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9055'
 id: 9056 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9056'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9056'
 id: 9057 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '9057'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9057'
 id: 9058 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9058'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9058'
 id: 9059 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '9059'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9059'
 id: 9060 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '9060'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9060'
 id: 9061 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '9061'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9061'
 id: 9062 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9062'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9062'
 id: 9063 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '9063'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9063'
 id: 9064 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '9064'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9064'
 id: 9065 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '9065'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9065'
 id: 9066 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '9066'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9066'
 id: 9067 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '9067'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9067'
 id: 9068 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9068'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9068'
 id: 9069 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9069'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9069'
 id: 9070 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9070'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9070'
 id: 9071 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9071'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9071'
 id: 9072 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '9072'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9072'
 id: 9073 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9073'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9073'
 id: 9074 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '9074'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9074'
 id: 9075 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9075'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9075'
 id: 9076 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '9076'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9076'
 id: 9077 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9077'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9077'
 id: 9078 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9078'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9078'
 id: 9079 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9079'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9079'
 id: 9080 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9080'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9080'
 id: 9081 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9081'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9081'
 id: 9082 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '9082'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9082'
 id: 9083 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '9083'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9083'
 id: 9084 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9084'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9084'
 id: 9085 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9085'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9085'
 id: 9086 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '9086'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9086'
 id: 9087 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '9087'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9087'
 id: 9088 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9088'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9088'
 id: 9089 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '9089'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9089'
 id: 9090 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '9090'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9090'
 id: 9091 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '9091'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9091'
 id: 9092 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '9092'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9092'
 id: 9093 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9093'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9093'
 id: 9094 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9094'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9094'
 id: 9095 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9095'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9095'
 id: 9096 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '9096'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9096'
 id: 9097 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9097'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9097'
 id: 9098 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9098'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9098'
 id: 9099 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '9099'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9099'
 id: 9100 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '9100'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9100'
 id: 9101 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9101'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9101'
 id: 9102 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9102'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9102'
 id: 9103 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '9103'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9103'
 id: 9104 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '9104'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9104'
 id: 9105 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '9105'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9105'
 id: 9106 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '9106'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9106'
 id: 9107 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '9107'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9107'
 id: 9108 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '9108'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9108'
 id: 9109 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '9109'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9109'
 id: 9110 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9110'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9110'
 id: 9111 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '9111'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9111'
 id: 9112 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9112'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9112'
 id: 9113 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '9113'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9113'
 id: 9114 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9114'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9114'
 id: 9115 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9115'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9115'
 id: 9116 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9116'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9116'
 id: 9117 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9117'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9117'
 id: 9118 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '9118'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9118'
 id: 9119 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '9119'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9119'
 id: 9120 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9120'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9120'
 id: 9121 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '9121'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9121'
 id: 9122 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9122'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9122'
 id: 9123 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9123'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9123'
 id: 9124 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9124'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9124'
 id: 9125 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9125'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9125'
 id: 9126 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9126'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9126'
 id: 9127 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '9127'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9127'
 id: 9128 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '9128'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9128'
 id: 9129 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9129'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9129'
 id: 9130 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '9130'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9130'
 id: 9131 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9131'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9131'
 id: 9132 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9132'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9132'
 id: 9133 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9133'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9133'
 id: 9134 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '9134'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9134'
 id: 9135 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '9135'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9135'
 id: 9136 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '9136'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9136'
 id: 9137 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9137'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9137'
 id: 9138 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '9138'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9138'
 id: 9139 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9139'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9139'
 id: 9140 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9140'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9140'
 id: 9141 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '9141'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9141'
 id: 9142 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9142'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9142'
 id: 9143 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '9143'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9143'
 id: 9144 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '9144'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9144'
 id: 9145 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9145'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9145'
 id: 9146 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '9146'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9146'
 id: 9147 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9147'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9147'
 id: 9148 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9148'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9148'
 id: 9149 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9149'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9149'
 id: 9150 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9150'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9150'
 id: 9151 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9151'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9151'
 id: 9152 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '9152'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9152'
 id: 9153 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '9153'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9153'
 id: 9154 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9154'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9154'
 id: 9155 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '9155'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9155'
 id: 9156 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9156'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9156'
 id: 9157 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '9157'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9157'
 id: 9158 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9158'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9158'
 id: 9159 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9159'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9159'
 id: 9160 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9160'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9160'
 id: 9161 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '9161'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9161'
 id: 9162 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '9162'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9162'
 id: 9163 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9163'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9163'
 id: 9164 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9164'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9164'
 id: 9165 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '9165'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9165'
 id: 9166 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '9166'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9166'
 id: 9167 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '9167'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9167'
 id: 9168 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '9168'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9168'
 id: 9169 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '9169'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9169'
 id: 9170 // word: 52
UPDATE job_vacancies SET domain_id =  '52' where raw_id = '9170'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9170'
 id: 9171 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '9171'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9171'
 id: 9172 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9172'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9172'
 id: 9173 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9173'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9173'
 id: 9174 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '9174'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9174'
 id: 9175 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9175'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9175'
 id: 9176 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '9176'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9176'
 id: 9177 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '9177'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9177'
 id: 9178 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '9178'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9178'
 id: 9179 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '9179'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9179'
 id: 9180 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9180'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9180'
 id: 9181 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9181'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9181'
 id: 9182 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '9182'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9182'
 id: 9183 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '9183'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9183'
 id: 9184 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9184'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9184'
 id: 9185 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '9185'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9185'
 id: 9186 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '9186'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9186'

 id: 9187 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '9187'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9187'
 id: 9188 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '9188'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9188'
 id: 9189 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9189'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9189'
 id: 9190 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9190'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9190'
 id: 9191 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9191'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9191'
 id: 9192 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9192'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9192'
 id: 9193 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9193'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9193'
 id: 9194 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '9194'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9194'
 id: 9195 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '9195'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9195'
 id: 9196 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9196'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9196'
 id: 9197 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9197'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9197'
 id: 9198 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9198'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9198'
 id: 9199 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9199'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9199'
 id: 9200 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '9200'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9200'
 id: 9201 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9201'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9201'
 id: 9202 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '9202'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9202'
 id: 9203 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '9203'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9203'
 id: 9204 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '9204'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9204'
 id: 9205 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '9205'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9205'
 id: 9206 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '9206'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9206'
 id: 9207 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9207'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9207'
 id: 9208 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '9208'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9208'
 id: 9209 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '9209'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9209'
 id: 9210 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '9210'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9210'
 id: 9211 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9211'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9211'
 id: 9212 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9212'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9212'
 id: 9213 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9213'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9213'
 id: 9214 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '9214'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9214'
 id: 9215 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9215'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9215'
 id: 9216 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9216'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9216'
 id: 9217 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '9217'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9217'
 id: 9218 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '9218'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9218'
 id: 9219 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '9219'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9219'
 id: 9220 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '9220'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9220'
 id: 9221 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '9221'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9221'
 id: 9222 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '9222'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9222'
 id: 9223 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '9223'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9223'
 id: 9224 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '9224'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9224'
 id: 9225 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9225'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9225'
 id: 9226 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9226'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9226'
 id: 9227 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9227'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9227'
 id: 9228 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9228'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9228'
 id: 9229 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '9229'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9229'
 id: 9230 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9230'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9230'
 id: 9231 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '9231'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9231'
 id: 9232 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9232'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9232'
 id: 9233 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '9233'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9233'
 id: 9234 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '9234'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9234'
 id: 9235 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9235'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9235'
 id: 9236 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9236'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9236'
 id: 9237 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9237'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9237'

 id: 9238 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '9238'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9238'
 id: 9239 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9239'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9239'
 id: 9240 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '9240'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9240'
 id: 9241 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '9241'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9241'
 id: 9242 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9242'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9242'
 id: 9243 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '9243'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9243'
 id: 9244 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9244'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9244'
 id: 9245 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '9245'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9245'
 id: 9246 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9246'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9246'
 id: 9247 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9247'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9247'
 id: 9248 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9248'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9248'
 id: 9249 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '9249'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9249'
 id: 9250 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '9250'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9250'
 id: 9251 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '9251'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9251'
 id: 9252 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '9252'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9252'
 id: 9253 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9253'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9253'
 id: 9254 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '9254'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9254'
 id: 9255 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '9255'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9255'
 id: 9256 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9256'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9256'
 id: 9257 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '9257'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9257'
 id: 9258 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '9258'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9258'
 id: 9259 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '9259'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9259'
 id: 9260 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9260'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9260'
 id: 9261 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9261'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9261'
 id: 9262 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9262'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9262'
 id: 9263 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9263'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9263'
 id: 9264 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '9264'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9264'
 id: 9265 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9265'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9265'
 id: 9266 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9266'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9266'
 id: 9267 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9267'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9267'
 id: 9268 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9268'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9268'
 id: 9269 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '9269'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9269'
 id: 9270 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '9270'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9270'
 id: 9271 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9271'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9271'
 id: 9272 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9272'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9272'
 id: 9273 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9273'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9273'
 id: 9274 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9274'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9274'
 id: 9275 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9275'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9275'
 id: 9276 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '9276'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9276'
 id: 9277 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '9277'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9277'
 id: 9278 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9278'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9278'
 id: 9279 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9279'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9279'
 id: 9280 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '9280'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9280'
 id: 9281 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9281'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9281'
 id: 9282 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '9282'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9282'
 id: 9283 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '9283'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9283'
 id: 9284 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '9284'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9284'
 id: 9285 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9285'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9285'
 id: 9286 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '9286'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9286'
 id: 9287 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '9287'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9287'
 id: 9288 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '9288'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9288'

 id: 9289 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9289'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9289'
 id: 9290 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '9290'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9290'
 id: 9291 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9291'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9291'
 id: 9292 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9292'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9292'
 id: 9293 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9293'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9293'
 id: 9294 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '9294'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9294'
 id: 9295 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9295'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9295'
 id: 9296 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '9296'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9296'
 id: 9297 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9297'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9297'
 id: 9298 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9298'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9298'
 id: 9299 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '9299'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9299'
 id: 9300 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '9300'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9300'
 id: 9301 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '9301'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9301'
 id: 9302 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '9302'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9302'
 id: 9303 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '9303'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9303'
 id: 9304 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '9304'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9304'
 id: 9305 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9305'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9305'
 id: 9306 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '9306'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9306'
 id: 9307 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '9307'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9307'
 id: 9308 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '9308'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9308'
 id: 9309 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '9309'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9309'
 id: 9310 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '9310'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9310'
 id: 9311 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '9311'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9311'
 id: 9312 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '9312'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9312'
 id: 9313 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '9313'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9313'
 id: 9314 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9314'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9314'
 id: 9315 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9315'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9315'
 id: 9316 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9316'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9316'
 id: 9317 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9317'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9317'
 id: 9318 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9318'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9318'
 id: 9319 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '9319'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9319'
 id: 9320 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9320'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9320'
 id: 9321 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '9321'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9321'
 id: 9322 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9322'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9322'
 id: 9323 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9323'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9323'
 id: 9324 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9324'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9324'
 id: 9325 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9325'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9325'
 id: 9326 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '9326'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9326'
 id: 9327 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '9327'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9327'
 id: 9328 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '9328'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9328'
 id: 9329 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9329'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9329'
 id: 9330 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '9330'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9330'
 id: 9331 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9331'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9331'
 id: 9332 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '9332'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9332'
 id: 9333 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9333'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9333'
 id: 9334 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9334'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9334'
 id: 9335 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '9335'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9335'
 id: 9336 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '9336'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9336'
 id: 9337 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '9337'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9337'
 id: 9338 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9338'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9338'
 id: 9339 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '9339'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9339'
 id: 9340 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '9340'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9340'
 id: 9341 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9341'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9341'
 id: 9342 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '9342'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9342'
 id: 9343 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '9343'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9343'
 id: 9344 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '9344'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9344'
 id: 9345 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '9345'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9345'
 id: 9346 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '9346'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9346'
 id: 9347 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '9347'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9347'
 id: 9348 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '9348'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9348'
 id: 9349 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9349'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9349'
 id: 9350 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9350'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9350'
 id: 9351 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9351'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9351'
 id: 9352 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9352'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9352'
 id: 9353 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9353'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9353'
 id: 9354 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9354'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9354'
 id: 9355 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '9355'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9355'
 id: 9356 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '9356'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9356'
 id: 9357 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9357'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9357'
 id: 9358 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '9358'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9358'
 id: 9359 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9359'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9359'
 id: 9360 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9360'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9360'
 id: 9361 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9361'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9361'
 id: 9362 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9362'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9362'
 id: 9363 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9363'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9363'
 id: 9364 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '9364'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9364'
 id: 9365 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '9365'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9365'
 id: 9366 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9366'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9366'
 id: 9367 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9367'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9367'
 id: 9368 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9368'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9368'
 id: 9369 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9369'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9369'
 id: 9370 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '9370'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9370'
 id: 9371 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '9371'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9371'
 id: 9372 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '9372'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9372'
 id: 9373 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9373'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9373'
 id: 9374 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9374'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9374'
 id: 9375 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '9375'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9375'
 id: 9376 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9376'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9376'
 id: 9377 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '9377'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9377'
 id: 9378 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9378'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9378'
 id: 9379 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9379'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9379'
 id: 9380 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '9380'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9380'
 id: 9381 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9381'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9381'
 id: 9382 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '9382'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9382'
 id: 9383 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '9383'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9383'
 id: 9384 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '9384'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9384'
 id: 9385 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9385'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9385'
 id: 9386 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9386'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9386'
 id: 9387 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9387'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9387'
 id: 9388 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '9388'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9388'
 id: 9389 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9389'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9389'
 id: 9390 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9390'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9390'
 id: 9391 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '9391'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9391'
 id: 9392 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9392'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9392'
 id: 9393 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9393'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9393'
 id: 9394 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9394'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9394'
 id: 9395 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9395'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9395'
 id: 9396 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9396'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9396'
 id: 9397 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '9397'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9397'
 id: 9398 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '9398'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9398'
 id: 9399 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9399'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9399'
 id: 9400 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9400'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9400'
 id: 9401 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '9401'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9401'
 id: 9402 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9402'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9402'
 id: 9403 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '9403'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9403'
 id: 9404 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9404'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9404'
 id: 9405 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '9405'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9405'
 id: 9406 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9406'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9406'
 id: 9407 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9407'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9407'
 id: 9408 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '9408'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9408'
 id: 9409 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '9409'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9409'
 id: 9410 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '9410'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9410'
 id: 9411 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '9411'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9411'
 id: 9412 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '9412'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9412'
 id: 9413 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9413'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9413'
 id: 9414 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9414'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9414'
 id: 9415 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9415'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9415'
 id: 9416 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '9416'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9416'
 id: 9417 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '9417'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9417'
 id: 9418 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '9418'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9418'
 id: 9419 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '9419'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9419'
 id: 9420 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9420'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9420'
 id: 9421 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9421'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9421'
 id: 9422 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '9422'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9422'
 id: 9423 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9423'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9423'
 id: 9424 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9424'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9424'
 id: 9425 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '9425'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9425'
 id: 9426 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9426'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9426'
 id: 9427 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9427'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9427'
 id: 9428 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9428'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9428'
 id: 9429 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9429'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9429'
 id: 9430 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9430'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9430'
 id: 9431 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '9431'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9431'
 id: 9432 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '9432'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9432'
 id: 9433 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '9433'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9433'
 id: 9434 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9434'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9434'
 id: 9435 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '9435'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9435'
 id: 9436 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9436'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9436'
 id: 9437 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '9437'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9437'
 id: 9438 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9438'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9438'
 id: 9439 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9439'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9439'
 id: 9440 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '9440'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9440'
 id: 9441 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '9441'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9441'
 id: 9442 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '9442'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9442'
 id: 9443 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9443'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9443'
 id: 9444 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9444'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9444'
 id: 9445 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '9445'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9445'
 id: 9446 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9446'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9446'
 id: 9447 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9447'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9447'
 id: 9448 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '9448'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9448'
 id: 9449 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9449'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9449'
 id: 9450 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9450'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9450'
 id: 9451 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9451'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9451'
 id: 9452 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9452'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9452'
 id: 9453 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9453'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9453'
 id: 9454 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9454'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9454'
 id: 9455 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '9455'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9455'
 id: 9456 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9456'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9456'
 id: 9457 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9457'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9457'
 id: 9458 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9458'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9458'
 id: 9459 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '9459'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9459'
 id: 9460 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9460'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9460'
 id: 9461 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9461'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9461'
 id: 9462 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9462'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9462'
 id: 9463 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '9463'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9463'
 id: 9464 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '9464'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9464'
 id: 9465 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9465'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9465'
 id: 9466 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '9466'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9466'
 id: 9467 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '9467'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9467'
 id: 9468 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9468'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9468'
 id: 9469 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9469'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9469'
 id: 9470 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9470'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9470'
 id: 9471 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9471'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9471'
 id: 9472 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '9472'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9472'
 id: 9473 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '9473'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9473'
 id: 9474 // word: 66
UPDATE job_vacancies SET domain_id =  '66' where raw_id = '9474'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9474'
 id: 9475 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '9475'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9475'
 id: 9476 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9476'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9476'
 id: 9477 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9477'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9477'
 id: 9478 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9478'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9478'
 id: 9479 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '9479'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9479'
 id: 9480 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9480'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9480'
 id: 9481 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9481'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9481'
 id: 9482 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9482'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9482'
 id: 9483 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '9483'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9483'
 id: 9484 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9484'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9484'
 id: 9485 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9485'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9485'
 id: 9486 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9486'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9486'
 id: 9487 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '9487'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9487'
 id: 9488 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '9488'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9488'
 id: 9489 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9489'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9489'
 id: 9490 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9490'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9490'
 id: 9491 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '9491'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9491'
 id: 9492 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9492'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9492'
 id: 9493 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9493'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9493'
 id: 9494 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9494'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9494'
 id: 9495 // word: 66
UPDATE job_vacancies SET domain_id =  '66' where raw_id = '9495'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9495'
 id: 9496 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '9496'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9496'
 id: 9497 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9497'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9497'
 id: 9498 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9498'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9498'
 id: 9499 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '9499'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9499'
 id: 9500 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9500'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9500'
 id: 9501 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9501'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9501'
 id: 9502 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '9502'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9502'
 id: 9503 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9503'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9503'
 id: 9504 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9504'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9504'
 id: 9505 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '9505'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9505'
 id: 9506 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9506'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9506'
 id: 9507 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9507'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9507'
 id: 9508 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9508'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9508'
 id: 9509 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9509'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9509'
 id: 9510 // word: 52
UPDATE job_vacancies SET domain_id =  '52' where raw_id = '9510'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9510'
 id: 9511 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '9511'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9511'
 id: 9512 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '9512'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9512'
 id: 9513 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9513'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9513'
 id: 9514 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '9514'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9514'
 id: 9515 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '9515'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9515'
 id: 9516 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '9516'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9516'
 id: 9517 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '9517'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9517'
 id: 9518 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9518'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9518'
 id: 9519 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9519'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9519'
 id: 9520 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9520'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9520'
 id: 9521 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9521'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9521'
 id: 9522 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9522'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9522'
 id: 9523 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9523'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9523'
 id: 9524 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '9524'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9524'
 id: 9525 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '9525'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9525'
 id: 9526 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '9526'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9526'
 id: 9527 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9527'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9527'
 id: 9528 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '9528'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9528'
 id: 9529 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '9529'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9529'
 id: 9530 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9530'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9530'
 id: 9531 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9531'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9531'
 id: 9532 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '9532'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9532'
 id: 9533 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9533'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9533'
 id: 9534 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '9534'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9534'
 id: 9535 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9535'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9535'
 id: 9536 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9536'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9536'
 id: 9537 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '9537'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9537'
 id: 9538 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9538'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9538'
 id: 9539 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9539'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9539'
 id: 9540 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9540'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9540'
 id: 9541 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9541'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9541'
 id: 9542 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '9542'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9542'
 id: 9543 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9543'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9543'
 id: 9544 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '9544'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9544'
 id: 9545 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9545'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9545'
 id: 9546 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '9546'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9546'
 id: 9547 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '9547'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9547'
 id: 9548 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9548'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9548'
 id: 9549 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9549'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9549'
 id: 9550 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9550'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9550'
 id: 9551 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9551'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9551'
 id: 9552 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9552'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9552'
 id: 9553 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '9553'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9553'
 id: 9554 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9554'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9554'
 id: 9555 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9555'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9555'
 id: 9556 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '9556'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9556'
 id: 9557 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '9557'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9557'
 id: 9558 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9558'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9558'
 id: 9559 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '9559'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9559'
 id: 9560 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9560'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9560'
 id: 9561 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9561'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9561'
 id: 9562 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9562'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9562'
 id: 9563 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '9563'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9563'
 id: 9564 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9564'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9564'
 id: 9565 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9565'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9565'
 id: 9566 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9566'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9566'
 id: 9567 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '9567'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9567'
 id: 9568 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '9568'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9568'
 id: 9569 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9569'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9569'
 id: 9570 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '9570'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9570'
 id: 9571 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '9571'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9571'
 id: 9572 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9572'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9572'
 id: 9573 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9573'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9573'
 id: 9574 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9574'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9574'
 id: 9575 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '9575'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9575'
 id: 9576 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9576'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9576'
 id: 9577 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '9577'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9577'
 id: 9578 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '9578'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9578'
 id: 9579 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '9579'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9579'
 id: 9580 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9580'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9580'
 id: 9581 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9581'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9581'
 id: 9582 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '9582'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9582'
 id: 9583 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9583'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9583'
 id: 9584 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '9584'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9584'
 id: 9585 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '9585'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9585'
 id: 9586 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '9586'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9586'
 id: 9587 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '9587'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9587'
 id: 9588 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9588'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9588'
 id: 9589 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9589'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9589'
 id: 9590 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9590'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9590'
 id: 9591 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '9591'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9591'
 id: 9592 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9592'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9592'
 id: 9593 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '9593'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9593'
 id: 9594 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9594'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9594'
 id: 9595 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9595'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9595'
 id: 9596 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '9596'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9596'
 id: 9597 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9597'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9597'
 id: 9598 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '9598'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9598'
 id: 9599 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '9599'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9599'
 id: 9600 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9600'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9600'
 id: 9601 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '9601'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9601'
 id: 9602 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9602'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9602'
 id: 9603 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '9603'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9603'
 id: 9604 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '9604'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9604'
 id: 9605 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9605'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9605'
 id: 9606 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9606'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9606'
 id: 9607 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9607'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9607'
 id: 9608 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '9608'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9608'
 id: 9609 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '9609'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9609'
 id: 9610 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9610'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9610'
 id: 9611 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9611'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9611'
 id: 9612 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9612'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9612'
 id: 9613 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '9613'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9613'
 id: 9614 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '9614'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9614'
 id: 9615 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '9615'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9615'
 id: 9616 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '9616'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9616'
 id: 9617 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9617'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9617'
 id: 9618 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9618'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9618'
 id: 9619 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9619'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9619'
 id: 9620 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9620'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9620'
 id: 9621 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9621'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9621'
 id: 9622 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '9622'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9622'
 id: 9623 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '9623'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9623'
 id: 9624 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9624'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9624'
 id: 9625 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '9625'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9625'
 id: 9626 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9626'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9626'
 id: 9627 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9627'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9627'
 id: 9628 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9628'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9628'
 id: 9629 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '9629'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9629'
 id: 9630 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '9630'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9630'
 id: 9631 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '9631'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9631'
 id: 9632 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '9632'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9632'
 id: 9633 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9633'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9633'
 id: 9634 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9634'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9634'
 id: 9635 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '9635'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9635'
 id: 9636 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9636'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9636'
 id: 9637 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '9637'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9637'
 id: 9638 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '9638'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9638'
 id: 9639 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9639'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9639'
 id: 9640 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9640'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9640'
 id: 9641 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '9641'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9641'
 id: 9642 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9642'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9642'
 id: 9643 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '9643'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9643'
 id: 9644 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '9644'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9644'
 id: 9645 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9645'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9645'
 id: 9646 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9646'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9646'
 id: 9647 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9647'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9647'
 id: 9648 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9648'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9648'
 id: 9649 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '9649'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9649'
 id: 9650 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9650'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9650'
 id: 9651 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9651'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9651'
 id: 9652 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '9652'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9652'
 id: 9653 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '9653'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9653'
 id: 9654 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9654'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9654'
 id: 9655 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9655'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9655'
 id: 9656 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '9656'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9656'
 id: 9657 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9657'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9657'
 id: 9658 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '9658'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9658'
 id: 9659 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9659'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9659'
 id: 9660 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9660'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9660'
 id: 9661 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '9661'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9661'
 id: 9662 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9662'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9662'
 id: 9663 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9663'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9663'
 id: 9664 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9664'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9664'
 id: 9665 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '9665'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9665'
 id: 9666 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '9666'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9666'
 id: 9667 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9667'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9667'
 id: 9668 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9668'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9668'
 id: 9669 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '9669'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9669'
 id: 9670 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9670'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9670'
 id: 9671 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9671'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9671'
 id: 9672 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '9672'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9672'
 id: 9673 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9673'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9673'
 id: 9674 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '9674'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9674'
 id: 9675 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '9675'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9675'
 id: 9676 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '9676'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9676'
 id: 9677 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9677'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9677'
 id: 9678 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9678'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9678'
 id: 9679 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '9679'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9679'
 id: 9680 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '9680'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9680'
 id: 9681 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '9681'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9681'
 id: 9682 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9682'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9682'
 id: 9683 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9683'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9683'
 id: 9684 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '9684'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9684'
 id: 9685 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9685'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9685'
 id: 9686 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9686'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9686'
 id: 9687 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '9687'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9687'
 id: 9688 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9688'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9688'
 id: 9689 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9689'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9689'
 id: 9690 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '9690'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9690'
 id: 9691 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '9691'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9691'
 id: 9692 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '9692'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9692'
 id: 9693 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9693'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9693'
 id: 9694 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '9694'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9694'
 id: 9695 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '9695'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9695'
 id: 9696 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9696'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9696'
 id: 9697 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9697'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9697'
 id: 9698 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9698'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9698'
 id: 9699 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '9699'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9699'
 id: 9700 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9700'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9700'
 id: 9701 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9701'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9701'
 id: 9702 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '9702'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9702'
 id: 9703 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9703'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9703'

 id: 9704 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '9704'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9704'
 id: 9705 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '9705'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9705'
 id: 9706 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '9706'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9706'
 id: 9707 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '9707'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9707'
 id: 9708 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9708'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9708'
 id: 9709 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9709'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9709'
 id: 9710 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9710'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9710'
 id: 9711 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '9711'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9711'
 id: 9712 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '9712'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9712'
 id: 9713 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '9713'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9713'
 id: 9714 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '9714'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9714'
 id: 9715 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9715'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9715'
 id: 9716 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '9716'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9716'
 id: 9717 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9717'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9717'
 id: 9718 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9718'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9718'
 id: 9719 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '9719'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9719'
 id: 9720 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9720'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9720'
 id: 9721 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9721'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9721'
 id: 9722 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '9722'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9722'
 id: 9723 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '9723'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9723'
 id: 9724 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '9724'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9724'
 id: 9725 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '9725'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9725'
 id: 9726 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9726'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9726'
 id: 9727 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9727'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9727'
 id: 9728 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9728'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9728'
 id: 9729 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9729'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9729'
 id: 9730 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9730'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9730'
 id: 9731 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9731'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9731'
 id: 9732 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9732'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9732'
 id: 9733 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9733'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9733'
 id: 9734 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9734'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9734'
 id: 9735 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9735'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9735'
 id: 9736 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9736'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9736'
 id: 9737 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9737'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9737'
 id: 9738 // word: 57
UPDATE job_vacancies SET domain_id =  '57' where raw_id = '9738'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9738'
 id: 9739 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '9739'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9739'
 id: 9740 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9740'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9740'
 id: 9741 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9741'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9741'
 id: 9742 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9742'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9742'
 id: 9743 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9743'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9743'
 id: 9744 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9744'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9744'
 id: 9745 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9745'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9745'
 id: 9746 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9746'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9746'
 id: 9747 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9747'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9747'
 id: 9748 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9748'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9748'
 id: 9749 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9749'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9749'
 id: 9750 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9750'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9750'
 id: 9751 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9751'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9751'
 id: 9752 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '9752'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9752'
 id: 9753 // word: 57
UPDATE job_vacancies SET domain_id =  '57' where raw_id = '9753'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9753'
 id: 9754 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9754'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9754'
 id: 9755 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9755'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9755'
 id: 9756 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9756'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9756'
 id: 9757 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9757'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9757'
 id: 9758 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9758'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9758'
 id: 9759 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '9759'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9759'
 id: 9760 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9760'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9760'
 id: 9761 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9761'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9761'
 id: 9762 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '9762'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9762'
 id: 9763 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9763'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9763'
 id: 9764 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '9764'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9764'
 id: 9765 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '9765'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9765'
 id: 9766 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9766'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9766'
 id: 9767 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9767'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9767'
 id: 9768 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '9768'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9768'
 id: 9769 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '9769'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9769'
 id: 9770 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '9770'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9770'
 id: 9771 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9771'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9771'
 id: 9772 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9772'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9772'
 id: 9773 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9773'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9773'
 id: 9774 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '9774'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9774'
 id: 9775 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9775'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9775'
 id: 9776 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '9776'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9776'
 id: 9777 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9777'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9777'
 id: 9778 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '9778'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9778'
 id: 9779 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9779'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9779'
 id: 9780 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9780'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9780'
 id: 9781 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '9781'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9781'
 id: 9782 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '9782'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9782'
 id: 9783 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9783'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9783'
 id: 9784 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9784'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9784'
 id: 9785 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '9785'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9785'
 id: 9786 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '9786'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9786'
 id: 9787 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '9787'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9787'
 id: 9788 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9788'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9788'
 id: 9789 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '9789'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9789'
 id: 9790 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '9790'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9790'
 id: 9791 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9791'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9791'
 id: 9792 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9792'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9792'
 id: 9793 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9793'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9793'
 id: 9794 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9794'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9794'
 id: 9795 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9795'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9795'
 id: 9796 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9796'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9796'
 id: 9797 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9797'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9797'
 id: 9798 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '9798'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9798'
 id: 9799 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '9799'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9799'
 id: 9800 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '9800'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9800'
 id: 9801 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9801'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9801'
 id: 9802 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9802'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9802'
 id: 9803 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9803'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9803'
 id: 9804 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9804'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9804'
 id: 9805 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '9805'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9805'
 id: 9806 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9806'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9806'
 id: 9807 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9807'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9807'
 id: 9808 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '9808'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9808'
 id: 9809 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '9809'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9809'
 id: 9810 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '9810'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9810'
 id: 9811 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9811'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9811'
 id: 9812 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9812'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9812'
 id: 9813 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9813'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9813'
 id: 9814 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '9814'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9814'
 id: 9815 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9815'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9815'
 id: 9816 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9816'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9816'
 id: 9817 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9817'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9817'
 id: 9818 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9818'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9818'
 id: 9819 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9819'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9819'
 id: 9820 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9820'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9820'
 id: 9821 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '9821'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9821'
 id: 9822 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '9822'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9822'
 id: 9823 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '9823'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9823'
 id: 9824 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '9824'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9824'
 id: 9825 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9825'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9825'
 id: 9826 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9826'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9826'
 id: 9827 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9827'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9827'
 id: 9828 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9828'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9828'
 id: 9829 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9829'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9829'
 id: 9830 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9830'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9830'
 id: 9831 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '9831'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9831'
 id: 9832 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9832'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9832'
 id: 9833 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9833'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9833'
 id: 9834 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9834'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9834'
 id: 9835 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9835'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9835'
 id: 9836 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '9836'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9836'
 id: 9837 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '9837'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9837'
 id: 9838 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9838'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9838'
 id: 9839 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '9839'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9839'
 id: 9840 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '9840'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9840'
 id: 9841 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '9841'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9841'
 id: 9842 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9842'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9842'
 id: 9843 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9843'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9843'
 id: 9844 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9844'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9844'
 id: 9845 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9845'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9845'
 id: 9846 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9846'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9846'
 id: 9847 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9847'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9847'
 id: 9848 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9848'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9848'
 id: 9849 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9849'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9849'
 id: 9850 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9850'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9850'
 id: 9851 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '9851'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9851'
 id: 9852 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '9852'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9852'
 id: 9853 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9853'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9853'
 id: 9854 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9854'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9854'
 id: 9855 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '9855'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9855'
 id: 9856 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '9856'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9856'
 id: 9857 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '9857'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9857'
 id: 9858 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '9858'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9858'

 id: 9859 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9859'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9859'
 id: 9860 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9860'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9860'
 id: 9861 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '9861'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9861'
 id: 9862 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '9862'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9862'
 id: 9863 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '9863'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9863'
 id: 9864 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9864'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9864'
 id: 9865 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '9865'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9865'
 id: 9866 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9866'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9866'
 id: 9867 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '9867'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9867'
 id: 9868 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9868'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9868'
 id: 9869 // word: 49
UPDATE job_vacancies SET domain_id =  '49' where raw_id = '9869'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9869'
 id: 9870 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '9870'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9870'
 id: 9871 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9871'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9871'
 id: 9872 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9872'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9872'
 id: 9873 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '9873'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9873'
 id: 9874 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9874'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9874'
 id: 9875 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9875'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9875'
 id: 9876 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '9876'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9876'
 id: 9877 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9877'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9877'
 id: 9878 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '9878'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9878'
 id: 9879 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '9879'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9879'
 id: 9880 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9880'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9880'
 id: 9881 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '9881'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9881'
 id: 9882 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9882'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9882'
 id: 9883 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '9883'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9883'
 id: 9884 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '9884'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9884'
 id: 9885 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9885'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9885'
 id: 9886 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '9886'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9886'
 id: 9887 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9887'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9887'
 id: 9888 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '9888'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9888'
 id: 9889 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9889'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9889'
 id: 9890 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9890'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9890'
 id: 9891 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '9891'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9891'
 id: 9892 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '9892'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9892'
 id: 9893 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '9893'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9893'
 id: 9894 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '9894'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9894'
 id: 9895 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '9895'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9895'
 id: 9896 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9896'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9896'
 id: 9897 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '9897'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9897'
 id: 9898 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '9898'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9898'
 id: 9899 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '9899'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9899'
 id: 9900 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '9900'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9900'
 id: 9901 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9901'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9901'
 id: 9902 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9902'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9902'
 id: 9903 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '9903'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9903'
 id: 9904 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '9904'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9904'
 id: 9905 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '9905'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9905'
 id: 9906 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9906'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9906'
 id: 9907 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '9907'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9907'
 id: 9908 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '9908'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9908'
 id: 9909 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '9909'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9909'
 id: 9910 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9910'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9910'
 id: 9911 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9911'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9911'
 id: 9912 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9912'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9912'
 id: 9913 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9913'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9913'
 id: 9914 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9914'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9914'
 id: 9915 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '9915'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9915'
 id: 9916 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '9916'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9916'
 id: 9917 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9917'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9917'
 id: 9918 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9918'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9918'
 id: 9919 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '9919'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9919'
 id: 9920 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9920'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9920'
 id: 9921 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '9921'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9921'
 id: 9922 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '9922'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9922'
 id: 9923 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9923'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9923'
 id: 9924 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '9924'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9924'
 id: 9925 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9925'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9925'
 id: 9926 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9926'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9926'
 id: 9927 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '9927'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9927'
 id: 9928 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '9928'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9928'
 id: 9929 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '9929'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9929'
 id: 9930 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9930'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9930'
 id: 9931 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9931'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9931'
 id: 9932 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '9932'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9932'
 id: 9933 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '9933'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9933'
 id: 9934 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9934'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9934'
 id: 9935 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9935'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9935'
 id: 9936 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9936'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9936'
 id: 9937 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9937'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9937'
 id: 9938 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '9938'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9938'
 id: 9939 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '9939'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9939'
 id: 9940 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9940'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9940'
 id: 9941 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9941'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9941'
 id: 9942 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9942'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9942'
 id: 9943 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9943'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9943'
 id: 9944 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '9944'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9944'
 id: 9945 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '9945'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9945'
 id: 9946 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9946'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9946'
 id: 9947 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9947'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9947'
 id: 9948 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '9948'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9948'
 id: 9949 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '9949'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9949'
 id: 9950 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '9950'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9950'
 id: 9951 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '9951'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9951'
 id: 9952 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '9952'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9952'
 id: 9953 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9953'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9953'
 id: 9954 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9954'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9954'
 id: 9955 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9955'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9955'
 id: 9956 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9956'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9956'
 id: 9957 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '9957'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9957'
 id: 9958 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9958'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9958'
 id: 9959 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9959'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9959'
 id: 9960 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '9960'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9960'
 id: 9961 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '9961'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9961'
 id: 9962 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '9962'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9962'
 id: 9963 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '9963'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9963'
 id: 9964 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '9964'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9964'
 id: 9965 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '9965'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9965'
 id: 9966 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '9966'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9966'
 id: 9967 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '9967'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9967'
 id: 9968 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '9968'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9968'
 id: 9969 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '9969'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9969'
 id: 9970 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '9970'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9970'
 id: 9971 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '9971'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9971'
 id: 9972 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9972'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9972'
 id: 9973 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9973'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9973'
 id: 9974 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '9974'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9974'
 id: 9975 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '9975'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9975'
 id: 9976 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9976'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9976'
 id: 9977 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '9977'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9977'
 id: 9978 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9978'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9978'
 id: 9979 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9979'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9979'
 id: 9980 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '9980'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9980'
 id: 9981 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '9981'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9981'
 id: 9982 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '9982'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9982'
 id: 9983 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9983'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9983'
 id: 9984 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '9984'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9984'
 id: 9985 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9985'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9985'
 id: 9986 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '9986'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9986'
 id: 9987 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '9987'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9987'
 id: 9988 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '9988'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9988'
 id: 9989 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '9989'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9989'
 id: 9990 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '9990'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9990'
 id: 9991 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '9991'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9991'
 id: 9992 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '9992'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9992'
 id: 9993 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '9993'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9993'
 id: 9994 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9994'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9994'
 id: 9995 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '9995'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9995'
 id: 9996 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '9996'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9996'
 id: 9997 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '9997'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9997'
 id: 9998 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9998'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9998'
 id: 9999 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '9999'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '9999'
 id: 10000 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '10000'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10000'
 id: 10001 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10001'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10001'
 id: 10002 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10002'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10002'
 id: 10003 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '10003'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10003'
 id: 10004 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10004'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10004'
 id: 10005 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10005'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10005'
 id: 10006 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10006'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10006'
 id: 10007 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10007'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10007'
 id: 10008 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '10008'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10008'
 id: 10009 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '10009'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10009'
 id: 10010 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10010'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10010'
 id: 10011 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10011'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10011'
 id: 10012 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10012'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10012'
 id: 10013 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '10013'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10013'
 id: 10014 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '10014'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10014'
 id: 10015 // word: 52
UPDATE job_vacancies SET domain_id =  '52' where raw_id = '10015'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10015'
 id: 10016 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10016'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10016'
 id: 10017 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10017'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10017'
 id: 10018 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10018'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10018'
 id: 10019 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10019'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10019'
 id: 10020 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10020'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10020'
 id: 10021 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10021'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10021'
 id: 10022 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10022'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10022'
 id: 10023 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10023'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10023'
 id: 10024 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10024'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10024'
 id: 10025 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '10025'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10025'
 id: 10026 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10026'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10026'
 id: 10027 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '10027'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10027'
 id: 10028 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10028'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10028'
 id: 10029 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '10029'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10029'
 id: 10030 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10030'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10030'
 id: 10031 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '10031'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10031'
 id: 10032 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10032'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10032'
 id: 10033 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10033'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10033'
 id: 10034 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10034'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10034'
 id: 10035 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '10035'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10035'
 id: 10036 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '10036'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10036'
 id: 10037 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '10037'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10037'
 id: 10038 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10038'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10038'
 id: 10039 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '10039'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10039'
 id: 10040 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '10040'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10040'
 id: 10041 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '10041'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10041'
 id: 10042 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10042'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10042'
 id: 10043 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10043'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10043'
 id: 10044 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10044'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10044'
 id: 10045 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10045'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10045'
 id: 10046 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10046'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10046'
 id: 10047 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '10047'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10047'
 id: 10048 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10048'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10048'
 id: 10049 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '10049'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10049'
 id: 10050 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10050'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10050'
 id: 10051 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '10051'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10051'
 id: 10052 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '10052'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10052'
 id: 10053 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10053'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10053'
 id: 10054 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '10054'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10054'
 id: 10055 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10055'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10055'
 id: 10056 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10056'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10056'
 id: 10057 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10057'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10057'
 id: 10058 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10058'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10058'
 id: 10059 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10059'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10059'
 id: 10060 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10060'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10060'
 id: 10061 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10061'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10061'
 id: 10062 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10062'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10062'
 id: 10063 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '10063'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10063'
 id: 10064 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '10064'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10064'
 id: 10065 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10065'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10065'
 id: 10066 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10066'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10066'
 id: 10067 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '10067'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10067'
 id: 10068 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10068'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10068'

 id: 10069 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10069'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10069'
 id: 10070 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '10070'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10070'
 id: 10071 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10071'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10071'
 id: 10072 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10072'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10072'
 id: 10073 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '10073'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10073'
 id: 10074 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10074'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10074'
 id: 10075 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10075'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10075'
 id: 10076 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10076'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10076'
 id: 10077 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10077'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10077'
 id: 10078 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10078'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10078'
 id: 10079 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10079'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10079'
 id: 10080 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10080'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10080'
 id: 10081 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10081'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10081'
 id: 10082 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10082'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10082'
 id: 10083 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10083'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10083'
 id: 10084 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '10084'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10084'
 id: 10085 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '10085'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10085'
 id: 10086 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10086'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10086'
 id: 10087 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '10087'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10087'
 id: 10088 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10088'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10088'
 id: 10089 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '10089'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10089'
 id: 10090 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '10090'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10090'
 id: 10091 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10091'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10091'
 id: 10092 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10092'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10092'
 id: 10093 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10093'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10093'
 id: 10094 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '10094'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10094'
 id: 10095 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '10095'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10095'
 id: 10096 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10096'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10096'
 id: 10097 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10097'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10097'
 id: 10098 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '10098'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10098'
 id: 10099 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '10099'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10099'
 id: 10100 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10100'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10100'
 id: 10101 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10101'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10101'
 id: 10102 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '10102'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10102'
 id: 10103 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10103'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10103'
 id: 10104 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10104'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10104'
 id: 10105 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '10105'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10105'
 id: 10106 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10106'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10106'
 id: 10107 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10107'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10107'
 id: 10108 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10108'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10108'
 id: 10109 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10109'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10109'
 id: 10110 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10110'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10110'
 id: 10111 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10111'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10111'
 id: 10112 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '10112'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10112'
 id: 10113 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '10113'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10113'
 id: 10114 // word: 52
UPDATE job_vacancies SET domain_id =  '52' where raw_id = '10114'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10114'
 id: 10115 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '10115'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10115'
 id: 10116 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10116'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10116'
 id: 10117 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '10117'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10117'
 id: 10118 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '10118'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10118'
 id: 10119 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '10119'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10119'
 id: 10120 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '10120'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10120'
 id: 10121 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10121'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10121'
 id: 10122 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10122'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10122'
 id: 10123 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '10123'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10123'
 id: 10124 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '10124'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10124'
 id: 10125 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10125'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10125'
 id: 10126 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '10126'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10126'
 id: 10127 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '10127'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10127'
 id: 10128 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '10128'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10128'
 id: 10129 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10129'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10129'
 id: 10130 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10130'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10130'
 id: 10131 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '10131'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10131'
 id: 10132 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10132'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10132'
 id: 10133 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '10133'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10133'
 id: 10134 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '10134'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10134'
 id: 10135 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10135'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10135'
 id: 10136 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '10136'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10136'
 id: 10137 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '10137'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10137'
 id: 10138 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '10138'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10138'
 id: 10139 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '10139'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10139'
 id: 10140 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10140'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10140'
 id: 10141 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10141'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10141'
 id: 10142 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10142'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10142'
 id: 10143 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '10143'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10143'
 id: 10144 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10144'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10144'
 id: 10145 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10145'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10145'
 id: 10146 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10146'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10146'
 id: 10147 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10147'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10147'
 id: 10148 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10148'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10148'
 id: 10149 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10149'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10149'
 id: 10150 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10150'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10150'
 id: 10151 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '10151'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10151'
 id: 10152 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10152'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10152'
 id: 10153 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10153'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10153'
 id: 10154 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '10154'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10154'
 id: 10155 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10155'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10155'
 id: 10156 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10156'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10156'
 id: 10157 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10157'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10157'
 id: 10158 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10158'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10158'
 id: 10159 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10159'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10159'
 id: 10160 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10160'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10160'
 id: 10161 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10161'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10161'
 id: 10162 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10162'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10162'
 id: 10163 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10163'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10163'
 id: 10164 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10164'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10164'
 id: 10165 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10165'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10165'
 id: 10166 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10166'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10166'
 id: 10167 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '10167'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10167'
 id: 10168 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10168'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10168'
 id: 10169 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10169'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10169'
 id: 10170 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '10170'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10170'
 id: 10171 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10171'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10171'
 id: 10172 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10172'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10172'
 id: 10173 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '10173'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10173'
 id: 10174 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10174'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10174'
 id: 10175 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '10175'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10175'
 id: 10176 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '10176'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10176'
 id: 10177 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10177'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10177'
 id: 10178 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10178'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10178'
 id: 10179 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10179'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10179'
 id: 10180 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10180'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10180'
 id: 10181 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10181'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10181'
 id: 10182 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10182'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10182'
 id: 10183 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10183'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10183'
 id: 10184 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10184'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10184'
 id: 10185 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10185'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10185'
 id: 10186 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10186'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10186'
 id: 10187 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '10187'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10187'
 id: 10188 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10188'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10188'
 id: 10189 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10189'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10189'
 id: 10190 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10190'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10190'
 id: 10191 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10191'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10191'
 id: 10192 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '10192'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10192'
 id: 10193 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '10193'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10193'
 id: 10194 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10194'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10194'
 id: 10195 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10195'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10195'
 id: 10196 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10196'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10196'
 id: 10197 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10197'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10197'
 id: 10198 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10198'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10198'
 id: 10199 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10199'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10199'
 id: 10200 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '10200'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10200'
 id: 10201 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10201'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10201'
 id: 10202 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '10202'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10202'
 id: 10203 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10203'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10203'
 id: 10204 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10204'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10204'
 id: 10205 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '10205'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10205'
 id: 10206 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10206'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10206'
 id: 10207 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10207'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10207'
 id: 10208 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '10208'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10208'
 id: 10209 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10209'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10209'
 id: 10210 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10210'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10210'
 id: 10211 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '10211'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10211'
 id: 10212 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '10212'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10212'
 id: 10213 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10213'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10213'
 id: 10214 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10214'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10214'
 id: 10215 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10215'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10215'
 id: 10216 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '10216'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10216'
 id: 10217 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10217'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10217'
 id: 10218 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10218'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10218'
 id: 10219 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10219'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10219'
 id: 10220 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10220'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10220'
 id: 10221 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10221'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10221'
 id: 10222 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '10222'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10222'
 id: 10223 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '10223'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10223'
 id: 10224 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10224'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10224'
 id: 10225 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10225'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10225'
 id: 10226 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '10226'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10226'
 id: 10227 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10227'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10227'
 id: 10228 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10228'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10228'
 id: 10229 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10229'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10229'
 id: 10230 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '10230'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10230'
 id: 10231 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '10231'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10231'
 id: 10232 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10232'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10232'
 id: 10233 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10233'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10233'
 id: 10234 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10234'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10234'
 id: 10235 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10235'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10235'
 id: 10236 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '10236'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10236'
 id: 10237 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10237'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10237'
 id: 10238 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10238'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10238'
 id: 10239 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '10239'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10239'
 id: 10240 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10240'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10240'
 id: 10241 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '10241'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10241'
 id: 10242 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10242'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10242'
 id: 10243 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10243'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10243'
 id: 10244 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10244'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10244'
 id: 10245 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '10245'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10245'
 id: 10246 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10246'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10246'
 id: 10247 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10247'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10247'
 id: 10248 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '10248'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10248'
 id: 10249 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10249'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10249'
 id: 10250 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '10250'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10250'
 id: 10251 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '10251'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10251'
 id: 10252 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '10252'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10252'
 id: 10253 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10253'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10253'
 id: 10254 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10254'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10254'
 id: 10255 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10255'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10255'
 id: 10256 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10256'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10256'
 id: 10257 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '10257'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10257'
 id: 10258 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10258'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10258'
 id: 10259 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10259'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10259'
 id: 10260 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '10260'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10260'
 id: 10261 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10261'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10261'
 id: 10262 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10262'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10262'
 id: 10263 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '10263'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10263'
 id: 10264 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10264'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10264'
 id: 10265 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '10265'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10265'
 id: 10266 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10266'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10266'
 id: 10267 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '10267'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10267'
 id: 10268 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10268'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10268'
 id: 10269 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '10269'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10269'
 id: 10270 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10270'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10270'
 id: 10271 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10271'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10271'
 id: 10272 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '10272'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10272'
 id: 10273 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10273'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10273'
 id: 10274 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10274'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10274'
 id: 10275 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10275'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10275'
 id: 10276 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10276'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10276'
 id: 10277 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10277'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10277'
 id: 10278 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10278'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10278'
 id: 10279 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '10279'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10279'
 id: 10280 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10280'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10280'
 id: 10281 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10281'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10281'
 id: 10282 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10282'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10282'
 id: 10283 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '10283'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10283'
 id: 10284 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '10284'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10284'
 id: 10285 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10285'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10285'
 id: 10286 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '10286'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10286'
 id: 10287 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '10287'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10287'
 id: 10288 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10288'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10288'
 id: 10289 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10289'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10289'
 id: 10290 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10290'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10290'
 id: 10291 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10291'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10291'
 id: 10292 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10292'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10292'
 id: 10293 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '10293'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10293'
 id: 10294 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10294'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10294'
 id: 10295 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '10295'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10295'
 id: 10296 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '10296'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10296'
 id: 10297 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '10297'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10297'
 id: 10298 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '10298'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10298'
 id: 10299 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '10299'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10299'
 id: 10300 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '10300'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10300'
 id: 10301 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '10301'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10301'
 id: 10302 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10302'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10302'
 id: 10303 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '10303'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10303'
 id: 10304 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '10304'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10304'
 id: 10305 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10305'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10305'
 id: 10306 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10306'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10306'
 id: 10307 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10307'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10307'
 id: 10308 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10308'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10308'
 id: 10309 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '10309'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10309'
 id: 10310 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '10310'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10310'
 id: 10311 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10311'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10311'
 id: 10312 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '10312'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10312'
 id: 10313 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '10313'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10313'
 id: 10314 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10314'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10314'
 id: 10315 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10315'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10315'
 id: 10316 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10316'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10316'
 id: 10317 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '10317'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10317'
 id: 10318 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10318'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10318'
 id: 10319 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '10319'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10319'
 id: 10320 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '10320'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10320'
 id: 10321 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10321'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10321'
 id: 10322 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10322'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10322'
 id: 10323 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10323'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10323'
 id: 10324 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '10324'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10324'
 id: 10325 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10325'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10325'
 id: 10326 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '10326'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10326'
 id: 10327 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '10327'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10327'
 id: 10328 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10328'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10328'
 id: 10329 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '10329'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10329'
 id: 10330 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '10330'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10330'
 id: 10331 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '10331'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10331'
 id: 10332 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '10332'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10332'
 id: 10333 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10333'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10333'
 id: 10334 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10334'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10334'
 id: 10335 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10335'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10335'
 id: 10336 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '10336'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10336'
 id: 10337 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10337'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10337'
 id: 10338 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10338'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10338'
 id: 10339 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '10339'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10339'
 id: 10340 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10340'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10340'
 id: 10341 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10341'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10341'
 id: 10342 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '10342'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10342'
 id: 10343 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10343'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10343'
 id: 10344 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '10344'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10344'
 id: 10345 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '10345'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10345'
 id: 10346 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '10346'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10346'
 id: 10347 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '10347'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10347'
 id: 10348 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10348'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10348'
 id: 10349 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10349'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10349'
 id: 10350 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '10350'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10350'
 id: 10351 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10351'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10351'
 id: 10352 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '10352'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10352'
 id: 10353 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10353'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10353'
 id: 10354 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10354'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10354'
 id: 10355 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '10355'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10355'
 id: 10356 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10356'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10356'
 id: 10357 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10357'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10357'
 id: 10358 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '10358'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10358'
 id: 10359 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10359'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10359'
 id: 10360 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10360'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10360'
 id: 10361 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10361'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10361'
 id: 10362 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10362'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10362'
 id: 10363 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '10363'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10363'
 id: 10364 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10364'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10364'
 id: 10365 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10365'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10365'
 id: 10366 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '10366'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10366'
 id: 10367 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10367'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10367'
 id: 10368 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10368'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10368'
 id: 10369 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10369'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10369'
 id: 10370 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10370'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10370'
 id: 10371 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10371'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10371'
 id: 10372 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10372'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10372'
 id: 10373 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10373'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10373'
 id: 10374 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '10374'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10374'
 id: 10375 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '10375'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10375'
 id: 10376 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '10376'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10376'
 id: 10377 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10377'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10377'
 id: 10378 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '10378'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10378'
 id: 10379 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10379'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10379'
 id: 10380 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '10380'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10380'
 id: 10381 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '10381'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10381'
 id: 10382 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10382'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10382'
 id: 10383 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10383'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10383'
 id: 10384 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '10384'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10384'
 id: 10385 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '10385'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10385'
 id: 10386 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '10386'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10386'
 id: 10387 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '10387'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10387'
 id: 10388 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '10388'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10388'
 id: 10389 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10389'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10389'
 id: 10390 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10390'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10390'
 id: 10391 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '10391'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10391'
 id: 10392 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '10392'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10392'
 id: 10393 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '10393'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10393'
 id: 10394 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '10394'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10394'
 id: 10395 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '10395'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10395'
 id: 10396 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10396'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10396'
 id: 10397 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '10397'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10397'
 id: 10398 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10398'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10398'
 id: 10399 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '10399'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10399'
 id: 10400 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '10400'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10400'
 id: 10401 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10401'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10401'
 id: 10402 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10402'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10402'
 id: 10403 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10403'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10403'
 id: 10404 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '10404'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10404'
 id: 10405 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '10405'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10405'
 id: 10406 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10406'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10406'
 id: 10407 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10407'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10407'
 id: 10408 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '10408'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10408'
 id: 10409 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '10409'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10409'
 id: 10410 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '10410'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10410'
 id: 10411 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '10411'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10411'
 id: 10412 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10412'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10412'
 id: 10413 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '10413'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10413'
 id: 10414 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10414'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10414'
 id: 10415 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10415'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10415'
 id: 10416 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10416'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10416'
 id: 10417 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10417'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10417'
 id: 10418 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '10418'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10418'
 id: 10419 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '10419'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10419'
 id: 10420 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10420'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10420'
 id: 10421 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10421'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10421'
 id: 10422 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '10422'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10422'
 id: 10423 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '10423'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10423'
 id: 10424 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10424'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10424'
 id: 10425 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10425'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10425'

 id: 10426 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '10426'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10426'
 id: 10427 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10427'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10427'
 id: 10428 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10428'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10428'
 id: 10429 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10429'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10429'
 id: 10430 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10430'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10430'
 id: 10431 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '10431'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10431'
 id: 10432 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10432'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10432'
 id: 10433 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10433'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10433'
 id: 10434 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '10434'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10434'
 id: 10435 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10435'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10435'
 id: 10436 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10436'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10436'
 id: 10437 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10437'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10437'
 id: 10438 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10438'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10438'
 id: 10439 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '10439'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10439'
 id: 10440 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10440'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10440'
 id: 10441 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10441'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10441'
 id: 10442 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '10442'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10442'
 id: 10443 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '10443'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10443'
 id: 10444 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '10444'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10444'
 id: 10445 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10445'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10445'
 id: 10446 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10446'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10446'
 id: 10447 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '10447'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10447'
 id: 10448 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10448'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10448'
 id: 10449 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10449'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10449'
 id: 10450 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '10450'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10450'
 id: 10451 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10451'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10451'
 id: 10452 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10452'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10452'
 id: 10453 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '10453'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10453'
 id: 10454 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10454'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10454'
 id: 10455 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10455'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10455'
 id: 10456 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10456'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10456'
 id: 10457 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10457'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10457'
 id: 10458 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10458'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10458'
 id: 10459 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10459'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10459'
 id: 10460 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10460'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10460'
 id: 10461 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '10461'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10461'
 id: 10462 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10462'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10462'
 id: 10463 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '10463'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10463'
 id: 10464 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '10464'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10464'
 id: 10465 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '10465'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10465'
 id: 10466 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10466'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10466'
 id: 10467 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '10467'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10467'
 id: 10468 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10468'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10468'
 id: 10469 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10469'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10469'
 id: 10470 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10470'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10470'
 id: 10471 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '10471'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10471'
 id: 10472 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '10472'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10472'
 id: 10473 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10473'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10473'
 id: 10474 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10474'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10474'
 id: 10475 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10475'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10475'
 id: 10476 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10476'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10476'
 id: 10477 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10477'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10477'
 id: 10478 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10478'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10478'
 id: 10479 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '10479'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10479'
 id: 10480 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10480'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10480'
 id: 10481 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10481'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10481'
 id: 10482 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '10482'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10482'
 id: 10483 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '10483'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10483'
 id: 10484 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10484'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10484'
 id: 10485 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10485'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10485'
 id: 10486 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10486'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10486'
 id: 10487 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10487'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10487'
 id: 10488 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10488'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10488'
 id: 10489 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '10489'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10489'
 id: 10490 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '10490'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10490'
 id: 10491 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10491'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10491'
 id: 10492 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10492'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10492'
 id: 10493 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '10493'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10493'
 id: 10494 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10494'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10494'
 id: 10495 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '10495'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10495'
 id: 10496 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10496'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10496'
 id: 10497 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10497'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10497'
 id: 10498 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '10498'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10498'
 id: 10499 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '10499'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10499'
 id: 10500 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10500'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10500'
 id: 10501 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10501'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10501'
 id: 10502 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '10502'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10502'
 id: 10503 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10503'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10503'
 id: 10504 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10504'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10504'
 id: 10505 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10505'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10505'
 id: 10506 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10506'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10506'
 id: 10507 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10507'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10507'
 id: 10508 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10508'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10508'
 id: 10509 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10509'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10509'
 id: 10510 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10510'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10510'
 id: 10511 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '10511'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10511'
 id: 10512 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '10512'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10512'
 id: 10513 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '10513'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10513'
 id: 10514 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10514'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10514'
 id: 10515 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10515'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10515'
 id: 10516 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '10516'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10516'
 id: 10517 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '10517'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10517'
 id: 10518 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10518'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10518'
 id: 10519 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10519'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10519'
 id: 10520 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10520'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10520'
 id: 10521 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10521'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10521'
 id: 10522 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10522'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10522'
 id: 10523 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10523'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10523'
 id: 10524 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '10524'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10524'
 id: 10525 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '10525'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10525'
 id: 10526 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10526'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10526'
 id: 10527 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '10527'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10527'
 id: 10528 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '10528'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10528'
 id: 10529 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '10529'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10529'
 id: 10530 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '10530'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10530'
 id: 10531 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10531'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10531'
 id: 10532 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '10532'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10532'
 id: 10533 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '10533'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10533'
 id: 10534 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '10534'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10534'
 id: 10535 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10535'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10535'
 id: 10536 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10536'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10536'
 id: 10537 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10537'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10537'
 id: 10538 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '10538'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10538'
 id: 10539 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10539'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10539'
 id: 10540 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10540'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10540'
 id: 10541 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '10541'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10541'
 id: 10542 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '10542'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10542'
 id: 10543 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10543'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10543'
 id: 10544 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10544'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10544'
 id: 10545 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10545'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10545'
 id: 10546 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10546'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10546'
 id: 10547 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '10547'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10547'
 id: 10548 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '10548'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10548'
 id: 10549 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10549'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10549'
 id: 10550 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '10550'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10550'
 id: 10551 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '10551'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10551'
 id: 10552 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10552'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10552'
 id: 10553 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10553'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10553'
 id: 10554 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '10554'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10554'
 id: 10555 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '10555'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10555'
 id: 10556 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10556'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10556'
 id: 10557 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '10557'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10557'
 id: 10558 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10558'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10558'
 id: 10559 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10559'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10559'
 id: 10560 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '10560'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10560'
 id: 10561 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10561'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10561'
 id: 10562 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10562'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10562'
 id: 10563 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '10563'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10563'
 id: 10564 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '10564'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10564'
 id: 10565 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10565'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10565'
 id: 10566 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10566'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10566'
 id: 10567 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '10567'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10567'
 id: 10568 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10568'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10568'
 id: 10569 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10569'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10569'
 id: 10570 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10570'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10570'
 id: 10571 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10571'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10571'
 id: 10572 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10572'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10572'
 id: 10573 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10573'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10573'
 id: 10574 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10574'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10574'
 id: 10575 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10575'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10575'
 id: 10576 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '10576'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10576'
 id: 10577 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '10577'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10577'
 id: 10578 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10578'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10578'
 id: 10579 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10579'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10579'
 id: 10580 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10580'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10580'
 id: 10581 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10581'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10581'
 id: 10582 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '10582'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10582'
 id: 10583 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '10583'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10583'
 id: 10584 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10584'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10584'
 id: 10585 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '10585'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10585'
 id: 10586 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10586'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10586'
 id: 10587 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '10587'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10587'
 id: 10588 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10588'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10588'
 id: 10589 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '10589'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10589'
 id: 10590 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10590'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10590'
 id: 10591 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10591'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10591'
 id: 10592 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10592'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10592'
 id: 10593 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10593'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10593'
 id: 10594 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10594'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10594'
 id: 10595 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '10595'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10595'
 id: 10596 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10596'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10596'
 id: 10597 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10597'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10597'
 id: 10598 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '10598'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10598'
 id: 10599 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10599'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10599'
 id: 10600 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10600'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10600'
 id: 10601 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10601'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10601'
 id: 10602 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '10602'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10602'
 id: 10603 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '10603'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10603'
 id: 10604 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10604'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10604'
 id: 10605 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10605'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10605'
 id: 10606 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10606'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10606'
 id: 10607 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '10607'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10607'
 id: 10608 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '10608'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10608'
 id: 10609 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10609'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10609'
 id: 10610 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10610'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10610'
 id: 10611 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '10611'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10611'
 id: 10612 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10612'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10612'
 id: 10613 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10613'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10613'
 id: 10614 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '10614'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10614'
 id: 10615 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '10615'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10615'
 id: 10616 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10616'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10616'
 id: 10617 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '10617'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10617'
 id: 10618 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '10618'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10618'
 id: 10619 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10619'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10619'
 id: 10620 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10620'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10620'
 id: 10621 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '10621'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10621'
 id: 10622 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '10622'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10622'
 id: 10623 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10623'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10623'
 id: 10624 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10624'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10624'
 id: 10625 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10625'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10625'
 id: 10626 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10626'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10626'
 id: 10627 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '10627'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10627'
 id: 10628 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10628'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10628'
 id: 10629 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '10629'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10629'
 id: 10630 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '10630'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10630'
 id: 10631 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10631'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10631'
 id: 10632 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10632'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10632'
 id: 10633 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10633'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10633'
 id: 10634 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10634'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10634'
 id: 10635 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '10635'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10635'
 id: 10636 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10636'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10636'
 id: 10637 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10637'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10637'
 id: 10638 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10638'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10638'
 id: 10639 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10639'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10639'
 id: 10640 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10640'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10640'
 id: 10641 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10641'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10641'
 id: 10642 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10642'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10642'
 id: 10643 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '10643'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10643'
 id: 10644 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '10644'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10644'
 id: 10645 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10645'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10645'
 id: 10646 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10646'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10646'
 id: 10647 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10647'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10647'
 id: 10648 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '10648'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10648'
 id: 10649 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10649'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10649'
 id: 10650 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10650'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10650'
 id: 10651 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '10651'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10651'
 id: 10652 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10652'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10652'
 id: 10653 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10653'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10653'
 id: 10654 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '10654'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10654'
 id: 10655 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10655'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10655'
 id: 10656 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10656'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10656'
 id: 10657 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10657'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10657'
 id: 10658 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '10658'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10658'
 id: 10659 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '10659'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10659'
 id: 10660 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '10660'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10660'
 id: 10661 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10661'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10661'
 id: 10662 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '10662'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10662'
 id: 10663 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '10663'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10663'
 id: 10664 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10664'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10664'
 id: 10665 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10665'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10665'
 id: 10666 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '10666'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10666'
 id: 10667 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '10667'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10667'
 id: 10668 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10668'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10668'
 id: 10669 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10669'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10669'
 id: 10670 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '10670'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10670'
 id: 10671 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '10671'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10671'
 id: 10672 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10672'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10672'
 id: 10673 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '10673'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10673'
 id: 10674 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '10674'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10674'
 id: 10675 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '10675'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10675'
 id: 10676 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '10676'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10676'
 id: 10677 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '10677'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10677'
 id: 10678 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10678'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10678'
 id: 10679 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '10679'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10679'
 id: 10680 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '10680'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10680'
 id: 10681 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '10681'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10681'
 id: 10682 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10682'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10682'
 id: 10683 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10683'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10683'
 id: 10684 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10684'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10684'
 id: 10685 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '10685'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10685'
 id: 10686 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '10686'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10686'
 id: 10687 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10687'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10687'
 id: 10688 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10688'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10688'
 id: 10689 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10689'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10689'
 id: 10690 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10690'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10690'
 id: 10691 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10691'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10691'
 id: 10692 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10692'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10692'
 id: 10693 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '10693'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10693'
 id: 10694 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '10694'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10694'
 id: 10695 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '10695'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10695'
 id: 10696 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10696'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10696'
 id: 10697 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '10697'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10697'
 id: 10698 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '10698'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10698'
 id: 10699 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10699'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10699'
 id: 10700 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '10700'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10700'
 id: 10701 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '10701'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10701'
 id: 10702 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '10702'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10702'
 id: 10703 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10703'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10703'
 id: 10704 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '10704'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10704'
 id: 10705 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10705'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10705'
 id: 10706 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10706'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10706'
 id: 10707 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '10707'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10707'
 id: 10708 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '10708'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10708'
 id: 10709 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '10709'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10709'
 id: 10710 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10710'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10710'
 id: 10711 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10711'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10711'
 id: 10712 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10712'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10712'
 id: 10713 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10713'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10713'
 id: 10714 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10714'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10714'
 id: 10715 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10715'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10715'
 id: 10716 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '10716'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10716'
 id: 10717 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '10717'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10717'
 id: 10718 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10718'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10718'
 id: 10719 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '10719'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10719'
 id: 10720 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10720'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10720'
 id: 10721 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '10721'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10721'
 id: 10722 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '10722'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10722'
 id: 10723 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10723'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10723'
 id: 10724 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10724'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10724'
 id: 10725 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '10725'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10725'
 id: 10726 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10726'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10726'
 id: 10727 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10727'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10727'
 id: 10728 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '10728'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10728'
 id: 10729 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '10729'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10729'
 id: 10730 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '10730'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10730'
 id: 10731 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '10731'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10731'
 id: 10732 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10732'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10732'
 id: 10733 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '10733'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10733'
 id: 10734 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '10734'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10734'
 id: 10735 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10735'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10735'
 id: 10736 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10736'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10736'
 id: 10737 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '10737'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10737'
 id: 10738 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10738'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10738'
 id: 10739 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10739'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10739'
 id: 10740 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10740'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10740'
 id: 10741 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10741'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10741'
 id: 10742 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '10742'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10742'
 id: 10743 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '10743'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10743'
 id: 10744 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10744'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10744'
 id: 10745 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '10745'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10745'
 id: 10746 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10746'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10746'
 id: 10747 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10747'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10747'
 id: 10748 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '10748'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10748'
 id: 10749 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '10749'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10749'
 id: 10750 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10750'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10750'
 id: 10751 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10751'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10751'
 id: 10752 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10752'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10752'
 id: 10753 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '10753'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10753'
 id: 10754 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '10754'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10754'
 id: 10755 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10755'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10755'
 id: 10756 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '10756'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10756'
 id: 10757 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10757'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10757'
 id: 10758 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '10758'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10758'
 id: 10759 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10759'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10759'
 id: 10760 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '10760'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10760'
 id: 10761 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10761'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10761'
 id: 10762 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10762'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10762'
 id: 10763 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10763'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10763'
 id: 10764 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '10764'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10764'
 id: 10765 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10765'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10765'
 id: 10766 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '10766'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10766'
 id: 10767 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '10767'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10767'
 id: 10768 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10768'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10768'
 id: 10769 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10769'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10769'
 id: 10770 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10770'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10770'
 id: 10771 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10771'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10771'
 id: 10772 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '10772'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10772'
 id: 10773 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10773'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10773'
 id: 10774 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10774'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10774'
 id: 10775 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '10775'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10775'
 id: 10776 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10776'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10776'
 id: 10777 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10777'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10777'
 id: 10778 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10778'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10778'
 id: 10779 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10779'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10779'
 id: 10780 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10780'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10780'
 id: 10781 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '10781'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10781'
 id: 10782 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10782'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10782'
 id: 10783 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10783'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10783'
 id: 10784 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10784'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10784'
 id: 10785 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '10785'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10785'
 id: 10786 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '10786'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10786'
 id: 10787 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10787'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10787'
 id: 10788 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10788'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10788'
 id: 10789 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '10789'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10789'
 id: 10790 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10790'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10790'
 id: 10791 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10791'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10791'
 id: 10792 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10792'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10792'
 id: 10793 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '10793'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10793'
 id: 10794 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '10794'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10794'
 id: 10795 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10795'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10795'
 id: 10796 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '10796'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10796'
 id: 10797 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '10797'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10797'
 id: 10798 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '10798'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10798'
 id: 10799 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '10799'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10799'
 id: 10800 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '10800'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10800'
 id: 10801 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10801'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10801'
 id: 10802 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '10802'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10802'
 id: 10803 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '10803'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10803'
 id: 10804 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10804'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10804'
 id: 10805 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '10805'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10805'
 id: 10806 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '10806'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10806'
 id: 10807 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10807'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10807'
 id: 10808 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '10808'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10808'
 id: 10809 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '10809'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10809'
 id: 10810 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10810'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10810'
 id: 10811 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10811'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10811'
 id: 10812 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10812'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10812'
 id: 10813 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10813'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10813'
 id: 10814 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '10814'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10814'
 id: 10815 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '10815'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10815'
 id: 10816 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10816'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10816'
 id: 10817 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '10817'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10817'
 id: 10818 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10818'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10818'
 id: 10819 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '10819'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10819'
 id: 10820 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10820'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10820'
 id: 10821 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10821'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10821'
 id: 10822 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10822'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10822'
 id: 10823 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '10823'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10823'
 id: 10824 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10824'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10824'
 id: 10825 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10825'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10825'
 id: 10826 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10826'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10826'
 id: 10827 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '10827'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10827'
 id: 10828 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '10828'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10828'
 id: 10829 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '10829'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10829'
 id: 10830 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '10830'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10830'
 id: 10831 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '10831'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10831'
 id: 10832 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10832'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10832'
 id: 10833 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '10833'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10833'
 id: 10834 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10834'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10834'
 id: 10835 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '10835'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10835'
 id: 10836 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10836'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10836'
 id: 10837 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10837'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10837'
 id: 10838 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10838'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10838'
 id: 10839 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '10839'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10839'
 id: 10840 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10840'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10840'
 id: 10841 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '10841'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10841'
 id: 10842 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10842'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10842'
 id: 10843 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10843'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10843'
 id: 10844 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '10844'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10844'
 id: 10845 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10845'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10845'
 id: 10846 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '10846'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10846'
 id: 10847 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10847'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10847'
 id: 10848 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10848'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10848'
 id: 10849 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '10849'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10849'
 id: 10850 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10850'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10850'
 id: 10851 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '10851'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10851'
 id: 10852 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '10852'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10852'
 id: 10853 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10853'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10853'
 id: 10854 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10854'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10854'
 id: 10855 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '10855'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10855'
 id: 10856 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10856'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10856'
 id: 10857 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10857'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10857'
 id: 10858 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10858'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10858'
 id: 10859 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '10859'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10859'
 id: 10860 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10860'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10860'
 id: 10861 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '10861'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10861'
 id: 10862 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '10862'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10862'
 id: 10863 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '10863'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10863'
 id: 10864 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10864'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10864'
 id: 10865 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10865'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10865'
 id: 10866 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10866'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10866'
 id: 10867 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10867'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10867'
 id: 10868 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10868'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10868'
 id: 10869 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '10869'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10869'
 id: 10870 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10870'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10870'
 id: 10871 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10871'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10871'
 id: 10872 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10872'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10872'
 id: 10873 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10873'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10873'
 id: 10874 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10874'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10874'
 id: 10875 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10875'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10875'
 id: 10876 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10876'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10876'
 id: 10877 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10877'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10877'
 id: 10878 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '10878'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10878'
 id: 10879 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10879'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10879'
 id: 10880 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10880'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10880'

 id: 10881 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '10881'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10881'
 id: 10882 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '10882'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10882'
 id: 10883 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '10883'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10883'
 id: 10884 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '10884'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10884'
 id: 10885 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '10885'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10885'
 id: 10886 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10886'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10886'
 id: 10887 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '10887'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10887'
 id: 10888 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '10888'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10888'
 id: 10889 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10889'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10889'
 id: 10890 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10890'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10890'
 id: 10891 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10891'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10891'
 id: 10892 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '10892'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10892'
 id: 10893 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '10893'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10893'
 id: 10894 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '10894'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10894'
 id: 10895 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '10895'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10895'
 id: 10896 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10896'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10896'
 id: 10897 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '10897'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10897'
 id: 10898 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '10898'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10898'
 id: 10899 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '10899'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10899'
 id: 10900 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10900'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10900'
 id: 10901 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '10901'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10901'
 id: 10902 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '10902'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10902'
 id: 10903 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '10903'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10903'
 id: 10904 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10904'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10904'
 id: 10905 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10905'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10905'
 id: 10906 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10906'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10906'
 id: 10907 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10907'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10907'
 id: 10908 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10908'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10908'
 id: 10909 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '10909'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10909'
 id: 10910 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '10910'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10910'
 id: 10911 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '10911'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10911'
 id: 10912 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10912'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10912'
 id: 10913 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '10913'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10913'
 id: 10914 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '10914'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10914'
 id: 10915 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '10915'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10915'
 id: 10916 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10916'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10916'
 id: 10917 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '10917'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10917'
 id: 10918 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '10918'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10918'
 id: 10919 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10919'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10919'
 id: 10920 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10920'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10920'
 id: 10921 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10921'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10921'
 id: 10922 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '10922'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10922'
 id: 10923 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10923'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10923'
 id: 10924 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '10924'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10924'
 id: 10925 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '10925'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10925'
 id: 10926 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '10926'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10926'
 id: 10927 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '10927'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10927'
 id: 10928 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10928'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10928'
 id: 10929 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10929'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10929'
 id: 10930 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10930'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10930'
 id: 10931 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '10931'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10931'
 id: 10932 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10932'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10932'
 id: 10933 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '10933'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10933'
 id: 10934 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '10934'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10934'
 id: 10935 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10935'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10935'
 id: 10936 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '10936'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10936'
 id: 10937 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '10937'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10937'
 id: 10938 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10938'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10938'
 id: 10939 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10939'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10939'
 id: 10940 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '10940'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10940'
 id: 10941 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10941'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10941'
 id: 10942 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '10942'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10942'
 id: 10943 // word: 16
UPDATE job_vacancies SET domain_id =  '16' where raw_id = '10943'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10943'
 id: 10944 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '10944'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10944'
 id: 10945 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10945'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10945'
 id: 10946 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10946'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10946'
 id: 10947 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10947'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10947'
 id: 10948 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10948'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10948'
 id: 10949 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10949'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10949'
 id: 10950 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '10950'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10950'
 id: 10951 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '10951'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10951'
 id: 10952 // word: 16
UPDATE job_vacancies SET domain_id =  '16' where raw_id = '10952'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10952'
 id: 10953 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '10953'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10953'
 id: 10954 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10954'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10954'
 id: 10955 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10955'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10955'
 id: 10956 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10956'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10956'
 id: 10957 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10957'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10957'
 id: 10958 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '10958'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10958'
 id: 10959 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10959'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10959'
 id: 10960 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '10960'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10960'
 id: 10961 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '10961'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10961'
 id: 10962 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10962'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10962'
 id: 10963 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '10963'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10963'
 id: 10964 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10964'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10964'
 id: 10965 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10965'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10965'
 id: 10966 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '10966'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10966'
 id: 10967 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10967'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10967'
 id: 10968 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '10968'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10968'
 id: 10969 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10969'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10969'
 id: 10970 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '10970'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10970'
 id: 10971 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10971'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10971'
 id: 10972 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '10972'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10972'
 id: 10973 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10973'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10973'
 id: 10974 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10974'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10974'
 id: 10975 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10975'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10975'
 id: 10976 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '10976'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10976'
 id: 10977 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10977'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10977'
 id: 10978 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10978'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10978'
 id: 10979 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '10979'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10979'
 id: 10980 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '10980'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10980'
 id: 10981 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '10981'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10981'
 id: 10982 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10982'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10982'
 id: 10983 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '10983'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10983'
 id: 10984 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '10984'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10984'
 id: 10985 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '10985'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10985'
 id: 10986 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '10986'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10986'
 id: 10987 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '10987'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10987'
 id: 10988 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '10988'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10988'
 id: 10989 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '10989'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10989'
 id: 10990 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '10990'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10990'
 id: 10991 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '10991'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10991'
 id: 10992 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '10992'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10992'
 id: 10993 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '10993'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10993'
 id: 10994 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '10994'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10994'
 id: 10995 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '10995'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10995'
 id: 10996 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '10996'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10996'
 id: 10997 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '10997'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10997'
 id: 10998 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '10998'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10998'
 id: 10999 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '10999'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '10999'
 id: 11000 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '11000'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11000'
 id: 11001 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '11001'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11001'
 id: 11002 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '11002'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11002'
 id: 11003 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '11003'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11003'
 id: 11004 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11004'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11004'
 id: 11005 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11005'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11005'
 id: 11006 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '11006'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11006'
 id: 11007 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11007'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11007'
 id: 11008 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '11008'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11008'
 id: 11009 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '11009'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11009'
 id: 11010 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11010'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11010'
 id: 11011 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11011'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11011'
 id: 11012 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11012'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11012'
 id: 11013 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '11013'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11013'
 id: 11014 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '11014'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11014'
 id: 11015 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11015'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11015'
 id: 11016 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11016'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11016'
 id: 11017 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11017'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11017'
 id: 11018 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '11018'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11018'
 id: 11019 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11019'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11019'
 id: 11020 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11020'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11020'
 id: 11021 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11021'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11021'
 id: 11022 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11022'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11022'
 id: 11023 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11023'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11023'
 id: 11024 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11024'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11024'
 id: 11025 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '11025'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11025'
 id: 11026 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '11026'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11026'
 id: 11027 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '11027'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11027'
 id: 11028 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '11028'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11028'
 id: 11029 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '11029'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11029'
 id: 11030 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '11030'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11030'
 id: 11031 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '11031'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11031'
 id: 11032 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11032'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11032'
 id: 11033 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11033'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11033'
 id: 11034 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11034'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11034'
 id: 11035 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11035'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11035'
 id: 11036 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11036'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11036'
 id: 11037 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '11037'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11037'
 id: 11038 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '11038'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11038'
 id: 11039 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '11039'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11039'
 id: 11040 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '11040'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11040'
 id: 11041 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11041'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11041'
 id: 11042 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11042'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11042'
 id: 11043 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '11043'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11043'
 id: 11044 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '11044'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11044'
 id: 11045 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11045'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11045'
 id: 11046 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '11046'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11046'
 id: 11047 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '11047'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11047'
 id: 11048 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '11048'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11048'
 id: 11049 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '11049'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11049'
 id: 11050 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11050'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11050'
 id: 11051 // word: 50
UPDATE job_vacancies SET domain_id =  '50' where raw_id = '11051'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11051'
 id: 11052 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11052'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11052'
 id: 11053 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '11053'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11053'
 id: 11054 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11054'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11054'
 id: 11055 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11055'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11055'
 id: 11056 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '11056'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11056'
 id: 11057 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '11057'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11057'
 id: 11058 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '11058'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11058'
 id: 11059 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11059'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11059'
 id: 11060 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '11060'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11060'
 id: 11061 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '11061'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11061'
 id: 11062 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11062'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11062'
 id: 11063 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11063'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11063'
 id: 11064 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '11064'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11064'
 id: 11065 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11065'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11065'
 id: 11066 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11066'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11066'
 id: 11067 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11067'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11067'
 id: 11068 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11068'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11068'
 id: 11069 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '11069'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11069'
 id: 11070 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '11070'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11070'
 id: 11071 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '11071'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11071'
 id: 11072 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11072'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11072'
 id: 11073 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '11073'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11073'
 id: 11074 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11074'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11074'
 id: 11075 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11075'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11075'
 id: 11076 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11076'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11076'
 id: 11077 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '11077'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11077'
 id: 11078 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11078'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11078'
 id: 11079 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11079'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11079'
 id: 11080 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '11080'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11080'
 id: 11081 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11081'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11081'
 id: 11082 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11082'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11082'
 id: 11083 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '11083'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11083'
 id: 11084 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '11084'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11084'
 id: 11085 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11085'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11085'
 id: 11086 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '11086'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11086'
 id: 11087 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11087'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11087'
 id: 11088 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11088'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11088'
 id: 11089 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11089'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11089'
 id: 11090 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '11090'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11090'
 id: 11091 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11091'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11091'
 id: 11092 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '11092'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11092'
 id: 11093 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '11093'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11093'
 id: 11094 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11094'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11094'
 id: 11095 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11095'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11095'
 id: 11096 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '11096'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11096'
 id: 11097 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '11097'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11097'
 id: 11098 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11098'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11098'
 id: 11099 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '11099'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11099'
 id: 11100 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11100'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11100'
 id: 11101 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '11101'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11101'
 id: 11102 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11102'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11102'
 id: 11103 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11103'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11103'
 id: 11104 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11104'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11104'
 id: 11105 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11105'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11105'
 id: 11106 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11106'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11106'
 id: 11107 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11107'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11107'
 id: 11108 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11108'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11108'
 id: 11109 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '11109'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11109'
 id: 11110 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11110'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11110'
 id: 11111 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '11111'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11111'
 id: 11112 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11112'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11112'
 id: 11113 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11113'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11113'
 id: 11114 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '11114'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11114'
 id: 11115 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11115'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11115'
 id: 11116 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11116'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11116'
 id: 11117 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11117'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11117'
 id: 11118 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '11118'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11118'
 id: 11119 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11119'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11119'
 id: 11120 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11120'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11120'
 id: 11121 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11121'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11121'
 id: 11122 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '11122'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11122'
 id: 11123 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '11123'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11123'
 id: 11124 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11124'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11124'
 id: 11125 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11125'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11125'
 id: 11126 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11126'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11126'
 id: 11127 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11127'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11127'
 id: 11128 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11128'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11128'
 id: 11129 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '11129'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11129'
 id: 11130 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11130'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11130'
 id: 11131 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '11131'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11131'
 id: 11132 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '11132'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11132'
 id: 11133 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '11133'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11133'
 id: 11134 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '11134'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11134'
 id: 11135 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11135'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11135'
 id: 11136 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '11136'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11136'
 id: 11137 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11137'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11137'
 id: 11138 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11138'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11138'
 id: 11139 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11139'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11139'
 id: 11140 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11140'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11140'
 id: 11141 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11141'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11141'
 id: 11142 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11142'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11142'
 id: 11143 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '11143'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11143'
 id: 11144 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11144'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11144'
 id: 11145 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '11145'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11145'
 id: 11146 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11146'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11146'
 id: 11147 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '11147'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11147'
 id: 11148 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '11148'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11148'
 id: 11149 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11149'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11149'
 id: 11150 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11150'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11150'
 id: 11151 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '11151'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11151'
 id: 11152 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '11152'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11152'
 id: 11153 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '11153'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11153'
 id: 11154 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '11154'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11154'
 id: 11155 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11155'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11155'
 id: 11156 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11156'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11156'
 id: 11157 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11157'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11157'
 id: 11158 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11158'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11158'
 id: 11159 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11159'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11159'
 id: 11160 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '11160'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11160'
 id: 11161 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '11161'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11161'
 id: 11162 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11162'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11162'
 id: 11163 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11163'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11163'
 id: 11164 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11164'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11164'
 id: 11165 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '11165'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11165'
 id: 11166 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '11166'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11166'
 id: 11167 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11167'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11167'
 id: 11168 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '11168'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11168'
 id: 11169 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '11169'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11169'
 id: 11170 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '11170'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11170'
 id: 11171 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11171'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11171'
 id: 11172 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '11172'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11172'
 id: 11173 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '11173'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11173'
 id: 11174 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '11174'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11174'
 id: 11175 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11175'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11175'
 id: 11176 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '11176'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11176'
 id: 11177 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '11177'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11177'
 id: 11178 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11178'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11178'
 id: 11179 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11179'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11179'
 id: 11180 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11180'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11180'
 id: 11181 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11181'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11181'
 id: 11182 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11182'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11182'
 id: 11183 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11183'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11183'
 id: 11184 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '11184'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11184'
 id: 11185 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '11185'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11185'
 id: 11186 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '11186'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11186'
 id: 11187 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '11187'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11187'
 id: 11188 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11188'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11188'
 id: 11189 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11189'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11189'
 id: 11190 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11190'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11190'
 id: 11191 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '11191'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11191'
 id: 11192 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '11192'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11192'
 id: 11193 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11193'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11193'
 id: 11194 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '11194'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11194'
 id: 11195 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '11195'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11195'
 id: 11196 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '11196'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11196'
 id: 11197 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '11197'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11197'
 id: 11198 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11198'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11198'
 id: 11199 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '11199'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11199'
 id: 11200 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '11200'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11200'
 id: 11201 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '11201'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11201'
 id: 11202 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '11202'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11202'
 id: 11203 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '11203'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11203'
 id: 11204 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11204'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11204'
 id: 11205 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '11205'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11205'
 id: 11206 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '11206'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11206'
 id: 11207 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11207'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11207'
 id: 11208 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11208'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11208'
 id: 11209 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11209'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11209'
 id: 11210 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '11210'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11210'
 id: 11211 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '11211'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11211'
 id: 11212 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '11212'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11212'
 id: 11213 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '11213'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11213'
 id: 11214 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11214'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11214'
 id: 11215 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11215'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11215'
 id: 11216 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '11216'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11216'
 id: 11217 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11217'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11217'
 id: 11218 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11218'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11218'
 id: 11219 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '11219'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11219'
 id: 11220 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '11220'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11220'
 id: 11221 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11221'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11221'
 id: 11222 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '11222'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11222'
 id: 11223 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11223'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11223'
 id: 11224 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '11224'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11224'
 id: 11225 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11225'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11225'
 id: 11226 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11226'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11226'
 id: 11227 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '11227'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11227'
 id: 11228 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11228'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11228'
 id: 11229 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '11229'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11229'
 id: 11230 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11230'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11230'
 id: 11231 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11231'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11231'
 id: 11232 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '11232'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11232'
 id: 11233 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11233'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11233'
 id: 11234 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11234'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11234'
 id: 11235 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11235'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11235'
 id: 11236 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11236'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11236'

 id: 11237 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '11237'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11237'
 id: 11238 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '11238'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11238'
 id: 11239 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11239'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11239'
 id: 11240 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '11240'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11240'
 id: 11241 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '11241'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11241'
 id: 11242 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '11242'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11242'
 id: 11243 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11243'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11243'
 id: 11244 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11244'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11244'
 id: 11245 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11245'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11245'
 id: 11246 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11246'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11246'
 id: 11247 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11247'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11247'
 id: 11248 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11248'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11248'
 id: 11249 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '11249'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11249'
 id: 11250 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '11250'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11250'
 id: 11251 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11251'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11251'
 id: 11252 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '11252'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11252'
 id: 11253 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11253'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11253'
 id: 11254 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '11254'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11254'
 id: 11255 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11255'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11255'
 id: 11256 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '11256'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11256'
 id: 11257 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '11257'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11257'
 id: 11258 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11258'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11258'
 id: 11259 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11259'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11259'
 id: 11260 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11260'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11260'
 id: 11261 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '11261'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11261'
 id: 11262 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11262'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11262'
 id: 11263 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11263'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11263'
 id: 11264 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '11264'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11264'
 id: 11265 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '11265'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11265'
 id: 11266 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '11266'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11266'
 id: 11267 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '11267'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11267'
 id: 11268 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '11268'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11268'
 id: 11269 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '11269'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11269'
 id: 11270 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11270'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11270'
 id: 11271 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11271'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11271'
 id: 11272 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11272'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11272'
 id: 11273 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11273'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11273'
 id: 11274 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11274'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11274'
 id: 11275 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '11275'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11275'
 id: 11276 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11276'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11276'
 id: 11277 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '11277'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11277'
 id: 11278 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '11278'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11278'
 id: 11279 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11279'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11279'
 id: 11280 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11280'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11280'
 id: 11281 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '11281'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11281'
 id: 11282 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11282'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11282'
 id: 11283 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '11283'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11283'
 id: 11284 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '11284'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11284'
 id: 11285 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11285'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11285'
 id: 11286 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '11286'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11286'
 id: 11287 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11287'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11287'
 id: 11288 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '11288'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11288'
 id: 11289 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '11289'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11289'
 id: 11290 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '11290'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11290'
 id: 11291 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '11291'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11291'
 id: 11292 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11292'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11292'
 id: 11293 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11293'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11293'
 id: 11294 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11294'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11294'
 id: 11295 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '11295'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11295'
 id: 11296 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11296'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11296'
 id: 11297 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11297'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11297'
 id: 11298 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11298'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11298'
 id: 11299 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '11299'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11299'
 id: 11300 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11300'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11300'
 id: 11301 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11301'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11301'
 id: 11302 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '11302'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11302'
 id: 11303 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '11303'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11303'
 id: 11304 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11304'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11304'
 id: 11305 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11305'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11305'
 id: 11306 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '11306'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11306'
 id: 11307 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11307'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11307'
 id: 11308 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '11308'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11308'
 id: 11309 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11309'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11309'
 id: 11310 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11310'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11310'
 id: 11311 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '11311'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11311'
 id: 11312 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '11312'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11312'
 id: 11313 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '11313'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11313'
 id: 11314 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11314'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11314'
 id: 11315 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11315'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11315'
 id: 11316 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11316'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11316'
 id: 11317 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11317'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11317'
 id: 11318 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11318'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11318'
 id: 11319 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '11319'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11319'
 id: 11320 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11320'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11320'
 id: 11321 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11321'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11321'
 id: 11322 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '11322'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11322'
 id: 11323 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '11323'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11323'
 id: 11324 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '11324'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11324'
 id: 11325 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '11325'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11325'
 id: 11326 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11326'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11326'
 id: 11327 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '11327'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11327'
 id: 11328 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '11328'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11328'
 id: 11329 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '11329'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11329'
 id: 11330 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '11330'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11330'
 id: 11331 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11331'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11331'
 id: 11332 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11332'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11332'
 id: 11333 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11333'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11333'
 id: 11334 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '11334'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11334'
 id: 11335 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '11335'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11335'
 id: 11336 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11336'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11336'
 id: 11337 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11337'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11337'
 id: 11338 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '11338'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11338'
 id: 11339 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '11339'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11339'
 id: 11340 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11340'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11340'
 id: 11341 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11341'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11341'
 id: 11342 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11342'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11342'
 id: 11343 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '11343'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11343'
 id: 11344 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '11344'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11344'
 id: 11345 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '11345'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11345'
 id: 11346 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '11346'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11346'
 id: 11347 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '11347'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11347'
 id: 11348 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '11348'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11348'
 id: 11349 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '11349'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11349'
 id: 11350 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11350'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11350'
 id: 11351 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '11351'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11351'
 id: 11352 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '11352'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11352'
 id: 11353 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11353'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11353'
 id: 11354 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '11354'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11354'
 id: 11355 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '11355'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11355'
 id: 11356 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11356'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11356'
 id: 11357 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11357'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11357'
 id: 11358 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '11358'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11358'
 id: 11359 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '11359'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11359'
 id: 11360 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '11360'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11360'
 id: 11361 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '11361'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11361'
 id: 11362 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11362'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11362'
 id: 11363 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '11363'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11363'
 id: 11364 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '11364'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11364'
 id: 11365 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11365'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11365'
 id: 11366 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '11366'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11366'
 id: 11367 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '11367'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11367'
 id: 11368 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '11368'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11368'
 id: 11369 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11369'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11369'
 id: 11370 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11370'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11370'
 id: 11371 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11371'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11371'
 id: 11372 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11372'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11372'
 id: 11373 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11373'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11373'
 id: 11374 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '11374'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11374'
 id: 11375 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '11375'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11375'
 id: 11376 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '11376'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11376'
 id: 11377 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '11377'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11377'
 id: 11378 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11378'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11378'
 id: 11379 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '11379'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11379'
 id: 11380 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '11380'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11380'
 id: 11381 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11381'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11381'
 id: 11382 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '11382'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11382'
 id: 11383 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '11383'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11383'
 id: 11384 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '11384'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11384'
 id: 11385 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '11385'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11385'
 id: 11386 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11386'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11386'
 id: 11387 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '11387'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11387'
 id: 11388 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '11388'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11388'
 id: 11389 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '11389'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11389'
 id: 11390 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '11390'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11390'
 id: 11391 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11391'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11391'
 id: 11392 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '11392'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11392'
 id: 11393 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11393'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11393'
 id: 11394 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11394'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11394'
 id: 11395 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '11395'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11395'
 id: 11396 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11396'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11396'
 id: 11397 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '11397'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11397'
 id: 11398 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '11398'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11398'
 id: 11399 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '11399'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11399'
 id: 11400 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11400'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11400'
 id: 11401 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11401'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11401'
 id: 11402 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11402'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11402'
 id: 11403 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '11403'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11403'
 id: 11404 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11404'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11404'
 id: 11405 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11405'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11405'
 id: 11406 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11406'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11406'
 id: 11407 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '11407'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11407'
 id: 11408 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11408'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11408'
 id: 11409 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '11409'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11409'
 id: 11410 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11410'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11410'
 id: 11411 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11411'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11411'
 id: 11412 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11412'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11412'
 id: 11413 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '11413'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11413'
 id: 11414 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11414'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11414'
 id: 11415 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '11415'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11415'
 id: 11416 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '11416'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11416'
 id: 11417 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11417'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11417'
 id: 11418 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '11418'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11418'
 id: 11419 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11419'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11419'
 id: 11420 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '11420'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11420'
 id: 11421 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11421'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11421'
 id: 11422 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '11422'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11422'
 id: 11423 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '11423'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11423'
 id: 11424 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11424'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11424'
 id: 11425 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '11425'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11425'
 id: 11426 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11426'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11426'
 id: 11427 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11427'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11427'
 id: 11428 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '11428'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11428'
 id: 11429 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '11429'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11429'
 id: 11430 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '11430'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11430'
 id: 11431 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '11431'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11431'
 id: 11432 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11432'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11432'
 id: 11433 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '11433'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11433'
 id: 11434 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11434'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11434'
 id: 11435 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '11435'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11435'
 id: 11436 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '11436'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11436'
 id: 11437 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11437'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11437'
 id: 11438 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11438'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11438'
 id: 11439 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '11439'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11439'
 id: 11440 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11440'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11440'
 id: 11441 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11441'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11441'
 id: 11442 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '11442'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11442'
 id: 11443 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '11443'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11443'
 id: 11444 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11444'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11444'
 id: 11445 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '11445'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11445'
 id: 11446 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11446'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11446'
 id: 11447 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '11447'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11447'
 id: 11448 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11448'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11448'
 id: 11449 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '11449'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11449'
 id: 11450 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '11450'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11450'
 id: 11451 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '11451'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11451'
 id: 11452 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '11452'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11452'
 id: 11453 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11453'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11453'
 id: 11454 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11454'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11454'
 id: 11455 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11455'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11455'
 id: 11456 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '11456'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11456'
 id: 11457 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11457'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11457'
 id: 11458 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '11458'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11458'
 id: 11459 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11459'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11459'
 id: 11460 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '11460'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11460'
 id: 11461 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11461'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11461'
 id: 11462 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '11462'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11462'
 id: 11463 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11463'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11463'
 id: 11464 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11464'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11464'
 id: 11465 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '11465'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11465'
 id: 11466 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '11466'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11466'
 id: 11467 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '11467'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11467'
 id: 11468 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '11468'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11468'
 id: 11469 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '11469'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11469'
 id: 11470 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '11470'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11470'
 id: 11471 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11471'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11471'
 id: 11472 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '11472'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11472'
 id: 11473 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11473'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11473'
 id: 11474 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11474'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11474'
 id: 11475 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '11475'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11475'
 id: 11476 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11476'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11476'
 id: 11477 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '11477'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11477'
 id: 11478 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11478'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11478'
 id: 11479 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11479'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11479'
 id: 11480 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '11480'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11480'
 id: 11481 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11481'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11481'
 id: 11482 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '11482'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11482'
 id: 11483 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11483'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11483'
 id: 11484 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '11484'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11484'
 id: 11485 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11485'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11485'
 id: 11486 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '11486'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11486'
 id: 11487 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11487'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11487'
 id: 11488 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '11488'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11488'
 id: 11489 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '11489'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11489'
 id: 11490 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11490'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11490'
 id: 11491 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '11491'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11491'
 id: 11492 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11492'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11492'
 id: 11493 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '11493'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11493'
 id: 11494 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11494'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11494'
 id: 11495 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11495'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11495'
 id: 11496 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '11496'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11496'
 id: 11497 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11497'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11497'
 id: 11498 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11498'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11498'
 id: 11499 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '11499'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11499'
 id: 11500 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11500'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11500'
 id: 11501 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '11501'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11501'
 id: 11502 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11502'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11502'
 id: 11503 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11503'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11503'
 id: 11504 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11504'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11504'
 id: 11505 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '11505'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11505'
 id: 11506 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11506'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11506'
 id: 11507 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '11507'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11507'
 id: 11508 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11508'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11508'
 id: 11509 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11509'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11509'
 id: 11510 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11510'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11510'
 id: 11511 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '11511'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11511'
 id: 11512 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '11512'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11512'
 id: 11513 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11513'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11513'
 id: 11514 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11514'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11514'
 id: 11515 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '11515'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11515'
 id: 11516 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11516'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11516'
 id: 11517 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11517'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11517'
 id: 11518 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11518'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11518'
 id: 11519 // word: 52
UPDATE job_vacancies SET domain_id =  '52' where raw_id = '11519'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11519'
 id: 11520 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '11520'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11520'
 id: 11521 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '11521'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11521'
 id: 11522 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11522'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11522'
 id: 11523 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '11523'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11523'
 id: 11524 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11524'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11524'
 id: 11525 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '11525'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11525'
 id: 11526 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11526'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11526'
 id: 11527 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '11527'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11527'
 id: 11528 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '11528'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11528'
 id: 11529 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '11529'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11529'
 id: 11530 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11530'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11530'
 id: 11531 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11531'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11531'
 id: 11532 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11532'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11532'
 id: 11533 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '11533'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11533'
 id: 11534 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11534'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11534'
 id: 11535 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11535'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11535'
 id: 11536 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '11536'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11536'
 id: 11537 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11537'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11537'
 id: 11538 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11538'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11538'
 id: 11539 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11539'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11539'
 id: 11540 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '11540'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11540'
 id: 11541 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '11541'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11541'
 id: 11542 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11542'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11542'
 id: 11543 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11543'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11543'
 id: 11544 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11544'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11544'
 id: 11545 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '11545'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11545'
 id: 11546 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '11546'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11546'
 id: 11547 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11547'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11547'
 id: 11548 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11548'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11548'
 id: 11549 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '11549'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11549'
 id: 11550 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11550'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11550'
 id: 11551 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11551'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11551'
 id: 11552 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '11552'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11552'
 id: 11553 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11553'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11553'
 id: 11554 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '11554'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11554'
 id: 11555 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11555'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11555'
 id: 11556 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '11556'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11556'
 id: 11557 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '11557'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11557'
 id: 11558 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11558'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11558'
 id: 11559 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11559'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11559'
 id: 11560 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '11560'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11560'
 id: 11561 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11561'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11561'
 id: 11562 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '11562'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11562'
 id: 11563 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '11563'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11563'
 id: 11564 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '11564'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11564'
 id: 11565 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '11565'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11565'
 id: 11566 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11566'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11566'
 id: 11567 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11567'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11567'
 id: 11568 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11568'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11568'
 id: 11569 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11569'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11569'
 id: 11570 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '11570'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11570'
 id: 11571 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '11571'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11571'
 id: 11572 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11572'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11572'
 id: 11573 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11573'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11573'
 id: 11574 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11574'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11574'
 id: 11575 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '11575'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11575'
 id: 11576 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '11576'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11576'
 id: 11577 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '11577'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11577'
 id: 11578 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '11578'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11578'
 id: 11579 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '11579'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11579'
 id: 11580 // word: 16
UPDATE job_vacancies SET domain_id =  '16' where raw_id = '11580'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11580'
 id: 11581 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '11581'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11581'
 id: 11582 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11582'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11582'
 id: 11583 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '11583'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11583'
 id: 11584 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '11584'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11584'
 id: 11585 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '11585'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11585'
 id: 11586 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '11586'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11586'
 id: 11587 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '11587'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11587'
 id: 11588 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '11588'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11588'
 id: 11589 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11589'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11589'
 id: 11590 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '11590'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11590'
 id: 11591 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '11591'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11591'
 id: 11592 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '11592'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11592'
 id: 11593 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11593'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11593'
 id: 11594 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '11594'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11594'
 id: 11595 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11595'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11595'
 id: 11596 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11596'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11596'
 id: 11597 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11597'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11597'
 id: 11598 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '11598'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11598'
 id: 11599 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '11599'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11599'
 id: 11600 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '11600'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11600'
 id: 11601 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11601'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11601'
 id: 11602 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '11602'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11602'
 id: 11603 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '11603'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11603'
 id: 11604 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '11604'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11604'
 id: 11605 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '11605'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11605'
 id: 11606 // word: 49
UPDATE job_vacancies SET domain_id =  '49' where raw_id = '11606'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11606'
 id: 11607 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '11607'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11607'
 id: 11608 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '11608'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11608'
 id: 11609 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '11609'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11609'
 id: 11610 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '11610'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11610'
 id: 11611 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '11611'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11611'
 id: 11612 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11612'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11612'
 id: 11613 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '11613'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11613'
 id: 11614 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11614'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11614'
 id: 11615 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '11615'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11615'
 id: 11616 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11616'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11616'
 id: 11617 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '11617'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11617'
 id: 11618 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11618'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11618'
 id: 11619 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11619'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11619'
 id: 11620 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '11620'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11620'
 id: 11621 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11621'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11621'
 id: 11622 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11622'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11622'
 id: 11623 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11623'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11623'
 id: 11624 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '11624'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11624'
 id: 11625 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '11625'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11625'
 id: 11626 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '11626'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11626'
 id: 11627 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '11627'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11627'
 id: 11628 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '11628'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11628'
 id: 11629 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11629'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11629'
 id: 11630 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '11630'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11630'
 id: 11631 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11631'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11631'
 id: 11632 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11632'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11632'
 id: 11633 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '11633'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11633'
 id: 11634 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11634'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11634'
 id: 11635 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '11635'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11635'
 id: 11636 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '11636'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11636'
 id: 11637 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '11637'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11637'
 id: 11638 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11638'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11638'
 id: 11639 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '11639'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11639'
 id: 11640 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '11640'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11640'
 id: 11641 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '11641'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11641'
 id: 11642 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11642'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11642'
 id: 11643 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11643'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11643'
 id: 11644 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11644'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11644'
 id: 11645 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11645'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11645'
 id: 11646 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11646'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11646'
 id: 11647 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '11647'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11647'
 id: 11648 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11648'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11648'
 id: 11649 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11649'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11649'
 id: 11650 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '11650'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11650'
 id: 11651 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '11651'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11651'
 id: 11652 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '11652'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11652'
 id: 11653 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '11653'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11653'
 id: 11654 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '11654'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11654'
 id: 11655 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11655'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11655'
 id: 11656 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '11656'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11656'
 id: 11657 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11657'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11657'
 id: 11658 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '11658'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11658'
 id: 11659 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '11659'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11659'
 id: 11660 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '11660'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11660'
 id: 11661 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '11661'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11661'
 id: 11662 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11662'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11662'
 id: 11663 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11663'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11663'
 id: 11664 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11664'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11664'
 id: 11665 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '11665'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11665'
 id: 11666 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '11666'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11666'
 id: 11667 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11667'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11667'
 id: 11668 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11668'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11668'
 id: 11669 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11669'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11669'
 id: 11670 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '11670'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11670'
 id: 11671 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '11671'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11671'
 id: 11672 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '11672'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11672'
 id: 11673 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '11673'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11673'
 id: 11674 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11674'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11674'
 id: 11675 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '11675'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11675'
 id: 11676 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '11676'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11676'
 id: 11677 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11677'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11677'
 id: 11678 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '11678'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11678'
 id: 11679 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '11679'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11679'
 id: 11680 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11680'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11680'
 id: 11681 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11681'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11681'
 id: 11682 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '11682'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11682'
 id: 11683 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '11683'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11683'
 id: 11684 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '11684'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11684'
 id: 11685 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '11685'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11685'
 id: 11686 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11686'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11686'
 id: 11687 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '11687'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11687'
 id: 11688 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11688'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11688'
 id: 11689 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '11689'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11689'
 id: 11690 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '11690'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11690'
 id: 11691 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '11691'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11691'
 id: 11692 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11692'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11692'
 id: 11693 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11693'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11693'
 id: 11694 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '11694'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11694'
 id: 11695 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '11695'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11695'
 id: 11696 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11696'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11696'
 id: 11697 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '11697'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11697'
 id: 11698 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '11698'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11698'
 id: 11699 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11699'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11699'
 id: 11700 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '11700'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11700'
 id: 11701 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11701'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11701'
 id: 11702 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11702'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11702'
 id: 11703 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11703'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11703'
 id: 11704 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '11704'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11704'
 id: 11705 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11705'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11705'
 id: 11706 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '11706'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11706'
 id: 11707 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11707'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11707'
 id: 11708 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11708'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11708'
 id: 11709 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11709'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11709'
 id: 11710 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '11710'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11710'
 id: 11711 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '11711'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11711'
 id: 11712 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '11712'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11712'
 id: 11713 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '11713'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11713'
 id: 11714 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11714'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11714'
 id: 11715 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '11715'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11715'
 id: 11716 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '11716'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11716'
 id: 11717 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11717'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11717'
 id: 11718 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '11718'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11718'
 id: 11719 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11719'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11719'
 id: 11720 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11720'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11720'
 id: 11721 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '11721'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11721'
 id: 11722 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11722'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11722'
 id: 11723 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11723'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11723'
 id: 11724 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11724'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11724'
 id: 11725 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11725'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11725'
 id: 11726 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '11726'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11726'
 id: 11727 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11727'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11727'
 id: 11728 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11728'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11728'
 id: 11729 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '11729'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11729'
 id: 11730 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '11730'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11730'
 id: 11731 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '11731'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11731'
 id: 11732 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11732'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11732'
 id: 11733 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '11733'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11733'
 id: 11734 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11734'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11734'
 id: 11735 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11735'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11735'
 id: 11736 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '11736'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11736'
 id: 11737 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11737'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11737'
 id: 11738 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11738'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11738'
 id: 11739 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11739'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11739'
 id: 11740 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11740'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11740'
 id: 11741 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '11741'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11741'
 id: 11742 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11742'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11742'
 id: 11743 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11743'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11743'
 id: 11744 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11744'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11744'
 id: 11745 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '11745'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11745'
 id: 11746 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '11746'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11746'
 id: 11747 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11747'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11747'
 id: 11748 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '11748'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11748'
 id: 11749 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11749'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11749'
 id: 11750 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '11750'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11750'
 id: 11751 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '11751'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11751'
 id: 11752 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11752'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11752'
 id: 11753 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11753'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11753'
 id: 11754 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11754'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11754'
 id: 11755 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11755'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11755'
 id: 11756 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11756'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11756'
 id: 11757 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '11757'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11757'
 id: 11758 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '11758'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11758'
 id: 11759 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '11759'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11759'
 id: 11760 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '11760'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11760'
 id: 11761 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '11761'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11761'
 id: 11762 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '11762'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11762'
 id: 11763 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '11763'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11763'
 id: 11764 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11764'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11764'
 id: 11765 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11765'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11765'
 id: 11766 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '11766'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11766'
 id: 11767 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11767'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11767'
 id: 11768 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11768'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11768'
 id: 11769 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11769'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11769'
 id: 11770 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '11770'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11770'
 id: 11771 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '11771'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11771'
 id: 11772 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '11772'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11772'
 id: 11773 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '11773'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11773'
 id: 11774 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '11774'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11774'
 id: 11775 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '11775'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11775'
 id: 11776 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '11776'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11776'
 id: 11777 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11777'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11777'
 id: 11778 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11778'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11778'
 id: 11779 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '11779'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11779'
 id: 11780 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11780'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11780'
 id: 11781 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11781'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11781'
 id: 11782 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '11782'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11782'
 id: 11783 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '11783'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11783'
 id: 11784 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '11784'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11784'
 id: 11785 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11785'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11785'
 id: 11786 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '11786'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11786'
 id: 11787 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '11787'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11787'
 id: 11788 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '11788'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11788'
 id: 11789 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11789'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11789'
 id: 11790 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11790'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11790'
 id: 11791 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11791'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11791'
 id: 11792 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11792'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11792'
 id: 11793 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '11793'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11793'
 id: 11794 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '11794'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11794'
 id: 11795 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11795'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11795'
 id: 11796 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11796'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11796'
 id: 11797 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11797'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11797'
 id: 11798 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '11798'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11798'
 id: 11799 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '11799'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11799'
 id: 11800 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '11800'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11800'
 id: 11801 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11801'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11801'
 id: 11802 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11802'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11802'
 id: 11803 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11803'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11803'
 id: 11804 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11804'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11804'
 id: 11805 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11805'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11805'
 id: 11806 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '11806'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11806'
 id: 11807 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11807'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11807'
 id: 11808 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11808'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11808'
 id: 11809 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11809'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11809'
 id: 11810 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '11810'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11810'
 id: 11811 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11811'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11811'
 id: 11812 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '11812'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11812'
 id: 11813 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11813'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11813'
 id: 11814 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '11814'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11814'
 id: 11815 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '11815'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11815'
 id: 11816 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '11816'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11816'
 id: 11817 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11817'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11817'
 id: 11818 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11818'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11818'
 id: 11819 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11819'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11819'
 id: 11820 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11820'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11820'
 id: 11821 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '11821'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11821'
 id: 11822 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '11822'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11822'
 id: 11823 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11823'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11823'
 id: 11824 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11824'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11824'
 id: 11825 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '11825'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11825'
 id: 11826 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11826'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11826'
 id: 11827 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '11827'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11827'
 id: 11828 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '11828'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11828'
 id: 11829 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11829'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11829'
 id: 11830 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11830'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11830'
 id: 11831 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '11831'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11831'
 id: 11832 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11832'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11832'
 id: 11833 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11833'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11833'
 id: 11834 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '11834'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11834'
 id: 11835 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '11835'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11835'
 id: 11836 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11836'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11836'
 id: 11837 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '11837'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11837'
 id: 11838 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11838'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11838'
 id: 11839 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '11839'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11839'
 id: 11840 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '11840'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11840'
 id: 11841 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11841'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11841'
 id: 11842 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11842'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11842'
 id: 11843 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11843'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11843'
 id: 11844 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11844'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11844'
 id: 11845 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '11845'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11845'
 id: 11846 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '11846'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11846'
 id: 11847 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11847'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11847'
 id: 11848 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11848'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11848'
 id: 11849 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '11849'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11849'
 id: 11850 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11850'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11850'
 id: 11851 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '11851'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11851'
 id: 11852 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '11852'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11852'
 id: 11853 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11853'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11853'
 id: 11854 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11854'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11854'
 id: 11855 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11855'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11855'
 id: 11856 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11856'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11856'
 id: 11857 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '11857'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11857'
 id: 11858 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '11858'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11858'
 id: 11859 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11859'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11859'
 id: 11860 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '11860'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11860'
 id: 11861 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11861'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11861'
 id: 11862 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '11862'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11862'
 id: 11863 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '11863'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11863'
 id: 11864 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11864'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11864'
 id: 11865 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '11865'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11865'
 id: 11866 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11866'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11866'
 id: 11867 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '11867'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11867'
 id: 11868 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '11868'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11868'
 id: 11869 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '11869'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11869'
 id: 11870 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11870'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11870'
 id: 11871 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '11871'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11871'
 id: 11872 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11872'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11872'
 id: 11873 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11873'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11873'
 id: 11874 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '11874'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11874'
 id: 11875 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '11875'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11875'
 id: 11876 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '11876'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11876'
 id: 11877 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11877'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11877'
 id: 11878 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '11878'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11878'
 id: 11879 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '11879'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11879'
 id: 11880 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '11880'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11880'
 id: 11881 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '11881'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11881'
 id: 11882 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11882'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11882'
 id: 11883 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '11883'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11883'
 id: 11884 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11884'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11884'
 id: 11885 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11885'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11885'
 id: 11886 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11886'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11886'
 id: 11887 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '11887'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11887'
 id: 11888 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11888'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11888'
 id: 11889 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11889'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11889'
 id: 11890 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '11890'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11890'
 id: 11891 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11891'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11891'
 id: 11892 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11892'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11892'
 id: 11893 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11893'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11893'
 id: 11894 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11894'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11894'
 id: 11895 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '11895'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11895'
 id: 11896 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '11896'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11896'
 id: 11897 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11897'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11897'
 id: 11898 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11898'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11898'
 id: 11899 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '11899'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11899'
 id: 11900 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11900'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11900'
 id: 11901 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '11901'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11901'
 id: 11902 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11902'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11902'
 id: 11903 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11903'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11903'
 id: 11904 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11904'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11904'
 id: 11905 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11905'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11905'
 id: 11906 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11906'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11906'
 id: 11907 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '11907'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11907'
 id: 11908 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11908'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11908'
 id: 11909 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11909'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11909'
 id: 11910 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '11910'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11910'
 id: 11911 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11911'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11911'
 id: 11912 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '11912'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11912'
 id: 11913 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '11913'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11913'
 id: 11914 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11914'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11914'
 id: 11915 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11915'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11915'
 id: 11916 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '11916'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11916'
 id: 11917 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '11917'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11917'
 id: 11918 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '11918'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11918'
 id: 11919 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '11919'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11919'
 id: 11920 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '11920'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11920'
 id: 11921 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11921'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11921'
 id: 11922 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '11922'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11922'
 id: 11923 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11923'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11923'
 id: 11924 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11924'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11924'
 id: 11925 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '11925'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11925'
 id: 11926 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11926'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11926'
 id: 11927 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '11927'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11927'
 id: 11928 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11928'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11928'
 id: 11929 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '11929'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11929'
 id: 11930 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11930'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11930'
 id: 11931 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11931'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11931'
 id: 11932 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11932'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11932'
 id: 11933 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11933'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11933'
 id: 11934 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '11934'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11934'
 id: 11935 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '11935'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11935'
 id: 11936 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '11936'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11936'
 id: 11937 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '11937'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11937'
 id: 11938 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11938'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11938'
 id: 11939 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '11939'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11939'
 id: 11940 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '11940'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11940'
 id: 11941 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11941'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11941'
 id: 11942 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '11942'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11942'
 id: 11943 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11943'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11943'
 id: 11944 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11944'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11944'
 id: 11945 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11945'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11945'
 id: 11946 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11946'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11946'
 id: 11947 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11947'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11947'
 id: 11948 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11948'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11948'
 id: 11949 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11949'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11949'
 id: 11950 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '11950'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11950'
 id: 11951 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '11951'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11951'
 id: 11952 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11952'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11952'
 id: 11953 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11953'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11953'
 id: 11954 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '11954'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11954'
 id: 11955 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '11955'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11955'
 id: 11956 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '11956'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11956'
 id: 11957 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11957'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11957'
 id: 11958 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '11958'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11958'
 id: 11959 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '11959'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11959'
 id: 11960 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11960'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11960'
 id: 11961 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '11961'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11961'
 id: 11962 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11962'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11962'
 id: 11963 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '11963'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11963'
 id: 11964 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '11964'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11964'
 id: 11965 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11965'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11965'
 id: 11966 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '11966'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11966'
 id: 11967 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11967'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11967'
 id: 11968 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '11968'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11968'
 id: 11969 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11969'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11969'
 id: 11970 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '11970'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11970'
 id: 11971 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '11971'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11971'
 id: 11972 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11972'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11972'
 id: 11973 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '11973'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11973'
 id: 11974 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '11974'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11974'
 id: 11975 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '11975'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11975'
 id: 11976 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11976'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11976'
 id: 11977 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '11977'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11977'
 id: 11978 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '11978'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11978'
 id: 11979 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '11979'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11979'
 id: 11980 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '11980'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11980'
 id: 11981 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '11981'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11981'
 id: 11982 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '11982'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11982'
 id: 11983 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '11983'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11983'
 id: 11984 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '11984'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11984'
 id: 11985 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '11985'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11985'
 id: 11986 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11986'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11986'
 id: 11987 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11987'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11987'
 id: 11988 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '11988'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11988'
 id: 11989 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '11989'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11989'
 id: 11990 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '11990'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11990'
 id: 11991 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '11991'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11991'
 id: 11992 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '11992'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11992'
 id: 11993 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '11993'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11993'
 id: 11994 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '11994'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11994'
 id: 11995 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '11995'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11995'
 id: 11996 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '11996'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11996'
 id: 11997 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '11997'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11997'
 id: 11998 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '11998'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11998'
 id: 11999 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '11999'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '11999'
 id: 12000 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12000'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12000'
 id: 12001 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '12001'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12001'

 id: 12002 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '12002'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12002'
 id: 12003 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12003'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12003'
 id: 12004 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12004'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12004'
 id: 12005 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '12005'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12005'
 id: 12006 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '12006'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12006'
 id: 12007 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12007'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12007'
 id: 12008 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12008'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12008'
 id: 12009 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '12009'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12009'
 id: 12010 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '12010'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12010'
 id: 12011 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '12011'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12011'
 id: 12012 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12012'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12012'
 id: 12013 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12013'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12013'
 id: 12014 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '12014'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12014'
 id: 12015 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12015'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12015'
 id: 12016 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '12016'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12016'
 id: 12017 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12017'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12017'
 id: 12018 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12018'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12018'
 id: 12019 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12019'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12019'
 id: 12020 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12020'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12020'
 id: 12021 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '12021'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12021'
 id: 12022 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12022'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12022'
 id: 12023 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '12023'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12023'
 id: 12024 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12024'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12024'
 id: 12025 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12025'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12025'
 id: 12026 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '12026'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12026'
 id: 12027 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12027'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12027'
 id: 12028 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '12028'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12028'
 id: 12029 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '12029'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12029'
 id: 12030 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '12030'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12030'
 id: 12031 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12031'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12031'
 id: 12032 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '12032'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12032'
 id: 12033 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '12033'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12033'
 id: 12034 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12034'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12034'
 id: 12035 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '12035'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12035'
 id: 12036 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '12036'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12036'
 id: 12037 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '12037'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12037'
 id: 12038 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '12038'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12038'
 id: 12039 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12039'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12039'
 id: 12040 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '12040'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12040'
 id: 12041 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '12041'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12041'
 id: 12042 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12042'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12042'
 id: 12043 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12043'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12043'
 id: 12044 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '12044'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12044'
 id: 12045 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12045'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12045'
 id: 12046 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '12046'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12046'
 id: 12047 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '12047'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12047'
 id: 12048 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '12048'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12048'
 id: 12049 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '12049'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12049'
 id: 12050 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '12050'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12050'
 id: 12051 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12051'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12051'
 id: 12052 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '12052'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12052'
 id: 12053 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '12053'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12053'
 id: 12054 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12054'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12054'
 id: 12055 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12055'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12055'
 id: 12056 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '12056'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12056'
 id: 12057 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12057'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12057'
 id: 12058 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '12058'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12058'
 id: 12059 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12059'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12059'
 id: 12060 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12060'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12060'
 id: 12061 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '12061'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12061'
 id: 12062 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12062'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12062'
 id: 12063 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '12063'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12063'
 id: 12064 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12064'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12064'
 id: 12065 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12065'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12065'
 id: 12066 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12066'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12066'
 id: 12067 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '12067'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12067'
 id: 12068 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12068'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12068'
 id: 12069 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12069'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12069'
 id: 12070 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '12070'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12070'
 id: 12071 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '12071'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12071'
 id: 12072 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '12072'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12072'
 id: 12073 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12073'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12073'
 id: 12074 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12074'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12074'
 id: 12075 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '12075'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12075'
 id: 12076 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '12076'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12076'
 id: 12077 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '12077'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12077'
 id: 12078 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '12078'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12078'
 id: 12079 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12079'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12079'
 id: 12080 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12080'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12080'
 id: 12081 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '12081'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12081'
 id: 12082 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '12082'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12082'
 id: 12083 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '12083'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12083'
 id: 12084 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12084'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12084'
 id: 12085 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12085'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12085'
 id: 12086 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '12086'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12086'
 id: 12087 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '12087'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12087'
 id: 12088 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '12088'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12088'
 id: 12089 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '12089'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12089'
 id: 12090 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12090'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12090'
 id: 12091 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '12091'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12091'
 id: 12092 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '12092'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12092'
 id: 12093 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12093'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12093'
 id: 12094 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '12094'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12094'
 id: 12095 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12095'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12095'
 id: 12096 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12096'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12096'
 id: 12097 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12097'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12097'
 id: 12098 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '12098'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12098'
 id: 12099 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '12099'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12099'
 id: 12100 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12100'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12100'
 id: 12101 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '12101'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12101'
 id: 12102 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12102'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12102'
 id: 12103 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '12103'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12103'
 id: 12104 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12104'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12104'
 id: 12105 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12105'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12105'
 id: 12106 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '12106'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12106'
 id: 12107 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '12107'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12107'
 id: 12108 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '12108'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12108'
 id: 12109 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12109'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12109'
 id: 12110 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '12110'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12110'
 id: 12111 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '12111'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12111'
 id: 12112 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '12112'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12112'
 id: 12113 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12113'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12113'
 id: 12114 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12114'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12114'
 id: 12115 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '12115'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12115'
 id: 12116 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12116'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12116'
 id: 12117 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '12117'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12117'
 id: 12118 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '12118'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12118'
 id: 12119 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12119'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12119'
 id: 12120 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12120'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12120'
 id: 12121 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12121'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12121'
 id: 12122 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12122'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12122'
 id: 12123 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12123'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12123'
 id: 12124 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12124'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12124'
 id: 12125 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12125'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12125'
 id: 12126 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '12126'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12126'
 id: 12127 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12127'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12127'
 id: 12128 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '12128'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12128'
 id: 12129 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '12129'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12129'
 id: 12130 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12130'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12130'
 id: 12131 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12131'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12131'
 id: 12132 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '12132'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12132'
 id: 12133 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '12133'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12133'
 id: 12134 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '12134'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12134'
 id: 12135 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12135'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12135'
 id: 12136 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '12136'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12136'
 id: 12137 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '12137'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12137'
 id: 12138 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '12138'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12138'
 id: 12139 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12139'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12139'
 id: 12140 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '12140'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12140'
 id: 12141 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '12141'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12141'
 id: 12142 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '12142'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12142'
 id: 12143 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '12143'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12143'
 id: 12144 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12144'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12144'
 id: 12145 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '12145'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12145'
 id: 12146 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12146'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12146'
 id: 12147 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '12147'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12147'
 id: 12148 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12148'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12148'
 id: 12149 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12149'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12149'
 id: 12150 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '12150'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12150'

 id: 12151 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12151'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12151'
 id: 12152 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '12152'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12152'
 id: 12153 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12153'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12153'
 id: 12154 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12154'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12154'
 id: 12155 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12155'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12155'
 id: 12156 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12156'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12156'
 id: 12157 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12157'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12157'
 id: 12158 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '12158'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12158'
 id: 12159 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12159'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12159'
 id: 12160 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '12160'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12160'
 id: 12161 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '12161'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12161'
 id: 12162 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '12162'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12162'
 id: 12163 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12163'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12163'
 id: 12164 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '12164'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12164'
 id: 12165 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '12165'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12165'
 id: 12166 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '12166'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12166'
 id: 12167 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '12167'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12167'
 id: 12168 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '12168'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12168'
 id: 12169 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '12169'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12169'
 id: 12170 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12170'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12170'
 id: 12171 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '12171'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12171'
 id: 12172 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '12172'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12172'
 id: 12173 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '12173'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12173'
 id: 12174 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '12174'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12174'
 id: 12175 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '12175'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12175'
 id: 12176 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '12176'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12176'
 id: 12177 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '12177'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12177'
 id: 12178 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '12178'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12178'
 id: 12179 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12179'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12179'
 id: 12180 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12180'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12180'
 id: 12181 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '12181'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12181'
 id: 12182 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '12182'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12182'
 id: 12183 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12183'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12183'
 id: 12184 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '12184'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12184'
 id: 12185 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '12185'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12185'
 id: 12186 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12186'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12186'
 id: 12187 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '12187'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12187'
 id: 12188 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '12188'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12188'
 id: 12189 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '12189'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12189'
 id: 12190 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '12190'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12190'
 id: 12191 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '12191'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12191'
 id: 12192 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12192'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12192'
 id: 12193 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12193'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12193'
 id: 12194 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '12194'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12194'
 id: 12195 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12195'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12195'
 id: 12196 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12196'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12196'
 id: 12197 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '12197'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12197'
 id: 12198 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '12198'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12198'
 id: 12199 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12199'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12199'
 id: 12200 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '12200'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12200'

 id: 12201 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12201'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12201'
 id: 12202 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '12202'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12202'
 id: 12203 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12203'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12203'
 id: 12204 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12204'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12204'
 id: 12205 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '12205'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12205'
 id: 12206 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12206'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12206'
 id: 12207 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '12207'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12207'
 id: 12208 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '12208'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12208'
 id: 12209 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '12209'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12209'
 id: 12210 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '12210'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12210'
 id: 12211 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '12211'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12211'
 id: 12212 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12212'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12212'
 id: 12213 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '12213'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12213'
 id: 12214 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '12214'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12214'
 id: 12215 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12215'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12215'
 id: 12216 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '12216'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12216'
 id: 12217 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12217'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12217'
 id: 12218 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12218'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12218'
 id: 12219 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12219'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12219'
 id: 12220 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '12220'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12220'
 id: 12221 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12221'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12221'
 id: 12222 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '12222'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12222'
 id: 12223 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12223'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12223'
 id: 12224 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12224'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12224'
 id: 12225 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '12225'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12225'
 id: 12226 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '12226'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12226'
 id: 12227 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '12227'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12227'
 id: 12228 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '12228'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12228'
 id: 12229 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12229'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12229'
 id: 12230 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '12230'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12230'
 id: 12231 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '12231'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12231'
 id: 12232 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12232'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12232'
 id: 12233 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '12233'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12233'
 id: 12234 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12234'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12234'
 id: 12235 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '12235'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12235'
 id: 12236 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '12236'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12236'
 id: 12237 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12237'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12237'
 id: 12238 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '12238'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12238'
 id: 12239 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12239'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12239'
 id: 12240 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '12240'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12240'
 id: 12241 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '12241'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12241'
 id: 12242 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12242'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12242'
 id: 12243 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '12243'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12243'
 id: 12244 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '12244'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12244'
 id: 12245 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12245'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12245'
 id: 12246 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12246'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12246'
 id: 12247 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '12247'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12247'
 id: 12248 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '12248'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12248'
 id: 12249 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '12249'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12249'
 id: 12250 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12250'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12250'
 id: 12251 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '12251'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12251'
 id: 12252 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12252'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12252'
 id: 12253 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12253'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12253'
 id: 12254 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '12254'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12254'
 id: 12255 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12255'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12255'
 id: 12256 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '12256'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12256'
 id: 12257 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12257'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12257'
 id: 12258 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12258'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12258'
 id: 12259 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12259'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12259'
 id: 12260 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12260'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12260'
 id: 12261 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12261'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12261'
 id: 12262 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12262'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12262'
 id: 12263 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12263'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12263'
 id: 12264 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12264'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12264'
 id: 12265 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12265'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12265'
 id: 12266 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '12266'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12266'
 id: 12267 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '12267'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12267'
 id: 12268 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12268'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12268'
 id: 12269 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '12269'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12269'
 id: 12270 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12270'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12270'
 id: 12271 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '12271'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12271'
 id: 12272 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '12272'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12272'
 id: 12273 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12273'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12273'
 id: 12274 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '12274'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12274'
 id: 12275 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12275'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12275'
 id: 12276 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12276'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12276'
 id: 12277 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '12277'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12277'
 id: 12278 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12278'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12278'
 id: 12279 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12279'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12279'
 id: 12280 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '12280'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12280'
 id: 12281 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12281'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12281'
 id: 12282 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '12282'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12282'
 id: 12283 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '12283'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12283'
 id: 12284 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '12284'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12284'
 id: 12285 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '12285'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12285'
 id: 12286 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12286'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12286'
 id: 12287 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '12287'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12287'
 id: 12288 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12288'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12288'
 id: 12289 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12289'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12289'
 id: 12290 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12290'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12290'
 id: 12291 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12291'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12291'
 id: 12292 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12292'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12292'
 id: 12293 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12293'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12293'
 id: 12294 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12294'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12294'
 id: 12295 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '12295'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12295'
 id: 12296 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12296'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12296'
 id: 12297 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '12297'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12297'
 id: 12298 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '12298'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12298'
 id: 12299 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12299'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12299'
 id: 12300 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12300'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12300'
 id: 12301 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '12301'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12301'
 id: 12302 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '12302'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12302'
 id: 12303 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '12303'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12303'
 id: 12304 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12304'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12304'
 id: 12305 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '12305'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12305'
 id: 12306 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '12306'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12306'
 id: 12307 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '12307'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12307'
 id: 12308 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12308'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12308'
 id: 12309 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12309'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12309'
 id: 12310 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12310'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12310'
 id: 12311 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12311'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12311'
 id: 12312 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '12312'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12312'
 id: 12313 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12313'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12313'
 id: 12314 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12314'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12314'
 id: 12315 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12315'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12315'
 id: 12316 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '12316'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12316'
 id: 12317 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '12317'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12317'
 id: 12318 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12318'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12318'
 id: 12319 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '12319'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12319'
 id: 12320 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '12320'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12320'
 id: 12321 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12321'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12321'
 id: 12322 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '12322'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12322'
 id: 12323 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12323'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12323'
 id: 12324 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12324'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12324'
 id: 12325 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '12325'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12325'
 id: 12326 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12326'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12326'
 id: 12327 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12327'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12327'
 id: 12328 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '12328'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12328'
 id: 12329 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '12329'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12329'
 id: 12330 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12330'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12330'
 id: 12331 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '12331'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12331'
 id: 12332 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12332'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12332'
 id: 12333 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12333'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12333'
 id: 12334 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '12334'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12334'
 id: 12335 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12335'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12335'
 id: 12336 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12336'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12336'
 id: 12337 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '12337'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12337'
 id: 12338 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12338'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12338'
 id: 12339 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12339'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12339'
 id: 12340 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '12340'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12340'
 id: 12341 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '12341'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12341'
 id: 12342 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '12342'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12342'
 id: 12343 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '12343'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12343'
 id: 12344 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '12344'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12344'
 id: 12345 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12345'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12345'
 id: 12346 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12346'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12346'
 id: 12347 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '12347'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12347'
 id: 12348 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '12348'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12348'
 id: 12349 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12349'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12349'
 id: 12350 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12350'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12350'
 id: 12351 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '12351'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12351'
 id: 12352 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '12352'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12352'
 id: 12353 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '12353'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12353'
 id: 12354 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '12354'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12354'
 id: 12355 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12355'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12355'
 id: 12356 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '12356'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12356'
 id: 12357 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '12357'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12357'
 id: 12358 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12358'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12358'
 id: 12359 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12359'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12359'
 id: 12360 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '12360'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12360'
 id: 12361 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '12361'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12361'
 id: 12362 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12362'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12362'
 id: 12363 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '12363'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12363'
 id: 12364 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12364'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12364'
 id: 12365 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12365'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12365'
 id: 12366 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12366'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12366'
 id: 12367 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '12367'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12367'
 id: 12368 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '12368'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12368'
 id: 12369 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '12369'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12369'
 id: 12370 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12370'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12370'
 id: 12371 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '12371'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12371'
 id: 12372 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '12372'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12372'
 id: 12373 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '12373'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12373'
 id: 12374 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '12374'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12374'
 id: 12375 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '12375'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12375'
 id: 12376 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12376'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12376'
 id: 12377 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '12377'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12377'
 id: 12378 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12378'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12378'
 id: 12379 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12379'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12379'
 id: 12380 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12380'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12380'
 id: 12381 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12381'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12381'
 id: 12382 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '12382'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12382'
 id: 12383 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12383'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12383'
 id: 12384 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12384'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12384'
 id: 12385 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '12385'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12385'
 id: 12386 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '12386'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12386'
 id: 12387 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '12387'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12387'
 id: 12388 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12388'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12388'
 id: 12389 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '12389'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12389'
 id: 12390 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '12390'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12390'
 id: 12391 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '12391'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12391'
 id: 12392 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12392'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12392'
 id: 12393 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '12393'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12393'
 id: 12394 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12394'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12394'
 id: 12395 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12395'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12395'
 id: 12396 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '12396'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12396'
 id: 12397 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12397'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12397'
 id: 12398 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12398'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12398'
 id: 12399 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12399'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12399'
 id: 12400 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12400'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12400'
 id: 12401 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12401'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12401'
 id: 12402 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12402'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12402'
 id: 12403 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12403'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12403'
 id: 12404 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '12404'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12404'
 id: 12405 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '12405'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12405'
 id: 12406 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12406'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12406'
 id: 12407 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '12407'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12407'
 id: 12408 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12408'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12408'
 id: 12409 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12409'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12409'
 id: 12410 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12410'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12410'
 id: 12411 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '12411'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12411'
 id: 12412 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12412'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12412'
 id: 12413 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12413'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12413'
 id: 12414 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12414'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12414'
 id: 12415 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12415'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12415'
 id: 12416 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '12416'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12416'
 id: 12417 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12417'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12417'
 id: 12418 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12418'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12418'
 id: 12419 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12419'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12419'
 id: 12420 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12420'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12420'
 id: 12421 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12421'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12421'
 id: 12422 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '12422'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12422'
 id: 12423 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '12423'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12423'
 id: 12424 // word: 57
UPDATE job_vacancies SET domain_id =  '57' where raw_id = '12424'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12424'
 id: 12425 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12425'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12425'
 id: 12426 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12426'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12426'
 id: 12427 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12427'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12427'
 id: 12428 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12428'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12428'
 id: 12429 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12429'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12429'
 id: 12430 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12430'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12430'
 id: 12431 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12431'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12431'
 id: 12432 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '12432'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12432'
 id: 12433 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12433'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12433'
 id: 12434 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '12434'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12434'
 id: 12435 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12435'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12435'
 id: 12436 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12436'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12436'
 id: 12437 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12437'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12437'
 id: 12438 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '12438'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12438'
 id: 12439 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '12439'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12439'
 id: 12440 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12440'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12440'
 id: 12441 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12441'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12441'
 id: 12442 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12442'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12442'
 id: 12443 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12443'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12443'
 id: 12444 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '12444'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12444'
 id: 12445 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12445'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12445'
 id: 12446 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12446'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12446'
 id: 12447 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '12447'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12447'
 id: 12448 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '12448'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12448'
 id: 12449 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '12449'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12449'
 id: 12450 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '12450'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12450'
 id: 12451 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12451'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12451'
 id: 12452 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12452'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12452'
 id: 12453 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '12453'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12453'
 id: 12454 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12454'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12454'
 id: 12455 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12455'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12455'
 id: 12456 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '12456'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12456'
 id: 12457 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '12457'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12457'
 id: 12458 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12458'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12458'
 id: 12459 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12459'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12459'
 id: 12460 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12460'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12460'
 id: 12461 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '12461'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12461'
 id: 12462 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12462'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12462'
 id: 12463 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12463'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12463'
 id: 12464 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '12464'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12464'
 id: 12465 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12465'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12465'
 id: 12466 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '12466'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12466'
 id: 12467 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12467'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12467'
 id: 12468 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12468'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12468'
 id: 12469 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '12469'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12469'
 id: 12470 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12470'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12470'
 id: 12471 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '12471'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12471'
 id: 12472 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12472'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12472'
 id: 12473 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '12473'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12473'
 id: 12474 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '12474'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12474'
 id: 12475 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '12475'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12475'
 id: 12476 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12476'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12476'
 id: 12477 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12477'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12477'
 id: 12478 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12478'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12478'
 id: 12479 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '12479'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12479'
 id: 12480 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12480'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12480'
 id: 12481 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12481'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12481'
 id: 12482 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '12482'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12482'
 id: 12483 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12483'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12483'
 id: 12484 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '12484'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12484'
 id: 12485 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12485'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12485'
 id: 12486 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '12486'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12486'
 id: 12487 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '12487'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12487'
 id: 12488 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '12488'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12488'
 id: 12489 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '12489'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12489'
 id: 12490 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12490'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12490'
 id: 12491 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '12491'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12491'
 id: 12492 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '12492'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12492'
 id: 12493 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '12493'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12493'
 id: 12494 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '12494'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12494'
 id: 12495 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '12495'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12495'
 id: 12496 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '12496'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12496'
 id: 12497 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '12497'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12497'
 id: 12498 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12498'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12498'
 id: 12499 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12499'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12499'
 id: 12500 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '12500'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12500'
 id: 12501 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12501'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12501'
 id: 12502 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '12502'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12502'
 id: 12503 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '12503'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12503'
 id: 12504 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12504'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12504'
 id: 12505 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '12505'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12505'
 id: 12506 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '12506'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12506'
 id: 12507 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12507'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12507'
 id: 12508 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12508'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12508'
 id: 12509 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '12509'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12509'
 id: 12510 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12510'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12510'
 id: 12511 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '12511'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12511'
 id: 12512 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12512'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12512'
 id: 12513 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12513'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12513'
 id: 12514 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '12514'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12514'
 id: 12515 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '12515'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12515'
 id: 12516 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12516'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12516'
 id: 12517 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12517'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12517'
 id: 12518 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '12518'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12518'
 id: 12519 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '12519'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12519'
 id: 12520 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '12520'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12520'
 id: 12521 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12521'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12521'
 id: 12522 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '12522'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12522'
 id: 12523 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12523'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12523'
 id: 12524 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '12524'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12524'
 id: 12525 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '12525'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12525'
 id: 12526 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '12526'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12526'
 id: 12527 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12527'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12527'
 id: 12528 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12528'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12528'
 id: 12529 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '12529'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12529'
 id: 12530 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '12530'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12530'
 id: 12531 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12531'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12531'
 id: 12532 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12532'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12532'
 id: 12533 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '12533'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12533'
 id: 12534 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '12534'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12534'
 id: 12535 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '12535'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12535'
 id: 12536 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12536'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12536'
 id: 12537 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '12537'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12537'
 id: 12538 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12538'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12538'
 id: 12539 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '12539'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12539'
 id: 12540 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '12540'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12540'
 id: 12541 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '12541'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12541'
 id: 12542 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '12542'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12542'
 id: 12543 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12543'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12543'
 id: 12544 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '12544'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12544'
 id: 12545 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12545'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12545'
 id: 12546 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12546'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12546'
 id: 12547 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '12547'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12547'
 id: 12548 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '12548'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12548'
 id: 12549 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12549'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12549'
 id: 12550 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12550'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12550'
 id: 12551 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '12551'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12551'
 id: 12552 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12552'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12552'
 id: 12553 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '12553'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12553'
 id: 12554 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '12554'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12554'
 id: 12555 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '12555'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12555'
 id: 12556 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12556'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12556'
 id: 12557 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '12557'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12557'
 id: 12558 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12558'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12558'
 id: 12559 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '12559'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12559'
 id: 12560 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12560'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12560'
 id: 12561 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12561'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12561'
 id: 12562 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '12562'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12562'
 id: 12563 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '12563'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12563'
 id: 12564 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '12564'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12564'
 id: 12565 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '12565'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12565'
 id: 12566 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '12566'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12566'
 id: 12567 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '12567'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12567'
 id: 12568 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12568'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12568'
 id: 12569 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '12569'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12569'
 id: 12570 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '12570'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12570'
 id: 12571 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '12571'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12571'
 id: 12572 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '12572'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12572'
 id: 12573 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12573'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12573'
 id: 12574 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12574'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12574'
 id: 12575 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12575'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12575'
 id: 12576 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '12576'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12576'
 id: 12577 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12577'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12577'
 id: 12578 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '12578'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12578'
 id: 12579 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12579'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12579'
 id: 12580 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12580'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12580'
 id: 12581 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '12581'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12581'
 id: 12582 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12582'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12582'
 id: 12583 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '12583'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12583'
 id: 12584 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '12584'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12584'
 id: 12585 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '12585'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12585'
 id: 12586 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '12586'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12586'
 id: 12587 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '12587'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12587'
 id: 12588 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12588'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12588'
 id: 12589 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12589'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12589'
 id: 12590 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '12590'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12590'
 id: 12591 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '12591'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12591'
 id: 12592 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '12592'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12592'
 id: 12593 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12593'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12593'
 id: 12594 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '12594'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12594'
 id: 12595 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '12595'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12595'
 id: 12596 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12596'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12596'
 id: 12597 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12597'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12597'
 id: 12598 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '12598'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12598'
 id: 12599 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12599'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12599'
 id: 12600 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12600'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12600'
 id: 12601 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '12601'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12601'
 id: 12602 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12602'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12602'
 id: 12603 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12603'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12603'
 id: 12604 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12604'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12604'
 id: 12605 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '12605'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12605'
 id: 12606 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12606'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12606'
 id: 12607 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12607'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12607'
 id: 12608 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12608'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12608'
 id: 12609 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12609'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12609'
 id: 12610 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12610'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12610'
 id: 12611 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '12611'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12611'

 id: 12612 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12612'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12612'
 id: 12613 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '12613'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12613'
 id: 12614 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '12614'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12614'
 id: 12615 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12615'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12615'
 id: 12616 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12616'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12616'
 id: 12617 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '12617'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12617'
 id: 12618 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12618'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12618'
 id: 12619 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '12619'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12619'
 id: 12620 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12620'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12620'
 id: 12621 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12621'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12621'
 id: 12622 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '12622'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12622'
 id: 12623 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12623'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12623'
 id: 12624 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '12624'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12624'
 id: 12625 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '12625'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12625'
 id: 12626 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12626'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12626'
 id: 12627 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '12627'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12627'
 id: 12628 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '12628'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12628'
 id: 12629 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12629'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12629'
 id: 12630 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '12630'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12630'
 id: 12631 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '12631'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12631'
 id: 12632 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12632'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12632'
 id: 12633 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12633'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12633'
 id: 12634 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12634'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12634'
 id: 12635 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '12635'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12635'
 id: 12636 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '12636'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12636'
 id: 12637 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '12637'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12637'
 id: 12638 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '12638'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12638'
 id: 12639 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12639'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12639'
 id: 12640 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '12640'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12640'
 id: 12641 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12641'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12641'
 id: 12642 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12642'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12642'
 id: 12643 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12643'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12643'
 id: 12644 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12644'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12644'
 id: 12645 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12645'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12645'
 id: 12646 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12646'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12646'
 id: 12647 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '12647'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12647'
 id: 12648 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '12648'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12648'
 id: 12649 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12649'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12649'
 id: 12650 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12650'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12650'
 id: 12651 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '12651'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12651'
 id: 12652 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12652'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12652'
 id: 12653 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12653'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12653'
 id: 12654 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '12654'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12654'
 id: 12655 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12655'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12655'
 id: 12656 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '12656'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12656'
 id: 12657 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12657'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12657'
 id: 12658 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '12658'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12658'
 id: 12659 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12659'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12659'
 id: 12660 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '12660'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12660'
 id: 12661 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12661'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12661'
 id: 12662 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '12662'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12662'
 id: 12663 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12663'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12663'
 id: 12664 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '12664'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12664'
 id: 12665 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12665'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12665'
 id: 12666 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '12666'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12666'
 id: 12667 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12667'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12667'
 id: 12668 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12668'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12668'
 id: 12669 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '12669'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12669'
 id: 12670 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12670'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12670'
 id: 12671 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '12671'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12671'
 id: 12672 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12672'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12672'
 id: 12673 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '12673'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12673'
 id: 12674 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '12674'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12674'
 id: 12675 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '12675'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12675'
 id: 12676 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12676'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12676'
 id: 12677 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12677'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12677'
 id: 12678 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '12678'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12678'
 id: 12679 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12679'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12679'
 id: 12680 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '12680'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12680'
 id: 12681 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '12681'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12681'
 id: 12682 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '12682'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12682'
 id: 12683 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12683'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12683'
 id: 12684 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12684'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12684'
 id: 12685 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12685'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12685'
 id: 12686 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12686'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12686'
 id: 12687 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12687'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12687'
 id: 12688 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12688'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12688'
 id: 12689 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '12689'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12689'
 id: 12690 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '12690'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12690'
 id: 12691 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '12691'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12691'
 id: 12692 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12692'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12692'
 id: 12693 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '12693'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12693'
 id: 12694 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '12694'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12694'
 id: 12695 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12695'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12695'
 id: 12696 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12696'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12696'
 id: 12697 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '12697'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12697'
 id: 12698 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12698'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12698'
 id: 12699 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '12699'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12699'
 id: 12700 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '12700'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12700'
 id: 12701 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '12701'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12701'
 id: 12702 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '12702'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12702'
 id: 12703 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12703'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12703'
 id: 12704 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '12704'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12704'
 id: 12705 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12705'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12705'
 id: 12706 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12706'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12706'
 id: 12707 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '12707'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12707'
 id: 12708 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '12708'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12708'
 id: 12709 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12709'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12709'
 id: 12710 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12710'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12710'
 id: 12711 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12711'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12711'
 id: 12712 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '12712'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12712'

 id: 12713 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12713'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12713'
 id: 12714 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '12714'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12714'
 id: 12715 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12715'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12715'
 id: 12716 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12716'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12716'
 id: 12717 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12717'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12717'
 id: 12718 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12718'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12718'
 id: 12719 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '12719'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12719'
 id: 12720 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '12720'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12720'
 id: 12721 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12721'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12721'
 id: 12722 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '12722'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12722'
 id: 12723 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '12723'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12723'
 id: 12724 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12724'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12724'
 id: 12725 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12725'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12725'
 id: 12726 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12726'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12726'
 id: 12727 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '12727'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12727'
 id: 12728 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12728'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12728'
 id: 12729 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12729'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12729'
 id: 12730 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12730'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12730'
 id: 12731 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '12731'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12731'
 id: 12732 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12732'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12732'
 id: 12733 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '12733'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12733'
 id: 12734 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12734'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12734'
 id: 12735 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12735'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12735'
 id: 12736 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '12736'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12736'
 id: 12737 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '12737'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12737'
 id: 12738 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '12738'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12738'
 id: 12739 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '12739'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12739'
 id: 12740 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12740'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12740'
 id: 12741 // word: 53
UPDATE job_vacancies SET domain_id =  '53' where raw_id = '12741'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12741'
 id: 12742 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '12742'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12742'
 id: 12743 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '12743'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12743'
 id: 12744 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '12744'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12744'
 id: 12745 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '12745'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12745'
 id: 12746 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12746'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12746'
 id: 12747 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12747'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12747'
 id: 12748 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12748'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12748'
 id: 12749 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '12749'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12749'
 id: 12750 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12750'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12750'
 id: 12751 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12751'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12751'
 id: 12752 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '12752'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12752'
 id: 12753 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12753'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12753'
 id: 12754 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '12754'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12754'
 id: 12755 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '12755'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12755'
 id: 12756 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '12756'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12756'
 id: 12757 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12757'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12757'
 id: 12758 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12758'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12758'
 id: 12759 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '12759'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12759'
 id: 12760 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '12760'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12760'
 id: 12761 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '12761'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12761'
 id: 12762 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12762'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12762'
 id: 12763 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '12763'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12763'
 id: 12764 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '12764'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12764'
 id: 12765 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '12765'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12765'
 id: 12766 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12766'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12766'
 id: 12767 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12767'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12767'
 id: 12768 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '12768'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12768'
 id: 12769 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12769'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12769'
 id: 12770 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '12770'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12770'
 id: 12771 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12771'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12771'
 id: 12772 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '12772'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12772'
 id: 12773 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12773'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12773'
 id: 12774 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '12774'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12774'
 id: 12775 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12775'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12775'
 id: 12776 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '12776'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12776'
 id: 12777 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12777'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12777'
 id: 12778 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12778'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12778'
 id: 12779 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '12779'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12779'
 id: 12780 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12780'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12780'
 id: 12781 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '12781'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12781'
 id: 12782 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12782'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12782'
 id: 12783 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '12783'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12783'
 id: 12784 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12784'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12784'
 id: 12785 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12785'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12785'
 id: 12786 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '12786'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12786'
 id: 12787 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12787'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12787'
 id: 12788 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '12788'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12788'
 id: 12789 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12789'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12789'
 id: 12790 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '12790'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12790'
 id: 12791 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12791'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12791'
 id: 12792 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '12792'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12792'
 id: 12793 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12793'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12793'
 id: 12794 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '12794'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12794'
 id: 12795 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '12795'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12795'
 id: 12796 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '12796'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12796'
 id: 12797 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '12797'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12797'
 id: 12798 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '12798'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12798'
 id: 12799 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '12799'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12799'
 id: 12800 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12800'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12800'
 id: 12801 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '12801'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12801'
 id: 12802 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12802'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12802'
 id: 12803 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '12803'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12803'
 id: 12804 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12804'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12804'
 id: 12805 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12805'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12805'
 id: 12806 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '12806'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12806'
 id: 12807 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12807'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12807'
 id: 12808 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '12808'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12808'
 id: 12809 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '12809'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12809'
 id: 12810 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '12810'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12810'
 id: 12811 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '12811'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12811'
 id: 12812 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12812'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12812'
 id: 12813 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12813'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12813'
 id: 12814 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12814'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12814'
 id: 12815 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '12815'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12815'
 id: 12816 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '12816'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12816'
 id: 12817 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '12817'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12817'
 id: 12818 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12818'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12818'
 id: 12819 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '12819'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12819'
 id: 12820 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12820'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12820'
 id: 12821 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12821'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12821'
 id: 12822 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '12822'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12822'
 id: 12823 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12823'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12823'
 id: 12824 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '12824'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12824'
 id: 12825 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12825'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12825'
 id: 12826 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12826'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12826'
 id: 12827 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12827'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12827'
 id: 12828 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12828'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12828'
 id: 12829 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12829'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12829'
 id: 12830 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12830'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12830'
 id: 12831 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12831'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12831'
 id: 12832 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12832'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12832'
 id: 12833 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '12833'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12833'
 id: 12834 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12834'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12834'
 id: 12835 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12835'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12835'
 id: 12836 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12836'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12836'
 id: 12837 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12837'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12837'
 id: 12838 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12838'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12838'
 id: 12839 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12839'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12839'
 id: 12840 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '12840'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12840'
 id: 12841 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12841'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12841'
 id: 12842 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12842'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12842'
 id: 12843 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12843'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12843'
 id: 12844 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12844'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12844'
 id: 12845 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '12845'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12845'
 id: 12846 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '12846'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12846'
 id: 12847 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12847'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12847'
 id: 12848 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12848'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12848'
 id: 12849 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12849'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12849'
 id: 12850 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12850'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12850'
 id: 12851 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '12851'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12851'
 id: 12852 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '12852'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12852'
 id: 12853 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '12853'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12853'
 id: 12854 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '12854'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12854'
 id: 12855 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12855'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12855'
 id: 12856 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12856'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12856'
 id: 12857 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '12857'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12857'
 id: 12858 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12858'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12858'
 id: 12859 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12859'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12859'
 id: 12860 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12860'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12860'
 id: 12861 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '12861'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12861'
 id: 12862 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12862'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12862'
 id: 12863 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '12863'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12863'
 id: 12864 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '12864'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12864'
 id: 12865 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12865'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12865'
 id: 12866 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12866'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12866'
 id: 12867 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '12867'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12867'
 id: 12868 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '12868'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12868'
 id: 12869 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12869'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12869'
 id: 12870 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '12870'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12870'
 id: 12871 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12871'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12871'
 id: 12872 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '12872'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12872'
 id: 12873 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '12873'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12873'
 id: 12874 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12874'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12874'
 id: 12875 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '12875'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12875'
 id: 12876 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12876'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12876'
 id: 12877 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '12877'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12877'
 id: 12878 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '12878'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12878'
 id: 12879 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12879'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12879'
 id: 12880 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12880'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12880'
 id: 12881 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '12881'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12881'
 id: 12882 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12882'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12882'
 id: 12883 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12883'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12883'
 id: 12884 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '12884'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12884'
 id: 12885 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '12885'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12885'
 id: 12886 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12886'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12886'
 id: 12887 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12887'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12887'
 id: 12888 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '12888'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12888'
 id: 12889 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '12889'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12889'
 id: 12890 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12890'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12890'
 id: 12891 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '12891'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12891'
 id: 12892 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '12892'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12892'
 id: 12893 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12893'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12893'
 id: 12894 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12894'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12894'
 id: 12895 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12895'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12895'
 id: 12896 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12896'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12896'
 id: 12897 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '12897'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12897'
 id: 12898 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12898'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12898'
 id: 12899 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '12899'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12899'
 id: 12900 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '12900'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12900'
 id: 12901 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '12901'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12901'
 id: 12902 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12902'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12902'
 id: 12903 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12903'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12903'
 id: 12904 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12904'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12904'
 id: 12905 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '12905'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12905'
 id: 12906 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '12906'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12906'
 id: 12907 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12907'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12907'
 id: 12908 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '12908'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12908'
 id: 12909 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '12909'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12909'
 id: 12910 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '12910'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12910'
 id: 12911 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12911'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12911'
 id: 12912 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '12912'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12912'
 id: 12913 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12913'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12913'
 id: 12914 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '12914'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12914'
 id: 12915 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12915'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12915'
 id: 12916 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12916'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12916'
 id: 12917 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12917'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12917'
 id: 12918 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12918'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12918'
 id: 12919 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '12919'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12919'
 id: 12920 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12920'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12920'
 id: 12921 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12921'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12921'
 id: 12922 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12922'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12922'
 id: 12923 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '12923'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12923'
 id: 12924 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12924'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12924'
 id: 12925 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12925'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12925'
 id: 12926 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12926'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12926'
 id: 12927 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '12927'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12927'
 id: 12928 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12928'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12928'
 id: 12929 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12929'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12929'
 id: 12930 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12930'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12930'
 id: 12931 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '12931'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12931'
 id: 12932 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12932'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12932'
 id: 12933 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12933'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12933'
 id: 12934 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12934'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12934'
 id: 12935 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12935'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12935'
 id: 12936 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12936'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12936'
 id: 12937 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12937'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12937'
 id: 12938 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '12938'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12938'
 id: 12939 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '12939'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12939'
 id: 12940 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '12940'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12940'
 id: 12941 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '12941'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12941'
 id: 12942 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '12942'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12942'
 id: 12943 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '12943'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12943'
 id: 12944 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '12944'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12944'
 id: 12945 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '12945'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12945'
 id: 12946 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '12946'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12946'
 id: 12947 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12947'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12947'
 id: 12948 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12948'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12948'
 id: 12949 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12949'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12949'
 id: 12950 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12950'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12950'
 id: 12951 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '12951'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12951'
 id: 12952 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '12952'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12952'
 id: 12953 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '12953'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12953'
 id: 12954 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '12954'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12954'
 id: 12955 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '12955'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12955'
 id: 12956 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12956'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12956'
 id: 12957 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12957'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12957'
 id: 12958 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '12958'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12958'
 id: 12959 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '12959'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12959'
 id: 12960 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '12960'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12960'
 id: 12961 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '12961'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12961'
 id: 12962 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '12962'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12962'
 id: 12963 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '12963'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12963'
 id: 12964 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12964'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12964'
 id: 12965 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12965'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12965'
 id: 12966 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '12966'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12966'
 id: 12967 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '12967'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12967'
 id: 12968 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12968'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12968'
 id: 12969 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '12969'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12969'
 id: 12970 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '12970'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12970'
 id: 12971 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12971'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12971'
 id: 12972 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '12972'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12972'
 id: 12973 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '12973'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12973'
 id: 12974 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '12974'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12974'
 id: 12975 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12975'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12975'
 id: 12976 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12976'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12976'
 id: 12977 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '12977'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12977'
 id: 12978 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '12978'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12978'
 id: 12979 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12979'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12979'
 id: 12980 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '12980'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12980'
 id: 12981 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '12981'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12981'
 id: 12982 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12982'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12982'
 id: 12983 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '12983'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12983'
 id: 12984 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '12984'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12984'
 id: 12985 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12985'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12985'
 id: 12986 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '12986'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12986'
 id: 12987 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '12987'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12987'
 id: 12988 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '12988'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12988'
 id: 12989 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '12989'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12989'
 id: 12990 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '12990'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12990'
 id: 12991 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12991'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12991'
 id: 12992 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '12992'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12992'
 id: 12993 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '12993'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12993'
 id: 12994 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '12994'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12994'
 id: 12995 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '12995'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12995'
 id: 12996 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '12996'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12996'
 id: 12997 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12997'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12997'
 id: 12998 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '12998'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12998'
 id: 12999 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '12999'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '12999'
 id: 13000 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '13000'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13000'
 id: 13001 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13001'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13001'
 id: 13002 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '13002'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13002'
 id: 13003 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13003'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13003'
 id: 13004 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '13004'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13004'
 id: 13005 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13005'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13005'
 id: 13006 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '13006'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13006'
 id: 13007 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '13007'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13007'
 id: 13008 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13008'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13008'
 id: 13009 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '13009'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13009'
 id: 13010 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '13010'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13010'
 id: 13011 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '13011'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13011'
 id: 13012 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13012'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13012'
 id: 13013 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '13013'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13013'
 id: 13014 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '13014'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13014'
 id: 13015 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13015'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13015'
 id: 13016 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13016'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13016'
 id: 13017 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '13017'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13017'
 id: 13018 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '13018'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13018'
 id: 13019 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '13019'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13019'
 id: 13020 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '13020'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13020'
 id: 13021 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '13021'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13021'
 id: 13022 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13022'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13022'
 id: 13023 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13023'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13023'
 id: 13024 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '13024'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13024'
 id: 13025 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '13025'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13025'
 id: 13026 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13026'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13026'
 id: 13027 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '13027'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13027'
 id: 13028 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '13028'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13028'
 id: 13029 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '13029'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13029'
 id: 13030 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13030'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13030'
 id: 13031 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13031'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13031'
 id: 13032 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13032'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13032'
 id: 13033 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '13033'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13033'
 id: 13034 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '13034'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13034'
 id: 13035 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13035'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13035'
 id: 13036 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13036'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13036'
 id: 13037 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '13037'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13037'
 id: 13038 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '13038'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13038'
 id: 13039 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '13039'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13039'
 id: 13040 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13040'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13040'
 id: 13041 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13041'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13041'
 id: 13042 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13042'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13042'
 id: 13043 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '13043'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13043'
 id: 13044 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '13044'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13044'
 id: 13045 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '13045'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13045'
 id: 13046 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '13046'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13046'
 id: 13047 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13047'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13047'
 id: 13048 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '13048'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13048'
 id: 13049 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '13049'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13049'
 id: 13050 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '13050'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13050'
 id: 13051 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '13051'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13051'
 id: 13052 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '13052'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13052'
 id: 13053 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '13053'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13053'
 id: 13054 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '13054'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13054'
 id: 13055 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13055'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13055'
 id: 13056 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13056'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13056'
 id: 13057 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13057'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13057'
 id: 13058 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13058'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13058'
 id: 13059 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '13059'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13059'
 id: 13060 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13060'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13060'
 id: 13061 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '13061'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13061'
 id: 13062 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '13062'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13062'
 id: 13063 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '13063'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13063'
 id: 13064 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '13064'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13064'
 id: 13065 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '13065'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13065'
 id: 13066 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '13066'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13066'
 id: 13067 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13067'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13067'
 id: 13068 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13068'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13068'
 id: 13069 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '13069'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13069'
 id: 13070 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13070'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13070'
 id: 13071 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '13071'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13071'

 id: 13072 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13072'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13072'
 id: 13073 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '13073'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13073'
 id: 13074 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '13074'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13074'
 id: 13075 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '13075'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13075'
 id: 13076 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '13076'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13076'
 id: 13077 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '13077'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13077'
 id: 13078 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '13078'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13078'
 id: 13079 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13079'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13079'
 id: 13080 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13080'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13080'
 id: 13081 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '13081'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13081'
 id: 13082 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '13082'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13082'
 id: 13083 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13083'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13083'
 id: 13084 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '13084'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13084'
 id: 13085 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13085'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13085'
 id: 13086 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13086'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13086'
 id: 13087 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13087'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13087'
 id: 13088 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13088'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13088'
 id: 13089 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '13089'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13089'
 id: 13090 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '13090'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13090'
 id: 13091 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '13091'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13091'
 id: 13092 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '13092'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13092'
 id: 13093 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '13093'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13093'
 id: 13094 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13094'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13094'
 id: 13095 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13095'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13095'
 id: 13096 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13096'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13096'
 id: 13097 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '13097'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13097'
 id: 13098 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13098'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13098'
 id: 13099 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13099'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13099'
 id: 13100 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13100'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13100'
 id: 13101 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '13101'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13101'
 id: 13102 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13102'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13102'
 id: 13103 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '13103'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13103'
 id: 13104 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '13104'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13104'
 id: 13105 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13105'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13105'
 id: 13106 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13106'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13106'
 id: 13107 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '13107'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13107'
 id: 13108 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13108'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13108'
 id: 13109 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13109'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13109'
 id: 13110 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '13110'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13110'
 id: 13111 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13111'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13111'
 id: 13112 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '13112'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13112'
 id: 13113 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13113'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13113'
 id: 13114 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '13114'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13114'
 id: 13115 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '13115'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13115'
 id: 13116 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '13116'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13116'
 id: 13117 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '13117'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13117'
 id: 13118 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13118'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13118'
 id: 13119 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '13119'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13119'
 id: 13120 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '13120'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13120'
 id: 13121 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '13121'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13121'
 id: 13122 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '13122'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13122'
 id: 13123 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13123'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13123'

 id: 13124 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13124'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13124'
 id: 13125 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '13125'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13125'
 id: 13126 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '13126'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13126'
 id: 13127 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13127'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13127'
 id: 13128 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '13128'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13128'
 id: 13129 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13129'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13129'
 id: 13130 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13130'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13130'
 id: 13131 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13131'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13131'
 id: 13132 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '13132'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13132'
 id: 13133 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '13133'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13133'
 id: 13134 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '13134'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13134'
 id: 13135 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '13135'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13135'
 id: 13136 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13136'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13136'
 id: 13137 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '13137'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13137'
 id: 13138 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13138'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13138'
 id: 13139 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '13139'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13139'
 id: 13140 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '13140'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13140'
 id: 13141 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13141'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13141'
 id: 13142 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13142'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13142'
 id: 13143 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '13143'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13143'
 id: 13144 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13144'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13144'
 id: 13145 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '13145'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13145'
 id: 13146 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13146'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13146'
 id: 13147 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '13147'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13147'
 id: 13148 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13148'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13148'
 id: 13149 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '13149'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13149'
 id: 13150 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '13150'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13150'
 id: 13151 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13151'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13151'
 id: 13152 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '13152'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13152'
 id: 13153 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '13153'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13153'
 id: 13154 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '13154'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13154'
 id: 13155 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13155'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13155'
 id: 13156 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '13156'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13156'
 id: 13157 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '13157'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13157'
 id: 13158 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13158'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13158'
 id: 13159 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '13159'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13159'
 id: 13160 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '13160'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13160'
 id: 13161 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13161'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13161'
 id: 13162 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '13162'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13162'
 id: 13163 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '13163'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13163'
 id: 13164 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13164'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13164'
 id: 13165 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13165'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13165'
 id: 13166 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13166'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13166'
 id: 13167 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '13167'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13167'
 id: 13168 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '13168'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13168'
 id: 13169 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '13169'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13169'
 id: 13170 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '13170'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13170'
 id: 13171 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '13171'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13171'
 id: 13172 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13172'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13172'
 id: 13173 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13173'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13173'
 id: 13174 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '13174'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13174'
 id: 13175 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '13175'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13175'
 id: 13176 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13176'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13176'
 id: 13177 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '13177'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13177'
 id: 13178 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '13178'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13178'
 id: 13179 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '13179'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13179'
 id: 13180 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13180'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13180'
 id: 13181 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '13181'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13181'
 id: 13182 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13182'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13182'
 id: 13183 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '13183'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13183'
 id: 13184 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '13184'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13184'
 id: 13185 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13185'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13185'
 id: 13186 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '13186'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13186'
 id: 13187 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '13187'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13187'
 id: 13188 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '13188'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13188'
 id: 13189 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13189'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13189'
 id: 13190 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '13190'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13190'
 id: 13191 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13191'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13191'
 id: 13192 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '13192'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13192'
 id: 13193 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '13193'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13193'
 id: 13194 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13194'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13194'
 id: 13195 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13195'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13195'
 id: 13196 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '13196'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13196'
 id: 13197 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13197'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13197'
 id: 13198 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13198'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13198'
 id: 13199 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '13199'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13199'
 id: 13200 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13200'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13200'
 id: 13201 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13201'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13201'
 id: 13202 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13202'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13202'
 id: 13203 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13203'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13203'
 id: 13204 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '13204'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13204'
 id: 13205 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '13205'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13205'
 id: 13206 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13206'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13206'
 id: 13207 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '13207'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13207'
 id: 13208 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13208'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13208'
 id: 13209 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '13209'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13209'
 id: 13210 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13210'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13210'
 id: 13211 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13211'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13211'
 id: 13212 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '13212'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13212'
 id: 13213 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '13213'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13213'
 id: 13214 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13214'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13214'
 id: 13215 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13215'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13215'
 id: 13216 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '13216'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13216'
 id: 13217 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '13217'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13217'
 id: 13218 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '13218'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13218'
 id: 13219 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '13219'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13219'
 id: 13220 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '13220'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13220'
 id: 13221 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13221'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13221'
 id: 13222 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '13222'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13222'
 id: 13223 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13223'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13223'
 id: 13224 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '13224'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13224'
 id: 13225 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '13225'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13225'
 id: 13226 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13226'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13226'
 id: 13227 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '13227'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13227'
 id: 13228 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '13228'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13228'
 id: 13229 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '13229'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13229'
 id: 13230 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13230'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13230'
 id: 13231 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '13231'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13231'
 id: 13232 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13232'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13232'
 id: 13233 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13233'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13233'
 id: 13234 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13234'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13234'
 id: 13235 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '13235'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13235'
 id: 13236 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '13236'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13236'
 id: 13237 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13237'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13237'
 id: 13238 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '13238'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13238'
 id: 13239 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13239'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13239'
 id: 13240 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13240'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13240'
 id: 13241 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13241'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13241'
 id: 13242 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '13242'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13242'
 id: 13243 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '13243'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13243'
 id: 13244 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '13244'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13244'
 id: 13245 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13245'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13245'
 id: 13246 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '13246'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13246'
 id: 13247 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13247'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13247'
 id: 13248 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '13248'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13248'
 id: 13249 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '13249'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13249'
 id: 13250 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '13250'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13250'
 id: 13251 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '13251'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13251'
 id: 13252 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13252'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13252'
 id: 13253 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13253'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13253'
 id: 13254 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '13254'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13254'
 id: 13255 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '13255'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13255'
 id: 13256 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '13256'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13256'
 id: 13257 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13257'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13257'
 id: 13258 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13258'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13258'
 id: 13259 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '13259'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13259'
 id: 13260 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13260'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13260'
 id: 13261 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13261'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13261'
 id: 13262 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '13262'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13262'
 id: 13263 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '13263'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13263'
 id: 13264 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '13264'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13264'
 id: 13265 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '13265'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13265'
 id: 13266 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '13266'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13266'
 id: 13267 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '13267'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13267'
 id: 13268 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '13268'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13268'
 id: 13269 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13269'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13269'
 id: 13270 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '13270'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13270'
 id: 13271 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13271'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13271'
 id: 13272 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '13272'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13272'
 id: 13273 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '13273'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13273'
 id: 13274 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13274'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13274'

 id: 13275 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13275'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13275'
 id: 13276 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '13276'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13276'
 id: 13277 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '13277'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13277'
 id: 13278 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13278'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13278'
 id: 13279 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13279'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13279'
 id: 13280 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13280'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13280'
 id: 13281 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13281'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13281'
 id: 13282 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13282'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13282'
 id: 13283 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13283'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13283'
 id: 13284 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '13284'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13284'
 id: 13285 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13285'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13285'
 id: 13286 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '13286'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13286'
 id: 13287 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13287'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13287'
 id: 13288 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '13288'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13288'
 id: 13289 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13289'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13289'
 id: 13290 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '13290'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13290'
 id: 13291 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13291'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13291'
 id: 13292 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13292'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13292'
 id: 13293 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '13293'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13293'
 id: 13294 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13294'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13294'
 id: 13295 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '13295'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13295'
 id: 13296 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '13296'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13296'
 id: 13297 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13297'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13297'
 id: 13298 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13298'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13298'
 id: 13299 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13299'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13299'
 id: 13300 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '13300'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13300'
 id: 13301 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13301'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13301'
 id: 13302 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '13302'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13302'
 id: 13303 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13303'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13303'
 id: 13304 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '13304'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13304'
 id: 13305 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '13305'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13305'
 id: 13306 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '13306'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13306'
 id: 13307 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13307'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13307'
 id: 13308 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13308'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13308'
 id: 13309 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '13309'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13309'
 id: 13310 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '13310'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13310'
 id: 13311 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '13311'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13311'
 id: 13312 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '13312'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13312'
 id: 13313 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '13313'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13313'
 id: 13314 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13314'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13314'
 id: 13315 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '13315'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13315'
 id: 13316 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '13316'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13316'
 id: 13317 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13317'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13317'
 id: 13318 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '13318'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13318'
 id: 13319 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13319'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13319'
 id: 13320 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13320'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13320'
 id: 13321 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13321'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13321'
 id: 13322 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '13322'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13322'
 id: 13323 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13323'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13323'
 id: 13324 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '13324'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13324'
 id: 13325 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13325'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13325'

 id: 13326 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13326'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13326'
 id: 13327 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '13327'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13327'
 id: 13328 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13328'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13328'
 id: 13329 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '13329'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13329'
 id: 13330 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13330'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13330'
 id: 13331 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '13331'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13331'
 id: 13332 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '13332'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13332'
 id: 13333 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13333'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13333'
 id: 13334 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '13334'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13334'
 id: 13335 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13335'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13335'
 id: 13336 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '13336'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13336'
 id: 13337 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13337'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13337'
 id: 13338 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '13338'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13338'
 id: 13339 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13339'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13339'
 id: 13340 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13340'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13340'
 id: 13341 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '13341'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13341'
 id: 13342 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13342'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13342'
 id: 13343 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13343'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13343'
 id: 13344 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '13344'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13344'
 id: 13345 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13345'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13345'
 id: 13346 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '13346'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13346'
 id: 13347 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '13347'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13347'
 id: 13348 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '13348'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13348'
 id: 13349 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13349'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13349'
 id: 13350 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '13350'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13350'
 id: 13351 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '13351'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13351'
 id: 13352 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '13352'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13352'
 id: 13353 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13353'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13353'
 id: 13354 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '13354'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13354'
 id: 13355 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13355'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13355'
 id: 13356 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '13356'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13356'
 id: 13357 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '13357'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13357'
 id: 13358 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '13358'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13358'
 id: 13359 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '13359'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13359'
 id: 13360 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '13360'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13360'
 id: 13361 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13361'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13361'
 id: 13362 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '13362'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13362'
 id: 13363 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '13363'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13363'
 id: 13364 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13364'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13364'
 id: 13365 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13365'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13365'
 id: 13366 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '13366'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13366'
 id: 13367 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '13367'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13367'
 id: 13368 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '13368'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13368'
 id: 13369 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '13369'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13369'
 id: 13370 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '13370'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13370'
 id: 13371 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13371'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13371'
 id: 13372 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13372'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13372'
 id: 13373 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '13373'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13373'
 id: 13374 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13374'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13374'
 id: 13375 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13375'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13375'
 id: 13376 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '13376'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13376'
 id: 13377 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '13377'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13377'
 id: 13378 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '13378'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13378'
 id: 13379 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '13379'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13379'
 id: 13380 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13380'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13380'
 id: 13381 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '13381'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13381'
 id: 13382 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13382'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13382'
 id: 13383 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13383'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13383'
 id: 13384 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13384'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13384'
 id: 13385 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '13385'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13385'
 id: 13386 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13386'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13386'
 id: 13387 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '13387'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13387'
 id: 13388 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13388'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13388'
 id: 13389 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '13389'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13389'
 id: 13390 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '13390'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13390'
 id: 13391 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13391'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13391'
 id: 13392 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13392'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13392'
 id: 13393 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '13393'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13393'
 id: 13394 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '13394'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13394'
 id: 13395 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '13395'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13395'
 id: 13396 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13396'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13396'
 id: 13397 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13397'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13397'
 id: 13398 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '13398'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13398'
 id: 13399 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '13399'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13399'
 id: 13400 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '13400'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13400'
 id: 13401 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13401'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13401'
 id: 13402 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '13402'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13402'
 id: 13403 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13403'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13403'
 id: 13404 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '13404'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13404'
 id: 13405 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13405'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13405'
 id: 13406 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13406'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13406'
 id: 13407 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13407'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13407'
 id: 13408 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '13408'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13408'
 id: 13409 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '13409'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13409'
 id: 13410 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '13410'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13410'
 id: 13411 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '13411'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13411'
 id: 13412 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13412'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13412'
 id: 13413 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '13413'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13413'
 id: 13414 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '13414'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13414'
 id: 13415 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '13415'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13415'
 id: 13416 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '13416'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13416'
 id: 13417 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '13417'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13417'
 id: 13418 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13418'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13418'
 id: 13419 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '13419'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13419'
 id: 13420 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13420'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13420'
 id: 13421 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13421'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13421'
 id: 13422 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '13422'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13422'
 id: 13423 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '13423'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13423'
 id: 13424 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13424'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13424'
 id: 13425 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '13425'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13425'
 id: 13426 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13426'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13426'

 id: 13427 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13427'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13427'
 id: 13428 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13428'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13428'
 id: 13429 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '13429'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13429'
 id: 13430 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '13430'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13430'
 id: 13431 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '13431'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13431'
 id: 13432 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '13432'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13432'
 id: 13433 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '13433'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13433'
 id: 13434 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13434'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13434'
 id: 13435 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13435'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13435'
 id: 13436 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13436'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13436'
 id: 13437 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13437'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13437'
 id: 13438 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '13438'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13438'
 id: 13439 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13439'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13439'
 id: 13440 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '13440'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13440'
 id: 13441 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '13441'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13441'
 id: 13442 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13442'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13442'
 id: 13443 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '13443'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13443'
 id: 13444 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13444'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13444'
 id: 13445 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13445'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13445'
 id: 13446 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '13446'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13446'
 id: 13447 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '13447'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13447'
 id: 13448 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '13448'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13448'
 id: 13449 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '13449'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13449'
 id: 13450 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13450'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13450'
 id: 13451 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13451'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13451'
 id: 13452 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13452'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13452'
 id: 13453 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '13453'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13453'
 id: 13454 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13454'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13454'
 id: 13455 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '13455'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13455'
 id: 13456 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '13456'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13456'
 id: 13457 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13457'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13457'
 id: 13458 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13458'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13458'
 id: 13459 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13459'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13459'
 id: 13460 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13460'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13460'
 id: 13461 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13461'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13461'
 id: 13462 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '13462'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13462'
 id: 13463 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13463'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13463'
 id: 13464 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13464'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13464'
 id: 13465 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '13465'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13465'
 id: 13466 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13466'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13466'
 id: 13467 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13467'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13467'
 id: 13468 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13468'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13468'
 id: 13469 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '13469'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13469'
 id: 13470 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '13470'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13470'
 id: 13471 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '13471'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13471'
 id: 13472 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13472'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13472'
 id: 13473 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '13473'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13473'
 id: 13474 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '13474'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13474'
 id: 13475 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13475'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13475'
 id: 13476 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '13476'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13476'
 id: 13477 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '13477'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13477'
 id: 13478 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13478'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13478'
 id: 13479 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '13479'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13479'
 id: 13480 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13480'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13480'
 id: 13481 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '13481'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13481'
 id: 13482 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '13482'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13482'
 id: 13483 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '13483'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13483'
 id: 13484 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13484'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13484'
 id: 13485 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13485'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13485'
 id: 13486 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13486'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13486'
 id: 13487 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13487'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13487'
 id: 13488 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '13488'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13488'
 id: 13489 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '13489'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13489'
 id: 13490 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13490'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13490'
 id: 13491 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '13491'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13491'
 id: 13492 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13492'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13492'
 id: 13493 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13493'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13493'
 id: 13494 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '13494'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13494'
 id: 13495 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '13495'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13495'
 id: 13496 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13496'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13496'
 id: 13497 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '13497'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13497'
 id: 13498 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '13498'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13498'
 id: 13499 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13499'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13499'
 id: 13500 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13500'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13500'
 id: 13501 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13501'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13501'
 id: 13502 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '13502'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13502'
 id: 13503 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13503'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13503'
 id: 13504 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13504'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13504'
 id: 13505 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '13505'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13505'
 id: 13506 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13506'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13506'
 id: 13507 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13507'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13507'
 id: 13508 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '13508'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13508'
 id: 13509 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '13509'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13509'
 id: 13510 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13510'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13510'
 id: 13511 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13511'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13511'
 id: 13512 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '13512'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13512'
 id: 13513 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '13513'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13513'
 id: 13514 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '13514'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13514'
 id: 13515 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13515'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13515'
 id: 13516 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '13516'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13516'
 id: 13517 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '13517'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13517'
 id: 13518 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '13518'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13518'
 id: 13519 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13519'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13519'
 id: 13520 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13520'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13520'
 id: 13521 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '13521'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13521'
 id: 13522 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '13522'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13522'
 id: 13523 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13523'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13523'
 id: 13524 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '13524'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13524'
 id: 13525 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13525'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13525'
 id: 13526 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '13526'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13526'
 id: 13527 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13527'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13527'
 id: 13528 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13528'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13528'
 id: 13529 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '13529'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13529'
 id: 13530 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '13530'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13530'
 id: 13531 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '13531'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13531'
 id: 13532 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '13532'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13532'
 id: 13533 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '13533'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13533'
 id: 13534 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '13534'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13534'
 id: 13535 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13535'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13535'
 id: 13536 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '13536'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13536'
 id: 13537 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13537'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13537'
 id: 13538 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13538'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13538'
 id: 13539 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13539'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13539'
 id: 13540 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '13540'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13540'
 id: 13541 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13541'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13541'
 id: 13542 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13542'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13542'
 id: 13543 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '13543'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13543'
 id: 13544 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '13544'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13544'
 id: 13545 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '13545'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13545'
 id: 13546 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13546'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13546'
 id: 13547 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13547'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13547'
 id: 13548 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13548'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13548'
 id: 13549 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13549'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13549'
 id: 13550 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '13550'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13550'
 id: 13551 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13551'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13551'
 id: 13552 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '13552'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13552'
 id: 13553 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '13553'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13553'
 id: 13554 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '13554'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13554'
 id: 13555 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13555'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13555'
 id: 13556 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13556'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13556'
 id: 13557 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '13557'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13557'
 id: 13558 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13558'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13558'
 id: 13559 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13559'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13559'
 id: 13560 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '13560'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13560'
 id: 13561 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13561'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13561'
 id: 13562 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '13562'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13562'
 id: 13563 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13563'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13563'
 id: 13564 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '13564'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13564'
 id: 13565 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '13565'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13565'
 id: 13566 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '13566'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13566'
 id: 13567 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13567'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13567'
 id: 13568 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13568'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13568'
 id: 13569 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13569'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13569'
 id: 13570 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '13570'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13570'
 id: 13571 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '13571'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13571'
 id: 13572 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '13572'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13572'
 id: 13573 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '13573'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13573'
 id: 13574 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '13574'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13574'
 id: 13575 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '13575'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13575'
 id: 13576 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '13576'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13576'
 id: 13577 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13577'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13577'
 id: 13578 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '13578'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13578'
 id: 13579 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '13579'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13579'
 id: 13580 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '13580'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13580'
 id: 13581 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13581'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13581'
 id: 13582 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13582'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13582'
 id: 13583 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '13583'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13583'
 id: 13584 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13584'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13584'
 id: 13585 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13585'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13585'
 id: 13586 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '13586'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13586'
 id: 13587 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13587'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13587'
 id: 13588 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '13588'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13588'
 id: 13589 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '13589'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13589'
 id: 13590 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13590'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13590'
 id: 13591 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13591'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13591'
 id: 13592 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '13592'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13592'
 id: 13593 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13593'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13593'
 id: 13594 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '13594'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13594'
 id: 13595 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '13595'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13595'
 id: 13596 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13596'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13596'
 id: 13597 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '13597'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13597'
 id: 13598 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '13598'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13598'
 id: 13599 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13599'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13599'
 id: 13600 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '13600'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13600'
 id: 13601 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13601'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13601'
 id: 13602 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13602'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13602'
 id: 13603 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13603'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13603'
 id: 13604 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13604'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13604'
 id: 13605 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '13605'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13605'
 id: 13606 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13606'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13606'
 id: 13607 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13607'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13607'
 id: 13608 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '13608'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13608'
 id: 13609 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '13609'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13609'
 id: 13610 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13610'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13610'
 id: 13611 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13611'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13611'
 id: 13612 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13612'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13612'
 id: 13613 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13613'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13613'
 id: 13614 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '13614'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13614'
 id: 13615 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13615'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13615'
 id: 13616 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '13616'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13616'
 id: 13617 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '13617'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13617'
 id: 13618 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '13618'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13618'
 id: 13619 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '13619'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13619'
 id: 13620 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '13620'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13620'
 id: 13621 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '13621'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13621'
 id: 13622 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13622'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13622'
 id: 13623 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13623'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13623'
 id: 13624 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13624'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13624'
 id: 13625 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13625'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13625'
 id: 13626 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13626'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13626'
 id: 13627 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13627'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13627'
 id: 13628 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13628'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13628'
 id: 13629 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '13629'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13629'
 id: 13630 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '13630'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13630'

 id: 13631 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '13631'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13631'
 id: 13632 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '13632'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13632'
 id: 13633 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13633'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13633'
 id: 13634 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13634'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13634'
 id: 13635 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13635'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13635'
 id: 13636 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '13636'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13636'
 id: 13637 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '13637'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13637'
 id: 13638 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '13638'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13638'
 id: 13639 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '13639'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13639'
 id: 13640 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13640'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13640'
 id: 13641 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '13641'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13641'
 id: 13642 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '13642'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13642'
 id: 13643 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '13643'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13643'
 id: 13644 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '13644'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13644'
 id: 13645 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13645'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13645'
 id: 13646 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13646'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13646'
 id: 13647 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13647'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13647'
 id: 13648 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13648'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13648'
 id: 13649 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '13649'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13649'
 id: 13650 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13650'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13650'
 id: 13651 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13651'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13651'
 id: 13652 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13652'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13652'
 id: 13653 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '13653'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13653'
 id: 13654 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '13654'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13654'
 id: 13655 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '13655'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13655'
 id: 13656 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13656'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13656'
 id: 13657 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '13657'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13657'
 id: 13658 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13658'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13658'
 id: 13659 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '13659'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13659'
 id: 13660 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13660'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13660'
 id: 13661 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '13661'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13661'
 id: 13662 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '13662'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13662'
 id: 13663 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13663'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13663'
 id: 13664 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13664'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13664'
 id: 13665 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '13665'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13665'
 id: 13666 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '13666'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13666'
 id: 13667 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '13667'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13667'
 id: 13668 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13668'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13668'
 id: 13669 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '13669'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13669'
 id: 13670 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '13670'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13670'
 id: 13671 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '13671'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13671'
 id: 13672 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13672'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13672'
 id: 13673 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '13673'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13673'
 id: 13674 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '13674'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13674'
 id: 13675 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '13675'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13675'
 id: 13676 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '13676'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13676'
 id: 13677 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13677'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13677'
 id: 13678 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '13678'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13678'
 id: 13679 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '13679'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13679'
 id: 13680 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13680'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13680'
 id: 13681 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '13681'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13681'
 id: 13682 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13682'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13682'
 id: 13683 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13683'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13683'
 id: 13684 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '13684'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13684'
 id: 13685 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13685'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13685'
 id: 13686 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13686'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13686'
 id: 13687 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13687'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13687'
 id: 13688 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13688'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13688'
 id: 13689 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '13689'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13689'
 id: 13690 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13690'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13690'
 id: 13691 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13691'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13691'
 id: 13692 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '13692'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13692'
 id: 13693 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13693'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13693'
 id: 13694 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '13694'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13694'
 id: 13695 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '13695'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13695'
 id: 13696 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13696'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13696'
 id: 13697 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '13697'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13697'
 id: 13698 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '13698'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13698'
 id: 13699 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '13699'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13699'
 id: 13700 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13700'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13700'
 id: 13701 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '13701'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13701'
 id: 13702 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '13702'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13702'
 id: 13703 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '13703'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13703'
 id: 13704 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '13704'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13704'
 id: 13705 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13705'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13705'
 id: 13706 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '13706'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13706'
 id: 13707 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '13707'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13707'
 id: 13708 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '13708'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13708'
 id: 13709 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13709'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13709'
 id: 13710 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '13710'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13710'
 id: 13711 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '13711'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13711'
 id: 13712 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '13712'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13712'
 id: 13713 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '13713'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13713'
 id: 13714 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '13714'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13714'
 id: 13715 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '13715'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13715'
 id: 13716 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '13716'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13716'
 id: 13717 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13717'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13717'
 id: 13718 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13718'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13718'
 id: 13719 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '13719'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13719'
 id: 13720 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13720'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13720'
 id: 13721 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '13721'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13721'
 id: 13722 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '13722'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13722'
 id: 13723 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '13723'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13723'
 id: 13724 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13724'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13724'
 id: 13725 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13725'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13725'
 id: 13726 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '13726'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13726'
 id: 13727 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '13727'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13727'
 id: 13728 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '13728'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13728'
 id: 13729 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '13729'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13729'
 id: 13730 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '13730'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13730'
 id: 13731 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '13731'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13731'
 id: 13732 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13732'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13732'
 id: 13733 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '13733'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13733'
 id: 13734 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '13734'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13734'
 id: 13735 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13735'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13735'
 id: 13736 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '13736'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13736'
 id: 13737 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13737'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13737'
 id: 13738 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '13738'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13738'
 id: 13739 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '13739'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13739'
 id: 13740 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '13740'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13740'
 id: 13741 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '13741'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13741'
 id: 13742 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '13742'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13742'
 id: 13743 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13743'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13743'
 id: 13744 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13744'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13744'
 id: 13745 // word: 66
UPDATE job_vacancies SET domain_id =  '66' where raw_id = '13745'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13745'
 id: 13746 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '13746'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13746'
 id: 13747 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13747'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13747'
 id: 13748 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '13748'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13748'
 id: 13749 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '13749'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13749'
 id: 13750 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13750'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13750'
 id: 13751 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13751'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13751'
 id: 13752 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '13752'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13752'
 id: 13753 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '13753'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13753'
 id: 13754 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13754'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13754'
 id: 13755 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '13755'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13755'
 id: 13756 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '13756'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13756'
 id: 13757 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '13757'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13757'
 id: 13758 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '13758'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13758'
 id: 13759 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '13759'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13759'
 id: 13760 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13760'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13760'
 id: 13761 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13761'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13761'
 id: 13762 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13762'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13762'
 id: 13763 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13763'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13763'
 id: 13764 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13764'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13764'
 id: 13765 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13765'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13765'
 id: 13766 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '13766'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13766'
 id: 13767 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13767'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13767'
 id: 13768 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13768'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13768'
 id: 13769 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13769'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13769'
 id: 13770 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '13770'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13770'
 id: 13771 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13771'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13771'
 id: 13772 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13772'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13772'
 id: 13773 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '13773'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13773'
 id: 13774 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '13774'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13774'
 id: 13775 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13775'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13775'
 id: 13776 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '13776'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13776'
 id: 13777 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '13777'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13777'
 id: 13778 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '13778'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13778'
 id: 13779 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13779'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13779'
 id: 13780 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '13780'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13780'
 id: 13781 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '13781'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13781'
 id: 13782 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13782'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13782'
 id: 13783 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '13783'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13783'
 id: 13784 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13784'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13784'
 id: 13785 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13785'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13785'
 id: 13786 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13786'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13786'
 id: 13787 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '13787'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13787'
 id: 13788 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '13788'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13788'
 id: 13789 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '13789'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13789'
 id: 13790 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13790'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13790'
 id: 13791 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13791'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13791'
 id: 13792 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '13792'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13792'
 id: 13793 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '13793'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13793'
 id: 13794 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '13794'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13794'
 id: 13795 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13795'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13795'
 id: 13796 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13796'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13796'
 id: 13797 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '13797'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13797'
 id: 13798 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13798'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13798'
 id: 13799 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13799'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13799'
 id: 13800 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13800'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13800'
 id: 13801 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '13801'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13801'
 id: 13802 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '13802'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13802'
 id: 13803 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '13803'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13803'
 id: 13804 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13804'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13804'
 id: 13805 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '13805'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13805'
 id: 13806 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13806'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13806'
 id: 13807 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '13807'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13807'
 id: 13808 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13808'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13808'
 id: 13809 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13809'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13809'
 id: 13810 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '13810'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13810'
 id: 13811 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '13811'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13811'
 id: 13812 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '13812'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13812'
 id: 13813 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '13813'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13813'
 id: 13814 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13814'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13814'
 id: 13815 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '13815'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13815'
 id: 13816 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '13816'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13816'
 id: 13817 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13817'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13817'
 id: 13818 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '13818'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13818'
 id: 13819 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '13819'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13819'
 id: 13820 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '13820'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13820'
 id: 13821 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '13821'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13821'
 id: 13822 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '13822'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13822'
 id: 13823 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13823'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13823'
 id: 13824 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13824'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13824'
 id: 13825 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '13825'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13825'
 id: 13826 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '13826'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13826'
 id: 13827 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '13827'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13827'
 id: 13828 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '13828'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13828'
 id: 13829 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13829'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13829'
 id: 13830 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '13830'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13830'
 id: 13831 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '13831'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13831'
 id: 13832 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '13832'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13832'
 id: 13833 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '13833'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13833'
 id: 13834 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '13834'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13834'
 id: 13835 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '13835'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13835'
 id: 13836 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '13836'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13836'
 id: 13837 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '13837'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13837'
 id: 13838 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '13838'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13838'
 id: 13839 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13839'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13839'
 id: 13840 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '13840'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13840'
 id: 13841 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13841'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13841'
 id: 13842 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '13842'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13842'
 id: 13843 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '13843'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13843'
 id: 13844 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '13844'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13844'
 id: 13845 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13845'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13845'
 id: 13846 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '13846'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13846'
 id: 13847 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '13847'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13847'
 id: 13848 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13848'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13848'
 id: 13849 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '13849'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13849'
 id: 13850 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '13850'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13850'
 id: 13851 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '13851'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13851'
 id: 13852 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '13852'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13852'
 id: 13853 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13853'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13853'
 id: 13854 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '13854'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13854'
 id: 13855 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '13855'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13855'
 id: 13856 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13856'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13856'
 id: 13857 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13857'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13857'
 id: 13858 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '13858'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13858'
 id: 13859 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13859'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13859'
 id: 13860 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13860'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13860'
 id: 13861 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13861'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13861'
 id: 13862 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '13862'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13862'
 id: 13863 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '13863'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13863'
 id: 13864 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '13864'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13864'
 id: 13865 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13865'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13865'
 id: 13866 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '13866'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13866'
 id: 13867 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '13867'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13867'
 id: 13868 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13868'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13868'
 id: 13869 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13869'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13869'
 id: 13870 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13870'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13870'
 id: 13871 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13871'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13871'
 id: 13872 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13872'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13872'
 id: 13873 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13873'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13873'
 id: 13874 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13874'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13874'
 id: 13875 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '13875'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13875'
 id: 13876 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13876'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13876'
 id: 13877 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '13877'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13877'
 id: 13878 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '13878'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13878'
 id: 13879 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13879'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13879'
 id: 13880 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '13880'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13880'
 id: 13881 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13881'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13881'
 id: 13882 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '13882'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13882'
 id: 13883 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '13883'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13883'
 id: 13884 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13884'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13884'
 id: 13885 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13885'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13885'
 id: 13886 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '13886'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13886'
 id: 13887 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13887'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13887'
 id: 13888 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '13888'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13888'
 id: 13889 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '13889'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13889'
 id: 13890 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '13890'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13890'
 id: 13891 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13891'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13891'
 id: 13892 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13892'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13892'
 id: 13893 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '13893'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13893'
 id: 13894 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13894'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13894'
 id: 13895 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '13895'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13895'
 id: 13896 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '13896'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13896'
 id: 13897 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '13897'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13897'
 id: 13898 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13898'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13898'
 id: 13899 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13899'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13899'
 id: 13900 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13900'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13900'
 id: 13901 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '13901'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13901'
 id: 13902 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13902'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13902'
 id: 13903 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '13903'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13903'
 id: 13904 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13904'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13904'
 id: 13905 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '13905'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13905'
 id: 13906 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '13906'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13906'
 id: 13907 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13907'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13907'
 id: 13908 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13908'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13908'
 id: 13909 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '13909'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13909'
 id: 13910 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13910'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13910'
 id: 13911 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '13911'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13911'
 id: 13912 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '13912'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13912'
 id: 13913 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '13913'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13913'
 id: 13914 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '13914'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13914'
 id: 13915 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '13915'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13915'
 id: 13916 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '13916'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13916'
 id: 13917 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13917'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13917'
 id: 13918 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '13918'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13918'
 id: 13919 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '13919'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13919'
 id: 13920 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13920'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13920'
 id: 13921 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13921'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13921'
 id: 13922 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '13922'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13922'
 id: 13923 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '13923'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13923'
 id: 13924 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '13924'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13924'
 id: 13925 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13925'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13925'
 id: 13926 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '13926'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13926'
 id: 13927 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13927'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13927'
 id: 13928 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13928'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13928'
 id: 13929 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13929'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13929'
 id: 13930 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '13930'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13930'
 id: 13931 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '13931'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13931'
 id: 13932 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13932'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13932'
 id: 13933 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '13933'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13933'
 id: 13934 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13934'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13934'
 id: 13935 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '13935'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13935'
 id: 13936 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13936'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13936'
 id: 13937 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '13937'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13937'
 id: 13938 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '13938'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13938'
 id: 13939 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '13939'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13939'
 id: 13940 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '13940'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13940'
 id: 13941 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13941'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13941'
 id: 13942 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13942'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13942'
 id: 13943 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13943'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13943'
 id: 13944 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13944'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13944'
 id: 13945 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13945'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13945'
 id: 13946 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13946'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13946'
 id: 13947 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13947'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13947'
 id: 13948 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '13948'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13948'
 id: 13949 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13949'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13949'
 id: 13950 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '13950'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13950'
 id: 13951 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '13951'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13951'
 id: 13952 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '13952'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13952'
 id: 13953 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '13953'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13953'
 id: 13954 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '13954'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13954'
 id: 13955 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13955'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13955'
 id: 13956 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '13956'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13956'
 id: 13957 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '13957'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13957'
 id: 13958 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13958'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13958'
 id: 13959 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '13959'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13959'
 id: 13960 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '13960'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13960'
 id: 13961 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13961'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13961'
 id: 13962 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '13962'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13962'
 id: 13963 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '13963'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13963'
 id: 13964 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '13964'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13964'
 id: 13965 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '13965'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13965'
 id: 13966 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '13966'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13966'
 id: 13967 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '13967'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13967'
 id: 13968 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13968'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13968'
 id: 13969 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '13969'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13969'
 id: 13970 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13970'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13970'
 id: 13971 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13971'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13971'
 id: 13972 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13972'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13972'
 id: 13973 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '13973'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13973'
 id: 13974 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '13974'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13974'
 id: 13975 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '13975'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13975'
 id: 13976 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13976'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13976'
 id: 13977 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '13977'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13977'
 id: 13978 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '13978'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13978'
 id: 13979 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13979'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13979'
 id: 13980 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13980'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13980'
 id: 13981 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '13981'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13981'
 id: 13982 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '13982'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13982'
 id: 13983 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '13983'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13983'

 id: 13984 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13984'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13984'
 id: 13985 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '13985'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13985'
 id: 13986 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13986'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13986'
 id: 13987 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '13987'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13987'
 id: 13988 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13988'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13988'
 id: 13989 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '13989'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13989'
 id: 13990 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13990'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13990'
 id: 13991 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '13991'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13991'
 id: 13992 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '13992'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13992'
 id: 13993 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '13993'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13993'
 id: 13994 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '13994'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13994'
 id: 13995 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '13995'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13995'
 id: 13996 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '13996'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13996'
 id: 13997 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '13997'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13997'
 id: 13998 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '13998'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13998'
 id: 13999 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '13999'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '13999'
 id: 14000 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '14000'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14000'
 id: 14001 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '14001'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14001'
 id: 14002 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '14002'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14002'
 id: 14003 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14003'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14003'
 id: 14004 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '14004'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14004'
 id: 14005 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14005'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14005'
 id: 14006 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '14006'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14006'
 id: 14007 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14007'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14007'
 id: 14008 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '14008'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14008'
 id: 14009 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '14009'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14009'
 id: 14010 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '14010'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14010'
 id: 14011 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '14011'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14011'
 id: 14012 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '14012'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14012'
 id: 14013 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14013'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14013'
 id: 14014 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14014'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14014'
 id: 14015 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '14015'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14015'
 id: 14016 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14016'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14016'
 id: 14017 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14017'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14017'
 id: 14018 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '14018'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14018'
 id: 14019 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '14019'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14019'
 id: 14020 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14020'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14020'
 id: 14021 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14021'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14021'
 id: 14022 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14022'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14022'
 id: 14023 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '14023'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14023'
 id: 14024 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14024'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14024'
 id: 14025 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14025'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14025'
 id: 14026 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '14026'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14026'
 id: 14027 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14027'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14027'
 id: 14028 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14028'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14028'
 id: 14029 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14029'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14029'
 id: 14030 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '14030'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14030'
 id: 14031 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14031'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14031'
 id: 14032 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '14032'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14032'
 id: 14033 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '14033'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14033'
 id: 14034 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '14034'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14034'
 id: 14035 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '14035'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14035'
 id: 14036 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14036'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14036'
 id: 14037 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '14037'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14037'
 id: 14038 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '14038'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14038'
 id: 14039 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14039'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14039'
 id: 14040 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14040'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14040'
 id: 14041 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '14041'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14041'
 id: 14042 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14042'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14042'
 id: 14043 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '14043'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14043'
 id: 14044 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14044'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14044'
 id: 14045 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14045'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14045'
 id: 14046 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '14046'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14046'
 id: 14047 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14047'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14047'
 id: 14048 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14048'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14048'
 id: 14049 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14049'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14049'
 id: 14050 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14050'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14050'
 id: 14051 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14051'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14051'
 id: 14052 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '14052'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14052'
 id: 14053 // word: 52
UPDATE job_vacancies SET domain_id =  '52' where raw_id = '14053'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14053'
 id: 14054 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '14054'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14054'
 id: 14055 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '14055'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14055'
 id: 14056 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14056'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14056'
 id: 14057 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14057'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14057'
 id: 14058 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14058'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14058'
 id: 14059 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '14059'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14059'
 id: 14060 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '14060'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14060'
 id: 14061 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '14061'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14061'
 id: 14062 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '14062'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14062'
 id: 14063 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14063'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14063'
 id: 14064 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14064'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14064'
 id: 14065 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14065'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14065'
 id: 14066 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14066'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14066'
 id: 14067 // word: 16
UPDATE job_vacancies SET domain_id =  '16' where raw_id = '14067'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14067'
 id: 14068 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14068'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14068'
 id: 14069 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14069'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14069'
 id: 14070 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14070'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14070'
 id: 14071 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '14071'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14071'
 id: 14072 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '14072'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14072'
 id: 14073 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '14073'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14073'
 id: 14074 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '14074'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14074'
 id: 14075 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '14075'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14075'
 id: 14076 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14076'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14076'
 id: 14077 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14077'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14077'
 id: 14078 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '14078'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14078'
 id: 14079 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '14079'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14079'
 id: 14080 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14080'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14080'
 id: 14081 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '14081'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14081'
 id: 14082 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14082'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14082'
 id: 14083 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '14083'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14083'
 id: 14084 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14084'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14084'

 id: 14085 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '14085'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14085'
 id: 14086 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '14086'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14086'
 id: 14087 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '14087'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14087'
 id: 14088 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '14088'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14088'
 id: 14089 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14089'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14089'
 id: 14090 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14090'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14090'
 id: 14091 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14091'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14091'
 id: 14092 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '14092'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14092'
 id: 14093 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14093'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14093'
 id: 14094 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '14094'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14094'
 id: 14095 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '14095'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14095'
 id: 14096 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '14096'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14096'
 id: 14097 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '14097'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14097'
 id: 14098 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14098'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14098'
 id: 14099 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '14099'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14099'
 id: 14100 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '14100'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14100'
 id: 14101 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '14101'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14101'
 id: 14102 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '14102'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14102'
 id: 14103 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14103'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14103'
 id: 14104 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '14104'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14104'
 id: 14105 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '14105'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14105'
 id: 14106 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '14106'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14106'
 id: 14107 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14107'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14107'
 id: 14108 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14108'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14108'
 id: 14109 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14109'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14109'
 id: 14110 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14110'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14110'
 id: 14111 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14111'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14111'
 id: 14112 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '14112'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14112'
 id: 14113 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14113'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14113'
 id: 14114 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '14114'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14114'
 id: 14115 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14115'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14115'
 id: 14116 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14116'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14116'
 id: 14117 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '14117'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14117'
 id: 14118 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '14118'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14118'
 id: 14119 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '14119'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14119'
 id: 14120 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14120'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14120'
 id: 14121 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '14121'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14121'
 id: 14122 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '14122'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14122'
 id: 14123 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '14123'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14123'
 id: 14124 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '14124'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14124'
 id: 14125 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '14125'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14125'
 id: 14126 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14126'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14126'
 id: 14127 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14127'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14127'
 id: 14128 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '14128'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14128'
 id: 14129 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '14129'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14129'
 id: 14130 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14130'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14130'
 id: 14131 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14131'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14131'
 id: 14132 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '14132'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14132'
 id: 14133 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '14133'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14133'
 id: 14134 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '14134'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14134'
 id: 14135 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '14135'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14135'
 id: 14136 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '14136'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14136'
 id: 14137 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14137'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14137'
 id: 14138 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14138'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14138'
 id: 14139 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '14139'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14139'
 id: 14140 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '14140'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14140'
 id: 14141 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14141'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14141'
 id: 14142 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14142'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14142'
 id: 14143 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '14143'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14143'
 id: 14144 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '14144'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14144'
 id: 14145 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '14145'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14145'
 id: 14146 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '14146'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14146'
 id: 14147 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14147'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14147'
 id: 14148 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14148'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14148'
 id: 14149 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14149'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14149'
 id: 14150 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14150'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14150'
 id: 14151 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14151'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14151'
 id: 14152 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14152'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14152'
 id: 14153 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '14153'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14153'
 id: 14154 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '14154'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14154'
 id: 14155 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14155'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14155'
 id: 14156 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '14156'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14156'
 id: 14157 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '14157'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14157'
 id: 14158 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '14158'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14158'
 id: 14159 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '14159'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14159'
 id: 14160 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14160'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14160'
 id: 14161 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14161'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14161'
 id: 14162 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14162'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14162'
 id: 14163 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14163'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14163'
 id: 14164 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '14164'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14164'
 id: 14165 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '14165'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14165'
 id: 14166 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '14166'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14166'
 id: 14167 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14167'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14167'
 id: 14168 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14168'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14168'
 id: 14169 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '14169'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14169'
 id: 14170 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '14170'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14170'
 id: 14171 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14171'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14171'
 id: 14172 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '14172'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14172'
 id: 14173 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14173'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14173'
 id: 14174 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14174'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14174'
 id: 14175 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14175'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14175'
 id: 14176 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14176'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14176'
 id: 14177 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '14177'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14177'
 id: 14178 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '14178'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14178'
 id: 14179 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14179'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14179'
 id: 14180 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14180'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14180'
 id: 14181 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14181'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14181'
 id: 14182 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14182'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14182'
 id: 14183 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '14183'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14183'
 id: 14184 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '14184'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14184'
 id: 14185 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '14185'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14185'
 id: 14186 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '14186'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14186'
 id: 14187 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '14187'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14187'
 id: 14188 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '14188'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14188'
 id: 14189 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14189'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14189'
 id: 14190 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '14190'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14190'
 id: 14191 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '14191'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14191'
 id: 14192 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14192'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14192'
 id: 14193 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14193'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14193'
 id: 14194 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '14194'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14194'
 id: 14195 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '14195'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14195'
 id: 14196 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14196'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14196'
 id: 14197 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '14197'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14197'
 id: 14198 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '14198'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14198'
 id: 14199 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '14199'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14199'
 id: 14200 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '14200'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14200'
 id: 14201 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14201'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14201'
 id: 14202 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14202'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14202'
 id: 14203 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14203'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14203'
 id: 14204 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '14204'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14204'
 id: 14205 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '14205'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14205'
 id: 14206 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14206'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14206'
 id: 14207 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14207'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14207'
 id: 14208 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '14208'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14208'
 id: 14209 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14209'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14209'
 id: 14210 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '14210'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14210'
 id: 14211 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14211'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14211'
 id: 14212 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14212'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14212'
 id: 14213 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14213'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14213'
 id: 14214 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '14214'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14214'
 id: 14215 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14215'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14215'
 id: 14216 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14216'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14216'
 id: 14217 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14217'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14217'
 id: 14218 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14218'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14218'
 id: 14219 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14219'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14219'
 id: 14220 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '14220'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14220'
 id: 14221 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '14221'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14221'
 id: 14222 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14222'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14222'
 id: 14223 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '14223'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14223'
 id: 14224 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '14224'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14224'
 id: 14225 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14225'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14225'
 id: 14226 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '14226'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14226'
 id: 14227 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14227'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14227'
 id: 14228 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '14228'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14228'
 id: 14229 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '14229'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14229'
 id: 14230 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14230'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14230'
 id: 14231 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14231'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14231'
 id: 14232 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14232'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14232'
 id: 14233 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14233'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14233'
 id: 14234 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '14234'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14234'
 id: 14235 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14235'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14235'
 id: 14236 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14236'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14236'
 id: 14237 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '14237'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14237'
 id: 14238 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '14238'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14238'
 id: 14239 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '14239'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14239'
 id: 14240 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '14240'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14240'
 id: 14241 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '14241'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14241'
 id: 14242 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14242'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14242'
 id: 14243 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14243'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14243'
 id: 14244 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '14244'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14244'
 id: 14245 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14245'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14245'
 id: 14246 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14246'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14246'
 id: 14247 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '14247'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14247'
 id: 14248 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '14248'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14248'
 id: 14249 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '14249'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14249'
 id: 14250 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '14250'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14250'
 id: 14251 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '14251'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14251'
 id: 14252 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '14252'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14252'
 id: 14253 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '14253'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14253'
 id: 14254 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '14254'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14254'
 id: 14255 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '14255'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14255'
 id: 14256 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '14256'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14256'
 id: 14257 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '14257'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14257'
 id: 14258 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '14258'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14258'
 id: 14259 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '14259'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14259'
 id: 14260 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14260'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14260'
 id: 14261 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14261'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14261'
 id: 14262 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14262'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14262'
 id: 14263 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14263'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14263'
 id: 14264 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '14264'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14264'
 id: 14265 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14265'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14265'
 id: 14266 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '14266'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14266'
 id: 14267 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14267'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14267'
 id: 14268 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '14268'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14268'
 id: 14269 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14269'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14269'
 id: 14270 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '14270'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14270'
 id: 14271 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14271'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14271'
 id: 14272 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '14272'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14272'
 id: 14273 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '14273'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14273'
 id: 14274 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14274'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14274'
 id: 14275 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14275'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14275'
 id: 14276 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '14276'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14276'
 id: 14277 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14277'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14277'
 id: 14278 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14278'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14278'
 id: 14279 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '14279'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14279'
 id: 14280 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '14280'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14280'
 id: 14281 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '14281'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14281'
 id: 14282 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '14282'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14282'
 id: 14283 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '14283'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14283'
 id: 14284 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '14284'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14284'
 id: 14285 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '14285'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14285'
 id: 14286 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14286'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14286'
 id: 14287 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '14287'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14287'
 id: 14288 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '14288'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14288'
 id: 14289 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '14289'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14289'
 id: 14290 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '14290'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14290'
 id: 14291 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14291'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14291'
 id: 14292 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14292'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14292'
 id: 14293 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '14293'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14293'
 id: 14294 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14294'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14294'
 id: 14295 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14295'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14295'
 id: 14296 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14296'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14296'
 id: 14297 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14297'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14297'
 id: 14298 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14298'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14298'
 id: 14299 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '14299'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14299'
 id: 14300 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '14300'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14300'
 id: 14301 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '14301'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14301'
 id: 14302 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '14302'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14302'
 id: 14303 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '14303'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14303'
 id: 14304 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14304'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14304'
 id: 14305 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '14305'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14305'
 id: 14306 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14306'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14306'
 id: 14307 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '14307'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14307'
 id: 14308 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14308'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14308'
 id: 14309 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '14309'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14309'
 id: 14310 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14310'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14310'
 id: 14311 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '14311'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14311'
 id: 14312 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '14312'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14312'
 id: 14313 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14313'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14313'
 id: 14314 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '14314'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14314'
 id: 14315 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14315'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14315'
 id: 14316 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '14316'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14316'
 id: 14317 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '14317'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14317'
 id: 14318 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '14318'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14318'
 id: 14319 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '14319'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14319'
 id: 14320 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14320'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14320'
 id: 14321 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14321'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14321'
 id: 14322 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14322'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14322'
 id: 14323 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '14323'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14323'
 id: 14324 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '14324'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14324'
 id: 14325 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14325'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14325'
 id: 14326 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '14326'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14326'
 id: 14327 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14327'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14327'
 id: 14328 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '14328'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14328'
 id: 14329 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '14329'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14329'
 id: 14330 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14330'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14330'
 id: 14331 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14331'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14331'
 id: 14332 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '14332'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14332'
 id: 14333 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '14333'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14333'
 id: 14334 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14334'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14334'
 id: 14335 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14335'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14335'
 id: 14336 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '14336'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14336'
 id: 14337 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14337'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14337'
 id: 14338 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '14338'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14338'
 id: 14339 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14339'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14339'
 id: 14340 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14340'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14340'
 id: 14341 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '14341'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14341'
 id: 14342 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14342'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14342'
 id: 14343 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '14343'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14343'
 id: 14344 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14344'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14344'
 id: 14345 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '14345'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14345'
 id: 14346 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '14346'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14346'
 id: 14347 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14347'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14347'
 id: 14348 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14348'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14348'
 id: 14349 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '14349'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14349'
 id: 14350 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14350'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14350'
 id: 14351 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14351'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14351'
 id: 14352 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '14352'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14352'
 id: 14353 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14353'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14353'
 id: 14354 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14354'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14354'
 id: 14355 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '14355'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14355'
 id: 14356 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '14356'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14356'
 id: 14357 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14357'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14357'
 id: 14358 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14358'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14358'
 id: 14359 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '14359'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14359'
 id: 14360 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '14360'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14360'
 id: 14361 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '14361'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14361'
 id: 14362 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14362'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14362'
 id: 14363 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '14363'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14363'
 id: 14364 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14364'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14364'
 id: 14365 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14365'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14365'
 id: 14366 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '14366'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14366'
 id: 14367 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14367'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14367'
 id: 14368 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '14368'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14368'
 id: 14369 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '14369'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14369'
 id: 14370 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '14370'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14370'
 id: 14371 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '14371'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14371'
 id: 14372 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14372'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14372'
 id: 14373 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14373'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14373'
 id: 14374 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '14374'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14374'
 id: 14375 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14375'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14375'
 id: 14376 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '14376'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14376'
 id: 14377 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '14377'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14377'
 id: 14378 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '14378'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14378'
 id: 14379 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '14379'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14379'
 id: 14380 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '14380'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14380'
 id: 14381 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '14381'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14381'
 id: 14382 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '14382'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14382'
 id: 14383 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '14383'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14383'
 id: 14384 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '14384'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14384'
 id: 14385 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14385'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14385'
 id: 14386 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '14386'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14386'
 id: 14387 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '14387'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14387'

 id: 14388 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14388'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14388'
 id: 14389 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14389'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14389'
 id: 14390 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14390'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14390'
 id: 14391 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14391'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14391'
 id: 14392 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '14392'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14392'
 id: 14393 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14393'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14393'
 id: 14394 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '14394'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14394'
 id: 14395 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '14395'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14395'
 id: 14396 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '14396'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14396'
 id: 14397 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14397'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14397'
 id: 14398 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14398'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14398'
 id: 14399 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '14399'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14399'
 id: 14400 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '14400'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14400'
 id: 14401 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '14401'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14401'
 id: 14402 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14402'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14402'
 id: 14403 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '14403'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14403'
 id: 14404 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '14404'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14404'
 id: 14405 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '14405'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14405'
 id: 14406 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '14406'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14406'
 id: 14407 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '14407'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14407'
 id: 14408 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14408'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14408'
 id: 14409 // word: 16
UPDATE job_vacancies SET domain_id =  '16' where raw_id = '14409'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14409'
 id: 14410 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14410'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14410'
 id: 14411 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '14411'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14411'
 id: 14412 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '14412'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14412'
 id: 14413 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '14413'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14413'
 id: 14414 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '14414'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14414'
 id: 14415 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '14415'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14415'
 id: 14416 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '14416'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14416'
 id: 14417 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '14417'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14417'
 id: 14418 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14418'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14418'
 id: 14419 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '14419'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14419'
 id: 14420 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14420'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14420'
 id: 14421 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '14421'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14421'
 id: 14422 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '14422'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14422'
 id: 14423 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '14423'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14423'
 id: 14424 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '14424'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14424'
 id: 14425 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '14425'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14425'
 id: 14426 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14426'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14426'
 id: 14427 // word: 16
UPDATE job_vacancies SET domain_id =  '16' where raw_id = '14427'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14427'
 id: 14428 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14428'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14428'
 id: 14429 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14429'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14429'
 id: 14430 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '14430'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14430'
 id: 14431 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '14431'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14431'
 id: 14432 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '14432'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14432'
 id: 14433 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14433'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14433'
 id: 14434 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14434'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14434'
 id: 14435 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '14435'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14435'
 id: 14436 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '14436'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14436'
 id: 14437 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '14437'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14437'
 id: 14438 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '14438'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14438'
 id: 14439 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '14439'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14439'
 id: 14440 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '14440'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14440'
 id: 14441 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '14441'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14441'
 id: 14442 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14442'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14442'
 id: 14443 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14443'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14443'
 id: 14444 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14444'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14444'
 id: 14445 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14445'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14445'
 id: 14446 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '14446'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14446'
 id: 14447 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14447'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14447'
 id: 14448 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14448'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14448'
 id: 14449 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14449'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14449'
 id: 14450 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '14450'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14450'
 id: 14451 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '14451'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14451'
 id: 14452 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14452'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14452'
 id: 14453 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14453'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14453'
 id: 14454 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14454'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14454'
 id: 14455 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '14455'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14455'
 id: 14456 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '14456'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14456'
 id: 14457 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '14457'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14457'
 id: 14458 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14458'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14458'
 id: 14459 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '14459'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14459'
 id: 14460 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14460'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14460'
 id: 14461 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14461'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14461'
 id: 14462 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '14462'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14462'
 id: 14463 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14463'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14463'
 id: 14464 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '14464'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14464'
 id: 14465 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '14465'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14465'
 id: 14466 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '14466'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14466'
 id: 14467 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '14467'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14467'
 id: 14468 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '14468'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14468'
 id: 14469 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '14469'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14469'
 id: 14470 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14470'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14470'
 id: 14471 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '14471'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14471'
 id: 14472 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '14472'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14472'
 id: 14473 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14473'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14473'
 id: 14474 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14474'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14474'
 id: 14475 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '14475'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14475'
 id: 14476 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14476'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14476'
 id: 14477 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '14477'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14477'
 id: 14478 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14478'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14478'
 id: 14479 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '14479'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14479'
 id: 14480 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14480'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14480'
 id: 14481 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '14481'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14481'
 id: 14482 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14482'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14482'
 id: 14483 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14483'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14483'
 id: 14484 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14484'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14484'
 id: 14485 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '14485'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14485'
 id: 14486 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '14486'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14486'
 id: 14487 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '14487'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14487'
 id: 14488 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14488'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14488'
 id: 14489 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14489'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14489'
 id: 14490 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14490'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14490'
 id: 14491 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '14491'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14491'
 id: 14492 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14492'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14492'
 id: 14493 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14493'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14493'
 id: 14494 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14494'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14494'
 id: 14495 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '14495'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14495'
 id: 14496 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '14496'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14496'
 id: 14497 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '14497'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14497'
 id: 14498 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '14498'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14498'
 id: 14499 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '14499'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14499'
 id: 14500 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14500'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14500'
 id: 14501 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '14501'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14501'
 id: 14502 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '14502'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14502'
 id: 14503 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '14503'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14503'
 id: 14504 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14504'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14504'
 id: 14505 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14505'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14505'
 id: 14506 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '14506'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14506'
 id: 14507 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14507'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14507'
 id: 14508 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14508'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14508'
 id: 14509 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14509'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14509'
 id: 14510 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14510'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14510'
 id: 14511 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14511'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14511'
 id: 14512 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '14512'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14512'
 id: 14513 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '14513'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14513'
 id: 14514 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14514'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14514'
 id: 14515 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14515'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14515'
 id: 14516 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '14516'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14516'
 id: 14517 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14517'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14517'
 id: 14518 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '14518'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14518'
 id: 14519 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14519'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14519'
 id: 14520 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '14520'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14520'
 id: 14521 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '14521'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14521'
 id: 14522 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14522'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14522'
 id: 14523 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14523'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14523'
 id: 14524 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '14524'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14524'
 id: 14525 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14525'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14525'
 id: 14526 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14526'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14526'
 id: 14527 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14527'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14527'
 id: 14528 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '14528'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14528'
 id: 14529 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14529'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14529'
 id: 14530 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14530'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14530'
 id: 14531 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14531'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14531'
 id: 14532 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '14532'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14532'
 id: 14533 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '14533'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14533'
 id: 14534 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14534'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14534'
 id: 14535 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '14535'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14535'
 id: 14536 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '14536'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14536'
 id: 14537 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '14537'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14537'
 id: 14538 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14538'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14538'
 id: 14539 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '14539'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14539'
 id: 14540 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14540'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14540'
 id: 14541 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14541'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14541'
 id: 14542 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14542'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14542'
 id: 14543 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '14543'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14543'
 id: 14544 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14544'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14544'
 id: 14545 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14545'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14545'
 id: 14546 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '14546'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14546'
 id: 14547 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '14547'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14547'
 id: 14548 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '14548'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14548'
 id: 14549 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14549'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14549'
 id: 14550 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '14550'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14550'
 id: 14551 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '14551'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14551'
 id: 14552 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14552'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14552'
 id: 14553 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14553'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14553'
 id: 14554 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '14554'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14554'
 id: 14555 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '14555'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14555'
 id: 14556 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14556'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14556'
 id: 14557 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '14557'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14557'
 id: 14558 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '14558'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14558'
 id: 14559 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14559'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14559'
 id: 14560 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '14560'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14560'
 id: 14561 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '14561'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14561'
 id: 14562 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14562'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14562'
 id: 14563 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '14563'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14563'
 id: 14564 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '14564'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14564'
 id: 14565 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '14565'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14565'
 id: 14566 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14566'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14566'
 id: 14567 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '14567'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14567'
 id: 14568 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '14568'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14568'
 id: 14569 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '14569'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14569'
 id: 14570 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '14570'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14570'
 id: 14571 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '14571'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14571'
 id: 14572 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '14572'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14572'
 id: 14573 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14573'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14573'
 id: 14574 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14574'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14574'
 id: 14575 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '14575'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14575'
 id: 14576 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '14576'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14576'
 id: 14577 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '14577'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14577'
 id: 14578 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '14578'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14578'
 id: 14579 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14579'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14579'
 id: 14580 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '14580'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14580'
 id: 14581 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '14581'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14581'
 id: 14582 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '14582'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14582'
 id: 14583 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14583'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14583'
 id: 14584 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '14584'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14584'
 id: 14585 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14585'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14585'
 id: 14586 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14586'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14586'
 id: 14587 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '14587'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14587'
 id: 14588 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14588'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14588'
 id: 14589 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14589'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14589'
 id: 14590 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '14590'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14590'
 id: 14591 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '14591'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14591'
 id: 14592 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14592'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14592'
 id: 14593 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14593'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14593'
 id: 14594 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14594'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14594'
 id: 14595 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '14595'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14595'
 id: 14596 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '14596'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14596'
 id: 14597 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14597'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14597'
 id: 14598 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '14598'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14598'
 id: 14599 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '14599'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14599'
 id: 14600 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '14600'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14600'
 id: 14601 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '14601'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14601'
 id: 14602 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14602'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14602'
 id: 14603 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '14603'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14603'
 id: 14604 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14604'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14604'
 id: 14605 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14605'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14605'
 id: 14606 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '14606'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14606'
 id: 14607 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '14607'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14607'
 id: 14608 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '14608'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14608'
 id: 14609 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '14609'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14609'
 id: 14610 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14610'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14610'
 id: 14611 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14611'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14611'
 id: 14612 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14612'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14612'
 id: 14613 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '14613'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14613'
 id: 14614 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '14614'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14614'
 id: 14615 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14615'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14615'
 id: 14616 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '14616'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14616'
 id: 14617 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '14617'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14617'
 id: 14618 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14618'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14618'
 id: 14619 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '14619'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14619'
 id: 14620 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '14620'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14620'
 id: 14621 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '14621'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14621'
 id: 14622 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14622'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14622'
 id: 14623 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14623'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14623'
 id: 14624 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14624'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14624'
 id: 14625 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '14625'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14625'
 id: 14626 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '14626'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14626'
 id: 14627 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '14627'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14627'
 id: 14628 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14628'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14628'
 id: 14629 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '14629'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14629'
 id: 14630 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '14630'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14630'
 id: 14631 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14631'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14631'
 id: 14632 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '14632'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14632'
 id: 14633 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '14633'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14633'
 id: 14634 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '14634'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14634'
 id: 14635 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14635'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14635'
 id: 14636 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14636'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14636'
 id: 14637 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14637'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14637'
 id: 14638 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '14638'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14638'
 id: 14639 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '14639'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14639'
 id: 14640 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '14640'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14640'
 id: 14641 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '14641'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14641'
 id: 14642 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14642'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14642'
 id: 14643 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '14643'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14643'
 id: 14644 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '14644'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14644'
 id: 14645 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14645'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14645'
 id: 14646 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '14646'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14646'
 id: 14647 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '14647'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14647'
 id: 14648 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '14648'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14648'
 id: 14649 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14649'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14649'
 id: 14650 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14650'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14650'
 id: 14651 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '14651'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14651'
 id: 14652 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '14652'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14652'
 id: 14653 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '14653'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14653'
 id: 14654 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14654'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14654'
 id: 14655 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '14655'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14655'
 id: 14656 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14656'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14656'
 id: 14657 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '14657'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14657'
 id: 14658 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14658'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14658'
 id: 14659 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '14659'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14659'
 id: 14660 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '14660'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14660'
 id: 14661 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '14661'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14661'
 id: 14662 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '14662'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14662'
 id: 14663 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '14663'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14663'
 id: 14664 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '14664'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14664'
 id: 14665 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14665'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14665'
 id: 14666 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14666'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14666'
 id: 14667 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '14667'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14667'
 id: 14668 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '14668'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14668'
 id: 14669 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '14669'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14669'
 id: 14670 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '14670'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14670'
 id: 14671 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '14671'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14671'
 id: 14672 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '14672'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14672'
 id: 14673 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14673'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14673'
 id: 14674 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '14674'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14674'
 id: 14675 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14675'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14675'
 id: 14676 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '14676'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14676'
 id: 14677 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '14677'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14677'
 id: 14678 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '14678'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14678'
 id: 14679 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '14679'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14679'
 id: 14680 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '14680'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14680'
 id: 14681 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '14681'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14681'
 id: 14682 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '14682'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14682'
 id: 14683 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14683'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14683'
 id: 14684 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14684'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14684'
 id: 14685 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14685'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14685'
 id: 14686 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '14686'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14686'
 id: 14687 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '14687'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14687'
 id: 14688 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '14688'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14688'
 id: 14689 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '14689'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14689'
 id: 14690 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14690'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14690'
 id: 14691 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '14691'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14691'
 id: 14692 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '14692'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14692'
 id: 14693 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '14693'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14693'
 id: 14694 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14694'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14694'
 id: 14695 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '14695'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14695'
 id: 14696 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14696'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14696'
 id: 14697 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14697'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14697'
 id: 14698 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '14698'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14698'
 id: 14699 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '14699'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14699'
 id: 14700 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14700'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14700'
 id: 14701 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '14701'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14701'
 id: 14702 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '14702'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14702'
 id: 14703 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '14703'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14703'
 id: 14704 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '14704'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14704'
 id: 14705 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '14705'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14705'
 id: 14706 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14706'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14706'
 id: 14707 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '14707'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14707'
 id: 14708 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '14708'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14708'
 id: 14709 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '14709'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14709'
 id: 14710 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14710'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14710'
 id: 14711 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '14711'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14711'
 id: 14712 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14712'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14712'
 id: 14713 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '14713'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14713'
 id: 14714 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '14714'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14714'
 id: 14715 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14715'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14715'
 id: 14716 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '14716'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14716'
 id: 14717 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14717'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14717'
 id: 14718 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14718'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14718'
 id: 14719 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14719'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14719'
 id: 14720 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '14720'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14720'
 id: 14721 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14721'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14721'
 id: 14722 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '14722'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14722'
 id: 14723 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14723'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14723'
 id: 14724 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '14724'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14724'
 id: 14725 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '14725'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14725'
 id: 14726 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '14726'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14726'
 id: 14727 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '14727'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14727'
 id: 14728 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14728'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14728'
 id: 14729 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '14729'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14729'
 id: 14730 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14730'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14730'
 id: 14731 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '14731'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14731'
 id: 14732 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14732'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14732'
 id: 14733 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '14733'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14733'
 id: 14734 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14734'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14734'
 id: 14735 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14735'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14735'
 id: 14736 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14736'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14736'
 id: 14737 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '14737'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14737'
 id: 14738 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14738'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14738'
 id: 14739 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '14739'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14739'
 id: 14740 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '14740'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14740'
 id: 14741 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14741'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14741'
 id: 14742 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '14742'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14742'
 id: 14743 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '14743'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14743'
 id: 14744 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '14744'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14744'

 id: 14745 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '14745'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14745'
 id: 14746 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '14746'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14746'
 id: 14747 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '14747'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14747'
 id: 14748 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '14748'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14748'
 id: 14749 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '14749'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14749'
 id: 14750 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14750'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14750'
 id: 14751 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '14751'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14751'
 id: 14752 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '14752'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14752'
 id: 14753 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14753'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14753'
 id: 14754 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '14754'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14754'
 id: 14755 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14755'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14755'
 id: 14756 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '14756'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14756'
 id: 14757 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '14757'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14757'
 id: 14758 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '14758'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14758'
 id: 14759 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '14759'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14759'
 id: 14760 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '14760'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14760'
 id: 14761 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '14761'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14761'
 id: 14762 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '14762'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14762'
 id: 14763 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '14763'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14763'
 id: 14764 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '14764'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14764'
 id: 14765 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '14765'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14765'
 id: 14766 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '14766'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14766'
 id: 14767 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '14767'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14767'
 id: 14768 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '14768'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14768'
 id: 14769 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '14769'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14769'
 id: 14770 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14770'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14770'
 id: 14771 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14771'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14771'
 id: 14772 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14772'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14772'
 id: 14773 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14773'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14773'
 id: 14774 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '14774'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14774'
 id: 14775 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '14775'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14775'
 id: 14776 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '14776'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14776'
 id: 14777 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '14777'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14777'
 id: 14778 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14778'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14778'
 id: 14779 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '14779'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14779'
 id: 14780 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '14780'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14780'
 id: 14781 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '14781'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14781'
 id: 14782 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '14782'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14782'
 id: 14783 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '14783'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14783'
 id: 14784 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '14784'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14784'
 id: 14785 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '14785'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14785'
 id: 14786 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '14786'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14786'
 id: 14787 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14787'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14787'
 id: 14788 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '14788'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14788'
 id: 14789 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14789'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14789'
 id: 14790 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '14790'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14790'
 id: 14791 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '14791'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14791'
 id: 14792 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14792'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14792'
 id: 14793 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14793'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14793'
 id: 14794 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14794'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14794'
 id: 14795 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '14795'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14795'
 id: 14796 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14796'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14796'
 id: 14797 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14797'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14797'
 id: 14798 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '14798'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14798'
 id: 14799 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14799'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14799'
 id: 14800 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '14800'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14800'
 id: 14801 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14801'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14801'
 id: 14802 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14802'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14802'
 id: 14803 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '14803'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14803'
 id: 14804 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '14804'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14804'
 id: 14805 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '14805'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14805'
 id: 14806 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '14806'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14806'
 id: 14807 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '14807'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14807'
 id: 14808 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '14808'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14808'
 id: 14809 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14809'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14809'
 id: 14810 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14810'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14810'
 id: 14811 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14811'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14811'
 id: 14812 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14812'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14812'
 id: 14813 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '14813'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14813'
 id: 14814 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14814'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14814'
 id: 14815 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14815'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14815'
 id: 14816 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14816'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14816'
 id: 14817 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14817'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14817'
 id: 14818 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '14818'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14818'
 id: 14819 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '14819'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14819'
 id: 14820 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14820'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14820'
 id: 14821 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14821'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14821'
 id: 14822 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '14822'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14822'
 id: 14823 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '14823'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14823'
 id: 14824 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '14824'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14824'
 id: 14825 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '14825'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14825'
 id: 14826 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14826'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14826'
 id: 14827 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '14827'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14827'
 id: 14828 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14828'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14828'
 id: 14829 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '14829'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14829'
 id: 14830 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14830'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14830'
 id: 14831 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14831'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14831'
 id: 14832 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14832'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14832'
 id: 14833 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14833'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14833'
 id: 14834 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14834'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14834'
 id: 14835 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14835'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14835'
 id: 14836 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '14836'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14836'
 id: 14837 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14837'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14837'
 id: 14838 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '14838'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14838'
 id: 14839 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14839'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14839'
 id: 14840 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14840'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14840'
 id: 14841 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '14841'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14841'
 id: 14842 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14842'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14842'
 id: 14843 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14843'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14843'
 id: 14844 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '14844'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14844'
 id: 14845 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14845'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14845'
 id: 14846 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '14846'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14846'
 id: 14847 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14847'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14847'
 id: 14848 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '14848'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14848'
 id: 14849 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14849'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14849'
 id: 14850 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '14850'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14850'
 id: 14851 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '14851'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14851'
 id: 14852 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '14852'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14852'
 id: 14853 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '14853'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14853'
 id: 14854 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '14854'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14854'
 id: 14855 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '14855'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14855'
 id: 14856 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '14856'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14856'
 id: 14857 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14857'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14857'
 id: 14858 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14858'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14858'
 id: 14859 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '14859'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14859'
 id: 14860 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14860'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14860'
 id: 14861 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '14861'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14861'
 id: 14862 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14862'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14862'
 id: 14863 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14863'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14863'
 id: 14864 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14864'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14864'
 id: 14865 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14865'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14865'
 id: 14866 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '14866'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14866'
 id: 14867 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14867'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14867'
 id: 14868 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '14868'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14868'
 id: 14869 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14869'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14869'
 id: 14870 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '14870'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14870'
 id: 14871 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14871'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14871'
 id: 14872 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '14872'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14872'
 id: 14873 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '14873'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14873'
 id: 14874 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '14874'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14874'
 id: 14875 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '14875'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14875'
 id: 14876 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14876'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14876'
 id: 14877 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14877'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14877'
 id: 14878 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '14878'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14878'
 id: 14879 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '14879'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14879'
 id: 14880 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '14880'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14880'
 id: 14881 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '14881'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14881'
 id: 14882 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14882'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14882'
 id: 14883 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14883'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14883'
 id: 14884 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '14884'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14884'
 id: 14885 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14885'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14885'
 id: 14886 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14886'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14886'
 id: 14887 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '14887'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14887'
 id: 14888 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14888'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14888'
 id: 14889 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14889'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14889'
 id: 14890 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '14890'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14890'
 id: 14891 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '14891'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14891'
 id: 14892 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '14892'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14892'
 id: 14893 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14893'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14893'
 id: 14894 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '14894'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14894'
 id: 14895 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14895'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14895'
 id: 14896 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '14896'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14896'
 id: 14897 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '14897'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14897'
 id: 14898 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '14898'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14898'
 id: 14899 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '14899'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14899'
 id: 14900 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14900'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14900'
 id: 14901 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14901'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14901'
 id: 14902 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '14902'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14902'
 id: 14903 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14903'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14903'
 id: 14904 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14904'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14904'
 id: 14905 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '14905'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14905'
 id: 14906 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14906'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14906'
 id: 14907 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14907'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14907'
 id: 14908 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '14908'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14908'
 id: 14909 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '14909'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14909'
 id: 14910 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '14910'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14910'
 id: 14911 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '14911'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14911'
 id: 14912 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14912'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14912'
 id: 14913 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14913'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14913'
 id: 14914 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '14914'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14914'
 id: 14915 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14915'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14915'
 id: 14916 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14916'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14916'
 id: 14917 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '14917'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14917'
 id: 14918 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '14918'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14918'
 id: 14919 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '14919'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14919'
 id: 14920 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14920'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14920'
 id: 14921 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14921'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14921'
 id: 14922 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '14922'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14922'
 id: 14923 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '14923'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14923'
 id: 14924 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '14924'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14924'
 id: 14925 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '14925'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14925'
 id: 14926 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '14926'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14926'
 id: 14927 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '14927'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14927'
 id: 14928 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14928'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14928'
 id: 14929 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '14929'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14929'
 id: 14930 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '14930'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14930'
 id: 14931 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '14931'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14931'
 id: 14932 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '14932'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14932'
 id: 14933 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '14933'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14933'
 id: 14934 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14934'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14934'
 id: 14935 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14935'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14935'
 id: 14936 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '14936'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14936'
 id: 14937 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14937'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14937'
 id: 14938 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '14938'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14938'
 id: 14939 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '14939'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14939'
 id: 14940 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '14940'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14940'
 id: 14941 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14941'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14941'
 id: 14942 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '14942'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14942'
 id: 14943 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14943'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14943'
 id: 14944 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14944'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14944'
 id: 14945 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14945'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14945'
 id: 14946 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '14946'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14946'
 id: 14947 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '14947'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14947'
 id: 14948 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14948'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14948'
 id: 14949 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '14949'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14949'
 id: 14950 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14950'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14950'
 id: 14951 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '14951'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14951'
 id: 14952 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '14952'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14952'
 id: 14953 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14953'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14953'
 id: 14954 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '14954'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14954'
 id: 14955 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14955'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14955'
 id: 14956 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '14956'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14956'
 id: 14957 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14957'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14957'
 id: 14958 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14958'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14958'
 id: 14959 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '14959'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14959'
 id: 14960 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14960'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14960'
 id: 14961 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '14961'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14961'
 id: 14962 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14962'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14962'
 id: 14963 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '14963'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14963'
 id: 14964 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14964'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14964'
 id: 14965 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '14965'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14965'
 id: 14966 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '14966'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14966'
 id: 14967 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '14967'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14967'
 id: 14968 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '14968'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14968'
 id: 14969 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14969'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14969'
 id: 14970 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '14970'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14970'
 id: 14971 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '14971'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14971'
 id: 14972 // word: 57
UPDATE job_vacancies SET domain_id =  '57' where raw_id = '14972'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14972'
 id: 14973 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14973'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14973'
 id: 14974 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '14974'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14974'
 id: 14975 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14975'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14975'
 id: 14976 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '14976'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14976'
 id: 14977 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '14977'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14977'
 id: 14978 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14978'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14978'
 id: 14979 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '14979'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14979'
 id: 14980 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '14980'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14980'
 id: 14981 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14981'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14981'
 id: 14982 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14982'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14982'
 id: 14983 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '14983'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14983'
 id: 14984 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14984'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14984'
 id: 14985 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '14985'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14985'
 id: 14986 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14986'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14986'
 id: 14987 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '14987'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14987'
 id: 14988 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14988'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14988'
 id: 14989 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '14989'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14989'
 id: 14990 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '14990'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14990'
 id: 14991 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '14991'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14991'
 id: 14992 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '14992'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14992'
 id: 14993 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '14993'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14993'
 id: 14994 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '14994'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14994'
 id: 14995 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '14995'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14995'
 id: 14996 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '14996'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14996'
 id: 14997 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '14997'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14997'
 id: 14998 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '14998'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14998'
 id: 14999 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '14999'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '14999'
 id: 15000 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15000'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15000'
 id: 15001 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15001'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15001'
 id: 15002 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '15002'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15002'
 id: 15003 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15003'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15003'
 id: 15004 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15004'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15004'
 id: 15005 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15005'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15005'
 id: 15006 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15006'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15006'
 id: 15007 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15007'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15007'
 id: 15008 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15008'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15008'
 id: 15009 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '15009'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15009'
 id: 15010 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15010'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15010'
 id: 15011 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15011'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15011'
 id: 15012 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '15012'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15012'
 id: 15013 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '15013'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15013'
 id: 15014 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '15014'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15014'
 id: 15015 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '15015'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15015'
 id: 15016 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '15016'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15016'
 id: 15017 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '15017'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15017'
 id: 15018 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '15018'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15018'
 id: 15019 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15019'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15019'
 id: 15020 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15020'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15020'
 id: 15021 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '15021'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15021'
 id: 15022 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '15022'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15022'
 id: 15023 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '15023'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15023'
 id: 15024 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '15024'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15024'
 id: 15025 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15025'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15025'
 id: 15026 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15026'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15026'
 id: 15027 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '15027'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15027'
 id: 15028 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15028'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15028'
 id: 15029 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '15029'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15029'
 id: 15030 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '15030'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15030'
 id: 15031 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '15031'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15031'
 id: 15032 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '15032'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15032'
 id: 15033 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15033'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15033'
 id: 15034 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15034'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15034'
 id: 15035 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '15035'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15035'
 id: 15036 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '15036'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15036'
 id: 15037 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '15037'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15037'
 id: 15038 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15038'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15038'
 id: 15039 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15039'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15039'
 id: 15040 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15040'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15040'
 id: 15041 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '15041'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15041'
 id: 15042 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '15042'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15042'
 id: 15043 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15043'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15043'
 id: 15044 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '15044'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15044'
 id: 15045 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15045'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15045'
 id: 15046 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15046'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15046'
 id: 15047 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15047'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15047'
 id: 15048 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '15048'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15048'
 id: 15049 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '15049'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15049'
 id: 15050 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '15050'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15050'
 id: 15051 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15051'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15051'
 id: 15052 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '15052'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15052'
 id: 15053 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15053'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15053'
 id: 15054 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15054'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15054'
 id: 15055 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '15055'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15055'
 id: 15056 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '15056'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15056'
 id: 15057 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '15057'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15057'
 id: 15058 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15058'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15058'
 id: 15059 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15059'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15059'
 id: 15060 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '15060'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15060'
 id: 15061 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15061'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15061'
 id: 15062 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15062'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15062'
 id: 15063 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15063'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15063'
 id: 15064 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15064'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15064'
 id: 15065 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '15065'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15065'
 id: 15066 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15066'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15066'
 id: 15067 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15067'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15067'
 id: 15068 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15068'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15068'
 id: 15069 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '15069'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15069'
 id: 15070 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '15070'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15070'
 id: 15071 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15071'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15071'
 id: 15072 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '15072'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15072'
 id: 15073 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '15073'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15073'
 id: 15074 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15074'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15074'
 id: 15075 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '15075'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15075'
 id: 15076 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15076'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15076'
 id: 15077 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '15077'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15077'
 id: 15078 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '15078'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15078'
 id: 15079 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '15079'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15079'
 id: 15080 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '15080'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15080'
 id: 15081 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '15081'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15081'
 id: 15082 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '15082'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15082'
 id: 15083 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '15083'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15083'
 id: 15084 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15084'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15084'
 id: 15085 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15085'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15085'
 id: 15086 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15086'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15086'
 id: 15087 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15087'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15087'
 id: 15088 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '15088'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15088'
 id: 15089 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15089'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15089'
 id: 15090 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '15090'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15090'
 id: 15091 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '15091'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15091'
 id: 15092 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '15092'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15092'
 id: 15093 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '15093'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15093'
 id: 15094 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15094'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15094'
 id: 15095 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '15095'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15095'
 id: 15096 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15096'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15096'
 id: 15097 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15097'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15097'
 id: 15098 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '15098'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15098'
 id: 15099 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15099'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15099'
 id: 15100 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15100'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15100'
 id: 15101 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '15101'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15101'
 id: 15102 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '15102'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15102'
 id: 15103 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '15103'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15103'
 id: 15104 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '15104'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15104'
 id: 15105 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15105'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15105'
 id: 15106 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '15106'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15106'
 id: 15107 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '15107'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15107'
 id: 15108 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '15108'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15108'
 id: 15109 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '15109'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15109'
 id: 15110 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15110'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15110'
 id: 15111 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '15111'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15111'
 id: 15112 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '15112'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15112'
 id: 15113 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15113'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15113'
 id: 15114 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15114'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15114'
 id: 15115 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '15115'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15115'
 id: 15116 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '15116'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15116'
 id: 15117 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '15117'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15117'
 id: 15118 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15118'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15118'
 id: 15119 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15119'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15119'
 id: 15120 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '15120'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15120'
 id: 15121 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15121'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15121'
 id: 15122 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '15122'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15122'
 id: 15123 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15123'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15123'
 id: 15124 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15124'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15124'
 id: 15125 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15125'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15125'
 id: 15126 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '15126'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15126'
 id: 15127 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '15127'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15127'
 id: 15128 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '15128'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15128'
 id: 15129 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '15129'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15129'
 id: 15130 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15130'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15130'
 id: 15131 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15131'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15131'
 id: 15132 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '15132'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15132'
 id: 15133 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15133'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15133'
 id: 15134 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15134'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15134'
 id: 15135 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '15135'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15135'
 id: 15136 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '15136'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15136'
 id: 15137 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '15137'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15137'
 id: 15138 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15138'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15138'
 id: 15139 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '15139'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15139'
 id: 15140 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15140'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15140'
 id: 15141 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15141'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15141'
 id: 15142 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '15142'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15142'
 id: 15143 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15143'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15143'
 id: 15144 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '15144'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15144'
 id: 15145 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15145'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15145'
 id: 15146 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15146'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15146'
 id: 15147 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '15147'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15147'
 id: 15148 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15148'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15148'
 id: 15149 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '15149'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15149'
 id: 15150 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15150'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15150'
 id: 15151 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '15151'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15151'
 id: 15152 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15152'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15152'
 id: 15153 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15153'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15153'
 id: 15154 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15154'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15154'
 id: 15155 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15155'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15155'
 id: 15156 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15156'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15156'
 id: 15157 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15157'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15157'
 id: 15158 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15158'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15158'
 id: 15159 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15159'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15159'
 id: 15160 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15160'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15160'
 id: 15161 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '15161'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15161'
 id: 15162 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15162'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15162'
 id: 15163 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15163'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15163'
 id: 15164 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15164'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15164'
 id: 15165 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15165'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15165'
 id: 15166 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '15166'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15166'
 id: 15167 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '15167'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15167'
 id: 15168 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '15168'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15168'
 id: 15169 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15169'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15169'
 id: 15170 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15170'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15170'
 id: 15171 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15171'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15171'
 id: 15172 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '15172'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15172'
 id: 15173 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15173'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15173'
 id: 15174 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '15174'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15174'
 id: 15175 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '15175'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15175'
 id: 15176 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '15176'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15176'
 id: 15177 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15177'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15177'
 id: 15178 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15178'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15178'
 id: 15179 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15179'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15179'
 id: 15180 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '15180'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15180'
 id: 15181 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15181'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15181'
 id: 15182 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '15182'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15182'
 id: 15183 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15183'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15183'
 id: 15184 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '15184'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15184'
 id: 15185 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '15185'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15185'
 id: 15186 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15186'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15186'
 id: 15187 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '15187'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15187'
 id: 15188 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '15188'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15188'
 id: 15189 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15189'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15189'
 id: 15190 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '15190'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15190'
 id: 15191 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15191'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15191'
 id: 15192 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15192'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15192'
 id: 15193 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15193'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15193'
 id: 15194 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '15194'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15194'
 id: 15195 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15195'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15195'
 id: 15196 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15196'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15196'
 id: 15197 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15197'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15197'
 id: 15198 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '15198'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15198'
 id: 15199 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15199'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15199'
 id: 15200 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15200'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15200'
 id: 15201 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15201'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15201'
 id: 15202 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '15202'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15202'
 id: 15203 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '15203'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15203'
 id: 15204 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15204'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15204'
 id: 15205 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15205'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15205'
 id: 15206 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '15206'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15206'
 id: 15207 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15207'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15207'
 id: 15208 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '15208'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15208'
 id: 15209 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15209'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15209'
 id: 15210 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15210'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15210'
 id: 15211 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '15211'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15211'
 id: 15212 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15212'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15212'
 id: 15213 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15213'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15213'
 id: 15214 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15214'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15214'
 id: 15215 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '15215'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15215'
 id: 15216 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15216'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15216'
 id: 15217 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15217'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15217'
 id: 15218 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '15218'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15218'
 id: 15219 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15219'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15219'
 id: 15220 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '15220'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15220'
 id: 15221 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15221'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15221'
 id: 15222 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '15222'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15222'
 id: 15223 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '15223'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15223'
 id: 15224 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15224'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15224'
 id: 15225 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '15225'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15225'
 id: 15226 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '15226'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15226'
 id: 15227 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15227'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15227'
 id: 15228 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15228'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15228'
 id: 15229 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15229'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15229'
 id: 15230 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15230'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15230'
 id: 15231 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '15231'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15231'
 id: 15232 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '15232'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15232'
 id: 15233 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '15233'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15233'
 id: 15234 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '15234'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15234'
 id: 15235 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '15235'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15235'
 id: 15236 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '15236'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15236'
 id: 15237 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15237'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15237'
 id: 15238 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '15238'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15238'
 id: 15239 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15239'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15239'
 id: 15240 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '15240'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15240'
 id: 15241 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15241'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15241'
 id: 15242 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '15242'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15242'
 id: 15243 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '15243'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15243'
 id: 15244 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '15244'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15244'
 id: 15245 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '15245'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15245'
 id: 15246 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15246'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15246'
 id: 15247 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15247'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15247'
 id: 15248 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15248'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15248'
 id: 15249 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '15249'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15249'
 id: 15250 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15250'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15250'
 id: 15251 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15251'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15251'
 id: 15252 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15252'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15252'
 id: 15253 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15253'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15253'
 id: 15254 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '15254'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15254'
 id: 15255 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '15255'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15255'
 id: 15256 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15256'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15256'
 id: 15257 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '15257'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15257'
 id: 15258 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '15258'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15258'
 id: 15259 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '15259'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15259'
 id: 15260 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '15260'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15260'
 id: 15261 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15261'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15261'
 id: 15262 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '15262'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15262'
 id: 15263 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '15263'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15263'
 id: 15264 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15264'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15264'
 id: 15265 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15265'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15265'
 id: 15266 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15266'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15266'
 id: 15267 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '15267'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15267'
 id: 15268 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '15268'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15268'
 id: 15269 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '15269'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15269'
 id: 15270 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15270'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15270'
 id: 15271 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '15271'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15271'
 id: 15272 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '15272'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15272'
 id: 15273 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15273'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15273'
 id: 15274 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15274'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15274'
 id: 15275 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '15275'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15275'
 id: 15276 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '15276'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15276'
 id: 15277 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '15277'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15277'
 id: 15278 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15278'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15278'
 id: 15279 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '15279'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15279'
 id: 15280 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15280'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15280'
 id: 15281 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15281'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15281'
 id: 15282 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15282'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15282'
 id: 15283 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15283'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15283'
 id: 15284 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '15284'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15284'
 id: 15285 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '15285'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15285'
 id: 15286 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '15286'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15286'
 id: 15287 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15287'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15287'
 id: 15288 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '15288'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15288'
 id: 15289 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15289'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15289'
 id: 15290 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15290'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15290'
 id: 15291 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '15291'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15291'
 id: 15292 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15292'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15292'
 id: 15293 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '15293'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15293'
 id: 15294 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15294'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15294'
 id: 15295 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15295'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15295'
 id: 15296 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '15296'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15296'
 id: 15297 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15297'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15297'
 id: 15298 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15298'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15298'
 id: 15299 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '15299'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15299'
 id: 15300 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '15300'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15300'
 id: 15301 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '15301'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15301'
 id: 15302 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15302'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15302'
 id: 15303 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '15303'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15303'
 id: 15304 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15304'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15304'
 id: 15305 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '15305'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15305'
 id: 15306 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15306'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15306'
 id: 15307 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15307'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15307'
 id: 15308 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '15308'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15308'
 id: 15309 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15309'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15309'
 id: 15310 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15310'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15310'
 id: 15311 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '15311'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15311'
 id: 15312 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '15312'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15312'
 id: 15313 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15313'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15313'
 id: 15314 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15314'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15314'
 id: 15315 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15315'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15315'
 id: 15316 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15316'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15316'
 id: 15317 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '15317'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15317'
 id: 15318 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15318'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15318'
 id: 15319 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '15319'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15319'
 id: 15320 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '15320'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15320'
 id: 15321 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15321'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15321'
 id: 15322 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '15322'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15322'
 id: 15323 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '15323'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15323'
 id: 15324 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '15324'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15324'
 id: 15325 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15325'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15325'
 id: 15326 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15326'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15326'
 id: 15327 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '15327'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15327'
 id: 15328 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '15328'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15328'
 id: 15329 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '15329'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15329'
 id: 15330 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '15330'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15330'
 id: 15331 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '15331'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15331'
 id: 15332 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '15332'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15332'
 id: 15333 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '15333'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15333'
 id: 15334 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15334'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15334'
 id: 15335 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '15335'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15335'
 id: 15336 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '15336'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15336'
 id: 15337 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '15337'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15337'
 id: 15338 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15338'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15338'
 id: 15339 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15339'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15339'
 id: 15340 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15340'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15340'
 id: 15341 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15341'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15341'
 id: 15342 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15342'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15342'
 id: 15343 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15343'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15343'
 id: 15344 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '15344'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15344'
 id: 15345 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '15345'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15345'
 id: 15346 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15346'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15346'
 id: 15347 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15347'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15347'
 id: 15348 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15348'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15348'
 id: 15349 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '15349'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15349'
 id: 15350 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '15350'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15350'
 id: 15351 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '15351'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15351'
 id: 15352 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15352'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15352'
 id: 15353 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '15353'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15353'
 id: 15354 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15354'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15354'
 id: 15355 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '15355'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15355'
 id: 15356 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15356'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15356'
 id: 15357 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '15357'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15357'
 id: 15358 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '15358'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15358'
 id: 15359 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '15359'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15359'
 id: 15360 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '15360'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15360'
 id: 15361 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15361'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15361'
 id: 15362 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15362'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15362'
 id: 15363 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15363'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15363'
 id: 15364 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '15364'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15364'
 id: 15365 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15365'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15365'
 id: 15366 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '15366'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15366'
 id: 15367 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15367'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15367'
 id: 15368 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15368'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15368'
 id: 15369 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '15369'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15369'
 id: 15370 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '15370'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15370'
 id: 15371 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '15371'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15371'
 id: 15372 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '15372'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15372'
 id: 15373 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15373'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15373'
 id: 15374 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '15374'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15374'
 id: 15375 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15375'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15375'
 id: 15376 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '15376'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15376'
 id: 15377 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15377'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15377'
 id: 15378 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '15378'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15378'
 id: 15379 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15379'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15379'
 id: 15380 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '15380'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15380'
 id: 15381 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15381'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15381'
 id: 15382 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '15382'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15382'
 id: 15383 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15383'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15383'
 id: 15384 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '15384'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15384'
 id: 15385 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15385'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15385'
 id: 15386 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '15386'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15386'
 id: 15387 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15387'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15387'
 id: 15388 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15388'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15388'
 id: 15389 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15389'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15389'
 id: 15390 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15390'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15390'
 id: 15391 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15391'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15391'
 id: 15392 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '15392'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15392'
 id: 15393 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15393'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15393'
 id: 15394 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15394'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15394'
 id: 15395 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15395'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15395'
 id: 15396 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '15396'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15396'
 id: 15397 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '15397'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15397'
 id: 15398 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '15398'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15398'
 id: 15399 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15399'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15399'
 id: 15400 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15400'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15400'
 id: 15401 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15401'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15401'
 id: 15402 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '15402'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15402'
 id: 15403 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '15403'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15403'
 id: 15404 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15404'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15404'
 id: 15405 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15405'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15405'

 id: 15406 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15406'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15406'
 id: 15407 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15407'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15407'
 id: 15408 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '15408'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15408'
 id: 15409 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15409'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15409'
 id: 15410 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15410'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15410'
 id: 15411 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15411'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15411'
 id: 15412 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '15412'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15412'
 id: 15413 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '15413'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15413'
 id: 15414 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15414'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15414'
 id: 15415 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '15415'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15415'
 id: 15416 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '15416'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15416'
 id: 15417 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '15417'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15417'
 id: 15418 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15418'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15418'
 id: 15419 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15419'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15419'
 id: 15420 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '15420'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15420'
 id: 15421 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15421'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15421'
 id: 15422 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '15422'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15422'
 id: 15423 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15423'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15423'
 id: 15424 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15424'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15424'
 id: 15425 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '15425'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15425'
 id: 15426 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '15426'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15426'
 id: 15427 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '15427'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15427'
 id: 15428 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15428'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15428'
 id: 15429 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '15429'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15429'
 id: 15430 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '15430'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15430'
 id: 15431 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15431'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15431'
 id: 15432 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '15432'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15432'
 id: 15433 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '15433'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15433'
 id: 15434 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15434'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15434'
 id: 15435 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15435'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15435'
 id: 15436 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15436'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15436'
 id: 15437 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15437'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15437'
 id: 15438 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15438'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15438'
 id: 15439 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15439'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15439'
 id: 15440 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '15440'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15440'
 id: 15441 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15441'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15441'
 id: 15442 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15442'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15442'
 id: 15443 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15443'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15443'
 id: 15444 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15444'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15444'
 id: 15445 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '15445'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15445'
 id: 15446 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15446'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15446'
 id: 15447 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '15447'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15447'
 id: 15448 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15448'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15448'
 id: 15449 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '15449'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15449'
 id: 15450 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15450'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15450'
 id: 15451 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '15451'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15451'
 id: 15452 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15452'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15452'
 id: 15453 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15453'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15453'
 id: 15454 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15454'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15454'
 id: 15455 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15455'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15455'
 id: 15456 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '15456'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15456'
 id: 15457 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15457'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15457'
 id: 15458 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15458'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15458'
 id: 15459 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15459'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15459'
 id: 15460 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15460'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15460'
 id: 15461 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15461'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15461'
 id: 15462 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15462'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15462'
 id: 15463 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '15463'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15463'
 id: 15464 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '15464'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15464'
 id: 15465 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '15465'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15465'
 id: 15466 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15466'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15466'
 id: 15467 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '15467'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15467'
 id: 15468 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '15468'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15468'
 id: 15469 // word: 52
UPDATE job_vacancies SET domain_id =  '52' where raw_id = '15469'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15469'
 id: 15470 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '15470'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15470'
 id: 15471 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15471'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15471'
 id: 15472 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '15472'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15472'
 id: 15473 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15473'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15473'
 id: 15474 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '15474'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15474'
 id: 15475 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15475'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15475'
 id: 15476 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15476'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15476'
 id: 15477 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15477'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15477'
 id: 15478 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15478'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15478'
 id: 15479 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15479'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15479'
 id: 15480 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '15480'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15480'
 id: 15481 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '15481'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15481'
 id: 15482 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15482'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15482'
 id: 15483 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '15483'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15483'
 id: 15484 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15484'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15484'
 id: 15485 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15485'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15485'
 id: 15486 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '15486'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15486'
 id: 15487 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '15487'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15487'
 id: 15488 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '15488'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15488'
 id: 15489 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15489'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15489'
 id: 15490 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15490'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15490'
 id: 15491 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15491'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15491'
 id: 15492 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15492'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15492'
 id: 15493 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15493'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15493'
 id: 15494 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '15494'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15494'
 id: 15495 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '15495'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15495'
 id: 15496 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '15496'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15496'
 id: 15497 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '15497'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15497'
 id: 15498 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15498'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15498'
 id: 15499 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '15499'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15499'
 id: 15500 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15500'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15500'
 id: 15501 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15501'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15501'
 id: 15502 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15502'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15502'
 id: 15503 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '15503'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15503'
 id: 15504 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '15504'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15504'
 id: 15505 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15505'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15505'
 id: 15506 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '15506'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15506'
 id: 15507 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '15507'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15507'
 id: 15508 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15508'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15508'
 id: 15509 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '15509'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15509'
 id: 15510 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '15510'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15510'
 id: 15511 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15511'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15511'
 id: 15512 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '15512'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15512'
 id: 15513 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '15513'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15513'
 id: 15514 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '15514'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15514'
 id: 15515 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '15515'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15515'
 id: 15516 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15516'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15516'
 id: 15517 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15517'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15517'
 id: 15518 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15518'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15518'
 id: 15519 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15519'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15519'
 id: 15520 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15520'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15520'
 id: 15521 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15521'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15521'
 id: 15522 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15522'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15522'
 id: 15523 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '15523'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15523'
 id: 15524 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '15524'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15524'
 id: 15525 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '15525'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15525'
 id: 15526 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '15526'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15526'
 id: 15527 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15527'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15527'
 id: 15528 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15528'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15528'
 id: 15529 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15529'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15529'
 id: 15530 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15530'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15530'
 id: 15531 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15531'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15531'
 id: 15532 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15532'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15532'
 id: 15533 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '15533'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15533'
 id: 15534 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15534'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15534'
 id: 15535 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15535'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15535'
 id: 15536 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '15536'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15536'
 id: 15537 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '15537'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15537'
 id: 15538 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15538'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15538'
 id: 15539 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '15539'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15539'
 id: 15540 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '15540'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15540'
 id: 15541 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '15541'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15541'
 id: 15542 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15542'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15542'
 id: 15543 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '15543'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15543'
 id: 15544 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15544'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15544'
 id: 15545 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '15545'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15545'
 id: 15546 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15546'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15546'
 id: 15547 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15547'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15547'
 id: 15548 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '15548'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15548'
 id: 15549 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15549'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15549'
 id: 15550 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15550'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15550'
 id: 15551 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '15551'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15551'
 id: 15552 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15552'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15552'
 id: 15553 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '15553'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15553'
 id: 15554 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '15554'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15554'
 id: 15555 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '15555'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15555'
 id: 15556 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15556'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15556'

 id: 15557 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '15557'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15557'
 id: 15558 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '15558'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15558'
 id: 15559 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '15559'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15559'
 id: 15560 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15560'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15560'
 id: 15561 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15561'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15561'
 id: 15562 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15562'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15562'
 id: 15563 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15563'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15563'
 id: 15564 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '15564'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15564'
 id: 15565 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15565'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15565'
 id: 15566 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15566'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15566'
 id: 15567 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15567'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15567'
 id: 15568 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15568'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15568'
 id: 15569 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '15569'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15569'
 id: 15570 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15570'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15570'
 id: 15571 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15571'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15571'
 id: 15572 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15572'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15572'
 id: 15573 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '15573'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15573'
 id: 15574 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '15574'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15574'
 id: 15575 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15575'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15575'
 id: 15576 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15576'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15576'
 id: 15577 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15577'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15577'
 id: 15578 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '15578'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15578'
 id: 15579 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15579'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15579'
 id: 15580 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15580'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15580'
 id: 15581 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15581'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15581'
 id: 15582 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15582'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15582'
 id: 15583 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '15583'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15583'
 id: 15584 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15584'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15584'
 id: 15585 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15585'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15585'
 id: 15586 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '15586'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15586'
 id: 15587 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15587'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15587'
 id: 15588 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15588'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15588'
 id: 15589 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15589'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15589'
 id: 15590 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '15590'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15590'
 id: 15591 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15591'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15591'
 id: 15592 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15592'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15592'
 id: 15593 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15593'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15593'
 id: 15594 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '15594'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15594'
 id: 15595 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '15595'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15595'
 id: 15596 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15596'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15596'
 id: 15597 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '15597'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15597'
 id: 15598 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15598'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15598'
 id: 15599 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '15599'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15599'
 id: 15600 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '15600'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15600'
 id: 15601 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '15601'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15601'
 id: 15602 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15602'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15602'
 id: 15603 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '15603'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15603'
 id: 15604 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '15604'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15604'
 id: 15605 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15605'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15605'
 id: 15606 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15606'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15606'
 id: 15607 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15607'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15607'
 id: 15608 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '15608'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15608'

 id: 15609 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '15609'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15609'
 id: 15610 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '15610'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15610'
 id: 15611 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '15611'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15611'
 id: 15612 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '15612'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15612'
 id: 15613 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '15613'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15613'
 id: 15614 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15614'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15614'
 id: 15615 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15615'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15615'
 id: 15616 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15616'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15616'
 id: 15617 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '15617'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15617'
 id: 15618 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '15618'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15618'
 id: 15619 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15619'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15619'
 id: 15620 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '15620'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15620'
 id: 15621 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '15621'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15621'
 id: 15622 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15622'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15622'
 id: 15623 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15623'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15623'
 id: 15624 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15624'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15624'
 id: 15625 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15625'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15625'
 id: 15626 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '15626'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15626'
 id: 15627 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '15627'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15627'
 id: 15628 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '15628'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15628'
 id: 15629 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '15629'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15629'
 id: 15630 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '15630'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15630'
 id: 15631 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '15631'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15631'
 id: 15632 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15632'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15632'
 id: 15633 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15633'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15633'
 id: 15634 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '15634'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15634'
 id: 15635 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15635'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15635'
 id: 15636 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15636'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15636'
 id: 15637 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15637'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15637'
 id: 15638 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15638'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15638'
 id: 15639 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '15639'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15639'
 id: 15640 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15640'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15640'
 id: 15641 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '15641'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15641'
 id: 15642 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '15642'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15642'
 id: 15643 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15643'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15643'
 id: 15644 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '15644'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15644'
 id: 15645 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15645'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15645'
 id: 15646 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '15646'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15646'
 id: 15647 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15647'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15647'
 id: 15648 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '15648'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15648'
 id: 15649 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '15649'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15649'
 id: 15650 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15650'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15650'
 id: 15651 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15651'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15651'
 id: 15652 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '15652'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15652'
 id: 15653 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '15653'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15653'
 id: 15654 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '15654'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15654'
 id: 15655 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '15655'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15655'
 id: 15656 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15656'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15656'
 id: 15657 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '15657'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15657'
 id: 15658 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15658'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15658'
 id: 15659 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15659'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15659'
 id: 15660 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15660'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15660'
 id: 15661 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15661'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15661'
 id: 15662 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '15662'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15662'
 id: 15663 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15663'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15663'
 id: 15664 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15664'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15664'
 id: 15665 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15665'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15665'
 id: 15666 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15666'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15666'
 id: 15667 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15667'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15667'
 id: 15668 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15668'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15668'
 id: 15669 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '15669'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15669'
 id: 15670 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '15670'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15670'
 id: 15671 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '15671'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15671'
 id: 15672 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '15672'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15672'
 id: 15673 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15673'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15673'
 id: 15674 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15674'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15674'
 id: 15675 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15675'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15675'
 id: 15676 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15676'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15676'
 id: 15677 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15677'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15677'
 id: 15678 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15678'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15678'
 id: 15679 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15679'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15679'
 id: 15680 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '15680'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15680'
 id: 15681 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15681'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15681'
 id: 15682 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15682'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15682'
 id: 15683 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15683'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15683'
 id: 15684 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15684'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15684'
 id: 15685 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15685'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15685'
 id: 15686 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '15686'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15686'
 id: 15687 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15687'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15687'
 id: 15688 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15688'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15688'
 id: 15689 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15689'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15689'
 id: 15690 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '15690'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15690'
 id: 15691 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '15691'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15691'
 id: 15692 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15692'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15692'
 id: 15693 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15693'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15693'
 id: 15694 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15694'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15694'
 id: 15695 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15695'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15695'
 id: 15696 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15696'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15696'
 id: 15697 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15697'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15697'
 id: 15698 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15698'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15698'
 id: 15699 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '15699'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15699'
 id: 15700 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '15700'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15700'
 id: 15701 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15701'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15701'
 id: 15702 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '15702'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15702'
 id: 15703 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '15703'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15703'
 id: 15704 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15704'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15704'
 id: 15705 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15705'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15705'
 id: 15706 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15706'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15706'
 id: 15707 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '15707'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15707'
 id: 15708 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '15708'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15708'
 id: 15709 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '15709'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15709'
 id: 15710 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15710'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15710'

 id: 15711 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15711'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15711'
 id: 15712 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '15712'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15712'
 id: 15713 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15713'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15713'
 id: 15714 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15714'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15714'
 id: 15715 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15715'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15715'
 id: 15716 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15716'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15716'
 id: 15717 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15717'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15717'
 id: 15718 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '15718'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15718'
 id: 15719 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '15719'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15719'
 id: 15720 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '15720'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15720'
 id: 15721 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '15721'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15721'
 id: 15722 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '15722'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15722'
 id: 15723 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15723'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15723'
 id: 15724 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15724'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15724'
 id: 15725 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '15725'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15725'
 id: 15726 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15726'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15726'
 id: 15727 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15727'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15727'
 id: 15728 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15728'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15728'
 id: 15729 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '15729'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15729'
 id: 15730 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15730'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15730'
 id: 15731 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '15731'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15731'
 id: 15732 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '15732'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15732'
 id: 15733 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15733'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15733'
 id: 15734 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15734'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15734'
 id: 15735 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '15735'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15735'
 id: 15736 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '15736'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15736'
 id: 15737 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '15737'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15737'
 id: 15738 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '15738'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15738'
 id: 15739 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '15739'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15739'
 id: 15740 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '15740'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15740'
 id: 15741 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15741'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15741'
 id: 15742 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15742'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15742'
 id: 15743 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15743'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15743'
 id: 15744 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '15744'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15744'
 id: 15745 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15745'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15745'
 id: 15746 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15746'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15746'
 id: 15747 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15747'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15747'
 id: 15748 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15748'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15748'
 id: 15749 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15749'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15749'
 id: 15750 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15750'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15750'
 id: 15751 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '15751'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15751'
 id: 15752 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '15752'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15752'
 id: 15753 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '15753'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15753'
 id: 15754 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15754'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15754'
 id: 15755 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '15755'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15755'
 id: 15756 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15756'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15756'
 id: 15757 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15757'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15757'
 id: 15758 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15758'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15758'
 id: 15759 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15759'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15759'
 id: 15760 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15760'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15760'
 id: 15761 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15761'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15761'
 id: 15762 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '15762'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15762'
 id: 15763 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '15763'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15763'
 id: 15764 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15764'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15764'
 id: 15765 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15765'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15765'
 id: 15766 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15766'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15766'
 id: 15767 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15767'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15767'
 id: 15768 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15768'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15768'
 id: 15769 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15769'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15769'
 id: 15770 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '15770'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15770'
 id: 15771 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15771'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15771'
 id: 15772 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15772'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15772'
 id: 15773 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15773'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15773'
 id: 15774 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15774'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15774'
 id: 15775 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15775'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15775'
 id: 15776 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '15776'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15776'
 id: 15777 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '15777'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15777'
 id: 15778 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '15778'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15778'
 id: 15779 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '15779'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15779'
 id: 15780 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15780'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15780'
 id: 15781 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15781'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15781'
 id: 15782 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '15782'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15782'
 id: 15783 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '15783'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15783'
 id: 15784 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15784'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15784'
 id: 15785 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15785'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15785'
 id: 15786 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15786'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15786'
 id: 15787 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15787'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15787'
 id: 15788 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15788'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15788'
 id: 15789 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15789'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15789'
 id: 15790 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15790'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15790'
 id: 15791 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15791'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15791'
 id: 15792 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15792'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15792'
 id: 15793 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15793'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15793'
 id: 15794 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '15794'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15794'
 id: 15795 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '15795'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15795'
 id: 15796 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '15796'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15796'
 id: 15797 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15797'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15797'
 id: 15798 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15798'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15798'
 id: 15799 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '15799'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15799'
 id: 15800 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15800'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15800'
 id: 15801 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '15801'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15801'
 id: 15802 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15802'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15802'
 id: 15803 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15803'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15803'
 id: 15804 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15804'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15804'
 id: 15805 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15805'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15805'
 id: 15806 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15806'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15806'
 id: 15807 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15807'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15807'
 id: 15808 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15808'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15808'
 id: 15809 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15809'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15809'
 id: 15810 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15810'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15810'
 id: 15811 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15811'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15811'
 id: 15812 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15812'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15812'
 id: 15813 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15813'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15813'
 id: 15814 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15814'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15814'
 id: 15815 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15815'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15815'
 id: 15816 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '15816'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15816'
 id: 15817 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15817'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15817'
 id: 15818 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '15818'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15818'
 id: 15819 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '15819'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15819'
 id: 15820 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15820'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15820'
 id: 15821 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15821'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15821'
 id: 15822 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '15822'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15822'
 id: 15823 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15823'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15823'
 id: 15824 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15824'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15824'
 id: 15825 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '15825'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15825'
 id: 15826 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15826'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15826'
 id: 15827 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15827'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15827'
 id: 15828 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15828'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15828'
 id: 15829 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '15829'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15829'
 id: 15830 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '15830'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15830'
 id: 15831 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '15831'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15831'
 id: 15832 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '15832'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15832'
 id: 15833 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '15833'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15833'
 id: 15834 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '15834'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15834'
 id: 15835 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15835'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15835'
 id: 15836 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15836'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15836'
 id: 15837 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '15837'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15837'
 id: 15838 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '15838'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15838'
 id: 15839 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '15839'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15839'
 id: 15840 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '15840'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15840'
 id: 15841 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15841'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15841'
 id: 15842 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15842'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15842'
 id: 15843 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15843'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15843'
 id: 15844 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15844'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15844'
 id: 15845 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15845'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15845'
 id: 15846 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '15846'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15846'
 id: 15847 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15847'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15847'
 id: 15848 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '15848'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15848'
 id: 15849 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15849'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15849'
 id: 15850 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15850'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15850'
 id: 15851 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15851'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15851'
 id: 15852 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '15852'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15852'
 id: 15853 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15853'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15853'
 id: 15854 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '15854'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15854'
 id: 15855 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15855'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15855'
 id: 15856 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15856'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15856'
 id: 15857 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15857'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15857'
 id: 15858 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15858'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15858'
 id: 15859 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15859'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15859'
 id: 15860 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '15860'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15860'
 id: 15861 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15861'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15861'
 id: 15862 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '15862'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15862'
 id: 15863 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '15863'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15863'

 id: 15864 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15864'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15864'
 id: 15865 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15865'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15865'
 id: 15866 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '15866'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15866'
 id: 15867 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '15867'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15867'
 id: 15868 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15868'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15868'
 id: 15869 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '15869'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15869'
 id: 15870 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15870'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15870'
 id: 15871 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '15871'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15871'
 id: 15872 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15872'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15872'
 id: 15873 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '15873'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15873'
 id: 15874 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15874'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15874'
 id: 15875 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15875'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15875'
 id: 15876 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '15876'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15876'
 id: 15877 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '15877'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15877'
 id: 15878 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15878'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15878'
 id: 15879 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '15879'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15879'
 id: 15880 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15880'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15880'
 id: 15881 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15881'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15881'
 id: 15882 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '15882'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15882'
 id: 15883 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '15883'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15883'
 id: 15884 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15884'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15884'
 id: 15885 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '15885'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15885'
 id: 15886 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15886'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15886'
 id: 15887 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15887'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15887'
 id: 15888 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15888'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15888'
 id: 15889 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '15889'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15889'
 id: 15890 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '15890'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15890'
 id: 15891 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '15891'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15891'
 id: 15892 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15892'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15892'
 id: 15893 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15893'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15893'
 id: 15894 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15894'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15894'
 id: 15895 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '15895'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15895'
 id: 15896 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15896'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15896'
 id: 15897 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '15897'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15897'
 id: 15898 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '15898'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15898'
 id: 15899 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15899'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15899'
 id: 15900 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15900'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15900'
 id: 15901 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '15901'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15901'
 id: 15902 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15902'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15902'
 id: 15903 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15903'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15903'
 id: 15904 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '15904'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15904'
 id: 15905 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '15905'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15905'
 id: 15906 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '15906'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15906'
 id: 15907 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15907'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15907'
 id: 15908 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '15908'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15908'
 id: 15909 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '15909'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15909'
 id: 15910 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15910'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15910'
 id: 15911 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '15911'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15911'
 id: 15912 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15912'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15912'
 id: 15913 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15913'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15913'
 id: 15914 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '15914'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15914'
 id: 15915 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15915'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15915'
 id: 15916 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '15916'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15916'
 id: 15917 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15917'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15917'
 id: 15918 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15918'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15918'
 id: 15919 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '15919'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15919'
 id: 15920 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '15920'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15920'
 id: 15921 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15921'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15921'
 id: 15922 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '15922'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15922'
 id: 15923 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '15923'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15923'
 id: 15924 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15924'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15924'
 id: 15925 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '15925'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15925'
 id: 15926 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '15926'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15926'
 id: 15927 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15927'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15927'
 id: 15928 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '15928'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15928'
 id: 15929 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '15929'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15929'
 id: 15930 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15930'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15930'
 id: 15931 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15931'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15931'
 id: 15932 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '15932'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15932'
 id: 15933 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15933'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15933'
 id: 15934 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15934'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15934'
 id: 15935 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '15935'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15935'
 id: 15936 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15936'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15936'
 id: 15937 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15937'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15937'
 id: 15938 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15938'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15938'
 id: 15939 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15939'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15939'
 id: 15940 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15940'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15940'
 id: 15941 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '15941'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15941'
 id: 15942 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15942'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15942'
 id: 15943 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15943'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15943'
 id: 15944 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15944'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15944'
 id: 15945 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '15945'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15945'
 id: 15946 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15946'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15946'
 id: 15947 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15947'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15947'
 id: 15948 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '15948'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15948'
 id: 15949 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15949'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15949'
 id: 15950 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15950'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15950'
 id: 15951 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15951'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15951'
 id: 15952 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15952'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15952'
 id: 15953 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15953'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15953'
 id: 15954 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '15954'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15954'
 id: 15955 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15955'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15955'
 id: 15956 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '15956'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15956'
 id: 15957 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '15957'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15957'
 id: 15958 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15958'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15958'
 id: 15959 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '15959'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15959'
 id: 15960 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '15960'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15960'
 id: 15961 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15961'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15961'
 id: 15962 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '15962'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15962'
 id: 15963 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15963'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15963'
 id: 15964 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15964'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15964'
 id: 15965 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '15965'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15965'
 id: 15966 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '15966'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15966'
 id: 15967 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15967'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15967'
 id: 15968 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15968'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15968'
 id: 15969 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15969'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15969'
 id: 15970 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '15970'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15970'
 id: 15971 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '15971'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15971'
 id: 15972 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15972'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15972'
 id: 15973 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15973'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15973'
 id: 15974 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15974'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15974'
 id: 15975 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '15975'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15975'
 id: 15976 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '15976'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15976'
 id: 15977 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15977'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15977'
 id: 15978 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15978'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15978'
 id: 15979 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '15979'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15979'
 id: 15980 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '15980'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15980'
 id: 15981 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '15981'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15981'
 id: 15982 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '15982'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15982'
 id: 15983 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15983'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15983'
 id: 15984 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '15984'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15984'
 id: 15985 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '15985'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15985'
 id: 15986 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '15986'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15986'
 id: 15987 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '15987'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15987'
 id: 15988 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '15988'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15988'
 id: 15989 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '15989'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15989'
 id: 15990 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15990'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15990'
 id: 15991 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '15991'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15991'
 id: 15992 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '15992'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15992'
 id: 15993 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '15993'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15993'
 id: 15994 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '15994'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15994'
 id: 15995 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '15995'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15995'
 id: 15996 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '15996'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15996'
 id: 15997 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '15997'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15997'
 id: 15998 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '15998'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15998'
 id: 15999 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '15999'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '15999'
 id: 16000 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16000'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16000'
 id: 16001 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16001'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16001'
 id: 16002 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16002'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16002'
 id: 16003 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '16003'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16003'
 id: 16004 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16004'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16004'
 id: 16005 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '16005'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16005'
 id: 16006 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '16006'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16006'
 id: 16007 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16007'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16007'
 id: 16008 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16008'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16008'
 id: 16009 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16009'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16009'
 id: 16010 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '16010'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16010'
 id: 16011 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '16011'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16011'
 id: 16012 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16012'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16012'
 id: 16013 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '16013'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16013'
 id: 16014 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16014'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16014'
 id: 16015 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '16015'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16015'
 id: 16016 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '16016'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16016'
 id: 16017 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '16017'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16017'
 id: 16018 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '16018'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16018'
 id: 16019 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '16019'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16019'
 id: 16020 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '16020'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16020'
 id: 16021 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '16021'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16021'
 id: 16022 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16022'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16022'
 id: 16023 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '16023'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16023'
 id: 16024 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '16024'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16024'
 id: 16025 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '16025'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16025'
 id: 16026 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16026'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16026'
 id: 16027 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '16027'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16027'
 id: 16028 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '16028'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16028'
 id: 16029 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '16029'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16029'
 id: 16030 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '16030'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16030'
 id: 16031 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '16031'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16031'
 id: 16032 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '16032'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16032'
 id: 16033 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16033'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16033'
 id: 16034 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '16034'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16034'
 id: 16035 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '16035'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16035'
 id: 16036 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '16036'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16036'
 id: 16037 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16037'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16037'
 id: 16038 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16038'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16038'
 id: 16039 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '16039'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16039'
 id: 16040 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16040'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16040'
 id: 16041 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16041'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16041'
 id: 16042 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '16042'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16042'
 id: 16043 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '16043'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16043'
 id: 16044 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16044'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16044'
 id: 16045 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16045'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16045'
 id: 16046 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16046'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16046'
 id: 16047 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16047'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16047'
 id: 16048 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16048'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16048'
 id: 16049 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16049'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16049'
 id: 16050 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16050'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16050'
 id: 16051 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16051'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16051'
 id: 16052 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '16052'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16052'
 id: 16053 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '16053'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16053'
 id: 16054 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '16054'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16054'
 id: 16055 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '16055'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16055'
 id: 16056 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '16056'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16056'
 id: 16057 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '16057'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16057'
 id: 16058 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16058'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16058'
 id: 16059 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16059'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16059'
 id: 16060 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '16060'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16060'
 id: 16061 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16061'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16061'
 id: 16062 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '16062'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16062'
 id: 16063 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16063'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16063'
 id: 16064 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16064'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16064'
 id: 16065 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '16065'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16065'
 id: 16066 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16066'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16066'
 id: 16067 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16067'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16067'
 id: 16068 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16068'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16068'
 id: 16069 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16069'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16069'
 id: 16070 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16070'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16070'
 id: 16071 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '16071'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16071'
 id: 16072 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16072'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16072'
 id: 16073 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '16073'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16073'
 id: 16074 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16074'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16074'
 id: 16075 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16075'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16075'
 id: 16076 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '16076'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16076'
 id: 16077 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '16077'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16077'
 id: 16078 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16078'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16078'
 id: 16079 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '16079'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16079'
 id: 16080 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16080'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16080'
 id: 16081 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '16081'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16081'
 id: 16082 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16082'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16082'
 id: 16083 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16083'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16083'
 id: 16084 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16084'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16084'
 id: 16085 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16085'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16085'
 id: 16086 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '16086'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16086'
 id: 16087 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '16087'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16087'
 id: 16088 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16088'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16088'
 id: 16089 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16089'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16089'
 id: 16090 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16090'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16090'
 id: 16091 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16091'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16091'
 id: 16092 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '16092'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16092'
 id: 16093 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '16093'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16093'
 id: 16094 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16094'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16094'
 id: 16095 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16095'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16095'
 id: 16096 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16096'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16096'
 id: 16097 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16097'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16097'
 id: 16098 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '16098'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16098'
 id: 16099 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '16099'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16099'
 id: 16100 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '16100'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16100'
 id: 16101 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '16101'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16101'
 id: 16102 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16102'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16102'
 id: 16103 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16103'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16103'
 id: 16104 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '16104'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16104'
 id: 16105 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16105'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16105'
 id: 16106 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '16106'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16106'
 id: 16107 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16107'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16107'
 id: 16108 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16108'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16108'
 id: 16109 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16109'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16109'
 id: 16110 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16110'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16110'
 id: 16111 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16111'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16111'
 id: 16112 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '16112'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16112'
 id: 16113 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16113'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16113'
 id: 16114 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16114'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16114'
 id: 16115 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '16115'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16115'
 id: 16116 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16116'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16116'
 id: 16117 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16117'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16117'
 id: 16118 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16118'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16118'
 id: 16119 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16119'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16119'
 id: 16120 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '16120'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16120'
 id: 16121 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16121'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16121'
 id: 16122 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16122'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16122'
 id: 16123 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16123'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16123'
 id: 16124 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16124'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16124'
 id: 16125 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '16125'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16125'
 id: 16126 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '16126'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16126'
 id: 16127 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '16127'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16127'
 id: 16128 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16128'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16128'
 id: 16129 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16129'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16129'
 id: 16130 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '16130'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16130'
 id: 16131 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16131'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16131'
 id: 16132 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '16132'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16132'
 id: 16133 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '16133'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16133'
 id: 16134 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16134'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16134'
 id: 16135 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16135'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16135'
 id: 16136 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16136'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16136'
 id: 16137 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16137'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16137'
 id: 16138 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '16138'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16138'
 id: 16139 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16139'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16139'
 id: 16140 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '16140'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16140'
 id: 16141 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '16141'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16141'
 id: 16142 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16142'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16142'
 id: 16143 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16143'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16143'
 id: 16144 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16144'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16144'
 id: 16145 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '16145'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16145'
 id: 16146 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16146'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16146'
 id: 16147 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '16147'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16147'
 id: 16148 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '16148'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16148'
 id: 16149 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '16149'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16149'
 id: 16150 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '16150'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16150'
 id: 16151 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '16151'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16151'
 id: 16152 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '16152'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16152'
 id: 16153 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16153'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16153'
 id: 16154 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16154'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16154'
 id: 16155 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '16155'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16155'
 id: 16156 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16156'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16156'
 id: 16157 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '16157'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16157'
 id: 16158 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16158'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16158'
 id: 16159 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '16159'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16159'
 id: 16160 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16160'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16160'
 id: 16161 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16161'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16161'
 id: 16162 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '16162'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16162'
 id: 16163 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '16163'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16163'
 id: 16164 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '16164'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16164'
 id: 16165 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '16165'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16165'
 id: 16166 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16166'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16166'
 id: 16167 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16167'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16167'
 id: 16168 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '16168'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16168'
 id: 16169 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16169'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16169'

 id: 16170 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16170'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16170'
 id: 16171 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '16171'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16171'
 id: 16172 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '16172'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16172'
 id: 16173 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '16173'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16173'
 id: 16174 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16174'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16174'
 id: 16175 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '16175'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16175'
 id: 16176 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16176'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16176'
 id: 16177 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16177'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16177'
 id: 16178 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '16178'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16178'
 id: 16179 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '16179'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16179'
 id: 16180 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '16180'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16180'
 id: 16181 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '16181'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16181'
 id: 16182 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16182'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16182'
 id: 16183 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16183'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16183'
 id: 16184 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16184'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16184'
 id: 16185 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16185'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16185'
 id: 16186 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16186'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16186'
 id: 16187 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '16187'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16187'
 id: 16188 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '16188'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16188'
 id: 16189 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '16189'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16189'
 id: 16190 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16190'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16190'
 id: 16191 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '16191'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16191'
 id: 16192 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16192'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16192'
 id: 16193 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16193'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16193'
 id: 16194 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '16194'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16194'
 id: 16195 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '16195'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16195'
 id: 16196 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16196'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16196'
 id: 16197 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '16197'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16197'
 id: 16198 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '16198'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16198'
 id: 16199 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16199'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16199'
 id: 16200 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16200'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16200'
 id: 16201 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '16201'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16201'
 id: 16202 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '16202'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16202'
 id: 16203 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '16203'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16203'
 id: 16204 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16204'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16204'
 id: 16205 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '16205'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16205'
 id: 16206 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '16206'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16206'
 id: 16207 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16207'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16207'
 id: 16208 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '16208'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16208'
 id: 16209 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16209'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16209'
 id: 16210 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16210'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16210'
 id: 16211 // word: 57
UPDATE job_vacancies SET domain_id =  '57' where raw_id = '16211'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16211'
 id: 16212 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16212'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16212'
 id: 16213 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16213'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16213'
 id: 16214 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16214'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16214'
 id: 16215 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '16215'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16215'
 id: 16216 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16216'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16216'
 id: 16217 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '16217'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16217'
 id: 16218 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16218'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16218'
 id: 16219 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '16219'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16219'
 id: 16220 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '16220'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16220'
 id: 16221 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16221'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16221'
 id: 16222 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '16222'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16222'
 id: 16223 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16223'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16223'
 id: 16224 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16224'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16224'
 id: 16225 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16225'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16225'
 id: 16226 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16226'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16226'
 id: 16227 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16227'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16227'
 id: 16228 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16228'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16228'
 id: 16229 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '16229'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16229'
 id: 16230 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16230'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16230'
 id: 16231 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16231'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16231'
 id: 16232 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16232'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16232'
 id: 16233 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16233'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16233'
 id: 16234 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16234'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16234'
 id: 16235 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16235'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16235'
 id: 16236 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '16236'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16236'
 id: 16237 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16237'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16237'
 id: 16238 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16238'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16238'
 id: 16239 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16239'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16239'
 id: 16240 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '16240'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16240'
 id: 16241 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16241'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16241'
 id: 16242 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16242'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16242'
 id: 16243 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16243'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16243'
 id: 16244 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16244'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16244'
 id: 16245 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16245'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16245'
 id: 16246 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '16246'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16246'
 id: 16247 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16247'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16247'
 id: 16248 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16248'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16248'
 id: 16249 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '16249'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16249'
 id: 16250 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '16250'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16250'
 id: 16251 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '16251'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16251'
 id: 16252 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '16252'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16252'
 id: 16253 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16253'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16253'
 id: 16254 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '16254'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16254'
 id: 16255 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '16255'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16255'
 id: 16256 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '16256'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16256'
 id: 16257 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16257'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16257'
 id: 16258 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '16258'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16258'
 id: 16259 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16259'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16259'
 id: 16260 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16260'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16260'
 id: 16261 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16261'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16261'
 id: 16262 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16262'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16262'
 id: 16263 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16263'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16263'
 id: 16264 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '16264'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16264'
 id: 16265 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16265'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16265'
 id: 16266 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16266'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16266'
 id: 16267 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16267'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16267'
 id: 16268 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '16268'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16268'
 id: 16269 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16269'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16269'
 id: 16270 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16270'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16270'
 id: 16271 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16271'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16271'
 id: 16272 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '16272'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16272'
 id: 16273 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16273'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16273'
 id: 16274 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16274'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16274'
 id: 16275 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16275'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16275'
 id: 16276 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16276'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16276'
 id: 16277 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '16277'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16277'
 id: 16278 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '16278'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16278'
 id: 16279 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16279'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16279'
 id: 16280 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16280'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16280'
 id: 16281 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16281'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16281'
 id: 16282 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16282'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16282'
 id: 16283 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '16283'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16283'
 id: 16284 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16284'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16284'
 id: 16285 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16285'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16285'
 id: 16286 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '16286'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16286'
 id: 16287 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16287'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16287'
 id: 16288 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16288'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16288'
 id: 16289 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16289'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16289'
 id: 16290 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16290'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16290'
 id: 16291 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '16291'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16291'
 id: 16292 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16292'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16292'
 id: 16293 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16293'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16293'
 id: 16294 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '16294'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16294'
 id: 16295 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16295'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16295'
 id: 16296 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16296'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16296'
 id: 16297 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16297'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16297'
 id: 16298 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16298'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16298'
 id: 16299 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '16299'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16299'
 id: 16300 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '16300'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16300'
 id: 16301 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16301'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16301'
 id: 16302 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16302'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16302'
 id: 16303 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16303'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16303'
 id: 16304 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '16304'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16304'
 id: 16305 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16305'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16305'
 id: 16306 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '16306'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16306'
 id: 16307 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16307'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16307'
 id: 16308 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16308'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16308'
 id: 16309 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16309'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16309'
 id: 16310 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16310'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16310'
 id: 16311 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '16311'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16311'
 id: 16312 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16312'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16312'
 id: 16313 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16313'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16313'
 id: 16314 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16314'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16314'
 id: 16315 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16315'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16315'
 id: 16316 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16316'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16316'
 id: 16317 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16317'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16317'
 id: 16318 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16318'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16318'
 id: 16319 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16319'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16319'
 id: 16320 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16320'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16320'
 id: 16321 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16321'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16321'
 id: 16322 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16322'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16322'
 id: 16323 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16323'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16323'
 id: 16324 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16324'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16324'
 id: 16325 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16325'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16325'
 id: 16326 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16326'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16326'
 id: 16327 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16327'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16327'
 id: 16328 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16328'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16328'
 id: 16329 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '16329'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16329'
 id: 16330 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16330'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16330'
 id: 16331 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '16331'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16331'
 id: 16332 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16332'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16332'
 id: 16333 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16333'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16333'
 id: 16334 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '16334'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16334'
 id: 16335 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16335'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16335'
 id: 16336 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16336'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16336'
 id: 16337 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16337'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16337'
 id: 16338 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16338'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16338'
 id: 16339 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '16339'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16339'
 id: 16340 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16340'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16340'
 id: 16341 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '16341'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16341'
 id: 16342 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '16342'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16342'
 id: 16343 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '16343'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16343'
 id: 16344 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16344'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16344'
 id: 16345 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16345'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16345'
 id: 16346 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '16346'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16346'
 id: 16347 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '16347'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16347'
 id: 16348 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16348'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16348'
 id: 16349 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16349'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16349'
 id: 16350 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16350'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16350'
 id: 16351 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '16351'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16351'
 id: 16352 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16352'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16352'
 id: 16353 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16353'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16353'
 id: 16354 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '16354'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16354'
 id: 16355 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '16355'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16355'
 id: 16356 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '16356'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16356'
 id: 16357 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '16357'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16357'
 id: 16358 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '16358'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16358'
 id: 16359 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16359'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16359'
 id: 16360 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16360'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16360'
 id: 16361 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16361'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16361'
 id: 16362 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '16362'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16362'
 id: 16363 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '16363'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16363'
 id: 16364 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16364'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16364'
 id: 16365 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16365'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16365'
 id: 16366 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16366'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16366'
 id: 16367 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16367'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16367'
 id: 16368 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16368'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16368'
 id: 16369 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '16369'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16369'
 id: 16370 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16370'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16370'
 id: 16371 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '16371'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16371'
 id: 16372 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16372'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16372'
 id: 16373 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16373'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16373'
 id: 16374 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16374'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16374'
 id: 16375 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16375'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16375'
 id: 16376 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '16376'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16376'
 id: 16377 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16377'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16377'
 id: 16378 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16378'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16378'
 id: 16379 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16379'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16379'
 id: 16380 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16380'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16380'
 id: 16381 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '16381'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16381'
 id: 16382 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16382'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16382'
 id: 16383 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16383'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16383'
 id: 16384 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '16384'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16384'
 id: 16385 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '16385'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16385'
 id: 16386 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16386'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16386'
 id: 16387 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '16387'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16387'
 id: 16388 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16388'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16388'
 id: 16389 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '16389'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16389'
 id: 16390 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '16390'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16390'
 id: 16391 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16391'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16391'
 id: 16392 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16392'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16392'
 id: 16393 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '16393'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16393'
 id: 16394 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16394'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16394'
 id: 16395 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16395'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16395'
 id: 16396 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '16396'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16396'
 id: 16397 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '16397'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16397'
 id: 16398 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16398'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16398'
 id: 16399 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16399'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16399'
 id: 16400 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16400'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16400'
 id: 16401 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '16401'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16401'
 id: 16402 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '16402'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16402'
 id: 16403 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16403'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16403'
 id: 16404 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16404'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16404'
 id: 16405 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16405'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16405'
 id: 16406 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16406'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16406'
 id: 16407 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16407'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16407'
 id: 16408 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16408'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16408'
 id: 16409 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16409'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16409'
 id: 16410 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16410'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16410'
 id: 16411 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16411'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16411'
 id: 16412 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16412'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16412'
 id: 16413 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '16413'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16413'
 id: 16414 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16414'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16414'
 id: 16415 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16415'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16415'
 id: 16416 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16416'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16416'
 id: 16417 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16417'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16417'
 id: 16418 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16418'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16418'
 id: 16419 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '16419'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16419'
 id: 16420 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '16420'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16420'
 id: 16421 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '16421'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16421'
 id: 16422 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '16422'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16422'
 id: 16423 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16423'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16423'
 id: 16424 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16424'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16424'
 id: 16425 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16425'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16425'
 id: 16426 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16426'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16426'
 id: 16427 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16427'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16427'
 id: 16428 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '16428'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16428'
 id: 16429 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16429'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16429'
 id: 16430 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16430'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16430'
 id: 16431 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16431'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16431'
 id: 16432 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '16432'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16432'
 id: 16433 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16433'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16433'
 id: 16434 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16434'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16434'
 id: 16435 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16435'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16435'
 id: 16436 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '16436'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16436'
 id: 16437 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '16437'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16437'
 id: 16438 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16438'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16438'
 id: 16439 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16439'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16439'
 id: 16440 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '16440'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16440'
 id: 16441 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16441'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16441'
 id: 16442 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '16442'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16442'
 id: 16443 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '16443'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16443'
 id: 16444 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '16444'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16444'
 id: 16445 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16445'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16445'
 id: 16446 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '16446'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16446'
 id: 16447 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16447'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16447'
 id: 16448 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '16448'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16448'
 id: 16449 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '16449'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16449'
 id: 16450 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16450'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16450'
 id: 16451 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '16451'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16451'
 id: 16452 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16452'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16452'
 id: 16453 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16453'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16453'
 id: 16454 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16454'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16454'
 id: 16455 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '16455'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16455'
 id: 16456 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16456'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16456'
 id: 16457 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '16457'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16457'
 id: 16458 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16458'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16458'
 id: 16459 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '16459'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16459'
 id: 16460 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16460'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16460'
 id: 16461 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16461'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16461'
 id: 16462 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '16462'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16462'
 id: 16463 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16463'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16463'
 id: 16464 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16464'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16464'
 id: 16465 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16465'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16465'
 id: 16466 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16466'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16466'
 id: 16467 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16467'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16467'
 id: 16468 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16468'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16468'
 id: 16469 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16469'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16469'
 id: 16470 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '16470'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16470'
 id: 16471 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16471'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16471'
 id: 16472 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16472'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16472'
 id: 16473 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16473'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16473'
 id: 16474 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16474'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16474'
 id: 16475 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16475'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16475'
 id: 16476 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '16476'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16476'
 id: 16477 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16477'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16477'
 id: 16478 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16478'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16478'
 id: 16479 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16479'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16479'
 id: 16480 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16480'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16480'
 id: 16481 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16481'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16481'
 id: 16482 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16482'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16482'
 id: 16483 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '16483'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16483'
 id: 16484 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16484'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16484'
 id: 16485 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16485'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16485'
 id: 16486 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16486'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16486'
 id: 16487 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '16487'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16487'
 id: 16488 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16488'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16488'
 id: 16489 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16489'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16489'
 id: 16490 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16490'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16490'
 id: 16491 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '16491'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16491'
 id: 16492 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16492'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16492'
 id: 16493 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16493'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16493'
 id: 16494 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16494'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16494'
 id: 16495 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '16495'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16495'
 id: 16496 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16496'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16496'
 id: 16497 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16497'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16497'
 id: 16498 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16498'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16498'
 id: 16499 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16499'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16499'
 id: 16500 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16500'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16500'
 id: 16501 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16501'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16501'
 id: 16502 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '16502'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16502'
 id: 16503 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16503'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16503'
 id: 16504 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16504'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16504'
 id: 16505 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16505'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16505'
 id: 16506 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16506'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16506'
 id: 16507 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16507'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16507'
 id: 16508 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16508'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16508'
 id: 16509 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '16509'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16509'
 id: 16510 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16510'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16510'
 id: 16511 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16511'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16511'
 id: 16512 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '16512'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16512'
 id: 16513 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '16513'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16513'
 id: 16514 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16514'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16514'
 id: 16515 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16515'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16515'
 id: 16516 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16516'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16516'
 id: 16517 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16517'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16517'
 id: 16518 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16518'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16518'
 id: 16519 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16519'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16519'
 id: 16520 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16520'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16520'
 id: 16521 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16521'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16521'
 id: 16522 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16522'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16522'
 id: 16523 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '16523'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16523'
 id: 16524 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16524'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16524'
 id: 16525 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16525'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16525'
 id: 16526 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '16526'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16526'
 id: 16527 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16527'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16527'
 id: 16528 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16528'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16528'
 id: 16529 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '16529'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16529'
 id: 16530 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '16530'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16530'
 id: 16531 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16531'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16531'
 id: 16532 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16532'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16532'
 id: 16533 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16533'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16533'
 id: 16534 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16534'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16534'
 id: 16535 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '16535'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16535'
 id: 16536 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '16536'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16536'
 id: 16537 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16537'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16537'
 id: 16538 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '16538'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16538'
 id: 16539 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16539'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16539'
 id: 16540 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16540'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16540'
 id: 16541 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16541'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16541'
 id: 16542 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16542'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16542'
 id: 16543 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '16543'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16543'
 id: 16544 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16544'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16544'
 id: 16545 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16545'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16545'
 id: 16546 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16546'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16546'
 id: 16547 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '16547'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16547'
 id: 16548 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16548'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16548'
 id: 16549 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16549'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16549'
 id: 16550 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16550'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16550'
 id: 16551 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16551'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16551'
 id: 16552 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '16552'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16552'
 id: 16553 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16553'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16553'
 id: 16554 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16554'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16554'
 id: 16555 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '16555'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16555'
 id: 16556 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16556'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16556'
 id: 16557 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '16557'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16557'
 id: 16558 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '16558'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16558'
 id: 16559 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '16559'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16559'
 id: 16560 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16560'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16560'
 id: 16561 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '16561'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16561'
 id: 16562 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16562'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16562'
 id: 16563 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16563'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16563'
 id: 16564 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '16564'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16564'
 id: 16565 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16565'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16565'
 id: 16566 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16566'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16566'
 id: 16567 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16567'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16567'
 id: 16568 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16568'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16568'
 id: 16569 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16569'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16569'
 id: 16570 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16570'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16570'
 id: 16571 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16571'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16571'
 id: 16572 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16572'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16572'
 id: 16573 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16573'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16573'
 id: 16574 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16574'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16574'

 id: 16575 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '16575'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16575'
 id: 16576 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '16576'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16576'
 id: 16577 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16577'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16577'
 id: 16578 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16578'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16578'
 id: 16579 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16579'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16579'
 id: 16580 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16580'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16580'
 id: 16581 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16581'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16581'
 id: 16582 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '16582'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16582'
 id: 16583 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16583'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16583'
 id: 16584 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '16584'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16584'
 id: 16585 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16585'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16585'
 id: 16586 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '16586'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16586'
 id: 16587 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16587'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16587'
 id: 16588 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16588'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16588'
 id: 16589 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '16589'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16589'
 id: 16590 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16590'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16590'
 id: 16591 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16591'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16591'
 id: 16592 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16592'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16592'
 id: 16593 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16593'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16593'
 id: 16594 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16594'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16594'
 id: 16595 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16595'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16595'
 id: 16596 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '16596'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16596'
 id: 16597 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '16597'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16597'
 id: 16598 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16598'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16598'
 id: 16599 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16599'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16599'
 id: 16600 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16600'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16600'
 id: 16601 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16601'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16601'
 id: 16602 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16602'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16602'
 id: 16603 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16603'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16603'
 id: 16604 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '16604'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16604'
 id: 16605 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16605'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16605'
 id: 16606 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16606'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16606'
 id: 16607 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '16607'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16607'
 id: 16608 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '16608'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16608'
 id: 16609 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16609'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16609'
 id: 16610 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '16610'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16610'
 id: 16611 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '16611'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16611'
 id: 16612 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16612'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16612'
 id: 16613 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16613'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16613'
 id: 16614 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '16614'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16614'
 id: 16615 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '16615'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16615'
 id: 16616 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16616'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16616'
 id: 16617 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '16617'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16617'
 id: 16618 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16618'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16618'
 id: 16619 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16619'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16619'
 id: 16620 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '16620'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16620'
 id: 16621 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '16621'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16621'
 id: 16622 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '16622'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16622'
 id: 16623 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16623'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16623'
 id: 16624 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16624'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16624'
 id: 16625 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16625'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16625'
 id: 16626 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16626'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16626'
 id: 16627 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '16627'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16627'
 id: 16628 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '16628'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16628'
 id: 16629 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16629'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16629'
 id: 16630 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16630'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16630'
 id: 16631 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '16631'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16631'
 id: 16632 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16632'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16632'
 id: 16633 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16633'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16633'
 id: 16634 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '16634'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16634'
 id: 16635 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16635'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16635'
 id: 16636 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '16636'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16636'
 id: 16637 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16637'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16637'
 id: 16638 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16638'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16638'
 id: 16639 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '16639'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16639'
 id: 16640 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16640'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16640'
 id: 16641 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16641'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16641'
 id: 16642 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '16642'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16642'
 id: 16643 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16643'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16643'
 id: 16644 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16644'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16644'
 id: 16645 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16645'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16645'
 id: 16646 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16646'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16646'
 id: 16647 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '16647'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16647'
 id: 16648 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16648'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16648'
 id: 16649 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16649'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16649'
 id: 16650 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '16650'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16650'
 id: 16651 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16651'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16651'
 id: 16652 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16652'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16652'
 id: 16653 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '16653'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16653'
 id: 16654 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16654'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16654'
 id: 16655 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16655'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16655'
 id: 16656 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '16656'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16656'
 id: 16657 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '16657'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16657'
 id: 16658 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16658'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16658'
 id: 16659 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '16659'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16659'
 id: 16660 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16660'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16660'
 id: 16661 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16661'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16661'
 id: 16662 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '16662'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16662'
 id: 16663 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16663'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16663'
 id: 16664 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16664'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16664'
 id: 16665 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '16665'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16665'
 id: 16666 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16666'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16666'
 id: 16667 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '16667'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16667'
 id: 16668 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16668'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16668'
 id: 16669 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '16669'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16669'
 id: 16670 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '16670'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16670'
 id: 16671 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16671'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16671'
 id: 16672 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '16672'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16672'
 id: 16673 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16673'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16673'
 id: 16674 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '16674'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16674'
 id: 16675 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16675'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16675'
 id: 16676 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16676'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16676'

 id: 16677 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '16677'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16677'
 id: 16678 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16678'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16678'
 id: 16679 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16679'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16679'
 id: 16680 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16680'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16680'
 id: 16681 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '16681'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16681'
 id: 16682 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16682'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16682'
 id: 16683 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '16683'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16683'
 id: 16684 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '16684'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16684'
 id: 16685 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16685'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16685'
 id: 16686 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16686'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16686'
 id: 16687 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '16687'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16687'
 id: 16688 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '16688'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16688'
 id: 16689 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '16689'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16689'
 id: 16690 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16690'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16690'
 id: 16691 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16691'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16691'
 id: 16692 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16692'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16692'
 id: 16693 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16693'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16693'
 id: 16694 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16694'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16694'
 id: 16695 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16695'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16695'
 id: 16696 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '16696'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16696'
 id: 16697 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16697'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16697'
 id: 16698 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '16698'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16698'
 id: 16699 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16699'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16699'
 id: 16700 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '16700'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16700'
 id: 16701 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16701'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16701'
 id: 16702 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '16702'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16702'
 id: 16703 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '16703'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16703'
 id: 16704 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16704'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16704'
 id: 16705 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '16705'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16705'
 id: 16706 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '16706'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16706'
 id: 16707 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16707'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16707'
 id: 16708 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16708'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16708'
 id: 16709 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '16709'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16709'
 id: 16710 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16710'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16710'
 id: 16711 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16711'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16711'
 id: 16712 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '16712'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16712'
 id: 16713 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16713'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16713'
 id: 16714 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '16714'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16714'
 id: 16715 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16715'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16715'
 id: 16716 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16716'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16716'
 id: 16717 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '16717'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16717'
 id: 16718 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '16718'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16718'
 id: 16719 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16719'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16719'
 id: 16720 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '16720'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16720'
 id: 16721 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '16721'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16721'
 id: 16722 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16722'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16722'
 id: 16723 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16723'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16723'
 id: 16724 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '16724'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16724'
 id: 16725 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16725'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16725'
 id: 16726 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16726'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16726'
 id: 16727 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16727'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16727'
 id: 16728 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16728'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16728'
 id: 16729 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16729'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16729'
 id: 16730 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16730'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16730'
 id: 16731 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16731'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16731'
 id: 16732 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16732'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16732'
 id: 16733 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '16733'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16733'
 id: 16734 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16734'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16734'
 id: 16735 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16735'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16735'
 id: 16736 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16736'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16736'
 id: 16737 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '16737'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16737'
 id: 16738 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16738'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16738'
 id: 16739 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '16739'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16739'
 id: 16740 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16740'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16740'
 id: 16741 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '16741'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16741'
 id: 16742 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '16742'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16742'
 id: 16743 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '16743'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16743'
 id: 16744 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16744'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16744'
 id: 16745 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16745'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16745'
 id: 16746 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16746'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16746'
 id: 16747 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16747'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16747'
 id: 16748 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16748'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16748'
 id: 16749 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16749'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16749'
 id: 16750 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '16750'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16750'
 id: 16751 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '16751'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16751'
 id: 16752 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '16752'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16752'
 id: 16753 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '16753'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16753'
 id: 16754 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16754'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16754'
 id: 16755 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16755'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16755'
 id: 16756 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16756'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16756'
 id: 16757 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '16757'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16757'
 id: 16758 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16758'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16758'
 id: 16759 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16759'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16759'
 id: 16760 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16760'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16760'
 id: 16761 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '16761'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16761'
 id: 16762 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16762'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16762'
 id: 16763 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16763'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16763'
 id: 16764 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16764'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16764'
 id: 16765 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16765'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16765'
 id: 16766 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16766'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16766'
 id: 16767 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '16767'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16767'
 id: 16768 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '16768'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16768'
 id: 16769 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '16769'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16769'
 id: 16770 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16770'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16770'
 id: 16771 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16771'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16771'
 id: 16772 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16772'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16772'
 id: 16773 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '16773'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16773'
 id: 16774 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16774'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16774'
 id: 16775 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16775'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16775'
 id: 16776 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '16776'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16776'
 id: 16777 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '16777'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16777'
 id: 16778 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '16778'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16778'
 id: 16779 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '16779'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16779'
 id: 16780 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16780'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16780'
 id: 16781 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16781'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16781'
 id: 16782 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16782'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16782'
 id: 16783 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '16783'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16783'
 id: 16784 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '16784'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16784'
 id: 16785 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16785'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16785'
 id: 16786 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16786'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16786'
 id: 16787 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16787'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16787'
 id: 16788 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16788'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16788'
 id: 16789 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '16789'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16789'
 id: 16790 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16790'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16790'
 id: 16791 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16791'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16791'
 id: 16792 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16792'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16792'
 id: 16793 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16793'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16793'
 id: 16794 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16794'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16794'
 id: 16795 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16795'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16795'
 id: 16796 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '16796'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16796'
 id: 16797 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16797'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16797'
 id: 16798 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16798'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16798'
 id: 16799 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16799'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16799'
 id: 16800 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16800'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16800'
 id: 16801 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16801'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16801'
 id: 16802 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16802'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16802'
 id: 16803 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16803'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16803'
 id: 16804 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '16804'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16804'
 id: 16805 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '16805'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16805'
 id: 16806 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '16806'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16806'
 id: 16807 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '16807'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16807'
 id: 16808 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '16808'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16808'
 id: 16809 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '16809'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16809'
 id: 16810 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16810'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16810'
 id: 16811 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16811'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16811'
 id: 16812 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16812'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16812'
 id: 16813 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '16813'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16813'
 id: 16814 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '16814'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16814'
 id: 16815 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16815'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16815'
 id: 16816 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16816'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16816'
 id: 16817 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16817'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16817'
 id: 16818 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16818'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16818'
 id: 16819 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16819'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16819'
 id: 16820 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '16820'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16820'
 id: 16821 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '16821'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16821'
 id: 16822 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '16822'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16822'
 id: 16823 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '16823'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16823'
 id: 16824 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16824'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16824'
 id: 16825 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '16825'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16825'
 id: 16826 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16826'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16826'
 id: 16827 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16827'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16827'
 id: 16828 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '16828'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16828'
 id: 16829 // word: 50
UPDATE job_vacancies SET domain_id =  '50' where raw_id = '16829'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16829'
 id: 16830 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16830'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16830'
 id: 16831 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '16831'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16831'
 id: 16832 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16832'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16832'
 id: 16833 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '16833'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16833'
 id: 16834 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16834'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16834'
 id: 16835 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '16835'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16835'
 id: 16836 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16836'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16836'
 id: 16837 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '16837'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16837'
 id: 16838 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16838'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16838'
 id: 16839 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '16839'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16839'
 id: 16840 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16840'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16840'
 id: 16841 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '16841'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16841'
 id: 16842 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16842'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16842'
 id: 16843 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '16843'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16843'
 id: 16844 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '16844'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16844'
 id: 16845 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16845'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16845'
 id: 16846 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16846'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16846'
 id: 16847 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16847'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16847'
 id: 16848 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16848'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16848'
 id: 16849 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '16849'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16849'
 id: 16850 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '16850'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16850'
 id: 16851 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '16851'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16851'
 id: 16852 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '16852'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16852'
 id: 16853 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '16853'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16853'
 id: 16854 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16854'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16854'
 id: 16855 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16855'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16855'
 id: 16856 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16856'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16856'
 id: 16857 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16857'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16857'
 id: 16858 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '16858'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16858'
 id: 16859 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16859'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16859'
 id: 16860 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16860'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16860'
 id: 16861 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16861'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16861'
 id: 16862 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16862'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16862'
 id: 16863 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16863'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16863'
 id: 16864 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '16864'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16864'
 id: 16865 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16865'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16865'
 id: 16866 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16866'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16866'
 id: 16867 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16867'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16867'
 id: 16868 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16868'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16868'
 id: 16869 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '16869'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16869'
 id: 16870 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16870'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16870'
 id: 16871 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '16871'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16871'
 id: 16872 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16872'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16872'
 id: 16873 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16873'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16873'
 id: 16874 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16874'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16874'
 id: 16875 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '16875'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16875'
 id: 16876 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16876'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16876'
 id: 16877 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16877'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16877'
 id: 16878 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16878'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16878'
 id: 16879 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16879'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16879'
 id: 16880 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16880'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16880'
 id: 16881 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16881'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16881'
 id: 16882 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '16882'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16882'
 id: 16883 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16883'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16883'
 id: 16884 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16884'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16884'
 id: 16885 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16885'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16885'
 id: 16886 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '16886'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16886'
 id: 16887 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '16887'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16887'
 id: 16888 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16888'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16888'
 id: 16889 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16889'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16889'
 id: 16890 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16890'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16890'
 id: 16891 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '16891'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16891'
 id: 16892 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '16892'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16892'
 id: 16893 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '16893'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16893'
 id: 16894 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '16894'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16894'
 id: 16895 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16895'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16895'
 id: 16896 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '16896'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16896'
 id: 16897 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16897'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16897'
 id: 16898 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16898'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16898'
 id: 16899 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16899'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16899'
 id: 16900 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '16900'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16900'
 id: 16901 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '16901'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16901'
 id: 16902 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '16902'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16902'
 id: 16903 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '16903'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16903'
 id: 16904 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16904'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16904'
 id: 16905 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16905'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16905'
 id: 16906 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16906'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16906'
 id: 16907 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '16907'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16907'
 id: 16908 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16908'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16908'
 id: 16909 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16909'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16909'
 id: 16910 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '16910'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16910'
 id: 16911 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '16911'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16911'
 id: 16912 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '16912'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16912'
 id: 16913 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16913'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16913'
 id: 16914 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '16914'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16914'
 id: 16915 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '16915'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16915'
 id: 16916 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16916'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16916'
 id: 16917 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16917'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16917'
 id: 16918 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16918'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16918'
 id: 16919 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '16919'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16919'
 id: 16920 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16920'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16920'
 id: 16921 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '16921'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16921'
 id: 16922 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16922'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16922'
 id: 16923 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '16923'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16923'
 id: 16924 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '16924'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16924'
 id: 16925 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '16925'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16925'
 id: 16926 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '16926'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16926'
 id: 16927 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16927'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16927'
 id: 16928 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16928'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16928'
 id: 16929 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16929'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16929'
 id: 16930 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '16930'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16930'
 id: 16931 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16931'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16931'
 id: 16932 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16932'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16932'
 id: 16933 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16933'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16933'
 id: 16934 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16934'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16934'
 id: 16935 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '16935'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16935'
 id: 16936 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16936'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16936'
 id: 16937 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16937'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16937'
 id: 16938 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '16938'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16938'
 id: 16939 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16939'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16939'
 id: 16940 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '16940'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16940'
 id: 16941 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16941'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16941'
 id: 16942 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16942'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16942'
 id: 16943 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16943'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16943'
 id: 16944 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16944'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16944'
 id: 16945 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16945'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16945'
 id: 16946 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '16946'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16946'
 id: 16947 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '16947'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16947'
 id: 16948 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '16948'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16948'
 id: 16949 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '16949'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16949'
 id: 16950 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16950'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16950'
 id: 16951 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16951'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16951'
 id: 16952 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '16952'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16952'
 id: 16953 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16953'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16953'
 id: 16954 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '16954'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16954'
 id: 16955 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '16955'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16955'
 id: 16956 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '16956'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16956'
 id: 16957 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16957'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16957'
 id: 16958 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '16958'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16958'
 id: 16959 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16959'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16959'
 id: 16960 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16960'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16960'
 id: 16961 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '16961'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16961'
 id: 16962 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16962'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16962'
 id: 16963 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16963'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16963'
 id: 16964 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16964'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16964'
 id: 16965 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '16965'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16965'
 id: 16966 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16966'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16966'
 id: 16967 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16967'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16967'
 id: 16968 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '16968'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16968'
 id: 16969 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16969'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16969'
 id: 16970 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16970'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16970'
 id: 16971 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16971'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16971'
 id: 16972 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '16972'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16972'
 id: 16973 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16973'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16973'
 id: 16974 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16974'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16974'
 id: 16975 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '16975'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16975'
 id: 16976 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16976'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16976'
 id: 16977 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16977'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16977'
 id: 16978 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '16978'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16978'
 id: 16979 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16979'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16979'
 id: 16980 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16980'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16980'
 id: 16981 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16981'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16981'
 id: 16982 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '16982'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16982'
 id: 16983 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '16983'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16983'
 id: 16984 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '16984'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16984'
 id: 16985 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16985'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16985'
 id: 16986 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16986'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16986'
 id: 16987 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '16987'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16987'
 id: 16988 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '16988'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16988'
 id: 16989 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '16989'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16989'
 id: 16990 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16990'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16990'
 id: 16991 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16991'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16991'
 id: 16992 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16992'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16992'
 id: 16993 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '16993'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16993'
 id: 16994 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '16994'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16994'
 id: 16995 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16995'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16995'
 id: 16996 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '16996'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16996'
 id: 16997 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '16997'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16997'
 id: 16998 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '16998'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16998'
 id: 16999 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '16999'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '16999'
 id: 17000 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '17000'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17000'
 id: 17001 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '17001'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17001'
 id: 17002 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17002'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17002'
 id: 17003 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '17003'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17003'
 id: 17004 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '17004'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17004'
 id: 17005 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '17005'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17005'
 id: 17006 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '17006'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17006'
 id: 17007 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17007'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17007'
 id: 17008 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '17008'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17008'
 id: 17009 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17009'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17009'
 id: 17010 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17010'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17010'
 id: 17011 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '17011'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17011'
 id: 17012 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17012'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17012'
 id: 17013 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '17013'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17013'
 id: 17014 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '17014'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17014'
 id: 17015 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17015'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17015'
 id: 17016 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17016'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17016'
 id: 17017 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '17017'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17017'
 id: 17018 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17018'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17018'
 id: 17019 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17019'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17019'
 id: 17020 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '17020'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17020'
 id: 17021 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '17021'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17021'
 id: 17022 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '17022'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17022'
 id: 17023 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '17023'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17023'
 id: 17024 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17024'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17024'
 id: 17025 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '17025'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17025'
 id: 17026 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17026'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17026'
 id: 17027 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17027'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17027'
 id: 17028 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17028'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17028'
 id: 17029 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17029'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17029'
 id: 17030 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '17030'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17030'
 id: 17031 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '17031'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17031'
 id: 17032 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '17032'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17032'
 id: 17033 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '17033'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17033'
 id: 17034 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '17034'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17034'
 id: 17035 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17035'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17035'
 id: 17036 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '17036'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17036'
 id: 17037 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '17037'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17037'
 id: 17038 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17038'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17038'
 id: 17039 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '17039'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17039'
 id: 17040 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17040'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17040'
 id: 17041 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17041'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17041'
 id: 17042 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '17042'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17042'
 id: 17043 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17043'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17043'
 id: 17044 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17044'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17044'
 id: 17045 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17045'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17045'
 id: 17046 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '17046'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17046'
 id: 17047 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '17047'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17047'
 id: 17048 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '17048'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17048'
 id: 17049 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '17049'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17049'
 id: 17050 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '17050'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17050'
 id: 17051 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '17051'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17051'
 id: 17052 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17052'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17052'
 id: 17053 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '17053'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17053'
 id: 17054 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17054'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17054'
 id: 17055 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '17055'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17055'
 id: 17056 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '17056'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17056'
 id: 17057 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '17057'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17057'
 id: 17058 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '17058'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17058'
 id: 17059 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17059'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17059'
 id: 17060 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '17060'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17060'
 id: 17061 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '17061'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17061'
 id: 17062 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17062'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17062'
 id: 17063 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '17063'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17063'
 id: 17064 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17064'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17064'
 id: 17065 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '17065'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17065'
 id: 17066 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17066'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17066'
 id: 17067 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '17067'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17067'
 id: 17068 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17068'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17068'
 id: 17069 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '17069'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17069'
 id: 17070 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '17070'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17070'
 id: 17071 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '17071'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17071'
 id: 17072 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17072'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17072'
 id: 17073 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17073'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17073'
 id: 17074 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '17074'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17074'
 id: 17075 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17075'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17075'
 id: 17076 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17076'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17076'
 id: 17077 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17077'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17077'
 id: 17078 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17078'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17078'
 id: 17079 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17079'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17079'
 id: 17080 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17080'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17080'
 id: 17081 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '17081'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17081'

 id: 17082 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17082'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17082'
 id: 17083 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '17083'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17083'
 id: 17084 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '17084'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17084'
 id: 17085 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '17085'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17085'
 id: 17086 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17086'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17086'
 id: 17087 // word: 53
UPDATE job_vacancies SET domain_id =  '53' where raw_id = '17087'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17087'
 id: 17088 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '17088'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17088'
 id: 17089 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17089'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17089'
 id: 17090 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17090'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17090'
 id: 17091 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '17091'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17091'
 id: 17092 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17092'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17092'
 id: 17093 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '17093'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17093'
 id: 17094 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '17094'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17094'
 id: 17095 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17095'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17095'
 id: 17096 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '17096'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17096'
 id: 17097 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17097'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17097'
 id: 17098 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17098'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17098'
 id: 17099 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '17099'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17099'
 id: 17100 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '17100'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17100'
 id: 17101 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '17101'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17101'
 id: 17102 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17102'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17102'
 id: 17103 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '17103'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17103'
 id: 17104 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '17104'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17104'
 id: 17105 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17105'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17105'
 id: 17106 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17106'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17106'
 id: 17107 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '17107'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17107'
 id: 17108 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17108'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17108'
 id: 17109 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17109'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17109'
 id: 17110 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17110'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17110'
 id: 17111 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '17111'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17111'
 id: 17112 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17112'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17112'
 id: 17113 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17113'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17113'
 id: 17114 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17114'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17114'
 id: 17115 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17115'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17115'
 id: 17116 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17116'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17116'
 id: 17117 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '17117'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17117'
 id: 17118 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '17118'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17118'
 id: 17119 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '17119'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17119'
 id: 17120 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17120'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17120'
 id: 17121 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '17121'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17121'
 id: 17122 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17122'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17122'
 id: 17123 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '17123'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17123'
 id: 17124 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '17124'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17124'
 id: 17125 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17125'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17125'
 id: 17126 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '17126'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17126'
 id: 17127 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17127'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17127'
 id: 17128 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '17128'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17128'
 id: 17129 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '17129'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17129'
 id: 17130 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17130'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17130'
 id: 17131 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '17131'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17131'
 id: 17132 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '17132'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17132'
 id: 17133 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '17133'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17133'
 id: 17134 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17134'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17134'
 id: 17135 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17135'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17135'
 id: 17136 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '17136'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17136'
 id: 17137 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17137'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17137'
 id: 17138 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '17138'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17138'
 id: 17139 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '17139'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17139'
 id: 17140 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17140'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17140'
 id: 17141 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '17141'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17141'
 id: 17142 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '17142'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17142'
 id: 17143 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17143'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17143'
 id: 17144 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '17144'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17144'
 id: 17145 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17145'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17145'
 id: 17146 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17146'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17146'
 id: 17147 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17147'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17147'
 id: 17148 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17148'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17148'
 id: 17149 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17149'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17149'
 id: 17150 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '17150'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17150'
 id: 17151 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '17151'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17151'
 id: 17152 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '17152'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17152'
 id: 17153 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '17153'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17153'
 id: 17154 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17154'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17154'
 id: 17155 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '17155'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17155'
 id: 17156 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17156'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17156'
 id: 17157 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17157'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17157'
 id: 17158 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17158'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17158'
 id: 17159 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '17159'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17159'
 id: 17160 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17160'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17160'
 id: 17161 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '17161'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17161'
 id: 17162 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17162'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17162'
 id: 17163 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17163'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17163'
 id: 17164 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '17164'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17164'
 id: 17165 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '17165'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17165'
 id: 17166 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '17166'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17166'
 id: 17167 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '17167'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17167'
 id: 17168 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '17168'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17168'
 id: 17169 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17169'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17169'
 id: 17170 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17170'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17170'
 id: 17171 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17171'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17171'
 id: 17172 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '17172'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17172'
 id: 17173 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17173'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17173'
 id: 17174 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '17174'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17174'
 id: 17175 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '17175'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17175'
 id: 17176 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17176'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17176'
 id: 17177 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17177'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17177'
 id: 17178 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '17178'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17178'
 id: 17179 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '17179'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17179'
 id: 17180 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '17180'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17180'
 id: 17181 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17181'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17181'
 id: 17182 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17182'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17182'
 id: 17183 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '17183'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17183'
 id: 17184 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '17184'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17184'
 id: 17185 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '17185'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17185'

 id: 17186 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '17186'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17186'
 id: 17187 // word: 52
UPDATE job_vacancies SET domain_id =  '52' where raw_id = '17187'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17187'
 id: 17188 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '17188'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17188'
 id: 17189 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17189'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17189'
 id: 17190 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17190'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17190'
 id: 17191 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '17191'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17191'
 id: 17192 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17192'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17192'
 id: 17193 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '17193'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17193'
 id: 17194 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '17194'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17194'
 id: 17195 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '17195'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17195'
 id: 17196 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17196'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17196'
 id: 17197 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '17197'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17197'
 id: 17198 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17198'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17198'
 id: 17199 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '17199'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17199'
 id: 17200 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '17200'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17200'
 id: 17201 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17201'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17201'
 id: 17202 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '17202'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17202'
 id: 17203 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17203'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17203'
 id: 17204 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '17204'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17204'
 id: 17205 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '17205'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17205'
 id: 17206 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '17206'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17206'
 id: 17207 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '17207'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17207'
 id: 17208 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17208'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17208'
 id: 17209 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '17209'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17209'
 id: 17210 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '17210'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17210'
 id: 17211 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '17211'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17211'
 id: 17212 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '17212'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17212'
 id: 17213 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17213'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17213'
 id: 17214 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17214'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17214'
 id: 17215 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '17215'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17215'
 id: 17216 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17216'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17216'
 id: 17217 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '17217'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17217'
 id: 17218 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '17218'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17218'
 id: 17219 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17219'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17219'
 id: 17220 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17220'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17220'
 id: 17221 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '17221'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17221'
 id: 17222 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '17222'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17222'
 id: 17223 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17223'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17223'
 id: 17224 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17224'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17224'
 id: 17225 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17225'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17225'
 id: 17226 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '17226'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17226'
 id: 17227 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17227'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17227'
 id: 17228 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '17228'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17228'
 id: 17229 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '17229'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17229'
 id: 17230 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '17230'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17230'
 id: 17231 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17231'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17231'
 id: 17232 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17232'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17232'
 id: 17233 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17233'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17233'
 id: 17234 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '17234'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17234'
 id: 17235 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '17235'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17235'
 id: 17236 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '17236'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17236'
 id: 17237 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '17237'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17237'
 id: 17238 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17238'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17238'
 id: 17239 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '17239'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17239'
 id: 17240 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '17240'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17240'
 id: 17241 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17241'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17241'
 id: 17242 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '17242'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17242'
 id: 17243 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '17243'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17243'
 id: 17244 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '17244'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17244'
 id: 17245 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17245'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17245'
 id: 17246 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17246'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17246'
 id: 17247 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '17247'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17247'
 id: 17248 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17248'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17248'
 id: 17249 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '17249'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17249'
 id: 17250 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17250'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17250'
 id: 17251 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17251'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17251'
 id: 17252 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17252'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17252'
 id: 17253 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17253'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17253'
 id: 17254 // word: 52
UPDATE job_vacancies SET domain_id =  '52' where raw_id = '17254'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17254'
 id: 17255 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '17255'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17255'
 id: 17256 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '17256'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17256'
 id: 17257 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17257'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17257'
 id: 17258 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17258'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17258'
 id: 17259 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '17259'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17259'
 id: 17260 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17260'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17260'
 id: 17261 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17261'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17261'
 id: 17262 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17262'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17262'
 id: 17263 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '17263'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17263'
 id: 17264 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17264'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17264'
 id: 17265 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17265'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17265'
 id: 17266 // word: 52
UPDATE job_vacancies SET domain_id =  '52' where raw_id = '17266'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17266'
 id: 17267 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17267'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17267'
 id: 17268 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '17268'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17268'
 id: 17269 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17269'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17269'
 id: 17270 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '17270'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17270'
 id: 17271 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17271'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17271'
 id: 17272 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17272'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17272'
 id: 17273 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '17273'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17273'
 id: 17274 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '17274'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17274'
 id: 17275 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '17275'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17275'
 id: 17276 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17276'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17276'
 id: 17277 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '17277'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17277'
 id: 17278 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '17278'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17278'
 id: 17279 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17279'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17279'
 id: 17280 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17280'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17280'
 id: 17281 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '17281'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17281'
 id: 17282 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17282'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17282'
 id: 17283 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '17283'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17283'
 id: 17284 // word: 52
UPDATE job_vacancies SET domain_id =  '52' where raw_id = '17284'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17284'
 id: 17285 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17285'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17285'
 id: 17286 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '17286'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17286'
 id: 17287 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '17287'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17287'
 id: 17288 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17288'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17288'
 id: 17289 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17289'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17289'
 id: 17290 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '17290'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17290'
 id: 17291 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '17291'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17291'
 id: 17292 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '17292'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17292'
 id: 17293 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17293'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17293'
 id: 17294 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '17294'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17294'
 id: 17295 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '17295'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17295'
 id: 17296 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17296'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17296'
 id: 17297 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17297'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17297'
 id: 17298 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '17298'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17298'
 id: 17299 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17299'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17299'
 id: 17300 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17300'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17300'
 id: 17301 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17301'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17301'
 id: 17302 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17302'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17302'
 id: 17303 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17303'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17303'
 id: 17304 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17304'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17304'
 id: 17305 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17305'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17305'
 id: 17306 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '17306'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17306'
 id: 17307 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '17307'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17307'
 id: 17308 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '17308'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17308'
 id: 17309 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '17309'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17309'
 id: 17310 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17310'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17310'
 id: 17311 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '17311'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17311'
 id: 17312 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17312'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17312'
 id: 17313 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17313'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17313'
 id: 17314 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '17314'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17314'
 id: 17315 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '17315'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17315'
 id: 17316 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17316'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17316'
 id: 17317 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17317'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17317'
 id: 17318 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '17318'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17318'
 id: 17319 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '17319'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17319'
 id: 17320 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17320'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17320'
 id: 17321 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '17321'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17321'
 id: 17322 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17322'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17322'
 id: 17323 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '17323'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17323'
 id: 17324 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17324'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17324'
 id: 17325 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '17325'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17325'
 id: 17326 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17326'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17326'
 id: 17327 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17327'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17327'
 id: 17328 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17328'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17328'
 id: 17329 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17329'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17329'
 id: 17330 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '17330'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17330'
 id: 17331 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '17331'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17331'
 id: 17332 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17332'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17332'
 id: 17333 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '17333'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17333'
 id: 17334 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '17334'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17334'
 id: 17335 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '17335'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17335'
 id: 17336 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17336'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17336'
 id: 17337 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17337'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17337'
 id: 17338 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '17338'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17338'
 id: 17339 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '17339'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17339'
 id: 17340 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17340'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17340'
 id: 17341 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '17341'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17341'
 id: 17342 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17342'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17342'
 id: 17343 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '17343'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17343'
 id: 17344 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '17344'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17344'
 id: 17345 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17345'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17345'
 id: 17346 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17346'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17346'
 id: 17347 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '17347'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17347'
 id: 17348 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '17348'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17348'
 id: 17349 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '17349'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17349'
 id: 17350 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17350'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17350'
 id: 17351 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17351'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17351'
 id: 17352 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '17352'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17352'
 id: 17353 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17353'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17353'
 id: 17354 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '17354'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17354'
 id: 17355 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17355'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17355'
 id: 17356 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '17356'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17356'
 id: 17357 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17357'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17357'
 id: 17358 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17358'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17358'
 id: 17359 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17359'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17359'
 id: 17360 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17360'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17360'
 id: 17361 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '17361'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17361'
 id: 17362 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '17362'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17362'
 id: 17363 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '17363'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17363'
 id: 17364 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17364'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17364'
 id: 17365 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '17365'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17365'
 id: 17366 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17366'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17366'
 id: 17367 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '17367'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17367'
 id: 17368 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17368'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17368'
 id: 17369 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '17369'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17369'
 id: 17370 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '17370'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17370'
 id: 17371 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '17371'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17371'
 id: 17372 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '17372'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17372'
 id: 17373 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '17373'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17373'
 id: 17374 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17374'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17374'
 id: 17375 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '17375'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17375'
 id: 17376 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17376'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17376'
 id: 17377 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17377'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17377'
 id: 17378 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17378'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17378'
 id: 17379 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17379'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17379'
 id: 17380 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17380'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17380'
 id: 17381 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17381'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17381'
 id: 17382 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '17382'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17382'
 id: 17383 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '17383'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17383'
 id: 17384 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17384'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17384'
 id: 17385 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '17385'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17385'
 id: 17386 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17386'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17386'
 id: 17387 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17387'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17387'
 id: 17388 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '17388'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17388'
 id: 17389 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '17389'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17389'
 id: 17390 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17390'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17390'
 id: 17391 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17391'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17391'
 id: 17392 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17392'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17392'
 id: 17393 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '17393'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17393'
 id: 17394 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '17394'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17394'
 id: 17395 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17395'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17395'
 id: 17396 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17396'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17396'
 id: 17397 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17397'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17397'
 id: 17398 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17398'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17398'
 id: 17399 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17399'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17399'
 id: 17400 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17400'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17400'
 id: 17401 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '17401'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17401'
 id: 17402 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17402'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17402'
 id: 17403 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17403'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17403'
 id: 17404 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17404'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17404'
 id: 17405 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '17405'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17405'
 id: 17406 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '17406'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17406'
 id: 17407 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '17407'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17407'
 id: 17408 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17408'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17408'
 id: 17409 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '17409'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17409'
 id: 17410 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17410'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17410'
 id: 17411 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '17411'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17411'
 id: 17412 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17412'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17412'
 id: 17413 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17413'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17413'
 id: 17414 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17414'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17414'
 id: 17415 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17415'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17415'
 id: 17416 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17416'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17416'
 id: 17417 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17417'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17417'
 id: 17418 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17418'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17418'
 id: 17419 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '17419'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17419'
 id: 17420 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '17420'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17420'
 id: 17421 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '17421'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17421'
 id: 17422 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '17422'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17422'
 id: 17423 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17423'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17423'
 id: 17424 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '17424'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17424'
 id: 17425 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17425'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17425'
 id: 17426 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17426'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17426'
 id: 17427 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17427'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17427'
 id: 17428 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17428'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17428'
 id: 17429 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17429'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17429'
 id: 17430 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '17430'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17430'
 id: 17431 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17431'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17431'
 id: 17432 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '17432'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17432'
 id: 17433 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '17433'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17433'
 id: 17434 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '17434'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17434'
 id: 17435 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '17435'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17435'
 id: 17436 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17436'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17436'
 id: 17437 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '17437'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17437'
 id: 17438 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17438'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17438'
 id: 17439 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '17439'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17439'
 id: 17440 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17440'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17440'

 id: 17441 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17441'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17441'
 id: 17442 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17442'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17442'
 id: 17443 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '17443'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17443'
 id: 17444 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '17444'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17444'
 id: 17445 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '17445'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17445'
 id: 17446 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '17446'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17446'
 id: 17447 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17447'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17447'
 id: 17448 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '17448'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17448'
 id: 17449 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '17449'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17449'
 id: 17450 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17450'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17450'
 id: 17451 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17451'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17451'
 id: 17452 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '17452'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17452'
 id: 17453 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '17453'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17453'
 id: 17454 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17454'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17454'
 id: 17455 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17455'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17455'
 id: 17456 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '17456'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17456'
 id: 17457 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '17457'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17457'
 id: 17458 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17458'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17458'
 id: 17459 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17459'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17459'
 id: 17460 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17460'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17460'
 id: 17461 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '17461'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17461'
 id: 17462 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '17462'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17462'
 id: 17463 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '17463'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17463'
 id: 17464 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17464'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17464'
 id: 17465 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17465'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17465'
 id: 17466 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17466'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17466'
 id: 17467 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '17467'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17467'
 id: 17468 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '17468'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17468'
 id: 17469 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17469'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17469'
 id: 17470 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17470'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17470'
 id: 17471 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '17471'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17471'
 id: 17472 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17472'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17472'
 id: 17473 // word: 66
UPDATE job_vacancies SET domain_id =  '66' where raw_id = '17473'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17473'
 id: 17474 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17474'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17474'
 id: 17475 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17475'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17475'
 id: 17476 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17476'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17476'
 id: 17477 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17477'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17477'
 id: 17478 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17478'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17478'
 id: 17479 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17479'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17479'
 id: 17480 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17480'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17480'
 id: 17481 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '17481'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17481'
 id: 17482 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '17482'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17482'
 id: 17483 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '17483'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17483'
 id: 17484 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17484'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17484'
 id: 17485 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17485'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17485'
 id: 17486 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17486'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17486'
 id: 17487 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17487'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17487'
 id: 17488 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '17488'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17488'
 id: 17489 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '17489'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17489'
 id: 17490 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17490'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17490'

 id: 17491 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17491'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17491'
 id: 17492 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '17492'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17492'
 id: 17493 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '17493'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17493'
 id: 17494 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '17494'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17494'
 id: 17495 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17495'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17495'
 id: 17496 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '17496'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17496'
 id: 17497 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17497'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17497'
 id: 17498 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '17498'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17498'
 id: 17499 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '17499'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17499'
 id: 17500 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '17500'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17500'
 id: 17501 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17501'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17501'
 id: 17502 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '17502'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17502'
 id: 17503 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '17503'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17503'
 id: 17504 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '17504'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17504'
 id: 17505 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '17505'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17505'
 id: 17506 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17506'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17506'
 id: 17507 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17507'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17507'
 id: 17508 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '17508'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17508'
 id: 17509 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '17509'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17509'
 id: 17510 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17510'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17510'
 id: 17511 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17511'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17511'
 id: 17512 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '17512'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17512'
 id: 17513 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '17513'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17513'
 id: 17514 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '17514'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17514'
 id: 17515 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '17515'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17515'
 id: 17516 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17516'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17516'
 id: 17517 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17517'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17517'
 id: 17518 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17518'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17518'
 id: 17519 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17519'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17519'
 id: 17520 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17520'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17520'
 id: 17521 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17521'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17521'
 id: 17522 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '17522'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17522'
 id: 17523 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17523'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17523'
 id: 17524 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '17524'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17524'
 id: 17525 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17525'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17525'
 id: 17526 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '17526'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17526'
 id: 17527 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '17527'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17527'
 id: 17528 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17528'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17528'
 id: 17529 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17529'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17529'
 id: 17530 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17530'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17530'
 id: 17531 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17531'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17531'
 id: 17532 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17532'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17532'
 id: 17533 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '17533'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17533'
 id: 17534 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17534'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17534'
 id: 17535 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '17535'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17535'
 id: 17536 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17536'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17536'
 id: 17537 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '17537'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17537'
 id: 17538 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '17538'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17538'
 id: 17539 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '17539'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17539'
 id: 17540 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '17540'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17540'
 id: 17541 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '17541'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17541'
 id: 17542 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '17542'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17542'
 id: 17543 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17543'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17543'
 id: 17544 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '17544'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17544'
 id: 17545 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '17545'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17545'
 id: 17546 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17546'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17546'
 id: 17547 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17547'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17547'
 id: 17548 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '17548'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17548'
 id: 17549 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '17549'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17549'
 id: 17550 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '17550'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17550'
 id: 17551 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '17551'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17551'
 id: 17552 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17552'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17552'
 id: 17553 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '17553'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17553'
 id: 17554 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17554'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17554'
 id: 17555 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17555'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17555'
 id: 17556 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '17556'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17556'
 id: 17557 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17557'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17557'
 id: 17558 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17558'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17558'
 id: 17559 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '17559'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17559'
 id: 17560 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '17560'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17560'
 id: 17561 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17561'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17561'
 id: 17562 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17562'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17562'
 id: 17563 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '17563'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17563'
 id: 17564 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17564'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17564'
 id: 17565 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '17565'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17565'
 id: 17566 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17566'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17566'
 id: 17567 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17567'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17567'
 id: 17568 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17568'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17568'
 id: 17569 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '17569'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17569'
 id: 17570 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17570'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17570'
 id: 17571 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '17571'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17571'
 id: 17572 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17572'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17572'
 id: 17573 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17573'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17573'
 id: 17574 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17574'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17574'
 id: 17575 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '17575'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17575'
 id: 17576 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17576'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17576'
 id: 17577 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17577'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17577'
 id: 17578 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '17578'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17578'
 id: 17579 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17579'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17579'
 id: 17580 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17580'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17580'
 id: 17581 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '17581'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17581'
 id: 17582 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17582'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17582'
 id: 17583 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '17583'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17583'
 id: 17584 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17584'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17584'
 id: 17585 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '17585'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17585'
 id: 17586 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17586'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17586'
 id: 17587 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '17587'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17587'
 id: 17588 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17588'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17588'
 id: 17589 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17589'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17589'
 id: 17590 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17590'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17590'
 id: 17591 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17591'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17591'
 id: 17592 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17592'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17592'
 id: 17593 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '17593'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17593'
 id: 17594 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17594'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17594'
 id: 17595 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '17595'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17595'
 id: 17596 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17596'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17596'
 id: 17597 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17597'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17597'
 id: 17598 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '17598'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17598'
 id: 17599 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17599'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17599'
 id: 17600 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '17600'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17600'
 id: 17601 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '17601'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17601'
 id: 17602 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17602'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17602'
 id: 17603 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17603'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17603'
 id: 17604 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '17604'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17604'
 id: 17605 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '17605'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17605'
 id: 17606 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '17606'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17606'
 id: 17607 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17607'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17607'
 id: 17608 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '17608'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17608'
 id: 17609 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '17609'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17609'
 id: 17610 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '17610'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17610'
 id: 17611 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '17611'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17611'
 id: 17612 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17612'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17612'
 id: 17613 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '17613'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17613'
 id: 17614 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '17614'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17614'
 id: 17615 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17615'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17615'
 id: 17616 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17616'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17616'
 id: 17617 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17617'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17617'
 id: 17618 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '17618'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17618'
 id: 17619 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17619'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17619'
 id: 17620 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17620'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17620'
 id: 17621 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17621'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17621'
 id: 17622 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17622'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17622'
 id: 17623 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17623'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17623'
 id: 17624 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '17624'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17624'
 id: 17625 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '17625'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17625'
 id: 17626 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17626'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17626'
 id: 17627 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17627'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17627'
 id: 17628 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '17628'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17628'
 id: 17629 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '17629'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17629'
 id: 17630 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '17630'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17630'
 id: 17631 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '17631'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17631'
 id: 17632 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17632'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17632'
 id: 17633 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '17633'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17633'
 id: 17634 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17634'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17634'
 id: 17635 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17635'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17635'
 id: 17636 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17636'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17636'
 id: 17637 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '17637'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17637'
 id: 17638 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17638'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17638'
 id: 17639 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '17639'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17639'
 id: 17640 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17640'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17640'
 id: 17641 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '17641'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17641'
 id: 17642 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '17642'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17642'
 id: 17643 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17643'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17643'
 id: 17644 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '17644'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17644'
 id: 17645 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17645'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17645'
 id: 17646 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '17646'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17646'
 id: 17647 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '17647'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17647'
 id: 17648 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '17648'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17648'
 id: 17649 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17649'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17649'
 id: 17650 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17650'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17650'
 id: 17651 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17651'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17651'
 id: 17652 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '17652'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17652'
 id: 17653 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '17653'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17653'
 id: 17654 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '17654'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17654'
 id: 17655 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17655'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17655'
 id: 17656 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17656'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17656'
 id: 17657 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17657'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17657'
 id: 17658 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '17658'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17658'
 id: 17659 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '17659'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17659'
 id: 17660 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '17660'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17660'
 id: 17661 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17661'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17661'
 id: 17662 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17662'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17662'
 id: 17663 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17663'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17663'
 id: 17664 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17664'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17664'
 id: 17665 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '17665'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17665'
 id: 17666 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '17666'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17666'
 id: 17667 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17667'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17667'
 id: 17668 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17668'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17668'
 id: 17669 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17669'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17669'
 id: 17670 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '17670'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17670'
 id: 17671 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '17671'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17671'
 id: 17672 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17672'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17672'
 id: 17673 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17673'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17673'
 id: 17674 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17674'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17674'
 id: 17675 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '17675'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17675'
 id: 17676 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '17676'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17676'
 id: 17677 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '17677'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17677'
 id: 17678 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17678'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17678'
 id: 17679 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '17679'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17679'
 id: 17680 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17680'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17680'
 id: 17681 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17681'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17681'
 id: 17682 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17682'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17682'
 id: 17683 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17683'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17683'
 id: 17684 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '17684'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17684'
 id: 17685 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '17685'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17685'
 id: 17686 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '17686'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17686'
 id: 17687 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '17687'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17687'
 id: 17688 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17688'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17688'
 id: 17689 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17689'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17689'
 id: 17690 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17690'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17690'
 id: 17691 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '17691'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17691'
 id: 17692 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '17692'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17692'
 id: 17693 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17693'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17693'
 id: 17694 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17694'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17694'
 id: 17695 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '17695'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17695'
 id: 17696 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17696'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17696'
 id: 17697 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '17697'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17697'
 id: 17698 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '17698'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17698'
 id: 17699 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17699'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17699'
 id: 17700 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '17700'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17700'
 id: 17701 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17701'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17701'
 id: 17702 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17702'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17702'
 id: 17703 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17703'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17703'
 id: 17704 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17704'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17704'
 id: 17705 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '17705'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17705'
 id: 17706 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17706'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17706'
 id: 17707 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '17707'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17707'
 id: 17708 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '17708'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17708'
 id: 17709 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17709'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17709'
 id: 17710 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '17710'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17710'
 id: 17711 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17711'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17711'
 id: 17712 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '17712'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17712'
 id: 17713 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17713'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17713'
 id: 17714 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17714'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17714'
 id: 17715 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17715'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17715'
 id: 17716 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17716'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17716'
 id: 17717 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '17717'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17717'
 id: 17718 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17718'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17718'
 id: 17719 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '17719'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17719'
 id: 17720 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17720'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17720'
 id: 17721 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '17721'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17721'
 id: 17722 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17722'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17722'
 id: 17723 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '17723'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17723'
 id: 17724 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '17724'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17724'
 id: 17725 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17725'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17725'
 id: 17726 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17726'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17726'
 id: 17727 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '17727'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17727'
 id: 17728 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17728'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17728'
 id: 17729 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17729'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17729'
 id: 17730 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '17730'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17730'
 id: 17731 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17731'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17731'
 id: 17732 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17732'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17732'
 id: 17733 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17733'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17733'
 id: 17734 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17734'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17734'
 id: 17735 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '17735'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17735'
 id: 17736 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '17736'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17736'
 id: 17737 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17737'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17737'
 id: 17738 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17738'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17738'
 id: 17739 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17739'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17739'
 id: 17740 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17740'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17740'
 id: 17741 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '17741'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17741'
 id: 17742 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17742'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17742'
 id: 17743 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17743'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17743'
 id: 17744 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '17744'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17744'
 id: 17745 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '17745'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17745'
 id: 17746 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '17746'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17746'
 id: 17747 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17747'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17747'
 id: 17748 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17748'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17748'
 id: 17749 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '17749'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17749'
 id: 17750 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '17750'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17750'
 id: 17751 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17751'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17751'
 id: 17752 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '17752'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17752'
 id: 17753 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '17753'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17753'
 id: 17754 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '17754'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17754'
 id: 17755 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17755'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17755'
 id: 17756 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17756'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17756'
 id: 17757 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17757'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17757'
 id: 17758 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '17758'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17758'
 id: 17759 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17759'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17759'
 id: 17760 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '17760'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17760'
 id: 17761 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17761'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17761'
 id: 17762 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '17762'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17762'
 id: 17763 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '17763'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17763'
 id: 17764 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '17764'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17764'
 id: 17765 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17765'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17765'
 id: 17766 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '17766'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17766'
 id: 17767 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17767'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17767'
 id: 17768 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17768'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17768'
 id: 17769 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17769'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17769'
 id: 17770 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '17770'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17770'
 id: 17771 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17771'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17771'
 id: 17772 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17772'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17772'
 id: 17773 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '17773'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17773'
 id: 17774 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17774'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17774'
 id: 17775 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17775'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17775'
 id: 17776 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '17776'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17776'
 id: 17777 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17777'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17777'
 id: 17778 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '17778'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17778'
 id: 17779 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '17779'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17779'
 id: 17780 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '17780'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17780'
 id: 17781 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17781'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17781'
 id: 17782 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '17782'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17782'
 id: 17783 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17783'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17783'
 id: 17784 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '17784'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17784'
 id: 17785 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17785'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17785'
 id: 17786 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17786'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17786'
 id: 17787 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17787'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17787'
 id: 17788 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17788'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17788'
 id: 17789 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '17789'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17789'
 id: 17790 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '17790'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17790'
 id: 17791 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17791'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17791'
 id: 17792 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '17792'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17792'
 id: 17793 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17793'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17793'
 id: 17794 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '17794'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17794'
 id: 17795 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '17795'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17795'
 id: 17796 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '17796'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17796'
 id: 17797 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17797'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17797'
 id: 17798 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17798'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17798'
 id: 17799 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '17799'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17799'
 id: 17800 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17800'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17800'
 id: 17801 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17801'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17801'
 id: 17802 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17802'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17802'
 id: 17803 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17803'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17803'
 id: 17804 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17804'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17804'
 id: 17805 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17805'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17805'
 id: 17806 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17806'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17806'
 id: 17807 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17807'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17807'
 id: 17808 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '17808'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17808'
 id: 17809 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17809'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17809'
 id: 17810 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '17810'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17810'
 id: 17811 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '17811'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17811'
 id: 17812 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '17812'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17812'
 id: 17813 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '17813'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17813'
 id: 17814 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17814'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17814'
 id: 17815 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17815'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17815'
 id: 17816 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '17816'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17816'
 id: 17817 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17817'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17817'
 id: 17818 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17818'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17818'
 id: 17819 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '17819'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17819'
 id: 17820 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17820'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17820'
 id: 17821 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '17821'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17821'
 id: 17822 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17822'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17822'
 id: 17823 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17823'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17823'
 id: 17824 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '17824'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17824'
 id: 17825 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17825'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17825'
 id: 17826 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17826'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17826'
 id: 17827 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '17827'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17827'
 id: 17828 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17828'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17828'
 id: 17829 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17829'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17829'
 id: 17830 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17830'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17830'
 id: 17831 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '17831'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17831'
 id: 17832 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17832'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17832'
 id: 17833 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '17833'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17833'
 id: 17834 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17834'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17834'
 id: 17835 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17835'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17835'
 id: 17836 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '17836'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17836'
 id: 17837 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17837'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17837'
 id: 17838 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17838'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17838'
 id: 17839 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '17839'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17839'
 id: 17840 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17840'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17840'
 id: 17841 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '17841'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17841'
 id: 17842 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17842'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17842'
 id: 17843 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '17843'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17843'
 id: 17844 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17844'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17844'
 id: 17845 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17845'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17845'
 id: 17846 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '17846'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17846'
 id: 17847 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17847'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17847'
 id: 17848 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '17848'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17848'
 id: 17849 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17849'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17849'
 id: 17850 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '17850'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17850'
 id: 17851 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '17851'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17851'
 id: 17852 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '17852'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17852'
 id: 17853 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17853'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17853'
 id: 17854 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17854'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17854'
 id: 17855 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17855'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17855'
 id: 17856 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17856'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17856'
 id: 17857 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '17857'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17857'
 id: 17858 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17858'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17858'
 id: 17859 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17859'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17859'
 id: 17860 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '17860'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17860'
 id: 17861 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17861'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17861'
 id: 17862 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17862'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17862'
 id: 17863 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17863'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17863'
 id: 17864 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '17864'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17864'
 id: 17865 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '17865'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17865'
 id: 17866 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '17866'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17866'
 id: 17867 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '17867'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17867'
 id: 17868 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '17868'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17868'
 id: 17869 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17869'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17869'
 id: 17870 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '17870'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17870'
 id: 17871 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '17871'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17871'
 id: 17872 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '17872'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17872'
 id: 17873 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '17873'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17873'
 id: 17874 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17874'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17874'
 id: 17875 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '17875'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17875'
 id: 17876 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '17876'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17876'
 id: 17877 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17877'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17877'
 id: 17878 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17878'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17878'
 id: 17879 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17879'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17879'
 id: 17880 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17880'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17880'
 id: 17881 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17881'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17881'
 id: 17882 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '17882'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17882'
 id: 17883 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '17883'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17883'
 id: 17884 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17884'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17884'
 id: 17885 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '17885'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17885'
 id: 17886 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '17886'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17886'
 id: 17887 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '17887'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17887'
 id: 17888 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17888'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17888'
 id: 17889 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17889'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17889'
 id: 17890 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '17890'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17890'
 id: 17891 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17891'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17891'
 id: 17892 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17892'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17892'
 id: 17893 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17893'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17893'
 id: 17894 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17894'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17894'
 id: 17895 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '17895'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17895'
 id: 17896 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17896'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17896'
 id: 17897 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17897'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17897'
 id: 17898 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '17898'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17898'
 id: 17899 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '17899'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17899'
 id: 17900 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '17900'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17900'
 id: 17901 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '17901'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17901'
 id: 17902 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '17902'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17902'
 id: 17903 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17903'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17903'
 id: 17904 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '17904'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17904'
 id: 17905 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17905'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17905'
 id: 17906 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '17906'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17906'
 id: 17907 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17907'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17907'
 id: 17908 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '17908'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17908'
 id: 17909 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '17909'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17909'
 id: 17910 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '17910'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17910'
 id: 17911 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17911'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17911'
 id: 17912 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '17912'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17912'
 id: 17913 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17913'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17913'
 id: 17914 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '17914'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17914'
 id: 17915 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17915'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17915'
 id: 17916 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17916'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17916'
 id: 17917 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '17917'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17917'
 id: 17918 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '17918'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17918'
 id: 17919 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '17919'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17919'
 id: 17920 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '17920'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17920'
 id: 17921 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17921'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17921'
 id: 17922 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17922'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17922'
 id: 17923 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '17923'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17923'
 id: 17924 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '17924'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17924'
 id: 17925 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '17925'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17925'
 id: 17926 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17926'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17926'
 id: 17927 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17927'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17927'
 id: 17928 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17928'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17928'
 id: 17929 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '17929'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17929'
 id: 17930 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17930'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17930'
 id: 17931 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '17931'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17931'
 id: 17932 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17932'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17932'
 id: 17933 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17933'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17933'
 id: 17934 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17934'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17934'
 id: 17935 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17935'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17935'
 id: 17936 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '17936'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17936'
 id: 17937 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17937'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17937'
 id: 17938 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '17938'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17938'
 id: 17939 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17939'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17939'
 id: 17940 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17940'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17940'
 id: 17941 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '17941'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17941'
 id: 17942 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '17942'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17942'
 id: 17943 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17943'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17943'
 id: 17944 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17944'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17944'
 id: 17945 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17945'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17945'
 id: 17946 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '17946'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17946'
 id: 17947 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17947'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17947'
 id: 17948 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17948'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17948'
 id: 17949 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17949'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17949'
 id: 17950 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '17950'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17950'
 id: 17951 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '17951'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17951'
 id: 17952 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '17952'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17952'
 id: 17953 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17953'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17953'
 id: 17954 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17954'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17954'
 id: 17955 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17955'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17955'
 id: 17956 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17956'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17956'
 id: 17957 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17957'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17957'
 id: 17958 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17958'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17958'
 id: 17959 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17959'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17959'
 id: 17960 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '17960'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17960'
 id: 17961 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17961'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17961'
 id: 17962 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17962'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17962'
 id: 17963 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '17963'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17963'
 id: 17964 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17964'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17964'
 id: 17965 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17965'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17965'
 id: 17966 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17966'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17966'
 id: 17967 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '17967'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17967'
 id: 17968 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17968'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17968'
 id: 17969 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17969'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17969'
 id: 17970 // word: 66
UPDATE job_vacancies SET domain_id =  '66' where raw_id = '17970'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17970'
 id: 17971 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17971'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17971'
 id: 17972 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17972'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17972'
 id: 17973 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '17973'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17973'
 id: 17974 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '17974'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17974'
 id: 17975 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17975'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17975'
 id: 17976 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '17976'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17976'
 id: 17977 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17977'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17977'
 id: 17978 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '17978'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17978'
 id: 17979 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '17979'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17979'
 id: 17980 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '17980'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17980'
 id: 17981 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '17981'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17981'
 id: 17982 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17982'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17982'
 id: 17983 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '17983'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17983'
 id: 17984 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17984'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17984'
 id: 17985 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '17985'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17985'
 id: 17986 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '17986'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17986'
 id: 17987 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17987'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17987'
 id: 17988 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '17988'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17988'
 id: 17989 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '17989'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17989'
 id: 17990 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17990'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17990'
 id: 17991 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '17991'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17991'
 id: 17992 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17992'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17992'
 id: 17993 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '17993'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17993'
 id: 17994 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '17994'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17994'
 id: 17995 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '17995'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17995'
 id: 17996 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '17996'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17996'
 id: 17997 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '17997'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17997'
 id: 17998 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17998'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17998'
 id: 17999 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '17999'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '17999'
 id: 18000 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '18000'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18000'
 id: 18001 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18001'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18001'
 id: 18002 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18002'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18002'
 id: 18003 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '18003'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18003'
 id: 18004 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '18004'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18004'
 id: 18005 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18005'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18005'
 id: 18006 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '18006'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18006'
 id: 18007 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18007'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18007'
 id: 18008 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '18008'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18008'
 id: 18009 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18009'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18009'
 id: 18010 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18010'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18010'
 id: 18011 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18011'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18011'
 id: 18012 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18012'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18012'
 id: 18013 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18013'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18013'
 id: 18014 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18014'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18014'
 id: 18015 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '18015'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18015'
 id: 18016 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '18016'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18016'
 id: 18017 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18017'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18017'
 id: 18018 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '18018'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18018'
 id: 18019 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18019'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18019'
 id: 18020 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '18020'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18020'
 id: 18021 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18021'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18021'
 id: 18022 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18022'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18022'
 id: 18023 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '18023'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18023'
 id: 18024 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '18024'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18024'
 id: 18025 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '18025'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18025'
 id: 18026 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18026'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18026'
 id: 18027 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18027'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18027'
 id: 18028 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18028'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18028'
 id: 18029 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '18029'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18029'
 id: 18030 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '18030'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18030'
 id: 18031 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18031'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18031'
 id: 18032 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18032'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18032'
 id: 18033 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18033'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18033'
 id: 18034 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '18034'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18034'
 id: 18035 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '18035'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18035'
 id: 18036 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '18036'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18036'
 id: 18037 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '18037'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18037'
 id: 18038 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '18038'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18038'
 id: 18039 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18039'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18039'
 id: 18040 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '18040'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18040'
 id: 18041 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18041'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18041'
 id: 18042 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '18042'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18042'
 id: 18043 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '18043'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18043'
 id: 18044 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '18044'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18044'
 id: 18045 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '18045'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18045'
 id: 18046 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '18046'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18046'
 id: 18047 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18047'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18047'
 id: 18048 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18048'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18048'
 id: 18049 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18049'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18049'
 id: 18050 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '18050'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18050'
 id: 18051 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '18051'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18051'
 id: 18052 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '18052'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18052'
 id: 18053 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '18053'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18053'
 id: 18054 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18054'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18054'
 id: 18055 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18055'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18055'
 id: 18056 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18056'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18056'
 id: 18057 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18057'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18057'
 id: 18058 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18058'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18058'
 id: 18059 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '18059'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18059'
 id: 18060 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '18060'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18060'
 id: 18061 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18061'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18061'
 id: 18062 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18062'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18062'
 id: 18063 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '18063'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18063'
 id: 18064 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18064'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18064'
 id: 18065 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18065'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18065'
 id: 18066 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18066'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18066'
 id: 18067 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18067'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18067'
 id: 18068 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18068'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18068'
 id: 18069 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18069'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18069'
 id: 18070 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '18070'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18070'
 id: 18071 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18071'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18071'
 id: 18072 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18072'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18072'
 id: 18073 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18073'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18073'
 id: 18074 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18074'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18074'
 id: 18075 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '18075'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18075'
 id: 18076 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '18076'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18076'
 id: 18077 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '18077'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18077'
 id: 18078 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '18078'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18078'
 id: 18079 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18079'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18079'
 id: 18080 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18080'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18080'
 id: 18081 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18081'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18081'
 id: 18082 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18082'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18082'
 id: 18083 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '18083'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18083'
 id: 18084 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18084'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18084'
 id: 18085 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18085'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18085'
 id: 18086 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18086'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18086'
 id: 18087 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18087'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18087'
 id: 18088 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '18088'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18088'
 id: 18089 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '18089'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18089'
 id: 18090 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18090'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18090'
 id: 18091 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '18091'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18091'
 id: 18092 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18092'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18092'
 id: 18093 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18093'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18093'
 id: 18094 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '18094'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18094'
 id: 18095 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18095'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18095'
 id: 18096 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18096'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18096'
 id: 18097 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '18097'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18097'
 id: 18098 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18098'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18098'
 id: 18099 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18099'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18099'
 id: 18100 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '18100'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18100'
 id: 18101 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18101'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18101'
 id: 18102 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '18102'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18102'
 id: 18103 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18103'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18103'
 id: 18104 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18104'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18104'
 id: 18105 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '18105'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18105'
 id: 18106 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18106'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18106'
 id: 18107 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18107'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18107'
 id: 18108 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '18108'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18108'
 id: 18109 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18109'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18109'
 id: 18110 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18110'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18110'
 id: 18111 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '18111'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18111'
 id: 18112 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18112'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18112'
 id: 18113 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '18113'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18113'
 id: 18114 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '18114'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18114'
 id: 18115 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18115'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18115'
 id: 18116 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18116'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18116'
 id: 18117 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18117'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18117'
 id: 18118 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '18118'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18118'
 id: 18119 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18119'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18119'
 id: 18120 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '18120'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18120'
 id: 18121 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18121'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18121'
 id: 18122 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18122'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18122'
 id: 18123 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '18123'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18123'
 id: 18124 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '18124'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18124'
 id: 18125 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18125'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18125'
 id: 18126 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '18126'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18126'
 id: 18127 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '18127'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18127'
 id: 18128 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18128'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18128'
 id: 18129 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '18129'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18129'
 id: 18130 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18130'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18130'
 id: 18131 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '18131'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18131'
 id: 18132 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '18132'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18132'
 id: 18133 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '18133'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18133'
 id: 18134 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18134'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18134'
 id: 18135 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '18135'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18135'
 id: 18136 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '18136'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18136'
 id: 18137 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18137'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18137'
 id: 18138 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '18138'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18138'
 id: 18139 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '18139'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18139'
 id: 18140 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '18140'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18140'
 id: 18141 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '18141'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18141'
 id: 18142 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18142'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18142'
 id: 18143 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18143'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18143'
 id: 18144 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18144'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18144'
 id: 18145 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18145'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18145'
 id: 18146 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18146'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18146'
 id: 18147 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '18147'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18147'
 id: 18148 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18148'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18148'
 id: 18149 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '18149'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18149'
 id: 18150 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '18150'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18150'
 id: 18151 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18151'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18151'
 id: 18152 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18152'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18152'
 id: 18153 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '18153'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18153'
 id: 18154 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '18154'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18154'
 id: 18155 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '18155'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18155'
 id: 18156 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '18156'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18156'
 id: 18157 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18157'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18157'
 id: 18158 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '18158'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18158'
 id: 18159 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18159'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18159'
 id: 18160 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '18160'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18160'
 id: 18161 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '18161'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18161'
 id: 18162 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18162'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18162'
 id: 18163 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18163'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18163'
 id: 18164 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18164'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18164'
 id: 18165 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18165'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18165'
 id: 18166 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '18166'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18166'
 id: 18167 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18167'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18167'
 id: 18168 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18168'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18168'
 id: 18169 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18169'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18169'
 id: 18170 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '18170'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18170'
 id: 18171 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '18171'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18171'
 id: 18172 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18172'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18172'
 id: 18173 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '18173'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18173'
 id: 18174 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18174'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18174'
 id: 18175 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '18175'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18175'
 id: 18176 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '18176'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18176'
 id: 18177 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '18177'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18177'
 id: 18178 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18178'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18178'
 id: 18179 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18179'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18179'
 id: 18180 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '18180'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18180'
 id: 18181 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '18181'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18181'
 id: 18182 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18182'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18182'
 id: 18183 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18183'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18183'
 id: 18184 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '18184'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18184'
 id: 18185 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '18185'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18185'
 id: 18186 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '18186'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18186'
 id: 18187 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18187'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18187'
 id: 18188 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18188'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18188'
 id: 18189 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '18189'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18189'
 id: 18190 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '18190'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18190'
 id: 18191 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '18191'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18191'
 id: 18192 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18192'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18192'
 id: 18193 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18193'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18193'
 id: 18194 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18194'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18194'
 id: 18195 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18195'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18195'
 id: 18196 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '18196'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18196'
 id: 18197 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '18197'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18197'
 id: 18198 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18198'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18198'
 id: 18199 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '18199'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18199'
 id: 18200 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18200'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18200'
 id: 18201 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '18201'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18201'
 id: 18202 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18202'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18202'
 id: 18203 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18203'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18203'

 id: 18204 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '18204'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18204'
 id: 18205 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '18205'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18205'
 id: 18206 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '18206'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18206'
 id: 18207 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18207'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18207'
 id: 18208 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18208'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18208'
 id: 18209 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '18209'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18209'
 id: 18210 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '18210'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18210'
 id: 18211 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '18211'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18211'
 id: 18212 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '18212'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18212'
 id: 18213 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18213'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18213'
 id: 18214 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18214'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18214'
 id: 18215 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '18215'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18215'
 id: 18216 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18216'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18216'
 id: 18217 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18217'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18217'
 id: 18218 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18218'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18218'
 id: 18219 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18219'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18219'
 id: 18220 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '18220'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18220'
 id: 18221 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '18221'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18221'
 id: 18222 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18222'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18222'
 id: 18223 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '18223'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18223'
 id: 18224 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '18224'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18224'
 id: 18225 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18225'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18225'
 id: 18226 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18226'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18226'
 id: 18227 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '18227'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18227'
 id: 18228 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '18228'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18228'
 id: 18229 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '18229'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18229'
 id: 18230 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '18230'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18230'
 id: 18231 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18231'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18231'
 id: 18232 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '18232'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18232'
 id: 18233 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18233'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18233'
 id: 18234 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18234'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18234'
 id: 18235 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18235'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18235'
 id: 18236 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '18236'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18236'
 id: 18237 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '18237'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18237'
 id: 18238 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18238'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18238'
 id: 18239 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '18239'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18239'
 id: 18240 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18240'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18240'
 id: 18241 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '18241'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18241'
 id: 18242 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18242'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18242'
 id: 18243 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '18243'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18243'
 id: 18244 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18244'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18244'
 id: 18245 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '18245'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18245'
 id: 18246 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18246'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18246'
 id: 18247 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '18247'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18247'
 id: 18248 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18248'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18248'
 id: 18249 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '18249'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18249'
 id: 18250 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18250'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18250'
 id: 18251 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18251'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18251'
 id: 18252 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18252'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18252'
 id: 18253 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '18253'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18253'
 id: 18254 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '18254'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18254'
 id: 18255 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18255'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18255'
 id: 18256 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18256'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18256'
 id: 18257 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '18257'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18257'
 id: 18258 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18258'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18258'
 id: 18259 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18259'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18259'
 id: 18260 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '18260'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18260'
 id: 18261 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18261'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18261'
 id: 18262 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18262'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18262'
 id: 18263 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '18263'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18263'
 id: 18264 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '18264'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18264'
 id: 18265 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18265'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18265'
 id: 18266 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '18266'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18266'
 id: 18267 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18267'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18267'
 id: 18268 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '18268'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18268'
 id: 18269 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '18269'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18269'
 id: 18270 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '18270'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18270'
 id: 18271 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18271'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18271'
 id: 18272 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18272'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18272'
 id: 18273 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '18273'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18273'
 id: 18274 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '18274'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18274'
 id: 18275 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18275'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18275'
 id: 18276 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '18276'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18276'
 id: 18277 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '18277'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18277'
 id: 18278 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '18278'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18278'
 id: 18279 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '18279'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18279'
 id: 18280 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '18280'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18280'
 id: 18281 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '18281'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18281'
 id: 18282 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18282'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18282'
 id: 18283 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '18283'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18283'
 id: 18284 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '18284'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18284'
 id: 18285 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18285'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18285'
 id: 18286 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18286'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18286'
 id: 18287 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18287'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18287'
 id: 18288 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '18288'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18288'
 id: 18289 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '18289'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18289'
 id: 18290 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '18290'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18290'
 id: 18291 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '18291'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18291'
 id: 18292 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18292'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18292'
 id: 18293 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18293'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18293'
 id: 18294 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '18294'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18294'
 id: 18295 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18295'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18295'
 id: 18296 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18296'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18296'
 id: 18297 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18297'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18297'
 id: 18298 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '18298'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18298'
 id: 18299 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '18299'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18299'
 id: 18300 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18300'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18300'
 id: 18301 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18301'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18301'
 id: 18302 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '18302'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18302'
 id: 18303 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '18303'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18303'
 id: 18304 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18304'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18304'
 id: 18305 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18305'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18305'
 id: 18306 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '18306'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18306'
 id: 18307 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '18307'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18307'
 id: 18308 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18308'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18308'
 id: 18309 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '18309'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18309'
 id: 18310 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '18310'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18310'
 id: 18311 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18311'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18311'
 id: 18312 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18312'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18312'
 id: 18313 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18313'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18313'
 id: 18314 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18314'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18314'
 id: 18315 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18315'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18315'
 id: 18316 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '18316'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18316'
 id: 18317 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18317'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18317'
 id: 18318 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '18318'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18318'
 id: 18319 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18319'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18319'
 id: 18320 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '18320'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18320'
 id: 18321 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '18321'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18321'
 id: 18322 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18322'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18322'
 id: 18323 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18323'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18323'
 id: 18324 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '18324'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18324'
 id: 18325 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '18325'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18325'
 id: 18326 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '18326'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18326'
 id: 18327 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '18327'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18327'
 id: 18328 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '18328'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18328'
 id: 18329 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '18329'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18329'
 id: 18330 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18330'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18330'
 id: 18331 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18331'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18331'
 id: 18332 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '18332'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18332'
 id: 18333 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '18333'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18333'
 id: 18334 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '18334'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18334'
 id: 18335 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18335'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18335'
 id: 18336 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18336'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18336'
 id: 18337 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '18337'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18337'
 id: 18338 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18338'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18338'
 id: 18339 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18339'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18339'
 id: 18340 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '18340'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18340'
 id: 18341 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18341'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18341'
 id: 18342 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18342'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18342'
 id: 18343 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18343'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18343'
 id: 18344 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '18344'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18344'
 id: 18345 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18345'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18345'
 id: 18346 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18346'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18346'
 id: 18347 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '18347'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18347'
 id: 18348 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18348'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18348'
 id: 18349 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '18349'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18349'
 id: 18350 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '18350'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18350'
 id: 18351 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '18351'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18351'
 id: 18352 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '18352'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18352'
 id: 18353 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '18353'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18353'
 id: 18354 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '18354'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18354'
 id: 18355 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18355'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18355'
 id: 18356 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18356'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18356'
 id: 18357 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18357'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18357'
 id: 18358 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '18358'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18358'
 id: 18359 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18359'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18359'
 id: 18360 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '18360'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18360'
 id: 18361 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18361'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18361'
 id: 18362 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18362'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18362'
 id: 18363 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18363'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18363'
 id: 18364 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '18364'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18364'
 id: 18365 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18365'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18365'
 id: 18366 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '18366'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18366'
 id: 18367 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18367'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18367'
 id: 18368 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18368'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18368'
 id: 18369 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '18369'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18369'
 id: 18370 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18370'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18370'
 id: 18371 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '18371'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18371'
 id: 18372 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18372'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18372'
 id: 18373 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '18373'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18373'
 id: 18374 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18374'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18374'
 id: 18375 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18375'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18375'
 id: 18376 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18376'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18376'
 id: 18377 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18377'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18377'
 id: 18378 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18378'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18378'
 id: 18379 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18379'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18379'
 id: 18380 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '18380'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18380'
 id: 18381 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18381'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18381'
 id: 18382 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18382'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18382'
 id: 18383 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '18383'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18383'
 id: 18384 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '18384'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18384'
 id: 18385 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '18385'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18385'
 id: 18386 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '18386'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18386'
 id: 18387 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18387'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18387'
 id: 18388 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '18388'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18388'
 id: 18389 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '18389'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18389'
 id: 18390 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '18390'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18390'
 id: 18391 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18391'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18391'
 id: 18392 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18392'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18392'
 id: 18393 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18393'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18393'
 id: 18394 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '18394'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18394'
 id: 18395 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '18395'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18395'
 id: 18396 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18396'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18396'
 id: 18397 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18397'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18397'
 id: 18398 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18398'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18398'
 id: 18399 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '18399'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18399'
 id: 18400 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '18400'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18400'
 id: 18401 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18401'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18401'
 id: 18402 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18402'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18402'
 id: 18403 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '18403'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18403'
 id: 18404 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18404'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18404'
 id: 18405 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18405'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18405'
 id: 18406 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '18406'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18406'

 id: 18407 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '18407'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18407'
 id: 18408 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '18408'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18408'
 id: 18409 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18409'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18409'
 id: 18410 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '18410'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18410'
 id: 18411 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '18411'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18411'
 id: 18412 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '18412'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18412'
 id: 18413 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '18413'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18413'
 id: 18414 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '18414'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18414'
 id: 18415 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18415'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18415'
 id: 18416 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '18416'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18416'
 id: 18417 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '18417'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18417'
 id: 18418 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '18418'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18418'
 id: 18419 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18419'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18419'
 id: 18420 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18420'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18420'
 id: 18421 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '18421'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18421'
 id: 18422 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '18422'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18422'
 id: 18423 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18423'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18423'
 id: 18424 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18424'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18424'
 id: 18425 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18425'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18425'
 id: 18426 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18426'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18426'
 id: 18427 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '18427'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18427'
 id: 18428 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18428'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18428'
 id: 18429 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '18429'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18429'
 id: 18430 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '18430'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18430'
 id: 18431 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18431'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18431'
 id: 18432 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '18432'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18432'
 id: 18433 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18433'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18433'
 id: 18434 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '18434'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18434'
 id: 18435 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '18435'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18435'
 id: 18436 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18436'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18436'
 id: 18437 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '18437'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18437'
 id: 18438 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18438'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18438'
 id: 18439 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18439'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18439'
 id: 18440 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18440'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18440'
 id: 18441 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '18441'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18441'
 id: 18442 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '18442'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18442'
 id: 18443 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18443'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18443'
 id: 18444 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18444'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18444'
 id: 18445 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '18445'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18445'
 id: 18446 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18446'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18446'
 id: 18447 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18447'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18447'
 id: 18448 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18448'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18448'
 id: 18449 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '18449'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18449'
 id: 18450 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18450'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18450'
 id: 18451 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '18451'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18451'
 id: 18452 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18452'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18452'
 id: 18453 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '18453'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18453'
 id: 18454 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18454'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18454'
 id: 18455 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '18455'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18455'
 id: 18456 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18456'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18456'
 id: 18457 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '18457'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18457'
 id: 18458 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18458'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18458'
 id: 18459 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '18459'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18459'
 id: 18460 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18460'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18460'
 id: 18461 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '18461'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18461'
 id: 18462 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18462'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18462'
 id: 18463 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18463'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18463'
 id: 18464 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18464'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18464'
 id: 18465 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18465'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18465'
 id: 18466 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18466'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18466'
 id: 18467 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18467'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18467'
 id: 18468 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18468'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18468'
 id: 18469 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '18469'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18469'
 id: 18470 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18470'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18470'
 id: 18471 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '18471'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18471'
 id: 18472 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18472'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18472'
 id: 18473 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '18473'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18473'
 id: 18474 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18474'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18474'
 id: 18475 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18475'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18475'
 id: 18476 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '18476'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18476'
 id: 18477 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18477'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18477'
 id: 18478 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18478'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18478'
 id: 18479 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '18479'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18479'
 id: 18480 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '18480'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18480'
 id: 18481 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18481'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18481'
 id: 18482 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '18482'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18482'
 id: 18483 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18483'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18483'
 id: 18484 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18484'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18484'
 id: 18485 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18485'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18485'
 id: 18486 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '18486'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18486'
 id: 18487 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '18487'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18487'
 id: 18488 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '18488'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18488'
 id: 18489 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18489'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18489'
 id: 18490 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '18490'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18490'
 id: 18491 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '18491'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18491'
 id: 18492 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18492'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18492'
 id: 18493 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18493'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18493'
 id: 18494 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18494'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18494'
 id: 18495 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18495'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18495'
 id: 18496 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '18496'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18496'
 id: 18497 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18497'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18497'
 id: 18498 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18498'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18498'
 id: 18499 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18499'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18499'
 id: 18500 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '18500'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18500'
 id: 18501 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '18501'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18501'
 id: 18502 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18502'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18502'
 id: 18503 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '18503'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18503'
 id: 18504 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '18504'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18504'
 id: 18505 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18505'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18505'
 id: 18506 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18506'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18506'
 id: 18507 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '18507'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18507'
 id: 18508 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '18508'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18508'
 id: 18509 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18509'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18509'
 id: 18510 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '18510'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18510'
 id: 18511 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18511'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18511'
 id: 18512 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18512'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18512'
 id: 18513 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '18513'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18513'
 id: 18514 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '18514'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18514'
 id: 18515 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18515'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18515'
 id: 18516 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '18516'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18516'
 id: 18517 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18517'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18517'
 id: 18518 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '18518'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18518'
 id: 18519 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '18519'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18519'
 id: 18520 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18520'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18520'
 id: 18521 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18521'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18521'
 id: 18522 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18522'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18522'
 id: 18523 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '18523'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18523'
 id: 18524 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '18524'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18524'
 id: 18525 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18525'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18525'
 id: 18526 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '18526'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18526'
 id: 18527 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '18527'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18527'
 id: 18528 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18528'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18528'
 id: 18529 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18529'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18529'
 id: 18530 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '18530'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18530'
 id: 18531 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '18531'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18531'
 id: 18532 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18532'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18532'
 id: 18533 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '18533'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18533'
 id: 18534 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18534'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18534'
 id: 18535 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '18535'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18535'
 id: 18536 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '18536'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18536'
 id: 18537 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '18537'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18537'
 id: 18538 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18538'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18538'
 id: 18539 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18539'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18539'
 id: 18540 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '18540'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18540'
 id: 18541 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '18541'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18541'
 id: 18542 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '18542'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18542'
 id: 18543 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '18543'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18543'
 id: 18544 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18544'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18544'
 id: 18545 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '18545'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18545'
 id: 18546 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18546'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18546'
 id: 18547 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18547'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18547'
 id: 18548 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '18548'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18548'
 id: 18549 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '18549'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18549'
 id: 18550 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18550'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18550'
 id: 18551 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '18551'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18551'
 id: 18552 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18552'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18552'
 id: 18553 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '18553'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18553'
 id: 18554 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18554'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18554'
 id: 18555 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18555'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18555'
 id: 18556 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '18556'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18556'
 id: 18557 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '18557'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18557'
 id: 18558 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '18558'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18558'
 id: 18559 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '18559'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18559'
 id: 18560 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18560'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18560'
 id: 18561 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18561'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18561'
 id: 18562 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18562'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18562'
 id: 18563 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '18563'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18563'
 id: 18564 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '18564'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18564'
 id: 18565 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18565'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18565'
 id: 18566 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '18566'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18566'
 id: 18567 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18567'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18567'
 id: 18568 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18568'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18568'
 id: 18569 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '18569'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18569'
 id: 18570 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '18570'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18570'
 id: 18571 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18571'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18571'
 id: 18572 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18572'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18572'
 id: 18573 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '18573'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18573'
 id: 18574 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '18574'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18574'
 id: 18575 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18575'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18575'
 id: 18576 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18576'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18576'
 id: 18577 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18577'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18577'
 id: 18578 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '18578'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18578'
 id: 18579 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18579'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18579'
 id: 18580 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18580'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18580'
 id: 18581 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18581'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18581'
 id: 18582 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '18582'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18582'
 id: 18583 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '18583'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18583'
 id: 18584 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18584'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18584'
 id: 18585 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18585'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18585'
 id: 18586 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18586'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18586'
 id: 18587 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '18587'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18587'
 id: 18588 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18588'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18588'
 id: 18589 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '18589'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18589'
 id: 18590 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18590'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18590'
 id: 18591 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '18591'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18591'
 id: 18592 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '18592'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18592'
 id: 18593 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18593'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18593'
 id: 18594 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '18594'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18594'
 id: 18595 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '18595'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18595'
 id: 18596 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18596'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18596'
 id: 18597 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18597'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18597'
 id: 18598 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '18598'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18598'
 id: 18599 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '18599'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18599'
 id: 18600 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '18600'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18600'
 id: 18601 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18601'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18601'
 id: 18602 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18602'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18602'
 id: 18603 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '18603'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18603'
 id: 18604 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18604'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18604'
 id: 18605 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18605'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18605'
 id: 18606 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18606'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18606'
 id: 18607 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18607'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18607'
 id: 18608 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '18608'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18608'
 id: 18609 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '18609'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18609'
 id: 18610 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '18610'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18610'
 id: 18611 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18611'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18611'
 id: 18612 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '18612'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18612'
 id: 18613 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '18613'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18613'
 id: 18614 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '18614'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18614'
 id: 18615 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '18615'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18615'
 id: 18616 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '18616'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18616'
 id: 18617 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18617'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18617'
 id: 18618 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18618'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18618'
 id: 18619 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '18619'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18619'
 id: 18620 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '18620'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18620'
 id: 18621 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18621'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18621'
 id: 18622 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '18622'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18622'
 id: 18623 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18623'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18623'
 id: 18624 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '18624'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18624'
 id: 18625 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '18625'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18625'
 id: 18626 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18626'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18626'
 id: 18627 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '18627'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18627'
 id: 18628 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18628'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18628'
 id: 18629 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18629'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18629'
 id: 18630 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18630'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18630'
 id: 18631 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '18631'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18631'
 id: 18632 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18632'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18632'
 id: 18633 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '18633'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18633'
 id: 18634 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '18634'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18634'
 id: 18635 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '18635'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18635'
 id: 18636 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18636'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18636'
 id: 18637 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '18637'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18637'
 id: 18638 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18638'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18638'
 id: 18639 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18639'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18639'
 id: 18640 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18640'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18640'
 id: 18641 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '18641'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18641'
 id: 18642 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '18642'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18642'
 id: 18643 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '18643'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18643'
 id: 18644 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '18644'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18644'
 id: 18645 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18645'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18645'
 id: 18646 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18646'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18646'
 id: 18647 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '18647'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18647'
 id: 18648 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18648'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18648'
 id: 18649 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '18649'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18649'
 id: 18650 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18650'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18650'
 id: 18651 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18651'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18651'
 id: 18652 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '18652'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18652'
 id: 18653 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18653'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18653'
 id: 18654 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '18654'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18654'
 id: 18655 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '18655'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18655'
 id: 18656 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '18656'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18656'
 id: 18657 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '18657'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18657'
 id: 18658 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18658'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18658'
 id: 18659 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18659'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18659'
 id: 18660 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '18660'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18660'
 id: 18661 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18661'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18661'
 id: 18662 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '18662'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18662'
 id: 18663 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '18663'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18663'
 id: 18664 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '18664'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18664'
 id: 18665 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18665'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18665'
 id: 18666 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '18666'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18666'
 id: 18667 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18667'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18667'
 id: 18668 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '18668'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18668'
 id: 18669 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18669'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18669'
 id: 18670 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '18670'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18670'
 id: 18671 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18671'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18671'
 id: 18672 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '18672'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18672'
 id: 18673 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '18673'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18673'
 id: 18674 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18674'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18674'
 id: 18675 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18675'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18675'
 id: 18676 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '18676'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18676'
 id: 18677 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18677'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18677'
 id: 18678 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18678'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18678'
 id: 18679 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '18679'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18679'
 id: 18680 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '18680'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18680'
 id: 18681 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '18681'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18681'
 id: 18682 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '18682'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18682'
 id: 18683 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '18683'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18683'
 id: 18684 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '18684'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18684'
 id: 18685 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '18685'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18685'
 id: 18686 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18686'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18686'
 id: 18687 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '18687'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18687'
 id: 18688 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '18688'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18688'
 id: 18689 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18689'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18689'
 id: 18690 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18690'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18690'
 id: 18691 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '18691'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18691'
 id: 18692 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18692'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18692'
 id: 18693 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18693'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18693'
 id: 18694 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18694'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18694'
 id: 18695 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18695'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18695'
 id: 18696 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '18696'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18696'
 id: 18697 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '18697'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18697'
 id: 18698 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18698'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18698'
 id: 18699 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '18699'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18699'
 id: 18700 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '18700'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18700'
 id: 18701 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '18701'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18701'
 id: 18702 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '18702'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18702'
 id: 18703 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '18703'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18703'
 id: 18704 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18704'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18704'
 id: 18705 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '18705'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18705'
 id: 18706 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '18706'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18706'
 id: 18707 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '18707'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18707'
 id: 18708 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '18708'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18708'
 id: 18709 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18709'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18709'
 id: 18710 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18710'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18710'
 id: 18711 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '18711'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18711'
 id: 18712 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '18712'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18712'
 id: 18713 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18713'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18713'
 id: 18714 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18714'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18714'
 id: 18715 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '18715'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18715'
 id: 18716 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '18716'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18716'
 id: 18717 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18717'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18717'
 id: 18718 // word: 66
UPDATE job_vacancies SET domain_id =  '66' where raw_id = '18718'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18718'
 id: 18719 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18719'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18719'
 id: 18720 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '18720'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18720'
 id: 18721 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18721'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18721'
 id: 18722 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '18722'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18722'
 id: 18723 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18723'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18723'
 id: 18724 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18724'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18724'
 id: 18725 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18725'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18725'
 id: 18726 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '18726'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18726'
 id: 18727 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '18727'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18727'
 id: 18728 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '18728'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18728'
 id: 18729 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '18729'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18729'
 id: 18730 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '18730'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18730'
 id: 18731 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '18731'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18731'
 id: 18732 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18732'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18732'
 id: 18733 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '18733'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18733'
 id: 18734 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '18734'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18734'
 id: 18735 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '18735'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18735'
 id: 18736 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '18736'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18736'
 id: 18737 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '18737'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18737'
 id: 18738 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18738'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18738'
 id: 18739 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '18739'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18739'
 id: 18740 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18740'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18740'
 id: 18741 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18741'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18741'
 id: 18742 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '18742'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18742'
 id: 18743 // word: 52
UPDATE job_vacancies SET domain_id =  '52' where raw_id = '18743'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18743'
 id: 18744 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18744'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18744'
 id: 18745 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18745'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18745'
 id: 18746 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '18746'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18746'
 id: 18747 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18747'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18747'
 id: 18748 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18748'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18748'
 id: 18749 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '18749'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18749'
 id: 18750 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18750'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18750'
 id: 18751 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '18751'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18751'
 id: 18752 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18752'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18752'
 id: 18753 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '18753'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18753'
 id: 18754 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '18754'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18754'
 id: 18755 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18755'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18755'
 id: 18756 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '18756'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18756'
 id: 18757 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18757'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18757'
 id: 18758 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '18758'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18758'
 id: 18759 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18759'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18759'
 id: 18760 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '18760'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18760'
 id: 18761 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '18761'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18761'
 id: 18762 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18762'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18762'
 id: 18763 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '18763'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18763'
 id: 18764 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '18764'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18764'
 id: 18765 // word: 55
UPDATE job_vacancies SET domain_id =  '55' where raw_id = '18765'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18765'
 id: 18766 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '18766'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18766'
 id: 18767 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18767'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18767'
 id: 18768 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18768'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18768'
 id: 18769 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '18769'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18769'
 id: 18770 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18770'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18770'
 id: 18771 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '18771'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18771'
 id: 18772 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '18772'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18772'
 id: 18773 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18773'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18773'
 id: 18774 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18774'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18774'
 id: 18775 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18775'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18775'
 id: 18776 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '18776'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18776'
 id: 18777 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '18777'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18777'
 id: 18778 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '18778'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18778'
 id: 18779 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '18779'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18779'
 id: 18780 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18780'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18780'
 id: 18781 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '18781'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18781'
 id: 18782 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '18782'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18782'
 id: 18783 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18783'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18783'
 id: 18784 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '18784'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18784'
 id: 18785 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18785'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18785'
 id: 18786 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18786'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18786'
 id: 18787 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '18787'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18787'
 id: 18788 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '18788'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18788'
 id: 18789 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '18789'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18789'
 id: 18790 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '18790'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18790'
 id: 18791 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18791'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18791'
 id: 18792 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '18792'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18792'
 id: 18793 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '18793'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18793'
 id: 18794 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18794'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18794'
 id: 18795 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '18795'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18795'
 id: 18796 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '18796'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18796'
 id: 18797 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18797'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18797'
 id: 18798 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '18798'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18798'
 id: 18799 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18799'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18799'
 id: 18800 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '18800'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18800'
 id: 18801 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18801'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18801'
 id: 18802 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18802'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18802'
 id: 18803 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '18803'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18803'
 id: 18804 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '18804'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18804'
 id: 18805 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '18805'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18805'
 id: 18806 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18806'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18806'
 id: 18807 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '18807'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18807'
 id: 18808 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18808'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18808'
 id: 18809 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '18809'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18809'
 id: 18810 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18810'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18810'
 id: 18811 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18811'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18811'
 id: 18812 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '18812'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18812'
 id: 18813 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '18813'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18813'
 id: 18814 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '18814'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18814'
 id: 18815 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18815'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18815'
 id: 18816 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18816'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18816'
 id: 18817 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '18817'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18817'
 id: 18818 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18818'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18818'
 id: 18819 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18819'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18819'
 id: 18820 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18820'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18820'
 id: 18821 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18821'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18821'
 id: 18822 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '18822'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18822'
 id: 18823 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18823'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18823'
 id: 18824 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18824'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18824'
 id: 18825 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18825'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18825'
 id: 18826 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '18826'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18826'
 id: 18827 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '18827'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18827'
 id: 18828 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '18828'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18828'
 id: 18829 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '18829'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18829'
 id: 18830 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18830'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18830'
 id: 18831 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '18831'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18831'
 id: 18832 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18832'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18832'
 id: 18833 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '18833'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18833'
 id: 18834 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18834'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18834'
 id: 18835 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18835'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18835'
 id: 18836 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '18836'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18836'
 id: 18837 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18837'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18837'
 id: 18838 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18838'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18838'
 id: 18839 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '18839'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18839'
 id: 18840 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '18840'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18840'
 id: 18841 // word: 57
UPDATE job_vacancies SET domain_id =  '57' where raw_id = '18841'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18841'
 id: 18842 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '18842'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18842'
 id: 18843 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '18843'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18843'
 id: 18844 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '18844'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18844'
 id: 18845 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18845'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18845'
 id: 18846 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '18846'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18846'
 id: 18847 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18847'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18847'
 id: 18848 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '18848'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18848'
 id: 18849 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '18849'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18849'
 id: 18850 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18850'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18850'
 id: 18851 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '18851'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18851'
 id: 18852 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18852'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18852'
 id: 18853 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '18853'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18853'
 id: 18854 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '18854'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18854'
 id: 18855 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18855'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18855'
 id: 18856 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18856'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18856'
 id: 18857 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '18857'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18857'
 id: 18858 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18858'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18858'
 id: 18859 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18859'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18859'
 id: 18860 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18860'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18860'
 id: 18861 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '18861'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18861'
 id: 18862 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '18862'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18862'
 id: 18863 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '18863'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18863'
 id: 18864 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '18864'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18864'
 id: 18865 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18865'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18865'
 id: 18866 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18866'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18866'
 id: 18867 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18867'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18867'
 id: 18868 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18868'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18868'
 id: 18869 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '18869'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18869'
 id: 18870 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18870'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18870'
 id: 18871 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '18871'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18871'
 id: 18872 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '18872'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18872'
 id: 18873 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18873'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18873'
 id: 18874 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18874'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18874'
 id: 18875 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '18875'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18875'
 id: 18876 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18876'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18876'
 id: 18877 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '18877'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18877'
 id: 18878 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18878'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18878'
 id: 18879 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18879'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18879'
 id: 18880 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '18880'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18880'
 id: 18881 // word: 66
UPDATE job_vacancies SET domain_id =  '66' where raw_id = '18881'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18881'
 id: 18882 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '18882'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18882'
 id: 18883 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18883'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18883'
 id: 18884 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '18884'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18884'
 id: 18885 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '18885'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18885'
 id: 18886 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '18886'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18886'
 id: 18887 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18887'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18887'
 id: 18888 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18888'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18888'
 id: 18889 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18889'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18889'
 id: 18890 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18890'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18890'
 id: 18891 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18891'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18891'
 id: 18892 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18892'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18892'
 id: 18893 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18893'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18893'
 id: 18894 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '18894'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18894'
 id: 18895 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18895'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18895'
 id: 18896 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18896'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18896'
 id: 18897 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '18897'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18897'
 id: 18898 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '18898'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18898'
 id: 18899 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '18899'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18899'
 id: 18900 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '18900'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18900'
 id: 18901 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '18901'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18901'
 id: 18902 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '18902'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18902'
 id: 18903 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '18903'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18903'
 id: 18904 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '18904'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18904'
 id: 18905 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18905'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18905'
 id: 18906 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18906'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18906'
 id: 18907 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '18907'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18907'
 id: 18908 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18908'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18908'
 id: 18909 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '18909'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18909'
 id: 18910 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18910'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18910'
 id: 18911 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18911'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18911'
 id: 18912 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '18912'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18912'
 id: 18913 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '18913'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18913'
 id: 18914 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '18914'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18914'
 id: 18915 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18915'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18915'
 id: 18916 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18916'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18916'
 id: 18917 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18917'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18917'
 id: 18918 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '18918'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18918'
 id: 18919 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '18919'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18919'
 id: 18920 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18920'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18920'
 id: 18921 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '18921'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18921'
 id: 18922 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '18922'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18922'
 id: 18923 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '18923'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18923'
 id: 18924 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '18924'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18924'
 id: 18925 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '18925'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18925'
 id: 18926 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '18926'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18926'
 id: 18927 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18927'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18927'
 id: 18928 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18928'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18928'
 id: 18929 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18929'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18929'
 id: 18930 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '18930'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18930'
 id: 18931 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18931'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18931'
 id: 18932 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18932'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18932'
 id: 18933 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18933'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18933'
 id: 18934 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '18934'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18934'
 id: 18935 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '18935'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18935'
 id: 18936 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18936'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18936'
 id: 18937 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18937'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18937'
 id: 18938 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18938'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18938'
 id: 18939 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '18939'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18939'
 id: 18940 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '18940'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18940'
 id: 18941 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '18941'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18941'
 id: 18942 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '18942'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18942'
 id: 18943 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '18943'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18943'
 id: 18944 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18944'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18944'
 id: 18945 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '18945'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18945'
 id: 18946 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18946'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18946'
 id: 18947 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '18947'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18947'
 id: 18948 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '18948'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18948'
 id: 18949 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18949'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18949'
 id: 18950 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '18950'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18950'
 id: 18951 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '18951'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18951'
 id: 18952 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '18952'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18952'
 id: 18953 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18953'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18953'
 id: 18954 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '18954'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18954'
 id: 18955 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18955'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18955'
 id: 18956 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '18956'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18956'
 id: 18957 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '18957'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18957'
 id: 18958 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18958'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18958'
 id: 18959 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18959'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18959'
 id: 18960 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '18960'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18960'
 id: 18961 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18961'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18961'
 id: 18962 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '18962'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18962'
 id: 18963 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '18963'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18963'
 id: 18964 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '18964'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18964'
 id: 18965 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18965'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18965'
 id: 18966 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '18966'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18966'
 id: 18967 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '18967'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18967'
 id: 18968 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18968'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18968'
 id: 18969 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18969'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18969'
 id: 18970 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18970'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18970'
 id: 18971 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '18971'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18971'
 id: 18972 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18972'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18972'
 id: 18973 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '18973'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18973'
 id: 18974 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '18974'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18974'
 id: 18975 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18975'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18975'
 id: 18976 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18976'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18976'
 id: 18977 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '18977'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18977'
 id: 18978 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '18978'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18978'
 id: 18979 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '18979'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18979'
 id: 18980 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '18980'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18980'
 id: 18981 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '18981'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18981'
 id: 18982 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '18982'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18982'
 id: 18983 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '18983'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18983'
 id: 18984 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '18984'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18984'
 id: 18985 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '18985'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18985'
 id: 18986 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '18986'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18986'
 id: 18987 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '18987'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18987'
 id: 18988 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18988'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18988'
 id: 18989 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '18989'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18989'
 id: 18990 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '18990'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18990'
 id: 18991 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '18991'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18991'
 id: 18992 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '18992'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18992'
 id: 18993 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '18993'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18993'
 id: 18994 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18994'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18994'
 id: 18995 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18995'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18995'
 id: 18996 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '18996'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18996'
 id: 18997 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '18997'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18997'
 id: 18998 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '18998'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18998'
 id: 18999 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '18999'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '18999'
 id: 19000 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '19000'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19000'
 id: 19001 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '19001'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19001'
 id: 19002 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '19002'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19002'
 id: 19003 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '19003'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19003'
 id: 19004 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '19004'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19004'
 id: 19005 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19005'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19005'
 id: 19006 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19006'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19006'
 id: 19007 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '19007'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19007'
 id: 19008 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19008'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19008'
 id: 19009 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19009'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19009'
 id: 19010 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '19010'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19010'
 id: 19011 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19011'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19011'
 id: 19012 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19012'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19012'
 id: 19013 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19013'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19013'
 id: 19014 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '19014'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19014'
 id: 19015 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19015'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19015'
 id: 19016 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '19016'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19016'
 id: 19017 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19017'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19017'
 id: 19018 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19018'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19018'
 id: 19019 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '19019'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19019'
 id: 19020 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19020'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19020'
 id: 19021 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '19021'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19021'
 id: 19022 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '19022'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19022'
 id: 19023 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19023'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19023'
 id: 19024 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19024'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19024'
 id: 19025 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '19025'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19025'
 id: 19026 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '19026'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19026'
 id: 19027 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '19027'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19027'
 id: 19028 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19028'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19028'
 id: 19029 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '19029'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19029'
 id: 19030 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '19030'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19030'
 id: 19031 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '19031'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19031'
 id: 19032 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19032'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19032'
 id: 19033 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '19033'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19033'
 id: 19034 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19034'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19034'
 id: 19035 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '19035'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19035'
 id: 19036 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '19036'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19036'
 id: 19037 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '19037'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19037'
 id: 19038 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19038'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19038'
 id: 19039 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '19039'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19039'
 id: 19040 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '19040'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19040'
 id: 19041 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '19041'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19041'
 id: 19042 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '19042'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19042'
 id: 19043 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '19043'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19043'
 id: 19044 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '19044'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19044'
 id: 19045 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '19045'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19045'
 id: 19046 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '19046'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19046'
 id: 19047 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19047'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19047'
 id: 19048 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '19048'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19048'
 id: 19049 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '19049'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19049'
 id: 19050 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '19050'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19050'
 id: 19051 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19051'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19051'
 id: 19052 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '19052'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19052'
 id: 19053 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '19053'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19053'
 id: 19054 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '19054'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19054'
 id: 19055 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19055'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19055'
 id: 19056 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '19056'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19056'
 id: 19057 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '19057'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19057'
 id: 19058 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '19058'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19058'
 id: 19059 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19059'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19059'
 id: 19060 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19060'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19060'
 id: 19061 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '19061'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19061'
 id: 19062 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '19062'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19062'
 id: 19063 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19063'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19063'
 id: 19064 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '19064'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19064'
 id: 19065 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '19065'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19065'
 id: 19066 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19066'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19066'

 id: 19067 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '19067'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19067'
 id: 19068 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '19068'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19068'
 id: 19069 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19069'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19069'
 id: 19070 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19070'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19070'
 id: 19071 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '19071'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19071'
 id: 19072 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '19072'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19072'
 id: 19073 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '19073'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19073'
 id: 19074 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '19074'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19074'
 id: 19075 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '19075'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19075'
 id: 19076 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19076'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19076'
 id: 19077 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19077'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19077'
 id: 19078 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19078'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19078'
 id: 19079 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '19079'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19079'
 id: 19080 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '19080'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19080'
 id: 19081 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19081'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19081'
 id: 19082 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19082'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19082'
 id: 19083 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19083'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19083'
 id: 19084 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '19084'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19084'
 id: 19085 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '19085'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19085'
 id: 19086 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19086'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19086'
 id: 19087 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19087'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19087'
 id: 19088 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '19088'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19088'
 id: 19089 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '19089'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19089'
 id: 19090 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19090'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19090'
 id: 19091 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19091'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19091'
 id: 19092 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '19092'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19092'
 id: 19093 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '19093'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19093'
 id: 19094 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19094'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19094'
 id: 19095 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '19095'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19095'
 id: 19096 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '19096'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19096'
 id: 19097 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19097'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19097'
 id: 19098 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19098'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19098'
 id: 19099 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '19099'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19099'
 id: 19100 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '19100'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19100'
 id: 19101 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19101'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19101'
 id: 19102 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '19102'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19102'
 id: 19103 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '19103'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19103'
 id: 19104 // word: 66
UPDATE job_vacancies SET domain_id =  '66' where raw_id = '19104'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19104'
 id: 19105 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '19105'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19105'
 id: 19106 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '19106'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19106'
 id: 19107 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '19107'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19107'
 id: 19108 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19108'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19108'
 id: 19109 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19109'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19109'
 id: 19110 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '19110'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19110'
 id: 19111 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '19111'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19111'
 id: 19112 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '19112'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19112'
 id: 19113 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '19113'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19113'
 id: 19114 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19114'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19114'
 id: 19115 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '19115'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19115'
 id: 19116 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19116'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19116'
 id: 19117 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '19117'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19117'
 id: 19118 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '19118'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19118'
 id: 19119 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '19119'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19119'
 id: 19120 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '19120'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19120'
 id: 19121 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19121'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19121'
 id: 19122 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19122'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19122'
 id: 19123 // word: 16
UPDATE job_vacancies SET domain_id =  '16' where raw_id = '19123'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19123'
 id: 19124 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '19124'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19124'
 id: 19125 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19125'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19125'
 id: 19126 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19126'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19126'
 id: 19127 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '19127'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19127'
 id: 19128 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '19128'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19128'
 id: 19129 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '19129'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19129'
 id: 19130 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '19130'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19130'
 id: 19131 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '19131'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19131'
 id: 19132 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '19132'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19132'
 id: 19133 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '19133'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19133'
 id: 19134 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '19134'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19134'
 id: 19135 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '19135'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19135'
 id: 19136 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '19136'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19136'
 id: 19137 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19137'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19137'
 id: 19138 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19138'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19138'
 id: 19139 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19139'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19139'
 id: 19140 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '19140'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19140'
 id: 19141 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '19141'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19141'
 id: 19142 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19142'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19142'
 id: 19143 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19143'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19143'
 id: 19144 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19144'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19144'
 id: 19145 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19145'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19145'
 id: 19146 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '19146'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19146'
 id: 19147 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '19147'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19147'
 id: 19148 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19148'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19148'
 id: 19149 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19149'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19149'
 id: 19150 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '19150'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19150'
 id: 19151 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19151'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19151'
 id: 19152 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19152'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19152'
 id: 19153 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '19153'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19153'
 id: 19154 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '19154'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19154'
 id: 19155 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '19155'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19155'
 id: 19156 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19156'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19156'
 id: 19157 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '19157'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19157'
 id: 19158 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '19158'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19158'
 id: 19159 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19159'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19159'
 id: 19160 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19160'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19160'
 id: 19161 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '19161'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19161'
 id: 19162 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19162'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19162'
 id: 19163 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '19163'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19163'
 id: 19164 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '19164'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19164'
 id: 19165 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '19165'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19165'
 id: 19166 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19166'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19166'
 id: 19167 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '19167'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19167'
 id: 19168 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '19168'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19168'
 id: 19169 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19169'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19169'
 id: 19170 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19170'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19170'
 id: 19171 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19171'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19171'
 id: 19172 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '19172'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19172'
 id: 19173 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '19173'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19173'
 id: 19174 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19174'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19174'
 id: 19175 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '19175'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19175'
 id: 19176 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19176'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19176'
 id: 19177 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '19177'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19177'
 id: 19178 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '19178'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19178'
 id: 19179 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19179'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19179'
 id: 19180 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '19180'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19180'
 id: 19181 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19181'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19181'
 id: 19182 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19182'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19182'
 id: 19183 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '19183'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19183'
 id: 19184 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '19184'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19184'
 id: 19185 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '19185'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19185'
 id: 19186 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '19186'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19186'
 id: 19187 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19187'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19187'
 id: 19188 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19188'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19188'
 id: 19189 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '19189'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19189'
 id: 19190 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '19190'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19190'
 id: 19191 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '19191'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19191'
 id: 19192 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19192'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19192'
 id: 19193 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19193'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19193'
 id: 19194 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '19194'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19194'
 id: 19195 // word: 52
UPDATE job_vacancies SET domain_id =  '52' where raw_id = '19195'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19195'
 id: 19196 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '19196'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19196'
 id: 19197 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '19197'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19197'
 id: 19198 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19198'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19198'
 id: 19199 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '19199'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19199'
 id: 19200 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19200'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19200'
 id: 19201 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '19201'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19201'
 id: 19202 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19202'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19202'
 id: 19203 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '19203'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19203'
 id: 19204 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '19204'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19204'
 id: 19205 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '19205'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19205'
 id: 19206 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19206'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19206'
 id: 19207 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '19207'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19207'
 id: 19208 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19208'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19208'
 id: 19209 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '19209'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19209'
 id: 19210 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '19210'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19210'
 id: 19211 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19211'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19211'
 id: 19212 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '19212'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19212'
 id: 19213 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19213'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19213'
 id: 19214 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '19214'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19214'
 id: 19215 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '19215'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19215'
 id: 19216 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '19216'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19216'
 id: 19217 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19217'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19217'
 id: 19218 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19218'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19218'
 id: 19219 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '19219'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19219'
 id: 19220 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19220'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19220'
 id: 19221 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '19221'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19221'
 id: 19222 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '19222'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19222'
 id: 19223 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19223'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19223'
 id: 19224 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '19224'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19224'
 id: 19225 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '19225'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19225'
 id: 19226 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '19226'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19226'
 id: 19227 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '19227'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19227'
 id: 19228 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '19228'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19228'
 id: 19229 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '19229'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19229'
 id: 19230 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '19230'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19230'
 id: 19231 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '19231'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19231'
 id: 19232 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19232'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19232'
 id: 19233 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19233'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19233'
 id: 19234 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19234'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19234'
 id: 19235 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '19235'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19235'
 id: 19236 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '19236'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19236'
 id: 19237 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19237'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19237'
 id: 19238 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19238'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19238'
 id: 19239 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19239'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19239'
 id: 19240 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19240'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19240'
 id: 19241 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '19241'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19241'
 id: 19242 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19242'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19242'
 id: 19243 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19243'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19243'
 id: 19244 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '19244'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19244'
 id: 19245 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '19245'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19245'
 id: 19246 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '19246'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19246'
 id: 19247 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '19247'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19247'
 id: 19248 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '19248'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19248'
 id: 19249 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '19249'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19249'
 id: 19250 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '19250'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19250'
 id: 19251 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '19251'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19251'
 id: 19252 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '19252'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19252'
 id: 19253 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19253'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19253'
 id: 19254 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '19254'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19254'
 id: 19255 // word: 50
UPDATE job_vacancies SET domain_id =  '50' where raw_id = '19255'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19255'
 id: 19256 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '19256'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19256'
 id: 19257 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '19257'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19257'
 id: 19258 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '19258'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19258'
 id: 19259 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19259'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19259'
 id: 19260 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '19260'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19260'
 id: 19261 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19261'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19261'
 id: 19262 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19262'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19262'
 id: 19263 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '19263'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19263'
 id: 19264 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19264'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19264'
 id: 19265 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19265'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19265'
 id: 19266 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '19266'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19266'
 id: 19267 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '19267'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19267'
 id: 19268 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '19268'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19268'
 id: 19269 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '19269'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19269'
 id: 19270 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '19270'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19270'
 id: 19271 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19271'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19271'
 id: 19272 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '19272'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19272'
 id: 19273 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '19273'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19273'
 id: 19274 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19274'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19274'
 id: 19275 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '19275'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19275'
 id: 19276 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19276'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19276'
 id: 19277 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '19277'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19277'
 id: 19278 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19278'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19278'
 id: 19279 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19279'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19279'
 id: 19280 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19280'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19280'
 id: 19281 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '19281'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19281'
 id: 19282 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '19282'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19282'
 id: 19283 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '19283'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19283'
 id: 19284 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19284'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19284'
 id: 19285 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19285'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19285'
 id: 19286 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19286'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19286'
 id: 19287 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '19287'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19287'
 id: 19288 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '19288'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19288'
 id: 19289 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '19289'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19289'
 id: 19290 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19290'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19290'
 id: 19291 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '19291'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19291'
 id: 19292 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '19292'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19292'
 id: 19293 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '19293'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19293'
 id: 19294 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '19294'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19294'
 id: 19295 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '19295'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19295'
 id: 19296 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19296'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19296'
 id: 19297 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19297'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19297'
 id: 19298 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19298'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19298'
 id: 19299 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19299'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19299'
 id: 19300 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19300'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19300'
 id: 19301 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19301'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19301'
 id: 19302 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19302'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19302'
 id: 19303 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19303'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19303'
 id: 19304 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '19304'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19304'
 id: 19305 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '19305'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19305'
 id: 19306 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '19306'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19306'
 id: 19307 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '19307'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19307'
 id: 19308 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19308'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19308'
 id: 19309 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19309'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19309'
 id: 19310 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19310'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19310'
 id: 19311 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '19311'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19311'
 id: 19312 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19312'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19312'
 id: 19313 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19313'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19313'
 id: 19314 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19314'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19314'
 id: 19315 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '19315'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19315'
 id: 19316 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '19316'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19316'
 id: 19317 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19317'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19317'
 id: 19318 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '19318'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19318'
 id: 19319 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '19319'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19319'
 id: 19320 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '19320'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19320'
 id: 19321 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '19321'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19321'
 id: 19322 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19322'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19322'
 id: 19323 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '19323'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19323'
 id: 19324 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '19324'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19324'
 id: 19325 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '19325'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19325'
 id: 19326 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '19326'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19326'
 id: 19327 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '19327'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19327'
 id: 19328 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19328'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19328'
 id: 19329 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19329'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19329'
 id: 19330 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19330'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19330'
 id: 19331 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '19331'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19331'
 id: 19332 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19332'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19332'
 id: 19333 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '19333'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19333'
 id: 19334 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '19334'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19334'
 id: 19335 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '19335'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19335'
 id: 19336 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '19336'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19336'
 id: 19337 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '19337'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19337'
 id: 19338 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '19338'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19338'
 id: 19339 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19339'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19339'
 id: 19340 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19340'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19340'
 id: 19341 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '19341'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19341'
 id: 19342 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '19342'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19342'
 id: 19343 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19343'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19343'
 id: 19344 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '19344'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19344'
 id: 19345 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '19345'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19345'
 id: 19346 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19346'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19346'
 id: 19347 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19347'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19347'
 id: 19348 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '19348'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19348'
 id: 19349 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19349'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19349'
 id: 19350 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '19350'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19350'
 id: 19351 // word: 52
UPDATE job_vacancies SET domain_id =  '52' where raw_id = '19351'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19351'
 id: 19352 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '19352'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19352'
 id: 19353 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '19353'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19353'
 id: 19354 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '19354'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19354'
 id: 19355 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '19355'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19355'
 id: 19356 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '19356'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19356'
 id: 19357 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19357'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19357'
 id: 19358 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19358'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19358'
 id: 19359 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '19359'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19359'
 id: 19360 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '19360'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19360'
 id: 19361 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19361'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19361'
 id: 19362 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '19362'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19362'
 id: 19363 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '19363'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19363'
 id: 19364 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19364'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19364'
 id: 19365 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '19365'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19365'
 id: 19366 // word: 52
UPDATE job_vacancies SET domain_id =  '52' where raw_id = '19366'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19366'
 id: 19367 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19367'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19367'
 id: 19368 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19368'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19368'
 id: 19369 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19369'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19369'
 id: 19370 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '19370'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19370'
 id: 19371 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '19371'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19371'
 id: 19372 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '19372'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19372'
 id: 19373 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '19373'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19373'
 id: 19374 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '19374'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19374'
 id: 19375 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19375'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19375'
 id: 19376 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19376'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19376'
 id: 19377 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '19377'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19377'
 id: 19378 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '19378'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19378'
 id: 19379 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19379'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19379'
 id: 19380 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '19380'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19380'
 id: 19381 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19381'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19381'
 id: 19382 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19382'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19382'
 id: 19383 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '19383'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19383'
 id: 19384 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '19384'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19384'
 id: 19385 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19385'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19385'
 id: 19386 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '19386'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19386'
 id: 19387 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19387'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19387'
 id: 19388 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '19388'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19388'
 id: 19389 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '19389'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19389'
 id: 19390 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '19390'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19390'
 id: 19391 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19391'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19391'
 id: 19392 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '19392'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19392'
 id: 19393 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '19393'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19393'
 id: 19394 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19394'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19394'
 id: 19395 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '19395'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19395'
 id: 19396 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '19396'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19396'
 id: 19397 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '19397'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19397'
 id: 19398 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '19398'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19398'
 id: 19399 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19399'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19399'
 id: 19400 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '19400'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19400'
 id: 19401 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19401'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19401'
 id: 19402 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '19402'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19402'
 id: 19403 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19403'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19403'
 id: 19404 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '19404'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19404'
 id: 19405 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '19405'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19405'
 id: 19406 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '19406'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19406'
 id: 19407 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19407'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19407'
 id: 19408 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '19408'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19408'
 id: 19409 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '19409'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19409'
 id: 19410 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19410'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19410'
 id: 19411 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '19411'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19411'
 id: 19412 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '19412'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19412'
 id: 19413 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '19413'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19413'
 id: 19414 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '19414'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19414'
 id: 19415 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19415'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19415'
 id: 19416 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19416'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19416'
 id: 19417 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '19417'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19417'
 id: 19418 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19418'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19418'
 id: 19419 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19419'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19419'
 id: 19420 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19420'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19420'
 id: 19421 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '19421'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19421'

 id: 19422 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19422'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19422'
 id: 19423 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19423'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19423'
 id: 19424 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19424'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19424'
 id: 19425 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '19425'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19425'
 id: 19426 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19426'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19426'
 id: 19427 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '19427'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19427'
 id: 19428 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '19428'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19428'
 id: 19429 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '19429'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19429'
 id: 19430 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19430'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19430'
 id: 19431 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19431'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19431'
 id: 19432 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19432'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19432'
 id: 19433 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '19433'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19433'
 id: 19434 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '19434'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19434'
 id: 19435 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '19435'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19435'
 id: 19436 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '19436'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19436'
 id: 19437 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '19437'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19437'
 id: 19438 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19438'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19438'
 id: 19439 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19439'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19439'
 id: 19440 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '19440'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19440'
 id: 19441 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19441'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19441'
 id: 19442 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '19442'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19442'
 id: 19443 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '19443'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19443'
 id: 19444 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19444'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19444'
 id: 19445 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19445'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19445'
 id: 19446 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '19446'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19446'
 id: 19447 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19447'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19447'
 id: 19448 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19448'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19448'
 id: 19449 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19449'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19449'
 id: 19450 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '19450'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19450'
 id: 19451 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '19451'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19451'
 id: 19452 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19452'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19452'
 id: 19453 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19453'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19453'
 id: 19454 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '19454'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19454'
 id: 19455 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19455'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19455'
 id: 19456 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '19456'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19456'
 id: 19457 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19457'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19457'
 id: 19458 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19458'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19458'
 id: 19459 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19459'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19459'
 id: 19460 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '19460'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19460'
 id: 19461 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19461'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19461'
 id: 19462 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '19462'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19462'
 id: 19463 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '19463'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19463'
 id: 19464 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '19464'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19464'
 id: 19465 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19465'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19465'
 id: 19466 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '19466'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19466'
 id: 19467 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19467'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19467'
 id: 19468 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19468'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19468'
 id: 19469 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19469'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19469'
 id: 19470 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '19470'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19470'
 id: 19471 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19471'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19471'
 id: 19472 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '19472'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19472'
 id: 19473 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19473'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19473'

 id: 19474 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '19474'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19474'
 id: 19475 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19475'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19475'
 id: 19476 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19476'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19476'
 id: 19477 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '19477'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19477'
 id: 19478 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '19478'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19478'
 id: 19479 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19479'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19479'
 id: 19480 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '19480'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19480'
 id: 19481 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19481'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19481'
 id: 19482 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '19482'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19482'
 id: 19483 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19483'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19483'
 id: 19484 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19484'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19484'
 id: 19485 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '19485'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19485'
 id: 19486 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19486'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19486'
 id: 19487 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '19487'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19487'
 id: 19488 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19488'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19488'
 id: 19489 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '19489'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19489'
 id: 19490 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '19490'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19490'
 id: 19491 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '19491'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19491'
 id: 19492 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '19492'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19492'
 id: 19493 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '19493'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19493'
 id: 19494 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '19494'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19494'
 id: 19495 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '19495'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19495'
 id: 19496 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19496'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19496'
 id: 19497 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '19497'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19497'
 id: 19498 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19498'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19498'
 id: 19499 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19499'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19499'
 id: 19500 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19500'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19500'
 id: 19501 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19501'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19501'
 id: 19502 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19502'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19502'
 id: 19503 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '19503'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19503'
 id: 19504 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19504'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19504'
 id: 19505 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '19505'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19505'
 id: 19506 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19506'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19506'
 id: 19507 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '19507'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19507'
 id: 19508 // word: 52
UPDATE job_vacancies SET domain_id =  '52' where raw_id = '19508'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19508'
 id: 19509 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '19509'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19509'
 id: 19510 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19510'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19510'
 id: 19511 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19511'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19511'
 id: 19512 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19512'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19512'
 id: 19513 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19513'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19513'
 id: 19514 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '19514'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19514'
 id: 19515 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '19515'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19515'
 id: 19516 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '19516'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19516'
 id: 19517 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '19517'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19517'
 id: 19518 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19518'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19518'
 id: 19519 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19519'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19519'
 id: 19520 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '19520'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19520'
 id: 19521 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '19521'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19521'
 id: 19522 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '19522'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19522'
 id: 19523 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19523'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19523'

 id: 19524 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '19524'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19524'
 id: 19525 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '19525'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19525'
 id: 19526 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '19526'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19526'
 id: 19527 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '19527'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19527'
 id: 19528 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '19528'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19528'
 id: 19529 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '19529'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19529'
 id: 19530 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '19530'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19530'
 id: 19531 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19531'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19531'
 id: 19532 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19532'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19532'
 id: 19533 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19533'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19533'
 id: 19534 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19534'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19534'
 id: 19535 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19535'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19535'
 id: 19536 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '19536'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19536'
 id: 19537 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '19537'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19537'
 id: 19538 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '19538'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19538'
 id: 19539 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '19539'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19539'
 id: 19540 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '19540'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19540'
 id: 19541 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19541'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19541'
 id: 19542 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '19542'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19542'
 id: 19543 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19543'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19543'
 id: 19544 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '19544'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19544'
 id: 19545 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '19545'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19545'
 id: 19546 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19546'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19546'
 id: 19547 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19547'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19547'
 id: 19548 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19548'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19548'
 id: 19549 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '19549'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19549'
 id: 19550 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '19550'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19550'
 id: 19551 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19551'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19551'
 id: 19552 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19552'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19552'
 id: 19553 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19553'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19553'
 id: 19554 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19554'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19554'
 id: 19555 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19555'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19555'
 id: 19556 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19556'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19556'
 id: 19557 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19557'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19557'
 id: 19558 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '19558'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19558'
 id: 19559 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '19559'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19559'
 id: 19560 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '19560'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19560'
 id: 19561 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19561'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19561'
 id: 19562 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '19562'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19562'
 id: 19563 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19563'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19563'
 id: 19564 // word: 50
UPDATE job_vacancies SET domain_id =  '50' where raw_id = '19564'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19564'
 id: 19565 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '19565'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19565'
 id: 19566 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19566'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19566'
 id: 19567 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19567'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19567'
 id: 19568 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19568'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19568'
 id: 19569 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '19569'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19569'
 id: 19570 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '19570'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19570'
 id: 19571 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19571'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19571'
 id: 19572 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '19572'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19572'
 id: 19573 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '19573'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19573'
 id: 19574 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19574'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19574'
 id: 19575 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '19575'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19575'
 id: 19576 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19576'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19576'
 id: 19577 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '19577'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19577'
 id: 19578 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '19578'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19578'
 id: 19579 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19579'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19579'
 id: 19580 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '19580'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19580'
 id: 19581 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '19581'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19581'
 id: 19582 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '19582'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19582'
 id: 19583 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '19583'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19583'
 id: 19584 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '19584'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19584'
 id: 19585 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '19585'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19585'
 id: 19586 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '19586'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19586'
 id: 19587 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '19587'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19587'
 id: 19588 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19588'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19588'
 id: 19589 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19589'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19589'
 id: 19590 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19590'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19590'
 id: 19591 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19591'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19591'
 id: 19592 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19592'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19592'
 id: 19593 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19593'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19593'
 id: 19594 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19594'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19594'
 id: 19595 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19595'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19595'
 id: 19596 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '19596'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19596'
 id: 19597 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '19597'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19597'
 id: 19598 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19598'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19598'
 id: 19599 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19599'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19599'
 id: 19600 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '19600'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19600'
 id: 19601 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '19601'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19601'
 id: 19602 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '19602'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19602'
 id: 19603 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19603'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19603'
 id: 19604 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19604'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19604'
 id: 19605 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '19605'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19605'
 id: 19606 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '19606'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19606'
 id: 19607 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19607'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19607'
 id: 19608 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '19608'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19608'
 id: 19609 // word: 50
UPDATE job_vacancies SET domain_id =  '50' where raw_id = '19609'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19609'
 id: 19610 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19610'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19610'
 id: 19611 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19611'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19611'
 id: 19612 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19612'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19612'
 id: 19613 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19613'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19613'
 id: 19614 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19614'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19614'
 id: 19615 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19615'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19615'
 id: 19616 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '19616'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19616'
 id: 19617 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19617'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19617'
 id: 19618 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19618'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19618'
 id: 19619 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '19619'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19619'
 id: 19620 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '19620'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19620'
 id: 19621 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '19621'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19621'
 id: 19622 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '19622'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19622'
 id: 19623 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '19623'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19623'
 id: 19624 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19624'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19624'
 id: 19625 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19625'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19625'

 id: 19626 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '19626'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19626'
 id: 19627 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '19627'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19627'
 id: 19628 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '19628'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19628'
 id: 19629 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19629'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19629'
 id: 19630 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '19630'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19630'
 id: 19631 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19631'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19631'
 id: 19632 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19632'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19632'
 id: 19633 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '19633'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19633'
 id: 19634 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19634'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19634'
 id: 19635 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '19635'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19635'
 id: 19636 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '19636'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19636'
 id: 19637 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19637'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19637'
 id: 19638 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '19638'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19638'
 id: 19639 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '19639'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19639'
 id: 19640 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19640'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19640'
 id: 19641 // word: 7
UPDATE job_vacancies SET domain_id =  '7' where raw_id = '19641'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19641'
 id: 19642 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '19642'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19642'
 id: 19643 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '19643'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19643'
 id: 19644 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19644'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19644'
 id: 19645 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19645'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19645'
 id: 19646 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19646'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19646'
 id: 19647 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19647'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19647'
 id: 19648 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '19648'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19648'
 id: 19649 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19649'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19649'
 id: 19650 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '19650'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19650'
 id: 19651 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19651'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19651'
 id: 19652 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19652'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19652'
 id: 19653 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19653'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19653'
 id: 19654 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19654'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19654'
 id: 19655 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '19655'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19655'
 id: 19656 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '19656'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19656'
 id: 19657 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19657'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19657'
 id: 19658 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19658'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19658'
 id: 19659 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19659'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19659'
 id: 19660 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '19660'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19660'
 id: 19661 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19661'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19661'
 id: 19662 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '19662'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19662'
 id: 19663 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19663'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19663'
 id: 19664 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '19664'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19664'
 id: 19665 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19665'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19665'
 id: 19666 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19666'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19666'
 id: 19667 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '19667'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19667'
 id: 19668 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '19668'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19668'
 id: 19669 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19669'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19669'
 id: 19670 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19670'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19670'
 id: 19671 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19671'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19671'
 id: 19672 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19672'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19672'
 id: 19673 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19673'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19673'
 id: 19674 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '19674'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19674'
 id: 19675 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19675'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19675'
 id: 19676 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '19676'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19676'
 id: 19677 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19677'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19677'

 id: 19678 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19678'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19678'
 id: 19679 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '19679'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19679'
 id: 19680 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '19680'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19680'
 id: 19681 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19681'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19681'
 id: 19682 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '19682'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19682'
 id: 19683 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19683'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19683'
 id: 19684 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '19684'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19684'
 id: 19685 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '19685'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19685'
 id: 19686 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '19686'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19686'
 id: 19687 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '19687'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19687'
 id: 19688 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '19688'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19688'
 id: 19689 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19689'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19689'
 id: 19690 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '19690'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19690'
 id: 19691 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '19691'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19691'
 id: 19692 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '19692'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19692'
 id: 19693 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19693'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19693'
 id: 19694 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19694'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19694'
 id: 19695 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '19695'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19695'
 id: 19696 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '19696'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19696'
 id: 19697 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '19697'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19697'
 id: 19698 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '19698'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19698'
 id: 19699 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '19699'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19699'
 id: 19700 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '19700'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19700'
 id: 19701 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '19701'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19701'
 id: 19702 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '19702'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19702'
 id: 19703 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19703'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19703'
 id: 19704 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19704'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19704'
 id: 19705 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '19705'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19705'
 id: 19706 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19706'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19706'
 id: 19707 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19707'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19707'
 id: 19708 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '19708'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19708'
 id: 19709 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19709'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19709'
 id: 19710 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19710'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19710'
 id: 19711 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19711'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19711'
 id: 19712 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19712'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19712'
 id: 19713 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19713'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19713'
 id: 19714 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '19714'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19714'
 id: 19715 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '19715'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19715'
 id: 19716 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19716'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19716'
 id: 19717 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '19717'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19717'
 id: 19718 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19718'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19718'
 id: 19719 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '19719'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19719'
 id: 19720 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '19720'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19720'
 id: 19721 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19721'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19721'
 id: 19722 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19722'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19722'
 id: 19723 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '19723'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19723'
 id: 19724 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19724'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19724'
 id: 19725 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '19725'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19725'
 id: 19726 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19726'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19726'
 id: 19727 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19727'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19727'
 id: 19728 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19728'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19728'
 id: 19729 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19729'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19729'

 id: 19730 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '19730'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19730'
 id: 19731 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '19731'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19731'
 id: 19732 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19732'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19732'
 id: 19733 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '19733'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19733'
 id: 19734 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19734'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19734'
 id: 19735 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19735'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19735'
 id: 19736 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19736'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19736'
 id: 19737 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19737'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19737'
 id: 19738 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19738'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19738'
 id: 19739 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19739'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19739'
 id: 19740 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '19740'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19740'
 id: 19741 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19741'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19741'
 id: 19742 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19742'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19742'
 id: 19743 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19743'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19743'
 id: 19744 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '19744'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19744'
 id: 19745 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '19745'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19745'
 id: 19746 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19746'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19746'
 id: 19747 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19747'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19747'
 id: 19748 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '19748'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19748'
 id: 19749 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '19749'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19749'
 id: 19750 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19750'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19750'
 id: 19751 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19751'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19751'
 id: 19752 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19752'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19752'
 id: 19753 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '19753'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19753'
 id: 19754 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '19754'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19754'
 id: 19755 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '19755'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19755'
 id: 19756 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '19756'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19756'
 id: 19757 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19757'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19757'
 id: 19758 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '19758'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19758'
 id: 19759 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19759'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19759'
 id: 19760 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19760'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19760'
 id: 19761 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19761'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19761'
 id: 19762 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19762'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19762'
 id: 19763 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '19763'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19763'
 id: 19764 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '19764'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19764'
 id: 19765 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19765'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19765'
 id: 19766 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '19766'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19766'
 id: 19767 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19767'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19767'
 id: 19768 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '19768'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19768'
 id: 19769 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '19769'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19769'
 id: 19770 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '19770'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19770'
 id: 19771 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '19771'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19771'
 id: 19772 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '19772'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19772'
 id: 19773 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '19773'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19773'
 id: 19774 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '19774'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19774'
 id: 19775 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '19775'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19775'
 id: 19776 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '19776'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19776'
 id: 19777 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '19777'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19777'
 id: 19778 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19778'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19778'
 id: 19779 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '19779'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19779'

 id: 19780 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19780'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19780'
 id: 19781 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19781'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19781'
 id: 19782 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '19782'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19782'
 id: 19783 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '19783'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19783'
 id: 19784 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '19784'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19784'
 id: 19785 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19785'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19785'
 id: 19786 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19786'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19786'
 id: 19787 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '19787'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19787'
 id: 19788 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19788'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19788'
 id: 19789 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '19789'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19789'
 id: 19790 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19790'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19790'
 id: 19791 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19791'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19791'
 id: 19792 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '19792'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19792'
 id: 19793 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19793'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19793'
 id: 19794 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '19794'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19794'
 id: 19795 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19795'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19795'
 id: 19796 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '19796'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19796'
 id: 19797 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '19797'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19797'
 id: 19798 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19798'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19798'
 id: 19799 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '19799'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19799'
 id: 19800 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19800'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19800'
 id: 19801 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '19801'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19801'
 id: 19802 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19802'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19802'
 id: 19803 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19803'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19803'
 id: 19804 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19804'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19804'
 id: 19805 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '19805'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19805'
 id: 19806 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '19806'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19806'
 id: 19807 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '19807'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19807'
 id: 19808 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19808'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19808'
 id: 19809 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19809'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19809'
 id: 19810 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19810'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19810'
 id: 19811 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19811'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19811'
 id: 19812 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19812'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19812'
 id: 19813 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19813'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19813'
 id: 19814 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '19814'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19814'
 id: 19815 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19815'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19815'
 id: 19816 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '19816'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19816'
 id: 19817 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '19817'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19817'
 id: 19818 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19818'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19818'
 id: 19819 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '19819'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19819'
 id: 19820 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19820'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19820'
 id: 19821 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '19821'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19821'
 id: 19822 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '19822'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19822'
 id: 19823 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19823'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19823'
 id: 19824 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19824'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19824'
 id: 19825 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '19825'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19825'
 id: 19826 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '19826'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19826'
 id: 19827 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19827'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19827'
 id: 19828 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19828'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19828'
 id: 19829 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19829'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19829'
 id: 19830 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19830'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19830'

 id: 19831 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19831'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19831'
 id: 19832 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '19832'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19832'
 id: 19833 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '19833'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19833'
 id: 19834 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '19834'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19834'
 id: 19835 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '19835'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19835'
 id: 19836 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '19836'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19836'
 id: 19837 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19837'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19837'
 id: 19838 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '19838'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19838'
 id: 19839 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '19839'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19839'
 id: 19840 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19840'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19840'
 id: 19841 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '19841'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19841'
 id: 19842 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19842'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19842'
 id: 19843 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '19843'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19843'
 id: 19844 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '19844'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19844'
 id: 19845 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19845'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19845'
 id: 19846 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19846'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19846'
 id: 19847 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19847'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19847'
 id: 19848 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '19848'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19848'
 id: 19849 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '19849'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19849'
 id: 19850 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '19850'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19850'
 id: 19851 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19851'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19851'
 id: 19852 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '19852'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19852'
 id: 19853 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19853'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19853'
 id: 19854 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '19854'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19854'
 id: 19855 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '19855'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19855'
 id: 19856 // word: 48
UPDATE job_vacancies SET domain_id =  '48' where raw_id = '19856'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19856'
 id: 19857 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19857'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19857'
 id: 19858 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '19858'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19858'
 id: 19859 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '19859'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19859'
 id: 19860 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19860'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19860'
 id: 19861 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '19861'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19861'
 id: 19862 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19862'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19862'
 id: 19863 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '19863'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19863'
 id: 19864 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '19864'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19864'
 id: 19865 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '19865'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19865'
 id: 19866 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19866'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19866'
 id: 19867 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19867'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19867'
 id: 19868 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19868'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19868'
 id: 19869 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19869'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19869'
 id: 19870 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '19870'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19870'
 id: 19871 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '19871'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19871'
 id: 19872 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19872'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19872'
 id: 19873 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19873'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19873'
 id: 19874 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19874'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19874'
 id: 19875 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19875'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19875'
 id: 19876 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '19876'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19876'
 id: 19877 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '19877'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19877'
 id: 19878 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19878'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19878'
 id: 19879 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19879'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19879'
 id: 19880 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '19880'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19880'
 id: 19881 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '19881'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19881'
 id: 19882 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19882'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19882'
 id: 19883 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '19883'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19883'
 id: 19884 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19884'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19884'
 id: 19885 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19885'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19885'
 id: 19886 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '19886'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19886'
 id: 19887 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19887'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19887'
 id: 19888 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19888'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19888'
 id: 19889 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19889'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19889'
 id: 19890 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '19890'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19890'
 id: 19891 // word: 52
UPDATE job_vacancies SET domain_id =  '52' where raw_id = '19891'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19891'
 id: 19892 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '19892'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19892'
 id: 19893 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '19893'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19893'
 id: 19894 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19894'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19894'
 id: 19895 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '19895'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19895'
 id: 19896 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '19896'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19896'
 id: 19897 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '19897'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19897'
 id: 19898 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '19898'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19898'
 id: 19899 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19899'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19899'
 id: 19900 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19900'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19900'
 id: 19901 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19901'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19901'
 id: 19902 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19902'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19902'
 id: 19903 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19903'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19903'
 id: 19904 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '19904'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19904'
 id: 19905 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '19905'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19905'
 id: 19906 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '19906'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19906'
 id: 19907 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '19907'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19907'
 id: 19908 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19908'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19908'
 id: 19909 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '19909'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19909'
 id: 19910 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19910'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19910'
 id: 19911 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '19911'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19911'
 id: 19912 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19912'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19912'
 id: 19913 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '19913'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19913'
 id: 19914 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '19914'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19914'
 id: 19915 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '19915'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19915'
 id: 19916 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '19916'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19916'
 id: 19917 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19917'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19917'
 id: 19918 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19918'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19918'
 id: 19919 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '19919'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19919'
 id: 19920 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19920'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19920'
 id: 19921 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19921'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19921'
 id: 19922 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19922'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19922'
 id: 19923 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '19923'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19923'
 id: 19924 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19924'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19924'
 id: 19925 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19925'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19925'
 id: 19926 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '19926'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19926'
 id: 19927 // word: 49
UPDATE job_vacancies SET domain_id =  '49' where raw_id = '19927'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19927'
 id: 19928 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '19928'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19928'
 id: 19929 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19929'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19929'
 id: 19930 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '19930'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19930'
 id: 19931 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19931'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19931'
 id: 19932 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '19932'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19932'
 id: 19933 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '19933'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19933'
 id: 19934 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '19934'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19934'
 id: 19935 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '19935'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19935'
 id: 19936 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19936'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19936'
 id: 19937 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '19937'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19937'
 id: 19938 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '19938'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19938'
 id: 19939 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19939'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19939'
 id: 19940 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19940'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19940'
 id: 19941 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19941'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19941'
 id: 19942 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19942'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19942'
 id: 19943 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '19943'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19943'
 id: 19944 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19944'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19944'
 id: 19945 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '19945'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19945'
 id: 19946 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '19946'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19946'
 id: 19947 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '19947'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19947'
 id: 19948 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19948'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19948'
 id: 19949 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19949'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19949'
 id: 19950 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '19950'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19950'
 id: 19951 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '19951'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19951'
 id: 19952 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '19952'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19952'
 id: 19953 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '19953'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19953'
 id: 19954 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '19954'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19954'
 id: 19955 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '19955'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19955'
 id: 19956 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19956'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19956'
 id: 19957 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '19957'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19957'
 id: 19958 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19958'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19958'
 id: 19959 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19959'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19959'
 id: 19960 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19960'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19960'
 id: 19961 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '19961'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19961'
 id: 19962 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19962'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19962'
 id: 19963 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19963'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19963'
 id: 19964 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19964'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19964'
 id: 19965 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19965'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19965'
 id: 19966 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19966'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19966'
 id: 19967 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19967'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19967'
 id: 19968 // word: 52
UPDATE job_vacancies SET domain_id =  '52' where raw_id = '19968'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19968'
 id: 19969 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19969'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19969'
 id: 19970 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '19970'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19970'
 id: 19971 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19971'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19971'
 id: 19972 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19972'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19972'
 id: 19973 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19973'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19973'
 id: 19974 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19974'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19974'
 id: 19975 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '19975'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19975'
 id: 19976 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '19976'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19976'
 id: 19977 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '19977'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19977'
 id: 19978 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '19978'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19978'
 id: 19979 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19979'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19979'
 id: 19980 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '19980'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19980'
 id: 19981 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19981'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19981'
 id: 19982 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '19982'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19982'
 id: 19983 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '19983'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19983'
 id: 19984 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19984'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19984'

 id: 19985 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '19985'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19985'
 id: 19986 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '19986'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19986'
 id: 19987 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19987'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19987'
 id: 19988 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '19988'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19988'
 id: 19989 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '19989'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19989'
 id: 19990 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '19990'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19990'
 id: 19991 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '19991'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19991'
 id: 19992 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '19992'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19992'
 id: 19993 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19993'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19993'
 id: 19994 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '19994'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19994'
 id: 19995 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '19995'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19995'
 id: 19996 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '19996'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19996'
 id: 19997 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '19997'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19997'
 id: 19998 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '19998'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19998'
 id: 19999 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '19999'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '19999'
 id: 20000 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '20000'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20000'
 id: 20001 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20001'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20001'
 id: 20002 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '20002'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20002'
 id: 20003 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20003'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20003'
 id: 20004 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20004'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20004'
 id: 20005 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '20005'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20005'
 id: 20006 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '20006'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20006'
 id: 20007 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '20007'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20007'
 id: 20008 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '20008'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20008'
 id: 20009 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '20009'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20009'
 id: 20010 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '20010'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20010'
 id: 20011 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '20011'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20011'
 id: 20012 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '20012'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20012'
 id: 20013 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '20013'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20013'
 id: 20014 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20014'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20014'
 id: 20015 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '20015'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20015'
 id: 20016 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '20016'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20016'
 id: 20017 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '20017'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20017'
 id: 20018 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '20018'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20018'
 id: 20019 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20019'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20019'
 id: 20020 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '20020'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20020'
 id: 20021 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20021'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20021'
 id: 20022 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20022'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20022'
 id: 20023 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20023'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20023'
 id: 20024 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '20024'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20024'
 id: 20025 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20025'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20025'
 id: 20026 // word: 51
UPDATE job_vacancies SET domain_id =  '51' where raw_id = '20026'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20026'
 id: 20027 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '20027'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20027'
 id: 20028 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20028'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20028'
 id: 20029 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20029'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20029'
 id: 20030 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20030'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20030'
 id: 20031 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20031'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20031'
 id: 20032 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '20032'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20032'
 id: 20033 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '20033'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20033'
 id: 20034 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '20034'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20034'
 id: 20035 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20035'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20035'
 id: 20036 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '20036'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20036'
 id: 20037 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '20037'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20037'
 id: 20038 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '20038'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20038'
 id: 20039 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '20039'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20039'
 id: 20040 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20040'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20040'
 id: 20041 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20041'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20041'
 id: 20042 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '20042'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20042'
 id: 20043 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '20043'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20043'
 id: 20044 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '20044'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20044'
 id: 20045 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20045'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20045'
 id: 20046 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20046'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20046'
 id: 20047 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '20047'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20047'
 id: 20048 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '20048'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20048'
 id: 20049 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '20049'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20049'
 id: 20050 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20050'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20050'
 id: 20051 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '20051'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20051'
 id: 20052 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20052'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20052'
 id: 20053 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '20053'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20053'
 id: 20054 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '20054'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20054'
 id: 20055 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '20055'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20055'
 id: 20056 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '20056'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20056'
 id: 20057 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '20057'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20057'
 id: 20058 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '20058'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20058'
 id: 20059 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '20059'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20059'
 id: 20060 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '20060'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20060'
 id: 20061 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '20061'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20061'
 id: 20062 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20062'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20062'
 id: 20063 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20063'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20063'
 id: 20064 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '20064'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20064'
 id: 20065 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20065'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20065'
 id: 20066 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '20066'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20066'
 id: 20067 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20067'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20067'
 id: 20068 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '20068'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20068'
 id: 20069 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '20069'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20069'
 id: 20070 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '20070'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20070'
 id: 20071 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20071'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20071'
 id: 20072 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '20072'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20072'
 id: 20073 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '20073'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20073'
 id: 20074 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20074'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20074'
 id: 20075 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '20075'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20075'
 id: 20076 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '20076'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20076'
 id: 20077 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '20077'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20077'
 id: 20078 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20078'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20078'
 id: 20079 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20079'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20079'
 id: 20080 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '20080'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20080'
 id: 20081 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '20081'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20081'
 id: 20082 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20082'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20082'
 id: 20083 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '20083'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20083'
 id: 20084 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '20084'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20084'
 id: 20085 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '20085'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20085'
 id: 20086 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '20086'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20086'
 id: 20087 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20087'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20087'
 id: 20088 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '20088'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20088'
 id: 20089 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20089'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20089'

 id: 20090 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20090'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20090'
 id: 20091 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '20091'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20091'
 id: 20092 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '20092'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20092'
 id: 20093 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '20093'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20093'
 id: 20094 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '20094'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20094'
 id: 20095 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '20095'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20095'
 id: 20096 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20096'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20096'
 id: 20097 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20097'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20097'
 id: 20098 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20098'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20098'
 id: 20099 // word: 27
UPDATE job_vacancies SET domain_id =  '27' where raw_id = '20099'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20099'
 id: 20100 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20100'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20100'
 id: 20101 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '20101'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20101'
 id: 20102 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '20102'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20102'
 id: 20103 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '20103'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20103'
 id: 20104 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '20104'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20104'
 id: 20105 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '20105'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20105'
 id: 20106 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '20106'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20106'
 id: 20107 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '20107'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20107'
 id: 20108 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20108'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20108'
 id: 20109 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20109'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20109'
 id: 20110 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '20110'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20110'
 id: 20111 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '20111'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20111'
 id: 20112 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '20112'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20112'
 id: 20113 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '20113'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20113'
 id: 20114 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '20114'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20114'
 id: 20115 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '20115'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20115'
 id: 20116 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '20116'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20116'
 id: 20117 // word: 56
UPDATE job_vacancies SET domain_id =  '56' where raw_id = '20117'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20117'
 id: 20118 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '20118'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20118'
 id: 20119 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '20119'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20119'
 id: 20120 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '20120'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20120'
 id: 20121 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '20121'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20121'
 id: 20122 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '20122'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20122'
 id: 20123 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20123'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20123'
 id: 20124 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '20124'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20124'
 id: 20125 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '20125'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20125'
 id: 20126 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '20126'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20126'
 id: 20127 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '20127'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20127'
 id: 20128 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '20128'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20128'
 id: 20129 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '20129'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20129'
 id: 20130 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '20130'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20130'
 id: 20131 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '20131'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20131'
 id: 20132 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '20132'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20132'
 id: 20133 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '20133'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20133'
 id: 20134 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '20134'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20134'
 id: 20135 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '20135'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20135'
 id: 20136 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '20136'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20136'
 id: 20137 // word: 68
UPDATE job_vacancies SET domain_id =  '68' where raw_id = '20137'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20137'
 id: 20138 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '20138'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20138'
 id: 20139 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '20139'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20139'
 id: 20140 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20140'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20140'
 id: 20141 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '20141'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20141'
 id: 20142 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20142'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20142'
 id: 20143 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20143'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20143'
 id: 20144 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20144'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20144'
 id: 20145 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20145'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20145'
 id: 20146 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20146'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20146'
 id: 20147 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '20147'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20147'
 id: 20148 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '20148'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20148'
 id: 20149 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '20149'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20149'
 id: 20150 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '20150'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20150'
 id: 20151 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '20151'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20151'
 id: 20152 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '20152'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20152'
 id: 20153 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '20153'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20153'
 id: 20154 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '20154'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20154'
 id: 20155 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20155'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20155'
 id: 20156 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '20156'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20156'
 id: 20157 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '20157'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20157'
 id: 20158 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20158'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20158'
 id: 20159 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '20159'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20159'
 id: 20160 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20160'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20160'
 id: 20161 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '20161'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20161'
 id: 20162 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20162'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20162'
 id: 20163 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20163'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20163'
 id: 20164 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20164'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20164'
 id: 20165 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '20165'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20165'
 id: 20166 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '20166'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20166'
 id: 20167 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '20167'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20167'
 id: 20168 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '20168'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20168'
 id: 20169 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '20169'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20169'
 id: 20170 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '20170'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20170'
 id: 20171 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '20171'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20171'
 id: 20172 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '20172'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20172'
 id: 20173 // word: 50
UPDATE job_vacancies SET domain_id =  '50' where raw_id = '20173'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20173'
 id: 20174 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '20174'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20174'
 id: 20175 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20175'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20175'
 id: 20176 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20176'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20176'
 id: 20177 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '20177'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20177'
 id: 20178 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '20178'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20178'
 id: 20179 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20179'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20179'
 id: 20180 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '20180'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20180'
 id: 20181 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '20181'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20181'
 id: 20182 // word: 59
UPDATE job_vacancies SET domain_id =  '59' where raw_id = '20182'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20182'
 id: 20183 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '20183'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20183'
 id: 20184 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '20184'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20184'
 id: 20185 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20185'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20185'
 id: 20186 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '20186'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20186'
 id: 20187 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '20187'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20187'
 id: 20188 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '20188'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20188'
 id: 20189 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20189'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20189'
 id: 20190 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '20190'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20190'
 id: 20191 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '20191'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20191'
 id: 20192 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '20192'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20192'
 id: 20193 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '20193'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20193'
 id: 20194 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20194'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20194'
 id: 20195 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '20195'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20195'
 id: 20196 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '20196'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20196'
 id: 20197 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '20197'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20197'
 id: 20198 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '20198'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20198'
 id: 20199 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '20199'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20199'
 id: 20200 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '20200'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20200'
 id: 20201 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '20201'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20201'
 id: 20202 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '20202'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20202'
 id: 20203 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '20203'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20203'
 id: 20204 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '20204'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20204'
 id: 20205 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20205'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20205'
 id: 20206 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '20206'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20206'
 id: 20207 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20207'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20207'
 id: 20208 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20208'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20208'
 id: 20209 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '20209'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20209'
 id: 20210 // word: 19
UPDATE job_vacancies SET domain_id =  '19' where raw_id = '20210'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20210'
 id: 20211 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20211'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20211'
 id: 20212 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '20212'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20212'
 id: 20213 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20213'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20213'
 id: 20214 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20214'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20214'
 id: 20215 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '20215'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20215'
 id: 20216 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20216'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20216'
 id: 20217 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '20217'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20217'
 id: 20218 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20218'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20218'
 id: 20219 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20219'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20219'
 id: 20220 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20220'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20220'
 id: 20221 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20221'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20221'
 id: 20222 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '20222'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20222'
 id: 20223 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '20223'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20223'
 id: 20224 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '20224'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20224'
 id: 20225 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20225'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20225'
 id: 20226 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '20226'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20226'
 id: 20227 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20227'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20227'
 id: 20228 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '20228'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20228'
 id: 20229 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '20229'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20229'
 id: 20230 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '20230'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20230'
 id: 20231 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '20231'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20231'
 id: 20232 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '20232'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20232'
 id: 20233 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20233'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20233'
 id: 20234 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '20234'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20234'
 id: 20235 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20235'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20235'
 id: 20236 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '20236'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20236'
 id: 20237 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '20237'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20237'
 id: 20238 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '20238'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20238'
 id: 20239 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '20239'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20239'
 id: 20240 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '20240'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20240'
 id: 20241 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20241'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20241'
 id: 20242 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '20242'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20242'
 id: 20243 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '20243'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20243'
 id: 20244 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '20244'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20244'
 id: 20245 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '20245'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20245'
 id: 20246 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '20246'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20246'
 id: 20247 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '20247'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20247'
 id: 20248 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20248'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20248'
 id: 20249 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '20249'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20249'
 id: 20250 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '20250'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20250'
 id: 20251 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '20251'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20251'
 id: 20252 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '20252'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20252'
 id: 20253 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20253'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20253'
 id: 20254 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20254'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20254'
 id: 20255 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '20255'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20255'
 id: 20256 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20256'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20256'
 id: 20257 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '20257'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20257'
 id: 20258 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20258'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20258'
 id: 20259 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20259'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20259'
 id: 20260 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '20260'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20260'
 id: 20261 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '20261'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20261'
 id: 20262 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '20262'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20262'
 id: 20263 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20263'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20263'
 id: 20264 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20264'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20264'
 id: 20265 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '20265'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20265'
 id: 20266 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '20266'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20266'
 id: 20267 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20267'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20267'
 id: 20268 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '20268'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20268'
 id: 20269 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '20269'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20269'
 id: 20270 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '20270'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20270'
 id: 20271 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20271'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20271'
 id: 20272 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '20272'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20272'
 id: 20273 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '20273'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20273'
 id: 20274 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20274'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20274'
 id: 20275 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '20275'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20275'
 id: 20276 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '20276'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20276'
 id: 20277 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '20277'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20277'
 id: 20278 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '20278'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20278'
 id: 20279 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '20279'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20279'
 id: 20280 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '20280'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20280'
 id: 20281 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20281'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20281'
 id: 20282 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '20282'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20282'
 id: 20283 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '20283'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20283'
 id: 20284 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20284'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20284'
 id: 20285 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '20285'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20285'
 id: 20286 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20286'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20286'
 id: 20287 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20287'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20287'
 id: 20288 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20288'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20288'
 id: 20289 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '20289'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20289'
 id: 20290 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20290'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20290'
 id: 20291 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '20291'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20291'
 id: 20292 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20292'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20292'
 id: 20293 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20293'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20293'
 id: 20294 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '20294'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20294'
 id: 20295 // word: 18
UPDATE job_vacancies SET domain_id =  '18' where raw_id = '20295'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20295'
 id: 20296 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '20296'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20296'
 id: 20297 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20297'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20297'
 id: 20298 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '20298'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20298'
 id: 20299 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20299'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20299'
 id: 20300 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '20300'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20300'
 id: 20301 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '20301'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20301'
 id: 20302 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20302'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20302'
 id: 20303 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '20303'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20303'
 id: 20304 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20304'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20304'
 id: 20305 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '20305'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20305'
 id: 20306 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '20306'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20306'
 id: 20307 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20307'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20307'
 id: 20308 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '20308'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20308'
 id: 20309 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '20309'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20309'
 id: 20310 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '20310'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20310'
 id: 20311 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '20311'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20311'
 id: 20312 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '20312'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20312'
 id: 20313 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20313'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20313'
 id: 20314 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '20314'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20314'
 id: 20315 // word: 15
UPDATE job_vacancies SET domain_id =  '15' where raw_id = '20315'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20315'
 id: 20316 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20316'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20316'
 id: 20317 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '20317'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20317'
 id: 20318 // word: 20
UPDATE job_vacancies SET domain_id =  '20' where raw_id = '20318'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20318'
 id: 20319 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '20319'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20319'
 id: 20320 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '20320'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20320'
 id: 20321 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '20321'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20321'
 id: 20322 // word: 52
UPDATE job_vacancies SET domain_id =  '52' where raw_id = '20322'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20322'
 id: 20323 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20323'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20323'
 id: 20324 // word: 6
UPDATE job_vacancies SET domain_id =  '6' where raw_id = '20324'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20324'
 id: 20325 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '20325'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20325'
 id: 20326 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20326'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20326'
 id: 20327 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20327'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20327'
 id: 20328 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20328'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20328'
 id: 20329 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '20329'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20329'
 id: 20330 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20330'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20330'
 id: 20331 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20331'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20331'
 id: 20332 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20332'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20332'
 id: 20333 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '20333'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20333'
 id: 20334 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '20334'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20334'
 id: 20335 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '20335'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20335'
 id: 20336 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '20336'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20336'
 id: 20337 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '20337'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20337'
 id: 20338 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '20338'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20338'
 id: 20339 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '20339'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20339'
 id: 20340 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20340'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20340'
 id: 20341 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '20341'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20341'
 id: 20342 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20342'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20342'
 id: 20343 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '20343'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20343'
 id: 20344 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '20344'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20344'
 id: 20345 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '20345'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20345'
 id: 20346 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '20346'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20346'

 id: 20347 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '20347'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20347'
 id: 20348 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '20348'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20348'
 id: 20349 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20349'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20349'
 id: 20350 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '20350'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20350'
 id: 20351 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20351'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20351'
 id: 20352 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '20352'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20352'
 id: 20353 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20353'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20353'
 id: 20354 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '20354'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20354'
 id: 20355 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '20355'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20355'
 id: 20356 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20356'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20356'
 id: 20357 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '20357'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20357'
 id: 20358 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '20358'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20358'
 id: 20359 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '20359'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20359'
 id: 20360 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '20360'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20360'
 id: 20361 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20361'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20361'
 id: 20362 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '20362'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20362'
 id: 20363 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '20363'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20363'
 id: 20364 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '20364'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20364'
 id: 20365 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20365'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20365'
 id: 20366 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20366'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20366'
 id: 20367 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '20367'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20367'
 id: 20368 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '20368'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20368'
 id: 20369 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20369'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20369'
 id: 20370 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20370'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20370'
 id: 20371 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '20371'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20371'
 id: 20372 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20372'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20372'
 id: 20373 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '20373'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20373'
 id: 20374 // word: 61
UPDATE job_vacancies SET domain_id =  '61' where raw_id = '20374'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20374'
 id: 20375 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '20375'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20375'
 id: 20376 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '20376'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20376'
 id: 20377 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '20377'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20377'
 id: 20378 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '20378'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20378'
 id: 20379 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '20379'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20379'
 id: 20380 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20380'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20380'
 id: 20381 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '20381'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20381'
 id: 20382 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '20382'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20382'
 id: 20383 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20383'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20383'
 id: 20384 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '20384'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20384'
 id: 20385 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20385'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20385'
 id: 20386 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20386'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20386'
 id: 20387 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20387'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20387'
 id: 20388 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20388'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20388'
 id: 20389 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '20389'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20389'
 id: 20390 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '20390'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20390'
 id: 20391 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '20391'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20391'
 id: 20392 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '20392'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20392'
 id: 20393 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '20393'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20393'
 id: 20394 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20394'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20394'
 id: 20395 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20395'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20395'
 id: 20396 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '20396'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20396'
 id: 20397 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '20397'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20397'
 id: 20398 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '20398'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20398'
 id: 20399 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20399'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20399'
 id: 20400 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '20400'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20400'
 id: 20401 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20401'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20401'
 id: 20402 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '20402'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20402'
 id: 20403 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20403'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20403'
 id: 20404 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20404'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20404'
 id: 20405 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '20405'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20405'
 id: 20406 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '20406'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20406'
 id: 20407 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '20407'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20407'
 id: 20408 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '20408'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20408'
 id: 20409 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '20409'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20409'
 id: 20410 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20410'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20410'
 id: 20411 // word: 58
UPDATE job_vacancies SET domain_id =  '58' where raw_id = '20411'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20411'
 id: 20412 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '20412'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20412'
 id: 20413 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20413'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20413'
 id: 20414 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '20414'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20414'
 id: 20415 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '20415'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20415'
 id: 20416 // word: 62
UPDATE job_vacancies SET domain_id =  '62' where raw_id = '20416'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20416'
 id: 20417 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20417'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20417'
 id: 20418 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '20418'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20418'
 id: 20419 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '20419'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20419'
 id: 20420 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20420'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20420'
 id: 20421 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '20421'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20421'
 id: 20422 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '20422'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20422'
 id: 20423 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '20423'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20423'
 id: 20424 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '20424'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20424'
 id: 20425 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '20425'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20425'
 id: 20426 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '20426'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20426'
 id: 20427 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '20427'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20427'
 id: 20428 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '20428'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20428'
 id: 20429 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '20429'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20429'
 id: 20430 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20430'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20430'
 id: 20431 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '20431'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20431'
 id: 20432 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20432'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20432'
 id: 20433 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '20433'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20433'
 id: 20434 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '20434'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20434'
 id: 20435 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '20435'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20435'
 id: 20436 // word: 70
UPDATE job_vacancies SET domain_id =  '70' where raw_id = '20436'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20436'
 id: 20437 // word: 21
UPDATE job_vacancies SET domain_id =  '21' where raw_id = '20437'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20437'
 id: 20438 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '20438'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20438'
 id: 20439 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '20439'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20439'
 id: 20440 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '20440'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20440'
 id: 20441 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20441'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20441'
 id: 20442 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20442'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20442'
 id: 20443 // word: 37
UPDATE job_vacancies SET domain_id =  '37' where raw_id = '20443'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20443'
 id: 20444 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '20444'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20444'
 id: 20445 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '20445'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20445'
 id: 20446 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '20446'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20446'
 id: 20447 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '20447'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20447'
 id: 20448 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '20448'

UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20448'
 id: 20449 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '20449'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20449'
 id: 20450 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20450'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20450'
 id: 20451 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '20451'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20451'
 id: 20452 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '20452'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20452'
 id: 20453 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '20453'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20453'
 id: 20454 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '20454'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20454'
 id: 20455 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '20455'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20455'
 id: 20456 // word: 35
UPDATE job_vacancies SET domain_id =  '35' where raw_id = '20456'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20456'
 id: 20457 // word: 34
UPDATE job_vacancies SET domain_id =  '34' where raw_id = '20457'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20457'
 id: 20458 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20458'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20458'
 id: 20459 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20459'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20459'
 id: 20460 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20460'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20460'
 id: 20461 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '20461'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20461'
 id: 20462 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20462'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20462'
 id: 20463 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '20463'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20463'
 id: 20464 // word: 42
UPDATE job_vacancies SET domain_id =  '42' where raw_id = '20464'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20464'
 id: 20465 // word: 44
UPDATE job_vacancies SET domain_id =  '44' where raw_id = '20465'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20465'
 id: 20466 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '20466'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20466'
 id: 20467 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20467'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20467'
 id: 20468 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '20468'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20468'
 id: 20469 // word: 54
UPDATE job_vacancies SET domain_id =  '54' where raw_id = '20469'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20469'
 id: 20470 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '20470'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20470'
 id: 20471 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '20471'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20471'
 id: 20472 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '20472'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20472'
 id: 20473 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20473'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20473'
 id: 20474 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '20474'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20474'
 id: 20475 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20475'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20475'
 id: 20476 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20476'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20476'
 id: 20477 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '20477'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20477'
 id: 20478 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '20478'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20478'
 id: 20479 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20479'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20479'
 id: 20480 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20480'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20480'
 id: 20481 // word: 3
UPDATE job_vacancies SET domain_id =  '3' where raw_id = '20481'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20481'
 id: 20482 // word: 5
UPDATE job_vacancies SET domain_id =  '5' where raw_id = '20482'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20482'
 id: 20483 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '20483'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20483'
 id: 20484 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20484'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20484'
 id: 20485 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '20485'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20485'
 id: 20486 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '20486'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20486'
 id: 20487 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '20487'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20487'
 id: 20488 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20488'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20488'
 id: 20489 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20489'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20489'
 id: 20490 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20490'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20490'
 id: 20491 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20491'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20491'
 id: 20492 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20492'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20492'
 id: 20493 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '20493'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20493'
 id: 20494 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '20494'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20494'
 id: 20495 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '20495'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20495'
 id: 20496 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20496'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20496'
 id: 20497 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '20497'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20497'
 id: 20498 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '20498'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20498'
 id: 20499 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20499'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20499'
 id: 20500 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20500'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20500'

 id: 20501 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20501'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20501'
 id: 20502 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20502'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20502'
 id: 20503 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '20503'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20503'
 id: 20504 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '20504'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20504'
 id: 20505 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '20505'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20505'
 id: 20506 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20506'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20506'
 id: 20507 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20507'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20507'
 id: 20508 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20508'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20508'
 id: 20509 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '20509'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20509'
 id: 20510 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '20510'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20510'
 id: 20511 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20511'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20511'
 id: 20512 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '20512'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20512'
 id: 20513 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '20513'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20513'
 id: 20514 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '20514'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20514'
 id: 20515 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20515'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20515'
 id: 20516 // word: 31
UPDATE job_vacancies SET domain_id =  '31' where raw_id = '20516'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20516'
 id: 20517 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20517'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20517'
 id: 20518 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20518'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20518'
 id: 20519 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '20519'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20519'
 id: 20520 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '20520'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20520'
 id: 20521 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '20521'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20521'
 id: 20522 // word: 36
UPDATE job_vacancies SET domain_id =  '36' where raw_id = '20522'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20522'
 id: 20523 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20523'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20523'
 id: 20524 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '20524'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20524'
 id: 20525 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '20525'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20525'
 id: 20526 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '20526'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20526'
 id: 20527 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20527'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20527'
 id: 20528 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20528'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20528'
 id: 20529 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '20529'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20529'
 id: 20530 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20530'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20530'
 id: 20531 // word: 30
UPDATE job_vacancies SET domain_id =  '30' where raw_id = '20531'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20531'
 id: 20532 // word: 9
UPDATE job_vacancies SET domain_id =  '9' where raw_id = '20532'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20532'
 id: 20533 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20533'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20533'
 id: 20534 // word: 73
UPDATE job_vacancies SET domain_id =  '73' where raw_id = '20534'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20534'
 id: 20535 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '20535'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20535'
 id: 20536 // word: 25
UPDATE job_vacancies SET domain_id =  '25' where raw_id = '20536'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20536'
 id: 20537 // word: 26
UPDATE job_vacancies SET domain_id =  '26' where raw_id = '20537'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20537'
 id: 20538 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '20538'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20538'
 id: 20539 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20539'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20539'
 id: 20540 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20540'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20540'
 id: 20541 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '20541'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20541'
 id: 20542 // word: 67
UPDATE job_vacancies SET domain_id =  '67' where raw_id = '20542'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20542'
 id: 20543 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '20543'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20543'
 id: 20544 // word: 69
UPDATE job_vacancies SET domain_id =  '69' where raw_id = '20544'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20544'
 id: 20545 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20545'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20545'
 id: 20546 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '20546'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20546'
 id: 20547 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '20547'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20547'
 id: 20548 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '20548'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20548'
 id: 20549 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '20549'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20549'
 id: 20550 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '20550'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20550'
 id: 20551 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20551'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20551'

 id: 20552 // word: 57
UPDATE job_vacancies SET domain_id =  '57' where raw_id = '20552'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20552'
 id: 20553 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20553'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20553'
 id: 20554 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '20554'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20554'
 id: 20555 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20555'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20555'
 id: 20556 // word: 39
UPDATE job_vacancies SET domain_id =  '39' where raw_id = '20556'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20556'
 id: 20557 // word: 24
UPDATE job_vacancies SET domain_id =  '24' where raw_id = '20557'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20557'
 id: 20558 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '20558'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20558'
 id: 20559 // word: 33
UPDATE job_vacancies SET domain_id =  '33' where raw_id = '20559'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20559'
 id: 20560 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '20560'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20560'
 id: 20561 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20561'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20561'
 id: 20562 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20562'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20562'
 id: 20563 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20563'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20563'
 id: 20564 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '20564'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20564'
 id: 20565 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20565'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20565'
 id: 20566 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '20566'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20566'
 id: 20567 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '20567'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20567'
 id: 20568 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '20568'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20568'
 id: 20569 // word: 12
UPDATE job_vacancies SET domain_id =  '12' where raw_id = '20569'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20569'
 id: 20570 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20570'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20570'
 id: 20571 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '20571'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20571'
 id: 20572 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20572'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20572'
 id: 20573 // word: 10
UPDATE job_vacancies SET domain_id =  '10' where raw_id = '20573'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20573'
 id: 20574 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '20574'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20574'
 id: 20575 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20575'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20575'
 id: 20576 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20576'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20576'
 id: 20577 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '20577'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20577'
 id: 20578 // word: 43
UPDATE job_vacancies SET domain_id =  '43' where raw_id = '20578'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20578'
 id: 20579 // word: 13
UPDATE job_vacancies SET domain_id =  '13' where raw_id = '20579'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20579'
 id: 20580 // word: 29
UPDATE job_vacancies SET domain_id =  '29' where raw_id = '20580'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20580'
 id: 20581 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '20581'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20581'
 id: 20582 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20582'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20582'
 id: 20583 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20583'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20583'
 id: 20584 // word: 17
UPDATE job_vacancies SET domain_id =  '17' where raw_id = '20584'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20584'
 id: 20585 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20585'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20585'
 id: 20586 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '20586'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20586'
 id: 20587 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '20587'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20587'
 id: 20588 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '20588'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20588'
 id: 20589 // word: 38
UPDATE job_vacancies SET domain_id =  '38' where raw_id = '20589'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20589'
 id: 20590 // word: 1
UPDATE job_vacancies SET domain_id =  '1' where raw_id = '20590'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20590'
 id: 20591 // word: 46
UPDATE job_vacancies SET domain_id =  '46' where raw_id = '20591'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20591'
 id: 20592 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '20592'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20592'
 id: 20593 // word: 2
UPDATE job_vacancies SET domain_id =  '2' where raw_id = '20593'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20593'
 id: 20594 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '20594'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20594'
 id: 20595 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20595'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20595'
 id: 20596 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '20596'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20596'
 id: 20597 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '20597'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20597'
 id: 20598 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '20598'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20598'
 id: 20599 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '20599'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20599'
 id: 20600 // word: 64
UPDATE job_vacancies SET domain_id =  '64' where raw_id = '20600'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20600'
 id: 20601 // word: 72
UPDATE job_vacancies SET domain_id =  '72' where raw_id = '20601'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20601'
 id: 20602 // word: 60
UPDATE job_vacancies SET domain_id =  '60' where raw_id = '20602'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20602'
 id: 20603 // word: 65
UPDATE job_vacancies SET domain_id =  '65' where raw_id = '20603'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20603'

 id: 20604 // word: 23
UPDATE job_vacancies SET domain_id =  '23' where raw_id = '20604'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20604'
 id: 20605 // word: 45
UPDATE job_vacancies SET domain_id =  '45' where raw_id = '20605'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20605'
 id: 20606 // word: 41
UPDATE job_vacancies SET domain_id =  '41' where raw_id = '20606'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20606'
 id: 20607 // word: 71
UPDATE job_vacancies SET domain_id =  '71' where raw_id = '20607'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20607'
 id: 20608 // word: 4
UPDATE job_vacancies SET domain_id =  '4' where raw_id = '20608'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20608'
 id: 20609 // word: 8
UPDATE job_vacancies SET domain_id =  '8' where raw_id = '20609'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20609'
 id: 20610 // word: 63
UPDATE job_vacancies SET domain_id =  '63' where raw_id = '20610'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20610'
 id: 20611 // word: 32
UPDATE job_vacancies SET domain_id =  '32' where raw_id = '20611'
UPDATE jobstreet_raws_rc SET domain = '--extracted--'     where id = '20611'
Done : 20611 row(s)