In [2]:
# Connect to DB

import mysql.connector
mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database="pr_scraping_job_vacancy_indonesia_2022_04"
)

mycursor = mydb.cursor()
print('connect')

entity = 'open'

connect

In [4]:
# insert new job_vacancies 

# set query 1
select = ' id, ' + entity
fromdb = 'jobstreet_raws_v2'
where = ' '
group = ' ' 
 
# query 1
mycursor = mydb.cursor()
mycursor.execute("SELECT " + select + " FROM `" + fromdb + "` " + where + group  )
myresult = mycursor.fetchall()
  
print('Start and Please Wait..')
# loop query 1
for x in myresult:  
    idx = str(x[0])
    word = x[1]  
    
    print(word)

    query3 = "UPDATE job_vacancies SET "+entity+" =  '" + word + "' where raw_id = '" + idx + "'"
    print(query3)
    mycursor.execute(query3)
    mydb.commit()  

    query4 = "UPDATE jobstreet_raws_rc SET "+entity+" = '--extracted--'   " 
    where4 = "  where id = '" + idx + "'"  
    print(query4 + where4)
    mycursor.execute(query4 + where4)
    mydb.commit()  
         
print('Done : ' + str(len(myresult)) + ' row(s)')

Start and Please Wait..
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '5'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '6'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '7'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '8'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '9'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '10'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '11'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '12'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '13'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '14'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '15'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '16'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '17'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '18'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '19'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '20'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '21'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '21'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '22'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '22'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '23'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '23'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '24'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '24'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '25'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '25'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '26'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '26'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '27'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '27'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '28'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '28'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '29'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '29'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '30'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '30'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '31'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '31'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '32'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '32'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '33'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '33'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '34'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '34'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '35'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '35'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '36'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '36'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '37'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '37'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '38'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '38'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '39'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '39'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '40'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '40'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '41'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '41'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '42'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '42'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '43'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '43'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '44'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '44'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '45'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '45'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '46'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '46'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '47'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '47'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '48'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '48'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '49'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '49'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '50'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '50'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '51'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '51'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '52'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '52'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '53'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '53'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '54'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '54'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '55'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '55'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '56'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '56'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '57'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '57'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '58'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '58'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '59'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '59'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '60'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '60'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '61'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '61'

2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '62'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '62'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '63'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '63'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '64'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '64'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '65'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '65'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '66'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '66'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '67'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '67'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '68'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '68'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '69'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '69'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '70'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '70'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '71'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '71'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '72'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '72'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '73'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '73'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '74'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '74'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '75'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '75'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '76'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '76'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '77'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '77'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '78'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '78'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '79'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '79'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '80'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '80'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '81'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '81'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '82'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '82'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '83'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '83'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '84'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '84'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '85'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '85'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '86'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '86'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '87'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '87'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '88'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '88'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '89'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '89'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '90'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '90'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '91'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '91'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '92'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '92'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '93'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '93'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '94'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '94'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '95'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '95'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '96'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '96'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '97'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '97'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '98'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '98'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '99'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '99'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '100'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '100'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '101'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '101'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '102'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '102'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '103'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '103'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '104'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '104'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '105'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '105'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '106'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '106'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '107'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '107'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '108'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '108'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '109'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '109'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '110'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '110'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '111'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '111'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '112'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '112'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '113'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '113'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '114'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '114'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '115'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '115'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '116'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '116'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '117'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '117'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '118'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '118'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '119'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '119'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '120'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '120'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '121'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '121'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '122'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '122'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '123'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '123'

2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '124'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '124'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '125'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '125'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '126'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '126'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '127'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '127'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '128'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '128'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '129'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '129'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '130'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '130'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '131'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '131'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '132'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '132'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '133'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '133'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '134'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '134'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '135'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '135'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '136'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '136'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '137'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '137'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '138'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '138'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '139'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '139'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '140'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '140'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '141'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '141'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '142'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '142'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '143'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '143'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '144'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '144'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '145'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '145'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '146'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '146'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '147'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '147'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '148'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '148'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '149'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '149'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '150'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '150'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '151'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '151'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '152'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '152'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '153'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '153'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '154'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '154'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '155'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '155'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '156'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '156'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '157'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '157'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '158'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '158'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '159'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '159'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '160'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '160'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '161'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '161'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '162'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '162'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '163'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '163'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '164'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '164'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '165'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '165'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '166'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '166'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '167'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '167'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '168'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '168'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '169'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '169'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '170'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '170'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '171'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '171'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '172'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '172'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '173'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '173'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '174'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '174'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '175'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '175'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '176'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '176'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '177'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '177'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '178'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '178'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '179'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '179'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '180'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '180'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '181'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '181'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '182'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '182'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '183'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '183'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '184'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '184'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '185'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '185'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '186'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '186'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '187'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '187'

2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '188'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '188'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '189'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '189'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '190'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '190'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '191'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '191'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '192'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '192'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '193'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '193'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '194'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '194'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '195'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '195'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '196'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '196'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '197'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '197'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '198'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '198'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '199'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '199'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '200'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '200'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '201'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '201'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '202'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '202'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '203'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '203'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '204'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '204'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '205'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '205'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '206'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '206'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '207'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '207'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '208'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '208'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '209'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '209'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '210'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '210'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '211'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '211'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '212'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '212'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '213'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '213'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '214'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '214'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '215'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '215'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '216'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '216'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '217'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '217'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '218'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '218'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '219'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '219'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '220'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '220'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '221'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '221'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '222'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '222'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '223'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '223'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '224'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '224'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '225'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '225'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '226'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '226'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '227'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '227'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '228'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '228'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '229'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '229'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '230'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '230'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '231'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '231'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '232'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '232'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '233'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '233'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '234'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '234'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '235'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '235'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '236'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '236'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '237'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '237'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '238'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '238'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '239'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '239'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '240'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '240'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '241'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '241'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '242'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '242'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '243'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '243'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '244'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '244'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '245'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '245'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '246'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '246'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '247'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '247'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '248'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '248'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '249'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '249'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '250'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '250'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '251'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '251'

2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '252'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '252'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '253'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '253'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '254'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '254'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '255'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '255'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '256'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '256'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '257'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '257'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '258'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '258'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '259'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '259'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '260'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '260'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '261'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '261'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '262'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '262'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '263'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '263'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '264'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '264'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '265'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '265'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '266'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '266'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '267'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '267'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '268'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '268'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '269'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '269'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '270'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '270'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '271'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '271'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '272'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '272'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '273'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '273'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '274'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '274'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '275'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '275'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '276'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '276'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '277'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '277'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '278'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '278'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '279'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '279'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '280'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '280'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '281'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '281'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '282'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '282'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '283'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '283'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '284'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '284'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '285'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '285'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '286'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '286'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '287'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '287'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '288'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '288'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '289'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '289'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '290'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '290'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '291'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '291'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '292'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '292'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '293'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '293'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '294'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '294'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '295'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '295'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '296'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '296'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '297'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '297'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '298'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '298'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '299'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '299'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '300'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '300'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '301'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '301'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '302'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '302'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '303'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '303'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '304'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '304'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '305'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '305'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '306'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '306'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '307'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '307'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '308'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '308'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '309'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '309'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '310'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '310'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '311'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '311'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '312'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '312'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '313'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '313'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '314'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '314'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '315'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '315'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '316'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '316'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '317'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '317'

2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '318'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '318'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '319'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '319'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '320'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '320'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '321'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '321'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '322'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '322'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '323'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '323'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '324'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '324'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '325'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '325'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '326'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '326'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '327'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '327'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '328'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '328'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '329'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '329'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '330'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '330'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '331'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '331'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '332'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '332'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '333'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '333'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '334'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '334'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '335'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '335'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '336'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '336'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '337'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '337'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '338'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '338'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '339'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '339'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '340'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '340'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '341'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '341'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '342'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '342'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '343'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '343'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '344'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '344'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '345'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '345'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '346'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '346'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '347'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '347'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '348'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '348'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '349'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '349'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '350'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '350'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '351'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '351'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '352'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '352'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '353'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '353'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '354'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '354'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '355'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '355'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '356'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '356'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '357'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '357'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '358'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '358'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '359'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '359'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '360'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '360'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '361'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '361'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '362'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '362'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '363'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '363'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '364'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '364'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '365'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '365'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '366'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '366'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '367'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '367'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '368'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '368'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '369'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '369'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '370'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '370'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '371'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '371'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '372'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '372'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '373'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '373'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '374'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '374'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '375'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '375'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '376'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '376'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '377'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '377'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '378'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '378'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '379'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '379'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '380'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '380'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '381'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '381'

2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '382'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '382'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '383'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '383'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '384'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '384'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '385'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '385'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '386'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '386'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '387'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '387'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '388'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '388'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '389'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '389'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '390'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '390'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '391'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '391'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '392'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '392'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '393'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '393'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '394'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '394'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '395'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '395'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '396'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '396'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '397'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '397'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '398'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '398'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '399'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '399'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '400'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '400'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '401'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '401'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '402'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '402'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '403'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '403'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '404'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '404'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '405'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '405'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '406'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '406'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '407'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '407'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '408'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '408'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '409'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '409'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '410'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '410'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '411'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '411'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '412'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '412'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '413'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '413'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '414'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '414'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '415'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '415'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '416'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '416'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '417'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '417'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '418'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '418'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '419'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '419'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '420'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '420'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '421'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '421'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '422'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '422'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '423'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '423'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '424'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '424'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '425'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '425'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '426'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '426'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '427'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '427'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '428'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '428'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '429'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '429'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '430'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '430'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '431'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '431'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '432'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '432'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '433'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '433'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '434'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '434'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '435'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '435'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '436'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '436'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '437'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '437'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '438'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '438'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '439'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '439'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '440'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '440'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '441'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '441'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '442'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '442'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '443'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '443'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '444'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '444'

2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '445'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '445'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '446'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '446'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '447'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '447'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '448'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '448'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '449'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '449'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '450'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '450'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '451'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '451'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '452'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '452'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '453'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '453'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '454'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '454'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '455'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '455'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '456'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '456'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '457'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '457'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '458'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '458'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '459'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '459'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '460'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '460'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '461'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '461'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '462'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '462'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '463'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '463'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '464'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '464'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '465'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '465'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '466'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '466'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '467'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '467'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '468'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '468'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '469'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '469'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '470'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '470'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '471'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '471'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '472'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '472'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '473'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '473'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '474'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '474'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '475'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '475'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '476'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '476'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '477'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '477'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '478'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '478'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '479'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '479'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '480'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '480'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '481'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '481'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '482'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '482'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '483'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '483'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '484'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '484'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '485'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '485'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '486'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '486'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '487'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '487'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '488'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '488'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '489'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '489'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '490'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '490'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '491'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '491'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '492'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '492'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '493'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '493'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '494'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '494'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '495'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '495'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '496'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '496'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '497'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '497'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '498'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '498'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '499'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '499'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '500'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '500'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '501'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '501'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '502'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '502'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '503'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '503'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '504'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '504'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '505'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '505'

2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '506'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '506'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '507'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '507'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '508'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '508'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '509'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '509'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '510'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '510'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '511'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '511'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '512'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '512'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '513'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '513'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '514'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '514'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '515'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '515'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '516'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '516'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '517'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '517'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '518'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '518'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '519'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '519'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '520'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '520'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '521'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '521'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '522'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '522'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '523'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '523'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '524'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '524'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '525'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '525'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '526'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '526'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '527'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '527'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '528'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '528'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '529'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '529'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '530'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '530'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '531'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '531'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '532'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '532'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '533'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '533'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '534'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '534'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '535'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '535'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '536'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '536'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '537'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '537'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '538'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '538'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '539'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '539'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '540'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '540'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '541'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '541'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '542'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '542'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '543'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '543'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '544'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '544'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '545'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '545'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '546'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '546'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '547'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '547'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '548'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '548'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '549'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '549'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '550'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '550'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '551'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '551'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '552'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '552'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '553'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '553'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '554'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '554'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '555'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '555'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '556'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '556'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '557'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '557'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '558'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '558'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '559'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '559'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '560'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '560'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '561'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '561'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '562'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '562'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '563'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '563'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '564'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '564'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '565'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '565'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '566'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '566'

2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '567'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '567'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '568'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '568'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '569'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '569'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '570'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '570'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '571'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '571'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '572'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '572'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '573'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '573'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '574'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '574'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '575'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '575'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '576'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '576'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '577'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '577'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '578'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '578'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '579'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '579'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '580'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '580'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '581'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '581'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '582'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '582'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '583'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '583'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '584'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '584'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '585'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '585'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '586'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '586'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '587'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '587'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '588'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '588'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '589'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '589'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '590'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '590'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '591'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '591'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '592'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '592'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '593'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '593'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '594'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '594'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '595'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '595'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '596'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '596'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '597'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '597'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '598'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '598'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '599'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '599'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '600'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '600'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '601'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '601'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '602'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '602'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '603'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '603'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '604'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '604'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '605'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '605'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '606'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '606'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '607'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '607'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '608'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '608'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '609'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '609'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '610'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '610'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '611'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '611'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '612'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '612'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '613'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '613'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '614'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '614'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '615'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '615'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '616'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '616'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '617'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '617'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '618'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '618'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '619'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '619'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '620'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '620'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '621'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '621'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '622'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '622'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '623'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '623'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '624'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '624'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '625'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '625'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '626'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '626'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '627'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '627'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '628'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '628'

2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '629'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '629'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '630'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '630'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '631'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '631'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '632'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '632'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '633'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '633'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '634'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '634'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '635'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '635'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '636'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '636'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '637'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '637'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '638'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '638'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '639'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '639'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '640'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '640'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '641'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '641'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '642'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '642'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '643'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '643'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '644'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '644'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '645'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '645'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '646'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '646'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '647'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '647'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '648'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '648'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '649'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '649'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '650'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '650'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '651'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '651'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '652'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '652'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '653'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '653'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '654'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '654'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '655'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '655'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '656'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '656'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '657'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '657'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '658'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '658'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '659'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '659'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '660'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '660'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '661'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '661'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '662'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '662'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '663'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '663'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '664'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '664'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '665'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '665'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '666'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '666'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '667'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '667'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '668'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '668'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '669'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '669'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '670'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '670'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '671'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '671'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '672'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '672'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '673'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '673'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '674'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '674'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '675'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '675'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '676'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '676'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '677'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '677'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '678'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '678'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '679'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '679'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '680'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '680'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '681'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '681'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '682'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '682'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '683'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '683'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '684'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '684'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '685'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '685'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '686'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '686'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '687'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '687'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '688'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '688'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '689'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '689'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '690'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '690'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '691'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '691'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '692'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '692'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '693'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '693'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '694'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '694'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '695'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '695'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '696'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '696'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '697'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '697'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '698'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '698'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '699'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '699'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '700'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '700'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '701'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '701'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '702'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '702'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '703'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '703'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '704'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '704'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '705'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '705'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '706'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '706'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '707'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '707'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '708'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '708'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '709'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '709'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '710'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '710'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '711'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '711'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '712'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '712'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '713'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '713'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '714'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '714'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '715'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '715'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '716'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '716'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '717'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '717'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '718'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '718'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '719'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '719'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '720'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '720'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '721'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '721'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '722'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '722'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '723'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '723'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '724'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '724'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '725'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '725'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '726'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '726'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '727'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '727'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '728'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '728'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '729'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '729'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '730'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '730'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '731'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '731'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '732'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '732'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '733'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '733'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '734'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '734'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '735'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '735'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '736'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '736'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '737'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '737'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '738'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '738'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '739'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '739'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '740'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '740'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '741'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '741'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '742'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '742'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '743'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '743'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '744'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '744'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '745'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '745'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '746'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '746'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '747'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '747'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '748'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '748'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '749'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '749'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '750'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '750'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '751'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '751'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '752'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '752'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '753'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '753'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '754'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '754'

2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '755'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '755'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '756'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '756'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '757'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '757'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '758'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '758'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '759'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '759'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '760'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '760'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '761'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '761'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '762'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '762'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '763'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '763'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '764'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '764'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '765'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '765'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '766'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '766'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '767'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '767'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '768'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '768'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '769'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '769'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '770'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '770'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '771'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '771'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '772'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '772'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '773'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '773'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '774'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '774'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '775'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '775'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '776'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '776'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '777'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '777'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '778'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '778'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '779'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '779'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '780'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '780'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '781'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '781'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '782'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '782'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '783'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '783'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '784'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '784'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '785'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '785'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '786'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '786'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '787'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '787'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '788'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '788'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '789'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '789'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '790'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '790'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '791'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '791'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '792'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '792'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '793'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '793'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '794'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '794'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '795'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '795'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '796'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '796'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '797'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '797'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '798'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '798'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '799'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '799'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '800'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '800'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '801'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '801'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '802'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '802'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '803'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '803'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '804'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '804'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '805'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '805'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '806'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '806'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '807'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '807'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '808'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '808'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '809'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '809'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '810'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '810'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '811'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '811'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '812'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '812'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '813'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '813'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '814'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '814'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '815'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '815'

2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '816'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '816'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '817'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '817'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '818'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '818'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '819'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '819'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '820'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '820'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '821'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '821'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '822'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '822'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '823'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '823'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '824'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '824'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '825'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '825'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '826'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '826'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '827'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '827'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '828'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '828'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '829'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '829'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '830'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '830'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '831'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '831'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '832'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '832'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '833'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '833'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '834'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '834'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '835'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '835'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '836'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '836'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '837'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '837'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '838'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '838'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '839'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '839'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '840'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '840'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '841'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '841'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '842'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '842'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '843'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '843'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '844'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '844'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '845'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '845'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '846'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '846'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '847'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '847'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '848'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '848'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '849'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '849'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '850'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '850'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '851'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '851'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '852'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '852'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '853'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '853'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '854'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '854'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '855'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '855'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '856'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '856'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '857'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '857'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '858'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '858'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '859'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '859'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '860'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '860'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '861'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '861'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '862'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '862'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '863'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '863'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '864'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '864'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '865'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '865'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '866'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '866'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '867'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '867'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '868'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '868'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '869'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '869'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '870'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '870'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '871'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '871'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '872'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '872'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '873'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '873'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '874'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '874'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '875'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '875'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '876'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '876'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '877'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '877'

2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '878'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '878'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '879'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '879'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '880'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '880'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '881'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '881'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '882'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '882'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '883'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '883'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '884'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '884'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '885'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '885'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '886'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '886'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '887'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '887'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '888'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '888'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '889'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '889'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '890'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '890'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '891'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '891'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '892'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '892'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '893'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '893'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '894'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '894'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '895'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '895'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '896'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '896'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '897'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '897'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '898'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '898'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '899'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '899'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '900'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '900'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '901'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '901'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '902'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '902'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '903'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '903'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '904'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '904'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '905'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '905'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '906'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '906'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '907'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '907'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '908'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '908'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '909'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '909'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '910'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '910'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '911'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '911'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '912'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '912'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '913'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '913'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '914'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '914'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '915'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '915'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '916'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '916'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '917'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '917'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '918'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '918'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '919'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '919'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '920'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '920'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '921'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '921'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '922'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '922'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '923'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '923'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '924'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '924'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '925'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '925'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '926'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '926'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '927'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '927'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '928'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '928'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '929'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '929'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '930'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '930'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '931'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '931'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '932'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '932'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '933'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '933'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '934'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '934'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '935'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '935'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '936'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '936'

2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '937'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '937'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '938'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '938'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '939'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '939'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '940'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '940'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '941'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '941'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '942'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '942'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '943'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '943'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '944'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '944'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '945'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '945'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '946'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '946'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '947'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '947'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '948'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '948'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '949'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '949'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '950'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '950'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '951'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '951'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '952'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '952'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '953'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '953'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '954'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '954'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '955'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '955'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '956'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '956'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '957'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '957'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '958'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '958'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '959'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '959'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '960'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '960'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '961'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '961'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '962'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '962'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '963'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '963'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '964'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '964'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '965'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '965'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '966'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '966'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '967'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '967'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '968'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '968'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '969'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '969'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '970'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '970'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '971'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '971'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '972'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '972'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '973'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '973'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '974'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '974'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '975'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '975'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '976'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '976'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '977'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '977'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '978'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '978'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '979'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '979'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '980'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '980'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '981'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '981'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '982'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '982'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '983'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '983'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '984'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '984'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '985'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '985'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '986'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '986'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '987'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '987'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '988'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '988'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '989'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '989'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '990'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '990'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '991'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '991'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '992'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '992'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '993'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '993'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '994'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '994'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '995'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '995'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '996'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '996'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '997'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '997'

2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '998'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '998'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '999'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '999'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1000'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1000'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1001'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1001'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1002'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1002'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1003'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1003'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1004'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1004'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1005'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1005'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1006'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1006'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1007'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1007'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1008'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1008'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1009'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1009'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1010'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1010'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1011'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1011'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1012'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1012'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1013'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1013'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1014'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1014'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1015'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1015'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1016'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1016'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1017'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1017'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1018'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1018'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1019'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1019'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1020'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1020'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1021'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1021'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1022'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1022'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1023'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1023'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1024'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1024'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1025'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1025'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1026'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1026'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1027'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1027'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1028'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1028'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1029'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1029'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1030'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1030'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1031'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1031'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1032'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1032'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1033'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1033'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1034'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1034'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1035'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1035'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1036'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1036'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1037'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1037'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1038'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1038'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '1039'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1039'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1040'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1040'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1041'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1041'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1042'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1042'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1043'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1043'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1044'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1044'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1045'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1045'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1046'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1046'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1047'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1047'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1048'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1048'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1049'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1049'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1050'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1050'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1051'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1051'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1052'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1052'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1053'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1053'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1054'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1054'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1055'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1055'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1056'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1056'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1057'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1057'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1058'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1058'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1059'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1059'

2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1060'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1060'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1061'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1061'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1062'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1062'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1063'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1063'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1064'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1064'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1065'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1065'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1066'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1066'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1067'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1067'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1068'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1068'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1069'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1069'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1070'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1070'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1071'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1071'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1072'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1072'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1073'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1073'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1074'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1074'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1075'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1075'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1076'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1076'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1077'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1077'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1078'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1078'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1079'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1079'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1080'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1080'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1081'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1081'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1082'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1082'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1083'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1083'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '1084'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1084'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1085'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1085'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1086'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1086'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1087'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1087'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1088'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1088'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1089'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1089'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1090'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1090'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1091'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1091'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1092'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1092'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1093'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1093'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1094'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1094'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1095'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1095'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1096'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1096'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1097'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1097'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1098'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1098'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1099'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1099'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1100'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1100'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1101'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1101'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1102'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1102'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '1103'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1103'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1104'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1104'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1105'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1105'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1106'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1106'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1107'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1107'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1108'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1108'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1109'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1109'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '1110'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1110'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1111'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1111'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1112'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1112'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1113'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1113'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1114'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1114'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1115'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1115'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1116'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1116'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1117'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1117'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1118'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1118'

2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1119'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1119'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1120'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1120'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1121'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1121'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1122'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1122'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1123'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1123'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1124'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1124'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1125'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1125'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1126'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1126'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1127'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1127'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1128'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1128'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1129'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1129'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1130'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1130'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1131'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1131'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1132'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1132'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '1133'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1133'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1134'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1134'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1135'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1135'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1136'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1136'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1137'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1137'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1138'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1138'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1139'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1139'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1140'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1140'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1141'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1141'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1142'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1142'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1143'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1143'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1144'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1144'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '1145'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1145'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1146'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1146'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1147'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1147'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1148'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1148'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1149'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1149'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1150'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1150'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '1151'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1151'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1152'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1152'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1153'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1153'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1154'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1154'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1155'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1155'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1156'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1156'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1157'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1157'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1158'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1158'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1159'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1159'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1160'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1160'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1161'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1161'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1162'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1162'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1163'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1163'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1164'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1164'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1165'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1165'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1166'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1166'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1167'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1167'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1168'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1168'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1169'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1169'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1170'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1170'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1171'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1171'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1172'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1172'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1173'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1173'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1174'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1174'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1175'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1175'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1176'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1176'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1177'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1177'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1178'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1178'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1179'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1179'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1180'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1180'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1181'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1181'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1182'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1182'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1183'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1183'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1184'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1184'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1185'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1185'

2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1186'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1186'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '1187'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1187'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1188'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1188'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1189'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1189'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1190'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1190'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1191'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1191'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1192'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1192'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1193'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1193'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1194'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1194'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1195'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1195'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1196'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1196'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1197'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1197'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1198'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1198'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1199'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1199'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1200'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1200'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1201'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1201'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1202'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1202'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1203'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1203'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1204'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1204'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1205'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1205'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1206'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1206'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1207'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1207'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1208'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1208'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1209'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1209'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1210'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1210'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1211'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1211'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1212'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1212'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1213'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1213'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1214'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1214'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '1215'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1215'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1216'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1216'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1217'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1217'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1218'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1218'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1219'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1219'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1220'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1220'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1221'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1221'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1222'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1222'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1223'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1223'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1224'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1224'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1225'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1225'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1226'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1226'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1227'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1227'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1228'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1228'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1229'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1229'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1230'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1230'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1231'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1231'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1232'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1232'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1233'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1233'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1234'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1234'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1235'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1235'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1236'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1236'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1237'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1237'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1238'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1238'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1239'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1239'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1240'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1240'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1241'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1241'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1242'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1242'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1243'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1243'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1244'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1244'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1245'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1245'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1246'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1246'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '1247'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1247'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1248'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1248'

2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1249'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1249'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1250'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1250'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1251'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1251'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1252'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1252'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1253'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1253'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1254'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1254'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1255'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1255'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '1256'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1256'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1257'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1257'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1258'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1258'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1259'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1259'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1260'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1260'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1261'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1261'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1262'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1262'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1263'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1263'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1264'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1264'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1265'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1265'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1266'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1266'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1267'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1267'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1268'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1268'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1269'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1269'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1270'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1270'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1271'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1271'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1272'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1272'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1273'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1273'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1274'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1274'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1275'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1275'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1276'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1276'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1277'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1277'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1278'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1278'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1279'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1279'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1280'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1280'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1281'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1281'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1282'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1282'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1283'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1283'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1284'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1284'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1285'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1285'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1286'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1286'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1287'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1287'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1288'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1288'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1289'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1289'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '1290'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1290'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1291'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1291'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1292'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1292'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1293'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1293'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1294'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1294'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1295'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1295'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1296'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1296'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1297'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1297'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1298'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1298'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1299'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1299'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1300'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1300'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1301'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1301'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '1302'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1302'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1303'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1303'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1304'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1304'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1305'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1305'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '1306'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1306'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1307'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1307'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1308'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1308'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1309'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1309'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1310'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1310'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1311'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1311'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1312'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1312'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1313'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1313'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1314'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1314'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1315'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1315'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '1316'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1316'

2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1317'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1317'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1318'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1318'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1319'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1319'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1320'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1320'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1321'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1321'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1322'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1322'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1323'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1323'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1324'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1324'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1325'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1325'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1326'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1326'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1327'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1327'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1328'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1328'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1329'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1329'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1330'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1330'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1331'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1331'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1332'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1332'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1333'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1333'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1334'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1334'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1335'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1335'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1336'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1336'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1337'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1337'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1338'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1338'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1339'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1339'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1340'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1340'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1341'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1341'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1342'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1342'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1343'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1343'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1344'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1344'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1345'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1345'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1346'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1346'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1347'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1347'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1348'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1348'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1349'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1349'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1350'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1350'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1351'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1351'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1352'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1352'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1353'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1353'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1354'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1354'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1355'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1355'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1356'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1356'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1357'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1357'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1358'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1358'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1359'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1359'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1360'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1360'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1361'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1361'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1362'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1362'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1363'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1363'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1364'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1364'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1365'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1365'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1366'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1366'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1367'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1367'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1368'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1368'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1369'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1369'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1370'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1370'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1371'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1371'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1372'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1372'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1373'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1373'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1374'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1374'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1375'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1375'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1376'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1376'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1377'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1377'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1378'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1378'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1379'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1379'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1380'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1380'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1381'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1381'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1382'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1382'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1383'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1383'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1384'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1384'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1385'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1385'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1386'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1386'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1387'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1387'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1388'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1388'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1389'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1389'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1390'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1390'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1391'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1391'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1392'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1392'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1393'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1393'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1394'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1394'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1395'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1395'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '1396'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1396'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1397'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1397'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1398'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1398'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1399'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1399'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1400'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1400'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1401'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1401'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1402'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1402'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1403'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1403'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1404'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1404'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1405'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1405'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1406'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1406'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1407'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1407'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1408'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1408'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1409'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1409'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1410'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1410'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1411'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1411'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1412'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1412'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1413'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1413'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1414'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1414'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1415'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1415'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1416'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1416'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1417'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1417'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1418'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1418'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1419'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1419'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1420'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1420'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1421'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1421'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1422'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1422'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1423'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1423'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1424'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1424'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1425'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1425'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1426'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1426'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1427'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1427'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1428'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1428'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1429'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1429'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1430'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1430'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1431'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1431'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1432'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1432'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1433'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1433'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1434'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1434'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1435'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1435'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1436'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1436'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1437'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1437'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1438'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1438'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1439'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1439'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1440'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1440'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1441'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1441'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1442'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1442'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1443'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1443'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '1444'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1444'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1445'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1445'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1446'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1446'

2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1447'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1447'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1448'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1448'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1449'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1449'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1450'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1450'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1451'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1451'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1452'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1452'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1453'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1453'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1454'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1454'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1455'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1455'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1456'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1456'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1457'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1457'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1458'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1458'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1459'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1459'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1460'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1460'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1461'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1461'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1462'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1462'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1463'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1463'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1464'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1464'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1465'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1465'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1466'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1466'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1467'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1467'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1468'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1468'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1469'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1469'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1470'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1470'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1471'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1471'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1472'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1472'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1473'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1473'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1474'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1474'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1475'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1475'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1476'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1476'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1477'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1477'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1478'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1478'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1479'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1479'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1480'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1480'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1481'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1481'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '1482'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1482'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1483'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1483'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1484'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1484'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1485'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1485'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1486'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1486'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1487'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1487'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1488'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1488'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1489'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1489'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1490'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1490'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1491'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1491'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1492'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1492'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1493'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1493'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1494'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1494'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1495'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1495'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1496'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1496'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1497'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1497'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1498'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1498'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1499'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1499'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1500'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1500'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1501'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1501'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1502'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1502'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1503'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1503'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1504'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1504'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1505'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1505'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1506'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1506'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1507'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1507'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1508'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1508'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1509'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1509'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1510'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1510'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1511'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1511'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1512'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1512'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1513'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1513'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1514'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1514'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1515'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1515'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1516'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1516'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1517'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1517'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1518'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1518'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1519'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1519'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '1520'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1520'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1521'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1521'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1522'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1522'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1523'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1523'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1524'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1524'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1525'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1525'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1526'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1526'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1527'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1527'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1528'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1528'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1529'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1529'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '1530'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1530'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1531'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1531'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1532'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1532'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1533'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1533'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1534'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1534'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1535'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1535'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1536'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1536'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1537'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1537'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1538'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1538'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '1539'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1539'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1540'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1540'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1541'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1541'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1542'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1542'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1543'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1543'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1544'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1544'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1545'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1545'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1546'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1546'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1547'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1547'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1548'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1548'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1549'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1549'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1550'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1550'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1551'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1551'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1552'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1552'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1553'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1553'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1554'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1554'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1555'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1555'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '1556'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1556'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1557'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1557'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1558'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1558'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1559'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1559'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1560'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1560'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1561'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1561'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1562'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1562'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1563'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1563'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1564'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1564'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1565'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1565'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1566'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1566'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1567'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1567'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1568'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1568'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1569'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1569'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1570'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1570'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '1571'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1571'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1572'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1572'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1573'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1573'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1574'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1574'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1575'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1575'

2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1576'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1576'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1577'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1577'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1578'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1578'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1579'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1579'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1580'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1580'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1581'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1581'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1582'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1582'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1583'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1583'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1584'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1584'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '1585'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1585'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1586'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1586'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1587'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1587'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1588'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1588'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1589'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1589'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1590'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1590'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '1591'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1591'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1592'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1592'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1593'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1593'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1594'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1594'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1595'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1595'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1596'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1596'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1597'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1597'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1598'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1598'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1599'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1599'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1600'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1600'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1601'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1601'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1602'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1602'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1603'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1603'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '1604'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1604'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1605'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1605'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1606'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1606'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1607'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1607'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1608'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1608'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1609'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1609'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1610'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1610'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1611'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1611'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '1612'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1612'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1613'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1613'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1614'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1614'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1615'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1615'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1616'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1616'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1617'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1617'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1618'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1618'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1619'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1619'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1620'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1620'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1621'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1621'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1622'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1622'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1623'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1623'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1624'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1624'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1625'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1625'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1626'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1626'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1627'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1627'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1628'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1628'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1629'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1629'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1630'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1630'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1631'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1631'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1632'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1632'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1633'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1633'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1634'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1634'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1635'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1635'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1636'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1636'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1637'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1637'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1638'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1638'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1639'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1639'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1640'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1640'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1641'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1641'

2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1642'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1642'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1643'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1643'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1644'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1644'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1645'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1645'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1646'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1646'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1647'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1647'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1648'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1648'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1649'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1649'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1650'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1650'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1651'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1651'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1652'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1652'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1653'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1653'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1654'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1654'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1655'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1655'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1656'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1656'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1657'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1657'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1658'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1658'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1659'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1659'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1660'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1660'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '1661'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1661'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '1662'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1662'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1663'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1663'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1664'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1664'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1665'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1665'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1666'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1666'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1667'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1667'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1668'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1668'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1669'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1669'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '1670'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1670'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1671'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1671'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1672'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1672'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1673'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1673'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1674'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1674'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1675'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1675'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1676'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1676'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1677'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1677'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1678'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1678'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1679'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1679'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1680'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1680'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1681'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1681'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1682'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1682'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1683'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1683'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1684'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1684'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1685'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1685'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1686'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1686'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1687'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1687'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1688'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1688'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1689'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1689'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1690'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1690'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1691'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1691'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1692'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1692'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1693'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1693'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '1694'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1694'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1695'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1695'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '1696'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1696'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1697'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1697'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '1698'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1698'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1699'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1699'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1700'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1700'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1701'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1701'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1702'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1702'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1703'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1703'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1704'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1704'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1705'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1705'

2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1706'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1706'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1707'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1707'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '1708'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1708'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1709'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1709'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1710'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1710'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1711'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1711'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1712'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1712'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1713'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1713'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1714'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1714'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1715'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1715'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1716'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1716'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1717'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1717'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1718'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1718'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1719'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1719'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1720'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1720'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1721'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1721'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1722'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1722'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1723'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1723'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1724'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1724'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1725'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1725'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1726'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1726'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1727'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1727'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1728'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1728'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1729'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1729'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1730'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1730'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1731'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1731'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1732'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1732'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1733'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1733'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1734'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1734'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1735'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1735'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1736'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1736'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1737'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1737'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1738'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1738'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1739'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1739'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1740'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1740'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1741'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1741'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1742'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1742'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '1743'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1743'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1744'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1744'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1745'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1745'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1746'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1746'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1747'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1747'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1748'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1748'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1749'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1749'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1750'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1750'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1751'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1751'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1752'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1752'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1753'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1753'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1754'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1754'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1755'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1755'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1756'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1756'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1757'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1757'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1758'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1758'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1759'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1759'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1760'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1760'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1761'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1761'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1762'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1762'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1763'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1763'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1764'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1764'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1765'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1765'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1766'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1766'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1767'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1767'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1768'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1768'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1769'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1769'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1770'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1770'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1771'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1771'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1772'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1772'

2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1773'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1773'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1774'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1774'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1775'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1775'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1776'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1776'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1777'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1777'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '1778'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1778'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1779'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1779'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1780'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1780'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1781'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1781'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1782'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1782'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '1783'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1783'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1784'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1784'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1785'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1785'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1786'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1786'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1787'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1787'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1788'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1788'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1789'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1789'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1790'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1790'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1791'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1791'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1792'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1792'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1793'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1793'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1794'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1794'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1795'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1795'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1796'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1796'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1797'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1797'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1798'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1798'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1799'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1799'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1800'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1800'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1801'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1801'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1802'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1802'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1803'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1803'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1804'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1804'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1805'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1805'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1806'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1806'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1807'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1807'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1808'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1808'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1809'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1809'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1810'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1810'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1811'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1811'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1812'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1812'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1813'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1813'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1814'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1814'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1815'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1815'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1816'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1816'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1817'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1817'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '1818'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1818'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1819'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1819'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1820'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1820'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1821'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1821'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1822'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1822'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1823'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1823'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1824'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1824'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1825'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1825'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1826'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1826'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1827'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1827'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1828'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1828'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1829'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1829'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1830'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1830'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1831'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1831'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '1832'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1832'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1833'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1833'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1834'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1834'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1835'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1835'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1836'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1836'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1837'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1837'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1838'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1838'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1839'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1839'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1840'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1840'

2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1841'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1841'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1842'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1842'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1843'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1843'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1844'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1844'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1845'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1845'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1846'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1846'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1847'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1847'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1848'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1848'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1849'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1849'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1850'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1850'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1851'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1851'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1852'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1852'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1853'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1853'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1854'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1854'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1855'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1855'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1856'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1856'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1857'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1857'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1858'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1858'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1859'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1859'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1860'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1860'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1861'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1861'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1862'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1862'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1863'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1863'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1864'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1864'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1865'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1865'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1866'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1866'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1867'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1867'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1868'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1868'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1869'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1869'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1870'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1870'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1871'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1871'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1872'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1872'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1873'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1873'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1874'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1874'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1875'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1875'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1876'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1876'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1877'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1877'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1878'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1878'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1879'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1879'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1880'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1880'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1881'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1881'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1882'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1882'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1883'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1883'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1884'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1884'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1885'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1885'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1886'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1886'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1887'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1887'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1888'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1888'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1889'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1889'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1890'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1890'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1891'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1891'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1892'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1892'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1893'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1893'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1894'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1894'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1895'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1895'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1896'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1896'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1897'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1897'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1898'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1898'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1899'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1899'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1900'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1900'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1901'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1901'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1902'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1902'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1903'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1903'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1904'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1904'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1905'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1905'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1906'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1906'

2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1907'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1907'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1908'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1908'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1909'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1909'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1910'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1910'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1911'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1911'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1912'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1912'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1913'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1913'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1914'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1914'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1915'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1915'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1916'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1916'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1917'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1917'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1918'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1918'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1919'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1919'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1920'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1920'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1921'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1921'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1922'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1922'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1923'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1923'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1924'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1924'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1925'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1925'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1926'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1926'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1927'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1927'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1928'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1928'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1929'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1929'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1930'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1930'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1931'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1931'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1932'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1932'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1933'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1933'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1934'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1934'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1935'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1935'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1936'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1936'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1937'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1937'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '1938'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1938'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1939'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1939'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1940'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1940'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1941'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1941'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1942'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1942'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1943'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1943'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1944'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1944'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1945'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1945'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1946'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1946'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1947'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1947'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1948'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1948'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1949'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1949'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1950'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1950'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1951'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1951'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1952'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1952'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1953'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1953'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1954'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1954'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1955'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1955'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1956'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1956'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1957'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1957'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1958'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1958'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1959'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1959'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1960'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1960'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1961'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1961'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '1962'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1962'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1963'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1963'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '1964'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1964'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1965'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1965'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1966'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1966'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1967'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1967'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1968'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1968'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1969'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1969'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1970'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1970'

2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1971'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1971'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1972'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1972'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1973'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1973'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1974'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1974'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1975'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1975'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1976'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1976'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1977'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1977'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1978'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1978'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '1979'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1979'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1980'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1980'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1981'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1981'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1982'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1982'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1983'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1983'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1984'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1984'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1985'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1985'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1986'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1986'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1987'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1987'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '1988'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1988'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1989'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1989'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1990'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1990'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '1991'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1991'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '1992'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1992'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1993'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1993'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1994'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1994'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1995'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1995'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '1996'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1996'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1997'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1997'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '1998'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1998'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '1999'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '1999'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2000'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2000'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2001'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2001'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2002'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2002'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2003'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2003'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '2004'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2004'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '2005'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2005'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2006'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2006'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2007'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2007'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2008'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2008'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2009'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2009'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2010'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2010'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2011'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2011'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2012'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2012'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2013'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2013'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2014'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2014'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2015'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2015'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2016'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2016'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2017'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2017'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2018'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2018'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2019'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2019'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2020'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2020'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2021'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2021'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2022'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2022'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2023'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2023'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2024'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2024'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2025'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2025'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2026'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2026'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2027'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2027'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2028'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2028'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2029'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2029'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2030'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2030'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2031'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2031'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2032'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2032'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2033'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2033'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2034'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2034'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2035'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2035'

2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2036'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2036'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2037'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2037'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2038'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2038'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '2039'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2039'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '2040'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2040'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2041'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2041'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2042'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2042'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2043'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2043'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2044'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2044'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2045'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2045'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2046'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2046'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2047'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2047'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2048'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2048'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2049'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2049'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2050'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2050'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2051'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2051'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2052'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2052'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2053'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2053'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2054'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2054'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2055'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2055'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2056'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2056'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2057'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2057'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2058'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2058'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2059'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2059'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2060'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2060'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2061'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2061'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2062'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2062'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2063'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2063'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2064'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2064'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2065'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2065'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2066'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2066'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2067'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2067'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2068'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2068'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2069'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2069'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2070'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2070'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '2071'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2071'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2072'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2072'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2073'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2073'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2074'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2074'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2075'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2075'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2076'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2076'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2077'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2077'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2078'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2078'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2079'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2079'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2080'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2080'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2081'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2081'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2082'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2082'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2083'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2083'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2084'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2084'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2085'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2085'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2086'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2086'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2087'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2087'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2088'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2088'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2089'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2089'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '2090'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2090'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2091'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2091'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '2092'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2092'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2093'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2093'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2094'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2094'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2095'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2095'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2096'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2096'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2097'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2097'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2098'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2098'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2099'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2099'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '2100'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2100'

2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2101'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2101'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2102'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2102'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2103'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2103'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2104'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2104'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2105'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2105'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2106'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2106'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2107'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2107'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2108'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2108'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2109'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2109'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2110'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2110'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2111'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2111'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2112'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2112'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2113'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2113'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2114'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2114'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '2115'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2115'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2116'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2116'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2117'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2117'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2118'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2118'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2119'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2119'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2120'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2120'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2121'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2121'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '2122'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2122'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2123'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2123'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2124'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2124'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2125'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2125'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '2126'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2126'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2127'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2127'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2128'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2128'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2129'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2129'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2130'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2130'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2131'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2131'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2132'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2132'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2133'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2133'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2134'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2134'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2135'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2135'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '2136'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2136'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2137'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2137'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2138'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2138'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2139'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2139'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2140'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2140'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2141'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2141'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '2142'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2142'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2143'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2143'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2144'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2144'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2145'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2145'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2146'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2146'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2147'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2147'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2148'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2148'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2149'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2149'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2150'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2150'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2151'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2151'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2152'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2152'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2153'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2153'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2154'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2154'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2155'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2155'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2156'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2156'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2157'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2157'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2158'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2158'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2159'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2159'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2160'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2160'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2161'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2161'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2162'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2162'

2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2163'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2163'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2164'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2164'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '2165'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2165'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2166'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2166'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2167'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2167'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2168'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2168'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2169'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2169'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2170'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2170'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '2171'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2171'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2172'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2172'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2173'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2173'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2174'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2174'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2175'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2175'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2176'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2176'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2177'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2177'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2178'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2178'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2179'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2179'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2180'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2180'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2181'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2181'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2182'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2182'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2183'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2183'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2184'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2184'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2185'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2185'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2186'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2186'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2187'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2187'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2188'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2188'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2189'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2189'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2190'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2190'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2191'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2191'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2192'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2192'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2193'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2193'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2194'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2194'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2195'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2195'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2196'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2196'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '2197'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2197'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2198'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2198'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2199'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2199'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2200'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2200'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2201'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2201'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2202'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2202'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2203'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2203'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2204'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2204'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2205'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2205'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2206'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2206'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2207'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2207'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2208'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2208'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2209'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2209'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2210'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2210'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2211'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2211'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2212'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2212'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2213'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2213'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2214'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2214'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2215'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2215'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2216'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2216'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2217'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2217'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2218'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2218'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2219'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2219'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2220'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2220'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2221'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2221'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2222'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2222'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2223'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2223'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2224'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2224'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2225'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2225'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2226'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2226'

2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2227'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2227'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2228'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2228'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2229'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2229'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2230'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2230'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2231'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2231'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2232'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2232'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2233'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2233'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2234'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2234'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2235'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2235'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2236'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2236'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2237'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2237'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2238'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2238'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '2239'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2239'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2240'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2240'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2241'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2241'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2242'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2242'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2243'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2243'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2244'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2244'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2245'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2245'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2246'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2246'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2247'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2247'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2248'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2248'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2249'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2249'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2250'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2250'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2251'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2251'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2252'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2252'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2253'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2253'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2254'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2254'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2255'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2255'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2256'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2256'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2257'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2257'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '2258'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2258'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2259'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2259'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2260'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2260'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2261'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2261'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2262'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2262'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2263'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2263'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2264'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2264'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2265'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2265'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2266'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2266'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2267'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2267'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2268'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2268'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2269'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2269'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2270'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2270'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2271'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2271'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2272'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2272'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2273'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2273'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2274'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2274'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2275'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2275'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2276'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2276'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2277'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2277'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2278'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2278'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2279'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2279'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2280'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2280'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2281'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2281'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2282'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2282'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2283'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2283'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2284'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2284'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2285'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2285'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2286'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2286'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2287'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2287'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2288'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2288'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2289'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2289'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2290'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2290'

2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2291'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2291'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2292'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2292'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2293'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2293'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2294'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2294'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2295'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2295'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '2296'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2296'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2297'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2297'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2298'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2298'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2299'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2299'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2300'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2300'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2301'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2301'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2302'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2302'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2303'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2303'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2304'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2304'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2305'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2305'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2306'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2306'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2307'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2307'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2308'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2308'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2309'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2309'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2310'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2310'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2311'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2311'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2312'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2312'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '2313'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2313'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2314'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2314'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2315'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2315'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2316'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2316'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '2317'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2317'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2318'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2318'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2319'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2319'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2320'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2320'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2321'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2321'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2322'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2322'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2323'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2323'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2324'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2324'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2325'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2325'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2326'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2326'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2327'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2327'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2328'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2328'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2329'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2329'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '2330'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2330'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2331'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2331'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2332'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2332'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2333'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2333'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2334'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2334'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2335'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2335'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2336'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2336'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2337'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2337'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2338'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2338'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2339'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2339'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '2340'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2340'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2341'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2341'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2342'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2342'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2343'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2343'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2344'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2344'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2345'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2345'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2346'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2346'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2347'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2347'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2348'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2348'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2349'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2349'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2350'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2350'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2351'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2351'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2352'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2352'

2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2353'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2353'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2354'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2354'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2355'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2355'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2356'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2356'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2357'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2357'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2358'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2358'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2359'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2359'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2360'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2360'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2361'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2361'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '2362'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2362'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2363'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2363'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2364'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2364'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2365'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2365'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2366'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2366'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '2367'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2367'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2368'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2368'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2369'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2369'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2370'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2370'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2371'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2371'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2372'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2372'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2373'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2373'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2374'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2374'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2375'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2375'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2376'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2376'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2377'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2377'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2378'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2378'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2379'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2379'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2380'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2380'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2381'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2381'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2382'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2382'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2383'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2383'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2384'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2384'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2385'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2385'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2386'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2386'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2387'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2387'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2388'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2388'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2389'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2389'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2390'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2390'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2391'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2391'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2392'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2392'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2393'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2393'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2394'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2394'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '2395'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2395'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2396'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2396'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2397'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2397'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2398'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2398'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2399'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2399'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2400'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2400'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2401'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2401'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2402'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2402'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2403'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2403'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2404'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2404'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2405'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2405'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2406'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2406'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2407'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2407'

2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2408'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2408'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2409'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2409'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2410'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2410'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2411'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2411'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2412'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2412'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2413'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2413'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2414'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2414'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2415'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2415'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2416'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2416'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2417'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2417'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2418'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2418'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2419'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2419'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2420'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2420'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2421'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2421'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '2422'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2422'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2423'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2423'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2424'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2424'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2425'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2425'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2426'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2426'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '2427'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2427'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2428'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2428'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2429'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2429'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2430'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2430'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2431'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2431'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2432'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2432'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2433'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2433'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '2434'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2434'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2435'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2435'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2436'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2436'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2437'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2437'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2438'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2438'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2439'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2439'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2440'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2440'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2441'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2441'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2442'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2442'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2443'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2443'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2444'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2444'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2445'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2445'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2446'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2446'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2447'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2447'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2448'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2448'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2449'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2449'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2450'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2450'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2451'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2451'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2452'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2452'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2453'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2453'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2454'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2454'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2455'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2455'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2456'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2456'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2457'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2457'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2458'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2458'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2459'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2459'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2460'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2460'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2461'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2461'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2462'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2462'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2463'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2463'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2464'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2464'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2465'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2465'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2466'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2466'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2467'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2467'

2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2468'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2468'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2469'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2469'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '2470'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2470'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2471'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2471'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2472'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2472'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2473'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2473'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2474'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2474'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2475'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2475'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2476'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2476'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2477'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2477'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2478'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2478'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2479'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2479'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2480'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2480'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2481'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2481'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2482'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2482'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2483'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2483'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2484'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2484'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2485'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2485'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2486'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2486'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2487'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2487'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2488'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2488'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2489'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2489'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2490'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2490'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2491'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2491'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2492'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2492'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2493'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2493'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2494'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2494'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2495'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2495'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2496'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2496'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2497'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2497'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2498'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2498'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2499'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2499'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2500'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2500'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2501'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2501'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2502'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2502'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '2503'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2503'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2504'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2504'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2505'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2505'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2506'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2506'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2507'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2507'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2508'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2508'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2509'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2509'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2510'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2510'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2511'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2511'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2512'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2512'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2513'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2513'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2514'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2514'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2515'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2515'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2516'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2516'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2517'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2517'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2518'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2518'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2519'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2519'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2520'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2520'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '2521'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2521'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2522'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2522'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2523'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2523'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2524'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2524'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2525'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2525'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2526'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2526'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2527'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2527'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2528'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2528'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2529'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2529'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2530'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2530'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2531'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2531'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2532'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2532'

2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2533'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2533'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2534'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2534'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2535'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2535'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2536'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2536'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2537'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2537'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2538'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2538'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2539'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2539'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2540'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2540'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '2541'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2541'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2542'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2542'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2543'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2543'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2544'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2544'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2545'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2545'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2546'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2546'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2547'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2547'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '2548'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2548'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2549'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2549'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2550'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2550'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2551'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2551'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2552'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2552'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2553'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2553'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2554'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2554'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2555'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2555'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2556'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2556'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2557'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2557'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2558'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2558'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2559'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2559'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2560'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2560'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2561'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2561'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2562'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2562'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2563'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2563'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2564'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2564'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2565'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2565'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2566'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2566'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2567'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2567'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '2568'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2568'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2569'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2569'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2570'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2570'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2571'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2571'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2572'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2572'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2573'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2573'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2574'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2574'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2575'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2575'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2576'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2576'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '2577'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2577'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2578'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2578'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2579'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2579'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2580'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2580'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2581'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2581'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2582'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2582'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2583'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2583'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2584'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2584'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2585'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2585'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2586'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2586'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2587'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2587'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2588'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2588'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2589'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2589'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2590'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2590'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2591'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2591'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2592'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2592'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2593'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2593'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2594'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2594'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2595'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2595'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2596'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2596'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2597'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2597'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2598'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2598'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2599'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2599'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2600'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2600'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2601'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2601'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2602'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2602'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2603'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2603'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2604'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2604'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2605'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2605'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2606'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2606'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2607'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2607'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2608'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2608'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2609'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2609'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2610'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2610'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2611'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2611'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2612'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2612'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2613'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2613'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2614'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2614'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2615'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2615'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2616'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2616'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2617'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2617'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2618'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2618'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2619'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2619'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2620'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2620'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2621'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2621'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2622'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2622'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2623'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2623'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2624'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2624'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2625'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2625'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2626'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2626'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2627'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2627'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '2628'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2628'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2629'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2629'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2630'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2630'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2631'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2631'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2632'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2632'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2633'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2633'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2634'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2634'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2635'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2635'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2636'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2636'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2637'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2637'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2638'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2638'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2639'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2639'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2640'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2640'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2641'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2641'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2642'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2642'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2643'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2643'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2644'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2644'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2645'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2645'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2646'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2646'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2647'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2647'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2648'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2648'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2649'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2649'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2650'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2650'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2651'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2651'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2652'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2652'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2653'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2653'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2654'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2654'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2655'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2655'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2656'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2656'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2657'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2657'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2658'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2658'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2659'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2659'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2660'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2660'

2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2661'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2661'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2662'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2662'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2663'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2663'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2664'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2664'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2665'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2665'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '2666'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2666'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2667'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2667'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2668'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2668'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2669'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2669'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2670'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2670'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2671'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2671'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2672'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2672'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2673'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2673'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2674'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2674'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2675'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2675'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2676'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2676'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2677'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2677'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2678'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2678'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2679'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2679'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2680'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2680'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '2681'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2681'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2682'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2682'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '2683'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2683'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2684'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2684'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2685'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2685'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2686'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2686'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2687'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2687'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2688'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2688'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2689'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2689'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2690'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2690'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2691'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2691'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2692'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2692'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2693'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2693'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2694'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2694'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2695'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2695'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '2696'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2696'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2697'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2697'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2698'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2698'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2699'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2699'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '2700'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2700'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '2701'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2701'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2702'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2702'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2703'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2703'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2704'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2704'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2705'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2705'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2706'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2706'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2707'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2707'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2708'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2708'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2709'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2709'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2710'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2710'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2711'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2711'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2712'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2712'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2713'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2713'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2714'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2714'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '2715'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2715'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2716'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2716'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2717'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2717'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '2718'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2718'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2719'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2719'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2720'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2720'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2721'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2721'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2722'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2722'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2723'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2723'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2724'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2724'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2725'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2725'

2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2726'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2726'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '2727'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2727'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2728'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2728'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2729'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2729'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2730'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2730'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '2731'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2731'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2732'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2732'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '2733'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2733'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2734'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2734'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2735'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2735'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '2736'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2736'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2737'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2737'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2738'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2738'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2739'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2739'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '2740'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2740'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2741'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2741'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2742'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2742'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2743'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2743'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2744'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2744'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '2745'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2745'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2746'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2746'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2747'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2747'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2748'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2748'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2749'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2749'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2750'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2750'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2751'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2751'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2752'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2752'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2753'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2753'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2754'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2754'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2755'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2755'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '2756'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2756'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2757'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2757'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2758'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2758'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2759'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2759'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2760'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2760'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2761'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2761'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2762'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2762'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2763'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2763'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2764'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2764'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2765'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2765'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2766'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2766'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2767'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2767'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2768'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2768'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2769'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2769'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2770'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2770'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2771'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2771'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2772'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2772'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2773'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2773'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2774'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2774'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2775'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2775'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2776'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2776'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2777'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2777'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2778'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2778'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2779'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2779'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2780'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2780'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2781'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2781'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2782'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2782'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '2783'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2783'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2784'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2784'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2785'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2785'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2786'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2786'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2787'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2787'

2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '2788'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2788'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2789'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2789'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2790'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2790'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2791'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2791'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2792'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2792'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '2793'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2793'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2794'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2794'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2795'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2795'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2796'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2796'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2797'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2797'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2798'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2798'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2799'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2799'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2800'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2800'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2801'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2801'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2802'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2802'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2803'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2803'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '2804'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2804'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2805'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2805'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2806'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2806'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2807'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2807'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2808'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2808'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2809'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2809'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2810'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2810'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2811'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2811'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2812'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2812'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2813'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2813'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2814'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2814'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2815'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2815'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2816'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2816'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2817'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2817'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '2818'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2818'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2819'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2819'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2820'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2820'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2821'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2821'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2822'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2822'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '2823'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2823'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2824'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2824'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2825'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2825'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2826'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2826'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2827'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2827'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2828'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2828'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2829'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2829'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2830'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2830'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2831'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2831'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2832'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2832'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '2833'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2833'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2834'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2834'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2835'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2835'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2836'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2836'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2837'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2837'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '2838'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2838'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2839'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2839'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2840'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2840'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '2841'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2841'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2842'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2842'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2843'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2843'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2844'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2844'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2845'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2845'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2846'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2846'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2847'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2847'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '2848'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2848'

2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2849'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2849'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2850'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2850'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2851'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2851'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2852'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2852'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2853'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2853'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2854'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2854'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2855'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2855'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2856'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2856'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2857'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2857'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '2858'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2858'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2859'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2859'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2860'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2860'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2861'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2861'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2862'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2862'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2863'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2863'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2864'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2864'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2865'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2865'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2866'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2866'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2867'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2867'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '2868'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2868'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2869'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2869'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2870'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2870'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2871'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2871'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '2872'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2872'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2873'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2873'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2874'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2874'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2875'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2875'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2876'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2876'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '2877'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2877'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2878'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2878'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2879'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2879'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2880'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2880'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2881'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2881'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2882'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2882'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2883'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2883'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2884'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2884'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2885'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2885'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2886'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2886'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2887'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2887'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2888'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2888'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2889'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2889'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '2890'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2890'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2891'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2891'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2892'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2892'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2893'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2893'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2894'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2894'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2895'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2895'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '2896'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2896'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2897'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2897'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2898'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2898'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2899'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2899'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2900'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2900'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2901'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2901'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2902'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2902'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2903'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2903'

2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2904'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2904'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2905'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2905'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2906'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2906'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2907'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2907'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2908'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2908'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2909'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2909'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2910'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2910'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2911'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2911'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2912'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2912'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2913'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2913'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2914'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2914'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2915'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2915'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2916'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2916'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2917'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2917'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2918'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2918'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2919'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2919'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2920'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2920'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2921'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2921'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2922'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2922'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2923'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2923'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '2924'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2924'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2925'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2925'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2926'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2926'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2927'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2927'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2928'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2928'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2929'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2929'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2930'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2930'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2931'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2931'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2932'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2932'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2933'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2933'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2934'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2934'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2935'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2935'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '2936'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2936'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '2937'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2937'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2938'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2938'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2939'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2939'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2940'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2940'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '2941'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2941'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2942'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2942'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2943'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2943'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2944'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2944'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2945'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2945'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2946'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2946'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2947'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2947'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2948'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2948'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2949'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2949'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2950'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2950'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2951'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2951'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '2952'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2952'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2953'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2953'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2954'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2954'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2955'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2955'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2956'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2956'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '2957'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2957'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2958'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2958'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '2959'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2959'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2960'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2960'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2961'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2961'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2962'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2962'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2963'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2963'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2964'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2964'

2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2965'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2965'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2966'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2966'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2967'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2967'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2968'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2968'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '2969'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2969'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2970'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2970'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2971'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2971'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2972'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2972'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '2973'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2973'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2974'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2974'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2975'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2975'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2976'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2976'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2977'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2977'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2978'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2978'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2979'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2979'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2980'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2980'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2981'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2981'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2982'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2982'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2983'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2983'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2984'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2984'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '2985'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2985'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2986'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2986'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2987'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2987'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2988'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2988'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2989'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2989'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2990'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2990'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2991'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2991'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '2992'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2992'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '2993'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2993'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2994'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2994'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '2995'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2995'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2996'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2996'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '2997'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2997'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '2998'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2998'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '2999'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '2999'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3000'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3000'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3001'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3001'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3002'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3002'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3003'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3003'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3004'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3004'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3005'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3005'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3006'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3006'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3007'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3007'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3008'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3008'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '3009'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3009'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3010'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3010'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3011'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3011'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3012'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3012'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3013'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3013'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3014'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3014'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3015'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3015'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3016'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3016'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3017'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3017'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3018'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3018'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3019'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3019'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3020'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3020'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3021'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3021'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3022'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3022'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3023'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3023'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3024'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3024'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3025'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3025'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3026'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3026'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3027'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3027'

2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3028'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3028'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3029'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3029'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3030'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3030'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3031'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3031'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3032'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3032'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3033'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3033'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3034'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3034'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3035'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3035'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3036'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3036'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3037'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3037'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '3038'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3038'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3039'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3039'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3040'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3040'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3041'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3041'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3042'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3042'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3043'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3043'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3044'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3044'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3045'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3045'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3046'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3046'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3047'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3047'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3048'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3048'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3049'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3049'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3050'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3050'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3051'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3051'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3052'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3052'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3053'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3053'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3054'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3054'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3055'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3055'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3056'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3056'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3057'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3057'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3058'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3058'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3059'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3059'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3060'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3060'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3061'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3061'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3062'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3062'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3063'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3063'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3064'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3064'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3065'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3065'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3066'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3066'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3067'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3067'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3068'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3068'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3069'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3069'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3070'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3070'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3071'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3071'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3072'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3072'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3073'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3073'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3074'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3074'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3075'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3075'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3076'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3076'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3077'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3077'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3078'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3078'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3079'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3079'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3080'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3080'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3081'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3081'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3082'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3082'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3083'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3083'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3084'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3084'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3085'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3085'

2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3086'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3086'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3087'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3087'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3088'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3088'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3089'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3089'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3090'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3090'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3091'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3091'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3092'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3092'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3093'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3093'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3094'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3094'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3095'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3095'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3096'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3096'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3097'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3097'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3098'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3098'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3099'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3099'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3100'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3100'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3101'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3101'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '3102'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3102'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3103'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3103'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3104'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3104'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3105'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3105'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3106'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3106'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3107'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3107'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3108'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3108'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3109'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3109'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3110'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3110'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3111'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3111'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3112'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3112'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3113'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3113'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3114'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3114'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3115'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3115'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3116'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3116'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3117'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3117'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3118'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3118'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '3119'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3119'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3120'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3120'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3121'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3121'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3122'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3122'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3123'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3123'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3124'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3124'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3125'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3125'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3126'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3126'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3127'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3127'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3128'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3128'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3129'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3129'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3130'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3130'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3131'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3131'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3132'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3132'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3133'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3133'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3134'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3134'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3135'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3135'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3136'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3136'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3137'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3137'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3138'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3138'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3139'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3139'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3140'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3140'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3141'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3141'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3142'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3142'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3143'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3143'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3144'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3144'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3145'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3145'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3146'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3146'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3147'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3147'

2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3148'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3148'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3149'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3149'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3150'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3150'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3151'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3151'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3152'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3152'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3153'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3153'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3154'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3154'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3155'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3155'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '3156'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3156'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3157'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3157'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3158'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3158'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3159'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3159'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3160'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3160'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3161'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3161'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3162'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3162'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3163'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3163'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3164'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3164'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3165'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3165'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3166'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3166'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3167'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3167'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3168'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3168'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3169'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3169'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3170'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3170'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3171'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3171'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3172'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3172'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3173'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3173'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3174'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3174'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3175'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3175'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3176'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3176'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3177'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3177'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3178'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3178'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3179'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3179'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3180'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3180'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3181'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3181'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3182'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3182'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3183'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3183'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3184'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3184'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3185'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3185'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3186'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3186'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3187'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3187'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3188'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3188'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3189'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3189'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3190'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3190'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3191'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3191'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3192'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3192'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3193'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3193'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3194'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3194'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3195'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3195'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3196'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3196'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3197'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3197'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3198'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3198'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3199'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3199'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3200'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3200'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3201'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3201'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3202'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3202'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3203'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3203'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3204'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3204'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3205'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3205'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3206'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3206'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3207'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3207'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3208'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3208'

2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3209'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3209'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3210'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3210'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3211'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3211'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3212'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3212'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3213'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3213'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3214'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3214'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '3215'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3215'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3216'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3216'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3217'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3217'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3218'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3218'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3219'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3219'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3220'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3220'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '3221'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3221'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3222'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3222'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3223'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3223'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3224'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3224'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3225'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3225'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3226'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3226'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3227'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3227'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3228'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3228'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3229'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3229'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3230'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3230'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3231'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3231'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3232'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3232'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3233'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3233'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3234'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3234'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3235'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3235'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3236'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3236'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3237'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3237'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3238'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3238'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3239'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3239'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3240'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3240'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3241'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3241'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3242'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3242'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3243'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3243'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3244'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3244'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3245'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3245'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3246'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3246'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3247'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3247'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3248'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3248'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3249'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3249'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3250'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3250'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3251'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3251'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3252'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3252'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '3253'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3253'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '3254'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3254'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3255'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3255'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3256'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3256'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3257'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3257'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3258'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3258'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3259'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3259'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3260'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3260'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3261'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3261'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3262'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3262'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3263'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3263'

2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3264'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3264'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3265'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3265'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3266'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3266'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3267'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3267'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3268'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3268'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3269'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3269'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3270'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3270'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3271'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3271'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3272'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3272'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3273'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3273'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3274'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3274'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3275'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3275'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3276'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3276'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3277'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3277'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3278'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3278'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3279'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3279'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3280'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3280'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3281'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3281'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3282'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3282'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3283'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3283'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3284'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3284'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3285'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3285'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3286'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3286'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3287'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3287'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3288'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3288'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3289'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3289'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3290'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3290'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3291'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3291'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3292'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3292'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3293'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3293'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3294'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3294'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3295'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3295'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3296'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3296'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3297'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3297'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3298'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3298'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3299'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3299'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3300'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3300'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3301'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3301'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3302'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3302'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3303'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3303'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3304'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3304'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3305'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3305'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3306'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3306'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3307'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3307'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3308'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3308'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3309'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3309'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3310'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3310'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3311'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3311'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3312'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3312'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3313'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3313'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3314'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3314'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3315'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3315'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3316'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3316'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3317'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3317'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3318'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3318'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3319'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3319'

2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3320'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3320'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3321'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3321'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3322'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3322'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3323'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3323'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3324'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3324'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3325'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3325'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3326'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3326'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3327'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3327'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3328'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3328'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3329'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3329'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '3330'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3330'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3331'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3331'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3332'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3332'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3333'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3333'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3334'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3334'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3335'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3335'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3336'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3336'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3337'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3337'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3338'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3338'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3339'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3339'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3340'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3340'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3341'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3341'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3342'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3342'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3343'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3343'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3344'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3344'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3345'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3345'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3346'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3346'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3347'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3347'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '3348'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3348'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3349'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3349'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3350'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3350'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3351'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3351'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3352'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3352'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3353'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3353'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3354'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3354'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3355'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3355'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3356'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3356'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3357'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3357'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3358'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3358'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3359'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3359'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3360'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3360'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3361'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3361'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3362'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3362'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3363'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3363'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3364'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3364'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3365'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3365'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3366'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3366'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3367'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3367'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3368'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3368'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3369'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3369'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3370'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3370'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3371'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3371'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3372'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3372'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3373'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3373'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3374'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3374'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3375'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3375'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '3376'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3376'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3377'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3377'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3378'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3378'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3379'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3379'

2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3380'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3380'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3381'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3381'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3382'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3382'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3383'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3383'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3384'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3384'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3385'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3385'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3386'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3386'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3387'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3387'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3388'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3388'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3389'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3389'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3390'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3390'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3391'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3391'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3392'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3392'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3393'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3393'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3394'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3394'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3395'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3395'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3396'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3396'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3397'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3397'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3398'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3398'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3399'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3399'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3400'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3400'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3401'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3401'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3402'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3402'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3403'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3403'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3404'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3404'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3405'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3405'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3406'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3406'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3407'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3407'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3408'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3408'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3409'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3409'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3410'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3410'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3411'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3411'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3412'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3412'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3413'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3413'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3414'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3414'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3415'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3415'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3416'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3416'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3417'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3417'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3418'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3418'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3419'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3419'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3420'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3420'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3421'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3421'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3422'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3422'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3423'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3423'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3424'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3424'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3425'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3425'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3426'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3426'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3427'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3427'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3428'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3428'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3429'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3429'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '3430'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3430'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3431'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3431'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3432'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3432'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3433'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3433'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3434'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3434'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3435'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3435'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3436'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3436'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3437'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3437'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3438'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3438'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3439'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3439'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3440'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3440'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3441'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3441'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3442'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3442'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3443'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3443'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3444'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3444'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3445'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3445'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3446'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3446'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3447'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3447'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3448'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3448'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3449'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3449'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3450'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3450'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3451'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3451'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3452'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3452'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3453'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3453'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3454'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3454'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3455'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3455'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3456'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3456'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3457'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3457'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3458'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3458'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3459'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3459'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3460'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3460'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3461'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3461'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3462'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3462'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3463'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3463'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3464'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3464'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3465'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3465'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3466'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3466'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3467'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3467'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '3468'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3468'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3469'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3469'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3470'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3470'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3471'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3471'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3472'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3472'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3473'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3473'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3474'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3474'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3475'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3475'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3476'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3476'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3477'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3477'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3478'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3478'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3479'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3479'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3480'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3480'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '3481'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3481'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3482'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3482'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3483'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3483'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3484'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3484'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '3485'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3485'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3486'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3486'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3487'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3487'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3488'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3488'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3489'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3489'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3490'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3490'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3491'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3491'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3492'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3492'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3493'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3493'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3494'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3494'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3495'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3495'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3496'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3496'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3497'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3497'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3498'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3498'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3499'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3499'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3500'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3500'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3501'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3501'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3502'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3502'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3503'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3503'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3504'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3504'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3505'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3505'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3506'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3506'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3507'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3507'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3508'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3508'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3509'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3509'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3510'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3510'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3511'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3511'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3512'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3512'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3513'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3513'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3514'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3514'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '3515'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3515'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3516'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3516'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3517'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3517'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3518'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3518'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3519'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3519'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3520'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3520'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3521'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3521'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3522'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3522'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3523'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3523'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3524'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3524'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3525'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3525'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3526'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3526'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3527'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3527'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3528'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3528'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3529'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3529'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3530'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3530'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3531'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3531'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3532'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3532'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3533'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3533'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3534'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3534'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '3535'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3535'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3536'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3536'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3537'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3537'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3538'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3538'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3539'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3539'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '3540'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3540'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3541'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3541'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3542'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3542'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3543'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3543'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '3544'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3544'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3545'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3545'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '3546'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3546'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3547'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3547'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '3548'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3548'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3549'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3549'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3550'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3550'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3551'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3551'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3552'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3552'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3553'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3553'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3554'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3554'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3555'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3555'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3556'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3556'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3557'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3557'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3558'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3558'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3559'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3559'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3560'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3560'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3561'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3561'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3562'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3562'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3563'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3563'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3564'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3564'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3565'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3565'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3566'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3566'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3567'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3567'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3568'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3568'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '3569'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3569'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3570'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3570'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3571'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3571'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3572'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3572'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3573'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3573'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3574'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3574'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3575'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3575'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3576'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3576'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3577'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3577'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3578'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3578'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3579'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3579'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3580'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3580'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3581'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3581'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3582'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3582'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3583'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3583'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3584'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3584'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3585'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3585'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3586'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3586'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3587'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3587'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3588'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3588'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3589'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3589'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3590'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3590'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3591'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3591'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3592'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3592'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3593'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3593'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3594'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3594'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3595'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3595'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3596'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3596'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3597'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3597'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3598'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3598'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3599'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3599'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3600'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3600'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3601'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3601'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3602'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3602'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3603'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3603'

2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3604'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3604'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3605'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3605'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '3606'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3606'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '3607'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3607'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3608'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3608'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3609'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3609'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3610'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3610'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3611'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3611'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3612'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3612'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3613'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3613'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '3614'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3614'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3615'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3615'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3616'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3616'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3617'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3617'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3618'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3618'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3619'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3619'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3620'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3620'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3621'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3621'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3622'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3622'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3623'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3623'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3624'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3624'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3625'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3625'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3626'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3626'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3627'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3627'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3628'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3628'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3629'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3629'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3630'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3630'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3631'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3631'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3632'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3632'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '3633'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3633'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3634'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3634'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3635'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3635'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3636'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3636'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3637'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3637'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3638'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3638'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3639'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3639'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '3640'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3640'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3641'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3641'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3642'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3642'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '3643'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3643'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3644'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3644'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3645'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3645'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '3646'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3646'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3647'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3647'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3648'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3648'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3649'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3649'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3650'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3650'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3651'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3651'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3652'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3652'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3653'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3653'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3654'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3654'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3655'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3655'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3656'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3656'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3657'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3657'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3658'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3658'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3659'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3659'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '3660'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3660'

2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3661'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3661'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3662'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3662'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3663'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3663'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '3664'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3664'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3665'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3665'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3666'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3666'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '3667'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3667'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3668'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3668'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3669'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3669'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3670'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3670'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3671'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3671'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3672'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3672'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3673'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3673'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3674'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3674'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3675'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3675'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3676'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3676'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3677'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3677'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3678'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3678'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3679'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3679'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3680'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3680'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3681'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3681'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3682'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3682'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3683'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3683'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3684'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3684'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3685'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3685'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3686'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3686'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3687'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3687'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3688'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3688'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3689'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3689'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3690'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3690'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3691'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3691'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3692'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3692'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '3693'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3693'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3694'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3694'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3695'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3695'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3696'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3696'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3697'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3697'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3698'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3698'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3699'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3699'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3700'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3700'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3701'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3701'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3702'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3702'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3703'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3703'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3704'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3704'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3705'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3705'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3706'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3706'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3707'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3707'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3708'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3708'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3709'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3709'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3710'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3710'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3711'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3711'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3712'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3712'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3713'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3713'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3714'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3714'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3715'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3715'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3716'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3716'

2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3717'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3717'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3718'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3718'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3719'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3719'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3720'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3720'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '3721'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3721'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3722'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3722'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3723'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3723'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3724'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3724'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3725'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3725'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3726'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3726'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3727'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3727'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '3728'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3728'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3729'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3729'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '3730'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3730'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3731'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3731'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3732'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3732'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3733'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3733'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3734'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3734'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3735'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3735'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3736'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3736'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3737'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3737'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3738'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3738'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3739'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3739'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3740'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3740'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3741'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3741'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3742'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3742'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3743'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3743'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3744'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3744'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3745'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3745'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3746'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3746'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3747'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3747'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3748'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3748'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3749'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3749'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3750'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3750'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3751'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3751'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3752'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3752'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3753'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3753'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3754'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3754'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '3755'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3755'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3756'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3756'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '3757'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3757'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3758'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3758'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3759'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3759'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3760'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3760'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3761'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3761'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3762'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3762'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3763'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3763'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3764'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3764'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3765'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3765'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3766'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3766'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3767'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3767'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3768'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3768'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3769'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3769'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3770'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3770'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3771'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3771'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3772'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3772'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3773'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3773'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3774'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3774'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3775'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3775'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3776'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3776'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3777'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3777'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3778'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3778'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3779'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3779'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3780'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3780'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3781'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3781'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3782'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3782'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3783'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3783'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3784'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3784'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3785'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3785'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3786'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3786'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3787'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3787'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3788'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3788'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3789'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3789'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3790'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3790'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3791'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3791'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3792'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3792'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3793'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3793'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3794'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3794'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3795'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3795'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3796'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3796'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3797'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3797'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3798'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3798'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3799'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3799'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3800'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3800'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3801'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3801'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3802'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3802'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3803'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3803'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3804'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3804'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3805'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3805'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3806'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3806'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3807'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3807'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3808'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3808'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3809'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3809'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3810'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3810'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3811'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3811'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3812'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3812'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3813'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3813'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3814'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3814'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3815'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3815'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3816'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3816'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3817'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3817'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3818'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3818'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3819'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3819'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3820'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3820'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3821'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3821'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3822'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3822'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3823'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3823'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3824'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3824'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3825'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3825'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3826'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3826'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3827'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3827'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3828'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3828'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '3829'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3829'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3830'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3830'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3831'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3831'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3832'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3832'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3833'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3833'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3834'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3834'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3835'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3835'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3836'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3836'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3837'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3837'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3838'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3838'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3839'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3839'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3840'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3840'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3841'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3841'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3842'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3842'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3843'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3843'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '3844'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3844'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3845'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3845'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3846'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3846'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3847'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3847'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3848'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3848'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3849'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3849'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3850'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3850'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3851'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3851'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3852'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3852'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3853'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3853'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3854'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3854'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3855'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3855'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3856'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3856'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3857'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3857'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3858'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3858'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3859'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3859'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3860'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3860'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3861'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3861'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3862'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3862'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3863'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3863'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3864'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3864'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3865'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3865'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3866'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3866'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3867'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3867'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3868'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3868'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3869'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3869'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3870'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3870'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3871'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3871'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3872'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3872'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3873'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3873'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3874'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3874'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3875'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3875'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3876'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3876'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3877'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3877'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3878'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3878'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3879'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3879'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3880'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3880'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3881'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3881'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3882'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3882'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3883'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3883'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3884'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3884'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3885'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3885'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3886'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3886'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3887'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3887'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3888'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3888'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3889'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3889'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3890'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3890'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3891'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3891'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3892'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3892'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3893'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3893'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3894'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3894'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3895'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3895'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3896'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3896'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3897'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3897'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3898'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3898'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3899'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3899'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3900'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3900'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3901'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3901'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3902'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3902'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3903'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3903'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3904'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3904'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3905'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3905'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3906'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3906'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3907'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3907'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '3908'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3908'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3909'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3909'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3910'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3910'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3911'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3911'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3912'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3912'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3913'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3913'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3914'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3914'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3915'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3915'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3916'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3916'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3917'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3917'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3918'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3918'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3919'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3919'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3920'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3920'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3921'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3921'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3922'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3922'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3923'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3923'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3924'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3924'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3925'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3925'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3926'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3926'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3927'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3927'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3928'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3928'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '3929'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3929'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3930'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3930'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3931'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3931'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3932'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3932'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3933'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3933'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3934'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3934'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3935'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3935'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3936'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3936'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3937'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3937'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3938'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3938'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3939'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3939'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3940'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3940'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3941'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3941'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3942'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3942'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3943'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3943'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3944'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3944'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3945'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3945'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3946'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3946'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '3947'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3947'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3948'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3948'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3949'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3949'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3950'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3950'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3951'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3951'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3952'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3952'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3953'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3953'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3954'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3954'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3955'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3955'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '3956'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3956'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3957'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3957'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3958'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3958'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '3959'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3959'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3960'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3960'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3961'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3961'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3962'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3962'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3963'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3963'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3964'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3964'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3965'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3965'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3966'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3966'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3967'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3967'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3968'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3968'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '3969'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3969'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3970'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3970'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3971'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3971'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3972'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3972'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3973'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3973'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3974'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3974'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3975'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3975'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3976'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3976'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3977'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3977'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3978'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3978'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3979'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3979'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '3980'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3980'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '3981'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3981'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3982'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3982'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3983'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3983'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3984'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3984'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3985'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3985'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3986'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3986'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3987'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3987'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3988'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3988'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '3989'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3989'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3990'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3990'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '3991'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3991'

2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3992'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3992'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3993'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3993'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3994'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3994'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '3995'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3995'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3996'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3996'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '3997'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3997'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '3998'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3998'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '3999'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '3999'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4000'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4000'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4001'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4001'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4002'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4002'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4003'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4003'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4004'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4004'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4005'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4005'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4006'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4006'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4007'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4007'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4008'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4008'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4009'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4009'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4010'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4010'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4011'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4011'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4012'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4012'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4013'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4013'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4014'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4014'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '4015'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4015'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4016'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4016'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4017'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4017'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4018'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4018'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4019'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4019'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4020'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4020'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4021'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4021'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4022'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4022'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4023'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4023'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4024'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4024'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4025'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4025'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4026'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4026'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4027'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4027'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '4028'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4028'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4029'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4029'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4030'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4030'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4031'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4031'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '4032'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4032'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4033'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4033'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '4034'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4034'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4035'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4035'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4036'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4036'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4037'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4037'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4038'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4038'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4039'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4039'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4040'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4040'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4041'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4041'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4042'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4042'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4043'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4043'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4044'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4044'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4045'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4045'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '4046'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4046'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4047'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4047'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4048'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4048'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4049'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4049'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4050'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4050'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4051'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4051'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4052'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4052'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4053'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4053'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4054'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4054'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4055'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4055'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4056'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4056'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4057'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4057'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4058'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4058'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4059'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4059'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4060'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4060'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4061'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4061'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4062'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4062'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '4063'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4063'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4064'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4064'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4065'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4065'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4066'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4066'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4067'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4067'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4068'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4068'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4069'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4069'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4070'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4070'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4071'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4071'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4072'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4072'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4073'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4073'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4074'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4074'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4075'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4075'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4076'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4076'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4077'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4077'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4078'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4078'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4079'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4079'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4080'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4080'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4081'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4081'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4082'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4082'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4083'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4083'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4084'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4084'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4085'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4085'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4086'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4086'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4087'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4087'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4088'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4088'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4089'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4089'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4090'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4090'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4091'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4091'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4092'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4092'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4093'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4093'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '4094'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4094'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '4095'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4095'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4096'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4096'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4097'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4097'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4098'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4098'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4099'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4099'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4100'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4100'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4101'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4101'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4102'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4102'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4103'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4103'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4104'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4104'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4105'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4105'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4106'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4106'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4107'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4107'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4108'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4108'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4109'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4109'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4110'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4110'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4111'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4111'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4112'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4112'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4113'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4113'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4114'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4114'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4115'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4115'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4116'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4116'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4117'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4117'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4118'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4118'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4119'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4119'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4120'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4120'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4121'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4121'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4122'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4122'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4123'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4123'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4124'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4124'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4125'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4125'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4126'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4126'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4127'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4127'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4128'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4128'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4129'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4129'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4130'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4130'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4131'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4131'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4132'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4132'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4133'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4133'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4134'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4134'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4135'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4135'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4136'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4136'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4137'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4137'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4138'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4138'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4139'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4139'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4140'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4140'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4141'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4141'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4142'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4142'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4143'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4143'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4144'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4144'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4145'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4145'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4146'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4146'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4147'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4147'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4148'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4148'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4149'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4149'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4150'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4150'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4151'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4151'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4152'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4152'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4153'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4153'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4154'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4154'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4155'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4155'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4156'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4156'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4157'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4157'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4158'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4158'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '4159'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4159'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4160'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4160'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4161'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4161'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4162'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4162'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4163'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4163'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4164'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4164'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4165'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4165'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4166'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4166'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4167'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4167'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4168'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4168'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4169'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4169'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4170'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4170'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4171'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4171'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4172'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4172'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4173'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4173'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4174'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4174'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4175'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4175'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4176'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4176'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4177'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4177'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4178'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4178'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4179'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4179'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4180'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4180'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4181'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4181'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4182'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4182'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4183'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4183'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4184'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4184'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4185'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4185'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4186'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4186'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4187'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4187'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4188'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4188'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4189'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4189'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '4190'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4190'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4191'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4191'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4192'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4192'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4193'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4193'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4194'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4194'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4195'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4195'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4196'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4196'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4197'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4197'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4198'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4198'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4199'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4199'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4200'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4200'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4201'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4201'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4202'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4202'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4203'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4203'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4204'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4204'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4205'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4205'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4206'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4206'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4207'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4207'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4208'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4208'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4209'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4209'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4210'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4210'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4211'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4211'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4212'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4212'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4213'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4213'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4214'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4214'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4215'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4215'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4216'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4216'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4217'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4217'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4218'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4218'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4219'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4219'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4220'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4220'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4221'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4221'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4222'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4222'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4223'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4223'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4224'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4224'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4225'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4225'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4226'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4226'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4227'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4227'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4228'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4228'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4229'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4229'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4230'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4230'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4231'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4231'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4232'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4232'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4233'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4233'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4234'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4234'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4235'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4235'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4236'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4236'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4237'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4237'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4238'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4238'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4239'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4239'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4240'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4240'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4241'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4241'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4242'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4242'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4243'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4243'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4244'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4244'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4245'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4245'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4246'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4246'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4247'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4247'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4248'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4248'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4249'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4249'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4250'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4250'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4251'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4251'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4252'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4252'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4253'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4253'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4254'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4254'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4255'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4255'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4256'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4256'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4257'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4257'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4258'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4258'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '4259'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4259'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4260'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4260'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4261'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4261'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4262'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4262'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4263'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4263'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4264'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4264'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4265'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4265'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4266'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4266'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4267'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4267'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4268'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4268'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4269'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4269'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4270'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4270'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4271'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4271'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4272'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4272'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4273'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4273'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4274'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4274'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4275'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4275'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4276'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4276'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '4277'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4277'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4278'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4278'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4279'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4279'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4280'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4280'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4281'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4281'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4282'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4282'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4283'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4283'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4284'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4284'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4285'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4285'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4286'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4286'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4287'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4287'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4288'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4288'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4289'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4289'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4290'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4290'

2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4291'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4291'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4292'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4292'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4293'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4293'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4294'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4294'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4295'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4295'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4296'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4296'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4297'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4297'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4298'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4298'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4299'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4299'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4300'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4300'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4301'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4301'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4302'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4302'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4303'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4303'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4304'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4304'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4305'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4305'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4306'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4306'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4307'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4307'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4308'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4308'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4309'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4309'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4310'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4310'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '4311'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4311'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4312'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4312'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4313'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4313'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4314'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4314'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4315'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4315'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4316'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4316'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4317'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4317'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4318'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4318'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4319'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4319'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4320'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4320'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4321'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4321'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4322'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4322'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4323'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4323'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '4324'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4324'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4325'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4325'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4326'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4326'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4327'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4327'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4328'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4328'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4329'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4329'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4330'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4330'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4331'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4331'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4332'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4332'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4333'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4333'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4334'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4334'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4335'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4335'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4336'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4336'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4337'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4337'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4338'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4338'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4339'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4339'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4340'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4340'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4341'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4341'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4342'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4342'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4343'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4343'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4344'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4344'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4345'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4345'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4346'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4346'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4347'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4347'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '4348'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4348'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4349'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4349'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4350'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4350'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4351'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4351'

2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4352'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4352'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4353'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4353'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4354'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4354'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4355'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4355'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4356'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4356'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4357'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4357'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4358'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4358'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4359'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4359'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4360'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4360'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4361'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4361'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4362'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4362'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4363'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4363'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4364'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4364'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4365'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4365'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4366'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4366'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4367'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4367'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4368'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4368'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4369'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4369'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4370'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4370'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4371'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4371'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4372'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4372'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4373'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4373'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4374'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4374'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4375'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4375'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4376'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4376'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4377'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4377'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4378'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4378'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4379'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4379'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4380'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4380'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4381'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4381'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4382'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4382'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4383'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4383'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4384'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4384'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4385'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4385'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4386'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4386'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4387'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4387'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4388'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4388'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4389'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4389'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4390'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4390'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4391'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4391'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4392'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4392'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4393'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4393'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4394'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4394'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4395'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4395'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4396'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4396'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4397'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4397'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4398'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4398'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4399'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4399'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4400'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4400'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4401'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4401'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4402'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4402'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4403'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4403'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4404'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4404'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4405'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4405'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4406'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4406'

2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4407'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4407'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4408'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4408'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4409'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4409'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4410'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4410'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4411'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4411'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '4412'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4412'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4413'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4413'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4414'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4414'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4415'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4415'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4416'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4416'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4417'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4417'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4418'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4418'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4419'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4419'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4420'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4420'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '4421'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4421'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4422'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4422'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4423'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4423'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4424'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4424'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4425'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4425'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4426'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4426'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4427'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4427'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4428'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4428'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4429'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4429'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4430'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4430'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4431'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4431'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4432'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4432'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4433'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4433'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4434'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4434'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4435'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4435'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4436'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4436'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4437'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4437'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4438'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4438'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4439'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4439'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4440'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4440'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4441'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4441'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4442'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4442'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4443'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4443'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4444'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4444'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4445'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4445'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4446'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4446'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4447'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4447'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4448'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4448'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4449'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4449'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4450'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4450'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4451'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4451'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4452'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4452'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4453'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4453'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4454'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4454'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4455'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4455'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4456'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4456'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4457'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4457'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4458'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4458'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4459'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4459'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4460'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4460'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4461'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4461'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4462'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4462'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4463'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4463'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4464'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4464'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4465'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4465'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4466'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4466'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4467'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4467'

2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4468'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4468'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4469'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4469'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4470'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4470'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4471'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4471'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4472'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4472'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4473'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4473'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4474'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4474'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4475'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4475'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4476'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4476'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4477'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4477'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4478'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4478'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '4479'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4479'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4480'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4480'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4481'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4481'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4482'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4482'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4483'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4483'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4484'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4484'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4485'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4485'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4486'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4486'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4487'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4487'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4488'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4488'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4489'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4489'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4490'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4490'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4491'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4491'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4492'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4492'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4493'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4493'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4494'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4494'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4495'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4495'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4496'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4496'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4497'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4497'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4498'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4498'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4499'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4499'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4500'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4500'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4501'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4501'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4502'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4502'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4503'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4503'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4504'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4504'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4505'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4505'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4506'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4506'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4507'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4507'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4508'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4508'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4509'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4509'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4510'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4510'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4511'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4511'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4512'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4512'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4513'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4513'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4514'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4514'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4515'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4515'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4516'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4516'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4517'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4517'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4518'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4518'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4519'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4519'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4520'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4520'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4521'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4521'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4522'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4522'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4523'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4523'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '4524'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4524'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4525'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4525'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4526'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4526'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4527'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4527'

2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4528'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4528'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4529'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4529'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4530'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4530'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4531'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4531'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4532'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4532'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4533'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4533'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4534'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4534'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4535'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4535'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4536'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4536'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4537'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4537'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4538'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4538'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4539'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4539'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4540'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4540'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4541'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4541'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4542'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4542'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4543'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4543'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '4544'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4544'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4545'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4545'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4546'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4546'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4547'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4547'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4548'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4548'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '4549'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4549'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4550'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4550'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4551'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4551'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4552'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4552'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4553'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4553'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4554'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4554'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4555'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4555'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4556'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4556'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4557'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4557'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4558'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4558'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4559'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4559'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4560'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4560'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4561'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4561'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4562'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4562'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4563'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4563'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4564'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4564'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4565'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4565'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4566'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4566'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4567'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4567'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4568'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4568'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4569'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4569'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4570'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4570'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4571'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4571'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4572'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4572'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4573'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4573'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4574'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4574'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4575'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4575'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4576'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4576'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4577'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4577'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4578'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4578'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4579'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4579'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '4580'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4580'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4581'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4581'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4582'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4582'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4583'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4583'

2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4584'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4584'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4585'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4585'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4586'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4586'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4587'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4587'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4588'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4588'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4589'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4589'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4590'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4590'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4591'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4591'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4592'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4592'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4593'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4593'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4594'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4594'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4595'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4595'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4596'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4596'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4597'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4597'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4598'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4598'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4599'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4599'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '4600'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4600'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4601'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4601'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '4602'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4602'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4603'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4603'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4604'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4604'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4605'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4605'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4606'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4606'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4607'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4607'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4608'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4608'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4609'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4609'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4610'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4610'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4611'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4611'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4612'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4612'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4613'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4613'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4614'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4614'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4615'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4615'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4616'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4616'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4617'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4617'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4618'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4618'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4619'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4619'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4620'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4620'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4621'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4621'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4622'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4622'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4623'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4623'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4624'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4624'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4625'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4625'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4626'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4626'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4627'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4627'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4628'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4628'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '4629'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4629'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4630'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4630'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4631'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4631'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4632'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4632'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4633'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4633'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4634'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4634'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4635'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4635'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4636'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4636'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4637'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4637'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4638'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4638'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '4639'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4639'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4640'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4640'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4641'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4641'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4642'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4642'

2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4643'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4643'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4644'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4644'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4645'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4645'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4646'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4646'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4647'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4647'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4648'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4648'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4649'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4649'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4650'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4650'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4651'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4651'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4652'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4652'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4653'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4653'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4654'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4654'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4655'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4655'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4656'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4656'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4657'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4657'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4658'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4658'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4659'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4659'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4660'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4660'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4661'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4661'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4662'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4662'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4663'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4663'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4664'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4664'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4665'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4665'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4666'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4666'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4667'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4667'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4668'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4668'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4669'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4669'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4670'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4670'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4671'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4671'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4672'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4672'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4673'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4673'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4674'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4674'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4675'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4675'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4676'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4676'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4677'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4677'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4678'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4678'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4679'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4679'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4680'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4680'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '4681'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4681'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4682'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4682'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4683'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4683'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4684'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4684'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4685'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4685'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4686'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4686'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4687'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4687'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4688'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4688'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4689'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4689'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4690'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4690'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4691'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4691'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4692'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4692'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4693'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4693'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4694'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4694'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4695'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4695'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4696'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4696'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4697'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4697'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4698'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4698'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4699'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4699'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4700'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4700'

2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4701'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4701'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4702'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4702'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4703'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4703'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '4704'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4704'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4705'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4705'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4706'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4706'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4707'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4707'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4708'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4708'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4709'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4709'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4710'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4710'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4711'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4711'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4712'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4712'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4713'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4713'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4714'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4714'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4715'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4715'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4716'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4716'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4717'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4717'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4718'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4718'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4719'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4719'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4720'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4720'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4721'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4721'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4722'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4722'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4723'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4723'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4724'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4724'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4725'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4725'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4726'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4726'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4727'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4727'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4728'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4728'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4729'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4729'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4730'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4730'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4731'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4731'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4732'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4732'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4733'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4733'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4734'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4734'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4735'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4735'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4736'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4736'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '4737'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4737'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4738'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4738'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4739'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4739'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4740'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4740'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4741'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4741'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4742'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4742'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4743'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4743'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4744'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4744'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4745'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4745'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4746'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4746'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4747'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4747'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4748'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4748'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4749'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4749'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4750'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4750'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4751'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4751'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4752'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4752'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4753'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4753'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4754'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4754'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4755'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4755'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4756'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4756'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4757'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4757'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4758'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4758'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4759'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4759'

2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4760'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4760'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '4761'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4761'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4762'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4762'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4763'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4763'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4764'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4764'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4765'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4765'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4766'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4766'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4767'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4767'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4768'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4768'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4769'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4769'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4770'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4770'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '4771'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4771'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4772'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4772'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4773'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4773'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4774'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4774'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4775'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4775'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4776'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4776'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4777'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4777'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4778'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4778'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4779'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4779'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4780'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4780'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4781'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4781'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4782'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4782'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4783'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4783'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4784'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4784'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4785'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4785'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4786'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4786'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4787'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4787'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4788'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4788'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4789'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4789'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4790'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4790'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4791'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4791'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4792'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4792'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4793'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4793'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4794'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4794'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4795'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4795'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4796'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4796'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4797'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4797'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4798'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4798'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4799'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4799'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4800'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4800'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4801'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4801'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4802'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4802'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4803'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4803'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4804'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4804'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4805'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4805'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4806'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4806'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4807'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4807'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4808'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4808'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4809'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4809'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4810'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4810'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4811'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4811'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4812'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4812'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4813'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4813'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4814'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4814'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4815'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4815'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4816'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4816'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4817'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4817'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4818'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4818'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4819'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4819'

2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4820'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4820'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4821'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4821'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4822'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4822'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4823'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4823'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4824'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4824'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4825'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4825'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4826'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4826'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4827'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4827'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4828'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4828'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4829'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4829'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4830'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4830'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4831'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4831'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4832'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4832'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4833'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4833'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '4834'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4834'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4835'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4835'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4836'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4836'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4837'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4837'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4838'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4838'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4839'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4839'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4840'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4840'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4841'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4841'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4842'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4842'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '4843'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4843'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4844'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4844'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4845'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4845'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4846'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4846'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4847'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4847'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4848'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4848'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4849'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4849'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4850'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4850'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4851'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4851'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4852'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4852'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4853'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4853'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4854'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4854'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4855'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4855'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '4856'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4856'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4857'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4857'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '4858'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4858'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4859'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4859'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4860'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4860'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4861'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4861'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4862'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4862'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4863'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4863'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4864'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4864'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4865'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4865'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4866'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4866'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4867'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4867'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4868'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4868'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4869'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4869'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4870'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4870'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4871'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4871'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4872'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4872'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4873'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4873'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4874'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4874'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4875'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4875'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4876'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4876'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4877'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4877'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4878'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4878'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4879'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4879'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4880'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4880'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4881'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4881'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4882'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4882'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4883'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4883'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '4884'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4884'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4885'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4885'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '4886'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4886'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4887'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4887'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4888'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4888'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4889'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4889'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4890'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4890'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4891'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4891'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4892'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4892'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4893'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4893'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4894'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4894'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4895'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4895'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4896'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4896'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '4897'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4897'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4898'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4898'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4899'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4899'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4900'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4900'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4901'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4901'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4902'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4902'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4903'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4903'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4904'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4904'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4905'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4905'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4906'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4906'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4907'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4907'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4908'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4908'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4909'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4909'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4910'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4910'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4911'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4911'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4912'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4912'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4913'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4913'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4914'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4914'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4915'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4915'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4916'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4916'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4917'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4917'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4918'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4918'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4919'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4919'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4920'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4920'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4921'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4921'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4922'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4922'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4923'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4923'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4924'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4924'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4925'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4925'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4926'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4926'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4927'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4927'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4928'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4928'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4929'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4929'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4930'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4930'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4931'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4931'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4932'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4932'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4933'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4933'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4934'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4934'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4935'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4935'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4936'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4936'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4937'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4937'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4938'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4938'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '4939'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4939'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4940'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4940'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4941'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4941'

2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4942'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4942'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4943'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4943'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4944'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4944'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4945'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4945'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4946'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4946'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4947'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4947'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4948'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4948'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4949'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4949'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4950'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4950'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4951'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4951'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4952'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4952'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4953'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4953'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4954'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4954'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4955'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4955'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4956'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4956'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4957'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4957'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4958'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4958'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4959'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4959'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4960'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4960'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4961'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4961'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '4962'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4962'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '4963'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4963'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4964'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4964'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4965'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4965'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4966'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4966'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4967'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4967'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4968'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4968'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4969'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4969'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4970'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4970'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4971'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4971'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '4972'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4972'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4973'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4973'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '4974'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4974'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4975'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4975'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4976'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4976'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4977'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4977'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4978'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4978'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4979'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4979'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4980'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4980'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4981'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4981'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4982'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4982'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4983'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4983'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4984'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4984'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '4985'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4985'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4986'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4986'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4987'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4987'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4988'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4988'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4989'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4989'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4990'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4990'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4991'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4991'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '4992'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4992'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '4993'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4993'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '4994'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4994'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4995'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4995'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '4996'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4996'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4997'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4997'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '4998'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4998'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '4999'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '4999'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5000'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5000'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5001'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5001'

2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5002'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5002'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5003'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5003'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5004'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5004'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5005'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5005'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5006'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5006'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5007'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5007'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5008'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5008'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5009'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5009'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5010'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5010'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5011'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5011'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5012'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5012'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5013'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5013'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5014'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5014'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5015'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5015'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5016'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5016'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5017'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5017'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5018'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5018'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5019'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5019'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5020'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5020'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5021'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5021'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5022'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5022'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5023'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5023'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5024'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5024'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5025'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5025'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5026'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5026'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5027'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5027'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '5028'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5028'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '5029'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5029'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5030'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5030'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5031'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5031'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5032'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5032'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5033'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5033'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5034'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5034'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5035'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5035'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5036'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5036'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5037'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5037'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5038'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5038'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5039'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5039'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5040'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5040'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5041'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5041'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5042'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5042'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5043'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5043'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5044'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5044'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5045'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5045'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5046'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5046'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5047'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5047'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5048'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5048'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '5049'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5049'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5050'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5050'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5051'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5051'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5052'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5052'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5053'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5053'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5054'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5054'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5055'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5055'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5056'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5056'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5057'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5057'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5058'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5058'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5059'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5059'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5060'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5060'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5061'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5061'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5062'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5062'

2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5063'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5063'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5064'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5064'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5065'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5065'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5066'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5066'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5067'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5067'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5068'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5068'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5069'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5069'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5070'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5070'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5071'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5071'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5072'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5072'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5073'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5073'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5074'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5074'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5075'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5075'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5076'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5076'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5077'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5077'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5078'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5078'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5079'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5079'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5080'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5080'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5081'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5081'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5082'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5082'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5083'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5083'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5084'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5084'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5085'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5085'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5086'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5086'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5087'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5087'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5088'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5088'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5089'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5089'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5090'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5090'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5091'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5091'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5092'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5092'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5093'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5093'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5094'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5094'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5095'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5095'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5096'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5096'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5097'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5097'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5098'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5098'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5099'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5099'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5100'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5100'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5101'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5101'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5102'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5102'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5103'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5103'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5104'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5104'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5105'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5105'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5106'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5106'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5107'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5107'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5108'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5108'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5109'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5109'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5110'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5110'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5111'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5111'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5112'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5112'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5113'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5113'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5114'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5114'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5115'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5115'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5116'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5116'

2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5117'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5117'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5118'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5118'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '5119'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5119'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5120'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5120'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5121'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5121'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5122'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5122'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5123'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5123'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5124'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5124'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5125'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5125'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5126'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5126'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5127'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5127'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5128'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5128'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '5129'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5129'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5130'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5130'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5131'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5131'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5132'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5132'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5133'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5133'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5134'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5134'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5135'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5135'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5136'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5136'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5137'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5137'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5138'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5138'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5139'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5139'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5140'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5140'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5141'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5141'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5142'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5142'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5143'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5143'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5144'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5144'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5145'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5145'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5146'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5146'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5147'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5147'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5148'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5148'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5149'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5149'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5150'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5150'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5151'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5151'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5152'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5152'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5153'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5153'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5154'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5154'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5155'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5155'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5156'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5156'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5157'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5157'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5158'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5158'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '5159'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5159'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5160'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5160'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5161'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5161'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5162'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5162'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5163'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5163'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5164'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5164'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5165'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5165'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5166'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5166'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5167'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5167'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5168'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5168'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5169'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5169'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5170'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5170'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5171'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5171'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5172'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5172'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5173'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5173'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5174'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5174'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5175'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5175'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5176'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5176'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5177'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5177'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5178'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5178'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5179'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5179'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5180'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5180'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '5181'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5181'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5182'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5182'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5183'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5183'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5184'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5184'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5185'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5185'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5186'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5186'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5187'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5187'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5188'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5188'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5189'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5189'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5190'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5190'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5191'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5191'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5192'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5192'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '5193'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5193'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5194'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5194'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5195'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5195'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '5196'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5196'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5197'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5197'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5198'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5198'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5199'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5199'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5200'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5200'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5201'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5201'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5202'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5202'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5203'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5203'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5204'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5204'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5205'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5205'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5206'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5206'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5207'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5207'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5208'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5208'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5209'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5209'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5210'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5210'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5211'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5211'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '5212'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5212'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5213'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5213'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5214'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5214'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5215'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5215'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '5216'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5216'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5217'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5217'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5218'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5218'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5219'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5219'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5220'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5220'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5221'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5221'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5222'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5222'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5223'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5223'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5224'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5224'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5225'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5225'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5226'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5226'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5227'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5227'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5228'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5228'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5229'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5229'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5230'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5230'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5231'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5231'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5232'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5232'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5233'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5233'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5234'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5234'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5235'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5235'

2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5236'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5236'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5237'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5237'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5238'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5238'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5239'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5239'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5240'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5240'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5241'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5241'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5242'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5242'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5243'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5243'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5244'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5244'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5245'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5245'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5246'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5246'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5247'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5247'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5248'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5248'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5249'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5249'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5250'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5250'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5251'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5251'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5252'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5252'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5253'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5253'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5254'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5254'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5255'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5255'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5256'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5256'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5257'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5257'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5258'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5258'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5259'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5259'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5260'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5260'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5261'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5261'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5262'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5262'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5263'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5263'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5264'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5264'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5265'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5265'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5266'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5266'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5267'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5267'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5268'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5268'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5269'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5269'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5270'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5270'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5271'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5271'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5272'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5272'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5273'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5273'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5274'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5274'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5275'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5275'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5276'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5276'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5277'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5277'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5278'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5278'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5279'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5279'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5280'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5280'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5281'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5281'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5282'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5282'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5283'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5283'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5284'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5284'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5285'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5285'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '5286'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5286'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5287'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5287'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5288'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5288'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5289'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5289'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5290'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5290'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5291'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5291'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5292'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5292'

2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5293'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5293'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5294'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5294'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5295'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5295'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5296'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5296'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5297'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5297'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5298'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5298'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5299'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5299'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5300'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5300'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5301'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5301'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5302'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5302'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5303'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5303'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5304'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5304'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5305'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5305'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5306'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5306'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5307'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5307'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5308'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5308'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5309'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5309'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5310'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5310'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5311'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5311'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5312'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5312'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5313'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5313'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5314'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5314'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5315'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5315'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5316'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5316'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5317'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5317'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5318'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5318'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5319'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5319'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5320'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5320'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5321'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5321'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5322'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5322'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5323'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5323'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5324'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5324'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5325'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5325'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5326'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5326'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5327'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5327'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5328'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5328'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5329'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5329'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5330'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5330'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5331'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5331'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5332'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5332'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5333'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5333'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5334'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5334'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5335'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5335'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5336'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5336'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5337'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5337'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5338'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5338'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5339'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5339'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5340'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5340'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5341'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5341'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5342'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5342'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5343'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5343'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5344'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5344'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5345'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5345'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5346'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5346'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5347'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5347'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5348'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5348'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5349'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5349'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5350'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5350'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5351'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5351'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5352'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5352'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5353'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5353'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5354'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5354'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5355'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5355'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5356'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5356'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5357'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5357'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5358'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5358'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5359'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5359'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5360'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5360'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5361'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5361'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5362'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5362'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5363'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5363'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5364'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5364'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5365'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5365'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5366'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5366'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5367'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5367'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5368'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5368'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5369'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5369'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5370'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5370'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5371'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5371'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5372'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5372'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5373'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5373'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5374'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5374'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5375'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5375'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5376'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5376'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5377'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5377'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5378'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5378'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5379'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5379'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5380'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5380'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5381'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5381'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5382'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5382'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5383'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5383'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5384'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5384'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5385'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5385'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5386'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5386'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5387'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5387'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5388'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5388'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5389'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5389'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5390'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5390'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5391'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5391'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5392'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5392'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5393'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5393'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5394'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5394'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5395'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5395'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5396'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5396'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5397'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5397'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5398'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5398'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '5399'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5399'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5400'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5400'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5401'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5401'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5402'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5402'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5403'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5403'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5404'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5404'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5405'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5405'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5406'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5406'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5407'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5407'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5408'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5408'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5409'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5409'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5410'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5410'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5411'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5411'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5412'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5412'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5413'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5413'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5414'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5414'

2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5415'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5415'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5416'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5416'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5417'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5417'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5418'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5418'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5419'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5419'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5420'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5420'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5421'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5421'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5422'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5422'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5423'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5423'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5424'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5424'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5425'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5425'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5426'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5426'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5427'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5427'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '5428'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5428'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5429'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5429'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5430'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5430'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5431'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5431'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5432'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5432'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5433'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5433'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5434'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5434'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5435'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5435'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5436'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5436'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5437'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5437'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5438'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5438'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '5439'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5439'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5440'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5440'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5441'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5441'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5442'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5442'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5443'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5443'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5444'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5444'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5445'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5445'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5446'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5446'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5447'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5447'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5448'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5448'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5449'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5449'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5450'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5450'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5451'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5451'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5452'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5452'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5453'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5453'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5454'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5454'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5455'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5455'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5456'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5456'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5457'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5457'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5458'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5458'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5459'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5459'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5460'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5460'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5461'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5461'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5462'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5462'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5463'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5463'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5464'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5464'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5465'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5465'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5466'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5466'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5467'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5467'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5468'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5468'

2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5469'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5469'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5470'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5470'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5471'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5471'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5472'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5472'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5473'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5473'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5474'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5474'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5475'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5475'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5476'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5476'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5477'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5477'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5478'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5478'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5479'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5479'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5480'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5480'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5481'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5481'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5482'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5482'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5483'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5483'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5484'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5484'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5485'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5485'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5486'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5486'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5487'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5487'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5488'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5488'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5489'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5489'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5490'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5490'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5491'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5491'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '5492'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5492'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5493'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5493'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5494'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5494'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5495'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5495'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5496'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5496'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5497'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5497'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5498'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5498'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5499'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5499'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5500'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5500'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5501'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5501'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5502'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5502'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5503'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5503'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5504'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5504'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5505'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5505'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5506'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5506'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5507'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5507'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5508'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5508'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5509'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5509'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5510'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5510'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5511'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5511'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5512'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5512'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5513'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5513'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5514'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5514'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5515'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5515'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5516'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5516'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5517'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5517'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5518'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5518'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5519'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5519'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5520'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5520'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5521'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5521'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5522'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5522'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5523'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5523'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5524'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5524'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5525'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5525'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5526'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5526'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5527'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5527'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5528'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5528'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5529'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5529'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5530'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5530'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5531'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5531'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5532'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5532'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5533'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5533'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5534'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5534'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5535'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5535'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '5536'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5536'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5537'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5537'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5538'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5538'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5539'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5539'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5540'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5540'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5541'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5541'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5542'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5542'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5543'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5543'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5544'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5544'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5545'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5545'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5546'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5546'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5547'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5547'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5548'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5548'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5549'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5549'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5550'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5550'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5551'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5551'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5552'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5552'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5553'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5553'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5554'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5554'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5555'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5555'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5556'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5556'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5557'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5557'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5558'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5558'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5559'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5559'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5560'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5560'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5561'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5561'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5562'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5562'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5563'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5563'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5564'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5564'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5565'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5565'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5566'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5566'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5567'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5567'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5568'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5568'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5569'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5569'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5570'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5570'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5571'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5571'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5572'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5572'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5573'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5573'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5574'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5574'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5575'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5575'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '5576'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5576'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5577'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5577'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5578'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5578'

2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5579'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5579'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5580'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5580'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5581'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5581'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5582'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5582'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5583'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5583'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5584'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5584'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5585'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5585'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5586'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5586'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5587'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5587'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5588'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5588'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5589'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5589'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5590'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5590'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5591'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5591'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5592'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5592'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5593'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5593'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5594'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5594'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5595'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5595'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5596'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5596'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5597'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5597'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5598'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5598'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5599'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5599'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5600'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5600'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5601'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5601'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5602'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5602'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5603'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5603'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5604'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5604'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5605'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5605'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5606'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5606'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5607'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5607'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5608'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5608'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5609'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5609'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5610'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5610'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5611'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5611'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5612'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5612'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5613'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5613'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5614'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5614'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5615'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5615'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5616'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5616'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5617'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5617'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5618'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5618'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5619'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5619'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5620'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5620'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5621'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5621'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5622'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5622'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5623'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5623'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5624'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5624'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5625'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5625'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5626'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5626'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5627'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5627'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5628'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5628'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5629'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5629'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5630'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5630'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5631'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5631'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5632'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5632'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5633'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5633'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5634'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5634'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5635'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5635'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5636'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5636'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5637'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5637'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5638'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5638'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5639'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5639'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5640'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5640'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5641'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5641'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5642'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5642'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5643'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5643'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5644'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5644'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5645'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5645'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5646'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5646'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5647'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5647'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5648'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5648'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5649'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5649'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5650'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5650'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5651'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5651'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5652'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5652'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5653'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5653'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5654'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5654'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5655'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5655'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5656'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5656'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5657'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5657'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5658'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5658'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5659'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5659'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5660'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5660'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5661'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5661'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5662'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5662'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5663'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5663'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5664'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5664'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5665'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5665'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5666'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5666'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5667'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5667'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5668'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5668'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5669'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5669'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5670'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5670'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5671'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5671'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5672'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5672'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5673'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5673'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5674'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5674'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5675'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5675'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5676'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5676'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5677'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5677'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5678'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5678'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5679'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5679'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5680'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5680'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5681'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5681'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5682'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5682'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5683'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5683'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5684'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5684'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5685'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5685'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5686'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5686'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5687'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5687'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5688'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5688'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5689'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5689'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5690'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5690'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '5691'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5691'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5692'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5692'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5693'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5693'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5694'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5694'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5695'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5695'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5696'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5696'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5697'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5697'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5698'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5698'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5699'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5699'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5700'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5700'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5701'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5701'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5702'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5702'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5703'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5703'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5704'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5704'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5705'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5705'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5706'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5706'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5707'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5707'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5708'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5708'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5709'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5709'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5710'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5710'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5711'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5711'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5712'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5712'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5713'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5713'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5714'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5714'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5715'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5715'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5716'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5716'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5717'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5717'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5718'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5718'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '5719'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5719'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5720'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5720'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5721'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5721'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5722'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5722'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5723'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5723'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5724'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5724'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5725'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5725'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5726'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5726'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5727'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5727'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5728'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5728'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5729'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5729'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5730'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5730'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5731'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5731'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5732'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5732'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5733'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5733'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5734'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5734'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5735'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5735'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5736'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5736'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5737'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5737'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5738'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5738'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5739'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5739'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5740'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5740'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5741'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5741'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5742'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5742'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '5743'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5743'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5744'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5744'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5745'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5745'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5746'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5746'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5747'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5747'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5748'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5748'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5749'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5749'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5750'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5750'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5751'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5751'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5752'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5752'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5753'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5753'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5754'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5754'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5755'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5755'

2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5756'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5756'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5757'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5757'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5758'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5758'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5759'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5759'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5760'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5760'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5761'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5761'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5762'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5762'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5763'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5763'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5764'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5764'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5765'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5765'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5766'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5766'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5767'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5767'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5768'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5768'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5769'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5769'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5770'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5770'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5771'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5771'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5772'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5772'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5773'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5773'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5774'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5774'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5775'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5775'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5776'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5776'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5777'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5777'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5778'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5778'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5779'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5779'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '5780'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5780'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5781'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5781'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5782'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5782'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5783'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5783'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5784'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5784'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5785'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5785'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5786'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5786'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5787'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5787'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5788'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5788'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5789'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5789'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5790'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5790'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5791'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5791'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5792'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5792'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5793'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5793'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5794'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5794'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5795'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5795'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5796'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5796'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5797'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5797'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '5798'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5798'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5799'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5799'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5800'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5800'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5801'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5801'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5802'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5802'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5803'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5803'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5804'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5804'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5805'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5805'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5806'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5806'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5807'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5807'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5808'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5808'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5809'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5809'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5810'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5810'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5811'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5811'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5812'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5812'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5813'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5813'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5814'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5814'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5815'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5815'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5816'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5816'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5817'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5817'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5818'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5818'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5819'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5819'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5820'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5820'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5821'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5821'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5822'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5822'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5823'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5823'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5824'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5824'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5825'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5825'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5826'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5826'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5827'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5827'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5828'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5828'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5829'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5829'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5830'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5830'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5831'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5831'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5832'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5832'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5833'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5833'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5834'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5834'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5835'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5835'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5836'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5836'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5837'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5837'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5838'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5838'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5839'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5839'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5840'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5840'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5841'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5841'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5842'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5842'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5843'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5843'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5844'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5844'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5845'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5845'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5846'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5846'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5847'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5847'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5848'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5848'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5849'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5849'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5850'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5850'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5851'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5851'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5852'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5852'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5853'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5853'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5854'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5854'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5855'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5855'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5856'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5856'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5857'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5857'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5858'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5858'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5859'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5859'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5860'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5860'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5861'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5861'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5862'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5862'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5863'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5863'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5864'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5864'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '5865'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5865'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5866'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5866'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5867'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5867'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5868'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5868'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5869'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5869'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5870'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5870'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5871'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5871'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5872'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5872'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5873'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5873'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5874'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5874'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5875'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5875'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5876'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5876'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5877'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5877'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5878'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5878'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5879'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5879'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5880'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5880'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5881'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5881'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5882'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5882'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5883'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5883'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5884'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5884'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5885'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5885'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5886'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5886'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5887'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5887'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5888'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5888'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5889'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5889'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5890'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5890'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5891'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5891'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5892'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5892'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5893'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5893'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5894'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5894'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5895'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5895'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5896'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5896'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5897'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5897'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5898'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5898'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5899'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5899'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5900'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5900'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5901'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5901'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5902'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5902'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5903'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5903'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5904'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5904'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5905'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5905'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5906'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5906'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5907'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5907'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5908'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5908'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5909'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5909'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5910'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5910'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5911'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5911'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5912'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5912'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5913'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5913'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5914'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5914'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '5915'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5915'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5916'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5916'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5917'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5917'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5918'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5918'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5919'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5919'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5920'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5920'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5921'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5921'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5922'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5922'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5923'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5923'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '5924'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5924'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5925'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5925'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5926'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5926'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5927'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5927'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5928'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5928'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '5929'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5929'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5930'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5930'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5931'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5931'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5932'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5932'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5933'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5933'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5934'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5934'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5935'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5935'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5936'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5936'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5937'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5937'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5938'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5938'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5939'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5939'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5940'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5940'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5941'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5941'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5942'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5942'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5943'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5943'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5944'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5944'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5945'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5945'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5946'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5946'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5947'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5947'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5948'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5948'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '5949'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5949'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5950'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5950'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5951'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5951'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5952'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5952'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5953'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5953'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5954'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5954'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '5955'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5955'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '5956'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5956'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5957'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5957'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5958'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5958'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5959'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5959'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5960'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5960'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5961'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5961'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5962'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5962'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5963'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5963'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5964'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5964'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5965'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5965'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5966'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5966'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5967'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5967'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5968'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5968'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5969'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5969'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5970'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5970'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5971'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5971'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '5972'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5972'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5973'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5973'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5974'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5974'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5975'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5975'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5976'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5976'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5977'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5977'

2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5978'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5978'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5979'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5979'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5980'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5980'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5981'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5981'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5982'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5982'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5983'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5983'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5984'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5984'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5985'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5985'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5986'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5986'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '5987'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5987'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5988'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5988'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5989'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5989'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5990'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5990'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5991'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5991'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '5992'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5992'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '5993'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5993'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '5994'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5994'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5995'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5995'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5996'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5996'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5997'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5997'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '5998'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5998'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '5999'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '5999'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6000'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6000'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '6001'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6001'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6002'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6002'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '6003'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6003'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6004'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6004'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6005'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6005'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6006'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6006'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '6007'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6007'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6008'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6008'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6009'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6009'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6010'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6010'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '6011'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6011'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6012'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6012'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6013'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6013'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '6014'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6014'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '6015'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6015'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6016'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6016'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6017'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6017'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '6018'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6018'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '6019'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6019'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6020'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6020'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6021'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6021'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6022'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6022'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6023'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6023'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6024'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6024'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6025'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6025'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6026'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6026'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6027'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6027'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6028'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6028'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6029'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6029'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6030'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6030'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '6031'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6031'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6032'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6032'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6033'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6033'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6034'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6034'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '6035'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6035'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6036'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6036'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6037'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6037'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6038'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6038'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6039'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6039'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6040'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6040'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6041'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6041'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6042'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6042'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6043'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6043'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6044'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6044'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6045'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6045'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '6046'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6046'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6047'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6047'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6048'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6048'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6049'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6049'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6050'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6050'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6051'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6051'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6052'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6052'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '6053'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6053'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6054'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6054'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6055'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6055'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6056'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6056'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6057'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6057'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6058'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6058'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6059'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6059'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6060'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6060'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '6061'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6061'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6062'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6062'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6063'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6063'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6064'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6064'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6065'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6065'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6066'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6066'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6067'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6067'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6068'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6068'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6069'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6069'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6070'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6070'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6071'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6071'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6072'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6072'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6073'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6073'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6074'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6074'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6075'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6075'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6076'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6076'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6077'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6077'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6078'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6078'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6079'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6079'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6080'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6080'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6081'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6081'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6082'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6082'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6083'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6083'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6084'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6084'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6085'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6085'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6086'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6086'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6087'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6087'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6088'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6088'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6089'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6089'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6090'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6090'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6091'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6091'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6092'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6092'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6093'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6093'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6094'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6094'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6095'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6095'

2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6096'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6096'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6097'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6097'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6098'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6098'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6099'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6099'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6100'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6100'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6101'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6101'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '6102'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6102'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6103'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6103'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6104'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6104'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6105'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6105'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6106'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6106'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6107'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6107'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6108'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6108'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6109'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6109'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '6110'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6110'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6111'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6111'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6112'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6112'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6113'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6113'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '6114'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6114'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6115'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6115'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6116'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6116'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6117'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6117'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6118'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6118'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6119'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6119'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6120'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6120'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6121'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6121'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6122'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6122'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6123'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6123'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6124'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6124'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6125'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6125'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6126'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6126'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6127'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6127'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6128'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6128'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6129'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6129'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6130'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6130'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6131'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6131'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6132'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6132'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6133'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6133'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6134'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6134'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6135'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6135'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6136'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6136'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6137'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6137'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6138'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6138'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6139'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6139'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '6140'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6140'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6141'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6141'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6142'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6142'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6143'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6143'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6144'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6144'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6145'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6145'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6146'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6146'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6147'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6147'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6148'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6148'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6149'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6149'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6150'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6150'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6151'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6151'

2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6152'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6152'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '6153'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6153'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6154'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6154'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6155'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6155'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6156'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6156'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6157'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6157'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6158'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6158'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6159'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6159'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '6160'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6160'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6161'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6161'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6162'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6162'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6163'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6163'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6164'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6164'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6165'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6165'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6166'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6166'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6167'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6167'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6168'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6168'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6169'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6169'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6170'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6170'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6171'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6171'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6172'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6172'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6173'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6173'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6174'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6174'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6175'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6175'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6176'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6176'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6177'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6177'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6178'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6178'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6179'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6179'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6180'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6180'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6181'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6181'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6182'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6182'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6183'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6183'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6184'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6184'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6185'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6185'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6186'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6186'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6187'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6187'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6188'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6188'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6189'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6189'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6190'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6190'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6191'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6191'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6192'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6192'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6193'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6193'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6194'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6194'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6195'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6195'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6196'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6196'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6197'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6197'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6198'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6198'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6199'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6199'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6200'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6200'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6201'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6201'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6202'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6202'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6203'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6203'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '6204'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6204'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6205'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6205'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6206'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6206'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '6207'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6207'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6208'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6208'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6209'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6209'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6210'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6210'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6211'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6211'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6212'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6212'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6213'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6213'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6214'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6214'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '6215'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6215'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6216'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6216'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6217'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6217'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6218'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6218'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6219'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6219'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6220'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6220'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6221'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6221'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6222'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6222'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6223'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6223'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6224'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6224'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6225'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6225'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6226'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6226'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6227'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6227'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6228'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6228'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6229'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6229'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6230'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6230'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6231'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6231'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6232'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6232'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6233'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6233'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6234'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6234'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6235'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6235'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6236'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6236'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '6237'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6237'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6238'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6238'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6239'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6239'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6240'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6240'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6241'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6241'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6242'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6242'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6243'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6243'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6244'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6244'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6245'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6245'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6246'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6246'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '6247'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6247'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6248'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6248'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6249'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6249'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6250'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6250'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6251'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6251'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6252'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6252'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6253'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6253'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6254'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6254'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6255'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6255'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6256'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6256'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6257'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6257'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6258'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6258'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '6259'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6259'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6260'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6260'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6261'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6261'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '6262'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6262'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6263'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6263'

2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6264'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6264'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6265'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6265'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6266'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6266'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6267'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6267'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6268'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6268'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6269'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6269'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6270'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6270'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6271'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6271'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '6272'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6272'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6273'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6273'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6274'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6274'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6275'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6275'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6276'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6276'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6277'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6277'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6278'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6278'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6279'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6279'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '6280'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6280'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6281'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6281'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6282'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6282'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6283'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6283'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6284'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6284'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6285'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6285'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6286'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6286'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6287'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6287'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6288'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6288'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6289'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6289'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6290'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6290'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6291'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6291'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6292'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6292'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6293'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6293'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6294'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6294'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6295'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6295'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '6296'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6296'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6297'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6297'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6298'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6298'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6299'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6299'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6300'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6300'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6301'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6301'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6302'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6302'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '6303'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6303'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6304'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6304'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6305'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6305'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6306'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6306'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6307'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6307'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6308'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6308'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6309'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6309'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '6310'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6310'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6311'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6311'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6312'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6312'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6313'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6313'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6314'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6314'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6315'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6315'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6316'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6316'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6317'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6317'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6318'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6318'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6319'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6319'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6320'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6320'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6321'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6321'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6322'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6322'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6323'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6323'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6324'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6324'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '6325'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6325'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '6326'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6326'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6327'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6327'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6328'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6328'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6329'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6329'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6330'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6330'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6331'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6331'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6332'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6332'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6333'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6333'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6334'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6334'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6335'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6335'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6336'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6336'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6337'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6337'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6338'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6338'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6339'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6339'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6340'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6340'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6341'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6341'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '6342'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6342'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6343'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6343'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6344'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6344'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6345'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6345'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6346'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6346'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6347'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6347'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '6348'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6348'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6349'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6349'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6350'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6350'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6351'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6351'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6352'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6352'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6353'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6353'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6354'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6354'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6355'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6355'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6356'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6356'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6357'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6357'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6358'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6358'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6359'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6359'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6360'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6360'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '6361'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6361'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6362'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6362'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6363'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6363'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6364'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6364'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6365'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6365'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6366'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6366'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6367'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6367'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6368'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6368'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6369'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6369'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6370'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6370'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6371'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6371'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6372'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6372'

2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6373'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6373'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6374'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6374'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6375'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6375'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6376'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6376'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6377'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6377'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6378'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6378'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '6379'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6379'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6380'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6380'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6381'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6381'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '6382'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6382'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6383'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6383'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6384'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6384'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6385'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6385'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6386'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6386'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6387'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6387'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6388'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6388'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6389'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6389'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '6390'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6390'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6391'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6391'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6392'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6392'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6393'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6393'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6394'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6394'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6395'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6395'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6396'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6396'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6397'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6397'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6398'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6398'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6399'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6399'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6400'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6400'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '6401'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6401'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6402'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6402'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6403'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6403'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6404'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6404'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6405'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6405'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6406'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6406'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6407'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6407'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6408'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6408'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6409'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6409'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6410'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6410'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6411'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6411'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6412'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6412'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6413'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6413'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6414'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6414'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6415'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6415'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6416'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6416'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6417'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6417'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6418'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6418'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6419'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6419'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6420'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6420'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6421'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6421'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6422'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6422'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6423'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6423'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6424'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6424'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6425'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6425'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6426'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6426'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6427'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6427'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6428'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6428'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6429'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6429'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6430'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6430'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6431'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6431'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '6432'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6432'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6433'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6433'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6434'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6434'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '6435'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6435'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6436'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6436'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '6437'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6437'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6438'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6438'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '6439'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6439'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6440'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6440'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6441'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6441'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6442'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6442'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6443'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6443'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '6444'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6444'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6445'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6445'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6446'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6446'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6447'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6447'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6448'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6448'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6449'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6449'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '6450'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6450'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6451'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6451'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6452'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6452'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6453'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6453'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '6454'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6454'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '6455'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6455'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6456'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6456'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6457'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6457'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6458'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6458'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6459'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6459'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6460'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6460'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6461'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6461'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6462'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6462'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6463'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6463'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '6464'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6464'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6465'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6465'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6466'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6466'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6467'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6467'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6468'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6468'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6469'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6469'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '6470'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6470'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6471'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6471'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6472'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6472'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6473'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6473'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6474'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6474'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6475'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6475'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6476'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6476'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6477'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6477'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6478'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6478'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6479'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6479'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6480'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6480'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '6481'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6481'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6482'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6482'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6483'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6483'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6484'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6484'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6485'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6485'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6486'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6486'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6487'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6487'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '6488'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6488'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6489'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6489'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6490'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6490'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6491'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6491'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6492'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6492'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6493'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6493'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6494'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6494'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6495'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6495'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6496'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6496'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6497'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6497'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6498'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6498'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6499'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6499'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6500'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6500'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6501'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6501'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6502'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6502'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6503'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6503'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6504'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6504'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6505'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6505'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6506'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6506'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6507'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6507'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6508'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6508'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6509'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6509'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6510'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6510'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6511'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6511'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '6512'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6512'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6513'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6513'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '6514'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6514'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6515'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6515'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6516'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6516'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6517'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6517'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6518'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6518'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6519'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6519'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6520'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6520'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6521'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6521'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '6522'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6522'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6523'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6523'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6524'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6524'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6525'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6525'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6526'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6526'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6527'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6527'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6528'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6528'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6529'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6529'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6530'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6530'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6531'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6531'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6532'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6532'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6533'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6533'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6534'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6534'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6535'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6535'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6536'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6536'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6537'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6537'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6538'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6538'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6539'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6539'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6540'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6540'

2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6541'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6541'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6542'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6542'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6543'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6543'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6544'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6544'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6545'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6545'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6546'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6546'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6547'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6547'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6548'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6548'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6549'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6549'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6550'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6550'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6551'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6551'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6552'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6552'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6553'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6553'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6554'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6554'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6555'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6555'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6556'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6556'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6557'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6557'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6558'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6558'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6559'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6559'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6560'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6560'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '6561'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6561'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6562'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6562'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6563'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6563'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6564'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6564'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6565'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6565'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6566'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6566'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6567'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6567'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6568'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6568'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6569'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6569'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6570'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6570'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6571'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6571'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6572'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6572'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6573'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6573'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6574'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6574'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6575'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6575'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6576'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6576'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6577'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6577'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6578'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6578'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6579'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6579'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6580'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6580'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6581'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6581'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6582'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6582'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6583'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6583'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6584'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6584'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '6585'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6585'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6586'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6586'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6587'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6587'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6588'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6588'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6589'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6589'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6590'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6590'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6591'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6591'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6592'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6592'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6593'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6593'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6594'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6594'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6595'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6595'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6596'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6596'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6597'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6597'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6598'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6598'

2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6599'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6599'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6600'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6600'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6601'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6601'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6602'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6602'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6603'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6603'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6604'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6604'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6605'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6605'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6606'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6606'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6607'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6607'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6608'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6608'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6609'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6609'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6610'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6610'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6611'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6611'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6612'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6612'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '6613'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6613'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6614'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6614'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6615'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6615'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6616'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6616'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6617'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6617'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6618'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6618'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '6619'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6619'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6620'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6620'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6621'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6621'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6622'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6622'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6623'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6623'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6624'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6624'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '6625'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6625'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '6626'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6626'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6627'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6627'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6628'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6628'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6629'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6629'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '6630'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6630'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6631'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6631'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '6632'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6632'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6633'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6633'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6634'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6634'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6635'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6635'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '6636'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6636'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6637'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6637'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6638'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6638'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6639'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6639'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6640'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6640'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '6641'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6641'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '6642'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6642'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6643'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6643'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6644'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6644'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6645'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6645'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6646'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6646'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6647'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6647'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6648'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6648'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6649'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6649'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6650'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6650'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6651'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6651'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6652'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6652'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6653'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6653'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6654'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6654'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '6655'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6655'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6656'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6656'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6657'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6657'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6658'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6658'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6659'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6659'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6660'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6660'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6661'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6661'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '6662'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6662'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '6663'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6663'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6664'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6664'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6665'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6665'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6666'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6666'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6667'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6667'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6668'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6668'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6669'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6669'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6670'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6670'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '6671'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6671'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6672'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6672'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6673'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6673'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6674'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6674'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6675'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6675'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6676'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6676'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6677'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6677'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6678'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6678'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6679'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6679'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6680'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6680'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6681'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6681'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6682'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6682'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6683'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6683'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6684'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6684'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6685'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6685'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6686'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6686'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '6687'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6687'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6688'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6688'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6689'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6689'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6690'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6690'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6691'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6691'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6692'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6692'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6693'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6693'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6694'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6694'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6695'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6695'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6696'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6696'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6697'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6697'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6698'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6698'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6699'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6699'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6700'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6700'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6701'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6701'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6702'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6702'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6703'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6703'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6704'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6704'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6705'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6705'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6706'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6706'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6707'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6707'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6708'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6708'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6709'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6709'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6710'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6710'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6711'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6711'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6712'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6712'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6713'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6713'

2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6714'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6714'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6715'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6715'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6716'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6716'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6717'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6717'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6718'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6718'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6719'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6719'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6720'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6720'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6721'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6721'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6722'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6722'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6723'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6723'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6724'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6724'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6725'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6725'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6726'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6726'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6727'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6727'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6728'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6728'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6729'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6729'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6730'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6730'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6731'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6731'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6732'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6732'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6733'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6733'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6734'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6734'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6735'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6735'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6736'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6736'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6737'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6737'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '6738'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6738'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6739'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6739'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6740'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6740'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '6741'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6741'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6742'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6742'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6743'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6743'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6744'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6744'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6745'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6745'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6746'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6746'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6747'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6747'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6748'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6748'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6749'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6749'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6750'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6750'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6751'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6751'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6752'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6752'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6753'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6753'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6754'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6754'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6755'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6755'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6756'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6756'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6757'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6757'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6758'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6758'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6759'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6759'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6760'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6760'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6761'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6761'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6762'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6762'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6763'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6763'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6764'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6764'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6765'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6765'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6766'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6766'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6767'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6767'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6768'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6768'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6769'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6769'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6770'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6770'

2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6771'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6771'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6772'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6772'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6773'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6773'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6774'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6774'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6775'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6775'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6776'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6776'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6777'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6777'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6778'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6778'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6779'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6779'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6780'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6780'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6781'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6781'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6782'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6782'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '6783'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6783'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6784'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6784'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6785'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6785'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6786'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6786'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6787'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6787'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6788'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6788'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6789'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6789'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6790'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6790'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6791'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6791'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6792'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6792'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6793'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6793'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6794'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6794'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6795'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6795'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6796'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6796'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '6797'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6797'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6798'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6798'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6799'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6799'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6800'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6800'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6801'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6801'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '6802'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6802'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6803'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6803'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6804'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6804'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6805'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6805'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6806'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6806'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6807'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6807'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6808'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6808'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6809'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6809'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6810'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6810'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6811'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6811'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6812'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6812'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6813'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6813'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6814'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6814'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6815'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6815'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6816'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6816'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6817'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6817'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6818'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6818'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6819'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6819'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6820'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6820'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '6821'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6821'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6822'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6822'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6823'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6823'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6824'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6824'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6825'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6825'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6826'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6826'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6827'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6827'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6828'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6828'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6829'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6829'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6830'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6830'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6831'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6831'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6832'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6832'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6833'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6833'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6834'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6834'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6835'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6835'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6836'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6836'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6837'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6837'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6838'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6838'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6839'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6839'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6840'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6840'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6841'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6841'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6842'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6842'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6843'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6843'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6844'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6844'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6845'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6845'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6846'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6846'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6847'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6847'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6848'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6848'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6849'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6849'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6850'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6850'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6851'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6851'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6852'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6852'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6853'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6853'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6854'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6854'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6855'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6855'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6856'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6856'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '6857'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6857'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6858'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6858'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6859'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6859'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6860'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6860'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6861'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6861'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6862'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6862'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6863'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6863'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6864'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6864'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6865'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6865'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6866'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6866'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6867'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6867'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6868'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6868'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6869'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6869'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6870'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6870'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6871'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6871'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6872'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6872'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6873'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6873'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6874'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6874'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6875'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6875'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6876'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6876'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6877'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6877'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6878'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6878'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6879'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6879'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6880'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6880'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6881'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6881'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6882'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6882'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6883'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6883'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6884'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6884'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6885'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6885'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6886'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6886'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6887'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6887'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6888'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6888'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6889'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6889'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6890'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6890'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6891'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6891'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6892'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6892'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6893'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6893'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6894'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6894'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '6895'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6895'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6896'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6896'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6897'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6897'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6898'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6898'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6899'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6899'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '6900'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6900'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6901'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6901'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6902'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6902'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6903'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6903'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6904'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6904'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6905'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6905'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6906'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6906'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6907'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6907'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6908'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6908'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6909'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6909'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6910'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6910'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6911'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6911'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6912'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6912'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6913'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6913'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6914'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6914'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6915'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6915'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6916'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6916'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6917'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6917'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6918'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6918'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6919'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6919'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6920'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6920'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6921'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6921'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6922'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6922'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6923'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6923'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6924'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6924'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6925'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6925'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6926'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6926'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6927'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6927'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6928'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6928'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6929'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6929'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6930'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6930'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6931'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6931'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6932'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6932'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6933'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6933'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6934'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6934'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6935'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6935'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6936'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6936'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6937'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6937'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6938'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6938'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6939'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6939'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6940'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6940'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6941'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6941'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6942'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6942'

2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6943'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6943'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6944'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6944'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6945'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6945'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6946'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6946'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6947'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6947'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '6948'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6948'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6949'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6949'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6950'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6950'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6951'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6951'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6952'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6952'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6953'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6953'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6954'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6954'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6955'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6955'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6956'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6956'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6957'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6957'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6958'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6958'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6959'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6959'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6960'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6960'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6961'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6961'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '6962'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6962'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6963'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6963'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6964'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6964'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6965'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6965'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6966'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6966'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6967'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6967'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6968'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6968'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6969'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6969'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '6970'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6970'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6971'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6971'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6972'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6972'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6973'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6973'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6974'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6974'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6975'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6975'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6976'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6976'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6977'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6977'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '6978'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6978'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '6979'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6979'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6980'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6980'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6981'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6981'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6982'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6982'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6983'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6983'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '6984'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6984'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6985'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6985'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6986'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6986'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '6987'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6987'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '6988'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6988'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6989'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6989'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6990'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6990'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6991'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6991'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6992'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6992'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6993'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6993'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6994'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6994'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '6995'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6995'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6996'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6996'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6997'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6997'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '6998'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6998'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '6999'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '6999'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7000'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7000'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7001'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7001'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7002'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7002'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7003'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7003'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7004'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7004'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7005'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7005'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '7006'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7006'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7007'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7007'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7008'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7008'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7009'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7009'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7010'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7010'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '7011'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7011'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7012'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7012'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7013'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7013'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7014'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7014'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7015'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7015'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7016'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7016'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7017'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7017'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7018'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7018'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7019'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7019'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7020'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7020'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7021'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7021'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7022'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7022'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7023'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7023'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7024'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7024'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7025'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7025'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7026'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7026'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7027'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7027'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7028'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7028'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7029'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7029'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7030'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7030'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7031'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7031'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7032'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7032'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7033'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7033'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7034'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7034'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7035'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7035'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7036'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7036'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7037'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7037'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7038'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7038'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '7039'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7039'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7040'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7040'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7041'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7041'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7042'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7042'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7043'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7043'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7044'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7044'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7045'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7045'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7046'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7046'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7047'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7047'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7048'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7048'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7049'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7049'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7050'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7050'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7051'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7051'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7052'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7052'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '7053'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7053'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7054'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7054'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7055'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7055'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7056'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7056'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7057'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7057'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7058'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7058'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7059'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7059'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7060'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7060'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7061'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7061'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7062'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7062'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7063'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7063'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7064'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7064'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7065'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7065'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7066'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7066'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '7067'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7067'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7068'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7068'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7069'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7069'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7070'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7070'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7071'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7071'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7072'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7072'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7073'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7073'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '7074'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7074'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7075'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7075'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '7076'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7076'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7077'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7077'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7078'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7078'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7079'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7079'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7080'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7080'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7081'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7081'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7082'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7082'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7083'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7083'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '7084'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7084'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7085'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7085'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7086'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7086'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7087'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7087'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7088'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7088'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7089'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7089'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7090'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7090'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '7091'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7091'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7092'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7092'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7093'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7093'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7094'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7094'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7095'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7095'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7096'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7096'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7097'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7097'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7098'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7098'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7099'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7099'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7100'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7100'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7101'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7101'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7102'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7102'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7103'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7103'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7104'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7104'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7105'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7105'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7106'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7106'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '7107'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7107'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7108'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7108'

2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7109'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7109'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7110'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7110'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7111'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7111'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7112'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7112'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7113'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7113'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7114'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7114'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7115'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7115'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7116'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7116'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7117'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7117'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7118'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7118'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7119'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7119'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7120'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7120'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7121'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7121'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '7122'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7122'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7123'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7123'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7124'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7124'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7125'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7125'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7126'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7126'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7127'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7127'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7128'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7128'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7129'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7129'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7130'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7130'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7131'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7131'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '7132'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7132'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7133'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7133'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7134'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7134'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7135'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7135'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7136'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7136'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7137'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7137'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7138'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7138'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7139'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7139'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7140'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7140'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7141'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7141'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7142'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7142'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7143'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7143'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7144'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7144'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7145'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7145'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '7146'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7146'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7147'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7147'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7148'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7148'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7149'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7149'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7150'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7150'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7151'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7151'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7152'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7152'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7153'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7153'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7154'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7154'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7155'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7155'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7156'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7156'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7157'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7157'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7158'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7158'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7159'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7159'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7160'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7160'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7161'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7161'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7162'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7162'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7163'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7163'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7164'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7164'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7165'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7165'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7166'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7166'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7167'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7167'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7168'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7168'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7169'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7169'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7170'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7170'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7171'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7171'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '7172'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7172'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7173'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7173'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7174'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7174'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7175'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7175'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7176'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7176'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7177'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7177'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7178'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7178'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7179'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7179'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7180'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7180'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7181'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7181'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7182'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7182'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7183'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7183'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7184'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7184'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7185'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7185'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7186'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7186'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7187'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7187'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7188'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7188'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7189'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7189'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7190'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7190'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7191'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7191'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7192'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7192'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7193'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7193'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7194'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7194'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7195'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7195'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7196'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7196'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7197'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7197'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7198'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7198'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7199'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7199'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7200'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7200'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7201'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7201'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7202'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7202'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7203'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7203'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7204'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7204'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7205'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7205'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7206'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7206'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7207'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7207'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7208'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7208'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7209'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7209'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7210'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7210'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7211'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7211'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7212'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7212'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7213'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7213'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7214'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7214'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7215'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7215'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7216'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7216'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7217'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7217'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7218'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7218'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7219'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7219'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7220'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7220'

2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7221'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7221'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7222'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7222'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7223'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7223'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7224'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7224'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7225'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7225'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7226'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7226'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7227'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7227'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7228'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7228'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7229'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7229'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '7230'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7230'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7231'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7231'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7232'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7232'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7233'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7233'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7234'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7234'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7235'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7235'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7236'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7236'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '7237'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7237'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '7238'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7238'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7239'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7239'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7240'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7240'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7241'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7241'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7242'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7242'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7243'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7243'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7244'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7244'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7245'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7245'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7246'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7246'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7247'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7247'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7248'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7248'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7249'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7249'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7250'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7250'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7251'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7251'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7252'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7252'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7253'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7253'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7254'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7254'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7255'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7255'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '7256'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7256'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7257'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7257'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7258'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7258'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7259'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7259'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7260'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7260'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7261'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7261'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7262'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7262'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7263'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7263'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7264'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7264'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7265'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7265'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7266'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7266'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7267'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7267'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7268'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7268'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7269'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7269'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7270'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7270'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7271'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7271'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7272'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7272'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7273'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7273'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7274'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7274'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7275'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7275'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7276'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7276'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7277'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7277'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7278'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7278'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7279'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7279'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7280'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7280'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7281'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7281'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7282'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7282'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7283'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7283'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7284'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7284'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7285'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7285'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7286'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7286'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7287'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7287'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7288'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7288'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7289'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7289'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7290'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7290'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7291'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7291'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7292'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7292'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7293'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7293'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7294'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7294'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7295'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7295'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7296'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7296'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7297'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7297'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7298'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7298'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7299'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7299'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7300'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7300'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7301'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7301'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '7302'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7302'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7303'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7303'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7304'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7304'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7305'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7305'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7306'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7306'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7307'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7307'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7308'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7308'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7309'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7309'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7310'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7310'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7311'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7311'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7312'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7312'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7313'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7313'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7314'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7314'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '7315'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7315'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7316'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7316'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7317'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7317'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7318'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7318'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7319'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7319'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7320'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7320'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7321'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7321'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7322'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7322'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7323'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7323'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7324'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7324'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7325'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7325'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7326'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7326'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7327'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7327'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7328'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7328'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7329'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7329'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7330'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7330'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7331'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7331'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7332'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7332'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7333'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7333'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7334'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7334'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7335'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7335'

2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7336'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7336'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7337'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7337'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7338'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7338'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7339'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7339'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '7340'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7340'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7341'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7341'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7342'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7342'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7343'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7343'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7344'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7344'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7345'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7345'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7346'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7346'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7347'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7347'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7348'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7348'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7349'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7349'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7350'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7350'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7351'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7351'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '7352'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7352'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7353'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7353'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '7354'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7354'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7355'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7355'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7356'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7356'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7357'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7357'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7358'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7358'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7359'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7359'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7360'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7360'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '7361'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7361'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7362'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7362'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7363'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7363'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7364'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7364'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7365'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7365'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7366'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7366'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7367'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7367'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7368'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7368'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7369'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7369'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7370'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7370'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7371'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7371'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7372'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7372'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7373'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7373'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7374'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7374'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7375'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7375'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7376'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7376'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7377'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7377'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7378'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7378'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7379'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7379'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7380'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7380'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7381'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7381'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7382'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7382'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7383'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7383'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7384'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7384'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7385'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7385'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7386'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7386'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7387'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7387'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7388'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7388'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '7389'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7389'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7390'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7390'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7391'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7391'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7392'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7392'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7393'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7393'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7394'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7394'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7395'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7395'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7396'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7396'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7397'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7397'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7398'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7398'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7399'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7399'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7400'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7400'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7401'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7401'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7402'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7402'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7403'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7403'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7404'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7404'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '7405'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7405'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7406'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7406'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7407'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7407'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7408'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7408'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7409'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7409'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7410'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7410'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7411'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7411'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7412'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7412'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7413'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7413'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7414'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7414'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7415'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7415'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7416'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7416'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7417'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7417'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7418'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7418'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7419'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7419'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7420'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7420'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7421'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7421'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7422'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7422'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7423'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7423'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7424'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7424'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7425'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7425'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7426'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7426'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7427'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7427'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7428'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7428'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7429'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7429'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7430'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7430'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '7431'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7431'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7432'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7432'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7433'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7433'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7434'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7434'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7435'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7435'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7436'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7436'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7437'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7437'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7438'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7438'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7439'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7439'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7440'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7440'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7441'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7441'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7442'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7442'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7443'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7443'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7444'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7444'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7445'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7445'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7446'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7446'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7447'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7447'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7448'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7448'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '7449'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7449'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7450'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7450'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '7451'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7451'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7452'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7452'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7453'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7453'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7454'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7454'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7455'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7455'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7456'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7456'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7457'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7457'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7458'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7458'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7459'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7459'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7460'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7460'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7461'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7461'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7462'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7462'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7463'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7463'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7464'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7464'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7465'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7465'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7466'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7466'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7467'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7467'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7468'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7468'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7469'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7469'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7470'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7470'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7471'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7471'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7472'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7472'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7473'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7473'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7474'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7474'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7475'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7475'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7476'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7476'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7477'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7477'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7478'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7478'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7479'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7479'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7480'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7480'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7481'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7481'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7482'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7482'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7483'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7483'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7484'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7484'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7485'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7485'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7486'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7486'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7487'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7487'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7488'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7488'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7489'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7489'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7490'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7490'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7491'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7491'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7492'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7492'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7493'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7493'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7494'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7494'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7495'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7495'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7496'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7496'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7497'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7497'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7498'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7498'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7499'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7499'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7500'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7500'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7501'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7501'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7502'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7502'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7503'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7503'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7504'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7504'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7505'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7505'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7506'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7506'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7507'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7507'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7508'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7508'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7509'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7509'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7510'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7510'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7511'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7511'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7512'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7512'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7513'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7513'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7514'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7514'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7515'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7515'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7516'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7516'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7517'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7517'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7518'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7518'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '7519'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7519'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7520'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7520'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7521'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7521'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7522'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7522'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7523'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7523'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7524'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7524'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7525'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7525'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7526'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7526'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '7527'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7527'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7528'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7528'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7529'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7529'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7530'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7530'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7531'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7531'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '7532'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7532'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7533'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7533'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7534'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7534'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7535'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7535'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7536'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7536'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '7537'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7537'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7538'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7538'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7539'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7539'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7540'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7540'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7541'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7541'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7542'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7542'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7543'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7543'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7544'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7544'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7545'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7545'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7546'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7546'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7547'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7547'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7548'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7548'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7549'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7549'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7550'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7550'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7551'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7551'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7552'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7552'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7553'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7553'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7554'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7554'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7555'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7555'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7556'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7556'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7557'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7557'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '7558'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7558'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7559'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7559'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7560'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7560'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7561'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7561'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7562'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7562'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7563'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7563'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7564'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7564'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7565'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7565'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '7566'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7566'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7567'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7567'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7568'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7568'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7569'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7569'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7570'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7570'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7571'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7571'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7572'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7572'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '7573'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7573'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7574'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7574'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7575'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7575'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7576'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7576'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7577'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7577'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7578'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7578'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7579'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7579'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7580'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7580'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7581'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7581'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7582'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7582'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7583'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7583'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7584'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7584'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '7585'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7585'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7586'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7586'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7587'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7587'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7588'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7588'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7589'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7589'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7590'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7590'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '7591'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7591'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7592'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7592'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7593'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7593'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7594'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7594'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7595'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7595'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7596'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7596'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7597'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7597'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7598'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7598'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7599'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7599'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7600'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7600'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7601'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7601'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7602'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7602'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7603'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7603'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7604'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7604'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7605'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7605'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7606'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7606'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7607'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7607'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7608'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7608'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7609'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7609'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7610'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7610'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7611'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7611'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7612'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7612'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7613'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7613'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7614'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7614'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7615'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7615'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7616'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7616'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7617'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7617'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7618'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7618'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7619'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7619'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7620'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7620'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7621'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7621'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7622'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7622'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7623'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7623'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7624'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7624'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '7625'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7625'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7626'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7626'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7627'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7627'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7628'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7628'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7629'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7629'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '7630'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7630'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7631'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7631'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7632'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7632'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7633'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7633'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7634'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7634'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '7635'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7635'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7636'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7636'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7637'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7637'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7638'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7638'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7639'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7639'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7640'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7640'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7641'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7641'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7642'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7642'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7643'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7643'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7644'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7644'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7645'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7645'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7646'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7646'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '7647'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7647'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7648'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7648'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7649'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7649'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7650'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7650'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '7651'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7651'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7652'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7652'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7653'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7653'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7654'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7654'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7655'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7655'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7656'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7656'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '7657'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7657'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7658'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7658'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7659'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7659'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7660'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7660'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7661'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7661'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7662'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7662'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '7663'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7663'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7664'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7664'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7665'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7665'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '7666'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7666'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7667'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7667'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '7668'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7668'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7669'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7669'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7670'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7670'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7671'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7671'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7672'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7672'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7673'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7673'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7674'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7674'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7675'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7675'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7676'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7676'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7677'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7677'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7678'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7678'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7679'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7679'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7680'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7680'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7681'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7681'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7682'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7682'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7683'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7683'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7684'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7684'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7685'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7685'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7686'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7686'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7687'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7687'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7688'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7688'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7689'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7689'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7690'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7690'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7691'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7691'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7692'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7692'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7693'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7693'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7694'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7694'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7695'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7695'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7696'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7696'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7697'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7697'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '7698'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7698'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7699'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7699'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7700'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7700'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7701'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7701'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7702'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7702'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7703'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7703'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '7704'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7704'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7705'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7705'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7706'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7706'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7707'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7707'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7708'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7708'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7709'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7709'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7710'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7710'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7711'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7711'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7712'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7712'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7713'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7713'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7714'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7714'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7715'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7715'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7716'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7716'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '7717'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7717'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '7718'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7718'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7719'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7719'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7720'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7720'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7721'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7721'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7722'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7722'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7723'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7723'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7724'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7724'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7725'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7725'

2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7726'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7726'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7727'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7727'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7728'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7728'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7729'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7729'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7730'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7730'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7731'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7731'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7732'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7732'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7733'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7733'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7734'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7734'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7735'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7735'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '7736'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7736'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7737'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7737'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7738'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7738'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7739'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7739'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7740'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7740'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7741'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7741'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7742'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7742'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7743'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7743'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7744'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7744'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7745'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7745'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7746'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7746'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7747'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7747'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7748'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7748'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7749'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7749'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7750'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7750'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7751'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7751'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7752'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7752'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7753'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7753'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7754'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7754'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7755'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7755'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7756'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7756'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7757'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7757'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7758'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7758'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7759'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7759'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7760'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7760'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7761'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7761'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7762'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7762'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7763'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7763'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7764'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7764'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7765'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7765'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7766'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7766'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7767'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7767'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7768'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7768'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '7769'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7769'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7770'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7770'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7771'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7771'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7772'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7772'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7773'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7773'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7774'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7774'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '7775'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7775'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7776'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7776'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7777'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7777'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7778'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7778'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7779'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7779'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7780'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7780'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7781'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7781'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '7782'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7782'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7783'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7783'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7784'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7784'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '7785'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7785'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7786'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7786'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7787'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7787'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7788'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7788'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7789'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7789'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '7790'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7790'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '7791'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7791'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7792'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7792'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7793'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7793'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7794'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7794'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7795'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7795'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7796'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7796'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7797'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7797'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7798'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7798'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7799'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7799'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7800'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7800'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7801'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7801'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7802'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7802'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7803'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7803'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7804'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7804'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '7805'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7805'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7806'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7806'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7807'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7807'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7808'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7808'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7809'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7809'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7810'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7810'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7811'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7811'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7812'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7812'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7813'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7813'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7814'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7814'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7815'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7815'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7816'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7816'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7817'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7817'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7818'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7818'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7819'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7819'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7820'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7820'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7821'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7821'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7822'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7822'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7823'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7823'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7824'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7824'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7825'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7825'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7826'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7826'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7827'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7827'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7828'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7828'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7829'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7829'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7830'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7830'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7831'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7831'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7832'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7832'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7833'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7833'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7834'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7834'

2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7835'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7835'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7836'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7836'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7837'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7837'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7838'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7838'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '7839'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7839'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7840'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7840'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7841'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7841'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7842'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7842'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7843'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7843'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7844'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7844'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7845'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7845'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7846'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7846'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7847'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7847'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7848'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7848'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7849'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7849'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7850'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7850'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7851'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7851'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7852'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7852'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7853'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7853'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7854'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7854'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7855'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7855'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7856'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7856'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7857'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7857'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7858'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7858'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7859'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7859'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7860'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7860'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '7861'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7861'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7862'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7862'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7863'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7863'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7864'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7864'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7865'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7865'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7866'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7866'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '7867'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7867'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7868'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7868'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7869'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7869'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7870'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7870'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7871'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7871'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7872'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7872'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7873'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7873'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7874'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7874'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7875'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7875'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7876'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7876'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7877'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7877'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '7878'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7878'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7879'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7879'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '7880'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7880'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '7881'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7881'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7882'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7882'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7883'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7883'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7884'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7884'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7885'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7885'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7886'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7886'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7887'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7887'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7888'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7888'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7889'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7889'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7890'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7890'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7891'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7891'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7892'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7892'

2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7893'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7893'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7894'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7894'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7895'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7895'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7896'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7896'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7897'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7897'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7898'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7898'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7899'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7899'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7900'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7900'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7901'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7901'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7902'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7902'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7903'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7903'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7904'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7904'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '7905'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7905'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7906'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7906'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7907'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7907'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7908'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7908'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7909'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7909'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7910'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7910'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '7911'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7911'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7912'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7912'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7913'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7913'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7914'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7914'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7915'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7915'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7916'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7916'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7917'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7917'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7918'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7918'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7919'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7919'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7920'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7920'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7921'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7921'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7922'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7922'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7923'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7923'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7924'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7924'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7925'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7925'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7926'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7926'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7927'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7927'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7928'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7928'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7929'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7929'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7930'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7930'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '7931'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7931'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '7932'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7932'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7933'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7933'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '7934'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7934'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7935'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7935'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7936'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7936'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7937'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7937'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7938'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7938'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7939'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7939'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7940'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7940'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7941'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7941'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7942'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7942'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7943'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7943'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7944'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7944'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7945'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7945'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7946'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7946'

2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7947'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7947'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7948'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7948'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7949'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7949'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7950'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7950'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7951'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7951'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7952'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7952'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7953'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7953'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7954'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7954'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7955'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7955'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7956'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7956'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7957'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7957'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7958'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7958'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7959'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7959'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7960'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7960'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7961'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7961'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7962'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7962'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7963'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7963'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7964'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7964'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7965'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7965'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7966'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7966'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7967'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7967'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7968'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7968'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7969'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7969'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7970'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7970'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7971'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7971'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7972'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7972'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7973'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7973'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7974'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7974'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7975'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7975'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7976'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7976'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7977'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7977'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7978'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7978'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7979'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7979'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7980'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7980'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '7981'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7981'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7982'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7982'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '7983'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7983'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7984'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7984'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7985'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7985'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '7986'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7986'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7987'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7987'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '7988'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7988'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7989'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7989'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7990'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7990'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7991'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7991'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7992'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7992'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '7993'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7993'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7994'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7994'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7995'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7995'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7996'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7996'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '7997'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7997'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7998'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7998'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '7999'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '7999'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8000'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8000'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8001'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8001'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8002'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8002'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8003'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8003'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8004'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8004'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8005'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8005'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8006'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8006'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8007'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8007'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8008'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8008'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8009'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8009'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8010'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8010'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '8011'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8011'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8012'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8012'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8013'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8013'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8014'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8014'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8015'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8015'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8016'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8016'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8017'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8017'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8018'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8018'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8019'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8019'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8020'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8020'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8021'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8021'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8022'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8022'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8023'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8023'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '8024'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8024'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8025'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8025'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '8026'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8026'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8027'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8027'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8028'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8028'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '8029'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8029'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '8030'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8030'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8031'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8031'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8032'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8032'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8033'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8033'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8034'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8034'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8035'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8035'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8036'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8036'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8037'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8037'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8038'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8038'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8039'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8039'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8040'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8040'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8041'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8041'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8042'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8042'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8043'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8043'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8044'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8044'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8045'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8045'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8046'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8046'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8047'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8047'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8048'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8048'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8049'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8049'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8050'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8050'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8051'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8051'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '8052'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8052'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8053'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8053'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8054'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8054'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8055'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8055'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8056'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8056'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8057'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8057'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8058'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8058'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8059'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8059'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8060'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8060'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8061'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8061'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8062'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8062'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8063'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8063'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8064'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8064'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8065'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8065'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8066'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8066'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8067'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8067'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8068'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8068'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8069'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8069'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8070'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8070'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8071'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8071'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8072'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8072'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8073'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8073'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8074'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8074'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8075'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8075'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8076'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8076'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8077'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8077'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8078'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8078'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '8079'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8079'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8080'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8080'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8081'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8081'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8082'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8082'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8083'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8083'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8084'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8084'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8085'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8085'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '8086'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8086'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8087'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8087'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8088'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8088'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '8089'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8089'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8090'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8090'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8091'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8091'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8092'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8092'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8093'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8093'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8094'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8094'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8095'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8095'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8096'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8096'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8097'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8097'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8098'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8098'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8099'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8099'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '8100'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8100'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8101'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8101'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8102'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8102'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8103'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8103'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8104'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8104'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8105'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8105'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '8106'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8106'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '8107'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8107'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8108'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8108'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8109'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8109'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '8110'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8110'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '8111'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8111'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8112'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8112'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8113'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8113'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8114'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8114'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8115'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8115'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8116'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8116'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8117'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8117'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '8118'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8118'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8119'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8119'

2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8120'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8120'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8121'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8121'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8122'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8122'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8123'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8123'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8124'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8124'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8125'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8125'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '8126'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8126'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8127'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8127'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8128'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8128'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8129'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8129'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8130'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8130'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8131'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8131'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8132'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8132'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8133'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8133'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8134'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8134'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8135'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8135'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8136'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8136'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8137'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8137'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8138'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8138'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8139'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8139'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8140'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8140'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8141'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8141'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8142'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8142'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8143'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8143'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8144'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8144'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8145'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8145'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8146'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8146'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8147'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8147'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8148'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8148'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '8149'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8149'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8150'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8150'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8151'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8151'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8152'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8152'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8153'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8153'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8154'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8154'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8155'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8155'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8156'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8156'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '8157'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8157'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8158'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8158'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8159'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8159'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8160'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8160'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '8161'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8161'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '8162'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8162'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8163'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8163'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8164'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8164'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8165'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8165'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '8166'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8166'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8167'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8167'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8168'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8168'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8169'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8169'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8170'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8170'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8171'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8171'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '8172'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8172'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8173'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8173'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8174'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8174'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8175'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8175'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8176'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8176'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8177'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8177'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8178'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8178'

2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8179'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8179'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '8180'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8180'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8181'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8181'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8182'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8182'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '8183'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8183'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8184'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8184'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '8185'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8185'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8186'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8186'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8187'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8187'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8188'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8188'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8189'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8189'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8190'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8190'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8191'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8191'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8192'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8192'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8193'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8193'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8194'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8194'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8195'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8195'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8196'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8196'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '8197'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8197'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8198'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8198'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8199'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8199'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8200'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8200'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '8201'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8201'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8202'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8202'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8203'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8203'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8204'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8204'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8205'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8205'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '8206'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8206'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8207'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8207'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8208'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8208'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8209'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8209'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '8210'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8210'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8211'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8211'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8212'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8212'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8213'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8213'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '8214'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8214'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '8215'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8215'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8216'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8216'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8217'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8217'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8218'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8218'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8219'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8219'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '8220'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8220'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8221'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8221'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '8222'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8222'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8223'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8223'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8224'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8224'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8225'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8225'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8226'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8226'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8227'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8227'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8228'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8228'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '8229'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8229'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '8230'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8230'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8231'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8231'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '8232'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8232'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8233'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8233'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8234'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8234'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8235'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8235'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8236'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8236'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8237'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8237'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8238'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8238'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8239'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8239'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8240'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8240'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8241'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8241'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8242'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8242'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8243'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8243'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8244'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8244'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8245'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8245'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8246'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8246'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8247'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8247'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8248'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8248'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8249'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8249'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8250'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8250'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8251'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8251'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8252'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8252'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8253'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8253'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8254'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8254'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8255'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8255'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '8256'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8256'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8257'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8257'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8258'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8258'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8259'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8259'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8260'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8260'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8261'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8261'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8262'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8262'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8263'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8263'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8264'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8264'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8265'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8265'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8266'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8266'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8267'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8267'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8268'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8268'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8269'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8269'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8270'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8270'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8271'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8271'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8272'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8272'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8273'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8273'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8274'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8274'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8275'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8275'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8276'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8276'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8277'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8277'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8278'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8278'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8279'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8279'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8280'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8280'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8281'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8281'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8282'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8282'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8283'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8283'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8284'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8284'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8285'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8285'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8286'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8286'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8287'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8287'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8288'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8288'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8289'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8289'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8290'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8290'

2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8291'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8291'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8292'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8292'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8293'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8293'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8294'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8294'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '8295'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8295'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '8296'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8296'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8297'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8297'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8298'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8298'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8299'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8299'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8300'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8300'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8301'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8301'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8302'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8302'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8303'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8303'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8304'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8304'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8305'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8305'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8306'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8306'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8307'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8307'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8308'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8308'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8309'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8309'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8310'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8310'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8311'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8311'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8312'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8312'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8313'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8313'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8314'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8314'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8315'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8315'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8316'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8316'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8317'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8317'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8318'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8318'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8319'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8319'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8320'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8320'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8321'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8321'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8322'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8322'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8323'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8323'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8324'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8324'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8325'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8325'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8326'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8326'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8327'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8327'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8328'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8328'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8329'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8329'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8330'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8330'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8331'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8331'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8332'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8332'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8333'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8333'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8334'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8334'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '8335'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8335'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8336'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8336'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '8337'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8337'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8338'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8338'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8339'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8339'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8340'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8340'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8341'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8341'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8342'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8342'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8343'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8343'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8344'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8344'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8345'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8345'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8346'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8346'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8347'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8347'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '8348'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8348'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8349'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8349'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8350'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8350'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8351'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8351'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8352'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8352'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8353'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8353'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8354'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8354'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8355'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8355'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8356'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8356'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8357'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8357'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8358'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8358'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8359'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8359'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8360'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8360'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8361'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8361'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8362'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8362'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8363'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8363'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8364'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8364'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8365'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8365'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8366'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8366'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8367'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8367'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8368'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8368'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8369'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8369'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8370'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8370'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8371'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8371'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8372'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8372'
2022-06-01
UPDATE job_vacancies SET open =  '2022-06-01' where raw_id = '8373'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8373'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '8374'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8374'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8375'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8375'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8376'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8376'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8377'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8377'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8378'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8378'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8379'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8379'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8380'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8380'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8381'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8381'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8382'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8382'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8383'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8383'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '8384'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8384'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8385'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8385'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8386'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8386'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8387'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8387'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8388'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8388'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8389'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8389'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8390'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8390'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8391'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8391'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8392'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8392'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8393'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8393'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8394'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8394'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8395'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8395'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8396'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8396'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '8397'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8397'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8398'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8398'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8399'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8399'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8400'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8400'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8401'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8401'

2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8402'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8402'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '8403'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8403'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8404'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8404'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8405'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8405'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8406'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8406'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8407'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8407'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8408'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8408'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8409'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8409'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8410'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8410'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8411'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8411'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8412'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8412'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8413'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8413'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8414'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8414'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8415'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8415'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8416'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8416'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8417'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8417'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8418'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8418'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8419'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8419'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8420'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8420'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8421'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8421'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8422'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8422'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8423'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8423'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8424'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8424'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8425'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8425'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8426'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8426'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '8427'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8427'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8428'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8428'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8429'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8429'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8430'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8430'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8431'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8431'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '8432'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8432'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8433'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8433'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8434'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8434'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8435'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8435'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8436'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8436'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8437'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8437'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '8438'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8438'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8439'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8439'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8440'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8440'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8441'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8441'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8442'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8442'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8443'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8443'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8444'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8444'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8445'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8445'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8446'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8446'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8447'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8447'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8448'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8448'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8449'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8449'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8450'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8450'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8451'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8451'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8452'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8452'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8453'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8453'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8454'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8454'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8455'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8455'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8456'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8456'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8457'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8457'

2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '8458'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8458'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8459'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8459'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8460'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8460'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8461'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8461'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8462'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8462'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8463'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8463'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '8464'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8464'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8465'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8465'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8466'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8466'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8467'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8467'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8468'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8468'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8469'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8469'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8470'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8470'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8471'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8471'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8472'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8472'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8473'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8473'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8474'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8474'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8475'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8475'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8476'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8476'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8477'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8477'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8478'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8478'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8479'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8479'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8480'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8480'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8481'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8481'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8482'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8482'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8483'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8483'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8484'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8484'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8485'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8485'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8486'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8486'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8487'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8487'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8488'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8488'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8489'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8489'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8490'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8490'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8491'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8491'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '8492'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8492'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8493'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8493'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8494'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8494'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8495'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8495'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8496'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8496'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8497'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8497'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8498'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8498'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '8499'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8499'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8500'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8500'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8501'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8501'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8502'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8502'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8503'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8503'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8504'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8504'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8505'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8505'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8506'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8506'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8507'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8507'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8508'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8508'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8509'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8509'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8510'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8510'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8511'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8511'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8512'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8512'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8513'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8513'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8514'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8514'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8515'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8515'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8516'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8516'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8517'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8517'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8518'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8518'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8519'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8519'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8520'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8520'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8521'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8521'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8522'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8522'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8523'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8523'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '8524'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8524'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8525'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8525'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8526'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8526'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8527'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8527'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8528'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8528'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8529'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8529'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8530'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8530'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8531'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8531'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8532'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8532'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8533'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8533'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8534'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8534'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8535'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8535'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '8536'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8536'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '8537'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8537'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8538'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8538'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8539'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8539'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8540'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8540'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '8541'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8541'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8542'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8542'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8543'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8543'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8544'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8544'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8545'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8545'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8546'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8546'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8547'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8547'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8548'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8548'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8549'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8549'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8550'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8550'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8551'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8551'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8552'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8552'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '8553'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8553'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8554'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8554'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8555'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8555'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8556'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8556'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8557'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8557'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8558'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8558'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8559'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8559'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8560'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8560'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8561'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8561'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8562'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8562'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '8563'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8563'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8564'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8564'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8565'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8565'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8566'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8566'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8567'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8567'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8568'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8568'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8569'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8569'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8570'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8570'

2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '8571'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8571'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8572'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8572'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8573'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8573'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8574'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8574'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8575'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8575'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '8576'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8576'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8577'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8577'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8578'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8578'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8579'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8579'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8580'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8580'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8581'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8581'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8582'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8582'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '8583'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8583'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8584'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8584'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8585'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8585'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '8586'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8586'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8587'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8587'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8588'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8588'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8589'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8589'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8590'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8590'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8591'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8591'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8592'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8592'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8593'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8593'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8594'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8594'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8595'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8595'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8596'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8596'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8597'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8597'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8598'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8598'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8599'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8599'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8600'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8600'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8601'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8601'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8602'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8602'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8603'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8603'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '8604'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8604'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8605'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8605'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8606'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8606'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8607'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8607'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8608'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8608'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8609'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8609'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8610'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8610'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8611'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8611'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8612'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8612'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8613'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8613'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8614'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8614'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8615'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8615'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8616'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8616'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '8617'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8617'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8618'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8618'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8619'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8619'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8620'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8620'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8621'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8621'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8622'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8622'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8623'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8623'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '8624'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8624'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8625'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8625'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8626'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8626'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8627'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8627'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '8628'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8628'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8629'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8629'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8630'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8630'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8631'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8631'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8632'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8632'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8633'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8633'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8634'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8634'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8635'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8635'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8636'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8636'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '8637'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8637'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8638'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8638'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8639'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8639'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8640'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8640'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8641'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8641'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8642'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8642'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8643'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8643'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '8644'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8644'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8645'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8645'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '8646'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8646'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8647'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8647'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8648'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8648'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '8649'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8649'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8650'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8650'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8651'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8651'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8652'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8652'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '8653'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8653'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8654'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8654'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8655'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8655'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8656'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8656'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8657'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8657'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8658'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8658'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8659'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8659'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8660'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8660'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8661'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8661'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8662'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8662'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8663'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8663'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8664'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8664'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8665'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8665'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '8666'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8666'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8667'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8667'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8668'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8668'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8669'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8669'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8670'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8670'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8671'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8671'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8672'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8672'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8673'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8673'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8674'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8674'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '8675'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8675'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8676'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8676'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8677'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8677'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8678'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8678'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8679'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8679'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8680'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8680'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8681'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8681'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8682'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8682'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8683'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8683'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8684'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8684'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '8685'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8685'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8686'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8686'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8687'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8687'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8688'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8688'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8689'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8689'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8690'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8690'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8691'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8691'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8692'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8692'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8693'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8693'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8694'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8694'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8695'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8695'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8696'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8696'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8697'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8697'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8698'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8698'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8699'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8699'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8700'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8700'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '8701'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8701'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '8702'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8702'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8703'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8703'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8704'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8704'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8705'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8705'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8706'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8706'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8707'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8707'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8708'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8708'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8709'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8709'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8710'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8710'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8711'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8711'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8712'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8712'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8713'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8713'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8714'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8714'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8715'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8715'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8716'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8716'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8717'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8717'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8718'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8718'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '8719'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8719'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8720'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8720'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '8721'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8721'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8722'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8722'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8723'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8723'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8724'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8724'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '8725'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8725'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8726'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8726'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '8727'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8727'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8728'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8728'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '8729'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8729'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8730'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8730'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8731'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8731'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8732'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8732'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '8733'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8733'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '8734'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8734'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8735'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8735'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8736'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8736'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8737'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8737'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8738'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8738'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '8739'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8739'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8740'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8740'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '8741'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8741'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '8742'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8742'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8743'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8743'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8744'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8744'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8745'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8745'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8746'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8746'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8747'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8747'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8748'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8748'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8749'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8749'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8750'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8750'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8751'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8751'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8752'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8752'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8753'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8753'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8754'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8754'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '8755'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8755'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8756'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8756'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8757'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8757'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8758'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8758'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8759'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8759'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8760'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8760'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8761'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8761'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8762'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8762'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8763'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8763'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8764'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8764'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8765'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8765'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8766'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8766'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8767'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8767'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8768'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8768'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8769'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8769'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8770'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8770'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8771'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8771'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8772'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8772'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8773'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8773'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8774'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8774'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8775'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8775'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8776'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8776'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8777'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8777'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8778'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8778'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8779'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8779'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8780'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8780'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8781'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8781'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8782'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8782'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8783'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8783'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8784'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8784'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '8785'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8785'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8786'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8786'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8787'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8787'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8788'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8788'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8789'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8789'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8790'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8790'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8791'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8791'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8792'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8792'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8793'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8793'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8794'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8794'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8795'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8795'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8796'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8796'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8797'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8797'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8798'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8798'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8799'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8799'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8800'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8800'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8801'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8801'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8802'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8802'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8803'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8803'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8804'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8804'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8805'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8805'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8806'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8806'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8807'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8807'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8808'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8808'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8809'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8809'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8810'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8810'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8811'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8811'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '8812'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8812'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8813'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8813'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '8814'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8814'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8815'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8815'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8816'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8816'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8817'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8817'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8818'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8818'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8819'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8819'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8820'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8820'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8821'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8821'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8822'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8822'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '8823'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8823'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8824'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8824'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8825'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8825'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8826'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8826'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8827'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8827'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8828'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8828'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8829'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8829'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8830'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8830'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8831'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8831'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8832'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8832'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8833'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8833'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8834'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8834'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8835'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8835'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8836'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8836'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8837'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8837'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8838'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8838'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8839'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8839'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8840'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8840'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8841'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8841'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8842'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8842'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8843'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8843'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8844'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8844'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8845'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8845'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8846'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8846'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8847'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8847'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8848'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8848'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '8849'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8849'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8850'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8850'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8851'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8851'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8852'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8852'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8853'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8853'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8854'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8854'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8855'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8855'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8856'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8856'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8857'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8857'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8858'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8858'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8859'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8859'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8860'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8860'

2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8861'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8861'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8862'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8862'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8863'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8863'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8864'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8864'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8865'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8865'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8866'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8866'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8867'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8867'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8868'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8868'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8869'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8869'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8870'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8870'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8871'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8871'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8872'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8872'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8873'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8873'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8874'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8874'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '8875'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8875'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8876'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8876'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8877'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8877'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '8878'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8878'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '8879'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8879'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8880'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8880'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8881'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8881'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8882'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8882'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8883'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8883'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8884'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8884'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '8885'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8885'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8886'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8886'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8887'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8887'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8888'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8888'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8889'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8889'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8890'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8890'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8891'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8891'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '8892'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8892'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8893'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8893'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8894'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8894'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8895'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8895'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8896'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8896'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8897'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8897'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8898'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8898'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8899'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8899'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8900'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8900'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8901'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8901'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8902'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8902'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8903'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8903'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8904'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8904'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8905'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8905'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8906'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8906'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '8907'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8907'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8908'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8908'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8909'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8909'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8910'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8910'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8911'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8911'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '8912'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8912'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8913'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8913'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8914'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8914'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8915'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8915'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8916'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8916'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8917'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8917'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8918'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8918'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8919'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8919'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8920'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8920'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8921'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8921'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8922'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8922'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8923'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8923'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8924'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8924'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8925'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8925'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8926'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8926'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '8927'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8927'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8928'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8928'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8929'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8929'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8930'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8930'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8931'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8931'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8932'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8932'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '8933'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8933'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8934'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8934'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8935'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8935'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8936'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8936'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '8937'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8937'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8938'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8938'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8939'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8939'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '8940'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8940'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8941'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8941'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8942'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8942'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8943'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8943'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8944'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8944'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8945'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8945'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8946'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8946'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '8947'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8947'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8948'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8948'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8949'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8949'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8950'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8950'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8951'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8951'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8952'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8952'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8953'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8953'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '8954'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8954'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8955'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8955'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8956'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8956'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8957'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8957'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8958'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8958'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8959'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8959'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8960'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8960'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8961'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8961'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8962'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8962'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8963'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8963'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '8964'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8964'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8965'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8965'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8966'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8966'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8967'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8967'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '8968'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8968'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '8969'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8969'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8970'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8970'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8971'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8971'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8972'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8972'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8973'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8973'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8974'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8974'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8975'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8975'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '8976'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8976'

2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8977'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8977'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '8978'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8978'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8979'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8979'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '8980'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8980'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8981'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8981'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8982'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8982'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8983'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8983'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8984'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8984'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '8985'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8985'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8986'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8986'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8987'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8987'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8988'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8988'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8989'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8989'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8990'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8990'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8991'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8991'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8992'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8992'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8993'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8993'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8994'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8994'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8995'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8995'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '8996'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8996'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8997'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8997'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '8998'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8998'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '8999'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '8999'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9000'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9000'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9001'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9001'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9002'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9002'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9003'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9003'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9004'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9004'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9005'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9005'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9006'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9006'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9007'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9007'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9008'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9008'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9009'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9009'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9010'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9010'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9011'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9011'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9012'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9012'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9013'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9013'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '9014'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9014'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9015'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9015'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9016'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9016'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9017'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9017'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9018'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9018'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9019'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9019'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9020'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9020'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9021'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9021'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9022'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9022'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9023'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9023'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9024'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9024'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9025'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9025'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9026'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9026'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9027'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9027'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9028'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9028'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9029'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9029'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9030'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9030'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9031'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9031'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9032'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9032'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9033'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9033'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9034'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9034'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9035'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9035'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9036'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9036'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9037'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9037'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9038'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9038'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9039'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9039'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9040'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9040'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9041'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9041'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9042'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9042'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9043'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9043'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9044'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9044'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9045'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9045'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9046'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9046'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9047'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9047'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9048'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9048'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9049'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9049'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9050'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9050'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9051'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9051'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9052'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9052'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9053'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9053'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9054'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9054'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9055'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9055'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9056'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9056'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9057'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9057'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '9058'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9058'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '9059'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9059'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '9060'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9060'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9061'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9061'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9062'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9062'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9063'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9063'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9064'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9064'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9065'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9065'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9066'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9066'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9067'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9067'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9068'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9068'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9069'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9069'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9070'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9070'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9071'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9071'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9072'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9072'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9073'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9073'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9074'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9074'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9075'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9075'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9076'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9076'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9077'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9077'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '9078'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9078'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9079'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9079'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9080'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9080'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9081'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9081'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9082'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9082'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9083'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9083'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9084'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9084'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9085'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9085'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9086'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9086'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '9087'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9087'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9088'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9088'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '9089'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9089'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9090'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9090'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9091'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9091'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9092'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9092'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9093'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9093'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '9094'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9094'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9095'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9095'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9096'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9096'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9097'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9097'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9098'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9098'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9099'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9099'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9100'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9100'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9101'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9101'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9102'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9102'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9103'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9103'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9104'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9104'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9105'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9105'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9106'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9106'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9107'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9107'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9108'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9108'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9109'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9109'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '9110'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9110'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9111'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9111'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9112'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9112'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9113'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9113'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9114'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9114'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '9115'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9115'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9116'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9116'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9117'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9117'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9118'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9118'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9119'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9119'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9120'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9120'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9121'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9121'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9122'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9122'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9123'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9123'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9124'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9124'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9125'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9125'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9126'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9126'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9127'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9127'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9128'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9128'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9129'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9129'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9130'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9130'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9131'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9131'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9132'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9132'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9133'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9133'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9134'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9134'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9135'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9135'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9136'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9136'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9137'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9137'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9138'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9138'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '9139'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9139'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9140'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9140'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9141'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9141'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9142'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9142'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9143'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9143'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '9144'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9144'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9145'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9145'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9146'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9146'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '9147'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9147'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9148'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9148'
2022-05-31
UPDATE job_vacancies SET open =  '2022-05-31' where raw_id = '9149'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9149'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9150'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9150'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9151'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9151'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9152'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9152'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9153'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9153'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9154'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9154'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9155'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9155'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9156'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9156'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9157'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9157'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9158'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9158'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9159'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9159'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9160'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9160'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9161'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9161'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '9162'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9162'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9163'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9163'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9164'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9164'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9165'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9165'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9166'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9166'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9167'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9167'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9168'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9168'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9169'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9169'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9170'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9170'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9171'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9171'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9172'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9172'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9173'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9173'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9174'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9174'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9175'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9175'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9176'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9176'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9177'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9177'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9178'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9178'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9179'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9179'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9180'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9180'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9181'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9181'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9182'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9182'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9183'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9183'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9184'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9184'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9185'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9185'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9186'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9186'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9187'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9187'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '9188'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9188'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9189'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9189'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9190'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9190'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9191'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9191'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9192'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9192'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9193'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9193'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9194'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9194'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9195'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9195'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9196'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9196'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9197'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9197'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9198'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9198'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9199'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9199'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9200'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9200'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9201'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9201'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '9202'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9202'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9203'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9203'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9204'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9204'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9205'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9205'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9206'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9206'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9207'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9207'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9208'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9208'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9209'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9209'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9210'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9210'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9211'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9211'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9212'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9212'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9213'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9213'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9214'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9214'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9215'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9215'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9216'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9216'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9217'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9217'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9218'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9218'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9219'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9219'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9220'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9220'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '9221'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9221'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9222'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9222'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9223'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9223'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9224'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9224'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9225'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9225'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9226'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9226'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9227'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9227'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9228'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9228'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9229'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9229'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9230'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9230'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9231'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9231'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9232'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9232'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9233'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9233'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9234'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9234'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9235'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9235'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9236'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9236'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9237'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9237'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9238'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9238'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9239'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9239'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '9240'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9240'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9241'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9241'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9242'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9242'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9243'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9243'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9244'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9244'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9245'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9245'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9246'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9246'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9247'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9247'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '9248'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9248'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9249'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9249'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9250'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9250'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9251'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9251'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9252'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9252'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9253'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9253'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9254'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9254'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9255'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9255'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9256'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9256'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9257'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9257'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9258'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9258'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '9259'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9259'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9260'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9260'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9261'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9261'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9262'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9262'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '9263'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9263'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9264'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9264'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9265'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9265'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9266'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9266'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9267'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9267'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '9268'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9268'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9269'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9269'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9270'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9270'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9271'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9271'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9272'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9272'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9273'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9273'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '9274'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9274'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9275'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9275'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9276'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9276'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9277'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9277'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9278'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9278'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9279'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9279'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9280'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9280'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9281'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9281'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9282'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9282'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9283'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9283'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '9284'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9284'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9285'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9285'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '9286'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9286'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9287'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9287'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9288'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9288'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9289'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9289'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9290'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9290'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '9291'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9291'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9292'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9292'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9293'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9293'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9294'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9294'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9295'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9295'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9296'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9296'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9297'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9297'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9298'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9298'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9299'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9299'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9300'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9300'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '9301'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9301'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9302'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9302'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9303'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9303'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9304'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9304'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9305'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9305'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9306'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9306'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9307'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9307'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9308'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9308'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9309'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9309'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9310'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9310'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9311'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9311'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9312'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9312'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9313'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9313'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9314'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9314'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9315'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9315'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9316'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9316'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9317'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9317'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9318'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9318'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '9319'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9319'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9320'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9320'

2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9321'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9321'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9322'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9322'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9323'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9323'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9324'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9324'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9325'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9325'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9326'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9326'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9327'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9327'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9328'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9328'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9329'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9329'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9330'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9330'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9331'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9331'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9332'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9332'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '9333'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9333'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '9334'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9334'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9335'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9335'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '9336'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9336'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9337'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9337'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9338'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9338'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9339'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9339'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9340'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9340'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9341'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9341'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9342'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9342'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9343'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9343'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9344'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9344'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9345'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9345'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9346'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9346'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9347'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9347'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9348'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9348'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9349'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9349'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9350'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9350'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9351'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9351'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9352'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9352'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9353'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9353'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9354'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9354'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9355'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9355'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9356'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9356'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9357'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9357'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9358'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9358'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9359'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9359'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9360'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9360'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9361'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9361'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9362'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9362'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9363'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9363'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '9364'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9364'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '9365'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9365'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9366'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9366'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9367'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9367'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9368'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9368'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9369'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9369'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9370'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9370'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9371'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9371'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9372'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9372'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9373'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9373'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9374'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9374'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9375'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9375'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9376'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9376'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9377'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9377'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9378'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9378'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '9379'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9379'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9380'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9380'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9381'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9381'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9382'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9382'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9383'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9383'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9384'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9384'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9385'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9385'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9386'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9386'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9387'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9387'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9388'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9388'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9389'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9389'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9390'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9390'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9391'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9391'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9392'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9392'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9393'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9393'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9394'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9394'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9395'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9395'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9396'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9396'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9397'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9397'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9398'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9398'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9399'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9399'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9400'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9400'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9401'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9401'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9402'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9402'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9403'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9403'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9404'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9404'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9405'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9405'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9406'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9406'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9407'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9407'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9408'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9408'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9409'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9409'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9410'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9410'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9411'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9411'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9412'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9412'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9413'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9413'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9414'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9414'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9415'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9415'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9416'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9416'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9417'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9417'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9418'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9418'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9419'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9419'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9420'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9420'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9421'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9421'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9422'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9422'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9423'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9423'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9424'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9424'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9425'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9425'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '9426'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9426'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9427'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9427'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9428'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9428'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9429'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9429'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9430'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9430'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '9431'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9431'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '9432'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9432'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9433'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9433'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9434'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9434'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9435'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9435'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9436'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9436'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9437'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9437'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9438'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9438'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '9439'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9439'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9440'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9440'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '9441'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9441'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9442'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9442'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9443'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9443'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9444'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9444'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9445'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9445'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '9446'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9446'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9447'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9447'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '9448'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9448'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9449'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9449'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9450'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9450'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9451'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9451'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9452'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9452'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9453'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9453'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '9454'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9454'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9455'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9455'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '9456'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9456'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9457'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9457'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9458'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9458'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9459'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9459'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9460'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9460'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9461'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9461'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9462'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9462'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9463'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9463'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9464'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9464'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9465'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9465'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9466'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9466'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9467'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9467'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9468'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9468'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9469'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9469'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9470'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9470'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9471'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9471'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9472'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9472'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9473'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9473'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9474'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9474'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9475'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9475'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9476'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9476'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9477'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9477'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9478'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9478'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9479'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9479'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9480'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9480'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9481'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9481'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9482'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9482'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9483'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9483'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9484'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9484'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9485'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9485'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9486'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9486'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9487'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9487'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9488'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9488'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9489'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9489'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9490'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9490'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9491'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9491'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9492'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9492'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9493'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9493'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9494'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9494'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9495'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9495'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9496'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9496'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9497'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9497'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9498'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9498'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9499'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9499'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9500'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9500'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9501'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9501'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9502'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9502'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9503'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9503'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9504'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9504'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9505'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9505'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9506'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9506'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9507'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9507'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9508'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9508'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9509'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9509'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9510'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9510'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9511'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9511'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9512'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9512'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '9513'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9513'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9514'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9514'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9515'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9515'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9516'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9516'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9517'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9517'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9518'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9518'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9519'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9519'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9520'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9520'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9521'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9521'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9522'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9522'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9523'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9523'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9524'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9524'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9525'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9525'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9526'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9526'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9527'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9527'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9528'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9528'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9529'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9529'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9530'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9530'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9531'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9531'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9532'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9532'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9533'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9533'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '9534'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9534'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9535'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9535'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9536'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9536'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9537'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9537'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '9538'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9538'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9539'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9539'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9540'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9540'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9541'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9541'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9542'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9542'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9543'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9543'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9544'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9544'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9545'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9545'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9546'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9546'

2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9547'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9547'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9548'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9548'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9549'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9549'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9550'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9550'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9551'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9551'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9552'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9552'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9553'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9553'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9554'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9554'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9555'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9555'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9556'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9556'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9557'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9557'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9558'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9558'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9559'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9559'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9560'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9560'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9561'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9561'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9562'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9562'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9563'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9563'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9564'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9564'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9565'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9565'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9566'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9566'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9567'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9567'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9568'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9568'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9569'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9569'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9570'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9570'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9571'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9571'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9572'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9572'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9573'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9573'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9574'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9574'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9575'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9575'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9576'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9576'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9577'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9577'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '9578'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9578'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9579'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9579'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9580'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9580'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '9581'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9581'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9582'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9582'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9583'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9583'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9584'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9584'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9585'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9585'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9586'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9586'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9587'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9587'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9588'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9588'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9589'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9589'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9590'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9590'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9591'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9591'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9592'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9592'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9593'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9593'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9594'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9594'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9595'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9595'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9596'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9596'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9597'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9597'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9598'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9598'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9599'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9599'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '9600'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9600'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9601'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9601'

2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9602'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9602'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9603'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9603'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9604'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9604'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9605'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9605'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9606'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9606'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9607'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9607'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9608'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9608'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9609'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9609'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9610'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9610'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9611'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9611'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9612'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9612'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9613'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9613'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9614'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9614'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9615'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9615'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9616'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9616'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9617'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9617'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9618'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9618'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9619'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9619'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9620'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9620'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9621'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9621'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9622'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9622'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9623'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9623'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '9624'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9624'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9625'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9625'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9626'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9626'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9627'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9627'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9628'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9628'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '9629'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9629'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9630'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9630'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9631'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9631'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9632'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9632'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9633'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9633'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9634'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9634'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9635'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9635'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9636'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9636'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9637'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9637'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9638'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9638'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9639'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9639'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '9640'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9640'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '9641'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9641'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9642'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9642'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9643'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9643'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9644'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9644'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9645'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9645'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9646'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9646'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9647'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9647'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '9648'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9648'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9649'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9649'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9650'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9650'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9651'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9651'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9652'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9652'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9653'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9653'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9654'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9654'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9655'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9655'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9656'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9656'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9657'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9657'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9658'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9658'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9659'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9659'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9660'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9660'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9661'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9661'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9662'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9662'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9663'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9663'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9664'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9664'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9665'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9665'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9666'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9666'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9667'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9667'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9668'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9668'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9669'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9669'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9670'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9670'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9671'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9671'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9672'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9672'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9673'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9673'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9674'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9674'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9675'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9675'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9676'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9676'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9677'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9677'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9678'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9678'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9679'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9679'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9680'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9680'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9681'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9681'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9682'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9682'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9683'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9683'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9684'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9684'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '9685'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9685'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9686'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9686'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9687'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9687'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9688'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9688'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9689'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9689'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9690'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9690'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9691'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9691'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9692'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9692'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9693'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9693'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9694'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9694'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9695'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9695'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9696'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9696'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9697'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9697'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9698'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9698'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9699'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9699'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9700'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9700'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '9701'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9701'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9702'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9702'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9703'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9703'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9704'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9704'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9705'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9705'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9706'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9706'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9707'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9707'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9708'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9708'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9709'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9709'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '9710'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9710'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9711'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9711'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9712'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9712'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9713'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9713'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9714'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9714'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9715'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9715'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9716'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9716'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9717'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9717'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9718'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9718'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '9719'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9719'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9720'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9720'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9721'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9721'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9722'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9722'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9723'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9723'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9724'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9724'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9725'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9725'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9726'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9726'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9727'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9727'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9728'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9728'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9729'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9729'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9730'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9730'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9731'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9731'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9732'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9732'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9733'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9733'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9734'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9734'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9735'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9735'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9736'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9736'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9737'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9737'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9738'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9738'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9739'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9739'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9740'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9740'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9741'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9741'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9742'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9742'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '9743'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9743'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9744'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9744'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '9745'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9745'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9746'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9746'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9747'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9747'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9748'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9748'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9749'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9749'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9750'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9750'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9751'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9751'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9752'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9752'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9753'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9753'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9754'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9754'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9755'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9755'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9756'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9756'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9757'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9757'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9758'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9758'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9759'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9759'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9760'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9760'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9761'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9761'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9762'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9762'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9763'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9763'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9764'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9764'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9765'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9765'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9766'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9766'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '9767'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9767'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9768'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9768'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9769'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9769'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9770'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9770'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9771'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9771'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9772'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9772'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9773'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9773'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9774'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9774'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9775'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9775'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9776'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9776'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9777'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9777'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9778'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9778'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9779'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9779'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9780'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9780'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9781'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9781'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9782'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9782'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9783'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9783'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9784'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9784'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '9785'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9785'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '9786'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9786'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9787'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9787'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9788'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9788'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9789'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9789'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9790'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9790'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9791'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9791'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9792'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9792'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9793'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9793'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9794'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9794'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9795'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9795'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9796'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9796'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9797'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9797'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9798'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9798'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9799'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9799'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '9800'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9800'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9801'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9801'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9802'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9802'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9803'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9803'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9804'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9804'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9805'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9805'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '9806'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9806'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9807'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9807'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9808'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9808'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9809'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9809'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9810'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9810'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9811'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9811'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9812'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9812'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9813'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9813'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9814'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9814'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9815'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9815'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9816'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9816'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9817'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9817'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9818'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9818'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9819'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9819'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9820'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9820'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9821'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9821'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9822'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9822'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9823'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9823'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9824'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9824'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9825'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9825'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9826'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9826'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9827'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9827'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9828'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9828'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9829'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9829'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9830'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9830'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9831'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9831'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9832'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9832'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9833'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9833'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9834'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9834'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9835'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9835'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9836'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9836'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9837'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9837'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9838'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9838'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9839'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9839'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '9840'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9840'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9841'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9841'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9842'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9842'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9843'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9843'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9844'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9844'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9845'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9845'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9846'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9846'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9847'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9847'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9848'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9848'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9849'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9849'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9850'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9850'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9851'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9851'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9852'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9852'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9853'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9853'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9854'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9854'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9855'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9855'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9856'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9856'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9857'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9857'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9858'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9858'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9859'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9859'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9860'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9860'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9861'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9861'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9862'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9862'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '9863'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9863'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9864'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9864'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9865'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9865'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '9866'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9866'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9867'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9867'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9868'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9868'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9869'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9869'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9870'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9870'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9871'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9871'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9872'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9872'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9873'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9873'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9874'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9874'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '9875'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9875'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9876'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9876'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9877'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9877'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9878'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9878'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9879'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9879'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9880'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9880'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9881'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9881'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9882'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9882'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9883'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9883'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9884'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9884'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9885'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9885'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9886'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9886'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9887'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9887'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9888'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9888'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9889'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9889'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9890'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9890'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9891'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9891'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9892'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9892'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9893'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9893'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '9894'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9894'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9895'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9895'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9896'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9896'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '9897'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9897'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9898'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9898'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9899'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9899'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9900'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9900'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9901'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9901'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9902'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9902'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '9903'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9903'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9904'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9904'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9905'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9905'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9906'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9906'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9907'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9907'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9908'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9908'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '9909'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9909'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9910'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9910'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9911'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9911'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9912'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9912'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9913'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9913'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9914'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9914'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9915'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9915'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9916'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9916'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9917'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9917'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9918'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9918'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9919'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9919'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9920'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9920'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9921'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9921'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9922'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9922'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9923'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9923'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '9924'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9924'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9925'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9925'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9926'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9926'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9927'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9927'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '9928'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9928'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9929'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9929'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9930'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9930'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9931'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9931'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9932'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9932'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9933'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9933'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9934'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9934'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9935'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9935'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9936'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9936'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9937'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9937'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9938'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9938'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9939'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9939'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9940'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9940'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9941'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9941'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9942'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9942'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '9943'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9943'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9944'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9944'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9945'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9945'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9946'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9946'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '9947'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9947'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9948'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9948'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9949'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9949'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9950'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9950'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9951'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9951'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '9952'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9952'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9953'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9953'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9954'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9954'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9955'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9955'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9956'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9956'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9957'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9957'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9958'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9958'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9959'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9959'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9960'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9960'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9961'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9961'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9962'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9962'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9963'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9963'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9964'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9964'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '9965'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9965'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '9966'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9966'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9967'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9967'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9968'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9968'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '9969'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9969'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9970'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9970'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9971'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9971'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9972'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9972'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9973'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9973'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9974'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9974'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9975'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9975'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9976'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9976'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '9977'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9977'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9978'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9978'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9979'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9979'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9980'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9980'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9981'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9981'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9982'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9982'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9983'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9983'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9984'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9984'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9985'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9985'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '9986'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9986'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '9987'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9987'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9988'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9988'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9989'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9989'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '9990'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9990'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9991'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9991'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '9992'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9992'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9993'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9993'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '9994'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9994'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '9995'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9995'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9996'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9996'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '9997'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9997'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '9998'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9998'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '9999'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '9999'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10000'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10000'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10001'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10001'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10002'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10002'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10003'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10003'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10004'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10004'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10005'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10005'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10006'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10006'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10007'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10007'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10008'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10008'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '10009'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10009'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10010'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10010'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10011'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10011'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10012'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10012'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10013'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10013'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10014'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10014'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10015'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10015'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10016'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10016'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10017'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10017'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10018'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10018'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10019'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10019'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10020'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10020'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10021'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10021'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10022'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10022'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10023'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10023'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10024'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10024'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10025'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10025'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10026'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10026'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10027'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10027'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10028'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10028'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10029'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10029'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10030'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10030'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10031'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10031'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10032'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10032'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '10033'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10033'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10034'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10034'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10035'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10035'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10036'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10036'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10037'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10037'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10038'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10038'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10039'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10039'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10040'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10040'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10041'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10041'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10042'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10042'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10043'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10043'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10044'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10044'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10045'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10045'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10046'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10046'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10047'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10047'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '10048'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10048'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10049'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10049'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10050'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10050'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '10051'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10051'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10052'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10052'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10053'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10053'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '10054'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10054'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10055'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10055'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10056'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10056'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10057'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10057'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10058'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10058'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10059'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10059'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10060'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10060'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10061'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10061'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10062'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10062'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10063'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10063'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10064'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10064'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10065'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10065'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10066'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10066'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10067'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10067'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10068'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10068'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10069'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10069'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '10070'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10070'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10071'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10071'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10072'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10072'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10073'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10073'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10074'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10074'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '10075'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10075'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10076'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10076'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10077'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10077'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10078'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10078'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10079'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10079'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10080'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10080'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10081'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10081'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10082'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10082'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10083'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10083'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10084'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10084'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10085'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10085'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10086'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10086'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10087'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10087'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10088'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10088'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10089'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10089'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10090'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10090'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10091'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10091'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10092'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10092'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10093'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10093'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10094'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10094'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10095'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10095'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10096'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10096'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10097'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10097'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10098'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10098'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10099'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10099'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10100'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10100'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10101'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10101'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10102'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10102'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10103'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10103'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10104'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10104'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10105'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10105'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10106'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10106'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10107'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10107'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10108'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10108'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '10109'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10109'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10110'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10110'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10111'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10111'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '10112'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10112'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10113'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10113'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10114'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10114'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10115'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10115'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10116'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10116'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10117'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10117'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10118'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10118'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10119'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10119'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10120'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10120'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10121'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10121'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10122'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10122'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10123'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10123'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10124'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10124'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10125'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10125'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10126'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10126'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10127'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10127'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10128'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10128'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10129'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10129'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10130'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10130'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10131'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10131'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10132'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10132'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10133'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10133'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10134'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10134'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10135'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10135'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '10136'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10136'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10137'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10137'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10138'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10138'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10139'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10139'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10140'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10140'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10141'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10141'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10142'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10142'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10143'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10143'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10144'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10144'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10145'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10145'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10146'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10146'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10147'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10147'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10148'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10148'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10149'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10149'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10150'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10150'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10151'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10151'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10152'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10152'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10153'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10153'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10154'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10154'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10155'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10155'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10156'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10156'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10157'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10157'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10158'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10158'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10159'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10159'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10160'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10160'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10161'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10161'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10162'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10162'

2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10163'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10163'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10164'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10164'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10165'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10165'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10166'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10166'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10167'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10167'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10168'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10168'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10169'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10169'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10170'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10170'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10171'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10171'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10172'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10172'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10173'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10173'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10174'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10174'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10175'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10175'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10176'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10176'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10177'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10177'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10178'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10178'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10179'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10179'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10180'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10180'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '10181'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10181'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10182'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10182'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10183'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10183'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10184'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10184'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10185'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10185'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10186'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10186'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10187'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10187'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '10188'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10188'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10189'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10189'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10190'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10190'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10191'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10191'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10192'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10192'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10193'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10193'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10194'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10194'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10195'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10195'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10196'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10196'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10197'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10197'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '10198'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10198'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10199'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10199'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '10200'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10200'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10201'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10201'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10202'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10202'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10203'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10203'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10204'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10204'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10205'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10205'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10206'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10206'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10207'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10207'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10208'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10208'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10209'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10209'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10210'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10210'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10211'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10211'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10212'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10212'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10213'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10213'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10214'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10214'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10215'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10215'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10216'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10216'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10217'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10217'

2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10218'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10218'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10219'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10219'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10220'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10220'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10221'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10221'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10222'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10222'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10223'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10223'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10224'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10224'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10225'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10225'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10226'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10226'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10227'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10227'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10228'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10228'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10229'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10229'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10230'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10230'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10231'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10231'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10232'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10232'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10233'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10233'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10234'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10234'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10235'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10235'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10236'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10236'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '10237'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10237'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10238'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10238'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10239'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10239'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10240'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10240'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10241'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10241'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10242'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10242'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10243'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10243'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '10244'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10244'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10245'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10245'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10246'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10246'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '10247'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10247'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10248'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10248'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10249'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10249'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10250'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10250'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10251'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10251'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10252'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10252'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10253'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10253'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10254'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10254'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10255'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10255'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10256'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10256'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10257'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10257'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10258'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10258'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '10259'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10259'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10260'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10260'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10261'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10261'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '10262'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10262'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10263'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10263'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10264'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10264'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10265'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10265'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10266'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10266'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10267'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10267'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10268'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10268'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10269'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10269'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10270'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10270'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10271'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10271'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10272'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10272'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10273'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10273'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10274'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10274'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10275'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10275'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10276'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10276'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '10277'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10277'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10278'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10278'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10279'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10279'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10280'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10280'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '10281'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10281'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10282'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10282'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10283'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10283'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10284'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10284'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10285'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10285'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10286'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10286'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10287'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10287'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10288'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10288'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10289'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10289'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10290'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10290'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10291'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10291'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10292'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10292'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10293'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10293'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10294'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10294'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10295'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10295'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10296'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10296'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10297'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10297'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10298'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10298'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10299'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10299'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10300'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10300'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10301'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10301'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10302'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10302'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10303'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10303'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10304'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10304'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10305'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10305'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10306'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10306'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10307'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10307'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10308'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10308'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10309'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10309'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10310'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10310'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10311'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10311'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10312'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10312'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10313'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10313'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10314'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10314'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '10315'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10315'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10316'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10316'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10317'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10317'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10318'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10318'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10319'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10319'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10320'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10320'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '10321'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10321'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10322'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10322'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10323'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10323'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10324'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10324'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10325'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10325'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10326'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10326'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10327'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10327'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10328'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10328'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10329'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10329'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10330'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10330'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10331'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10331'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10332'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10332'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10333'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10333'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '10334'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10334'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10335'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10335'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10336'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10336'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10337'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10337'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10338'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10338'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10339'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10339'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10340'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10340'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10341'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10341'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10342'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10342'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10343'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10343'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10344'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10344'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10345'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10345'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10346'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10346'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10347'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10347'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10348'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10348'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10349'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10349'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10350'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10350'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10351'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10351'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10352'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10352'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '10353'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10353'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10354'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10354'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10355'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10355'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10356'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10356'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10357'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10357'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10358'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10358'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10359'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10359'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10360'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10360'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10361'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10361'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10362'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10362'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10363'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10363'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '10364'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10364'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10365'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10365'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10366'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10366'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10367'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10367'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10368'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10368'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10369'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10369'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10370'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10370'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10371'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10371'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10372'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10372'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10373'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10373'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10374'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10374'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10375'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10375'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10376'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10376'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10377'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10377'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10378'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10378'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10379'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10379'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10380'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10380'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '10381'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10381'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10382'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10382'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10383'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10383'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10384'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10384'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10385'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10385'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10386'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10386'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '10387'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10387'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10388'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10388'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10389'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10389'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10390'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10390'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10391'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10391'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10392'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10392'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10393'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10393'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10394'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10394'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10395'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10395'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10396'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10396'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10397'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10397'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10398'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10398'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10399'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10399'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10400'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10400'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10401'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10401'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10402'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10402'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10403'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10403'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10404'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10404'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10405'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10405'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10406'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10406'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10407'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10407'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10408'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10408'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10409'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10409'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10410'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10410'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10411'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10411'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10412'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10412'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10413'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10413'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10414'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10414'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10415'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10415'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10416'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10416'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10417'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10417'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10418'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10418'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10419'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10419'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10420'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10420'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10421'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10421'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10422'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10422'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10423'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10423'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10424'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10424'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10425'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10425'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10426'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10426'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '10427'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10427'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10428'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10428'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10429'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10429'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10430'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10430'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10431'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10431'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10432'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10432'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '10433'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10433'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10434'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10434'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10435'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10435'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '10436'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10436'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10437'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10437'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10438'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10438'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10439'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10439'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10440'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10440'

2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10441'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10441'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10442'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10442'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10443'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10443'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10444'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10444'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10445'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10445'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10446'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10446'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10447'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10447'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '10448'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10448'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10449'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10449'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10450'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10450'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10451'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10451'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10452'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10452'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10453'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10453'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10454'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10454'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10455'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10455'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10456'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10456'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10457'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10457'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10458'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10458'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10459'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10459'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10460'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10460'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10461'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10461'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '10462'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10462'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10463'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10463'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10464'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10464'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10465'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10465'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10466'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10466'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10467'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10467'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10468'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10468'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10469'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10469'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10470'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10470'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10471'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10471'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10472'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10472'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10473'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10473'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10474'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10474'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10475'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10475'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10476'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10476'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10477'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10477'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10478'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10478'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10479'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10479'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10480'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10480'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10481'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10481'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10482'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10482'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10483'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10483'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10484'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10484'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10485'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10485'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10486'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10486'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10487'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10487'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10488'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10488'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10489'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10489'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10490'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10490'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10491'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10491'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10492'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10492'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10493'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10493'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10494'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10494'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10495'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10495'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10496'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10496'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10497'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10497'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10498'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10498'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10499'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10499'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10500'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10500'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10501'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10501'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10502'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10502'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10503'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10503'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10504'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10504'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10505'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10505'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10506'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10506'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10507'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10507'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10508'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10508'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10509'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10509'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10510'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10510'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10511'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10511'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '10512'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10512'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10513'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10513'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10514'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10514'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10515'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10515'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10516'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10516'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10517'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10517'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10518'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10518'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10519'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10519'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10520'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10520'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '10521'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10521'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10522'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10522'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10523'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10523'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10524'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10524'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10525'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10525'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10526'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10526'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10527'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10527'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10528'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10528'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10529'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10529'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10530'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10530'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10531'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10531'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10532'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10532'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10533'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10533'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10534'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10534'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10535'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10535'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10536'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10536'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10537'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10537'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10538'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10538'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10539'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10539'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10540'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10540'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10541'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10541'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10542'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10542'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10543'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10543'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10544'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10544'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10545'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10545'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10546'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10546'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10547'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10547'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10548'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10548'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10549'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10549'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10550'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10550'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10551'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10551'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10552'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10552'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10553'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10553'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10554'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10554'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10555'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10555'

2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10556'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10556'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10557'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10557'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10558'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10558'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10559'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10559'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10560'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10560'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10561'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10561'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10562'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10562'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10563'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10563'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10564'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10564'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10565'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10565'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10566'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10566'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10567'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10567'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10568'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10568'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10569'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10569'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10570'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10570'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10571'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10571'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10572'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10572'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10573'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10573'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10574'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10574'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10575'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10575'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10576'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10576'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10577'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10577'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10578'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10578'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10579'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10579'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '10580'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10580'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10581'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10581'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10582'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10582'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10583'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10583'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10584'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10584'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10585'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10585'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10586'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10586'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10587'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10587'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10588'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10588'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10589'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10589'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10590'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10590'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10591'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10591'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10592'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10592'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10593'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10593'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10594'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10594'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10595'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10595'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10596'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10596'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10597'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10597'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10598'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10598'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10599'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10599'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10600'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10600'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '10601'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10601'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10602'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10602'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10603'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10603'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10604'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10604'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10605'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10605'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10606'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10606'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10607'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10607'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10608'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10608'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10609'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10609'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10610'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10610'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10611'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10611'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10612'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10612'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10613'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10613'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10614'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10614'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10615'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10615'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10616'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10616'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10617'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10617'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10618'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10618'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10619'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10619'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10620'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10620'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10621'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10621'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10622'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10622'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10623'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10623'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10624'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10624'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10625'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10625'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10626'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10626'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10627'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10627'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10628'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10628'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10629'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10629'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10630'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10630'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10631'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10631'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10632'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10632'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10633'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10633'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10634'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10634'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10635'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10635'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10636'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10636'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10637'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10637'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10638'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10638'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10639'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10639'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10640'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10640'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10641'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10641'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10642'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10642'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10643'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10643'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10644'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10644'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10645'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10645'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10646'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10646'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10647'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10647'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10648'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10648'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10649'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10649'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10650'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10650'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10651'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10651'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10652'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10652'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10653'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10653'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10654'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10654'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10655'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10655'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10656'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10656'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '10657'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10657'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10658'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10658'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10659'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10659'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10660'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10660'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10661'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10661'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10662'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10662'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10663'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10663'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10664'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10664'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10665'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10665'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10666'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10666'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10667'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10667'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10668'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10668'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10669'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10669'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10670'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10670'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10671'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10671'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10672'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10672'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10673'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10673'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10674'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10674'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10675'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10675'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10676'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10676'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10677'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10677'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10678'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10678'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10679'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10679'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10680'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10680'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10681'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10681'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '10682'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10682'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '10683'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10683'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10684'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10684'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10685'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10685'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10686'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10686'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10687'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10687'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10688'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10688'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10689'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10689'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '10690'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10690'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '10691'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10691'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10692'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10692'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10693'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10693'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10694'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10694'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10695'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10695'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10696'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10696'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10697'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10697'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10698'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10698'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10699'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10699'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10700'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10700'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10701'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10701'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10702'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10702'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10703'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10703'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10704'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10704'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10705'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10705'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10706'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10706'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10707'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10707'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10708'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10708'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10709'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10709'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10710'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10710'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10711'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10711'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10712'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10712'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10713'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10713'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '10714'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10714'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10715'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10715'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10716'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10716'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10717'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10717'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10718'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10718'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10719'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10719'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10720'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10720'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10721'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10721'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10722'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10722'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10723'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10723'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '10724'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10724'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10725'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10725'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10726'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10726'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10727'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10727'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10728'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10728'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10729'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10729'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10730'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10730'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10731'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10731'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10732'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10732'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10733'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10733'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10734'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10734'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10735'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10735'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10736'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10736'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10737'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10737'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10738'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10738'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10739'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10739'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10740'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10740'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10741'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10741'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10742'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10742'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10743'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10743'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10744'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10744'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10745'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10745'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10746'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10746'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10747'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10747'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10748'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10748'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10749'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10749'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10750'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10750'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10751'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10751'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10752'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10752'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10753'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10753'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10754'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10754'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10755'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10755'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10756'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10756'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10757'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10757'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10758'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10758'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10759'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10759'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10760'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10760'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10761'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10761'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10762'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10762'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10763'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10763'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10764'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10764'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '10765'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10765'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10766'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10766'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10767'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10767'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10768'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10768'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '10769'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10769'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10770'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10770'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10771'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10771'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10772'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10772'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10773'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10773'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10774'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10774'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10775'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10775'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10776'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10776'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10777'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10777'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10778'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10778'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '10779'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10779'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10780'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10780'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10781'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10781'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '10782'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10782'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10783'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10783'

2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10784'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10784'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10785'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10785'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10786'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10786'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '10787'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10787'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10788'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10788'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10789'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10789'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10790'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10790'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10791'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10791'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10792'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10792'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10793'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10793'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10794'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10794'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10795'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10795'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10796'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10796'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10797'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10797'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10798'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10798'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10799'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10799'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10800'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10800'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10801'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10801'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10802'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10802'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '10803'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10803'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10804'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10804'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10805'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10805'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10806'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10806'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10807'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10807'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10808'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10808'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10809'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10809'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10810'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10810'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10811'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10811'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10812'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10812'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10813'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10813'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10814'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10814'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10815'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10815'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10816'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10816'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10817'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10817'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10818'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10818'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10819'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10819'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10820'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10820'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10821'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10821'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10822'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10822'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10823'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10823'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10824'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10824'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10825'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10825'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10826'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10826'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10827'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10827'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10828'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10828'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10829'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10829'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10830'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10830'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10831'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10831'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10832'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10832'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10833'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10833'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10834'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10834'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10835'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10835'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '10836'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10836'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10837'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10837'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10838'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10838'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10839'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10839'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10840'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10840'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10841'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10841'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10842'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10842'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10843'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10843'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '10844'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10844'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10845'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10845'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10846'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10846'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10847'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10847'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10848'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10848'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10849'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10849'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10850'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10850'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10851'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10851'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10852'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10852'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10853'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10853'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10854'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10854'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10855'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10855'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10856'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10856'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10857'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10857'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10858'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10858'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10859'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10859'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10860'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10860'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10861'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10861'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '10862'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10862'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10863'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10863'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10864'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10864'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10865'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10865'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10866'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10866'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10867'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10867'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10868'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10868'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10869'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10869'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '10870'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10870'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10871'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10871'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10872'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10872'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10873'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10873'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10874'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10874'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10875'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10875'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10876'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10876'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10877'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10877'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10878'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10878'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10879'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10879'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10880'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10880'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10881'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10881'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10882'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10882'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10883'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10883'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10884'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10884'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10885'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10885'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10886'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10886'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '10887'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10887'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10888'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10888'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10889'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10889'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10890'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10890'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '10891'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10891'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10892'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10892'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10893'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10893'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10894'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10894'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10895'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10895'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10896'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10896'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10897'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10897'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10898'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10898'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10899'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10899'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10900'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10900'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10901'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10901'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10902'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10902'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10903'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10903'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10904'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10904'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10905'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10905'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10906'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10906'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '10907'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10907'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10908'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10908'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10909'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10909'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10910'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10910'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10911'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10911'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '10912'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10912'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10913'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10913'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '10914'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10914'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10915'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10915'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10916'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10916'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10917'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10917'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10918'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10918'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10919'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10919'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '10920'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10920'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10921'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10921'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10922'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10922'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '10923'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10923'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10924'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10924'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10925'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10925'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10926'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10926'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10927'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10927'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10928'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10928'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10929'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10929'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10930'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10930'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10931'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10931'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10932'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10932'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '10933'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10933'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10934'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10934'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10935'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10935'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '10936'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10936'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10937'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10937'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10938'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10938'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '10939'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10939'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10940'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10940'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10941'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10941'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10942'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10942'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10943'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10943'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10944'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10944'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10945'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10945'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10946'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10946'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10947'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10947'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10948'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10948'

2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10949'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10949'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10950'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10950'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '10951'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10951'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10952'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10952'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10953'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10953'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10954'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10954'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10955'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10955'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10956'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10956'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10957'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10957'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10958'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10958'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '10959'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10959'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10960'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10960'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10961'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10961'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10962'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10962'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10963'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10963'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10964'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10964'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10965'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10965'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10966'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10966'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10967'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10967'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10968'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10968'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10969'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10969'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10970'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10970'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10971'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10971'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10972'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10972'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10973'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10973'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10974'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10974'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10975'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10975'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10976'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10976'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10977'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10977'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10978'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10978'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10979'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10979'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '10980'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10980'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10981'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10981'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10982'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10982'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '10983'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10983'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10984'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10984'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10985'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10985'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10986'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10986'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10987'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10987'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '10988'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10988'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10989'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10989'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10990'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10990'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10991'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10991'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10992'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10992'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '10993'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10993'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10994'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10994'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '10995'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10995'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '10996'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10996'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '10997'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10997'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '10998'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10998'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '10999'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '10999'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '11000'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11000'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11001'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11001'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11002'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11002'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11003'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11003'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11004'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11004'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11005'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11005'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11006'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11006'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11007'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11007'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11008'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11008'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11009'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11009'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11010'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11010'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11011'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11011'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11012'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11012'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11013'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11013'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11014'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11014'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11015'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11015'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11016'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11016'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11017'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11017'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11018'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11018'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11019'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11019'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11020'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11020'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11021'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11021'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11022'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11022'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11023'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11023'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11024'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11024'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11025'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11025'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11026'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11026'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11027'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11027'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '11028'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11028'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11029'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11029'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11030'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11030'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11031'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11031'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11032'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11032'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11033'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11033'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11034'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11034'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11035'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11035'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11036'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11036'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11037'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11037'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11038'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11038'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '11039'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11039'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11040'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11040'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11041'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11041'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11042'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11042'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11043'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11043'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11044'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11044'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11045'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11045'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11046'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11046'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11047'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11047'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11048'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11048'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11049'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11049'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11050'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11050'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11051'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11051'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11052'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11052'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11053'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11053'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '11054'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11054'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11055'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11055'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11056'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11056'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11057'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11057'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11058'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11058'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '11059'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11059'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11060'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11060'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11061'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11061'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11062'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11062'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11063'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11063'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11064'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11064'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11065'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11065'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11066'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11066'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11067'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11067'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11068'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11068'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11069'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11069'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11070'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11070'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11071'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11071'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11072'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11072'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11073'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11073'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11074'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11074'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11075'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11075'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11076'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11076'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11077'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11077'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11078'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11078'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11079'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11079'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11080'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11080'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11081'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11081'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11082'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11082'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11083'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11083'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11084'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11084'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11085'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11085'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11086'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11086'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11087'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11087'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11088'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11088'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11089'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11089'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11090'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11090'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11091'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11091'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11092'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11092'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11093'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11093'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11094'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11094'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11095'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11095'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11096'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11096'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11097'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11097'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11098'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11098'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11099'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11099'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '11100'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11100'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11101'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11101'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11102'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11102'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11103'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11103'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11104'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11104'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11105'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11105'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11106'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11106'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11107'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11107'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11108'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11108'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11109'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11109'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11110'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11110'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11111'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11111'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11112'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11112'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11113'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11113'

2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '11114'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11114'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11115'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11115'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '11116'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11116'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '11117'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11117'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '11118'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11118'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11119'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11119'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11120'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11120'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11121'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11121'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11122'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11122'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11123'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11123'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11124'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11124'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '11125'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11125'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11126'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11126'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11127'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11127'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '11128'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11128'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '11129'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11129'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11130'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11130'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11131'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11131'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11132'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11132'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11133'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11133'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11134'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11134'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '11135'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11135'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '11136'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11136'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11137'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11137'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11138'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11138'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11139'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11139'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11140'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11140'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11141'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11141'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11142'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11142'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11143'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11143'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11144'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11144'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11145'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11145'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11146'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11146'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11147'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11147'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11148'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11148'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11149'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11149'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11150'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11150'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11151'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11151'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11152'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11152'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11153'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11153'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11154'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11154'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11155'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11155'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11156'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11156'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11157'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11157'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11158'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11158'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11159'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11159'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11160'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11160'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11161'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11161'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11162'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11162'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11163'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11163'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '11164'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11164'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11165'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11165'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11166'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11166'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11167'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11167'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11168'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11168'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11169'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11169'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11170'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11170'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11171'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11171'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11172'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11172'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11173'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11173'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11174'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11174'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11175'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11175'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11176'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11176'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11177'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11177'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11178'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11178'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '11179'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11179'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11180'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11180'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '11181'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11181'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11182'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11182'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11183'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11183'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11184'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11184'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11185'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11185'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11186'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11186'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11187'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11187'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11188'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11188'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11189'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11189'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11190'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11190'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11191'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11191'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11192'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11192'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11193'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11193'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11194'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11194'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11195'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11195'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '11196'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11196'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11197'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11197'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11198'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11198'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11199'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11199'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11200'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11200'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11201'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11201'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11202'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11202'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11203'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11203'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11204'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11204'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11205'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11205'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11206'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11206'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11207'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11207'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11208'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11208'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11209'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11209'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11210'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11210'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11211'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11211'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11212'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11212'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11213'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11213'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11214'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11214'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11215'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11215'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11216'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11216'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11217'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11217'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11218'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11218'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11219'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11219'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11220'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11220'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11221'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11221'

2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11222'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11222'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11223'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11223'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11224'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11224'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11225'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11225'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '11226'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11226'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11227'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11227'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11228'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11228'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11229'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11229'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11230'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11230'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11231'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11231'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11232'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11232'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '11233'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11233'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11234'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11234'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11235'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11235'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11236'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11236'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11237'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11237'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11238'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11238'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11239'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11239'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11240'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11240'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11241'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11241'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11242'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11242'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11243'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11243'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11244'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11244'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11245'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11245'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11246'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11246'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11247'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11247'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11248'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11248'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11249'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11249'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11250'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11250'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11251'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11251'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11252'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11252'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '11253'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11253'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11254'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11254'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11255'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11255'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11256'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11256'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11257'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11257'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11258'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11258'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11259'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11259'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11260'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11260'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11261'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11261'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11262'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11262'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11263'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11263'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11264'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11264'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11265'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11265'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11266'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11266'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11267'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11267'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11268'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11268'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11269'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11269'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11270'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11270'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11271'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11271'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11272'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11272'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11273'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11273'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11274'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11274'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11275'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11275'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11276'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11276'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11277'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11277'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11278'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11278'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11279'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11279'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11280'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11280'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11281'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11281'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11282'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11282'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11283'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11283'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '11284'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11284'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11285'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11285'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11286'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11286'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11287'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11287'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11288'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11288'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11289'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11289'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11290'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11290'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11291'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11291'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11292'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11292'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11293'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11293'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11294'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11294'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11295'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11295'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11296'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11296'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11297'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11297'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11298'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11298'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11299'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11299'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11300'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11300'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11301'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11301'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11302'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11302'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11303'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11303'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11304'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11304'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11305'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11305'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11306'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11306'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11307'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11307'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11308'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11308'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '11309'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11309'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11310'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11310'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11311'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11311'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11312'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11312'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11313'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11313'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11314'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11314'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11315'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11315'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11316'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11316'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11317'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11317'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11318'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11318'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11319'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11319'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11320'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11320'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11321'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11321'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11322'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11322'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11323'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11323'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11324'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11324'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11325'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11325'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11326'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11326'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11327'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11327'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11328'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11328'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11329'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11329'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11330'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11330'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11331'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11331'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11332'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11332'

2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11333'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11333'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11334'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11334'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11335'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11335'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11336'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11336'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11337'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11337'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11338'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11338'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11339'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11339'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11340'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11340'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11341'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11341'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11342'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11342'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11343'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11343'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11344'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11344'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '11345'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11345'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11346'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11346'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11347'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11347'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11348'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11348'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11349'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11349'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '11350'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11350'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11351'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11351'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11352'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11352'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11353'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11353'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11354'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11354'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11355'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11355'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11356'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11356'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11357'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11357'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11358'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11358'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11359'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11359'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11360'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11360'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11361'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11361'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11362'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11362'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11363'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11363'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11364'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11364'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11365'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11365'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11366'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11366'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11367'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11367'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11368'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11368'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11369'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11369'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11370'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11370'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11371'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11371'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11372'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11372'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11373'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11373'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11374'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11374'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11375'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11375'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11376'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11376'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11377'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11377'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11378'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11378'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11379'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11379'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11380'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11380'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11381'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11381'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11382'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11382'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11383'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11383'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11384'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11384'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11385'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11385'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11386'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11386'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11387'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11387'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11388'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11388'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11389'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11389'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11390'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11390'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11391'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11391'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11392'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11392'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11393'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11393'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11394'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11394'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11395'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11395'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11396'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11396'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11397'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11397'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11398'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11398'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11399'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11399'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11400'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11400'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11401'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11401'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11402'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11402'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11403'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11403'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11404'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11404'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11405'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11405'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11406'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11406'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11407'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11407'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11408'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11408'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11409'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11409'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11410'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11410'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11411'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11411'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11412'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11412'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11413'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11413'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11414'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11414'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11415'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11415'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11416'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11416'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11417'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11417'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11418'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11418'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11419'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11419'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '11420'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11420'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '11421'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11421'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11422'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11422'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11423'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11423'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11424'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11424'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11425'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11425'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11426'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11426'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11427'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11427'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11428'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11428'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11429'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11429'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11430'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11430'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11431'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11431'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11432'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11432'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11433'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11433'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11434'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11434'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11435'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11435'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11436'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11436'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11437'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11437'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11438'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11438'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11439'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11439'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11440'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11440'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11441'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11441'

2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11442'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11442'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11443'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11443'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11444'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11444'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11445'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11445'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11446'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11446'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11447'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11447'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11448'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11448'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11449'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11449'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11450'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11450'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11451'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11451'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11452'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11452'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11453'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11453'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11454'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11454'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11455'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11455'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11456'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11456'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11457'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11457'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11458'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11458'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11459'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11459'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11460'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11460'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11461'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11461'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11462'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11462'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11463'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11463'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11464'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11464'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11465'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11465'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11466'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11466'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11467'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11467'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11468'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11468'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11469'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11469'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11470'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11470'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11471'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11471'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11472'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11472'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11473'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11473'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11474'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11474'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11475'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11475'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11476'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11476'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11477'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11477'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11478'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11478'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11479'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11479'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11480'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11480'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11481'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11481'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11482'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11482'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11483'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11483'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11484'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11484'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11485'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11485'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11486'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11486'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11487'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11487'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11488'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11488'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11489'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11489'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11490'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11490'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11491'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11491'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11492'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11492'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11493'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11493'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '11494'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11494'

2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11495'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11495'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11496'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11496'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11497'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11497'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11498'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11498'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11499'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11499'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11500'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11500'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11501'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11501'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11502'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11502'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11503'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11503'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11504'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11504'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11505'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11505'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11506'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11506'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '11507'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11507'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11508'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11508'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11509'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11509'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11510'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11510'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11511'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11511'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11512'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11512'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11513'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11513'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11514'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11514'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11515'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11515'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11516'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11516'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11517'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11517'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11518'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11518'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11519'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11519'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11520'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11520'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11521'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11521'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11522'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11522'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11523'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11523'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11524'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11524'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11525'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11525'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11526'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11526'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11527'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11527'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11528'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11528'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11529'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11529'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11530'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11530'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '11531'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11531'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11532'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11532'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11533'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11533'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11534'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11534'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11535'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11535'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11536'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11536'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11537'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11537'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11538'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11538'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11539'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11539'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11540'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11540'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11541'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11541'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11542'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11542'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11543'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11543'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11544'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11544'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11545'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11545'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11546'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11546'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11547'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11547'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11548'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11548'

2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11549'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11549'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11550'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11550'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11551'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11551'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11552'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11552'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11553'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11553'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11554'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11554'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11555'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11555'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11556'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11556'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11557'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11557'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '11558'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11558'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11559'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11559'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11560'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11560'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11561'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11561'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11562'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11562'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11563'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11563'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11564'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11564'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '11565'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11565'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11566'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11566'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11567'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11567'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11568'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11568'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11569'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11569'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11570'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11570'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11571'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11571'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11572'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11572'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11573'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11573'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11574'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11574'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11575'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11575'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11576'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11576'
2022-05-30
UPDATE job_vacancies SET open =  '2022-05-30' where raw_id = '11577'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11577'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11578'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11578'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11579'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11579'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11580'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11580'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11581'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11581'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11582'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11582'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11583'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11583'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11584'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11584'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11585'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11585'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11586'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11586'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11587'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11587'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11588'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11588'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11589'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11589'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11590'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11590'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11591'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11591'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11592'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11592'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11593'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11593'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11594'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11594'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11595'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11595'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11596'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11596'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11597'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11597'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11598'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11598'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11599'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11599'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11600'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11600'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '11601'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11601'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11602'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11602'

2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11603'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11603'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11604'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11604'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11605'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11605'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11606'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11606'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11607'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11607'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11608'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11608'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11609'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11609'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11610'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11610'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11611'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11611'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11612'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11612'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11613'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11613'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11614'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11614'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11615'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11615'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11616'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11616'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11617'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11617'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11618'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11618'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11619'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11619'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11620'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11620'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11621'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11621'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11622'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11622'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11623'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11623'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11624'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11624'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11625'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11625'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11626'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11626'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11627'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11627'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11628'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11628'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11629'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11629'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11630'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11630'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11631'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11631'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11632'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11632'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11633'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11633'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11634'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11634'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11635'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11635'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11636'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11636'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11637'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11637'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11638'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11638'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11639'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11639'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11640'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11640'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11641'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11641'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '11642'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11642'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11643'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11643'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11644'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11644'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11645'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11645'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11646'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11646'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11647'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11647'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11648'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11648'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11649'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11649'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11650'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11650'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11651'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11651'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11652'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11652'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11653'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11653'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11654'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11654'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11655'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11655'

2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11656'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11656'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11657'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11657'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11658'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11658'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11659'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11659'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11660'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11660'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11661'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11661'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11662'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11662'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11663'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11663'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11664'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11664'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11665'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11665'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11666'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11666'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11667'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11667'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11668'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11668'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11669'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11669'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11670'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11670'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11671'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11671'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11672'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11672'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11673'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11673'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11674'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11674'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11675'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11675'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11676'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11676'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11677'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11677'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11678'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11678'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11679'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11679'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11680'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11680'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11681'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11681'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11682'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11682'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11683'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11683'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11684'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11684'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11685'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11685'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11686'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11686'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11687'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11687'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11688'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11688'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11689'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11689'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11690'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11690'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11691'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11691'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11692'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11692'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11693'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11693'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11694'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11694'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11695'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11695'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11696'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11696'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11697'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11697'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11698'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11698'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11699'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11699'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11700'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11700'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11701'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11701'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '11702'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11702'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11703'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11703'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11704'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11704'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11705'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11705'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11706'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11706'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11707'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11707'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11708'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11708'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11709'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11709'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11710'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11710'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11711'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11711'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11712'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11712'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11713'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11713'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11714'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11714'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11715'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11715'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11716'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11716'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11717'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11717'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11718'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11718'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11719'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11719'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11720'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11720'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11721'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11721'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11722'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11722'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11723'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11723'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '11724'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11724'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11725'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11725'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11726'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11726'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11727'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11727'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11728'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11728'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11729'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11729'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11730'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11730'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11731'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11731'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11732'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11732'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11733'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11733'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11734'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11734'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11735'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11735'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11736'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11736'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11737'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11737'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11738'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11738'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11739'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11739'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11740'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11740'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11741'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11741'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11742'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11742'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11743'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11743'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11744'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11744'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '11745'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11745'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11746'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11746'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11747'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11747'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11748'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11748'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11749'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11749'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11750'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11750'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11751'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11751'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11752'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11752'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11753'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11753'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '11754'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11754'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11755'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11755'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11756'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11756'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11757'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11757'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11758'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11758'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11759'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11759'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11760'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11760'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11761'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11761'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11762'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11762'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11763'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11763'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11764'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11764'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11765'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11765'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11766'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11766'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '11767'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11767'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11768'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11768'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11769'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11769'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11770'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11770'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '11771'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11771'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11772'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11772'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11773'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11773'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11774'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11774'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11775'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11775'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11776'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11776'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '11777'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11777'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11778'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11778'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11779'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11779'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11780'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11780'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11781'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11781'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11782'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11782'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11783'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11783'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11784'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11784'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11785'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11785'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11786'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11786'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11787'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11787'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11788'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11788'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11789'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11789'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11790'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11790'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11791'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11791'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11792'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11792'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11793'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11793'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11794'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11794'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11795'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11795'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11796'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11796'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11797'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11797'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11798'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11798'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11799'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11799'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11800'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11800'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11801'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11801'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11802'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11802'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11803'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11803'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11804'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11804'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11805'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11805'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11806'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11806'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11807'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11807'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11808'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11808'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11809'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11809'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11810'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11810'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11811'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11811'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11812'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11812'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '11813'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11813'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11814'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11814'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11815'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11815'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11816'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11816'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11817'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11817'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11818'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11818'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11819'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11819'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11820'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11820'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11821'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11821'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11822'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11822'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11823'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11823'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11824'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11824'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11825'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11825'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11826'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11826'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11827'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11827'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11828'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11828'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11829'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11829'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11830'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11830'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11831'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11831'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11832'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11832'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11833'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11833'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11834'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11834'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11835'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11835'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11836'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11836'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11837'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11837'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11838'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11838'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11839'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11839'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11840'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11840'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11841'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11841'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '11842'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11842'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11843'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11843'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11844'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11844'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11845'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11845'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11846'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11846'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11847'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11847'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11848'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11848'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11849'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11849'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11850'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11850'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11851'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11851'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11852'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11852'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11853'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11853'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11854'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11854'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11855'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11855'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11856'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11856'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11857'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11857'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11858'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11858'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11859'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11859'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11860'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11860'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11861'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11861'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11862'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11862'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11863'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11863'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11864'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11864'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11865'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11865'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11866'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11866'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11867'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11867'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11868'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11868'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11869'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11869'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11870'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11870'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11871'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11871'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11872'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11872'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11873'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11873'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11874'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11874'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11875'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11875'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11876'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11876'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11877'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11877'

2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11878'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11878'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11879'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11879'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11880'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11880'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11881'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11881'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11882'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11882'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11883'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11883'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11884'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11884'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11885'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11885'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11886'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11886'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11887'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11887'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11888'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11888'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11889'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11889'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11890'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11890'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11891'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11891'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11892'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11892'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11893'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11893'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11894'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11894'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11895'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11895'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11896'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11896'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11897'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11897'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11898'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11898'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11899'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11899'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11900'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11900'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11901'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11901'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11902'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11902'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11903'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11903'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11904'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11904'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11905'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11905'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11906'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11906'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11907'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11907'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11908'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11908'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11909'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11909'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11910'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11910'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '11911'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11911'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11912'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11912'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11913'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11913'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11914'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11914'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11915'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11915'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11916'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11916'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11917'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11917'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11918'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11918'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11919'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11919'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11920'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11920'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11921'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11921'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11922'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11922'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11923'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11923'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11924'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11924'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11925'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11925'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11926'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11926'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11927'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11927'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11928'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11928'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11929'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11929'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11930'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11930'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11931'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11931'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11932'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11932'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11933'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11933'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11934'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11934'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11935'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11935'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '11936'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11936'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11937'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11937'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11938'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11938'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11939'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11939'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11940'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11940'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11941'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11941'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '11942'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11942'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11943'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11943'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11944'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11944'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11945'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11945'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11946'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11946'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11947'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11947'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11948'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11948'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11949'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11949'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11950'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11950'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11951'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11951'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11952'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11952'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11953'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11953'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11954'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11954'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11955'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11955'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11956'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11956'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11957'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11957'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11958'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11958'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11959'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11959'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11960'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11960'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11961'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11961'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '11962'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11962'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11963'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11963'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11964'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11964'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11965'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11965'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11966'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11966'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11967'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11967'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '11968'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11968'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11969'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11969'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11970'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11970'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11971'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11971'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11972'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11972'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11973'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11973'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11974'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11974'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11975'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11975'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11976'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11976'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11977'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11977'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11978'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11978'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11979'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11979'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11980'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11980'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11981'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11981'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11982'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11982'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11983'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11983'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11984'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11984'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11985'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11985'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11986'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11986'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11987'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11987'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11988'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11988'

2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11989'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11989'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11990'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11990'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11991'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11991'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '11992'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11992'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11993'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11993'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '11994'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11994'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '11995'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11995'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11996'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11996'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '11997'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11997'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11998'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11998'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '11999'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '11999'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12000'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12000'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12001'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12001'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12002'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12002'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12003'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12003'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12004'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12004'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12005'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12005'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12006'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12006'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12007'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12007'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12008'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12008'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12009'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12009'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12010'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12010'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12011'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12011'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12012'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12012'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12013'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12013'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12014'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12014'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12015'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12015'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12016'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12016'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '12017'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12017'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12018'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12018'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12019'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12019'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12020'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12020'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12021'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12021'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12022'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12022'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12023'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12023'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12024'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12024'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12025'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12025'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12026'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12026'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12027'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12027'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12028'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12028'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12029'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12029'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12030'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12030'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12031'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12031'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12032'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12032'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12033'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12033'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12034'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12034'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12035'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12035'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12036'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12036'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12037'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12037'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12038'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12038'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12039'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12039'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12040'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12040'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12041'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12041'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12042'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12042'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12043'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12043'

2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12044'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12044'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12045'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12045'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12046'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12046'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12047'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12047'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '12048'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12048'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12049'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12049'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12050'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12050'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12051'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12051'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12052'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12052'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12053'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12053'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12054'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12054'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12055'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12055'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12056'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12056'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12057'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12057'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12058'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12058'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '12059'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12059'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12060'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12060'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12061'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12061'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12062'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12062'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12063'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12063'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12064'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12064'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12065'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12065'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12066'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12066'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12067'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12067'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12068'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12068'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12069'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12069'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12070'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12070'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '12071'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12071'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12072'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12072'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12073'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12073'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '12074'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12074'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12075'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12075'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12076'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12076'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12077'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12077'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12078'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12078'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12079'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12079'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12080'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12080'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12081'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12081'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12082'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12082'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12083'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12083'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12084'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12084'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12085'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12085'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12086'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12086'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12087'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12087'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12088'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12088'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12089'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12089'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12090'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12090'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12091'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12091'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12092'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12092'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12093'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12093'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12094'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12094'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12095'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12095'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12096'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12096'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12097'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12097'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12098'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12098'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12099'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12099'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12100'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12100'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12101'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12101'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12102'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12102'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12103'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12103'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12104'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12104'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '12105'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12105'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12106'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12106'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12107'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12107'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12108'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12108'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12109'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12109'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12110'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12110'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '12111'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12111'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12112'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12112'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12113'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12113'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12114'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12114'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12115'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12115'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12116'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12116'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12117'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12117'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '12118'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12118'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12119'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12119'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12120'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12120'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12121'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12121'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12122'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12122'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12123'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12123'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12124'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12124'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12125'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12125'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12126'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12126'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12127'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12127'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12128'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12128'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12129'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12129'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12130'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12130'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12131'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12131'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '12132'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12132'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12133'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12133'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '12134'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12134'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12135'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12135'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12136'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12136'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12137'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12137'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '12138'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12138'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12139'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12139'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12140'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12140'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12141'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12141'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '12142'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12142'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12143'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12143'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12144'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12144'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12145'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12145'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12146'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12146'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '12147'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12147'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12148'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12148'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12149'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12149'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12150'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12150'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12151'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12151'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '12152'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12152'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12153'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12153'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12154'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12154'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12155'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12155'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12156'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12156'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12157'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12157'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12158'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12158'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12159'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12159'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12160'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12160'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '12161'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12161'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12162'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12162'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12163'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12163'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12164'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12164'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12165'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12165'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12166'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12166'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12167'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12167'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12168'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12168'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12169'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12169'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12170'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12170'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12171'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12171'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12172'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12172'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12173'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12173'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12174'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12174'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12175'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12175'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12176'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12176'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12177'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12177'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12178'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12178'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12179'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12179'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12180'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12180'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12181'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12181'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12182'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12182'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12183'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12183'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12184'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12184'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12185'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12185'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12186'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12186'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12187'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12187'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12188'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12188'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12189'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12189'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12190'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12190'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12191'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12191'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12192'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12192'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12193'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12193'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '12194'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12194'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12195'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12195'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12196'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12196'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12197'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12197'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12198'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12198'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12199'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12199'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12200'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12200'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12201'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12201'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12202'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12202'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12203'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12203'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12204'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12204'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12205'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12205'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12206'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12206'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12207'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12207'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12208'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12208'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12209'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12209'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12210'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12210'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12211'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12211'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12212'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12212'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12213'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12213'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12214'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12214'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12215'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12215'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12216'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12216'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12217'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12217'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12218'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12218'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12219'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12219'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12220'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12220'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12221'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12221'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12222'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12222'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12223'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12223'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12224'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12224'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12225'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12225'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12226'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12226'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12227'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12227'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12228'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12228'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12229'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12229'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12230'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12230'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12231'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12231'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12232'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12232'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12233'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12233'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12234'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12234'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12235'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12235'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12236'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12236'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12237'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12237'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12238'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12238'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12239'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12239'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12240'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12240'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12241'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12241'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12242'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12242'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '12243'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12243'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12244'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12244'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12245'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12245'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12246'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12246'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12247'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12247'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12248'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12248'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12249'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12249'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12250'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12250'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12251'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12251'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '12252'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12252'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12253'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12253'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12254'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12254'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12255'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12255'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12256'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12256'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12257'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12257'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12258'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12258'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12259'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12259'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12260'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12260'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12261'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12261'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12262'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12262'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12263'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12263'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12264'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12264'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12265'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12265'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12266'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12266'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12267'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12267'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12268'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12268'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12269'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12269'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '12270'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12270'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12271'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12271'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12272'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12272'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12273'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12273'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '12274'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12274'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12275'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12275'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12276'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12276'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12277'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12277'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12278'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12278'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12279'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12279'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12280'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12280'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12281'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12281'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12282'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12282'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '12283'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12283'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12284'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12284'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12285'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12285'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '12286'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12286'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '12287'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12287'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12288'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12288'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12289'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12289'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12290'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12290'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12291'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12291'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '12292'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12292'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '12293'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12293'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12294'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12294'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '12295'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12295'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12296'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12296'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12297'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12297'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12298'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12298'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12299'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12299'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12300'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12300'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12301'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12301'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12302'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12302'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12303'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12303'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12304'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12304'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12305'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12305'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12306'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12306'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12307'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12307'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12308'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12308'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12309'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12309'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12310'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12310'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12311'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12311'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12312'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12312'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12313'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12313'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12314'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12314'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12315'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12315'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '12316'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12316'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12317'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12317'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12318'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12318'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12319'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12319'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12320'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12320'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12321'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12321'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12322'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12322'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12323'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12323'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12324'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12324'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12325'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12325'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12326'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12326'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12327'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12327'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12328'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12328'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12329'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12329'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12330'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12330'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '12331'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12331'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12332'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12332'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12333'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12333'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12334'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12334'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12335'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12335'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12336'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12336'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12337'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12337'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12338'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12338'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12339'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12339'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12340'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12340'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12341'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12341'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12342'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12342'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12343'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12343'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12344'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12344'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12345'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12345'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12346'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12346'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12347'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12347'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12348'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12348'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12349'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12349'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12350'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12350'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12351'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12351'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12352'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12352'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12353'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12353'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12354'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12354'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12355'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12355'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '12356'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12356'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12357'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12357'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12358'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12358'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12359'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12359'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12360'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12360'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12361'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12361'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12362'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12362'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12363'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12363'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12364'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12364'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12365'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12365'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12366'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12366'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12367'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12367'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12368'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12368'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12369'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12369'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12370'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12370'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '12371'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12371'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12372'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12372'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12373'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12373'

2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12374'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12374'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12375'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12375'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12376'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12376'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12377'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12377'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12378'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12378'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12379'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12379'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12380'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12380'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12381'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12381'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '12382'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12382'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12383'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12383'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12384'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12384'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12385'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12385'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12386'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12386'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12387'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12387'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '12388'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12388'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12389'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12389'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12390'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12390'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12391'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12391'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12392'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12392'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12393'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12393'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12394'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12394'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12395'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12395'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12396'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12396'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12397'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12397'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12398'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12398'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12399'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12399'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12400'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12400'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12401'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12401'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12402'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12402'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12403'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12403'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12404'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12404'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12405'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12405'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12406'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12406'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12407'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12407'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12408'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12408'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12409'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12409'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12410'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12410'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12411'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12411'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '12412'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12412'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12413'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12413'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12414'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12414'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12415'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12415'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12416'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12416'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12417'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12417'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12418'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12418'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12419'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12419'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12420'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12420'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12421'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12421'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12422'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12422'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12423'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12423'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12424'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12424'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12425'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12425'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12426'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12426'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12427'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12427'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12428'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12428'

2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12429'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12429'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12430'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12430'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12431'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12431'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12432'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12432'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12433'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12433'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12434'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12434'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12435'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12435'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12436'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12436'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12437'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12437'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12438'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12438'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12439'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12439'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12440'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12440'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12441'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12441'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12442'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12442'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12443'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12443'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12444'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12444'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12445'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12445'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '12446'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12446'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12447'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12447'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12448'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12448'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12449'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12449'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12450'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12450'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12451'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12451'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12452'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12452'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12453'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12453'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12454'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12454'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12455'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12455'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12456'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12456'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12457'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12457'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12458'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12458'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12459'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12459'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12460'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12460'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12461'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12461'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12462'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12462'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12463'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12463'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12464'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12464'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12465'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12465'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12466'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12466'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12467'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12467'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12468'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12468'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12469'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12469'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12470'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12470'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12471'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12471'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12472'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12472'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12473'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12473'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12474'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12474'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12475'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12475'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12476'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12476'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12477'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12477'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12478'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12478'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12479'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12479'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12480'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12480'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12481'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12481'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12482'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12482'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12483'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12483'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12484'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12484'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12485'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12485'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12486'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12486'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12487'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12487'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12488'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12488'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12489'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12489'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12490'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12490'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12491'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12491'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12492'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12492'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12493'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12493'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12494'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12494'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12495'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12495'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12496'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12496'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12497'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12497'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12498'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12498'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12499'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12499'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12500'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12500'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12501'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12501'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12502'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12502'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12503'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12503'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12504'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12504'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12505'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12505'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12506'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12506'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '12507'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12507'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12508'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12508'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12509'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12509'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12510'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12510'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12511'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12511'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12512'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12512'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12513'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12513'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12514'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12514'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12515'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12515'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12516'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12516'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12517'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12517'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12518'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12518'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12519'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12519'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12520'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12520'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12521'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12521'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12522'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12522'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12523'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12523'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12524'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12524'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12525'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12525'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12526'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12526'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12527'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12527'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12528'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12528'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12529'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12529'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12530'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12530'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12531'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12531'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12532'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12532'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12533'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12533'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12534'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12534'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12535'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12535'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12536'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12536'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '12537'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12537'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12538'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12538'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12539'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12539'

2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12540'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12540'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12541'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12541'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12542'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12542'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12543'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12543'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12544'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12544'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12545'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12545'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12546'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12546'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12547'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12547'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12548'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12548'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12549'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12549'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12550'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12550'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12551'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12551'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12552'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12552'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12553'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12553'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12554'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12554'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12555'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12555'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12556'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12556'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12557'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12557'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12558'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12558'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12559'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12559'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12560'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12560'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12561'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12561'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12562'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12562'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12563'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12563'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12564'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12564'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12565'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12565'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12566'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12566'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12567'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12567'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12568'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12568'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12569'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12569'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12570'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12570'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12571'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12571'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12572'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12572'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12573'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12573'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12574'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12574'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12575'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12575'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12576'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12576'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '12577'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12577'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12578'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12578'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12579'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12579'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12580'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12580'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12581'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12581'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12582'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12582'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12583'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12583'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12584'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12584'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12585'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12585'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12586'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12586'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12587'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12587'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12588'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12588'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12589'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12589'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12590'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12590'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12591'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12591'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12592'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12592'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12593'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12593'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '12594'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12594'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12595'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12595'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12596'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12596'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12597'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12597'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12598'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12598'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12599'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12599'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12600'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12600'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12601'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12601'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12602'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12602'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '12603'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12603'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12604'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12604'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12605'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12605'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12606'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12606'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12607'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12607'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12608'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12608'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12609'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12609'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12610'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12610'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12611'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12611'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12612'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12612'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12613'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12613'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12614'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12614'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12615'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12615'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12616'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12616'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12617'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12617'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12618'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12618'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12619'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12619'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12620'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12620'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12621'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12621'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12622'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12622'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12623'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12623'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12624'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12624'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12625'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12625'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12626'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12626'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12627'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12627'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12628'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12628'
2022-05-28
UPDATE job_vacancies SET open =  '2022-05-28' where raw_id = '12629'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12629'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12630'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12630'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12631'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12631'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '12632'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12632'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12633'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12633'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12634'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12634'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12635'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12635'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12636'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12636'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12637'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12637'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12638'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12638'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12639'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12639'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12640'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12640'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12641'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12641'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12642'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12642'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12643'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12643'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12644'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12644'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12645'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12645'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12646'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12646'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12647'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12647'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12648'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12648'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '12649'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12649'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12650'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12650'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12651'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12651'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12652'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12652'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12653'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12653'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12654'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12654'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12655'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12655'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '12656'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12656'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12657'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12657'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12658'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12658'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12659'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12659'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12660'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12660'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12661'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12661'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12662'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12662'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12663'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12663'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12664'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12664'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12665'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12665'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12666'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12666'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12667'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12667'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12668'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12668'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12669'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12669'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12670'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12670'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12671'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12671'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '12672'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12672'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12673'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12673'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12674'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12674'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12675'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12675'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12676'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12676'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12677'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12677'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12678'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12678'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12679'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12679'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12680'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12680'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12681'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12681'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12682'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12682'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12683'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12683'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12684'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12684'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12685'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12685'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12686'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12686'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12687'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12687'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12688'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12688'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12689'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12689'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12690'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12690'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12691'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12691'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12692'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12692'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12693'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12693'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12694'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12694'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '12695'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12695'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12696'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12696'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12697'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12697'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12698'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12698'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12699'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12699'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12700'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12700'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12701'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12701'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12702'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12702'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12703'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12703'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12704'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12704'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12705'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12705'

2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12706'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12706'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12707'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12707'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12708'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12708'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12709'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12709'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12710'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12710'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12711'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12711'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12712'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12712'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12713'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12713'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12714'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12714'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12715'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12715'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12716'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12716'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12717'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12717'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12718'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12718'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12719'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12719'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12720'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12720'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12721'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12721'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12722'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12722'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12723'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12723'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '12724'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12724'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12725'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12725'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12726'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12726'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12727'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12727'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '12728'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12728'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12729'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12729'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12730'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12730'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12731'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12731'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12732'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12732'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12733'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12733'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12734'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12734'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12735'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12735'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12736'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12736'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12737'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12737'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12738'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12738'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12739'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12739'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12740'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12740'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12741'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12741'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12742'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12742'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12743'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12743'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12744'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12744'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12745'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12745'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '12746'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12746'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12747'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12747'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12748'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12748'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12749'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12749'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '12750'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12750'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12751'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12751'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12752'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12752'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12753'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12753'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12754'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12754'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12755'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12755'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12756'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12756'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12757'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12757'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12758'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12758'

2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '12759'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12759'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12760'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12760'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12761'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12761'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12762'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12762'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12763'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12763'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12764'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12764'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12765'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12765'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '12766'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12766'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12767'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12767'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12768'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12768'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12769'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12769'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12770'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12770'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12771'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12771'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12772'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12772'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12773'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12773'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '12774'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12774'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12775'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12775'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12776'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12776'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12777'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12777'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12778'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12778'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '12779'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12779'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12780'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12780'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12781'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12781'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12782'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12782'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '12783'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12783'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12784'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12784'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12785'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12785'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12786'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12786'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12787'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12787'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12788'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12788'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12789'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12789'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '12790'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12790'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12791'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12791'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12792'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12792'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12793'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12793'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12794'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12794'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12795'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12795'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12796'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12796'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12797'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12797'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12798'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12798'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12799'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12799'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12800'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12800'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12801'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12801'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12802'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12802'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12803'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12803'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12804'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12804'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12805'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12805'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12806'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12806'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12807'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12807'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12808'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12808'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12809'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12809'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12810'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12810'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12811'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12811'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12812'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12812'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12813'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12813'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12814'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12814'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12815'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12815'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12816'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12816'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12817'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12817'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12818'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12818'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12819'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12819'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12820'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12820'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12821'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12821'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12822'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12822'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12823'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12823'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12824'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12824'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12825'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12825'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12826'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12826'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12827'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12827'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12828'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12828'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12829'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12829'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12830'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12830'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12831'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12831'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12832'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12832'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12833'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12833'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12834'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12834'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12835'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12835'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12836'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12836'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12837'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12837'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12838'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12838'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12839'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12839'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12840'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12840'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '12841'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12841'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '12842'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12842'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12843'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12843'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12844'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12844'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12845'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12845'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12846'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12846'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12847'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12847'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12848'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12848'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12849'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12849'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12850'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12850'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12851'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12851'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12852'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12852'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12853'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12853'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12854'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12854'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12855'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12855'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12856'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12856'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12857'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12857'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '12858'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12858'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12859'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12859'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12860'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12860'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12861'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12861'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12862'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12862'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12863'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12863'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12864'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12864'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12865'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12865'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12866'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12866'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12867'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12867'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12868'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12868'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12869'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12869'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12870'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12870'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12871'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12871'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12872'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12872'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12873'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12873'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12874'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12874'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12875'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12875'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12876'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12876'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12877'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12877'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12878'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12878'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12879'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12879'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12880'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12880'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12881'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12881'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12882'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12882'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12883'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12883'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12884'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12884'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12885'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12885'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12886'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12886'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '12887'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12887'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12888'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12888'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12889'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12889'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12890'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12890'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12891'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12891'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12892'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12892'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12893'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12893'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12894'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12894'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12895'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12895'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12896'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12896'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12897'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12897'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12898'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12898'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12899'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12899'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12900'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12900'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12901'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12901'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12902'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12902'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12903'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12903'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12904'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12904'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12905'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12905'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12906'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12906'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12907'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12907'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12908'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12908'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12909'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12909'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12910'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12910'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12911'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12911'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12912'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12912'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12913'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12913'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12914'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12914'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12915'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12915'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12916'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12916'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12917'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12917'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12918'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12918'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12919'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12919'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12920'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12920'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12921'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12921'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12922'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12922'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12923'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12923'

2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12924'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12924'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12925'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12925'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12926'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12926'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12927'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12927'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12928'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12928'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12929'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12929'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12930'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12930'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12931'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12931'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12932'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12932'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12933'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12933'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12934'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12934'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12935'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12935'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12936'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12936'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12937'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12937'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12938'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12938'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12939'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12939'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '12940'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12940'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12941'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12941'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12942'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12942'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12943'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12943'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12944'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12944'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '12945'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12945'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12946'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12946'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12947'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12947'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '12948'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12948'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12949'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12949'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12950'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12950'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12951'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12951'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12952'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12952'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12953'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12953'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12954'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12954'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12955'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12955'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12956'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12956'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12957'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12957'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12958'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12958'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12959'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12959'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12960'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12960'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12961'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12961'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '12962'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12962'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12963'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12963'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12964'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12964'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12965'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12965'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12966'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12966'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12967'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12967'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12968'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12968'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12969'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12969'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12970'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12970'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12971'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12971'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12972'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12972'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12973'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12973'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12974'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12974'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12975'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12975'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12976'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12976'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '12977'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12977'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12978'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12978'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12979'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12979'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12980'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12980'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12981'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12981'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12982'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12982'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12983'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12983'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12984'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12984'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12985'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12985'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12986'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12986'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12987'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12987'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12988'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12988'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12989'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12989'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12990'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12990'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '12991'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12991'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12992'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12992'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '12993'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12993'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12994'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12994'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '12995'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12995'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '12996'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12996'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12997'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12997'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '12998'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12998'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '12999'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '12999'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13000'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13000'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13001'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13001'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13002'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13002'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13003'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13003'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13004'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13004'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '13005'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13005'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13006'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13006'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13007'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13007'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13008'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13008'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13009'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13009'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13010'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13010'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13011'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13011'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13012'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13012'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13013'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13013'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13014'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13014'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13015'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13015'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13016'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13016'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '13017'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13017'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13018'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13018'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13019'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13019'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '13020'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13020'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13021'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13021'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13022'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13022'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13023'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13023'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13024'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13024'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13025'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13025'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13026'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13026'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13027'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13027'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13028'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13028'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13029'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13029'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13030'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13030'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13031'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13031'

2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13032'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13032'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13033'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13033'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13034'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13034'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13035'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13035'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13036'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13036'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '13037'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13037'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13038'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13038'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13039'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13039'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '13040'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13040'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13041'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13041'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13042'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13042'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13043'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13043'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13044'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13044'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13045'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13045'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13046'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13046'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13047'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13047'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13048'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13048'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13049'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13049'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13050'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13050'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13051'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13051'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13052'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13052'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13053'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13053'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13054'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13054'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13055'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13055'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13056'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13056'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13057'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13057'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13058'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13058'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13059'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13059'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13060'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13060'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13061'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13061'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13062'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13062'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13063'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13063'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13064'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13064'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13065'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13065'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13066'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13066'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13067'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13067'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13068'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13068'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13069'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13069'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13070'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13070'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13071'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13071'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13072'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13072'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13073'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13073'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13074'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13074'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13075'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13075'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13076'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13076'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13077'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13077'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13078'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13078'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13079'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13079'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13080'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13080'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13081'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13081'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13082'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13082'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13083'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13083'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13084'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13084'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13085'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13085'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '13086'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13086'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13087'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13087'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13088'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13088'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13089'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13089'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13090'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13090'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13091'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13091'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13092'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13092'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13093'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13093'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13094'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13094'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13095'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13095'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13096'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13096'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13097'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13097'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '13098'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13098'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13099'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13099'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13100'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13100'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13101'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13101'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13102'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13102'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '13103'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13103'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13104'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13104'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '13105'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13105'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '13106'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13106'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13107'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13107'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13108'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13108'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13109'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13109'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13110'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13110'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '13111'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13111'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13112'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13112'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13113'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13113'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13114'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13114'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '13115'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13115'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13116'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13116'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13117'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13117'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13118'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13118'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13119'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13119'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13120'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13120'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13121'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13121'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13122'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13122'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13123'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13123'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13124'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13124'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13125'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13125'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13126'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13126'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '13127'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13127'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13128'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13128'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13129'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13129'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13130'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13130'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13131'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13131'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13132'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13132'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13133'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13133'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13134'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13134'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13135'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13135'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13136'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13136'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13137'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13137'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '13138'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13138'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13139'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13139'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13140'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13140'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13141'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13141'

2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13142'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13142'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13143'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13143'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13144'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13144'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13145'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13145'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13146'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13146'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13147'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13147'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '13148'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13148'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13149'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13149'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13150'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13150'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13151'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13151'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13152'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13152'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13153'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13153'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13154'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13154'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13155'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13155'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13156'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13156'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13157'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13157'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13158'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13158'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13159'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13159'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '13160'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13160'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13161'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13161'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13162'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13162'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13163'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13163'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13164'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13164'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13165'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13165'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13166'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13166'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13167'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13167'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13168'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13168'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13169'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13169'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13170'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13170'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13171'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13171'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '13172'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13172'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13173'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13173'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13174'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13174'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13175'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13175'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13176'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13176'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13177'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13177'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13178'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13178'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13179'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13179'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13180'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13180'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13181'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13181'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13182'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13182'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13183'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13183'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13184'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13184'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13185'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13185'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13186'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13186'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13187'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13187'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13188'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13188'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13189'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13189'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '13190'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13190'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13191'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13191'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13192'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13192'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13193'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13193'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13194'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13194'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13195'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13195'

2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13196'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13196'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13197'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13197'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13198'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13198'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13199'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13199'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13200'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13200'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '13201'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13201'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13202'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13202'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13203'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13203'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '13204'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13204'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13205'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13205'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13206'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13206'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13207'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13207'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13208'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13208'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13209'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13209'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13210'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13210'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13211'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13211'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13212'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13212'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13213'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13213'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '13214'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13214'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13215'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13215'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13216'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13216'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13217'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13217'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13218'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13218'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13219'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13219'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '13220'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13220'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13221'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13221'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13222'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13222'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13223'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13223'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13224'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13224'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13225'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13225'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13226'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13226'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13227'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13227'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13228'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13228'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13229'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13229'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13230'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13230'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13231'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13231'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13232'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13232'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13233'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13233'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13234'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13234'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13235'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13235'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13236'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13236'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13237'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13237'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13238'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13238'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13239'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13239'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13240'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13240'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13241'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13241'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13242'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13242'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13243'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13243'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13244'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13244'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13245'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13245'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13246'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13246'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13247'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13247'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13248'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13248'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13249'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13249'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13250'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13250'

2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13251'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13251'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13252'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13252'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13253'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13253'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13254'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13254'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13255'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13255'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13256'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13256'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13257'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13257'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13258'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13258'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '13259'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13259'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13260'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13260'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13261'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13261'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13262'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13262'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13263'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13263'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13264'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13264'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13265'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13265'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13266'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13266'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13267'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13267'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13268'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13268'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13269'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13269'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13270'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13270'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13271'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13271'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13272'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13272'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13273'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13273'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13274'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13274'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '13275'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13275'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13276'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13276'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13277'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13277'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '13278'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13278'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13279'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13279'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13280'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13280'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '13281'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13281'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13282'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13282'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '13283'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13283'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '13284'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13284'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '13285'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13285'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13286'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13286'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13287'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13287'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13288'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13288'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13289'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13289'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13290'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13290'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '13291'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13291'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13292'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13292'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13293'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13293'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13294'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13294'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13295'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13295'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13296'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13296'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13297'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13297'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '13298'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13298'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13299'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13299'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13300'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13300'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '13301'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13301'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13302'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13302'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13303'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13303'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13304'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13304'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13305'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13305'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13306'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13306'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13307'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13307'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13308'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13308'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13309'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13309'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13310'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13310'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13311'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13311'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13312'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13312'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13313'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13313'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13314'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13314'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13315'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13315'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13316'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13316'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13317'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13317'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13318'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13318'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '13319'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13319'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13320'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13320'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '13321'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13321'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13322'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13322'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13323'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13323'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '13324'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13324'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13325'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13325'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13326'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13326'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13327'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13327'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13328'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13328'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13329'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13329'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13330'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13330'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13331'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13331'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13332'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13332'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13333'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13333'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13334'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13334'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13335'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13335'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13336'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13336'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13337'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13337'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13338'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13338'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13339'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13339'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13340'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13340'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13341'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13341'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13342'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13342'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13343'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13343'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '13344'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13344'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13345'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13345'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13346'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13346'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13347'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13347'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13348'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13348'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13349'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13349'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13350'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13350'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13351'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13351'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '13352'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13352'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13353'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13353'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13354'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13354'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13355'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13355'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13356'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13356'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13357'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13357'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13358'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13358'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13359'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13359'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13360'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13360'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13361'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13361'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13362'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13362'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13363'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13363'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13364'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13364'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13365'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13365'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13366'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13366'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13367'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13367'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13368'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13368'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13369'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13369'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '13370'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13370'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '13371'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13371'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13372'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13372'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13373'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13373'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '13374'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13374'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13375'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13375'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13376'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13376'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13377'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13377'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13378'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13378'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13379'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13379'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13380'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13380'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13381'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13381'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13382'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13382'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13383'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13383'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13384'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13384'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13385'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13385'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '13386'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13386'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13387'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13387'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13388'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13388'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13389'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13389'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13390'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13390'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '13391'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13391'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '13392'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13392'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13393'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13393'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13394'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13394'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13395'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13395'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13396'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13396'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13397'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13397'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '13398'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13398'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13399'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13399'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13400'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13400'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13401'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13401'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13402'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13402'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13403'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13403'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13404'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13404'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '13405'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13405'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13406'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13406'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13407'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13407'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13408'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13408'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13409'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13409'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13410'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13410'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13411'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13411'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13412'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13412'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13413'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13413'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13414'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13414'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13415'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13415'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13416'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13416'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '13417'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13417'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13418'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13418'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13419'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13419'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13420'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13420'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13421'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13421'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13422'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13422'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13423'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13423'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13424'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13424'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13425'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13425'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13426'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13426'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13427'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13427'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13428'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13428'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13429'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13429'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13430'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13430'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13431'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13431'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13432'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13432'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13433'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13433'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13434'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13434'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13435'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13435'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13436'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13436'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13437'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13437'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13438'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13438'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13439'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13439'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13440'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13440'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13441'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13441'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13442'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13442'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13443'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13443'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13444'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13444'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13445'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13445'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13446'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13446'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13447'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13447'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13448'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13448'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13449'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13449'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13450'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13450'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13451'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13451'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13452'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13452'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13453'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13453'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '13454'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13454'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13455'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13455'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13456'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13456'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13457'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13457'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13458'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13458'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '13459'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13459'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13460'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13460'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '13461'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13461'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '13462'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13462'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13463'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13463'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13464'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13464'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13465'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13465'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13466'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13466'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13467'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13467'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13468'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13468'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13469'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13469'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13470'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13470'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13471'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13471'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13472'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13472'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13473'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13473'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13474'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13474'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13475'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13475'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13476'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13476'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13477'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13477'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13478'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13478'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13479'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13479'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13480'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13480'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13481'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13481'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13482'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13482'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13483'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13483'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13484'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13484'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13485'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13485'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13486'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13486'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13487'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13487'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13488'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13488'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13489'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13489'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13490'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13490'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13491'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13491'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13492'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13492'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13493'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13493'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13494'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13494'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13495'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13495'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13496'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13496'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13497'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13497'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13498'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13498'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13499'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13499'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13500'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13500'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13501'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13501'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13502'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13502'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13503'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13503'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13504'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13504'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '13505'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13505'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13506'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13506'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13507'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13507'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13508'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13508'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13509'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13509'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13510'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13510'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13511'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13511'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13512'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13512'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13513'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13513'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13514'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13514'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13515'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13515'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13516'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13516'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13517'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13517'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13518'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13518'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '13519'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13519'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13520'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13520'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13521'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13521'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13522'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13522'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13523'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13523'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13524'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13524'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13525'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13525'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13526'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13526'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13527'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13527'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13528'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13528'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13529'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13529'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13530'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13530'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13531'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13531'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13532'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13532'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13533'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13533'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13534'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13534'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13535'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13535'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13536'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13536'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13537'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13537'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13538'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13538'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13539'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13539'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13540'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13540'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13541'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13541'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '13542'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13542'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13543'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13543'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13544'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13544'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13545'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13545'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13546'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13546'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13547'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13547'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '13548'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13548'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13549'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13549'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13550'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13550'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13551'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13551'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13552'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13552'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '13553'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13553'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13554'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13554'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13555'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13555'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '13556'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13556'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13557'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13557'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13558'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13558'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13559'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13559'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13560'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13560'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13561'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13561'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13562'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13562'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13563'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13563'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13564'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13564'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13565'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13565'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13566'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13566'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13567'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13567'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13568'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13568'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13569'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13569'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13570'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13570'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13571'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13571'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13572'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13572'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13573'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13573'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13574'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13574'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13575'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13575'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13576'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13576'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13577'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13577'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13578'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13578'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13579'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13579'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13580'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13580'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '13581'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13581'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13582'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13582'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13583'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13583'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13584'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13584'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '13585'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13585'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13586'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13586'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13587'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13587'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13588'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13588'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13589'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13589'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '13590'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13590'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13591'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13591'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13592'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13592'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '13593'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13593'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '13594'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13594'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '13595'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13595'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13596'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13596'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13597'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13597'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13598'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13598'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13599'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13599'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13600'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13600'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '13601'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13601'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13602'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13602'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13603'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13603'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '13604'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13604'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13605'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13605'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13606'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13606'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13607'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13607'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '13608'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13608'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13609'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13609'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13610'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13610'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13611'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13611'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13612'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13612'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13613'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13613'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13614'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13614'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13615'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13615'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13616'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13616'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13617'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13617'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13618'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13618'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13619'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13619'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13620'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13620'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13621'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13621'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '13622'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13622'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13623'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13623'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13624'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13624'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13625'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13625'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13626'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13626'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13627'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13627'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13628'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13628'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13629'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13629'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13630'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13630'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13631'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13631'

2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13632'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13632'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13633'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13633'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13634'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13634'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13635'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13635'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13636'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13636'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13637'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13637'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13638'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13638'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13639'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13639'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13640'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13640'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13641'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13641'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13642'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13642'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13643'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13643'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13644'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13644'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '13645'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13645'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '13646'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13646'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13647'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13647'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13648'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13648'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13649'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13649'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13650'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13650'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13651'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13651'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13652'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13652'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13653'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13653'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13654'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13654'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13655'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13655'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13656'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13656'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13657'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13657'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13658'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13658'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13659'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13659'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13660'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13660'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13661'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13661'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13662'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13662'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13663'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13663'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13664'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13664'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13665'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13665'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13666'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13666'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13667'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13667'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13668'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13668'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '13669'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13669'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13670'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13670'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13671'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13671'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13672'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13672'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13673'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13673'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13674'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13674'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13675'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13675'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13676'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13676'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13677'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13677'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13678'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13678'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13679'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13679'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13680'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13680'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13681'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13681'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13682'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13682'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13683'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13683'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13684'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13684'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '13685'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13685'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13686'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13686'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13687'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13687'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13688'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13688'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13689'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13689'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13690'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13690'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13691'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13691'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13692'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13692'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13693'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13693'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13694'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13694'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13695'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13695'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13696'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13696'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13697'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13697'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13698'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13698'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13699'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13699'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '13700'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13700'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13701'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13701'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13702'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13702'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '13703'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13703'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13704'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13704'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13705'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13705'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13706'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13706'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13707'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13707'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13708'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13708'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13709'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13709'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13710'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13710'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13711'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13711'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13712'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13712'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13713'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13713'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13714'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13714'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '13715'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13715'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13716'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13716'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '13717'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13717'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13718'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13718'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13719'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13719'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '13720'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13720'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13721'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13721'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13722'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13722'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13723'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13723'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13724'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13724'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13725'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13725'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13726'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13726'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13727'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13727'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13728'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13728'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13729'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13729'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13730'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13730'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13731'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13731'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13732'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13732'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13733'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13733'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13734'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13734'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13735'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13735'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13736'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13736'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13737'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13737'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13738'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13738'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13739'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13739'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13740'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13740'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '13741'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13741'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13742'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13742'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '13743'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13743'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13744'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13744'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13745'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13745'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13746'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13746'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13747'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13747'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13748'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13748'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13749'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13749'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13750'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13750'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13751'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13751'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13752'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13752'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13753'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13753'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13754'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13754'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13755'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13755'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13756'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13756'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13757'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13757'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13758'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13758'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13759'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13759'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13760'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13760'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13761'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13761'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13762'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13762'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13763'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13763'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13764'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13764'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13765'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13765'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13766'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13766'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13767'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13767'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13768'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13768'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13769'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13769'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13770'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13770'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '13771'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13771'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13772'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13772'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13773'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13773'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13774'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13774'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13775'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13775'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13776'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13776'
2022-05-29
UPDATE job_vacancies SET open =  '2022-05-29' where raw_id = '13777'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13777'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13778'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13778'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13779'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13779'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13780'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13780'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13781'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13781'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13782'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13782'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13783'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13783'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13784'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13784'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13785'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13785'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13786'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13786'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13787'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13787'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '13788'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13788'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13789'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13789'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13790'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13790'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '13791'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13791'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13792'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13792'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '13793'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13793'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13794'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13794'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13795'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13795'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13796'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13796'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13797'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13797'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13798'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13798'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '13799'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13799'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13800'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13800'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13801'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13801'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13802'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13802'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13803'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13803'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13804'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13804'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13805'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13805'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13806'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13806'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13807'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13807'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13808'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13808'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '13809'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13809'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13810'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13810'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '13811'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13811'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13812'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13812'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13813'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13813'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13814'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13814'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13815'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13815'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13816'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13816'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13817'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13817'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '13818'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13818'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13819'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13819'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '13820'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13820'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13821'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13821'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13822'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13822'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13823'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13823'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13824'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13824'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13825'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13825'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13826'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13826'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13827'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13827'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13828'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13828'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13829'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13829'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '13830'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13830'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13831'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13831'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13832'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13832'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13833'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13833'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13834'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13834'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13835'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13835'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13836'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13836'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13837'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13837'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13838'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13838'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13839'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13839'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13840'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13840'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13841'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13841'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13842'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13842'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13843'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13843'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13844'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13844'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13845'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13845'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13846'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13846'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13847'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13847'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13848'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13848'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '13849'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13849'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13850'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13850'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13851'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13851'

2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13852'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13852'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13853'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13853'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13854'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13854'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13855'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13855'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13856'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13856'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13857'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13857'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13858'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13858'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13859'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13859'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13860'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13860'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13861'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13861'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13862'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13862'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13863'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13863'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13864'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13864'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13865'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13865'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13866'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13866'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13867'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13867'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13868'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13868'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13869'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13869'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '13870'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13870'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13871'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13871'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13872'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13872'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13873'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13873'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13874'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13874'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13875'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13875'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13876'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13876'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13877'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13877'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13878'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13878'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '13879'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13879'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13880'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13880'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13881'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13881'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13882'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13882'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13883'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13883'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13884'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13884'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13885'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13885'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13886'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13886'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13887'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13887'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13888'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13888'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13889'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13889'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13890'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13890'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13891'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13891'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13892'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13892'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13893'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13893'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13894'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13894'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13895'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13895'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13896'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13896'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13897'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13897'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13898'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13898'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13899'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13899'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '13900'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13900'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13901'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13901'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13902'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13902'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13903'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13903'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13904'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13904'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13905'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13905'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13906'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13906'

2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13907'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13907'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13908'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13908'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13909'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13909'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13910'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13910'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13911'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13911'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13912'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13912'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13913'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13913'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '13914'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13914'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13915'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13915'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13916'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13916'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13917'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13917'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13918'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13918'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13919'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13919'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13920'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13920'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13921'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13921'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13922'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13922'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13923'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13923'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13924'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13924'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '13925'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13925'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13926'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13926'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13927'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13927'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13928'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13928'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13929'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13929'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13930'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13930'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13931'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13931'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13932'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13932'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13933'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13933'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13934'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13934'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13935'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13935'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13936'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13936'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '13937'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13937'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13938'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13938'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13939'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13939'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13940'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13940'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13941'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13941'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13942'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13942'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13943'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13943'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13944'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13944'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13945'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13945'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '13946'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13946'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13947'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13947'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13948'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13948'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13949'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13949'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13950'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13950'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13951'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13951'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13952'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13952'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13953'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13953'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13954'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13954'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13955'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13955'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13956'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13956'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13957'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13957'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13958'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13958'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13959'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13959'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13960'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13960'

2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13961'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13961'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13962'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13962'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13963'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13963'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13964'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13964'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '13965'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13965'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13966'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13966'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13967'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13967'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '13968'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13968'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13969'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13969'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13970'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13970'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '13971'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13971'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13972'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13972'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13973'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13973'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13974'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13974'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13975'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13975'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13976'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13976'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13977'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13977'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13978'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13978'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '13979'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13979'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13980'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13980'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13981'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13981'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13982'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13982'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13983'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13983'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13984'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13984'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13985'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13985'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13986'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13986'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13987'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13987'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13988'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13988'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13989'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13989'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13990'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13990'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13991'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13991'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13992'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13992'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13993'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13993'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '13994'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13994'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '13995'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13995'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '13996'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13996'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13997'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13997'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '13998'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13998'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '13999'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '13999'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14000'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14000'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14001'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14001'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14002'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14002'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '14003'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14003'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14004'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14004'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14005'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14005'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14006'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14006'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14007'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14007'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14008'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14008'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14009'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14009'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14010'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14010'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14011'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14011'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14012'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14012'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14013'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14013'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14014'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14014'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14015'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14015'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14016'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14016'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14017'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14017'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14018'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14018'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14019'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14019'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14020'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14020'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14021'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14021'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14022'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14022'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14023'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14023'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14024'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14024'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14025'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14025'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14026'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14026'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14027'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14027'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14028'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14028'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14029'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14029'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14030'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14030'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14031'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14031'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14032'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14032'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14033'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14033'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14034'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14034'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14035'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14035'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14036'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14036'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14037'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14037'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14038'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14038'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14039'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14039'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14040'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14040'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14041'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14041'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14042'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14042'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14043'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14043'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14044'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14044'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14045'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14045'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14046'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14046'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14047'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14047'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '14048'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14048'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14049'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14049'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14050'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14050'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14051'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14051'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14052'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14052'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14053'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14053'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '14054'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14054'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14055'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14055'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14056'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14056'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14057'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14057'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14058'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14058'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14059'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14059'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14060'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14060'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '14061'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14061'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '14062'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14062'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14063'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14063'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '14064'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14064'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14065'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14065'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14066'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14066'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14067'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14067'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14068'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14068'

2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14069'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14069'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14070'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14070'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '14071'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14071'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14072'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14072'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14073'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14073'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14074'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14074'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14075'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14075'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14076'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14076'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14077'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14077'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14078'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14078'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14079'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14079'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '14080'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14080'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '14081'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14081'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14082'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14082'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14083'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14083'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14084'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14084'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14085'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14085'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14086'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14086'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14087'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14087'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14088'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14088'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14089'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14089'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14090'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14090'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14091'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14091'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14092'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14092'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '14093'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14093'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14094'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14094'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14095'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14095'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14096'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14096'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14097'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14097'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14098'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14098'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14099'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14099'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14100'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14100'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14101'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14101'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14102'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14102'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '14103'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14103'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14104'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14104'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14105'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14105'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14106'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14106'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14107'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14107'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14108'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14108'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14109'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14109'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14110'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14110'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14111'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14111'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14112'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14112'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14113'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14113'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14114'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14114'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14115'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14115'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14116'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14116'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14117'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14117'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14118'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14118'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14119'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14119'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14120'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14120'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14121'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14121'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '14122'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14122'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14123'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14123'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14124'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14124'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14125'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14125'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14126'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14126'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14127'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14127'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14128'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14128'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14129'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14129'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14130'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14130'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14131'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14131'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14132'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14132'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14133'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14133'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14134'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14134'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14135'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14135'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14136'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14136'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14137'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14137'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '14138'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14138'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14139'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14139'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14140'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14140'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14141'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14141'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14142'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14142'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14143'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14143'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14144'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14144'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14145'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14145'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14146'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14146'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14147'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14147'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14148'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14148'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14149'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14149'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '14150'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14150'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14151'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14151'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14152'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14152'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14153'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14153'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14154'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14154'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14155'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14155'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14156'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14156'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14157'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14157'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14158'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14158'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14159'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14159'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14160'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14160'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14161'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14161'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14162'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14162'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14163'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14163'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14164'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14164'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14165'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14165'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14166'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14166'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14167'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14167'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14168'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14168'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14169'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14169'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14170'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14170'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14171'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14171'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14172'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14172'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '14173'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14173'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14174'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14174'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14175'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14175'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14176'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14176'

2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14177'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14177'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14178'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14178'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14179'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14179'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14180'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14180'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '14181'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14181'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14182'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14182'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '14183'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14183'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14184'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14184'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14185'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14185'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14186'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14186'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '14187'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14187'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14188'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14188'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14189'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14189'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14190'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14190'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14191'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14191'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14192'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14192'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14193'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14193'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14194'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14194'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14195'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14195'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14196'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14196'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14197'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14197'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14198'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14198'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14199'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14199'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14200'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14200'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14201'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14201'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14202'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14202'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14203'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14203'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14204'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14204'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14205'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14205'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14206'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14206'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14207'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14207'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14208'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14208'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14209'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14209'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14210'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14210'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14211'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14211'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14212'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14212'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14213'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14213'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14214'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14214'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14215'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14215'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14216'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14216'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14217'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14217'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14218'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14218'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14219'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14219'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '14220'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14220'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14221'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14221'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14222'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14222'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14223'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14223'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14224'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14224'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '14225'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14225'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14226'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14226'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14227'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14227'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14228'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14228'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14229'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14229'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14230'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14230'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '14231'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14231'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14232'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14232'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14233'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14233'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14234'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14234'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14235'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14235'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14236'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14236'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '14237'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14237'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14238'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14238'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14239'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14239'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14240'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14240'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14241'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14241'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14242'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14242'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14243'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14243'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14244'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14244'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14245'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14245'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14246'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14246'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14247'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14247'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14248'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14248'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14249'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14249'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14250'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14250'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14251'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14251'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14252'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14252'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '14253'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14253'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14254'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14254'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14255'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14255'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14256'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14256'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14257'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14257'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14258'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14258'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14259'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14259'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14260'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14260'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14261'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14261'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14262'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14262'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14263'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14263'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14264'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14264'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14265'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14265'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14266'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14266'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14267'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14267'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14268'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14268'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '14269'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14269'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14270'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14270'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14271'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14271'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14272'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14272'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14273'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14273'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14274'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14274'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14275'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14275'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14276'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14276'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14277'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14277'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14278'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14278'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '14279'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14279'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14280'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14280'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14281'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14281'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14282'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14282'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '14283'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14283'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14284'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14284'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14285'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14285'

2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14286'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14286'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14287'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14287'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14288'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14288'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14289'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14289'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14290'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14290'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14291'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14291'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14292'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14292'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14293'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14293'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14294'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14294'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14295'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14295'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14296'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14296'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14297'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14297'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14298'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14298'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14299'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14299'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14300'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14300'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14301'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14301'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '14302'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14302'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14303'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14303'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '14304'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14304'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14305'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14305'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14306'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14306'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14307'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14307'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14308'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14308'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14309'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14309'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14310'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14310'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14311'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14311'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14312'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14312'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14313'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14313'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14314'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14314'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14315'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14315'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14316'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14316'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14317'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14317'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14318'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14318'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14319'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14319'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14320'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14320'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14321'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14321'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14322'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14322'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14323'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14323'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14324'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14324'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14325'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14325'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14326'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14326'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14327'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14327'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14328'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14328'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14329'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14329'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '14330'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14330'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14331'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14331'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14332'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14332'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14333'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14333'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14334'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14334'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14335'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14335'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14336'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14336'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14337'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14337'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '14338'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14338'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14339'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14339'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14340'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14340'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14341'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14341'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14342'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14342'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14343'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14343'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14344'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14344'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14345'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14345'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14346'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14346'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14347'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14347'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14348'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14348'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14349'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14349'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14350'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14350'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14351'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14351'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14352'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14352'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14353'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14353'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14354'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14354'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14355'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14355'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14356'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14356'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14357'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14357'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14358'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14358'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14359'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14359'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14360'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14360'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14361'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14361'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14362'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14362'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14363'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14363'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14364'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14364'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '14365'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14365'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14366'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14366'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14367'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14367'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14368'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14368'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14369'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14369'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14370'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14370'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14371'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14371'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14372'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14372'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14373'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14373'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14374'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14374'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14375'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14375'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14376'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14376'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14377'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14377'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14378'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14378'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '14379'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14379'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14380'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14380'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14381'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14381'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '14382'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14382'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14383'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14383'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14384'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14384'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14385'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14385'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14386'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14386'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14387'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14387'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14388'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14388'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14389'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14389'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14390'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14390'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14391'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14391'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '14392'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14392'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14393'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14393'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14394'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14394'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14395'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14395'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14396'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14396'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14397'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14397'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14398'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14398'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14399'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14399'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14400'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14400'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14401'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14401'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '14402'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14402'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14403'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14403'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14404'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14404'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14405'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14405'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14406'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14406'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14407'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14407'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14408'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14408'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14409'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14409'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14410'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14410'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14411'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14411'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14412'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14412'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '14413'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14413'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14414'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14414'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14415'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14415'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '14416'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14416'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14417'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14417'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14418'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14418'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14419'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14419'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14420'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14420'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14421'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14421'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14422'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14422'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14423'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14423'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14424'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14424'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14425'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14425'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14426'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14426'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14427'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14427'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14428'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14428'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14429'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14429'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14430'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14430'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14431'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14431'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14432'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14432'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14433'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14433'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14434'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14434'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14435'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14435'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14436'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14436'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14437'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14437'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '14438'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14438'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14439'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14439'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14440'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14440'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14441'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14441'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14442'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14442'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14443'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14443'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14444'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14444'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14445'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14445'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14446'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14446'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14447'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14447'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14448'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14448'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14449'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14449'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14450'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14450'

2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14451'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14451'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14452'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14452'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14453'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14453'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14454'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14454'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14455'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14455'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14456'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14456'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14457'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14457'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14458'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14458'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '14459'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14459'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14460'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14460'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14461'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14461'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14462'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14462'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14463'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14463'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14464'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14464'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14465'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14465'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14466'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14466'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14467'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14467'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14468'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14468'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14469'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14469'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14470'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14470'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14471'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14471'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14472'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14472'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14473'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14473'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14474'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14474'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14475'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14475'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14476'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14476'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14477'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14477'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14478'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14478'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14479'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14479'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14480'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14480'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14481'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14481'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14482'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14482'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14483'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14483'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14484'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14484'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14485'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14485'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14486'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14486'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14487'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14487'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14488'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14488'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14489'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14489'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14490'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14490'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14491'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14491'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14492'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14492'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14493'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14493'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14494'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14494'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '14495'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14495'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14496'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14496'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '14497'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14497'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14498'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14498'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14499'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14499'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14500'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14500'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14501'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14501'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14502'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14502'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '14503'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14503'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14504'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14504'

2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14505'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14505'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14506'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14506'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '14507'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14507'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14508'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14508'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '14509'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14509'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14510'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14510'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14511'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14511'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14512'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14512'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14513'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14513'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14514'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14514'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14515'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14515'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14516'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14516'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14517'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14517'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14518'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14518'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14519'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14519'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14520'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14520'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14521'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14521'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14522'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14522'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14523'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14523'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14524'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14524'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14525'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14525'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14526'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14526'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14527'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14527'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14528'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14528'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14529'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14529'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14530'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14530'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14531'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14531'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14532'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14532'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14533'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14533'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14534'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14534'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14535'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14535'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14536'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14536'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14537'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14537'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14538'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14538'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14539'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14539'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14540'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14540'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14541'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14541'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14542'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14542'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14543'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14543'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '14544'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14544'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14545'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14545'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '14546'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14546'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14547'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14547'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14548'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14548'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14549'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14549'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14550'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14550'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14551'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14551'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14552'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14552'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14553'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14553'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14554'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14554'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14555'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14555'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14556'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14556'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14557'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14557'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14558'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14558'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14559'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14559'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '14560'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14560'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14561'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14561'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14562'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14562'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14563'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14563'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14564'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14564'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14565'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14565'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14566'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14566'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14567'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14567'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14568'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14568'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14569'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14569'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14570'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14570'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14571'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14571'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14572'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14572'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14573'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14573'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14574'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14574'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14575'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14575'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14576'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14576'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14577'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14577'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14578'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14578'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '14579'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14579'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14580'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14580'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14581'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14581'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14582'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14582'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14583'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14583'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14584'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14584'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14585'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14585'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14586'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14586'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14587'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14587'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14588'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14588'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14589'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14589'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14590'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14590'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '14591'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14591'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14592'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14592'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14593'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14593'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14594'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14594'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14595'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14595'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14596'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14596'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14597'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14597'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14598'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14598'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14599'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14599'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14600'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14600'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14601'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14601'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14602'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14602'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14603'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14603'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14604'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14604'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14605'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14605'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14606'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14606'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14607'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14607'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '14608'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14608'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14609'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14609'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14610'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14610'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14611'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14611'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14612'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14612'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14613'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14613'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14614'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14614'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14615'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14615'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '14616'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14616'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14617'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14617'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14618'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14618'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '14619'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14619'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14620'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14620'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14621'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14621'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14622'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14622'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14623'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14623'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14624'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14624'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14625'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14625'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14626'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14626'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14627'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14627'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '14628'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14628'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14629'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14629'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14630'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14630'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14631'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14631'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14632'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14632'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14633'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14633'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14634'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14634'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14635'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14635'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14636'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14636'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14637'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14637'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14638'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14638'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14639'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14639'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '14640'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14640'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14641'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14641'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '14642'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14642'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14643'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14643'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14644'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14644'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14645'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14645'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14646'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14646'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14647'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14647'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14648'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14648'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '14649'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14649'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14650'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14650'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14651'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14651'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14652'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14652'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14653'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14653'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14654'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14654'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14655'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14655'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14656'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14656'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14657'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14657'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14658'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14658'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14659'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14659'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14660'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14660'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14661'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14661'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14662'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14662'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14663'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14663'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '14664'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14664'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14665'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14665'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14666'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14666'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '14667'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14667'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14668'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14668'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '14669'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14669'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14670'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14670'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14671'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14671'

2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14672'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14672'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14673'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14673'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14674'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14674'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14675'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14675'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14676'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14676'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14677'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14677'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14678'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14678'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14679'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14679'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '14680'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14680'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14681'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14681'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14682'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14682'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14683'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14683'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14684'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14684'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14685'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14685'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14686'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14686'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14687'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14687'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '14688'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14688'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14689'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14689'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14690'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14690'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14691'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14691'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14692'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14692'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14693'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14693'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14694'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14694'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14695'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14695'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14696'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14696'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14697'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14697'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14698'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14698'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14699'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14699'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14700'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14700'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14701'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14701'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14702'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14702'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14703'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14703'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14704'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14704'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14705'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14705'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14706'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14706'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14707'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14707'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '14708'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14708'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14709'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14709'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14710'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14710'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14711'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14711'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14712'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14712'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14713'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14713'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14714'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14714'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14715'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14715'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14716'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14716'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14717'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14717'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14718'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14718'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14719'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14719'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14720'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14720'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14721'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14721'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14722'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14722'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14723'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14723'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '14724'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14724'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14725'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14725'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14726'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14726'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14727'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14727'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14728'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14728'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14729'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14729'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14730'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14730'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14731'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14731'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14732'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14732'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14733'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14733'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14734'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14734'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14735'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14735'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14736'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14736'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14737'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14737'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14738'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14738'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14739'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14739'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '14740'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14740'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14741'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14741'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14742'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14742'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14743'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14743'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14744'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14744'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14745'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14745'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14746'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14746'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14747'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14747'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14748'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14748'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14749'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14749'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14750'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14750'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '14751'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14751'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14752'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14752'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14753'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14753'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14754'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14754'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14755'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14755'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14756'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14756'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '14757'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14757'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14758'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14758'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14759'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14759'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14760'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14760'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '14761'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14761'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14762'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14762'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14763'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14763'
2022-05-26
UPDATE job_vacancies SET open =  '2022-05-26' where raw_id = '14764'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14764'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14765'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14765'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14766'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14766'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14767'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14767'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '14768'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14768'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14769'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14769'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14770'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14770'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14771'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14771'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14772'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14772'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14773'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14773'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14774'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14774'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14775'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14775'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14776'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14776'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14777'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14777'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14778'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14778'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14779'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14779'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14780'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14780'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14781'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14781'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14782'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14782'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14783'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14783'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14784'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14784'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14785'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14785'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14786'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14786'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14787'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14787'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14788'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14788'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14789'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14789'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14790'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14790'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14791'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14791'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '14792'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14792'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14793'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14793'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14794'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14794'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14795'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14795'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14796'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14796'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14797'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14797'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14798'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14798'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14799'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14799'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14800'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14800'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14801'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14801'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14802'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14802'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14803'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14803'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14804'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14804'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14805'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14805'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14806'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14806'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14807'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14807'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14808'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14808'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14809'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14809'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14810'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14810'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14811'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14811'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14812'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14812'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14813'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14813'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14814'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14814'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14815'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14815'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14816'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14816'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14817'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14817'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14818'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14818'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14819'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14819'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14820'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14820'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14821'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14821'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14822'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14822'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14823'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14823'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14824'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14824'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14825'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14825'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14826'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14826'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14827'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14827'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14828'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14828'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '14829'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14829'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14830'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14830'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14831'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14831'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14832'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14832'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '14833'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14833'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14834'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14834'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14835'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14835'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14836'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14836'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14837'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14837'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14838'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14838'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14839'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14839'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14840'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14840'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14841'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14841'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14842'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14842'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14843'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14843'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14844'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14844'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14845'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14845'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14846'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14846'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14847'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14847'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14848'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14848'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14849'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14849'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14850'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14850'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14851'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14851'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '14852'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14852'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14853'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14853'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14854'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14854'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '14855'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14855'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14856'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14856'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '14857'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14857'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14858'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14858'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14859'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14859'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14860'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14860'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14861'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14861'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14862'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14862'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14863'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14863'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14864'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14864'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14865'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14865'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14866'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14866'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14867'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14867'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14868'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14868'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14869'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14869'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14870'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14870'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14871'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14871'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14872'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14872'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14873'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14873'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14874'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14874'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14875'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14875'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14876'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14876'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14877'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14877'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '14878'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14878'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '14879'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14879'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14880'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14880'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14881'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14881'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14882'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14882'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14883'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14883'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14884'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14884'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14885'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14885'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14886'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14886'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14887'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14887'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14888'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14888'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14889'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14889'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14890'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14890'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14891'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14891'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14892'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14892'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14893'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14893'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14894'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14894'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14895'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14895'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14896'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14896'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14897'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14897'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14898'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14898'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '14899'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14899'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14900'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14900'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14901'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14901'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14902'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14902'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14903'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14903'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14904'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14904'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14905'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14905'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14906'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14906'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14907'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14907'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14908'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14908'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14909'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14909'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14910'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14910'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14911'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14911'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14912'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14912'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14913'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14913'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14914'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14914'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14915'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14915'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14916'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14916'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14917'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14917'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14918'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14918'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14919'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14919'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14920'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14920'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14921'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14921'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14922'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14922'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14923'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14923'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14924'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14924'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14925'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14925'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14926'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14926'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14927'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14927'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14928'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14928'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14929'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14929'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14930'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14930'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14931'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14931'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '14932'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14932'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14933'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14933'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14934'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14934'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14935'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14935'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14936'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14936'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14937'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14937'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '14938'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14938'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14939'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14939'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14940'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14940'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14941'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14941'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14942'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14942'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '14943'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14943'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14944'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14944'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14945'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14945'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14946'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14946'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14947'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14947'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14948'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14948'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14949'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14949'
2022-05-27
UPDATE job_vacancies SET open =  '2022-05-27' where raw_id = '14950'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14950'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14951'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14951'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14952'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14952'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14953'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14953'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14954'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14954'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14955'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14955'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '14956'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14956'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14957'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14957'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14958'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14958'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14959'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14959'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14960'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14960'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14961'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14961'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '14962'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14962'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '14963'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14963'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14964'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14964'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14965'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14965'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14966'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14966'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14967'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14967'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14968'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14968'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14969'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14969'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14970'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14970'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14971'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14971'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14972'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14972'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14973'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14973'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '14974'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14974'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14975'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14975'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14976'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14976'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14977'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14977'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14978'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14978'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14979'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14979'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14980'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14980'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14981'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14981'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14982'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14982'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '14983'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14983'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14984'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14984'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14985'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14985'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14986'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14986'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14987'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14987'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14988'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14988'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '14989'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14989'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14990'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14990'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14991'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14991'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '14992'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14992'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14993'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14993'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14994'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14994'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '14995'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14995'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14996'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14996'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '14997'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14997'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14998'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14998'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '14999'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '14999'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15000'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15000'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15001'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15001'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15002'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15002'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15003'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15003'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15004'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15004'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15005'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15005'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15006'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15006'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '15007'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15007'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '15008'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15008'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15009'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15009'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15010'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15010'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15011'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15011'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15012'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15012'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15013'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15013'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15014'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15014'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15015'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15015'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15016'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15016'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15017'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15017'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15018'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15018'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15019'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15019'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15020'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15020'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15021'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15021'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15022'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15022'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15023'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15023'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15024'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15024'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15025'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15025'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15026'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15026'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15027'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15027'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15028'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15028'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15029'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15029'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15030'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15030'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15031'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15031'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15032'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15032'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15033'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15033'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15034'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15034'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15035'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15035'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15036'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15036'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15037'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15037'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15038'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15038'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15039'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15039'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15040'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15040'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15041'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15041'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15042'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15042'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15043'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15043'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15044'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15044'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15045'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15045'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15046'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15046'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15047'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15047'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15048'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15048'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15049'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15049'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15050'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15050'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15051'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15051'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15052'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15052'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15053'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15053'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15054'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15054'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15055'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15055'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15056'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15056'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '15057'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15057'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15058'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15058'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15059'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15059'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15060'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15060'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15061'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15061'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15062'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15062'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15063'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15063'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15064'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15064'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15065'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15065'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15066'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15066'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15067'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15067'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15068'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15068'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15069'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15069'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '15070'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15070'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '15071'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15071'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15072'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15072'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15073'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15073'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15074'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15074'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15075'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15075'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15076'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15076'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15077'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15077'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15078'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15078'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15079'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15079'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15080'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15080'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15081'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15081'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15082'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15082'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15083'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15083'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15084'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15084'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15085'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15085'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15086'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15086'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15087'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15087'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '15088'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15088'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15089'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15089'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15090'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15090'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15091'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15091'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15092'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15092'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15093'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15093'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15094'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15094'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15095'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15095'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15096'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15096'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15097'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15097'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15098'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15098'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '15099'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15099'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15100'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15100'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15101'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15101'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '15102'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15102'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15103'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15103'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15104'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15104'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15105'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15105'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15106'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15106'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15107'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15107'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '15108'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15108'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15109'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15109'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15110'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15110'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15111'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15111'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15112'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15112'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15113'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15113'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15114'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15114'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15115'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15115'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15116'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15116'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15117'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15117'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15118'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15118'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15119'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15119'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15120'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15120'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15121'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15121'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15122'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15122'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15123'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15123'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15124'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15124'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15125'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15125'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15126'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15126'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15127'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15127'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '15128'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15128'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15129'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15129'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '15130'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15130'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15131'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15131'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15132'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15132'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15133'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15133'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15134'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15134'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15135'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15135'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '15136'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15136'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15137'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15137'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '15138'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15138'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15139'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15139'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15140'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15140'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15141'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15141'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15142'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15142'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15143'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15143'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15144'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15144'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15145'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15145'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15146'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15146'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15147'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15147'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15148'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15148'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15149'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15149'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15150'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15150'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15151'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15151'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '15152'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15152'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '15153'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15153'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15154'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15154'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15155'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15155'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15156'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15156'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15157'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15157'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15158'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15158'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15159'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15159'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15160'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15160'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15161'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15161'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15162'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15162'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15163'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15163'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15164'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15164'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15165'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15165'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15166'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15166'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15167'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15167'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15168'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15168'

2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15169'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15169'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15170'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15170'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '15171'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15171'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15172'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15172'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15173'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15173'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15174'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15174'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15175'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15175'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15176'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15176'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '15177'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15177'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15178'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15178'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15179'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15179'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15180'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15180'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15181'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15181'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '15182'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15182'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15183'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15183'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15184'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15184'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15185'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15185'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15186'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15186'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15187'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15187'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15188'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15188'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15189'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15189'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15190'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15190'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15191'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15191'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15192'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15192'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '15193'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15193'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15194'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15194'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15195'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15195'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15196'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15196'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '15197'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15197'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15198'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15198'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15199'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15199'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15200'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15200'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15201'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15201'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15202'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15202'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15203'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15203'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '15204'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15204'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15205'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15205'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15206'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15206'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15207'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15207'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15208'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15208'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15209'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15209'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15210'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15210'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15211'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15211'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15212'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15212'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15213'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15213'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '15214'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15214'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15215'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15215'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15216'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15216'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15217'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15217'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15218'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15218'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15219'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15219'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15220'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15220'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15221'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15221'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15222'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15222'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15223'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15223'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15224'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15224'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15225'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15225'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15226'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15226'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15227'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15227'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15228'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15228'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15229'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15229'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15230'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15230'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15231'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15231'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15232'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15232'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15233'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15233'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15234'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15234'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15235'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15235'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15236'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15236'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15237'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15237'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '15238'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15238'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '15239'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15239'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15240'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15240'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15241'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15241'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15242'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15242'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15243'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15243'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15244'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15244'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15245'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15245'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15246'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15246'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15247'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15247'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15248'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15248'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '15249'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15249'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15250'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15250'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15251'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15251'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '15252'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15252'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15253'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15253'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '15254'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15254'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15255'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15255'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15256'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15256'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15257'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15257'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15258'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15258'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15259'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15259'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15260'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15260'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15261'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15261'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15262'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15262'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15263'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15263'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15264'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15264'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '15265'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15265'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15266'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15266'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15267'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15267'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15268'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15268'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15269'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15269'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15270'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15270'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15271'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15271'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15272'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15272'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15273'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15273'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15274'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15274'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15275'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15275'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15276'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15276'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15277'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15277'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15278'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15278'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15279'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15279'

2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15280'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15280'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15281'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15281'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15282'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15282'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15283'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15283'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15284'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15284'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15285'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15285'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15286'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15286'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15287'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15287'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15288'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15288'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15289'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15289'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15290'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15290'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15291'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15291'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15292'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15292'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15293'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15293'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15294'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15294'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15295'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15295'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15296'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15296'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15297'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15297'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15298'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15298'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15299'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15299'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15300'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15300'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15301'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15301'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '15302'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15302'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15303'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15303'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '15304'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15304'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15305'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15305'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '15306'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15306'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15307'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15307'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15308'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15308'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15309'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15309'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15310'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15310'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15311'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15311'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15312'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15312'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '15313'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15313'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15314'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15314'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '15315'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15315'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15316'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15316'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15317'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15317'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15318'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15318'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15319'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15319'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15320'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15320'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15321'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15321'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15322'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15322'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15323'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15323'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15324'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15324'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '15325'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15325'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15326'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15326'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15327'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15327'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '15328'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15328'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15329'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15329'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15330'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15330'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15331'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15331'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15332'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15332'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '15333'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15333'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15334'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15334'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '15335'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15335'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15336'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15336'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15337'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15337'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15338'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15338'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15339'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15339'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15340'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15340'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15341'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15341'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15342'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15342'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15343'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15343'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15344'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15344'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15345'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15345'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15346'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15346'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15347'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15347'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15348'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15348'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '15349'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15349'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15350'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15350'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15351'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15351'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15352'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15352'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15353'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15353'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15354'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15354'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15355'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15355'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15356'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15356'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15357'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15357'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15358'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15358'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15359'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15359'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15360'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15360'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15361'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15361'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15362'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15362'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15363'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15363'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15364'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15364'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15365'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15365'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15366'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15366'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15367'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15367'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15368'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15368'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15369'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15369'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15370'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15370'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15371'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15371'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15372'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15372'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15373'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15373'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15374'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15374'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15375'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15375'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15376'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15376'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '15377'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15377'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15378'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15378'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15379'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15379'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15380'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15380'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15381'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15381'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15382'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15382'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15383'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15383'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15384'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15384'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15385'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15385'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15386'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15386'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15387'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15387'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15388'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15388'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15389'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15389'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '15390'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15390'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15391'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15391'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15392'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15392'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15393'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15393'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '15394'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15394'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15395'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15395'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15396'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15396'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15397'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15397'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15398'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15398'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15399'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15399'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15400'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15400'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15401'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15401'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15402'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15402'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15403'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15403'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15404'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15404'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15405'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15405'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15406'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15406'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15407'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15407'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15408'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15408'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15409'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15409'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15410'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15410'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15411'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15411'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '15412'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15412'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15413'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15413'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '15414'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15414'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15415'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15415'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15416'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15416'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15417'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15417'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15418'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15418'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15419'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15419'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15420'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15420'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15421'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15421'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15422'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15422'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15423'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15423'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '15424'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15424'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15425'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15425'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15426'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15426'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15427'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15427'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15428'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15428'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15429'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15429'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '15430'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15430'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15431'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15431'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15432'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15432'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15433'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15433'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '15434'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15434'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15435'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15435'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15436'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15436'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15437'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15437'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15438'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15438'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15439'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15439'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '15440'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15440'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15441'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15441'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15442'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15442'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15443'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15443'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15444'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15444'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15445'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15445'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15446'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15446'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15447'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15447'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15448'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15448'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15449'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15449'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15450'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15450'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15451'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15451'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15452'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15452'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15453'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15453'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15454'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15454'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '15455'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15455'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15456'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15456'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15457'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15457'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15458'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15458'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15459'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15459'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15460'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15460'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15461'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15461'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15462'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15462'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15463'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15463'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15464'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15464'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15465'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15465'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15466'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15466'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15467'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15467'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15468'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15468'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15469'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15469'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15470'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15470'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15471'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15471'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15472'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15472'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15473'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15473'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '15474'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15474'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15475'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15475'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15476'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15476'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15477'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15477'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15478'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15478'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '15479'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15479'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15480'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15480'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15481'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15481'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '15482'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15482'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15483'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15483'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '15484'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15484'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15485'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15485'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15486'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15486'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '15487'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15487'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15488'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15488'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15489'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15489'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15490'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15490'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15491'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15491'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15492'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15492'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '15493'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15493'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '15494'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15494'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15495'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15495'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15496'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15496'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15497'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15497'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15498'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15498'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15499'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15499'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15500'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15500'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '15501'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15501'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15502'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15502'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15503'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15503'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15504'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15504'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15505'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15505'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15506'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15506'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15507'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15507'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15508'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15508'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '15509'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15509'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15510'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15510'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15511'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15511'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15512'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15512'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15513'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15513'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15514'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15514'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15515'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15515'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15516'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15516'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15517'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15517'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15518'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15518'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15519'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15519'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15520'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15520'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15521'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15521'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '15522'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15522'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15523'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15523'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15524'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15524'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15525'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15525'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15526'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15526'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15527'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15527'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15528'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15528'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15529'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15529'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15530'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15530'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15531'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15531'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15532'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15532'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15533'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15533'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '15534'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15534'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15535'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15535'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '15536'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15536'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15537'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15537'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15538'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15538'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15539'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15539'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15540'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15540'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15541'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15541'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15542'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15542'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15543'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15543'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15544'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15544'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15545'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15545'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15546'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15546'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15547'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15547'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15548'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15548'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15549'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15549'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15550'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15550'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15551'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15551'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15552'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15552'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15553'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15553'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15554'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15554'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15555'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15555'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15556'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15556'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15557'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15557'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15558'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15558'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15559'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15559'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15560'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15560'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '15561'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15561'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15562'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15562'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15563'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15563'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15564'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15564'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15565'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15565'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15566'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15566'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15567'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15567'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15568'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15568'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15569'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15569'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15570'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15570'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15571'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15571'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15572'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15572'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15573'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15573'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15574'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15574'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15575'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15575'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '15576'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15576'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15577'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15577'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15578'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15578'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15579'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15579'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15580'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15580'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15581'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15581'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15582'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15582'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15583'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15583'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15584'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15584'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15585'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15585'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15586'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15586'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15587'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15587'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15588'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15588'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15589'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15589'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15590'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15590'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15591'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15591'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15592'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15592'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15593'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15593'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15594'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15594'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '15595'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15595'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '15596'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15596'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15597'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15597'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15598'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15598'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15599'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15599'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '15600'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15600'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15601'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15601'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15602'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15602'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15603'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15603'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15604'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15604'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15605'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15605'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15606'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15606'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15607'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15607'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '15608'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15608'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15609'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15609'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15610'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15610'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15611'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15611'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15612'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15612'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15613'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15613'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '15614'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15614'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15615'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15615'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15616'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15616'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15617'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15617'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15618'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15618'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15619'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15619'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15620'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15620'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15621'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15621'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '15622'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15622'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15623'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15623'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15624'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15624'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '15625'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15625'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15626'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15626'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15627'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15627'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15628'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15628'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15629'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15629'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '15630'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15630'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15631'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15631'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15632'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15632'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15633'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15633'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15634'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15634'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15635'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15635'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15636'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15636'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15637'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15637'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15638'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15638'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15639'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15639'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '15640'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15640'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15641'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15641'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '15642'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15642'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15643'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15643'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15644'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15644'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '15645'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15645'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15646'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15646'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15647'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15647'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15648'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15648'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15649'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15649'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15650'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15650'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15651'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15651'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15652'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15652'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15653'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15653'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15654'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15654'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15655'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15655'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15656'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15656'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15657'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15657'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15658'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15658'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15659'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15659'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15660'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15660'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15661'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15661'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15662'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15662'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15663'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15663'

2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15664'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15664'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15665'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15665'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15666'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15666'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15667'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15667'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15668'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15668'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15669'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15669'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15670'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15670'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15671'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15671'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15672'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15672'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '15673'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15673'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15674'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15674'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15675'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15675'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15676'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15676'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15677'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15677'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '15678'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15678'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15679'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15679'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '15680'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15680'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15681'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15681'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15682'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15682'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15683'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15683'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '15684'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15684'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15685'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15685'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15686'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15686'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15687'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15687'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15688'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15688'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15689'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15689'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15690'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15690'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15691'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15691'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15692'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15692'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '15693'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15693'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '15694'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15694'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15695'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15695'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '15696'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15696'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15697'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15697'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15698'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15698'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '15699'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15699'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15700'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15700'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '15701'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15701'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15702'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15702'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '15703'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15703'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15704'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15704'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15705'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15705'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15706'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15706'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15707'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15707'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15708'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15708'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15709'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15709'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15710'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15710'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '15711'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15711'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15712'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15712'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15713'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15713'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15714'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15714'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15715'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15715'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15716'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15716'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15717'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15717'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15718'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15718'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15719'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15719'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '15720'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15720'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '15721'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15721'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15722'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15722'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15723'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15723'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15724'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15724'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15725'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15725'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15726'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15726'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15727'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15727'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15728'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15728'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15729'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15729'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '15730'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15730'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15731'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15731'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15732'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15732'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15733'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15733'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15734'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15734'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15735'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15735'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15736'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15736'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15737'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15737'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15738'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15738'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15739'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15739'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15740'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15740'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15741'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15741'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15742'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15742'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15743'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15743'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15744'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15744'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15745'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15745'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15746'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15746'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15747'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15747'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '15748'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15748'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15749'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15749'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15750'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15750'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15751'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15751'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15752'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15752'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15753'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15753'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15754'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15754'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15755'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15755'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15756'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15756'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15757'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15757'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15758'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15758'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15759'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15759'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15760'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15760'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15761'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15761'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15762'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15762'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15763'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15763'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15764'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15764'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15765'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15765'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15766'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15766'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15767'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15767'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '15768'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15768'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15769'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15769'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15770'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15770'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15771'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15771'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15772'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15772'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15773'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15773'

2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15774'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15774'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15775'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15775'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15776'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15776'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15777'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15777'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '15778'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15778'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15779'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15779'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15780'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15780'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15781'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15781'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15782'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15782'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '15783'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15783'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15784'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15784'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '15785'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15785'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15786'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15786'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15787'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15787'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15788'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15788'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15789'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15789'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15790'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15790'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15791'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15791'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15792'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15792'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15793'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15793'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15794'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15794'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15795'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15795'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15796'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15796'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15797'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15797'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15798'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15798'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15799'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15799'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '15800'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15800'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15801'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15801'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15802'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15802'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15803'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15803'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15804'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15804'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15805'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15805'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15806'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15806'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15807'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15807'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15808'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15808'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15809'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15809'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '15810'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15810'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15811'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15811'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15812'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15812'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15813'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15813'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15814'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15814'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15815'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15815'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15816'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15816'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15817'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15817'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15818'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15818'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15819'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15819'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15820'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15820'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15821'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15821'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15822'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15822'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15823'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15823'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '15824'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15824'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '15825'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15825'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '15826'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15826'

2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15827'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15827'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15828'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15828'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15829'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15829'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15830'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15830'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15831'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15831'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15832'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15832'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15833'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15833'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '15834'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15834'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15835'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15835'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15836'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15836'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15837'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15837'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15838'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15838'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15839'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15839'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15840'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15840'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15841'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15841'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15842'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15842'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15843'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15843'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15844'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15844'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15845'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15845'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15846'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15846'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15847'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15847'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15848'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15848'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15849'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15849'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15850'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15850'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15851'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15851'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15852'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15852'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15853'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15853'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15854'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15854'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15855'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15855'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15856'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15856'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15857'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15857'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15858'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15858'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15859'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15859'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15860'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15860'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15861'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15861'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15862'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15862'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '15863'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15863'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15864'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15864'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15865'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15865'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '15866'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15866'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '15867'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15867'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15868'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15868'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15869'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15869'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15870'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15870'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15871'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15871'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15872'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15872'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15873'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15873'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15874'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15874'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '15875'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15875'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15876'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15876'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15877'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15877'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15878'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15878'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '15879'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15879'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15880'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15880'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15881'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15881'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '15882'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15882'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '15883'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15883'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15884'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15884'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15885'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15885'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15886'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15886'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '15887'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15887'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '15888'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15888'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15889'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15889'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15890'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15890'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15891'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15891'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '15892'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15892'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15893'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15893'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '15894'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15894'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15895'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15895'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '15896'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15896'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15897'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15897'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '15898'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15898'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15899'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15899'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15900'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15900'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15901'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15901'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15902'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15902'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15903'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15903'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15904'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15904'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15905'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15905'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15906'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15906'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15907'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15907'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15908'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15908'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15909'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15909'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '15910'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15910'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15911'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15911'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15912'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15912'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15913'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15913'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15914'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15914'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15915'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15915'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15916'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15916'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '15917'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15917'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15918'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15918'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15919'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15919'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15920'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15920'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '15921'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15921'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '15922'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15922'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15923'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15923'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '15924'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15924'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15925'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15925'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15926'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15926'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15927'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15927'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15928'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15928'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15929'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15929'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15930'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15930'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '15931'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15931'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15932'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15932'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15933'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15933'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15934'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15934'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15935'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15935'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15936'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15936'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '15937'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15937'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15938'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15938'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '15939'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15939'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15940'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15940'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15941'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15941'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15942'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15942'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '15943'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15943'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15944'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15944'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15945'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15945'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15946'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15946'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '15947'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15947'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15948'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15948'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15949'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15949'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15950'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15950'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15951'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15951'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15952'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15952'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15953'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15953'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15954'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15954'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15955'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15955'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '15956'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15956'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15957'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15957'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15958'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15958'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15959'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15959'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15960'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15960'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15961'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15961'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15962'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15962'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15963'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15963'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '15964'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15964'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '15965'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15965'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '15966'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15966'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15967'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15967'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '15968'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15968'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15969'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15969'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '15970'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15970'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '15971'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15971'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15972'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15972'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15973'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15973'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15974'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15974'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15975'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15975'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15976'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15976'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15977'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15977'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15978'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15978'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '15979'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15979'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15980'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15980'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '15981'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15981'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15982'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15982'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '15983'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15983'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15984'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15984'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15985'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15985'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15986'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15986'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15987'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15987'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15988'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15988'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15989'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15989'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '15990'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15990'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15991'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15991'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15992'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15992'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15993'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15993'

2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '15994'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15994'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '15995'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15995'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '15996'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15996'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '15997'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15997'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '15998'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15998'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '15999'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '15999'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16000'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16000'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16001'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16001'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16002'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16002'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16003'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16003'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16004'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16004'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '16005'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16005'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16006'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16006'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16007'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16007'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16008'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16008'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16009'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16009'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16010'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16010'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16011'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16011'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16012'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16012'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '16013'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16013'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '16014'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16014'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16015'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16015'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16016'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16016'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16017'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16017'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16018'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16018'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '16019'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16019'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16020'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16020'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16021'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16021'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16022'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16022'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16023'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16023'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16024'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16024'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16025'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16025'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16026'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16026'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '16027'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16027'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16028'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16028'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16029'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16029'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16030'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16030'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16031'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16031'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '16032'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16032'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16033'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16033'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16034'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16034'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16035'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16035'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16036'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16036'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16037'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16037'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16038'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16038'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16039'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16039'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16040'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16040'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16041'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16041'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16042'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16042'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16043'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16043'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16044'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16044'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16045'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16045'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16046'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16046'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16047'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16047'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16048'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16048'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16049'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16049'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16050'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16050'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16051'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16051'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16052'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16052'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16053'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16053'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16054'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16054'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16055'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16055'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16056'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16056'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16057'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16057'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16058'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16058'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16059'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16059'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16060'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16060'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16061'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16061'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16062'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16062'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16063'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16063'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16064'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16064'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16065'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16065'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16066'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16066'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16067'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16067'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16068'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16068'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16069'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16069'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '16070'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16070'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16071'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16071'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16072'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16072'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16073'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16073'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16074'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16074'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16075'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16075'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16076'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16076'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16077'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16077'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16078'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16078'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16079'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16079'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16080'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16080'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16081'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16081'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16082'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16082'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '16083'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16083'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16084'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16084'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16085'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16085'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16086'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16086'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16087'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16087'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16088'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16088'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '16089'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16089'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16090'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16090'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16091'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16091'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16092'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16092'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16093'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16093'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16094'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16094'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16095'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16095'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16096'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16096'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16097'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16097'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16098'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16098'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16099'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16099'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '16100'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16100'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16101'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16101'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16102'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16102'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16103'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16103'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16104'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16104'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16105'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16105'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16106'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16106'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16107'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16107'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16108'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16108'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16109'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16109'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16110'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16110'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16111'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16111'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16112'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16112'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '16113'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16113'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16114'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16114'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16115'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16115'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16116'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16116'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16117'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16117'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16118'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16118'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16119'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16119'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '16120'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16120'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16121'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16121'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16122'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16122'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16123'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16123'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16124'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16124'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16125'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16125'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16126'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16126'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16127'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16127'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16128'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16128'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16129'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16129'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16130'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16130'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16131'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16131'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16132'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16132'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16133'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16133'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16134'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16134'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16135'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16135'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16136'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16136'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '16137'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16137'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16138'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16138'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16139'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16139'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16140'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16140'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '16141'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16141'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16142'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16142'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16143'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16143'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16144'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16144'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16145'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16145'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16146'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16146'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16147'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16147'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16148'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16148'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16149'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16149'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16150'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16150'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16151'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16151'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16152'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16152'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '16153'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16153'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16154'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16154'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16155'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16155'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16156'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16156'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16157'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16157'

2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '16158'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16158'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16159'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16159'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16160'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16160'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16161'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16161'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16162'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16162'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '16163'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16163'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16164'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16164'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16165'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16165'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16166'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16166'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16167'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16167'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16168'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16168'
2022-05-22
UPDATE job_vacancies SET open =  '2022-05-22' where raw_id = '16169'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16169'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16170'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16170'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16171'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16171'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16172'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16172'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16173'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16173'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16174'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16174'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16175'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16175'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16176'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16176'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16177'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16177'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16178'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16178'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16179'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16179'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '16180'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16180'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16181'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16181'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16182'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16182'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16183'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16183'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16184'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16184'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16185'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16185'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16186'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16186'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16187'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16187'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16188'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16188'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16189'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16189'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16190'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16190'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16191'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16191'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16192'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16192'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16193'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16193'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16194'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16194'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16195'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16195'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16196'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16196'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16197'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16197'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16198'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16198'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16199'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16199'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16200'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16200'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16201'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16201'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16202'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16202'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16203'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16203'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16204'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16204'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16205'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16205'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16206'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16206'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16207'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16207'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16208'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16208'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '16209'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16209'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16210'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16210'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '16211'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16211'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16212'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16212'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16213'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16213'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16214'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16214'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16215'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16215'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16216'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16216'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16217'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16217'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16218'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16218'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16219'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16219'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16220'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16220'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16221'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16221'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16222'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16222'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16223'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16223'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16224'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16224'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16225'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16225'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16226'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16226'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16227'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16227'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '16228'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16228'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16229'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16229'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16230'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16230'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16231'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16231'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16232'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16232'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16233'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16233'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16234'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16234'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16235'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16235'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16236'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16236'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16237'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16237'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16238'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16238'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16239'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16239'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16240'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16240'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16241'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16241'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16242'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16242'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16243'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16243'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16244'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16244'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16245'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16245'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16246'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16246'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16247'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16247'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '16248'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16248'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16249'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16249'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16250'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16250'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16251'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16251'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16252'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16252'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '16253'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16253'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16254'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16254'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16255'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16255'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16256'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16256'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16257'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16257'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16258'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16258'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16259'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16259'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16260'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16260'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16261'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16261'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16262'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16262'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16263'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16263'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '16264'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16264'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16265'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16265'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16266'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16266'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16267'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16267'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16268'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16268'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16269'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16269'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '16270'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16270'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16271'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16271'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16272'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16272'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16273'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16273'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16274'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16274'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '16275'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16275'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16276'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16276'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16277'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16277'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16278'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16278'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16279'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16279'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16280'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16280'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '16281'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16281'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16282'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16282'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16283'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16283'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16284'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16284'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16285'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16285'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16286'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16286'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '16287'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16287'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16288'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16288'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '16289'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16289'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16290'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16290'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16291'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16291'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16292'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16292'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16293'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16293'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16294'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16294'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16295'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16295'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16296'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16296'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16297'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16297'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16298'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16298'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16299'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16299'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16300'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16300'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16301'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16301'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16302'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16302'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16303'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16303'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16304'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16304'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16305'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16305'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16306'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16306'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16307'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16307'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16308'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16308'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16309'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16309'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16310'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16310'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16311'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16311'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16312'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16312'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16313'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16313'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16314'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16314'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16315'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16315'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16316'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16316'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16317'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16317'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16318'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16318'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16319'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16319'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16320'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16320'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16321'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16321'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '16322'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16322'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16323'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16323'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16324'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16324'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16325'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16325'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16326'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16326'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16327'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16327'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16328'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16328'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16329'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16329'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16330'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16330'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16331'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16331'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16332'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16332'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '16333'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16333'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16334'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16334'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16335'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16335'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16336'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16336'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16337'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16337'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16338'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16338'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16339'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16339'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16340'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16340'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16341'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16341'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16342'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16342'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16343'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16343'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16344'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16344'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16345'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16345'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16346'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16346'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16347'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16347'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16348'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16348'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16349'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16349'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16350'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16350'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16351'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16351'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16352'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16352'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16353'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16353'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16354'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16354'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16355'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16355'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16356'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16356'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16357'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16357'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16358'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16358'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16359'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16359'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '16360'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16360'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16361'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16361'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16362'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16362'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16363'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16363'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16364'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16364'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16365'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16365'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16366'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16366'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16367'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16367'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16368'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16368'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16369'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16369'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16370'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16370'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '16371'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16371'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16372'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16372'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16373'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16373'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16374'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16374'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16375'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16375'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16376'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16376'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16377'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16377'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16378'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16378'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16379'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16379'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16380'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16380'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16381'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16381'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16382'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16382'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16383'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16383'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16384'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16384'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16385'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16385'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16386'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16386'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16387'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16387'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16388'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16388'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16389'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16389'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16390'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16390'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16391'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16391'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16392'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16392'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16393'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16393'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16394'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16394'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16395'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16395'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16396'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16396'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16397'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16397'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16398'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16398'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16399'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16399'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16400'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16400'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16401'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16401'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16402'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16402'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16403'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16403'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16404'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16404'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16405'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16405'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16406'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16406'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16407'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16407'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16408'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16408'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16409'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16409'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16410'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16410'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16411'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16411'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16412'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16412'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '16413'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16413'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16414'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16414'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16415'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16415'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16416'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16416'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16417'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16417'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16418'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16418'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16419'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16419'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16420'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16420'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16421'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16421'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '16422'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16422'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16423'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16423'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16424'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16424'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16425'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16425'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16426'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16426'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16427'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16427'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16428'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16428'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16429'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16429'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16430'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16430'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16431'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16431'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16432'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16432'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16433'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16433'

2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '16434'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16434'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16435'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16435'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16436'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16436'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16437'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16437'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16438'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16438'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16439'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16439'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16440'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16440'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16441'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16441'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16442'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16442'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '16443'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16443'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16444'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16444'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16445'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16445'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16446'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16446'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '16447'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16447'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16448'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16448'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16449'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16449'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16450'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16450'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16451'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16451'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16452'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16452'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '16453'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16453'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16454'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16454'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16455'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16455'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16456'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16456'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16457'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16457'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16458'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16458'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16459'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16459'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '16460'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16460'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16461'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16461'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16462'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16462'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16463'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16463'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16464'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16464'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16465'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16465'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16466'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16466'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16467'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16467'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16468'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16468'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16469'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16469'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16470'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16470'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16471'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16471'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16472'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16472'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16473'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16473'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16474'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16474'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16475'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16475'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16476'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16476'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '16477'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16477'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16478'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16478'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16479'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16479'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16480'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16480'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16481'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16481'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16482'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16482'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16483'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16483'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16484'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16484'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16485'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16485'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16486'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16486'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16487'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16487'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16488'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16488'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16489'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16489'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16490'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16490'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '16491'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16491'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16492'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16492'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16493'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16493'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16494'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16494'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '16495'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16495'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16496'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16496'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16497'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16497'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16498'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16498'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16499'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16499'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16500'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16500'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16501'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16501'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '16502'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16502'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16503'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16503'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16504'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16504'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16505'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16505'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16506'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16506'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16507'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16507'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16508'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16508'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16509'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16509'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16510'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16510'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16511'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16511'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16512'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16512'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16513'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16513'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16514'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16514'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16515'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16515'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16516'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16516'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16517'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16517'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16518'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16518'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16519'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16519'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16520'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16520'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16521'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16521'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16522'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16522'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16523'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16523'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16524'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16524'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16525'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16525'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16526'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16526'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16527'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16527'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16528'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16528'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16529'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16529'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16530'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16530'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16531'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16531'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16532'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16532'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16533'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16533'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16534'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16534'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16535'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16535'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16536'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16536'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16537'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16537'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16538'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16538'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16539'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16539'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16540'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16540'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16541'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16541'

2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16542'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16542'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16543'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16543'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16544'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16544'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16545'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16545'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16546'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16546'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16547'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16547'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16548'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16548'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16549'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16549'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16550'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16550'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16551'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16551'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16552'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16552'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16553'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16553'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16554'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16554'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16555'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16555'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16556'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16556'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16557'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16557'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16558'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16558'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16559'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16559'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16560'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16560'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16561'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16561'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16562'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16562'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16563'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16563'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16564'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16564'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16565'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16565'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16566'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16566'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16567'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16567'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16568'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16568'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16569'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16569'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16570'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16570'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16571'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16571'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16572'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16572'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16573'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16573'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16574'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16574'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16575'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16575'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16576'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16576'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16577'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16577'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16578'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16578'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16579'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16579'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16580'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16580'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16581'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16581'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '16582'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16582'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16583'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16583'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16584'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16584'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16585'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16585'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16586'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16586'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16587'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16587'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16588'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16588'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16589'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16589'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16590'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16590'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16591'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16591'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16592'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16592'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16593'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16593'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16594'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16594'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '16595'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16595'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16596'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16596'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16597'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16597'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16598'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16598'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16599'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16599'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16600'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16600'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16601'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16601'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16602'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16602'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16603'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16603'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16604'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16604'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16605'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16605'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16606'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16606'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16607'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16607'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16608'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16608'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16609'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16609'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16610'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16610'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16611'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16611'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16612'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16612'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '16613'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16613'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16614'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16614'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16615'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16615'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16616'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16616'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16617'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16617'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16618'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16618'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16619'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16619'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16620'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16620'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16621'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16621'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16622'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16622'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16623'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16623'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16624'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16624'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16625'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16625'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16626'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16626'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16627'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16627'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16628'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16628'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '16629'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16629'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16630'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16630'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16631'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16631'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16632'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16632'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16633'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16633'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16634'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16634'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16635'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16635'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16636'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16636'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16637'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16637'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16638'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16638'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16639'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16639'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16640'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16640'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16641'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16641'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16642'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16642'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16643'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16643'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16644'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16644'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16645'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16645'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16646'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16646'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16647'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16647'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16648'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16648'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16649'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16649'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16650'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16650'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16651'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16651'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16652'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16652'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16653'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16653'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16654'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16654'

2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16655'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16655'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16656'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16656'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16657'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16657'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16658'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16658'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16659'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16659'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16660'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16660'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16661'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16661'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16662'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16662'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16663'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16663'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16664'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16664'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16665'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16665'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16666'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16666'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16667'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16667'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16668'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16668'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16669'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16669'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16670'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16670'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16671'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16671'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16672'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16672'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16673'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16673'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16674'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16674'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16675'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16675'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16676'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16676'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16677'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16677'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16678'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16678'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16679'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16679'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16680'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16680'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16681'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16681'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16682'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16682'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16683'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16683'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16684'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16684'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16685'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16685'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16686'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16686'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16687'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16687'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16688'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16688'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16689'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16689'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16690'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16690'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '16691'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16691'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16692'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16692'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16693'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16693'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16694'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16694'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16695'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16695'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16696'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16696'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16697'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16697'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16698'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16698'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16699'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16699'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16700'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16700'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16701'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16701'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16702'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16702'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16703'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16703'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16704'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16704'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16705'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16705'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16706'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16706'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16707'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16707'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16708'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16708'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16709'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16709'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16710'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16710'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16711'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16711'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '16712'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16712'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16713'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16713'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16714'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16714'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16715'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16715'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16716'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16716'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16717'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16717'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16718'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16718'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16719'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16719'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16720'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16720'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16721'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16721'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16722'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16722'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16723'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16723'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16724'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16724'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16725'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16725'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16726'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16726'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16727'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16727'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16728'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16728'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16729'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16729'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16730'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16730'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16731'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16731'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16732'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16732'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16733'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16733'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16734'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16734'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16735'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16735'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16736'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16736'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16737'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16737'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16738'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16738'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16739'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16739'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16740'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16740'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16741'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16741'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16742'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16742'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16743'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16743'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16744'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16744'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16745'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16745'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16746'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16746'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16747'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16747'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16748'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16748'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16749'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16749'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16750'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16750'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16751'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16751'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16752'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16752'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16753'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16753'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16754'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16754'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16755'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16755'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16756'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16756'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16757'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16757'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16758'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16758'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16759'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16759'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16760'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16760'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16761'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16761'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16762'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16762'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16763'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16763'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16764'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16764'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16765'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16765'

2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16766'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16766'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16767'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16767'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16768'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16768'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16769'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16769'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16770'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16770'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16771'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16771'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16772'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16772'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16773'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16773'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16774'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16774'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16775'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16775'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16776'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16776'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16777'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16777'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16778'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16778'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16779'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16779'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16780'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16780'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16781'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16781'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16782'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16782'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16783'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16783'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16784'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16784'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16785'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16785'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16786'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16786'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16787'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16787'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16788'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16788'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16789'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16789'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16790'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16790'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16791'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16791'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16792'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16792'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16793'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16793'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16794'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16794'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16795'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16795'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16796'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16796'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16797'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16797'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16798'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16798'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16799'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16799'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16800'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16800'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16801'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16801'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '16802'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16802'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16803'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16803'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16804'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16804'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16805'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16805'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16806'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16806'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16807'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16807'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16808'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16808'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16809'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16809'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16810'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16810'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16811'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16811'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16812'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16812'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16813'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16813'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16814'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16814'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16815'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16815'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16816'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16816'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16817'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16817'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '16818'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16818'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16819'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16819'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16820'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16820'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16821'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16821'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '16822'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16822'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16823'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16823'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16824'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16824'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16825'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16825'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16826'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16826'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16827'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16827'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16828'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16828'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16829'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16829'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16830'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16830'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16831'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16831'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16832'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16832'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16833'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16833'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16834'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16834'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16835'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16835'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '16836'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16836'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16837'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16837'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16838'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16838'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16839'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16839'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16840'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16840'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16841'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16841'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16842'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16842'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16843'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16843'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16844'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16844'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '16845'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16845'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16846'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16846'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16847'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16847'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16848'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16848'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16849'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16849'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16850'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16850'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16851'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16851'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16852'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16852'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16853'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16853'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16854'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16854'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16855'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16855'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16856'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16856'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16857'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16857'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16858'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16858'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16859'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16859'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '16860'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16860'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16861'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16861'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16862'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16862'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16863'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16863'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16864'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16864'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16865'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16865'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16866'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16866'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16867'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16867'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16868'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16868'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16869'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16869'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16870'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16870'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16871'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16871'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16872'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16872'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16873'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16873'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16874'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16874'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16875'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16875'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16876'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16876'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16877'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16877'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16878'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16878'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16879'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16879'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16880'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16880'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16881'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16881'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16882'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16882'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16883'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16883'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16884'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16884'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16885'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16885'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16886'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16886'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16887'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16887'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16888'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16888'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16889'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16889'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16890'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16890'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16891'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16891'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '16892'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16892'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16893'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16893'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16894'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16894'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16895'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16895'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16896'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16896'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16897'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16897'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16898'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16898'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16899'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16899'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16900'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16900'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16901'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16901'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16902'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16902'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16903'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16903'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16904'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16904'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16905'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16905'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16906'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16906'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16907'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16907'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16908'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16908'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16909'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16909'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16910'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16910'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16911'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16911'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16912'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16912'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16913'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16913'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16914'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16914'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16915'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16915'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16916'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16916'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16917'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16917'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '16918'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16918'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16919'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16919'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16920'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16920'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16921'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16921'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16922'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16922'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16923'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16923'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16924'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16924'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16925'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16925'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16926'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16926'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16927'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16927'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16928'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16928'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16929'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16929'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16930'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16930'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16931'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16931'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16932'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16932'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16933'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16933'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16934'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16934'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16935'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16935'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16936'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16936'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16937'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16937'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16938'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16938'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16939'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16939'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16940'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16940'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16941'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16941'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16942'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16942'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '16943'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16943'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16944'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16944'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16945'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16945'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16946'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16946'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16947'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16947'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16948'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16948'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16949'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16949'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16950'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16950'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16951'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16951'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16952'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16952'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16953'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16953'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16954'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16954'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16955'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16955'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '16956'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16956'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '16957'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16957'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16958'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16958'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '16959'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16959'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16960'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16960'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16961'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16961'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16962'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16962'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '16963'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16963'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '16964'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16964'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16965'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16965'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '16966'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16966'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16967'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16967'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16968'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16968'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '16969'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16969'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16970'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16970'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16971'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16971'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16972'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16972'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16973'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16973'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16974'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16974'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16975'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16975'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '16976'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16976'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16977'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16977'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16978'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16978'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16979'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16979'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16980'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16980'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16981'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16981'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16982'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16982'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '16983'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16983'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16984'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16984'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16985'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16985'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16986'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16986'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16987'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16987'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16988'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16988'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16989'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16989'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16990'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16990'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '16991'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16991'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16992'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16992'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '16993'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16993'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16994'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16994'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16995'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16995'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16996'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16996'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16997'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16997'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '16998'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16998'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '16999'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '16999'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17000'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17000'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '17001'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17001'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17002'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17002'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '17003'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17003'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17004'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17004'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17005'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17005'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17006'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17006'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17007'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17007'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17008'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17008'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17009'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17009'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17010'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17010'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17011'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17011'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17012'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17012'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17013'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17013'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '17014'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17014'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17015'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17015'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17016'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17016'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17017'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17017'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17018'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17018'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17019'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17019'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17020'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17020'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17021'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17021'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17022'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17022'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17023'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17023'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17024'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17024'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17025'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17025'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17026'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17026'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17027'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17027'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17028'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17028'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17029'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17029'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '17030'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17030'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17031'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17031'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17032'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17032'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17033'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17033'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '17034'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17034'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17035'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17035'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17036'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17036'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17037'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17037'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17038'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17038'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17039'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17039'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17040'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17040'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17041'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17041'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17042'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17042'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17043'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17043'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17044'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17044'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17045'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17045'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '17046'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17046'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17047'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17047'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17048'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17048'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '17049'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17049'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17050'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17050'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17051'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17051'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17052'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17052'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17053'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17053'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17054'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17054'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '17055'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17055'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17056'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17056'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17057'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17057'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17058'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17058'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17059'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17059'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17060'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17060'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '17061'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17061'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17062'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17062'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17063'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17063'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17064'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17064'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17065'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17065'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17066'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17066'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17067'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17067'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17068'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17068'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '17069'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17069'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17070'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17070'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17071'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17071'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17072'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17072'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17073'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17073'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17074'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17074'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17075'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17075'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17076'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17076'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17077'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17077'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17078'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17078'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17079'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17079'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17080'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17080'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17081'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17081'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17082'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17082'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17083'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17083'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17084'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17084'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17085'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17085'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17086'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17086'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17087'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17087'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17088'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17088'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17089'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17089'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17090'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17090'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17091'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17091'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17092'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17092'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17093'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17093'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17094'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17094'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17095'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17095'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '17096'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17096'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17097'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17097'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17098'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17098'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17099'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17099'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17100'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17100'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17101'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17101'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17102'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17102'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17103'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17103'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '17104'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17104'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17105'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17105'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17106'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17106'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17107'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17107'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17108'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17108'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17109'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17109'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17110'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17110'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17111'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17111'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17112'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17112'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17113'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17113'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17114'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17114'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17115'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17115'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17116'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17116'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17117'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17117'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17118'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17118'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17119'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17119'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17120'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17120'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17121'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17121'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17122'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17122'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17123'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17123'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17124'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17124'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17125'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17125'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17126'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17126'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17127'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17127'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17128'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17128'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17129'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17129'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17130'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17130'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17131'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17131'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17132'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17132'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '17133'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17133'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17134'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17134'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17135'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17135'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '17136'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17136'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17137'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17137'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17138'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17138'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17139'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17139'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17140'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17140'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17141'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17141'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17142'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17142'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17143'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17143'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17144'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17144'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17145'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17145'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17146'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17146'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17147'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17147'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17148'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17148'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17149'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17149'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17150'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17150'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17151'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17151'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17152'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17152'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17153'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17153'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17154'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17154'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17155'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17155'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17156'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17156'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17157'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17157'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17158'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17158'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '17159'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17159'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17160'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17160'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17161'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17161'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17162'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17162'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17163'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17163'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17164'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17164'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17165'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17165'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17166'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17166'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17167'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17167'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17168'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17168'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17169'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17169'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17170'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17170'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '17171'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17171'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17172'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17172'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '17173'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17173'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17174'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17174'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17175'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17175'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17176'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17176'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17177'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17177'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17178'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17178'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17179'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17179'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17180'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17180'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17181'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17181'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17182'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17182'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17183'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17183'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17184'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17184'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17185'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17185'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17186'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17186'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17187'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17187'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17188'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17188'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17189'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17189'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '17190'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17190'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17191'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17191'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17192'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17192'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17193'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17193'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17194'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17194'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17195'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17195'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17196'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17196'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17197'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17197'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17198'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17198'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17199'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17199'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17200'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17200'

2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17201'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17201'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17202'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17202'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17203'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17203'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17204'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17204'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '17205'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17205'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17206'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17206'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '17207'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17207'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17208'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17208'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17209'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17209'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17210'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17210'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17211'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17211'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17212'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17212'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17213'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17213'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17214'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17214'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17215'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17215'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17216'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17216'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17217'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17217'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17218'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17218'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17219'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17219'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17220'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17220'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17221'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17221'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17222'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17222'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17223'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17223'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17224'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17224'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17225'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17225'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '17226'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17226'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17227'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17227'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17228'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17228'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17229'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17229'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17230'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17230'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17231'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17231'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '17232'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17232'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17233'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17233'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17234'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17234'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17235'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17235'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '17236'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17236'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17237'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17237'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17238'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17238'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17239'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17239'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17240'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17240'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17241'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17241'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17242'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17242'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17243'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17243'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17244'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17244'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17245'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17245'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17246'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17246'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17247'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17247'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17248'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17248'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17249'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17249'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17250'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17250'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17251'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17251'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17252'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17252'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17253'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17253'

2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17254'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17254'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17255'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17255'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17256'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17256'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17257'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17257'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17258'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17258'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17259'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17259'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17260'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17260'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17261'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17261'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17262'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17262'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '17263'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17263'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17264'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17264'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17265'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17265'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17266'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17266'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17267'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17267'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17268'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17268'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17269'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17269'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '17270'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17270'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17271'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17271'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17272'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17272'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17273'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17273'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '17274'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17274'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17275'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17275'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17276'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17276'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17277'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17277'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17278'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17278'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17279'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17279'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17280'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17280'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17281'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17281'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '17282'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17282'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17283'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17283'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17284'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17284'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17285'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17285'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17286'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17286'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '17287'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17287'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17288'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17288'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17289'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17289'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '17290'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17290'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '17291'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17291'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17292'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17292'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17293'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17293'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17294'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17294'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17295'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17295'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17296'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17296'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17297'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17297'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17298'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17298'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17299'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17299'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '17300'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17300'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17301'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17301'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17302'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17302'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '17303'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17303'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17304'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17304'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17305'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17305'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17306'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17306'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17307'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17307'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17308'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17308'

2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17309'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17309'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17310'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17310'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17311'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17311'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17312'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17312'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17313'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17313'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17314'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17314'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17315'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17315'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17316'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17316'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17317'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17317'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17318'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17318'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17319'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17319'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '17320'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17320'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17321'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17321'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17322'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17322'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17323'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17323'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '17324'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17324'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17325'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17325'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17326'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17326'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17327'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17327'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17328'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17328'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17329'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17329'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '17330'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17330'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17331'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17331'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17332'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17332'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '17333'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17333'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17334'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17334'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17335'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17335'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17336'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17336'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17337'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17337'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17338'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17338'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17339'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17339'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17340'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17340'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17341'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17341'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17342'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17342'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17343'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17343'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17344'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17344'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17345'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17345'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17346'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17346'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17347'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17347'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17348'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17348'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17349'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17349'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17350'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17350'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17351'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17351'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17352'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17352'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17353'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17353'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17354'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17354'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17355'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17355'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '17356'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17356'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17357'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17357'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17358'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17358'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17359'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17359'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17360'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17360'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17361'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17361'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17362'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17362'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17363'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17363'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17364'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17364'

2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17365'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17365'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17366'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17366'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17367'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17367'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17368'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17368'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '17369'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17369'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '17370'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17370'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17371'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17371'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17372'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17372'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17373'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17373'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17374'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17374'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17375'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17375'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17376'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17376'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17377'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17377'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17378'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17378'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17379'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17379'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17380'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17380'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17381'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17381'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17382'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17382'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17383'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17383'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17384'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17384'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17385'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17385'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17386'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17386'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17387'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17387'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17388'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17388'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17389'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17389'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17390'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17390'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17391'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17391'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17392'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17392'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17393'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17393'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17394'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17394'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17395'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17395'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17396'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17396'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17397'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17397'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17398'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17398'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17399'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17399'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17400'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17400'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17401'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17401'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17402'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17402'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17403'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17403'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17404'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17404'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17405'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17405'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17406'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17406'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17407'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17407'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17408'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17408'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17409'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17409'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17410'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17410'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17411'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17411'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17412'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17412'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17413'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17413'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17414'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17414'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17415'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17415'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17416'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17416'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17417'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17417'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17418'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17418'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '17419'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17419'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17420'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17420'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '17421'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17421'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17422'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17422'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17423'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17423'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17424'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17424'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17425'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17425'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17426'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17426'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17427'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17427'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17428'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17428'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '17429'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17429'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17430'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17430'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17431'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17431'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17432'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17432'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17433'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17433'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '17434'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17434'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17435'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17435'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17436'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17436'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17437'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17437'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17438'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17438'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17439'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17439'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17440'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17440'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '17441'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17441'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '17442'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17442'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17443'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17443'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17444'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17444'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17445'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17445'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17446'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17446'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17447'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17447'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '17448'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17448'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17449'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17449'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17450'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17450'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17451'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17451'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17452'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17452'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17453'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17453'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17454'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17454'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17455'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17455'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17456'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17456'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17457'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17457'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '17458'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17458'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17459'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17459'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '17460'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17460'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17461'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17461'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17462'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17462'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17463'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17463'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17464'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17464'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17465'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17465'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17466'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17466'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17467'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17467'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17468'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17468'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17469'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17469'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17470'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17470'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17471'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17471'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17472'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17472'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17473'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17473'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17474'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17474'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17475'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17475'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17476'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17476'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17477'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17477'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17478'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17478'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17479'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17479'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17480'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17480'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17481'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17481'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17482'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17482'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17483'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17483'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17484'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17484'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17485'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17485'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17486'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17486'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17487'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17487'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17488'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17488'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17489'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17489'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17490'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17490'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17491'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17491'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17492'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17492'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17493'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17493'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17494'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17494'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17495'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17495'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17496'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17496'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17497'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17497'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17498'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17498'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17499'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17499'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17500'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17500'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17501'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17501'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17502'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17502'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17503'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17503'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17504'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17504'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17505'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17505'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17506'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17506'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17507'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17507'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17508'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17508'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17509'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17509'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17510'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17510'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17511'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17511'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17512'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17512'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17513'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17513'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17514'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17514'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17515'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17515'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17516'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17516'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17517'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17517'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17518'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17518'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17519'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17519'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17520'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17520'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '17521'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17521'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17522'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17522'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17523'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17523'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17524'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17524'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17525'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17525'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17526'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17526'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17527'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17527'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17528'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17528'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17529'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17529'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17530'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17530'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17531'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17531'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17532'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17532'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17533'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17533'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17534'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17534'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '17535'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17535'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17536'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17536'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17537'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17537'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17538'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17538'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17539'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17539'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17540'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17540'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17541'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17541'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17542'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17542'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17543'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17543'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17544'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17544'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17545'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17545'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17546'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17546'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17547'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17547'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17548'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17548'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17549'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17549'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17550'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17550'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17551'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17551'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17552'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17552'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '17553'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17553'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17554'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17554'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '17555'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17555'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17556'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17556'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17557'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17557'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17558'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17558'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17559'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17559'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17560'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17560'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17561'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17561'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17562'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17562'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17563'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17563'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17564'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17564'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17565'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17565'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17566'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17566'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17567'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17567'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17568'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17568'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17569'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17569'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17570'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17570'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17571'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17571'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17572'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17572'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '17573'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17573'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17574'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17574'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17575'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17575'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '17576'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17576'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17577'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17577'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17578'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17578'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17579'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17579'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17580'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17580'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17581'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17581'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17582'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17582'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17583'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17583'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17584'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17584'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17585'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17585'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17586'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17586'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17587'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17587'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17588'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17588'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17589'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17589'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17590'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17590'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17591'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17591'

2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17592'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17592'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '17593'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17593'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17594'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17594'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17595'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17595'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17596'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17596'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17597'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17597'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17598'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17598'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17599'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17599'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17600'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17600'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17601'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17601'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '17602'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17602'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17603'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17603'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17604'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17604'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17605'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17605'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17606'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17606'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17607'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17607'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17608'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17608'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17609'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17609'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17610'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17610'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17611'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17611'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17612'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17612'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17613'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17613'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17614'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17614'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '17615'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17615'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '17616'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17616'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17617'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17617'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17618'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17618'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17619'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17619'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17620'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17620'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17621'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17621'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17622'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17622'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17623'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17623'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17624'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17624'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '17625'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17625'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '17626'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17626'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17627'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17627'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17628'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17628'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17629'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17629'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17630'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17630'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17631'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17631'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17632'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17632'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17633'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17633'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17634'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17634'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '17635'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17635'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17636'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17636'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17637'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17637'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17638'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17638'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17639'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17639'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17640'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17640'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '17641'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17641'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17642'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17642'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17643'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17643'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17644'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17644'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17645'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17645'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17646'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17646'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17647'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17647'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17648'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17648'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17649'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17649'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '17650'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17650'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17651'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17651'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17652'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17652'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17653'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17653'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17654'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17654'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17655'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17655'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17656'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17656'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17657'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17657'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17658'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17658'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17659'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17659'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17660'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17660'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17661'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17661'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17662'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17662'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17663'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17663'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17664'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17664'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17665'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17665'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17666'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17666'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17667'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17667'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17668'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17668'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17669'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17669'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17670'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17670'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17671'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17671'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '17672'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17672'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17673'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17673'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17674'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17674'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17675'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17675'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17676'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17676'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17677'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17677'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17678'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17678'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '17679'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17679'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17680'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17680'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '17681'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17681'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17682'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17682'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17683'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17683'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17684'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17684'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17685'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17685'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17686'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17686'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17687'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17687'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17688'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17688'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17689'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17689'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17690'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17690'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17691'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17691'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17692'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17692'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17693'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17693'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17694'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17694'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17695'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17695'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17696'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17696'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17697'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17697'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17698'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17698'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '17699'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17699'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17700'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17700'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17701'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17701'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17702'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17702'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17703'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17703'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17704'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17704'

2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17705'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17705'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17706'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17706'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17707'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17707'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17708'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17708'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17709'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17709'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17710'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17710'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17711'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17711'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17712'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17712'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17713'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17713'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '17714'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17714'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17715'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17715'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17716'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17716'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17717'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17717'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17718'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17718'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '17719'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17719'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17720'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17720'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17721'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17721'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17722'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17722'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17723'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17723'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17724'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17724'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17725'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17725'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17726'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17726'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17727'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17727'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17728'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17728'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17729'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17729'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17730'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17730'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '17731'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17731'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17732'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17732'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17733'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17733'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17734'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17734'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17735'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17735'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17736'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17736'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17737'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17737'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17738'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17738'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17739'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17739'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17740'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17740'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17741'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17741'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17742'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17742'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17743'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17743'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17744'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17744'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17745'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17745'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17746'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17746'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17747'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17747'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17748'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17748'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17749'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17749'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17750'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17750'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17751'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17751'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17752'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17752'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17753'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17753'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17754'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17754'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17755'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17755'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17756'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17756'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17757'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17757'

2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17758'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17758'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17759'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17759'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17760'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17760'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17761'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17761'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17762'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17762'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17763'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17763'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '17764'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17764'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17765'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17765'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17766'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17766'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17767'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17767'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17768'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17768'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17769'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17769'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17770'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17770'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17771'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17771'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '17772'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17772'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17773'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17773'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17774'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17774'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17775'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17775'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17776'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17776'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17777'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17777'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17778'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17778'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17779'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17779'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17780'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17780'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17781'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17781'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17782'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17782'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17783'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17783'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17784'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17784'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17785'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17785'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17786'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17786'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17787'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17787'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17788'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17788'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17789'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17789'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17790'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17790'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17791'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17791'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17792'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17792'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17793'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17793'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '17794'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17794'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17795'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17795'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17796'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17796'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17797'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17797'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17798'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17798'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17799'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17799'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17800'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17800'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17801'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17801'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17802'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17802'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17803'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17803'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '17804'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17804'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17805'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17805'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17806'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17806'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17807'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17807'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17808'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17808'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17809'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17809'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17810'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17810'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17811'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17811'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17812'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17812'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17813'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17813'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17814'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17814'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17815'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17815'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17816'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17816'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17817'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17817'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17818'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17818'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '17819'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17819'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17820'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17820'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17821'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17821'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17822'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17822'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17823'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17823'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17824'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17824'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17825'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17825'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17826'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17826'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17827'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17827'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17828'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17828'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17829'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17829'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17830'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17830'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17831'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17831'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17832'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17832'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17833'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17833'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17834'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17834'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17835'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17835'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17836'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17836'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17837'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17837'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '17838'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17838'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17839'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17839'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17840'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17840'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17841'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17841'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17842'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17842'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17843'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17843'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17844'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17844'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17845'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17845'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17846'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17846'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17847'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17847'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17848'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17848'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17849'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17849'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17850'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17850'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17851'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17851'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17852'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17852'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17853'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17853'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17854'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17854'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17855'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17855'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17856'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17856'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17857'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17857'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17858'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17858'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17859'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17859'
2022-05-21
UPDATE job_vacancies SET open =  '2022-05-21' where raw_id = '17860'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17860'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17861'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17861'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17862'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17862'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17863'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17863'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17864'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17864'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '17865'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17865'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17866'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17866'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17867'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17867'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '17868'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17868'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17869'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17869'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17870'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17870'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17871'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17871'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17872'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17872'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17873'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17873'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17874'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17874'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '17875'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17875'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '17876'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17876'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17877'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17877'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17878'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17878'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17879'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17879'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17880'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17880'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17881'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17881'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17882'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17882'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17883'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17883'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17884'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17884'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17885'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17885'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17886'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17886'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17887'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17887'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17888'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17888'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17889'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17889'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17890'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17890'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '17891'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17891'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17892'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17892'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17893'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17893'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17894'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17894'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '17895'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17895'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17896'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17896'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17897'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17897'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17898'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17898'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17899'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17899'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17900'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17900'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17901'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17901'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17902'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17902'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17903'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17903'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17904'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17904'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17905'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17905'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '17906'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17906'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17907'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17907'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17908'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17908'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17909'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17909'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '17910'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17910'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17911'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17911'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17912'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17912'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17913'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17913'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17914'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17914'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17915'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17915'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17916'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17916'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17917'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17917'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17918'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17918'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17919'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17919'
2022-05-25
UPDATE job_vacancies SET open =  '2022-05-25' where raw_id = '17920'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17920'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17921'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17921'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '17922'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17922'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17923'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17923'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '17924'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17924'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17925'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17925'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17926'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17926'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17927'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17927'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17928'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17928'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17929'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17929'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17930'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17930'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17931'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17931'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17932'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17932'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17933'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17933'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17934'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17934'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17935'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17935'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17936'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17936'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17937'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17937'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '17938'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17938'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17939'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17939'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '17940'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17940'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17941'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17941'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '17942'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17942'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17943'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17943'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17944'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17944'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17945'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17945'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17946'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17946'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17947'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17947'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17948'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17948'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17949'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17949'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17950'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17950'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17951'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17951'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17952'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17952'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17953'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17953'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17954'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17954'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17955'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17955'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17956'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17956'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17957'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17957'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17958'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17958'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17959'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17959'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17960'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17960'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17961'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17961'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17962'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17962'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17963'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17963'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17964'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17964'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17965'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17965'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17966'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17966'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17967'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17967'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '17968'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17968'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17969'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17969'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17970'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17970'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '17971'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17971'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17972'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17972'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17973'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17973'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17974'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17974'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17975'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17975'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17976'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17976'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17977'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17977'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '17978'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17978'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17979'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17979'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17980'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17980'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17981'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17981'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '17982'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17982'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17983'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17983'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17984'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17984'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17985'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17985'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17986'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17986'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17987'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17987'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17988'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17988'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '17989'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17989'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17990'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17990'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17991'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17991'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17992'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17992'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17993'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17993'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17994'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17994'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17995'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17995'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '17996'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17996'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '17997'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17997'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '17998'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17998'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '17999'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '17999'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18000'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18000'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18001'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18001'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18002'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18002'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18003'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18003'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18004'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18004'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18005'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18005'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18006'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18006'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18007'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18007'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18008'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18008'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '18009'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18009'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18010'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18010'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '18011'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18011'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18012'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18012'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18013'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18013'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18014'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18014'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18015'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18015'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18016'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18016'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18017'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18017'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18018'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18018'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18019'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18019'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18020'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18020'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18021'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18021'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18022'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18022'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18023'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18023'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18024'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18024'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18025'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18025'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18026'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18026'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18027'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18027'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18028'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18028'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18029'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18029'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18030'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18030'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '18031'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18031'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18032'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18032'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18033'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18033'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18034'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18034'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18035'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18035'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18036'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18036'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18037'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18037'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18038'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18038'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18039'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18039'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18040'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18040'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18041'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18041'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18042'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18042'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18043'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18043'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18044'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18044'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18045'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18045'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18046'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18046'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18047'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18047'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18048'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18048'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18049'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18049'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18050'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18050'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18051'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18051'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18052'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18052'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18053'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18053'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18054'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18054'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18055'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18055'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18056'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18056'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18057'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18057'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18058'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18058'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '18059'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18059'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '18060'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18060'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18061'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18061'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '18062'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18062'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18063'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18063'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18064'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18064'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '18065'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18065'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18066'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18066'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18067'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18067'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18068'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18068'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18069'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18069'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '18070'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18070'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18071'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18071'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18072'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18072'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18073'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18073'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18074'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18074'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '18075'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18075'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '18076'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18076'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18077'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18077'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18078'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18078'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18079'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18079'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18080'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18080'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18081'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18081'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18082'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18082'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '18083'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18083'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18084'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18084'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18085'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18085'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18086'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18086'

2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18087'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18087'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18088'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18088'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18089'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18089'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18090'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18090'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18091'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18091'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18092'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18092'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18093'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18093'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '18094'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18094'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18095'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18095'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18096'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18096'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '18097'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18097'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18098'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18098'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18099'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18099'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18100'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18100'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18101'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18101'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18102'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18102'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18103'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18103'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '18104'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18104'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18105'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18105'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18106'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18106'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18107'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18107'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18108'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18108'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18109'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18109'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18110'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18110'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '18111'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18111'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18112'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18112'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18113'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18113'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18114'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18114'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18115'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18115'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18116'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18116'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18117'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18117'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18118'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18118'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18119'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18119'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18120'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18120'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18121'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18121'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '18122'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18122'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18123'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18123'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18124'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18124'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18125'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18125'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18126'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18126'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '18127'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18127'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18128'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18128'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18129'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18129'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18130'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18130'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '18131'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18131'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '18132'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18132'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18133'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18133'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18134'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18134'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18135'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18135'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18136'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18136'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18137'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18137'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18138'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18138'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '18139'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18139'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18140'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18140'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18141'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18141'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18142'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18142'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18143'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18143'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18144'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18144'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18145'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18145'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18146'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18146'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18147'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18147'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18148'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18148'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18149'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18149'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18150'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18150'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18151'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18151'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18152'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18152'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18153'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18153'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18154'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18154'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18155'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18155'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18156'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18156'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18157'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18157'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18158'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18158'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18159'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18159'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '18160'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18160'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18161'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18161'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18162'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18162'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18163'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18163'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18164'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18164'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18165'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18165'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18166'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18166'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18167'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18167'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18168'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18168'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18169'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18169'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '18170'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18170'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18171'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18171'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18172'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18172'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '18173'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18173'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18174'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18174'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18175'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18175'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '18176'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18176'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18177'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18177'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18178'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18178'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18179'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18179'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18180'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18180'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18181'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18181'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18182'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18182'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18183'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18183'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18184'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18184'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18185'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18185'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18186'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18186'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18187'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18187'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18188'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18188'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18189'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18189'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18190'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18190'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18191'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18191'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18192'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18192'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18193'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18193'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '18194'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18194'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18195'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18195'

2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18196'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18196'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18197'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18197'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18198'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18198'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18199'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18199'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18200'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18200'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18201'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18201'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18202'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18202'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18203'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18203'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18204'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18204'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18205'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18205'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18206'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18206'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18207'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18207'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18208'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18208'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18209'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18209'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18210'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18210'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18211'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18211'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18212'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18212'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18213'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18213'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18214'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18214'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18215'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18215'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18216'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18216'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18217'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18217'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '18218'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18218'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18219'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18219'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18220'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18220'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18221'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18221'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18222'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18222'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18223'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18223'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18224'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18224'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18225'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18225'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18226'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18226'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18227'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18227'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18228'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18228'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18229'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18229'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18230'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18230'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18231'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18231'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18232'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18232'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18233'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18233'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18234'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18234'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18235'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18235'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18236'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18236'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18237'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18237'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18238'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18238'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18239'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18239'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18240'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18240'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18241'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18241'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18242'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18242'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18243'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18243'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18244'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18244'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18245'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18245'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18246'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18246'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18247'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18247'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18248'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18248'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '18249'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18249'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18250'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18250'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18251'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18251'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18252'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18252'

2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18253'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18253'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18254'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18254'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18255'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18255'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18256'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18256'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18257'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18257'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18258'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18258'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18259'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18259'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18260'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18260'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18261'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18261'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18262'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18262'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18263'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18263'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18264'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18264'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18265'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18265'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18266'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18266'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18267'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18267'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18268'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18268'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18269'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18269'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18270'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18270'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18271'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18271'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18272'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18272'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18273'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18273'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '18274'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18274'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18275'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18275'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '18276'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18276'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18277'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18277'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18278'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18278'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18279'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18279'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18280'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18280'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18281'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18281'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18282'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18282'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18283'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18283'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18284'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18284'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18285'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18285'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18286'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18286'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18287'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18287'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18288'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18288'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18289'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18289'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18290'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18290'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '18291'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18291'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18292'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18292'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18293'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18293'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18294'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18294'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18295'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18295'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18296'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18296'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18297'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18297'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18298'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18298'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18299'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18299'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18300'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18300'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18301'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18301'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18302'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18302'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18303'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18303'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18304'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18304'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18305'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18305'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18306'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18306'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18307'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18307'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18308'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18308'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18309'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18309'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18310'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18310'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18311'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18311'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18312'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18312'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18313'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18313'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18314'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18314'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18315'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18315'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18316'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18316'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18317'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18317'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '18318'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18318'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18319'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18319'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18320'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18320'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18321'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18321'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18322'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18322'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18323'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18323'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '18324'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18324'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18325'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18325'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '18326'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18326'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18327'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18327'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18328'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18328'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18329'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18329'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18330'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18330'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18331'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18331'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18332'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18332'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18333'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18333'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18334'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18334'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18335'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18335'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18336'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18336'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18337'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18337'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '18338'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18338'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18339'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18339'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18340'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18340'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18341'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18341'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18342'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18342'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18343'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18343'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18344'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18344'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18345'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18345'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18346'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18346'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18347'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18347'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18348'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18348'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18349'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18349'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '18350'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18350'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18351'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18351'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18352'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18352'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18353'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18353'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18354'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18354'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18355'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18355'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18356'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18356'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18357'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18357'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18358'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18358'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '18359'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18359'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18360'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18360'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18361'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18361'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18362'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18362'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '18363'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18363'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18364'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18364'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18365'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18365'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18366'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18366'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18367'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18367'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '18368'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18368'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18369'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18369'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18370'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18370'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18371'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18371'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18372'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18372'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18373'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18373'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18374'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18374'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18375'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18375'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18376'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18376'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18377'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18377'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18378'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18378'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18379'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18379'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18380'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18380'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '18381'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18381'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18382'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18382'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18383'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18383'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18384'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18384'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18385'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18385'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18386'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18386'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18387'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18387'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18388'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18388'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18389'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18389'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18390'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18390'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18391'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18391'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18392'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18392'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18393'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18393'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18394'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18394'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18395'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18395'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18396'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18396'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18397'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18397'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18398'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18398'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18399'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18399'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '18400'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18400'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18401'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18401'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18402'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18402'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18403'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18403'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18404'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18404'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18405'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18405'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18406'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18406'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18407'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18407'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18408'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18408'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18409'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18409'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18410'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18410'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18411'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18411'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18412'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18412'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18413'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18413'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18414'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18414'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18415'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18415'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18416'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18416'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18417'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18417'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '18418'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18418'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18419'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18419'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18420'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18420'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18421'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18421'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18422'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18422'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18423'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18423'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18424'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18424'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18425'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18425'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '18426'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18426'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18427'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18427'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18428'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18428'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18429'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18429'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18430'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18430'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18431'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18431'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18432'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18432'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18433'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18433'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18434'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18434'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18435'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18435'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18436'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18436'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18437'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18437'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18438'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18438'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18439'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18439'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18440'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18440'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18441'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18441'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18442'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18442'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18443'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18443'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18444'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18444'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18445'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18445'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18446'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18446'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18447'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18447'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18448'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18448'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18449'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18449'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18450'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18450'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18451'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18451'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18452'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18452'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18453'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18453'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18454'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18454'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18455'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18455'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18456'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18456'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18457'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18457'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18458'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18458'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18459'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18459'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18460'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18460'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18461'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18461'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18462'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18462'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18463'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18463'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18464'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18464'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18465'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18465'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18466'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18466'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18467'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18467'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18468'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18468'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '18469'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18469'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18470'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18470'

2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18471'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18471'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18472'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18472'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '18473'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18473'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18474'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18474'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18475'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18475'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18476'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18476'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18477'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18477'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18478'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18478'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18479'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18479'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18480'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18480'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18481'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18481'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18482'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18482'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '18483'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18483'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18484'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18484'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18485'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18485'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18486'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18486'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18487'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18487'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18488'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18488'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18489'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18489'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18490'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18490'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18491'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18491'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '18492'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18492'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18493'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18493'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18494'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18494'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18495'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18495'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18496'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18496'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18497'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18497'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18498'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18498'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18499'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18499'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18500'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18500'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18501'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18501'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18502'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18502'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18503'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18503'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18504'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18504'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18505'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18505'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18506'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18506'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18507'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18507'
2022-05-23
UPDATE job_vacancies SET open =  '2022-05-23' where raw_id = '18508'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18508'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '18509'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18509'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18510'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18510'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18511'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18511'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18512'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18512'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18513'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18513'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18514'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18514'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18515'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18515'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '18516'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18516'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18517'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18517'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18518'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18518'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18519'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18519'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18520'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18520'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18521'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18521'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18522'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18522'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18523'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18523'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18524'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18524'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18525'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18525'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18526'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18526'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18527'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18527'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18528'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18528'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18529'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18529'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18530'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18530'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18531'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18531'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18532'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18532'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18533'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18533'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18534'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18534'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18535'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18535'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18536'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18536'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18537'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18537'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18538'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18538'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18539'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18539'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18540'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18540'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18541'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18541'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18542'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18542'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18543'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18543'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18544'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18544'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18545'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18545'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18546'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18546'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18547'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18547'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18548'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18548'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18549'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18549'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18550'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18550'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18551'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18551'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18552'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18552'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18553'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18553'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18554'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18554'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18555'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18555'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18556'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18556'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18557'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18557'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18558'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18558'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18559'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18559'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18560'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18560'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18561'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18561'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18562'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18562'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18563'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18563'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18564'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18564'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18565'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18565'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18566'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18566'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18567'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18567'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18568'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18568'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18569'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18569'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18570'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18570'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18571'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18571'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18572'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18572'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18573'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18573'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18574'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18574'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18575'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18575'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18576'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18576'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18577'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18577'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18578'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18578'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18579'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18579'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18580'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18580'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18581'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18581'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18582'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18582'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18583'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18583'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18584'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18584'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18585'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18585'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18586'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18586'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18587'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18587'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18588'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18588'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '18589'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18589'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18590'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18590'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18591'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18591'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18592'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18592'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18593'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18593'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18594'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18594'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18595'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18595'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18596'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18596'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18597'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18597'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18598'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18598'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18599'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18599'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18600'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18600'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18601'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18601'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18602'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18602'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18603'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18603'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18604'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18604'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18605'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18605'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18606'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18606'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18607'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18607'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18608'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18608'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18609'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18609'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18610'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18610'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18611'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18611'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18612'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18612'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18613'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18613'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18614'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18614'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18615'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18615'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18616'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18616'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18617'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18617'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18618'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18618'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18619'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18619'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18620'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18620'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '18621'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18621'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18622'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18622'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18623'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18623'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18624'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18624'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18625'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18625'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18626'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18626'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '18627'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18627'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18628'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18628'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18629'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18629'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18630'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18630'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18631'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18631'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18632'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18632'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18633'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18633'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18634'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18634'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18635'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18635'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18636'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18636'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18637'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18637'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18638'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18638'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18639'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18639'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18640'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18640'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '18641'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18641'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18642'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18642'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18643'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18643'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18644'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18644'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18645'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18645'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18646'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18646'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18647'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18647'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18648'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18648'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18649'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18649'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18650'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18650'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18651'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18651'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18652'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18652'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18653'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18653'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18654'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18654'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18655'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18655'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18656'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18656'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18657'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18657'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18658'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18658'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18659'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18659'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18660'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18660'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18661'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18661'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '18662'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18662'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18663'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18663'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18664'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18664'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18665'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18665'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18666'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18666'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18667'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18667'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18668'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18668'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18669'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18669'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18670'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18670'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18671'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18671'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18672'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18672'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18673'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18673'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18674'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18674'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18675'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18675'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18676'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18676'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18677'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18677'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18678'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18678'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18679'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18679'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '18680'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18680'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18681'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18681'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18682'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18682'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18683'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18683'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18684'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18684'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18685'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18685'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18686'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18686'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18687'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18687'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18688'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18688'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18689'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18689'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18690'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18690'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18691'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18691'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18692'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18692'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18693'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18693'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18694'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18694'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18695'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18695'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18696'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18696'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18697'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18697'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18698'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18698'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18699'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18699'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18700'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18700'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18701'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18701'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18702'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18702'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18703'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18703'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18704'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18704'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18705'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18705'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18706'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18706'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18707'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18707'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18708'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18708'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18709'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18709'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18710'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18710'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18711'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18711'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18712'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18712'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18713'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18713'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18714'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18714'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18715'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18715'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18716'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18716'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18717'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18717'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18718'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18718'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18719'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18719'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18720'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18720'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18721'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18721'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18722'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18722'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18723'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18723'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18724'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18724'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18725'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18725'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18726'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18726'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18727'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18727'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '18728'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18728'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18729'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18729'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18730'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18730'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18731'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18731'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18732'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18732'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18733'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18733'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18734'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18734'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18735'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18735'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18736'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18736'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18737'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18737'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18738'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18738'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18739'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18739'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18740'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18740'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18741'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18741'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18742'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18742'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18743'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18743'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18744'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18744'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18745'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18745'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '18746'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18746'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18747'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18747'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18748'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18748'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18749'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18749'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18750'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18750'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18751'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18751'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '18752'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18752'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18753'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18753'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18754'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18754'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18755'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18755'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18756'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18756'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18757'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18757'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18758'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18758'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18759'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18759'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18760'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18760'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18761'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18761'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18762'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18762'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18763'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18763'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18764'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18764'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18765'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18765'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18766'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18766'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18767'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18767'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18768'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18768'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18769'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18769'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18770'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18770'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18771'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18771'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18772'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18772'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18773'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18773'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18774'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18774'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18775'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18775'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18776'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18776'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18777'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18777'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '18778'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18778'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18779'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18779'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18780'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18780'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18781'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18781'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18782'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18782'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18783'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18783'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18784'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18784'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18785'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18785'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18786'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18786'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '18787'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18787'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18788'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18788'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18789'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18789'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18790'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18790'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18791'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18791'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18792'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18792'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18793'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18793'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18794'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18794'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18795'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18795'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18796'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18796'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18797'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18797'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18798'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18798'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18799'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18799'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18800'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18800'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18801'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18801'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18802'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18802'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18803'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18803'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18804'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18804'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18805'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18805'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18806'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18806'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18807'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18807'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18808'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18808'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18809'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18809'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18810'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18810'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18811'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18811'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18812'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18812'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '18813'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18813'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18814'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18814'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18815'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18815'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18816'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18816'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18817'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18817'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18818'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18818'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18819'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18819'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18820'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18820'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18821'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18821'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18822'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18822'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18823'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18823'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '18824'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18824'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18825'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18825'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18826'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18826'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18827'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18827'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18828'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18828'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18829'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18829'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18830'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18830'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18831'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18831'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18832'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18832'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18833'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18833'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18834'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18834'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18835'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18835'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18836'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18836'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18837'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18837'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18838'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18838'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18839'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18839'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18840'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18840'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18841'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18841'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18842'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18842'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18843'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18843'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18844'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18844'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18845'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18845'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18846'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18846'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18847'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18847'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18848'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18848'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18849'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18849'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18850'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18850'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18851'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18851'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18852'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18852'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18853'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18853'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '18854'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18854'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18855'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18855'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18856'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18856'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18857'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18857'

2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18858'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18858'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18859'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18859'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18860'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18860'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18861'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18861'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18862'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18862'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '18863'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18863'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18864'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18864'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18865'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18865'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18866'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18866'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18867'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18867'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18868'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18868'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18869'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18869'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18870'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18870'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18871'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18871'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18872'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18872'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18873'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18873'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18874'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18874'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18875'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18875'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18876'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18876'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18877'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18877'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18878'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18878'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18879'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18879'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18880'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18880'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18881'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18881'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18882'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18882'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18883'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18883'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18884'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18884'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18885'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18885'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18886'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18886'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18887'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18887'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18888'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18888'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18889'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18889'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18890'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18890'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18891'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18891'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18892'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18892'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18893'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18893'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18894'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18894'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18895'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18895'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18896'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18896'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18897'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18897'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18898'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18898'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18899'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18899'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '18900'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18900'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18901'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18901'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18902'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18902'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18903'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18903'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18904'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18904'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18905'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18905'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18906'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18906'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18907'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18907'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18908'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18908'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18909'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18909'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18910'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18910'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18911'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18911'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18912'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18912'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18913'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18913'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18914'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18914'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18915'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18915'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18916'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18916'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18917'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18917'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18918'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18918'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18919'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18919'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18920'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18920'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18921'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18921'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18922'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18922'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18923'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18923'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18924'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18924'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18925'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18925'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18926'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18926'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18927'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18927'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18928'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18928'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18929'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18929'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18930'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18930'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18931'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18931'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18932'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18932'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18933'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18933'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18934'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18934'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18935'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18935'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18936'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18936'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18937'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18937'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18938'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18938'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18939'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18939'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18940'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18940'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18941'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18941'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18942'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18942'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18943'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18943'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18944'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18944'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18945'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18945'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18946'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18946'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18947'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18947'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18948'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18948'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18949'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18949'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18950'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18950'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18951'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18951'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18952'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18952'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18953'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18953'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18954'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18954'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18955'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18955'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18956'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18956'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18957'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18957'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18958'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18958'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18959'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18959'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18960'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18960'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18961'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18961'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18962'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18962'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18963'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18963'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18964'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18964'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18965'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18965'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18966'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18966'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18967'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18967'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18968'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18968'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '18969'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18969'

2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18970'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18970'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18971'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18971'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18972'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18972'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18973'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18973'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18974'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18974'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18975'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18975'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18976'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18976'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18977'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18977'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18978'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18978'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18979'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18979'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18980'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18980'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18981'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18981'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18982'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18982'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18983'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18983'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18984'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18984'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18985'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18985'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18986'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18986'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18987'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18987'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18988'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18988'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18989'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18989'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18990'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18990'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18991'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18991'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18992'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18992'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18993'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18993'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18994'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18994'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '18995'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18995'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '18996'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18996'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '18997'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18997'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '18998'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18998'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '18999'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '18999'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19000'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19000'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19001'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19001'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19002'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19002'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19003'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19003'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19004'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19004'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '19005'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19005'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19006'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19006'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19007'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19007'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19008'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19008'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19009'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19009'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19010'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19010'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19011'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19011'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19012'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19012'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19013'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19013'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19014'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19014'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19015'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19015'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19016'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19016'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19017'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19017'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19018'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19018'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19019'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19019'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19020'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19020'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19021'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19021'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19022'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19022'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19023'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19023'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19024'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19024'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19025'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19025'

2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19026'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19026'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19027'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19027'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19028'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19028'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19029'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19029'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19030'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19030'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19031'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19031'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19032'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19032'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '19033'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19033'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19034'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19034'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19035'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19035'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19036'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19036'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19037'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19037'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19038'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19038'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '19039'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19039'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19040'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19040'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '19041'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19041'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19042'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19042'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19043'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19043'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19044'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19044'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19045'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19045'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '19046'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19046'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19047'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19047'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19048'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19048'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19049'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19049'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19050'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19050'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19051'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19051'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19052'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19052'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '19053'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19053'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19054'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19054'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19055'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19055'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19056'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19056'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19057'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19057'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19058'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19058'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19059'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19059'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19060'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19060'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19061'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19061'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19062'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19062'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19063'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19063'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19064'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19064'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19065'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19065'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19066'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19066'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19067'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19067'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19068'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19068'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19069'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19069'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19070'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19070'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '19071'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19071'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19072'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19072'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19073'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19073'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19074'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19074'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19075'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19075'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19076'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19076'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19077'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19077'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19078'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19078'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19079'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19079'

2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19080'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19080'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19081'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19081'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19082'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19082'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19083'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19083'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19084'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19084'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19085'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19085'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19086'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19086'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19087'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19087'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19088'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19088'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19089'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19089'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19090'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19090'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19091'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19091'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19092'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19092'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19093'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19093'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19094'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19094'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19095'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19095'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19096'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19096'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19097'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19097'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19098'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19098'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19099'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19099'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19100'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19100'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19101'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19101'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19102'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19102'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19103'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19103'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19104'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19104'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19105'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19105'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19106'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19106'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19107'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19107'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19108'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19108'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19109'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19109'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19110'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19110'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19111'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19111'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19112'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19112'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19113'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19113'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19114'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19114'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19115'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19115'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19116'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19116'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19117'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19117'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19118'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19118'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19119'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19119'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19120'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19120'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19121'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19121'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19122'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19122'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19123'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19123'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '19124'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19124'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19125'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19125'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19126'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19126'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19127'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19127'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19128'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19128'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '19129'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19129'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19130'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19130'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '19131'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19131'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19132'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19132'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19133'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19133'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19134'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19134'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19135'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19135'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19136'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19136'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19137'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19137'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19138'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19138'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '19139'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19139'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19140'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19140'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19141'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19141'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19142'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19142'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19143'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19143'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19144'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19144'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '19145'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19145'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19146'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19146'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19147'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19147'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19148'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19148'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19149'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19149'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19150'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19150'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19151'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19151'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19152'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19152'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19153'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19153'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19154'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19154'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '19155'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19155'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19156'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19156'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '19157'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19157'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19158'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19158'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '19159'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19159'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19160'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19160'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19161'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19161'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19162'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19162'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19163'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19163'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19164'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19164'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19165'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19165'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19166'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19166'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19167'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19167'
2022-05-24
UPDATE job_vacancies SET open =  '2022-05-24' where raw_id = '19168'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19168'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19169'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19169'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19170'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19170'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19171'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19171'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19172'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19172'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19173'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19173'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19174'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19174'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19175'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19175'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19176'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19176'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19177'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19177'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19178'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19178'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19179'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19179'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19180'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19180'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19181'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19181'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19182'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19182'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19183'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19183'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19184'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19184'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19185'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19185'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19186'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19186'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19187'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19187'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19188'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19188'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19189'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19189'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19190'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19190'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '19191'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19191'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '19192'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19192'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19193'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19193'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19194'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19194'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19195'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19195'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19196'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19196'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19197'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19197'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19198'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19198'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19199'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19199'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19200'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19200'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '19201'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19201'
2022-05-08
UPDATE job_vacancies SET open =  '2022-05-08' where raw_id = '19202'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19202'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19203'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19203'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19204'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19204'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19205'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19205'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19206'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19206'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19207'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19207'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19208'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19208'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19209'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19209'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19210'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19210'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19211'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19211'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19212'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19212'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19213'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19213'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19214'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19214'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19215'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19215'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19216'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19216'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19217'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19217'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19218'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19218'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19219'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19219'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19220'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19220'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19221'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19221'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19222'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19222'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19223'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19223'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19224'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19224'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19225'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19225'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19226'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19226'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19227'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19227'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19228'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19228'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19229'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19229'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19230'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19230'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19231'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19231'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19232'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19232'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19233'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19233'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19234'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19234'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19235'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19235'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19236'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19236'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19237'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19237'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19238'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19238'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19239'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19239'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19240'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19240'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19241'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19241'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19242'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19242'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19243'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19243'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19244'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19244'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19245'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19245'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19246'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19246'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19247'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19247'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19248'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19248'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19249'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19249'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19250'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19250'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '19251'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19251'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19252'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19252'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19253'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19253'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19254'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19254'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19255'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19255'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19256'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19256'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19257'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19257'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19258'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19258'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19259'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19259'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19260'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19260'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19261'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19261'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19262'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19262'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19263'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19263'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19264'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19264'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19265'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19265'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19266'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19266'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19267'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19267'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19268'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19268'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19269'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19269'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '19270'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19270'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19271'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19271'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19272'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19272'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19273'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19273'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19274'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19274'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19275'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19275'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19276'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19276'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19277'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19277'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19278'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19278'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '19279'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19279'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19280'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19280'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19281'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19281'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19282'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19282'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19283'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19283'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19284'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19284'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19285'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19285'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19286'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19286'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19287'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19287'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19288'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19288'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19289'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19289'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19290'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19290'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19291'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19291'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19292'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19292'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19293'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19293'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19294'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19294'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19295'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19295'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19296'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19296'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19297'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19297'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19298'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19298'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19299'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19299'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19300'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19300'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19301'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19301'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19302'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19302'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19303'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19303'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19304'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19304'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19305'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19305'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19306'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19306'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19307'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19307'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19308'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19308'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19309'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19309'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '19310'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19310'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19311'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19311'

2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19312'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19312'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19313'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19313'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19314'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19314'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19315'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19315'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19316'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19316'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19317'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19317'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19318'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19318'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19319'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19319'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19320'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19320'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19321'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19321'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19322'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19322'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19323'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19323'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19324'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19324'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19325'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19325'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19326'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19326'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19327'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19327'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19328'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19328'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19329'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19329'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19330'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19330'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19331'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19331'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19332'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19332'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19333'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19333'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19334'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19334'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19335'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19335'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19336'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19336'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19337'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19337'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19338'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19338'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19339'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19339'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19340'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19340'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19341'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19341'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19342'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19342'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19343'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19343'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19344'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19344'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19345'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19345'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19346'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19346'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19347'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19347'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19348'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19348'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19349'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19349'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19350'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19350'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19351'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19351'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19352'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19352'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19353'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19353'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19354'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19354'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19355'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19355'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19356'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19356'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19357'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19357'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19358'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19358'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19359'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19359'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19360'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19360'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19361'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19361'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19362'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19362'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19363'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19363'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19364'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19364'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19365'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19365'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19366'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19366'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19367'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19367'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19368'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19368'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19369'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19369'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19370'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19370'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19371'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19371'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19372'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19372'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19373'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19373'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19374'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19374'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19375'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19375'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19376'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19376'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19377'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19377'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19378'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19378'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19379'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19379'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19380'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19380'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19381'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19381'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19382'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19382'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '19383'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19383'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19384'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19384'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19385'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19385'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19386'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19386'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19387'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19387'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '19388'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19388'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19389'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19389'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19390'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19390'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19391'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19391'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19392'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19392'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19393'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19393'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19394'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19394'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19395'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19395'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19396'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19396'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19397'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19397'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19398'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19398'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19399'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19399'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19400'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19400'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19401'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19401'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19402'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19402'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19403'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19403'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19404'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19404'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19405'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19405'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19406'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19406'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19407'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19407'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19408'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19408'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19409'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19409'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19410'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19410'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '19411'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19411'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19412'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19412'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19413'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19413'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19414'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19414'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19415'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19415'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19416'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19416'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19417'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19417'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19418'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19418'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19419'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19419'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19420'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19420'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19421'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19421'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19422'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19422'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19423'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19423'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19424'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19424'
2022-05-08
UPDATE job_vacancies SET open =  '2022-05-08' where raw_id = '19425'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19425'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19426'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19426'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19427'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19427'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19428'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19428'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '19429'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19429'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19430'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19430'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19431'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19431'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19432'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19432'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19433'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19433'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19434'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19434'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19435'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19435'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19436'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19436'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19437'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19437'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '19438'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19438'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19439'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19439'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19440'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19440'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19441'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19441'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19442'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19442'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19443'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19443'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19444'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19444'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19445'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19445'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19446'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19446'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19447'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19447'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19448'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19448'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19449'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19449'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19450'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19450'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19451'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19451'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19452'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19452'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19453'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19453'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19454'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19454'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19455'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19455'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19456'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19456'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19457'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19457'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19458'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19458'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19459'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19459'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19460'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19460'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19461'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19461'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19462'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19462'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19463'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19463'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19464'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19464'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19465'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19465'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19466'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19466'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19467'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19467'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19468'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19468'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19469'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19469'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19470'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19470'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19471'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19471'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19472'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19472'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19473'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19473'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19474'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19474'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19475'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19475'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19476'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19476'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19477'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19477'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19478'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19478'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19479'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19479'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19480'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19480'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19481'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19481'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19482'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19482'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19483'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19483'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19484'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19484'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19485'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19485'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19486'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19486'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19487'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19487'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19488'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19488'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19489'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19489'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19490'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19490'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19491'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19491'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19492'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19492'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19493'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19493'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19494'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19494'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19495'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19495'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19496'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19496'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19497'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19497'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19498'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19498'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19499'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19499'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19500'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19500'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19501'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19501'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19502'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19502'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19503'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19503'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19504'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19504'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19505'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19505'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19506'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19506'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19507'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19507'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19508'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19508'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19509'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19509'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19510'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19510'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19511'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19511'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19512'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19512'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19513'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19513'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19514'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19514'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19515'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19515'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19516'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19516'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19517'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19517'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '19518'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19518'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19519'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19519'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19520'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19520'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19521'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19521'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19522'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19522'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19523'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19523'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '19524'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19524'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19525'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19525'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19526'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19526'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19527'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19527'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19528'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19528'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19529'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19529'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19530'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19530'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19531'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19531'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19532'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19532'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19533'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19533'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19534'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19534'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19535'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19535'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19536'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19536'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19537'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19537'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19538'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19538'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19539'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19539'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19540'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19540'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19541'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19541'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19542'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19542'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19543'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19543'

2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19544'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19544'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19545'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19545'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19546'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19546'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19547'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19547'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19548'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19548'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19549'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19549'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19550'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19550'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19551'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19551'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19552'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19552'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19553'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19553'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19554'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19554'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19555'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19555'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19556'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19556'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19557'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19557'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19558'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19558'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19559'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19559'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19560'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19560'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19561'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19561'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19562'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19562'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19563'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19563'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19564'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19564'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19565'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19565'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19566'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19566'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19567'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19567'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19568'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19568'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19569'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19569'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19570'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19570'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19571'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19571'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19572'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19572'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19573'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19573'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19574'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19574'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19575'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19575'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '19576'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19576'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19577'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19577'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19578'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19578'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19579'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19579'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19580'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19580'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19581'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19581'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19582'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19582'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19583'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19583'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19584'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19584'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19585'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19585'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19586'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19586'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19587'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19587'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19588'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19588'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19589'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19589'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19590'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19590'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19591'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19591'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19592'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19592'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19593'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19593'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19594'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19594'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19595'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19595'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19596'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19596'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19597'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19597'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19598'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19598'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19599'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19599'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19600'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19600'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19601'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19601'

2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19602'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19602'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19603'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19603'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19604'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19604'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19605'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19605'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19606'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19606'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19607'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19607'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19608'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19608'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19609'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19609'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19610'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19610'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19611'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19611'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19612'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19612'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19613'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19613'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19614'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19614'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19615'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19615'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19616'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19616'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19617'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19617'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19618'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19618'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19619'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19619'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19620'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19620'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19621'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19621'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19622'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19622'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19623'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19623'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '19624'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19624'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19625'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19625'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19626'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19626'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19627'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19627'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19628'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19628'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19629'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19629'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19630'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19630'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19631'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19631'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19632'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19632'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19633'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19633'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '19634'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19634'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19635'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19635'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19636'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19636'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19637'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19637'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19638'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19638'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19639'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19639'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19640'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19640'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19641'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19641'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '19642'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19642'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19643'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19643'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19644'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19644'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19645'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19645'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19646'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19646'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19647'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19647'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19648'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19648'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19649'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19649'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19650'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19650'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19651'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19651'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19652'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19652'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19653'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19653'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '19654'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19654'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19655'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19655'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19656'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19656'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19657'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19657'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19658'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19658'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19659'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19659'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '19660'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19660'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19661'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19661'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19662'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19662'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19663'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19663'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19664'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19664'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19665'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19665'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19666'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19666'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19667'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19667'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19668'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19668'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19669'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19669'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19670'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19670'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19671'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19671'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19672'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19672'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19673'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19673'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19674'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19674'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19675'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19675'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19676'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19676'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19677'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19677'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19678'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19678'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19679'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19679'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19680'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19680'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19681'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19681'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19682'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19682'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19683'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19683'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19684'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19684'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19685'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19685'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19686'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19686'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19687'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19687'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19688'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19688'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19689'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19689'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19690'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19690'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19691'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19691'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19692'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19692'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19693'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19693'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19694'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19694'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '19695'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19695'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19696'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19696'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19697'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19697'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19698'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19698'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '19699'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19699'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19700'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19700'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19701'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19701'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19702'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19702'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19703'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19703'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19704'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19704'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19705'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19705'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19706'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19706'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19707'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19707'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19708'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19708'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19709'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19709'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19710'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19710'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19711'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19711'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19712'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19712'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19713'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19713'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19714'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19714'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19715'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19715'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19716'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19716'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19717'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19717'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19718'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19718'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19719'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19719'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19720'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19720'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19721'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19721'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19722'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19722'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19723'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19723'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19724'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19724'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19725'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19725'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19726'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19726'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19727'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19727'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19728'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19728'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19729'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19729'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19730'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19730'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19731'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19731'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19732'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19732'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19733'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19733'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19734'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19734'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19735'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19735'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '19736'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19736'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19737'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19737'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19738'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19738'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19739'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19739'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19740'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19740'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19741'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19741'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19742'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19742'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '19743'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19743'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19744'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19744'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '19745'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19745'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19746'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19746'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19747'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19747'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19748'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19748'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19749'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19749'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19750'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19750'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19751'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19751'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19752'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19752'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19753'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19753'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19754'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19754'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19755'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19755'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19756'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19756'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19757'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19757'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19758'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19758'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19759'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19759'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '19760'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19760'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19761'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19761'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19762'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19762'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19763'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19763'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19764'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19764'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19765'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19765'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19766'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19766'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19767'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19767'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19768'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19768'

2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19769'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19769'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '19770'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19770'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19771'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19771'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19772'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19772'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19773'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19773'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19774'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19774'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19775'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19775'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19776'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19776'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19777'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19777'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '19778'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19778'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19779'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19779'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19780'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19780'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19781'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19781'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19782'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19782'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19783'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19783'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19784'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19784'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19785'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19785'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19786'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19786'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19787'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19787'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19788'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19788'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19789'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19789'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19790'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19790'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19791'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19791'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19792'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19792'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19793'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19793'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19794'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19794'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19795'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19795'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19796'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19796'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19797'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19797'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19798'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19798'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19799'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19799'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19800'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19800'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19801'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19801'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19802'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19802'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19803'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19803'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19804'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19804'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19805'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19805'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19806'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19806'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19807'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19807'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19808'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19808'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19809'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19809'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19810'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19810'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19811'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19811'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19812'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19812'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19813'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19813'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19814'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19814'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19815'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19815'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19816'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19816'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19817'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19817'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19818'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19818'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19819'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19819'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19820'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19820'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19821'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19821'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19822'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19822'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19823'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19823'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19824'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19824'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19825'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19825'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19826'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19826'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19827'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19827'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19828'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19828'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19829'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19829'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19830'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19830'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19831'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19831'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19832'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19832'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19833'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19833'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19834'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19834'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19835'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19835'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19836'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19836'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19837'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19837'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19838'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19838'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19839'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19839'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19840'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19840'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19841'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19841'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19842'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19842'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19843'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19843'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19844'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19844'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19845'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19845'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19846'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19846'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19847'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19847'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19848'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19848'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19849'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19849'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19850'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19850'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19851'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19851'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19852'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19852'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19853'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19853'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '19854'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19854'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19855'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19855'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19856'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19856'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19857'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19857'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19858'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19858'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19859'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19859'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19860'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19860'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19861'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19861'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19862'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19862'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19863'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19863'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19864'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19864'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19865'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19865'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19866'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19866'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19867'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19867'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19868'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19868'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19869'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19869'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19870'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19870'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19871'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19871'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19872'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19872'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19873'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19873'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19874'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19874'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19875'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19875'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19876'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19876'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19877'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19877'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19878'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19878'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19879'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19879'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19880'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19880'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19881'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19881'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19882'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19882'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19883'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19883'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19884'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19884'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19885'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19885'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19886'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19886'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19887'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19887'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19888'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19888'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19889'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19889'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19890'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19890'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19891'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19891'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19892'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19892'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19893'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19893'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19894'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19894'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19895'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19895'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19896'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19896'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19897'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19897'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19898'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19898'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19899'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19899'
2022-05-08
UPDATE job_vacancies SET open =  '2022-05-08' where raw_id = '19900'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19900'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19901'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19901'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19902'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19902'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19903'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19903'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19904'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19904'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19905'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19905'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19906'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19906'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19907'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19907'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19908'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19908'
2022-05-20
UPDATE job_vacancies SET open =  '2022-05-20' where raw_id = '19909'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19909'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19910'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19910'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19911'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19911'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19912'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19912'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19913'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19913'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19914'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19914'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19915'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19915'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19916'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19916'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19917'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19917'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19918'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19918'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19919'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19919'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19920'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19920'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19921'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19921'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19922'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19922'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19923'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19923'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '19924'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19924'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19925'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19925'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19926'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19926'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19927'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19927'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19928'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19928'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19929'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19929'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19930'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19930'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19931'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19931'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19932'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19932'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19933'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19933'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19934'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19934'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19935'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19935'

2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19936'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19936'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19937'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19937'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19938'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19938'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19939'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19939'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19940'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19940'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '19941'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19941'
2022-05-07
UPDATE job_vacancies SET open =  '2022-05-07' where raw_id = '19942'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19942'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19943'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19943'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19944'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19944'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19945'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19945'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19946'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19946'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19947'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19947'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19948'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19948'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19949'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19949'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19950'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19950'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19951'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19951'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '19952'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19952'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19953'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19953'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19954'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19954'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19955'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19955'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19956'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19956'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '19957'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19957'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19958'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19958'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '19959'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19959'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19960'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19960'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19961'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19961'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19962'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19962'
2022-05-06
UPDATE job_vacancies SET open =  '2022-05-06' where raw_id = '19963'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19963'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19964'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19964'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19965'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19965'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19966'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19966'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19967'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19967'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19968'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19968'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19969'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19969'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19970'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19970'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19971'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19971'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19972'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19972'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19973'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19973'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19974'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19974'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19975'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19975'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19976'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19976'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19977'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19977'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19978'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19978'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19979'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19979'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19980'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19980'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19981'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19981'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19982'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19982'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19983'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19983'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19984'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19984'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19985'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19985'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19986'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19986'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19987'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19987'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19988'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19988'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19989'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19989'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19990'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19990'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19991'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19991'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '19992'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19992'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '19993'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19993'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19994'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19994'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '19995'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19995'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '19996'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19996'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19997'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19997'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19998'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19998'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '19999'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '19999'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20000'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20000'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20001'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20001'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20002'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20002'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20003'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20003'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '20004'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20004'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20005'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20005'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20006'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20006'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20007'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20007'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20008'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20008'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20009'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20009'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '20010'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20010'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20011'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20011'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20012'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20012'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20013'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20013'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20014'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20014'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20015'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20015'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20016'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20016'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20017'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20017'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20018'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20018'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20019'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20019'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20020'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20020'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20021'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20021'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20022'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20022'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20023'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20023'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20024'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20024'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20025'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20025'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20026'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20026'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20027'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20027'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20028'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20028'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20029'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20029'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20030'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20030'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20031'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20031'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20032'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20032'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20033'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20033'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20034'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20034'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20035'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20035'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20036'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20036'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20037'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20037'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20038'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20038'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20039'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20039'
2022-05-08
UPDATE job_vacancies SET open =  '2022-05-08' where raw_id = '20040'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20040'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20041'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20041'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20042'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20042'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20043'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20043'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20044'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20044'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '20045'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20045'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20046'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20046'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20047'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20047'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20048'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20048'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20049'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20049'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20050'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20050'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20051'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20051'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20052'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20052'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '20053'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20053'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20054'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20054'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20055'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20055'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20056'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20056'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20057'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20057'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20058'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20058'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20059'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20059'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20060'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20060'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20061'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20061'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20062'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20062'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20063'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20063'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20064'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20064'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20065'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20065'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20066'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20066'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20067'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20067'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20068'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20068'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20069'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20069'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20070'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20070'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20071'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20071'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20072'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20072'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20073'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20073'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20074'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20074'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20075'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20075'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20076'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20076'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20077'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20077'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20078'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20078'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20079'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20079'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20080'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20080'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20081'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20081'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20082'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20082'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20083'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20083'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20084'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20084'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20085'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20085'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20086'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20086'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20087'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20087'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20088'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20088'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20089'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20089'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20090'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20090'
2022-05-19
UPDATE job_vacancies SET open =  '2022-05-19' where raw_id = '20091'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20091'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20092'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20092'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20093'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20093'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20094'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20094'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '20095'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20095'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20096'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20096'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '20097'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20097'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '20098'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20098'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20099'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20099'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20100'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20100'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20101'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20101'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '20102'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20102'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20103'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20103'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20104'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20104'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20105'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20105'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20106'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20106'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20107'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20107'

2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20108'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20108'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20109'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20109'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20110'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20110'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20111'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20111'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20112'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20112'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20113'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20113'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20114'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20114'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20115'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20115'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '20116'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20116'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20117'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20117'
2022-05-08
UPDATE job_vacancies SET open =  '2022-05-08' where raw_id = '20118'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20118'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20119'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20119'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20120'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20120'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20121'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20121'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20122'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20122'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20123'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20123'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20124'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20124'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20125'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20125'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20126'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20126'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20127'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20127'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20128'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20128'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20129'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20129'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20130'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20130'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20131'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20131'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '20132'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20132'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20133'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20133'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '20134'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20134'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20135'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20135'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20136'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20136'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20137'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20137'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20138'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20138'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20139'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20139'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20140'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20140'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20141'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20141'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20142'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20142'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20143'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20143'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20144'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20144'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20145'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20145'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20146'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20146'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20147'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20147'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20148'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20148'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20149'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20149'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20150'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20150'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20151'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20151'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20152'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20152'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '20153'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20153'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20154'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20154'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20155'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20155'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20156'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20156'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20157'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20157'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20158'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20158'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20159'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20159'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20160'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20160'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20161'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20161'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '20162'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20162'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20163'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20163'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20164'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20164'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20165'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20165'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '20166'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20166'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20167'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20167'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20168'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20168'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20169'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20169'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20170'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20170'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20171'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20171'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20172'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20172'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20173'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20173'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20174'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20174'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20175'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20175'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20176'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20176'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '20177'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20177'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20178'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20178'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20179'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20179'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20180'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20180'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20181'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20181'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20182'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20182'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20183'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20183'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20184'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20184'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20185'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20185'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20186'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20186'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20187'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20187'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20188'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20188'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20189'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20189'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20190'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20190'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20191'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20191'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20192'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20192'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20193'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20193'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20194'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20194'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20195'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20195'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20196'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20196'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20197'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20197'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20198'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20198'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20199'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20199'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20200'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20200'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20201'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20201'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20202'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20202'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20203'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20203'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '20204'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20204'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20205'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20205'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20206'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20206'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20207'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20207'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20208'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20208'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20209'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20209'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '20210'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20210'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20211'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20211'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20212'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20212'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20213'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20213'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '20214'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20214'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20215'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20215'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20216'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20216'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20217'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20217'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20218'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20218'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20219'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20219'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20220'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20220'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20221'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20221'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20222'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20222'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20223'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20223'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '20224'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20224'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20225'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20225'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20226'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20226'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20227'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20227'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20228'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20228'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20229'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20229'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20230'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20230'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20231'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20231'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20232'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20232'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20233'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20233'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20234'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20234'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20235'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20235'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20236'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20236'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20237'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20237'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20238'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20238'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20239'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20239'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20240'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20240'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20241'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20241'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20242'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20242'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20243'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20243'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20244'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20244'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20245'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20245'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20246'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20246'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20247'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20247'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20248'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20248'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20249'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20249'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20250'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20250'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20251'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20251'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20252'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20252'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20253'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20253'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20254'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20254'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20255'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20255'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20256'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20256'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20257'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20257'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20258'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20258'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20259'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20259'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20260'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20260'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20261'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20261'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20262'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20262'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20263'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20263'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20264'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20264'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20265'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20265'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20266'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20266'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20267'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20267'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20268'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20268'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20269'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20269'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20270'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20270'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20271'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20271'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20272'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20272'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '20273'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20273'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20274'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20274'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20275'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20275'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '20276'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20276'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20277'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20277'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20278'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20278'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20279'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20279'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20280'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20280'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20281'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20281'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20282'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20282'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20283'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20283'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20284'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20284'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20285'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20285'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20286'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20286'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20287'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20287'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20288'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20288'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20289'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20289'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20290'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20290'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20291'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20291'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20292'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20292'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '20293'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20293'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20294'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20294'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20295'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20295'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20296'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20296'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20297'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20297'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20298'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20298'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20299'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20299'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20300'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20300'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20301'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20301'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20302'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20302'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20303'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20303'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20304'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20304'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20305'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20305'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20306'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20306'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20307'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20307'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20308'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20308'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20309'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20309'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20310'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20310'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20311'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20311'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20312'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20312'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20313'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20313'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20314'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20314'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20315'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20315'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20316'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20316'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '20317'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20317'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20318'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20318'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20319'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20319'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20320'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20320'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20321'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20321'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20322'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20322'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20323'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20323'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20324'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20324'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20325'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20325'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20326'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20326'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20327'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20327'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20328'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20328'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20329'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20329'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20330'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20330'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20331'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20331'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20332'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20332'

2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20333'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20333'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20334'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20334'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20335'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20335'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20336'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20336'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20337'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20337'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20338'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20338'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20339'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20339'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20340'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20340'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20341'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20341'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20342'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20342'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20343'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20343'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20344'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20344'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20345'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20345'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20346'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20346'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20347'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20347'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20348'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20348'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20349'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20349'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20350'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20350'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20351'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20351'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20352'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20352'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20353'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20353'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20354'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20354'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '20355'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20355'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20356'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20356'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20357'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20357'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20358'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20358'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20359'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20359'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20360'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20360'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20361'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20361'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20362'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20362'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20363'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20363'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20364'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20364'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20365'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20365'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20366'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20366'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20367'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20367'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20368'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20368'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20369'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20369'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '20370'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20370'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20371'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20371'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20372'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20372'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '20373'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20373'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20374'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20374'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20375'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20375'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20376'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20376'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20377'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20377'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20378'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20378'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20379'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20379'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20380'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20380'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20381'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20381'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20382'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20382'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20383'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20383'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20384'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20384'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20385'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20385'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20386'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20386'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20387'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20387'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20388'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20388'

2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20389'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20389'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20390'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20390'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20391'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20391'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20392'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20392'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20393'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20393'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20394'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20394'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20395'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20395'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20396'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20396'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20397'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20397'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20398'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20398'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20399'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20399'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20400'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20400'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20401'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20401'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20402'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20402'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20403'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20403'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20404'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20404'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20405'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20405'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20406'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20406'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20407'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20407'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20408'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20408'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20409'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20409'
2022-05-08
UPDATE job_vacancies SET open =  '2022-05-08' where raw_id = '20410'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20410'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20411'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20411'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20412'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20412'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20413'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20413'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20414'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20414'
2022-05-06
UPDATE job_vacancies SET open =  '2022-05-06' where raw_id = '20415'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20415'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20416'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20416'
2022-05-06
UPDATE job_vacancies SET open =  '2022-05-06' where raw_id = '20417'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20417'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20418'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20418'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20419'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20419'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20420'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20420'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20421'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20421'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20422'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20422'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20423'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20423'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20424'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20424'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20425'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20425'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20426'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20426'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20427'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20427'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20428'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20428'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20429'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20429'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20430'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20430'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20431'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20431'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20432'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20432'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20433'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20433'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20434'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20434'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20435'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20435'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20436'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20436'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20437'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20437'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20438'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20438'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20439'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20439'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20440'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20440'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20441'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20441'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20442'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20442'

2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20443'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20443'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20444'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20444'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20445'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20445'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20446'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20446'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20447'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20447'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20448'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20448'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20449'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20449'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20450'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20450'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20451'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20451'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20452'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20452'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20453'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20453'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20454'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20454'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20455'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20455'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20456'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20456'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20457'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20457'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20458'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20458'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20459'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20459'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20460'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20460'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20461'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20461'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20462'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20462'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20463'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20463'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20464'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20464'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20465'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20465'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20466'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20466'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20467'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20467'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20468'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20468'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20469'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20469'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20470'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20470'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20471'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20471'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20472'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20472'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20473'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20473'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20474'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20474'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20475'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20475'
2022-05-15
UPDATE job_vacancies SET open =  '2022-05-15' where raw_id = '20476'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20476'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20477'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20477'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20478'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20478'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20479'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20479'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20480'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20480'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20481'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20481'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20482'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20482'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20483'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20483'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20484'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20484'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20485'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20485'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '20486'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20486'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20487'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20487'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20488'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20488'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20489'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20489'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20490'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20490'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20491'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20491'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20492'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20492'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20493'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20493'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '20494'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20494'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20495'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20495'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20496'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20496'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20497'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20497'
2022-05-14
UPDATE job_vacancies SET open =  '2022-05-14' where raw_id = '20498'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20498'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20499'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20499'
2022-05-18
UPDATE job_vacancies SET open =  '2022-05-18' where raw_id = '20500'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20500'
2022-05-16
UPDATE job_vacancies SET open =  '2022-05-16' where raw_id = '20501'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20501'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20502'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20502'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20503'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20503'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20504'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20504'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20505'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20505'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20506'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20506'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20507'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20507'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20508'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20508'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20509'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20509'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20510'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20510'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20511'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20511'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20512'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20512'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '20513'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20513'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20514'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20514'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20515'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20515'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20516'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20516'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20517'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20517'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20518'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20518'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20519'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20519'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20520'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20520'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20521'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20521'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20522'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20522'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20523'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20523'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20524'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20524'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20525'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20525'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '20526'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20526'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20527'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20527'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20528'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20528'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20529'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20529'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20530'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20530'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20531'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20531'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20532'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20532'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20533'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20533'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20534'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20534'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20535'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20535'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20536'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20536'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20537'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20537'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20538'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20538'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20539'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20539'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20540'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20540'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20541'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20541'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20542'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20542'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20543'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20543'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '20544'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20544'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20545'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20545'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20546'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20546'
2022-05-06
UPDATE job_vacancies SET open =  '2022-05-06' where raw_id = '20547'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20547'
2022-05-13
UPDATE job_vacancies SET open =  '2022-05-13' where raw_id = '20548'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20548'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20549'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20549'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20550'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20550'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20551'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20551'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20552'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20552'

2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20553'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20553'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20554'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20554'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20555'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20555'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20556'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20556'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20557'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20557'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20558'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20558'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20559'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20559'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20560'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20560'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20561'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20561'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20562'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20562'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20563'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20563'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20564'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20564'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20565'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20565'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20566'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20566'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20567'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20567'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20568'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20568'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20569'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20569'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20570'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20570'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20571'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20571'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20572'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20572'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20573'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20573'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20574'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20574'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20575'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20575'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20576'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20576'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20577'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20577'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20578'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20578'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20579'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20579'
2022-05-17
UPDATE job_vacancies SET open =  '2022-05-17' where raw_id = '20580'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20580'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20581'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20581'
2022-05-12
UPDATE job_vacancies SET open =  '2022-05-12' where raw_id = '20582'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20582'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20583'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20583'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20584'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20584'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20585'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20585'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20586'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20586'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20587'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20587'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20588'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20588'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20589'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20589'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20590'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20590'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20591'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20591'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20592'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20592'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20593'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20593'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20594'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20594'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20595'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20595'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20596'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20596'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20597'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20597'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20598'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20598'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20599'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20599'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20600'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20600'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20601'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20601'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20602'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20602'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20603'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20603'
2022-05-11
UPDATE job_vacancies SET open =  '2022-05-11' where raw_id = '20604'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20604'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20605'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20605'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20606'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20606'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20607'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20607'
2022-05-10
UPDATE job_vacancies SET open =  '2022-05-10' where raw_id = '20608'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20608'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20609'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20609'
2022-05-06
UPDATE job_vacancies SET open =  '2022-05-06' where raw_id = '20610'
UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20610'
2022-05-09
UPDATE job_vacancies SET open =  '2022-05-09' where raw_id = '20611'

UPDATE jobstreet_raws_rc SET open = '--extracted--'     where id = '20611'
Done : 20611 row(s)