In [1]:
# Connect to DB

host="localhost"
user="root"

# host="192.168.100.3"
# user="rootx"

import mysql.connector
mydb = mysql.connector.connect(
    host=host,
    user=user,
    password="",
    database="pr_scraping_job_vacancy_indonesia_2022_04"
)
mycursor = mydb.cursor()
print('connect')

entity = 'placement'

# set query 1
select = ' id, created_at, ' + entity
fromdb = 'jobstreet_raws'
where = ' '
group = ' '

connect

In [2]:
# check distinct
group = ' Group By ' +  entity
 
# query 1
mycursor = mydb.cursor()
mycursor.execute("SELECT " + select + " FROM `" + fromdb + "` " + where + group  )
myresult = mycursor.fetchall()

print('We start and please wait ...')
# loop query 1
for x in myresult:  
    idx = str(x[0])
    created_at = x[1]  
    word = x[2] 
    
    
    print(word) 
    
#     queryx = "insert into career_levels (nama) values ('"+word+"')  "  
#     print(queryx)
#     mycursor.execute(queryx)
#     mydb.commit()    
    
print('done : ' + str(len(myresult)) + ' row(s)')

We start and please wait ...
Aceh
Ambon
Asahan Kisaran
Badung
Bali
Balikpapan
Bandar Lampung
Bandung
Bangka
Bangka Belitung
Banjar
Banjarbaru
Banjarmasin
Banjarnegara
Banten
Bantul
Banyuwangi
Barito Timur
Barito Utara
Batam
Bayan Lepas
Bekasi
Belitung
Bengkulu
Bima
Binjai
Bintan
Bitung
Blitar
Bogor
Bontang
Brebes
Bukittinggi
Bulungan
Buton
Cambodia
Cianjur
Cibinong
Cikarang
Cikupa
Cilacap
Cilegon
Cileungsi
Cimahi
Cirebon
Citeureup
Cyberjaya
Demak
Denpasar
Depok
Dumai
Ende
Flores Timur Larantuka
Gianyar
Gorontalo
Gowa
Gresik
Gunung Kidul
Halmahera
Hong Kong
Hulu Sungai Selatan
Hulu Sungai Tengah
Jakarta Barat
Jakarta Pusat
Jakarta Raya
Jakarta Selatan
Jakarta Timur
Jakarta Utara
Jambi
Jawa Barat
Jawa Tengah
Jawa Timur
Jayapura
Jember
Jepara
Kalimantan Barat
Kalimantan Selatan
Kalimantan Tengah
Kalimantan Timur
Kalimantan Utara
Karangasem
Karawang
Kediri
Kendari
Kepulauan Riau
Ketapang
Klaten
Klungkung
Kota Banda Aceh
Kotabaru
Kotawaringin Barat
Kotawaringin Timur
Kuala Lumpur
Kudus
Kulon Progo
Kupang
Kuta
Kutai Barat
Kutai Kartanegara
Kutai Timur
Lampung
Lhokseumawe
Lombok
Madiun
Madura
Magelang
Mahakam Ulu
Makassar
Makati City
Malang
Malinau
Maluku
Maluku Barat
Maluku Utara
Mamuju
Manado
Manila City
Manokwari
Maros
Mataram
Medan
Melawi
Merauke
Minahasa
Mojokerto
Muara Enim
National Capital Reg
Nunukan
Nusa Tenggara Barat
Nusa Tenggara Timur
Padang
Padang Sidempuan
Palangkaraya
Palembang
Palopo
Palu
Pandeglang
Pangkal Pinang
Papua
Papua Barat
Pare-Pare
Paser
Pasuruan
Pekalongan
Pekanbaru
Pemalang
Pematangsiantar
Penajam Paser Utara
Petaling Jaya
Pontianak
Poso
Prabumulih
Probolinggo
Purbalingga
Purwakarta
Purwokerto
Purworejo
Riau
Salatiga
Samarinda
Sambas
Semarang
Seminyak
Serang
Seruyan
Sibolga
Sidoarjo
Singkawang
Sintang
Sleman
Sorong
Sukabumi
Sulawesi Barat
Sulawesi Selatan
Sulawesi Tengah
Sulawesi Tenggara
Sulawesi Utara
Sumatera Barat
Sumatera Selatan
Sumatera Utara
Sumbawa
Surabaya
Surakarta
Tabalong
Taiwan
Tanah Laut
Tangerang
Tanjung Pinang
Tapanuli
Tapin
Tarakan
Tasikmalaya
Tegal
Ternate
Timika
Timor-Leste
Tuban
Ubud
Ungaran
Wonogiri
Yogyakarta
done : 201 row(s)