In [2]:
# Connect to DB

host="localhost"
user="root"

# host="192.168.100.3"
# user="rootx"

import mysql.connector
mydb = mysql.connector.connect(
    host=host,
    user=user,
    password="",
    database="pr_scraping_job_vacancy_indonesia_2022_04"
)
mycursor = mydb.cursor()
print('connect')

entity = 'gpa_min'

# set query 1
select = ' id, created_at, ' + entity
fromdb = 'jobstreet_raws'
where = ' '
group = ' ' 

# ALTER TABLE `job_vacancies` ADD `salary_type_id` INT NULL DEFAULT NULL AFTER `experience`;

connect

In [4]:
query = 'ALTER TABLE `job_vacancies` ADD `gpa_min` INT NULL DEFAULT NULL AFTER `career_level_id`;'
mycursor.execute(query)
mydb.commit()    
print('Done')

Done

In [ ]:
# insert new job_vacancies 

# set query 1
select = ' id, ' + entity
fromdb = 'jobstreet_raws_v2'
where = ' '
group = ' ' 
 
# query 1
mycursor = mydb.cursor()
mycursor.execute("SELECT " + select + " FROM `" + fromdb + "` " + where + group  )
myresult = mycursor.fetchall()
  
print('Start and Please Wait..')
# loop query 1
for x in myresult:  
    idx = str(x[0])
    word = x[1]  
    
#     words = ' id: ' + idx + ' // word: ' + word
    print(word)
    
    if(word is None):
        query3 = "UPDATE job_vacancies SET "+entity+" =  Null where raw_id = '" + idx + "'"
    else:
        query3 = "UPDATE job_vacancies SET "+entity+" =  '" + word + "' where raw_id = '" + idx + "'"
        
    print(query3)
    mycursor.execute(query3)
    mydb.commit()  

    query4 = "UPDATE jobstreet_raws_rc SET "+entity+" = '--extracted--'   " 
    where4 = "  where id = '" + idx + "'"  
    print(query4 + where4)
    mycursor.execute(query4 + where4)
    mydb.commit()  
         
print('Done : ' + str(len(myresult)) + ' row(s)')

Start and Please Wait..
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '4'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '4'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '5'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '5'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '6'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '6'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '7'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '7'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '8'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '8'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '9'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '9'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '10'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '10'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '11'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '11'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '12'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '12'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '13'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '13'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '14'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '14'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '15'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '15'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '16'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '16'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '17'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '17'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '18'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '18'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '19'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '19'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '20'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '20'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '21'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '21'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '22'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '22'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '23'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '23'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '24'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '24'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '25'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '25'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '26'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '26'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '27'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '27'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '28'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '28'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '29'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '29'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '30'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '30'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '31'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '31'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '32'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '32'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '33'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '33'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '34'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '34'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '35'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '35'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '36'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '36'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '37'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '37'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '38'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '38'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '39'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '39'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '40'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '40'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '41'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '41'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '42'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '42'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '43'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '43'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '44'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '44'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '45'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '45'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '46'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '46'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '47'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '47'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '48'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '48'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '49'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '49'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '50'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '50'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '51'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '51'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '52'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '52'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '53'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '53'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '54'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '54'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '55'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '55'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '56'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '56'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '57'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '57'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '58'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '58'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '59'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '59'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '60'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '60'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '61'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '61'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '62'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '62'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '63'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '63'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '64'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '64'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '65'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '65'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '66'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '66'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '67'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '67'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '68'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '68'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '69'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '69'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '70'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '70'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '71'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '71'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '72'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '72'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '73'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '73'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '74'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '74'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '75'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '75'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '76'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '76'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '77'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '77'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '78'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '78'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '79'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '79'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '80'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '80'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '81'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '81'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '82'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '82'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '83'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '83'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '84'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '84'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '85'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '85'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '86'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '86'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '87'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '87'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '88'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '88'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '89'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '89'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '90'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '90'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '91'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '91'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '92'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '92'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '93'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '93'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '94'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '94'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '95'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '95'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '96'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '96'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '97'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '97'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '98'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '98'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '99'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '99'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '100'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '100'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '101'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '101'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '102'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '102'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '103'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '103'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '104'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '104'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '105'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '105'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '106'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '106'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '107'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '107'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '108'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '108'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '109'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '109'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '110'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '110'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '111'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '111'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '112'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '112'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '113'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '113'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '114'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '114'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '115'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '115'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '116'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '116'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '117'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '117'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '118'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '118'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '119'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '119'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '120'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '120'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '121'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '121'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '122'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '122'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '123'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '123'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '124'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '124'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '125'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '125'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '126'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '126'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '127'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '127'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '128'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '128'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '129'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '129'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '130'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '130'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '131'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '131'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '132'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '132'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '133'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '133'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '134'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '134'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '135'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '135'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '136'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '136'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '137'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '137'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '138'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '138'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '139'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '139'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '140'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '140'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '141'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '141'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '142'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '142'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '143'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '143'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '144'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '144'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '145'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '145'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '146'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '146'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '147'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '147'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '148'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '148'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '149'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '149'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '150'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '150'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '151'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '151'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '152'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '152'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '153'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '153'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '154'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '154'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '155'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '155'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '156'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '156'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '157'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '157'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '158'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '158'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '159'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '159'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '160'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '160'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '161'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '161'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '162'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '162'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '163'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '163'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '164'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '164'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '165'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '165'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '166'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '166'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '167'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '167'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '168'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '168'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '169'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '169'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '170'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '170'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '171'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '171'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '172'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '172'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '173'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '173'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '174'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '174'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '175'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '175'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '176'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '176'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '177'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '177'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '178'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '178'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '179'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '179'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '180'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '180'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '181'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '181'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '182'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '182'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '183'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '183'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '184'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '184'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '185'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '185'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '186'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '186'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '187'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '187'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '188'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '188'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '189'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '189'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '190'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '190'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '191'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '191'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '192'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '192'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '193'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '193'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '194'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '194'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '195'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '195'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '196'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '196'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '197'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '197'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '198'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '198'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '199'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '199'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '200'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '200'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '201'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '201'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '202'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '202'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '203'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '203'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '204'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '204'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '205'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '205'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '206'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '206'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '207'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '207'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '208'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '208'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '209'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '209'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '210'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '210'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '211'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '211'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '212'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '212'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '213'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '213'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '214'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '214'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '215'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '215'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '216'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '216'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '217'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '217'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '218'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '218'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '219'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '219'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '220'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '220'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '221'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '221'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '222'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '222'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '223'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '223'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '224'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '224'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '225'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '225'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '226'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '226'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '227'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '227'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '228'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '228'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '229'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '229'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '230'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '230'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '231'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '231'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '232'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '232'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '233'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '233'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '234'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '234'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '235'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '235'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '236'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '236'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '237'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '237'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '238'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '238'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '239'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '239'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '240'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '240'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '241'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '241'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '242'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '242'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '243'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '243'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '244'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '244'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '245'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '245'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '246'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '246'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '247'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '247'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '248'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '248'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '249'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '249'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '250'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '250'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '251'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '251'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '252'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '252'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '253'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '253'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '254'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '254'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '255'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '255'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '256'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '256'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '257'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '257'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '258'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '258'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '259'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '259'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '260'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '260'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '261'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '261'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '262'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '262'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '263'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '263'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '264'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '264'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '265'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '265'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '266'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '266'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '267'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '267'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '268'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '268'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '269'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '269'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '270'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '270'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '271'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '271'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '272'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '272'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '273'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '273'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '274'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '274'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '275'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '275'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '276'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '276'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '277'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '277'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '278'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '278'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '279'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '279'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '280'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '280'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '281'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '281'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '282'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '282'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '283'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '283'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '284'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '284'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '285'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '285'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '286'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '286'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '287'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '287'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '288'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '288'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '289'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '289'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '290'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '290'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '291'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '291'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '292'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '292'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '293'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '293'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '294'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '294'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '295'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '295'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '296'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '296'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '297'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '297'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '298'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '298'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '299'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '299'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '300'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '300'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '301'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '301'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '302'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '302'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '303'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '303'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '304'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '304'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '305'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '305'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '306'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '306'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '307'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '307'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '308'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '308'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '309'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '309'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '310'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '310'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '311'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '311'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '312'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '312'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '313'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '313'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '314'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '314'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '315'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '315'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '316'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '316'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '317'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '317'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '318'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '318'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '319'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '319'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '320'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '320'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '321'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '321'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '322'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '322'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '323'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '323'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '324'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '324'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '325'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '325'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '326'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '326'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '327'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '327'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '328'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '328'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '329'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '329'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '330'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '330'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '331'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '331'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '332'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '332'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '333'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '333'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '334'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '334'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '335'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '335'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '336'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '336'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '337'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '337'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '338'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '338'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '339'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '339'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '340'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '340'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '341'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '341'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '342'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '342'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '343'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '343'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '344'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '344'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '345'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '345'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '346'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '346'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '347'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '347'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '348'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '348'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '349'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '349'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '350'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '350'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '351'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '351'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '352'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '352'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '353'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '353'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '354'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '354'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '355'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '355'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '356'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '356'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '357'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '357'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '358'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '358'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '359'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '359'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '360'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '360'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '361'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '361'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '362'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '362'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '363'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '363'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '364'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '364'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '365'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '365'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '366'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '366'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '367'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '367'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '368'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '368'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '369'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '369'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '370'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '370'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '371'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '371'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '372'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '372'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '373'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '373'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '374'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '374'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '375'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '375'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '376'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '376'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '377'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '377'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '378'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '378'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '379'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '379'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '380'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '380'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '381'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '381'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '382'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '382'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '383'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '383'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '384'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '384'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '385'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '385'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '386'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '386'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '387'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '387'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '388'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '388'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '389'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '389'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '390'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '390'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '391'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '391'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '392'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '392'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '393'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '393'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '394'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '394'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '395'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '395'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '396'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '396'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '397'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '397'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '398'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '398'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '399'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '399'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '400'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '400'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '401'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '401'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '402'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '402'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '403'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '403'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '404'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '404'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '405'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '405'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '406'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '406'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '407'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '407'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '408'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '408'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '409'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '409'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '410'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '410'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '411'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '411'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '412'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '412'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '413'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '413'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '414'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '414'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '415'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '415'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '416'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '416'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '417'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '417'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '418'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '418'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '419'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '419'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '420'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '420'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '421'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '421'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '422'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '422'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '423'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '423'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '424'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '424'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '425'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '425'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '426'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '426'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '427'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '427'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '428'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '428'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '429'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '429'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '430'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '430'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '431'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '431'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '432'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '432'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '433'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '433'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '434'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '434'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '435'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '435'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '436'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '436'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '437'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '437'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '438'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '438'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '439'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '439'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '440'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '440'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '441'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '441'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '442'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '442'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '443'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '443'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '444'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '444'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '445'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '445'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '446'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '446'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '447'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '447'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '448'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '448'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '449'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '449'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '450'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '450'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '451'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '451'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '452'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '452'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '453'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '453'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '454'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '454'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '455'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '455'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '456'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '456'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '457'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '457'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '458'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '458'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '459'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '459'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '460'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '460'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '461'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '461'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '462'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '462'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '463'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '463'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '464'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '464'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '465'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '465'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '466'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '466'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '467'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '467'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '468'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '468'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '469'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '469'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '470'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '470'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '471'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '471'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '472'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '472'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '473'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '473'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '474'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '474'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '475'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '475'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '476'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '476'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '477'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '477'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '478'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '478'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '479'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '479'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '480'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '480'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '481'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '481'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '482'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '482'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '483'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '483'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '484'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '484'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '485'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '485'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '486'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '486'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '487'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '487'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '488'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '488'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '489'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '489'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '490'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '490'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '491'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '491'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '492'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '492'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '493'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '493'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '494'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '494'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '495'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '495'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '496'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '496'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '497'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '497'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '498'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '498'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '499'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '499'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '500'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '500'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '501'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '501'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '502'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '502'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '503'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '503'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '504'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '504'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '505'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '505'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '506'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '506'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '507'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '507'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '508'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '508'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '509'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '509'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '510'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '510'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '511'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '511'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '512'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '512'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '513'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '513'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '514'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '514'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '515'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '515'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '516'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '516'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '517'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '517'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '518'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '518'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '519'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '519'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '520'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '520'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '521'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '521'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '522'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '522'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '523'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '523'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '524'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '524'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '525'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '525'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '526'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '526'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '527'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '527'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '528'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '528'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '529'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '529'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '530'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '530'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '531'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '531'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '532'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '532'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '533'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '533'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '534'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '534'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '535'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '535'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '536'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '536'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '537'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '537'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '538'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '538'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '539'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '539'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '540'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '540'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '541'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '541'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '542'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '542'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '543'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '543'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '544'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '544'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '545'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '545'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '546'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '546'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '547'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '547'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '548'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '548'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '549'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '549'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '550'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '550'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '551'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '551'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '552'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '552'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '553'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '553'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '554'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '554'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '555'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '555'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '556'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '556'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '557'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '557'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '558'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '558'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '559'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '559'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '560'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '560'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '561'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '561'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '562'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '562'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '563'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '563'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '564'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '564'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '565'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '565'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '566'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '566'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '567'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '567'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '568'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '568'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '569'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '569'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '570'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '570'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '571'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '571'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '572'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '572'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '573'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '573'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '574'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '574'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '575'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '575'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '576'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '576'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '577'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '577'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '578'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '578'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '579'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '579'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '580'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '580'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '581'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '581'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '582'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '582'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '583'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '583'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '584'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '584'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '585'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '585'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '586'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '586'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '587'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '587'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '588'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '588'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '589'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '589'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '590'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '590'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '591'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '591'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '592'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '592'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '593'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '593'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '594'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '594'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '595'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '595'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '596'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '596'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '597'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '597'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '598'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '598'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '599'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '599'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '600'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '600'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '601'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '601'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '602'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '602'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '603'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '603'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '604'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '604'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '605'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '605'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '606'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '606'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '607'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '607'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '608'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '608'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '609'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '609'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '610'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '610'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '611'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '611'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '612'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '612'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '613'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '613'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '614'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '614'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '615'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '615'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '616'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '616'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '617'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '617'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '618'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '618'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '619'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '619'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '620'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '620'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '621'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '621'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '622'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '622'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '623'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '623'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '624'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '624'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '625'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '625'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '626'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '626'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '627'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '627'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '628'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '628'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '629'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '629'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '630'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '630'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '631'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '631'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '632'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '632'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '633'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '633'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '634'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '634'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '635'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '635'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '636'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '636'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '637'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '637'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '638'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '638'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '639'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '639'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '640'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '640'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '641'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '641'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '642'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '642'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '643'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '643'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '644'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '644'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '645'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '645'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '646'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '646'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '647'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '647'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '648'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '648'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '649'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '649'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '650'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '650'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '651'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '651'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '652'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '652'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '653'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '653'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '654'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '654'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '655'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '655'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '656'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '656'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '657'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '657'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '658'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '658'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '659'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '659'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '660'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '660'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '661'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '661'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '662'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '662'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '663'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '663'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '664'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '664'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '665'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '665'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '666'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '666'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '667'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '667'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '668'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '668'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '669'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '669'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '670'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '670'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '671'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '671'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '672'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '672'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '673'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '673'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '674'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '674'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '675'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '675'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '676'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '676'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '677'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '677'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '678'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '678'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '679'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '679'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '680'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '680'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '681'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '681'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '682'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '682'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '683'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '683'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '684'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '684'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '685'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '685'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '686'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '686'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '687'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '687'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '688'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '688'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '689'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '689'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '690'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '690'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '691'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '691'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '692'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '692'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '693'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '693'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '694'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '694'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '695'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '695'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '696'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '696'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '697'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '697'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '698'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '698'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '699'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '699'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '700'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '700'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '701'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '701'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '702'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '702'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '703'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '703'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '704'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '704'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '705'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '705'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '706'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '706'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '707'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '707'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '708'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '708'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '709'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '709'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '710'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '710'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '711'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '711'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '712'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '712'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '713'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '713'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '714'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '714'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '715'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '715'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '716'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '716'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '717'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '717'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '718'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '718'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '719'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '719'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '720'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '720'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '721'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '721'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '722'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '722'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '723'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '723'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '724'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '724'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '725'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '725'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '726'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '726'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '727'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '727'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '728'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '728'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '729'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '729'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '730'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '730'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '731'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '731'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '732'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '732'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '733'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '733'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '734'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '734'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '735'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '735'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '736'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '736'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '737'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '737'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '738'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '738'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '739'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '739'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '740'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '740'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '741'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '741'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '742'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '742'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '743'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '743'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '744'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '744'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '745'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '745'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '746'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '746'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '747'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '747'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '748'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '748'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '749'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '749'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '750'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '750'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '751'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '751'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '752'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '752'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '753'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '753'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '754'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '754'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '755'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '755'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '756'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '756'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '757'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '757'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '758'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '758'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '759'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '759'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '760'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '760'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '761'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '761'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '762'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '762'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '763'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '763'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '764'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '764'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '765'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '765'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '766'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '766'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '767'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '767'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '768'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '768'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '769'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '769'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '770'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '770'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '771'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '771'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '772'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '772'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '773'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '773'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '774'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '774'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '775'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '775'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '776'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '776'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '777'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '777'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '778'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '778'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '779'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '779'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '780'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '780'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '781'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '781'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '782'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '782'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '783'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '783'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '784'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '784'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '785'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '785'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '786'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '786'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '787'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '787'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '788'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '788'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '789'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '789'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '790'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '790'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '791'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '791'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '792'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '792'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '793'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '793'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '794'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '794'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '795'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '795'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '796'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '796'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '797'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '797'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '798'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '798'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '799'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '799'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '800'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '800'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '801'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '801'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '802'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '802'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '803'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '803'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '804'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '804'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '805'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '805'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '806'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '806'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '807'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '807'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '808'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '808'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '809'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '809'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '810'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '810'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '811'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '811'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '812'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '812'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '813'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '813'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '814'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '814'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '815'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '815'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '816'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '816'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '817'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '817'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '818'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '818'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '819'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '819'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '820'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '820'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '821'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '821'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '822'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '822'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '823'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '823'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '824'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '824'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '825'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '825'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '826'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '826'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '827'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '827'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '828'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '828'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '829'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '829'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '830'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '830'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '831'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '831'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '832'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '832'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '833'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '833'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '834'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '834'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '835'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '835'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '836'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '836'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '837'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '837'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '838'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '838'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '839'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '839'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '840'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '840'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '841'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '841'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '842'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '842'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '843'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '843'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '844'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '844'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '845'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '845'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '846'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '846'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '847'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '847'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '848'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '848'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '849'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '849'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '850'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '850'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '851'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '851'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '852'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '852'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '853'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '853'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '854'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '854'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '855'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '855'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '856'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '856'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '857'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '857'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '858'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '858'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '859'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '859'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '860'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '860'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '861'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '861'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '862'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '862'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '863'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '863'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '864'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '864'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '865'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '865'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '866'

UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '866'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '867'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '867'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '868'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '868'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '869'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '869'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '870'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '870'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '871'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '871'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '872'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '872'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '873'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '873'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '874'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '874'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '875'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '875'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '876'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '876'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '877'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '877'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '878'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '878'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '879'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '879'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '880'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '880'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '881'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '881'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '882'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '882'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '883'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '883'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '884'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '884'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '885'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '885'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '886'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '886'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '887'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '887'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '888'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '888'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '889'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '889'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '890'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '890'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '891'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '891'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '892'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '892'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '893'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '893'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '894'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '894'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '895'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '895'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '896'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '896'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '897'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '897'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '898'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '898'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '899'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '899'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '900'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '900'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '901'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '901'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '902'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '902'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '903'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '903'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '904'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '904'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '905'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '905'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '906'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '906'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '907'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '907'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '908'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '908'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '909'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '909'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '910'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '910'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '911'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '911'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '912'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '912'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '913'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '913'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '914'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '914'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '915'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '915'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '916'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '916'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '917'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '917'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '918'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '918'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '919'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '919'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '920'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '920'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '921'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '921'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '922'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '922'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '923'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '923'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '924'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '924'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '925'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '925'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '926'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '926'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '927'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '927'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '928'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '928'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '929'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '929'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '930'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '930'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '931'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '931'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '932'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '932'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '933'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '933'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '934'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '934'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '935'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '935'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '936'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '936'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '937'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '937'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '938'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '938'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '939'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '939'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '940'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '940'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '941'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '941'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '942'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '942'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '943'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '943'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '944'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '944'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '945'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '945'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '946'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '946'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '947'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '947'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '948'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '948'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '949'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '949'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '950'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '950'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '951'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '951'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '952'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '952'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '953'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '953'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '954'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '954'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '955'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '955'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '956'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '956'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '957'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '957'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '958'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '958'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '959'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '959'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '960'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '960'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '961'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '961'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '962'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '962'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '963'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '963'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '964'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '964'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '965'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '965'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '966'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '966'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '967'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '967'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '968'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '968'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '969'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '969'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '970'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '970'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '971'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '971'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '972'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '972'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '973'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '973'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '974'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '974'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '975'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '975'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '976'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '976'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '977'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '977'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '978'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '978'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '979'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '979'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '980'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '980'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '981'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '981'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '982'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '982'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '983'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '983'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '984'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '984'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '985'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '985'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '986'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '986'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '987'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '987'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '988'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '988'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '989'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '989'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '990'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '990'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '991'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '991'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '992'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '992'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '993'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '993'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '994'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '994'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '995'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '995'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '996'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '996'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '997'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '997'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '998'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '998'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '999'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '999'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1000'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1000'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1001'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1001'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1002'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1002'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1003'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1003'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1004'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1004'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1005'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1005'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1006'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1006'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1007'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1007'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1008'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1008'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1009'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1009'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1010'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1010'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1011'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1011'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1012'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1012'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1013'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1013'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1014'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1014'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1015'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1015'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1016'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1016'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1017'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1017'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1018'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1018'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1019'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1019'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1020'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1020'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1021'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1021'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1022'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1022'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1023'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1023'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1024'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1024'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1025'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1025'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1026'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1026'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1027'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1027'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1028'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1028'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1029'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1029'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1030'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1030'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1031'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1031'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1032'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1032'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1033'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1033'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1034'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1034'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1035'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1035'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1036'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1036'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1037'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1037'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1038'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1038'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1039'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1039'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1040'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1040'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1041'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1041'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1042'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1042'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1043'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1043'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1044'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1044'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1045'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1045'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1046'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1046'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1047'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1047'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1048'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1048'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1049'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1049'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1050'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1050'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1051'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1051'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1052'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1052'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1053'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1053'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1054'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1054'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1055'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1055'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1056'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1056'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1057'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1057'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1058'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1058'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1059'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1059'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1060'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1060'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1061'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1061'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1062'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1062'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1063'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1063'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1064'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1064'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1065'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1065'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1066'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1066'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1067'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1067'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1068'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1068'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1069'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1069'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1070'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1070'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1071'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1071'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1072'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1072'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1073'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1073'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1074'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1074'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1075'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1075'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1076'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1076'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1077'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1077'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1078'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1078'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1079'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1079'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1080'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1080'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1081'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1081'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1082'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1082'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1083'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1083'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1084'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1084'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1085'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1085'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1086'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1086'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1087'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1087'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1088'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1088'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1089'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1089'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1090'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1090'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1091'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1091'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1092'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1092'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1093'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1093'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1094'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1094'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1095'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1095'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1096'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1096'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1097'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1097'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1098'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1098'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1099'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1099'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1100'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1100'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1101'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1101'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1102'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1102'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1103'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1103'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1104'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1104'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1105'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1105'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1106'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1106'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1107'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1107'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1108'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1108'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1109'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1109'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1110'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1110'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1111'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1111'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1112'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1112'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1113'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1113'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1114'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1114'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1115'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1115'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1116'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1116'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1117'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1117'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1118'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1118'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1119'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1119'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1120'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1120'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1121'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1121'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1122'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1122'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1123'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1123'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1124'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1124'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1125'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1125'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1126'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1126'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1127'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1127'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1128'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1128'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1129'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1129'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1130'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1130'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1131'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1131'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1132'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1132'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1133'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1133'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1134'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1134'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1135'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1135'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1136'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1136'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1137'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1137'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1138'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1138'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1139'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1139'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1140'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1140'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1141'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1141'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1142'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1142'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1143'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1143'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1144'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1144'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1145'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1145'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1146'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1146'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1147'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1147'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1148'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1148'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1149'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1149'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1150'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1150'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1151'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1151'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1152'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1152'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1153'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1153'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1154'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1154'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1155'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1155'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1156'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1156'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1157'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1157'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1158'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1158'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1159'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1159'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1160'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1160'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1161'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1161'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1162'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1162'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1163'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1163'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1164'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1164'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1165'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1165'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1166'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1166'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1167'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1167'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1168'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1168'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1169'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1169'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1170'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1170'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1171'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1171'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1172'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1172'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1173'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1173'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1174'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1174'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1175'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1175'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1176'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1176'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1177'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1177'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1178'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1178'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1179'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1179'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1180'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1180'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1181'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1181'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1182'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1182'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1183'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1183'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1184'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1184'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1185'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1185'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1186'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1186'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1187'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1187'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1188'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1188'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1189'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1189'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1190'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1190'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1191'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1191'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1192'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1192'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1193'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1193'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1194'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1194'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1195'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1195'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1196'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1196'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1197'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1197'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1198'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1198'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1199'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1199'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1200'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1200'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1201'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1201'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1202'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1202'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1203'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1203'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1204'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1204'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1205'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1205'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1206'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1206'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1207'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1207'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1208'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1208'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1209'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1209'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1210'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1210'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1211'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1211'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1212'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1212'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1213'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1213'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1214'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1214'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1215'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1215'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1216'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1216'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1217'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1217'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1218'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1218'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1219'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1219'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1220'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1220'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1221'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1221'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1222'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1222'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1223'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1223'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1224'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1224'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1225'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1225'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1226'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1226'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1227'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1227'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1228'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1228'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1229'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1229'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1230'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1230'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1231'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1231'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1232'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1232'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1233'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1233'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1234'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1234'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1235'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1235'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1236'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1236'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1237'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1237'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1238'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1238'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1239'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1239'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1240'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1240'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1241'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1241'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1242'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1242'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1243'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1243'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1244'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1244'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1245'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1245'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1246'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1246'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1247'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1247'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1248'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1248'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1249'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1249'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1250'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1250'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1251'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1251'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1252'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1252'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1253'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1253'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1254'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1254'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1255'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1255'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1256'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1256'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1257'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1257'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1258'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1258'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1259'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1259'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1260'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1260'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1261'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1261'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1262'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1262'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1263'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1263'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1264'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1264'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1265'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1265'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1266'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1266'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1267'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1267'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1268'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1268'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1269'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1269'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1270'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1270'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1271'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1271'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1272'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1272'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1273'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1273'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1274'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1274'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1275'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1275'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1276'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1276'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1277'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1277'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1278'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1278'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1279'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1279'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1280'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1280'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1281'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1281'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1282'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1282'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1283'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1283'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1284'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1284'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1285'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1285'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1286'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1286'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1287'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1287'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1288'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1288'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1289'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1289'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1290'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1290'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1291'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1291'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1292'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1292'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1293'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1293'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1294'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1294'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1295'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1295'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1296'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1296'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1297'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1297'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1298'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1298'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1299'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1299'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1300'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1300'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1301'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1301'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1302'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1302'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1303'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1303'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1304'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1304'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1305'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1305'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1306'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1306'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1307'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1307'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1308'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1308'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1309'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1309'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1310'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1310'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1311'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1311'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1312'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1312'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1313'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1313'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1314'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1314'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1315'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1315'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1316'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1316'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1317'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1317'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1318'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1318'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1319'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1319'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1320'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1320'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1321'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1321'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1322'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1322'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1323'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1323'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1324'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1324'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1325'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1325'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1326'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1326'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1327'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1327'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1328'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1328'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1329'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1329'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1330'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1330'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1331'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1331'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1332'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1332'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1333'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1333'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1334'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1334'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1335'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1335'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1336'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1336'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1337'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1337'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1338'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1338'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1339'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1339'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1340'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1340'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1341'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1341'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1342'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1342'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1343'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1343'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1344'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1344'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1345'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1345'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1346'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1346'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1347'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1347'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1348'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1348'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1349'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1349'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1350'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1350'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1351'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1351'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1352'

UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1352'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1353'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1353'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1354'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1354'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1355'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1355'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1356'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1356'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1357'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1357'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1358'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1358'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1359'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1359'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1360'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1360'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1361'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1361'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1362'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1362'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1363'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1363'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1364'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1364'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1365'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1365'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1366'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1366'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1367'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1367'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1368'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1368'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1369'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1369'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1370'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1370'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1371'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1371'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1372'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1372'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1373'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1373'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1374'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1374'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1375'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1375'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1376'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1376'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1377'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1377'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1378'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1378'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1379'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1379'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1380'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1380'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1381'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1381'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1382'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1382'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1383'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1383'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1384'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1384'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1385'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1385'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1386'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1386'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1387'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1387'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1388'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1388'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1389'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1389'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1390'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1390'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1391'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1391'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1392'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1392'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1393'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1393'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1394'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1394'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1395'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1395'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1396'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1396'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1397'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1397'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1398'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1398'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1399'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1399'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1400'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1400'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1401'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1401'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1402'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1402'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1403'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1403'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1404'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1404'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1405'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1405'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1406'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1406'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1407'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1407'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1408'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1408'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1409'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1409'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1410'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1410'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1411'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1411'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1412'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1412'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1413'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1413'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1414'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1414'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1415'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1415'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1416'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1416'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1417'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1417'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1418'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1418'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1419'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1419'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1420'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1420'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1421'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1421'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1422'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1422'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1423'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1423'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1424'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1424'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1425'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1425'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1426'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1426'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1427'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1427'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1428'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1428'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1429'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1429'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1430'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1430'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1431'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1431'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1432'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1432'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1433'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1433'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1434'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1434'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1435'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1435'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1436'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1436'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1437'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1437'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1438'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1438'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1439'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1439'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1440'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1440'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1441'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1441'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1442'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1442'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1443'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1443'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1444'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1444'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1445'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1445'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1446'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1446'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1447'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1447'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1448'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1448'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1449'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1449'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1450'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1450'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1451'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1451'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1452'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1452'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1453'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1453'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1454'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1454'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1455'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1455'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1456'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1456'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1457'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1457'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1458'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1458'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1459'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1459'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1460'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1460'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1461'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1461'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1462'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1462'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1463'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1463'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1464'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1464'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1465'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1465'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1466'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1466'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1467'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1467'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1468'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1468'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1469'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1469'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1470'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1470'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1471'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1471'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1472'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1472'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1473'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1473'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1474'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1474'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1475'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1475'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1476'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1476'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1477'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1477'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1478'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1478'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1479'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1479'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1480'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1480'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1481'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1481'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1482'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1482'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1483'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1483'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1484'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1484'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1485'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1485'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1486'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1486'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1487'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1487'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1488'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1488'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1489'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1489'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1490'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1490'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1491'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1491'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1492'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1492'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1493'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1493'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1494'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1494'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1495'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1495'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1496'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1496'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1497'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1497'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1498'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1498'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1499'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1499'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1500'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1500'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1501'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1501'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1502'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1502'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1503'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1503'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1504'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1504'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1505'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1505'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1506'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1506'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1507'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1507'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1508'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1508'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1509'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1509'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1510'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1510'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1511'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1511'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1512'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1512'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1513'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1513'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1514'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1514'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1515'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1515'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1516'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1516'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1517'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1517'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1518'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1518'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1519'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1519'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1520'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1520'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1521'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1521'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1522'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1522'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1523'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1523'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1524'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1524'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1525'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1525'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1526'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1526'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1527'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1527'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1528'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1528'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1529'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1529'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1530'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1530'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1531'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1531'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1532'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1532'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1533'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1533'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1534'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1534'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1535'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1535'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1536'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1536'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1537'

UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1537'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1538'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1538'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1539'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1539'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1540'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1540'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1541'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1541'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1542'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1542'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1543'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1543'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1544'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1544'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1545'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1545'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1546'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1546'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1547'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1547'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1548'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1548'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1549'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1549'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1550'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1550'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1551'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1551'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1552'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1552'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1553'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1553'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1554'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1554'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1555'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1555'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1556'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1556'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1557'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1557'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1558'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1558'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1559'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1559'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1560'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1560'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1561'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1561'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1562'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1562'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1563'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1563'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1564'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1564'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1565'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1565'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1566'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1566'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1567'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1567'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1568'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1568'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1569'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1569'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1570'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1570'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1571'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1571'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1572'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1572'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1573'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1573'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1574'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1574'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1575'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1575'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1576'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1576'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1577'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1577'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1578'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1578'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1579'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1579'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1580'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1580'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1581'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1581'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1582'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1582'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1583'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1583'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1584'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1584'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1585'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1585'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1586'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1586'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1587'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1587'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1588'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1588'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1589'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1589'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1590'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1590'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1591'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1591'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1592'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1592'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1593'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1593'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1594'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1594'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1595'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1595'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1596'

UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1596'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1597'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1597'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1598'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1598'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1599'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1599'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1600'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1600'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1601'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1601'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1602'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1602'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1603'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1603'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1604'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1604'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1605'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1605'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1606'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1606'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1607'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1607'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1608'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1608'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1609'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1609'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1610'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1610'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1611'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1611'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1612'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1612'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1613'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1613'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1614'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1614'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1615'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1615'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1616'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1616'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1617'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1617'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1618'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1618'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1619'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1619'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1620'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1620'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1621'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1621'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1622'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1622'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1623'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1623'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1624'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1624'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1625'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1625'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1626'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1626'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1627'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1627'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1628'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1628'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1629'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1629'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1630'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1630'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1631'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1631'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1632'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1632'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1633'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1633'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1634'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1634'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1635'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1635'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1636'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1636'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1637'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1637'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1638'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1638'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1639'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1639'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1640'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1640'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1641'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1641'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1642'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1642'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1643'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1643'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1644'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1644'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1645'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1645'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1646'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1646'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1647'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1647'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1648'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1648'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1649'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1649'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1650'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1650'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1651'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1651'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1652'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1652'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1653'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1653'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1654'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1654'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1655'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1655'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1656'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1656'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1657'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1657'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1658'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1658'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1659'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1659'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1660'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1660'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1661'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1661'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1662'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1662'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1663'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1663'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1664'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1664'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1665'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1665'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1666'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1666'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1667'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1667'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1668'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1668'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1669'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1669'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1670'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1670'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1671'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1671'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1672'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1672'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1673'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1673'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1674'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1674'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1675'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1675'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1676'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1676'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1677'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1677'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1678'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1678'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1679'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1679'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1680'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1680'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1681'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1681'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1682'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1682'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1683'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1683'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1684'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1684'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1685'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1685'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1686'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1686'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1687'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1687'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1688'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1688'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1689'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1689'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1690'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1690'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1691'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1691'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1692'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1692'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1693'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1693'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1694'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1694'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1695'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1695'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1696'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1696'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1697'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1697'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1698'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1698'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1699'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1699'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1700'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1700'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1701'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1701'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1702'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1702'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1703'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1703'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1704'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1704'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1705'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1705'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1706'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1706'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1707'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1707'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1708'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1708'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1709'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1709'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1710'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1710'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1711'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1711'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1712'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1712'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1713'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1713'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1714'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1714'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1715'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1715'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1716'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1716'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1717'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1717'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1718'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1718'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1719'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1719'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1720'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1720'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1721'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1721'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1722'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1722'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1723'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1723'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1724'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1724'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1725'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1725'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1726'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1726'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1727'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1727'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1728'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1728'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1729'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1729'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1730'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1730'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1731'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1731'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1732'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1732'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1733'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1733'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1734'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1734'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1735'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1735'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1736'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1736'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1737'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1737'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1738'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1738'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1739'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1739'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1740'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1740'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1741'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1741'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1742'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1742'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1743'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1743'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1744'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1744'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1745'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1745'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1746'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1746'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1747'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1747'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1748'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1748'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1749'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1749'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1750'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1750'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1751'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1751'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1752'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1752'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1753'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1753'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1754'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1754'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1755'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1755'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1756'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1756'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1757'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1757'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1758'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1758'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1759'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1759'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1760'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1760'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1761'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1761'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1762'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1762'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1763'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1763'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1764'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1764'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1765'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1765'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1766'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1766'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1767'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1767'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1768'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1768'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1769'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1769'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1770'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1770'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1771'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1771'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1772'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1772'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1773'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1773'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1774'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1774'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1775'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1775'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1776'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1776'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1777'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1777'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1778'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1778'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1779'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1779'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1780'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1780'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1781'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1781'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1782'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1782'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1783'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1783'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1784'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1784'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1785'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1785'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1786'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1786'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1787'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1787'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1788'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1788'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1789'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1789'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1790'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1790'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1791'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1791'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1792'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1792'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1793'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1793'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1794'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1794'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1795'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1795'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1796'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1796'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1797'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1797'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1798'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1798'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1799'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1799'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1800'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1800'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1801'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1801'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1802'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1802'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1803'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1803'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1804'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1804'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1805'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1805'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1806'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1806'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1807'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1807'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1808'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1808'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1809'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1809'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1810'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1810'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1811'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1811'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1812'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1812'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1813'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1813'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1814'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1814'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1815'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1815'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1816'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1816'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1817'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1817'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1818'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1818'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1819'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1819'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1820'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1820'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1821'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1821'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1822'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1822'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1823'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1823'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1824'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1824'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1825'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1825'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1826'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1826'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1827'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1827'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1828'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1828'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1829'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1829'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1830'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1830'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1831'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1831'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1832'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1832'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1833'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1833'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1834'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1834'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1835'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1835'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1836'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1836'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1837'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1837'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1838'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1838'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1839'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1839'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1840'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1840'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1841'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1841'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1842'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1842'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1843'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1843'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1844'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1844'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1845'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1845'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1846'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1846'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1847'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1847'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1848'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1848'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1849'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1849'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1850'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1850'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1851'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1851'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1852'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1852'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1853'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1853'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1854'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1854'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1855'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1855'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1856'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1856'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1857'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1857'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1858'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1858'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1859'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1859'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1860'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1860'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1861'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1861'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1862'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1862'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1863'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1863'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1864'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1864'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1865'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1865'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1866'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1866'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1867'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1867'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1868'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1868'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1869'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1869'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1870'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1870'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1871'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1871'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1872'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1872'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1873'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1873'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1874'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1874'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1875'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1875'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1876'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1876'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1877'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1877'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1878'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1878'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1879'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1879'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1880'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1880'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1881'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1881'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1882'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1882'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1883'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1883'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1884'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1884'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1885'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1885'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1886'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1886'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1887'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1887'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1888'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1888'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1889'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1889'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1890'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1890'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1891'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1891'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1892'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1892'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1893'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1893'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1894'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1894'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1895'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1895'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1896'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1896'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1897'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1897'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1898'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1898'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1899'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1899'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1900'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1900'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1901'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1901'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1902'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1902'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1903'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1903'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1904'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1904'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1905'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1905'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1906'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1906'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1907'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1907'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1908'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1908'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1909'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1909'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1910'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1910'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1911'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1911'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1912'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1912'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1913'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1913'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1914'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1914'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1915'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1915'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1916'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1916'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1917'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1917'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1918'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1918'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1919'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1919'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1920'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1920'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1921'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1921'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1922'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1922'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1923'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1923'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1924'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1924'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1925'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1925'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1926'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1926'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1927'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1927'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1928'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1928'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1929'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1929'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1930'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1930'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1931'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1931'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1932'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1932'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1933'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1933'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1934'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1934'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1935'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1935'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1936'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1936'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1937'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1937'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1938'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1938'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1939'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1939'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1940'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1940'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1941'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1941'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1942'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1942'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1943'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1943'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1944'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1944'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1945'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1945'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1946'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1946'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1947'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1947'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1948'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1948'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1949'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1949'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1950'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1950'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1951'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1951'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1952'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1952'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1953'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1953'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1954'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1954'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1955'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1955'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1956'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1956'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1957'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1957'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1958'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1958'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1959'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1959'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1960'

UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1960'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1961'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1961'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1962'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1962'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1963'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1963'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1964'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1964'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1965'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1965'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1966'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1966'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1967'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1967'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1968'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1968'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1969'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1969'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1970'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1970'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1971'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1971'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1972'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1972'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1973'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1973'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1974'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1974'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1975'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1975'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1976'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1976'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1977'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1977'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1978'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1978'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1979'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1979'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1980'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1980'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1981'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1981'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1982'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1982'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1983'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1983'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1984'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1984'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1985'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1985'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1986'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1986'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1987'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1987'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1988'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1988'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1989'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1989'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1990'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1990'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1991'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1991'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1992'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1992'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1993'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1993'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1994'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1994'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1995'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1995'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1996'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1996'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1997'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1997'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1998'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1998'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '1999'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '1999'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2000'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2000'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2001'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2001'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2002'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2002'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2003'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2003'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2004'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2004'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2005'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2005'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2006'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2006'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2007'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2007'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2008'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2008'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2009'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2009'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2010'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2010'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2011'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2011'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2012'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2012'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2013'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2013'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2014'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2014'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2015'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2015'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2016'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2016'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2017'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2017'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2018'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2018'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2019'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2019'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2020'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2020'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2021'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2021'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2022'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2022'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2023'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2023'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2024'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2024'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2025'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2025'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2026'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2026'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2027'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2027'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2028'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2028'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2029'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2029'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2030'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2030'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2031'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2031'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2032'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2032'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2033'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2033'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2034'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2034'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2035'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2035'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2036'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2036'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2037'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2037'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2038'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2038'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2039'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2039'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2040'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2040'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2041'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2041'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2042'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2042'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2043'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2043'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2044'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2044'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2045'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2045'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2046'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2046'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2047'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2047'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2048'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2048'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2049'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2049'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2050'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2050'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2051'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2051'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2052'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2052'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2053'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2053'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2054'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2054'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2055'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2055'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2056'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2056'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2057'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2057'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2058'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2058'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2059'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2059'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2060'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2060'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2061'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2061'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2062'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2062'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2063'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2063'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2064'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2064'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2065'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2065'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2066'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2066'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2067'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2067'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2068'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2068'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2069'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2069'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2070'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2070'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2071'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2071'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2072'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2072'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2073'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2073'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2074'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2074'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2075'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2075'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2076'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2076'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2077'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2077'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2078'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2078'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2079'

UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2079'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2080'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2080'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2081'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2081'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2082'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2082'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2083'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2083'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2084'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2084'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2085'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2085'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2086'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2086'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2087'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2087'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2088'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2088'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2089'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2089'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2090'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2090'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2091'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2091'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2092'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2092'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2093'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2093'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2094'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2094'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2095'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2095'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2096'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2096'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2097'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2097'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2098'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2098'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2099'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2099'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2100'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2100'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2101'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2101'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2102'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2102'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2103'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2103'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2104'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2104'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2105'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2105'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2106'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2106'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2107'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2107'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2108'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2108'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2109'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2109'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2110'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2110'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2111'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2111'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2112'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2112'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2113'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2113'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2114'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2114'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2115'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2115'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2116'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2116'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2117'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2117'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2118'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2118'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2119'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2119'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2120'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2120'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2121'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2121'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2122'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2122'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2123'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2123'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2124'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2124'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2125'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2125'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2126'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2126'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2127'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2127'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2128'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2128'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2129'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2129'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2130'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2130'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2131'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2131'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2132'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2132'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2133'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2133'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2134'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2134'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2135'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2135'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2136'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2136'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2137'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2137'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2138'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2138'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2139'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2139'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2140'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2140'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2141'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2141'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2142'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2142'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2143'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2143'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2144'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2144'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2145'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2145'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2146'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2146'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2147'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2147'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2148'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2148'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2149'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2149'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2150'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2150'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2151'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2151'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2152'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2152'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2153'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2153'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2154'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2154'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2155'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2155'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2156'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2156'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2157'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2157'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2158'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2158'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2159'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2159'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2160'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2160'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2161'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2161'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2162'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2162'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2163'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2163'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2164'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2164'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2165'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2165'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2166'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2166'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2167'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2167'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2168'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2168'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2169'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2169'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2170'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2170'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2171'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2171'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2172'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2172'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2173'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2173'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2174'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2174'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2175'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2175'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2176'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2176'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2177'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2177'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2178'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2178'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2179'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2179'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2180'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2180'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2181'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2181'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2182'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2182'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2183'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2183'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2184'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2184'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2185'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2185'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2186'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2186'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2187'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2187'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2188'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2188'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2189'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2189'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2190'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2190'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2191'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2191'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2192'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2192'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2193'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2193'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2194'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2194'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2195'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2195'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2196'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2196'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2197'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2197'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2198'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2198'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2199'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2199'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2200'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2200'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2201'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2201'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2202'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2202'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2203'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2203'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2204'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2204'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2205'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2205'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2206'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2206'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2207'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2207'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2208'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2208'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2209'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2209'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2210'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2210'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2211'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2211'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2212'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2212'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2213'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2213'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2214'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2214'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2215'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2215'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2216'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2216'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2217'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2217'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2218'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2218'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2219'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2219'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2220'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2220'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2221'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2221'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2222'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2222'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2223'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2223'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2224'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2224'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2225'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2225'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2226'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2226'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2227'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2227'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2228'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2228'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2229'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2229'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2230'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2230'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2231'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2231'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2232'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2232'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2233'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2233'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2234'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2234'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2235'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2235'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2236'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2236'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2237'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2237'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2238'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2238'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2239'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2239'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2240'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2240'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2241'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2241'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2242'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2242'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2243'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2243'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2244'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2244'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2245'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2245'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2246'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2246'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2247'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2247'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2248'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2248'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2249'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2249'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2250'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2250'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2251'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2251'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2252'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2252'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2253'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2253'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2254'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2254'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2255'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2255'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2256'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2256'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2257'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2257'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2258'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2258'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2259'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2259'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2260'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2260'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2261'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2261'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2262'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2262'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2263'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2263'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2264'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2264'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2265'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2265'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2266'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2266'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2267'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2267'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2268'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2268'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2269'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2269'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2270'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2270'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2271'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2271'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2272'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2272'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2273'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2273'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2274'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2274'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2275'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2275'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2276'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2276'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2277'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2277'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2278'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2278'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2279'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2279'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2280'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2280'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2281'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2281'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2282'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2282'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2283'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2283'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2284'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2284'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2285'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2285'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2286'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2286'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2287'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2287'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2288'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2288'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2289'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2289'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2290'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2290'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2291'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2291'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2292'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2292'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2293'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2293'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2294'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2294'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2295'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2295'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2296'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2296'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2297'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2297'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2298'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2298'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2299'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2299'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2300'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2300'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2301'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2301'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2302'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2302'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2303'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2303'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2304'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2304'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2305'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2305'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2306'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2306'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2307'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2307'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2308'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2308'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2309'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2309'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2310'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2310'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2311'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2311'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2312'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2312'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2313'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2313'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2314'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2314'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2315'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2315'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2316'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2316'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2317'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2317'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2318'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2318'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2319'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2319'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2320'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2320'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2321'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2321'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2322'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2322'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2323'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2323'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2324'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2324'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2325'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2325'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2326'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2326'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2327'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2327'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2328'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2328'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2329'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2329'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2330'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2330'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2331'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2331'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2332'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2332'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2333'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2333'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2334'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2334'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2335'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2335'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2336'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2336'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2337'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2337'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2338'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2338'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2339'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2339'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2340'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2340'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2341'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2341'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2342'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2342'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2343'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2343'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2344'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2344'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2345'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2345'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2346'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2346'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2347'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2347'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2348'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2348'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2349'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2349'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2350'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2350'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2351'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2351'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2352'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2352'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2353'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2353'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2354'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2354'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2355'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2355'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2356'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2356'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2357'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2357'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2358'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2358'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2359'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2359'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2360'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2360'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2361'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2361'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2362'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2362'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2363'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2363'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2364'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2364'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2365'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2365'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2366'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2366'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2367'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2367'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2368'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2368'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2369'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2369'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2370'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2370'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2371'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2371'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2372'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2372'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2373'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2373'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2374'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2374'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2375'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2375'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2376'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2376'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2377'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2377'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2378'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2378'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2379'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2379'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2380'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2380'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2381'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2381'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2382'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2382'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2383'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2383'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2384'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2384'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2385'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2385'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2386'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2386'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2387'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2387'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2388'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2388'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2389'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2389'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2390'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2390'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2391'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2391'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2392'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2392'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2393'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2393'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2394'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2394'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2395'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2395'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2396'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2396'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2397'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2397'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2398'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2398'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2399'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2399'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2400'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2400'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2401'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2401'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2402'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2402'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2403'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2403'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2404'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2404'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2405'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2405'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2406'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2406'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2407'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2407'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2408'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2408'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2409'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2409'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2410'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2410'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2411'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2411'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2412'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2412'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2413'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2413'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2414'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2414'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2415'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2415'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2416'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2416'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2417'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2417'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2418'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2418'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2419'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2419'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2420'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2420'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2421'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2421'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2422'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2422'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2423'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2423'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2424'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2424'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2425'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2425'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2426'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2426'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2427'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2427'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2428'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2428'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2429'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2429'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2430'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2430'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2431'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2431'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2432'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2432'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2433'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2433'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2434'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2434'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2435'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2435'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2436'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2436'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2437'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2437'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2438'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2438'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2439'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2439'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2440'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2440'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2441'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2441'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2442'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2442'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2443'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2443'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2444'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2444'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2445'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2445'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2446'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2446'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2447'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2447'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2448'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2448'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2449'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2449'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2450'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2450'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2451'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2451'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2452'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2452'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2453'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2453'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2454'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2454'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2455'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2455'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2456'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2456'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2457'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2457'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2458'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2458'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2459'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2459'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2460'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2460'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2461'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2461'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2462'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2462'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2463'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2463'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2464'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2464'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2465'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2465'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2466'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2466'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2467'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2467'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2468'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2468'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2469'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2469'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2470'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2470'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2471'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2471'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2472'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2472'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2473'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2473'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2474'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2474'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2475'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2475'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2476'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2476'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2477'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2477'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2478'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2478'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2479'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2479'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2480'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2480'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2481'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2481'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2482'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2482'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2483'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2483'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2484'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2484'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2485'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2485'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2486'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2486'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2487'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2487'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2488'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2488'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2489'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2489'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2490'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2490'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2491'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2491'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2492'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2492'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2493'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2493'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2494'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2494'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2495'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2495'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2496'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2496'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2497'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2497'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2498'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2498'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2499'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2499'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2500'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2500'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2501'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2501'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2502'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2502'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2503'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2503'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2504'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2504'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2505'

UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2505'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2506'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2506'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2507'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2507'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2508'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2508'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2509'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2509'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2510'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2510'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2511'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2511'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2512'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2512'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2513'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2513'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2514'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2514'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2515'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2515'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2516'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2516'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2517'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2517'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2518'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2518'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2519'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2519'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2520'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2520'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2521'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2521'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2522'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2522'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2523'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2523'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2524'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2524'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2525'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2525'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2526'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2526'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2527'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2527'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2528'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2528'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2529'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2529'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2530'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2530'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2531'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2531'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2532'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2532'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2533'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2533'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2534'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2534'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2535'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2535'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2536'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2536'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2537'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2537'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2538'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2538'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2539'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2539'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2540'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2540'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2541'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2541'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2542'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2542'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2543'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2543'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2544'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2544'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2545'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2545'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2546'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2546'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2547'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2547'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2548'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2548'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2549'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2549'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2550'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2550'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2551'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2551'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2552'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2552'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2553'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2553'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2554'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2554'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2555'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2555'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2556'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2556'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2557'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2557'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2558'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2558'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2559'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2559'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2560'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2560'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2561'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2561'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2562'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2562'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2563'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2563'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2564'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2564'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2565'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2565'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2566'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2566'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2567'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2567'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2568'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2568'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2569'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2569'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2570'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2570'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2571'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2571'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2572'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2572'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2573'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2573'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2574'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2574'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2575'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2575'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2576'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2576'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2577'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2577'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2578'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2578'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2579'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2579'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2580'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2580'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2581'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2581'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2582'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2582'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2583'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2583'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2584'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2584'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2585'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2585'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2586'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2586'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2587'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2587'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2588'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2588'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2589'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2589'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2590'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2590'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2591'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2591'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2592'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2592'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2593'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2593'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2594'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2594'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2595'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2595'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2596'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2596'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2597'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2597'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2598'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2598'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2599'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2599'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2600'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2600'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2601'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2601'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2602'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2602'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2603'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2603'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2604'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2604'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2605'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2605'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2606'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2606'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2607'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2607'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2608'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2608'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2609'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2609'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2610'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2610'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2611'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2611'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2612'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2612'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2613'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2613'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2614'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2614'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2615'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2615'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2616'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2616'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2617'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2617'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2618'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2618'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2619'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2619'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2620'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2620'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2621'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2621'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2622'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2622'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2623'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2623'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2624'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2624'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2625'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2625'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2626'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2626'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2627'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2627'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2628'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2628'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2629'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2629'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2630'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2630'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2631'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2631'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2632'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2632'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2633'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2633'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2634'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2634'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2635'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2635'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2636'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2636'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2637'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2637'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2638'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2638'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2639'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2639'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2640'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2640'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2641'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2641'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2642'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2642'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2643'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2643'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2644'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2644'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2645'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2645'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2646'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2646'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2647'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2647'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2648'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2648'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2649'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2649'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2650'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2650'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2651'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2651'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2652'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2652'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2653'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2653'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2654'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2654'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2655'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2655'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2656'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2656'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2657'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2657'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2658'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2658'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2659'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2659'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2660'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2660'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2661'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2661'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2662'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2662'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2663'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2663'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2664'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2664'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2665'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2665'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2666'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2666'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2667'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2667'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2668'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2668'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2669'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2669'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2670'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2670'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2671'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2671'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2672'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2672'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2673'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2673'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2674'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2674'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2675'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2675'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2676'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2676'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2677'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2677'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2678'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2678'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2679'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2679'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2680'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2680'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2681'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2681'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2682'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2682'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2683'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2683'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2684'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2684'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2685'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2685'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2686'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2686'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2687'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2687'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2688'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2688'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2689'

UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2689'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2690'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2690'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2691'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2691'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2692'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2692'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2693'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2693'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2694'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2694'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2695'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2695'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2696'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2696'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2697'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2697'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2698'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2698'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2699'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2699'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2700'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2700'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2701'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2701'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2702'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2702'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2703'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2703'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2704'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2704'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2705'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2705'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2706'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2706'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2707'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2707'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2708'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2708'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2709'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2709'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2710'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2710'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2711'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2711'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2712'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2712'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2713'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2713'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2714'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2714'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2715'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2715'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2716'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2716'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2717'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2717'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2718'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2718'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2719'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2719'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2720'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2720'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2721'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2721'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2722'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2722'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2723'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2723'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2724'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2724'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2725'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2725'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2726'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2726'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2727'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2727'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2728'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2728'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2729'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2729'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2730'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2730'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2731'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2731'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2732'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2732'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2733'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2733'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2734'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2734'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2735'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2735'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2736'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2736'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2737'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2737'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2738'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2738'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2739'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2739'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2740'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2740'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2741'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2741'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2742'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2742'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2743'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2743'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2744'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2744'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2745'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2745'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2746'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2746'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2747'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2747'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2748'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2748'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2749'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2749'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2750'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2750'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2751'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2751'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2752'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2752'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2753'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2753'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2754'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2754'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2755'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2755'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2756'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2756'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2757'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2757'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2758'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2758'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2759'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2759'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2760'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2760'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2761'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2761'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2762'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2762'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2763'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2763'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2764'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2764'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2765'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2765'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2766'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2766'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2767'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2767'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2768'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2768'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2769'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2769'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2770'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2770'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2771'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2771'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2772'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2772'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2773'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2773'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2774'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2774'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2775'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2775'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2776'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2776'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2777'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2777'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2778'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2778'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2779'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2779'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2780'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2780'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2781'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2781'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2782'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2782'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2783'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2783'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2784'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2784'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2785'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2785'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2786'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2786'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2787'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2787'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2788'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2788'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2789'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2789'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2790'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2790'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2791'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2791'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2792'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2792'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2793'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2793'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2794'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2794'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2795'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2795'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2796'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2796'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2797'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2797'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2798'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2798'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2799'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2799'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2800'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2800'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2801'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2801'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2802'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2802'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2803'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2803'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2804'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2804'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2805'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2805'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2806'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2806'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2807'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2807'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2808'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2808'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2809'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2809'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2810'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2810'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2811'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2811'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2812'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2812'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2813'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2813'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2814'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2814'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2815'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2815'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2816'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2816'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2817'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2817'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2818'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2818'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2819'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2819'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2820'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2820'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2821'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2821'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2822'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2822'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2823'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2823'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2824'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2824'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2825'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2825'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2826'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2826'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2827'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2827'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2828'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2828'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2829'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2829'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2830'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2830'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2831'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2831'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2832'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2832'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2833'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2833'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2834'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2834'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2835'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2835'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2836'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2836'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2837'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2837'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2838'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2838'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2839'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2839'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2840'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2840'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2841'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2841'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2842'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2842'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2843'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2843'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2844'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2844'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2845'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2845'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2846'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2846'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2847'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2847'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2848'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2848'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2849'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2849'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2850'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2850'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2851'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2851'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2852'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2852'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2853'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2853'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2854'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2854'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2855'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2855'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2856'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2856'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2857'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2857'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2858'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2858'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2859'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2859'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2860'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2860'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2861'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2861'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2862'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2862'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2863'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2863'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2864'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2864'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2865'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2865'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2866'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2866'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2867'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2867'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2868'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2868'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2869'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2869'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2870'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2870'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2871'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2871'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2872'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2872'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2873'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2873'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2874'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2874'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2875'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2875'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2876'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2876'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2877'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2877'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2878'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2878'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2879'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2879'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2880'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2880'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2881'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2881'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2882'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2882'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2883'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2883'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2884'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2884'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2885'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2885'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2886'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2886'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2887'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2887'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2888'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2888'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2889'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2889'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2890'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2890'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2891'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2891'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2892'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2892'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2893'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2893'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2894'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2894'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2895'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2895'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2896'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2896'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2897'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2897'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2898'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2898'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2899'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2899'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2900'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2900'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2901'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2901'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2902'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2902'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2903'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2903'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2904'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2904'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2905'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2905'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2906'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2906'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2907'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2907'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2908'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2908'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2909'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2909'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2910'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2910'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2911'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2911'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2912'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2912'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2913'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2913'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2914'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2914'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2915'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2915'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2916'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2916'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2917'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2917'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2918'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2918'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2919'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2919'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2920'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2920'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2921'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2921'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2922'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2922'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2923'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2923'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2924'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2924'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2925'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2925'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2926'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2926'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2927'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2927'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2928'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2928'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2929'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2929'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2930'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2930'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2931'

UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2931'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2932'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2932'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2933'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2933'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2934'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2934'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2935'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2935'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2936'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2936'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2937'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2937'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2938'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2938'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2939'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2939'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2940'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2940'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2941'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2941'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2942'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2942'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2943'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2943'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2944'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2944'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2945'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2945'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2946'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2946'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2947'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2947'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2948'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2948'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2949'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2949'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2950'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2950'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2951'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2951'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2952'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2952'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2953'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2953'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2954'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2954'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2955'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2955'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2956'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2956'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2957'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2957'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2958'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2958'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2959'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2959'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2960'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2960'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2961'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2961'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2962'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2962'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2963'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2963'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2964'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2964'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2965'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2965'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2966'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2966'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2967'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2967'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2968'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2968'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2969'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2969'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2970'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2970'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2971'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2971'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2972'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2972'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2973'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2973'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2974'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2974'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2975'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2975'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2976'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2976'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2977'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2977'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2978'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2978'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2979'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2979'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2980'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2980'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2981'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2981'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2982'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2982'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2983'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2983'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2984'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2984'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2985'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2985'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2986'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2986'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2987'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2987'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2988'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2988'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2989'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2989'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2990'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2990'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2991'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2991'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2992'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2992'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2993'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2993'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2994'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2994'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2995'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2995'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2996'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2996'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2997'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2997'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2998'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2998'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '2999'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '2999'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3000'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3000'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3001'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3001'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3002'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3002'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3003'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3003'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3004'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3004'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3005'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3005'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3006'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3006'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3007'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3007'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3008'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3008'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3009'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3009'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3010'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3010'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3011'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3011'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3012'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3012'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3013'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3013'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3014'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3014'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3015'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3015'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3016'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3016'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3017'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3017'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3018'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3018'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3019'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3019'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3020'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3020'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3021'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3021'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3022'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3022'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3023'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3023'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3024'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3024'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3025'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3025'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3026'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3026'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3027'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3027'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3028'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3028'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3029'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3029'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3030'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3030'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3031'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3031'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3032'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3032'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3033'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3033'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3034'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3034'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3035'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3035'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3036'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3036'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3037'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3037'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3038'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3038'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3039'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3039'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3040'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3040'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3041'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3041'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3042'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3042'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3043'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3043'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3044'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3044'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3045'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3045'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3046'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3046'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3047'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3047'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3048'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3048'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3049'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3049'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3050'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3050'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3051'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3051'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3052'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3052'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3053'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3053'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3054'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3054'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3055'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3055'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3056'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3056'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3057'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3057'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3058'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3058'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3059'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3059'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3060'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3060'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3061'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3061'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3062'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3062'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3063'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3063'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3064'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3064'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3065'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3065'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3066'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3066'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3067'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3067'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3068'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3068'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3069'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3069'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3070'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3070'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3071'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3071'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3072'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3072'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3073'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3073'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3074'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3074'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3075'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3075'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3076'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3076'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3077'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3077'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3078'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3078'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3079'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3079'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3080'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3080'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3081'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3081'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3082'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3082'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3083'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3083'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3084'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3084'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3085'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3085'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3086'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3086'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3087'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3087'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3088'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3088'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3089'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3089'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3090'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3090'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3091'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3091'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3092'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3092'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3093'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3093'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3094'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3094'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3095'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3095'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3096'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3096'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3097'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3097'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3098'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3098'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3099'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3099'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3100'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3100'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3101'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3101'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3102'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3102'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3103'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3103'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3104'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3104'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3105'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3105'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3106'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3106'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3107'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3107'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3108'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3108'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3109'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3109'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3110'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3110'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3111'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3111'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3112'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3112'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3113'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3113'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3114'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3114'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3115'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3115'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3116'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3116'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3117'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3117'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3118'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3118'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3119'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3119'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3120'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3120'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3121'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3121'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3122'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3122'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3123'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3123'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3124'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3124'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3125'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3125'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3126'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3126'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3127'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3127'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3128'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3128'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3129'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3129'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3130'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3130'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3131'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3131'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3132'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3132'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3133'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3133'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3134'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3134'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3135'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3135'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3136'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3136'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3137'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3137'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3138'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3138'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3139'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3139'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3140'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3140'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3141'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3141'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3142'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3142'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3143'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3143'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3144'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3144'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3145'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3145'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3146'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3146'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3147'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3147'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3148'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3148'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3149'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3149'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3150'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3150'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3151'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3151'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3152'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3152'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3153'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3153'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3154'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3154'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3155'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3155'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3156'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3156'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3157'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3157'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3158'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3158'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3159'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3159'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3160'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3160'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3161'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3161'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3162'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3162'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3163'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3163'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3164'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3164'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3165'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3165'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3166'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3166'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3167'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3167'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3168'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3168'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3169'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3169'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3170'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3170'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3171'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3171'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3172'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3172'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3173'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3173'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3174'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3174'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3175'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3175'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3176'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3176'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3177'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3177'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3178'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3178'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3179'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3179'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3180'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3180'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3181'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3181'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3182'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3182'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3183'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3183'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3184'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3184'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3185'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3185'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3186'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3186'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3187'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3187'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3188'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3188'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3189'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3189'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3190'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3190'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3191'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3191'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3192'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3192'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3193'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3193'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3194'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3194'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3195'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3195'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3196'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3196'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3197'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3197'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3198'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3198'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3199'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3199'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3200'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3200'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3201'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3201'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3202'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3202'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3203'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3203'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3204'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3204'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3205'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3205'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3206'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3206'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3207'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3207'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3208'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3208'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3209'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3209'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3210'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3210'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3211'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3211'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3212'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3212'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3213'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3213'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3214'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3214'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3215'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3215'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3216'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3216'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3217'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3217'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3218'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3218'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3219'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3219'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3220'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3220'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3221'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3221'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3222'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3222'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3223'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3223'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3224'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3224'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3225'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3225'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3226'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3226'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3227'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3227'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3228'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3228'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3229'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3229'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3230'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3230'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3231'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3231'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3232'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3232'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3233'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3233'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3234'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3234'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3235'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3235'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3236'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3236'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3237'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3237'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3238'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3238'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3239'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3239'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3240'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3240'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3241'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3241'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3242'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3242'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3243'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3243'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3244'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3244'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3245'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3245'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3246'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3246'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3247'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3247'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3248'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3248'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3249'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3249'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3250'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3250'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3251'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3251'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3252'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3252'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3253'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3253'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3254'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3254'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3255'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3255'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3256'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3256'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3257'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3257'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3258'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3258'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3259'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3259'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3260'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3260'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3261'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3261'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3262'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3262'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3263'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3263'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3264'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3264'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3265'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3265'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3266'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3266'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3267'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3267'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3268'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3268'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3269'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3269'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3270'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3270'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3271'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3271'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3272'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3272'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3273'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3273'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3274'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3274'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3275'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3275'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3276'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3276'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3277'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3277'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3278'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3278'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3279'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3279'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3280'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3280'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3281'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3281'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3282'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3282'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3283'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3283'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3284'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3284'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3285'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3285'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3286'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3286'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3287'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3287'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3288'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3288'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3289'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3289'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3290'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3290'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3291'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3291'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3292'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3292'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3293'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3293'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3294'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3294'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3295'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3295'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3296'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3296'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3297'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3297'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3298'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3298'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3299'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3299'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3300'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3300'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3301'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3301'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3302'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3302'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3303'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3303'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3304'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3304'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3305'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3305'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3306'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3306'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3307'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3307'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3308'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3308'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3309'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3309'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3310'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3310'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3311'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3311'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3312'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3312'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3313'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3313'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3314'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3314'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3315'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3315'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3316'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3316'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3317'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3317'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3318'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3318'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3319'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3319'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3320'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3320'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3321'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3321'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3322'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3322'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3323'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3323'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3324'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3324'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3325'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3325'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3326'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3326'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3327'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3327'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3328'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3328'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3329'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3329'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3330'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3330'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3331'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3331'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3332'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3332'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3333'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3333'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3334'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3334'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3335'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3335'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3336'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3336'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3337'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3337'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3338'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3338'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3339'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3339'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3340'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3340'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3341'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3341'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3342'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3342'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3343'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3343'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3344'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3344'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3345'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3345'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3346'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3346'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3347'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3347'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3348'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3348'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3349'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3349'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3350'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3350'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3351'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3351'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3352'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3352'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3353'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3353'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3354'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3354'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3355'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3355'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3356'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3356'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3357'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3357'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3358'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3358'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3359'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3359'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3360'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3360'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3361'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3361'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3362'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3362'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3363'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3363'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3364'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3364'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3365'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3365'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3366'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3366'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3367'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3367'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3368'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3368'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3369'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3369'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3370'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3370'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3371'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3371'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3372'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3372'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3373'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3373'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3374'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3374'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3375'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3375'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3376'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3376'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3377'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3377'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3378'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3378'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3379'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3379'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3380'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3380'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3381'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3381'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3382'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3382'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3383'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3383'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3384'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3384'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3385'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3385'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3386'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3386'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3387'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3387'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3388'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3388'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3389'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3389'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3390'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3390'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3391'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3391'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3392'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3392'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3393'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3393'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3394'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3394'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3395'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3395'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3396'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3396'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3397'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3397'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3398'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3398'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3399'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3399'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3400'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3400'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3401'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3401'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3402'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3402'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3403'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3403'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3404'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3404'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3405'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3405'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3406'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3406'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3407'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3407'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3408'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3408'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3409'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3409'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3410'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3410'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3411'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3411'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3412'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3412'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3413'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3413'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3414'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3414'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3415'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3415'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3416'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3416'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3417'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3417'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3418'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3418'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3419'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3419'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3420'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3420'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3421'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3421'

None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3422'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3422'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3423'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3423'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3424'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3424'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3425'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3425'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3426'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3426'
None
UPDATE job_vacancies SET max_age =  Null where raw_id = '3427'
UPDATE jobstreet_raws_rc SET max_age = '--extracted--'     where id = '3427'