In [2]:
# Connect to DB

host="localhost"
user="root"

# host="192.168.100.3"
# user="rootx"

import mysql.connector
mydb = mysql.connector.connect(
    host=host,
    user=user,
    password="",
    database="pr_scraping_job_vacancy_indonesia_2022_04"
)
mycursor = mydb.cursor()
print('connect')

entity = 'gpa_min'

# set query 1
select = ' id, created_at, ' + entity
fromdb = 'jobstreet_raws'
where = ' '
group = ' ' 

# ALTER TABLE `job_vacancies` ADD `salary_type_id` INT NULL DEFAULT NULL AFTER `experience`;

connect

In [4]:
query = 'ALTER TABLE `job_vacancies` ADD `gpa_min` INT NULL DEFAULT NULL AFTER `experience`;'
mycursor.execute(query)
mydb.commit()    
print('Done')

Done

In [ ]:
# insert new job_vacancies 

# set query 1
select = ' id, ' + entity
fromdb = 'jobstreet_raws_v2'
where = ' '
group = ' ' 
 
# query 1
mycursor = mydb.cursor()
mycursor.execute("SELECT " + select + " FROM `" + fromdb + "` " + where + group  )
myresult = mycursor.fetchall()
  
print('Start and Please Wait..')
# loop query 1
for x in myresult:  
    idx = str(x[0])
    word = x[1]  
    
#     words = ' id: ' + idx + ' // word: ' + word
    print(word)
    
    query3 = "UPDATE job_vacancies SET "+entity+" =  Null where raw_id = '" + idx + "'"
    
#     if(word is None):
#         query3 = "UPDATE job_vacancies SET "+entity+" =  Null where raw_id = '" + idx + "'"
#     else:
#         query3 = "UPDATE job_vacancies SET "+entity+" =  '" + word + "' where raw_id = '" + idx + "'"
        
    print(query3)
    mycursor.execute(query3)
    mydb.commit()  

    query4 = "UPDATE jobstreet_raws_rc SET "+entity+" = '--extracted--'   " 
    where4 = "  where id = '" + idx + "'"  
    print(query4 + where4)
    mycursor.execute(query4 + where4)
    mydb.commit()  
         
print('Done : ' + str(len(myresult)) + ' row(s)')

Start and Please Wait..
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '10'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '10'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '11'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '11'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '12'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '12'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '13'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '13'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '14'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '14'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '15'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '15'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '16'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '16'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '17'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '17'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '18'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '18'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '19'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '19'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '20'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '20'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '21'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '21'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '22'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '22'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '23'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '23'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '24'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '24'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '25'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '25'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '26'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '26'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '27'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '27'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '28'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '28'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '29'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '29'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '30'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '30'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '31'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '31'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '32'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '32'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '33'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '33'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '34'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '34'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '35'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '35'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '36'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '36'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '37'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '37'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '38'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '38'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '39'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '39'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '40'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '40'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '41'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '41'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '42'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '42'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '43'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '43'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '44'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '44'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '45'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '45'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '46'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '46'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '47'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '47'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '48'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '48'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '49'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '49'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '50'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '50'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '51'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '51'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '52'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '52'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '53'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '53'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '54'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '54'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '55'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '55'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '56'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '56'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '57'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '57'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '58'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '58'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '59'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '59'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '60'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '60'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '61'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '61'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '62'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '62'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '63'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '63'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '64'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '64'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '65'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '65'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '66'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '66'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '67'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '67'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '68'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '68'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '69'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '69'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '70'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '70'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '71'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '71'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '72'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '72'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '73'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '73'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '74'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '74'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '75'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '75'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '76'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '76'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '77'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '77'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '78'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '78'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '79'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '79'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '80'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '80'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '81'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '81'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '82'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '82'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '83'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '83'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '84'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '84'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '85'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '85'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '86'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '86'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '87'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '87'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '88'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '88'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '89'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '89'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '90'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '90'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '91'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '91'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '92'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '92'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '93'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '93'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '94'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '94'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '95'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '95'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '96'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '96'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '97'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '97'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '98'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '98'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '99'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '99'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '100'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '100'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '101'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '101'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '102'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '102'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '103'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '103'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '104'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '104'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '105'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '105'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '106'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '106'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '107'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '107'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '108'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '108'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '109'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '109'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '110'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '110'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '111'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '111'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '112'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '112'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '113'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '113'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '114'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '114'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '115'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '115'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '116'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '116'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '117'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '117'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '118'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '118'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '119'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '119'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '120'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '120'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '121'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '121'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '122'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '122'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '123'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '123'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '124'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '124'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '125'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '125'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '126'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '126'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '127'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '127'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '128'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '128'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '129'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '129'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '130'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '130'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '131'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '131'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '132'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '132'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '133'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '133'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '134'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '134'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '135'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '135'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '136'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '136'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '137'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '137'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '138'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '138'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '139'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '139'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '140'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '140'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '141'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '141'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '142'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '142'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '143'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '143'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '144'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '144'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '145'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '145'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '146'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '146'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '147'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '147'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '148'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '148'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '149'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '149'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '150'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '150'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '151'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '151'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '152'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '152'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '153'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '153'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '154'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '154'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '155'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '155'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '156'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '156'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '157'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '157'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '158'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '158'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '159'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '159'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '160'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '160'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '161'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '161'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '162'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '162'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '163'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '163'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '164'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '164'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '165'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '165'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '166'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '166'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '167'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '167'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '168'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '168'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '169'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '169'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '170'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '170'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '171'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '171'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '172'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '172'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '173'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '173'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '174'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '174'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '175'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '175'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '176'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '176'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '177'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '177'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '178'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '178'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '179'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '179'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '180'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '180'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '181'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '181'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '182'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '182'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '183'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '183'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '184'

UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '184'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '185'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '185'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '186'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '186'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '187'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '187'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '188'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '188'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '189'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '189'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '190'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '190'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '191'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '191'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '192'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '192'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '193'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '193'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '194'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '194'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '195'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '195'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '196'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '196'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '197'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '197'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '198'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '198'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '199'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '199'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '200'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '200'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '201'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '201'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '202'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '202'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '203'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '203'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '204'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '204'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '205'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '205'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '206'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '206'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '207'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '207'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '208'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '208'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '209'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '209'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '210'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '210'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '211'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '211'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '212'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '212'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '213'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '213'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '214'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '214'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '215'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '215'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '216'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '216'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '217'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '217'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '218'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '218'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '219'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '219'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '220'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '220'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '221'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '221'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '222'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '222'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '223'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '223'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '224'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '224'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '225'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '225'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '226'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '226'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '227'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '227'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '228'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '228'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '229'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '229'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '230'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '230'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '231'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '231'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '232'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '232'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '233'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '233'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '234'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '234'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '235'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '235'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '236'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '236'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '237'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '237'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '238'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '238'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '239'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '239'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '240'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '240'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '241'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '241'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '242'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '242'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '243'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '243'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '244'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '244'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '245'

UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '245'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '246'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '246'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '247'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '247'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '248'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '248'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '249'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '249'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '250'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '250'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '251'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '251'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '252'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '252'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '253'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '253'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '254'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '254'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '255'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '255'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '256'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '256'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '257'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '257'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '258'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '258'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '259'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '259'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '260'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '260'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '261'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '261'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '262'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '262'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '263'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '263'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '264'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '264'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '265'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '265'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '266'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '266'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '267'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '267'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '268'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '268'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '269'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '269'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '270'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '270'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '271'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '271'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '272'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '272'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '273'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '273'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '274'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '274'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '275'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '275'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '276'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '276'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '277'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '277'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '278'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '278'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '279'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '279'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '280'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '280'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '281'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '281'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '282'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '282'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '283'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '283'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '284'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '284'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '285'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '285'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '286'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '286'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '287'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '287'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '288'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '288'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '289'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '289'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '290'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '290'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '291'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '291'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '292'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '292'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '293'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '293'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '294'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '294'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '295'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '295'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '296'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '296'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '297'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '297'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '298'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '298'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '299'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '299'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '300'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '300'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '301'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '301'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '302'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '302'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '303'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '303'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '304'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '304'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '305'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '305'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '306'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '306'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '307'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '307'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '308'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '308'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '309'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '309'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '310'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '310'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '311'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '311'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '312'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '312'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '313'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '313'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '314'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '314'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '315'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '315'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '316'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '316'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '317'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '317'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '318'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '318'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '319'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '319'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '320'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '320'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '321'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '321'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '322'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '322'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '323'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '323'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '324'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '324'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '325'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '325'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '326'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '326'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '327'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '327'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '328'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '328'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '329'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '329'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '330'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '330'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '331'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '331'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '332'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '332'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '333'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '333'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '334'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '334'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '335'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '335'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '336'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '336'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '337'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '337'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '338'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '338'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '339'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '339'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '340'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '340'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '341'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '341'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '342'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '342'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '343'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '343'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '344'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '344'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '345'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '345'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '346'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '346'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '347'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '347'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '348'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '348'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '349'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '349'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '350'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '350'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '351'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '351'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '352'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '352'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '353'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '353'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '354'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '354'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '355'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '355'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '356'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '356'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '357'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '357'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '358'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '358'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '359'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '359'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '360'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '360'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '361'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '361'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '362'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '362'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '363'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '363'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '364'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '364'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '365'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '365'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '366'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '366'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '367'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '367'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '368'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '368'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '369'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '369'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '370'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '370'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '371'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '371'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '372'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '372'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '373'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '373'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '374'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '374'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '375'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '375'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '376'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '376'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '377'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '377'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '378'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '378'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '379'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '379'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '380'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '380'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '381'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '381'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '382'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '382'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '383'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '383'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '384'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '384'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '385'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '385'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '386'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '386'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '387'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '387'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '388'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '388'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '389'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '389'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '390'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '390'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '391'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '391'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '392'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '392'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '393'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '393'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '394'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '394'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '395'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '395'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '396'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '396'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '397'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '397'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '398'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '398'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '399'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '399'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '400'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '400'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '401'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '401'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '402'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '402'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '403'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '403'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '404'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '404'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '405'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '405'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '406'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '406'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '407'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '407'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '408'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '408'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '409'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '409'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '410'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '410'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '411'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '411'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '412'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '412'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '413'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '413'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '414'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '414'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '415'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '415'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '416'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '416'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '417'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '417'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '418'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '418'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '419'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '419'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '420'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '420'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '421'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '421'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '422'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '422'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '423'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '423'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '424'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '424'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '425'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '425'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '426'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '426'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '427'

UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '427'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '428'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '428'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '429'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '429'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '430'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '430'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '431'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '431'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '432'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '432'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '433'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '433'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '434'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '434'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '435'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '435'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '436'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '436'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '437'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '437'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '438'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '438'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '439'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '439'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '440'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '440'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '441'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '441'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '442'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '442'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '443'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '443'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '444'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '444'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '445'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '445'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '446'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '446'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '447'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '447'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '448'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '448'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '449'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '449'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '450'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '450'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '451'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '451'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '452'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '452'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '453'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '453'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '454'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '454'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '455'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '455'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '456'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '456'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '457'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '457'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '458'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '458'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '459'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '459'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '460'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '460'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '461'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '461'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '462'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '462'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '463'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '463'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '464'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '464'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '465'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '465'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '466'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '466'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '467'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '467'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '468'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '468'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '469'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '469'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '470'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '470'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '471'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '471'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '472'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '472'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '473'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '473'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '474'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '474'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '475'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '475'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '476'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '476'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '477'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '477'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '478'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '478'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '479'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '479'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '480'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '480'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '481'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '481'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '482'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '482'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '483'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '483'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '484'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '484'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '485'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '485'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '486'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '486'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '487'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '487'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '488'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '488'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '489'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '489'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '490'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '490'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '491'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '491'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '492'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '492'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '493'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '493'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '494'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '494'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '495'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '495'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '496'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '496'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '497'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '497'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '498'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '498'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '499'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '499'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '500'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '500'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '501'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '501'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '502'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '502'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '503'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '503'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '504'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '504'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '505'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '505'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '506'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '506'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '507'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '507'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '508'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '508'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '509'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '509'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '510'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '510'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '511'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '511'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '512'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '512'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '513'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '513'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '514'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '514'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '515'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '515'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '516'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '516'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '517'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '517'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '518'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '518'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '519'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '519'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '520'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '520'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '521'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '521'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '522'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '522'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '523'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '523'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '524'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '524'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '525'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '525'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '526'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '526'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '527'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '527'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '528'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '528'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '529'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '529'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '530'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '530'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '531'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '531'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '532'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '532'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '533'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '533'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '534'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '534'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '535'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '535'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '536'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '536'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '537'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '537'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '538'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '538'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '539'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '539'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '540'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '540'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '541'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '541'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '542'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '542'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '543'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '543'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '544'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '544'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '545'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '545'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '546'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '546'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '547'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '547'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '548'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '548'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '549'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '549'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '550'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '550'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '551'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '551'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '552'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '552'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '553'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '553'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '554'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '554'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '555'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '555'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '556'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '556'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '557'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '557'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '558'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '558'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '559'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '559'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '560'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '560'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '561'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '561'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '562'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '562'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '563'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '563'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '564'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '564'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '565'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '565'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '566'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '566'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '567'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '567'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '568'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '568'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '569'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '569'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '570'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '570'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '571'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '571'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '572'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '572'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '573'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '573'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '574'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '574'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '575'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '575'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '576'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '576'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '577'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '577'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '578'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '578'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '579'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '579'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '580'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '580'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '581'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '581'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '582'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '582'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '583'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '583'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '584'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '584'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '585'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '585'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '586'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '586'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '587'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '587'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '588'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '588'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '589'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '589'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '590'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '590'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '591'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '591'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '592'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '592'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '593'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '593'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '594'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '594'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '595'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '595'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '596'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '596'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '597'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '597'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '598'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '598'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '599'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '599'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '600'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '600'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '601'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '601'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '602'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '602'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '603'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '603'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '604'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '604'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '605'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '605'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '606'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '606'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '607'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '607'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '608'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '608'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '609'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '609'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '610'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '610'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '611'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '611'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '612'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '612'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '613'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '613'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '614'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '614'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '615'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '615'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '616'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '616'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '617'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '617'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '618'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '618'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '619'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '619'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '620'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '620'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '621'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '621'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '622'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '622'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '623'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '623'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '624'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '624'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '625'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '625'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '626'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '626'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '627'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '627'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '628'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '628'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '629'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '629'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '630'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '630'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '631'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '631'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '632'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '632'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '633'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '633'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '634'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '634'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '635'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '635'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '636'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '636'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '637'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '637'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '638'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '638'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '639'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '639'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '640'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '640'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '641'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '641'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '642'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '642'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '643'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '643'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '644'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '644'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '645'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '645'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '646'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '646'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '647'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '647'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '648'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '648'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '649'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '649'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '650'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '650'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '651'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '651'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '652'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '652'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '653'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '653'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '654'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '654'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '655'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '655'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '656'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '656'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '657'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '657'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '658'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '658'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '659'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '659'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '660'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '660'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '661'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '661'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '662'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '662'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '663'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '663'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '664'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '664'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '665'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '665'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '666'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '666'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '667'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '667'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '668'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '668'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '669'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '669'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '670'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '670'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '671'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '671'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '672'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '672'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '673'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '673'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '674'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '674'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '675'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '675'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '676'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '676'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '677'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '677'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '678'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '678'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '679'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '679'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '680'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '680'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '681'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '681'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '682'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '682'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '683'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '683'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '684'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '684'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '685'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '685'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '686'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '686'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '687'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '687'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '688'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '688'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '689'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '689'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '690'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '690'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '691'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '691'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '692'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '692'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '693'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '693'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '694'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '694'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '695'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '695'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '696'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '696'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '697'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '697'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '698'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '698'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '699'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '699'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '700'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '700'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '701'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '701'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '702'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '702'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '703'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '703'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '704'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '704'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '705'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '705'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '706'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '706'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '707'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '707'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '708'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '708'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '709'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '709'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '710'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '710'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '711'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '711'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '712'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '712'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '713'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '713'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '714'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '714'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '715'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '715'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '716'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '716'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '717'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '717'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '718'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '718'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '719'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '719'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '720'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '720'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '721'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '721'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '722'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '722'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '723'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '723'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '724'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '724'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '725'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '725'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '726'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '726'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '727'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '727'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '728'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '728'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '729'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '729'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '730'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '730'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '731'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '731'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '732'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '732'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '733'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '733'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '734'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '734'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '735'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '735'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '736'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '736'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '737'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '737'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '738'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '738'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '739'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '739'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '740'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '740'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '741'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '741'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '742'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '742'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '743'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '743'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '744'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '744'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '745'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '745'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '746'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '746'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '747'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '747'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '748'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '748'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '749'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '749'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '750'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '750'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '751'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '751'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '752'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '752'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '753'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '753'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '754'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '754'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '755'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '755'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '756'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '756'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '757'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '757'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '758'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '758'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '759'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '759'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '760'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '760'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '761'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '761'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '762'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '762'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '763'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '763'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '764'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '764'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '765'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '765'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '766'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '766'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '767'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '767'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '768'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '768'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '769'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '769'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '770'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '770'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '771'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '771'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '772'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '772'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '773'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '773'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '774'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '774'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '775'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '775'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '776'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '776'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '777'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '777'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '778'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '778'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '779'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '779'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '780'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '780'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '781'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '781'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '782'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '782'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '783'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '783'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '784'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '784'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '785'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '785'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '786'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '786'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '787'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '787'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '788'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '788'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '789'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '789'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '790'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '790'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '791'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '791'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '792'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '792'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '793'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '793'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '794'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '794'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '795'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '795'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '796'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '796'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '797'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '797'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '798'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '798'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '799'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '799'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '800'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '800'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '801'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '801'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '802'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '802'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '803'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '803'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '804'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '804'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '805'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '805'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '806'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '806'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '807'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '807'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '808'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '808'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '809'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '809'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '810'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '810'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '811'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '811'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '812'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '812'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '813'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '813'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '814'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '814'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '815'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '815'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '816'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '816'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '817'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '817'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '818'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '818'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '819'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '819'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '820'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '820'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '821'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '821'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '822'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '822'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '823'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '823'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '824'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '824'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '825'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '825'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '826'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '826'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '827'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '827'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '828'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '828'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '829'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '829'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '830'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '830'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '831'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '831'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '832'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '832'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '833'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '833'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '834'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '834'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '835'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '835'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '836'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '836'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '837'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '837'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '838'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '838'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '839'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '839'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '840'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '840'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '841'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '841'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '842'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '842'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '843'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '843'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '844'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '844'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '845'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '845'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '846'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '846'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '847'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '847'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '848'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '848'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '849'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '849'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '850'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '850'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '851'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '851'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '852'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '852'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '853'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '853'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '854'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '854'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '855'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '855'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '856'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '856'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '857'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '857'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '858'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '858'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '859'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '859'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '860'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '860'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '861'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '861'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '862'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '862'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '863'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '863'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '864'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '864'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '865'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '865'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '866'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '866'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '867'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '867'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '868'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '868'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '869'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '869'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '870'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '870'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '871'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '871'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '872'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '872'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '873'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '873'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '874'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '874'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '875'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '875'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '876'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '876'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '877'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '877'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '878'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '878'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '879'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '879'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '880'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '880'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '881'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '881'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '882'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '882'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '883'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '883'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '884'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '884'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '885'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '885'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '886'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '886'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '887'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '887'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '888'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '888'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '889'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '889'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '890'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '890'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '891'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '891'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '892'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '892'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '893'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '893'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '894'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '894'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '895'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '895'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '896'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '896'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '897'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '897'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '898'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '898'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '899'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '899'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '900'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '900'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '901'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '901'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '902'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '902'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '903'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '903'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '904'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '904'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '905'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '905'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '906'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '906'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '907'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '907'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '908'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '908'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '909'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '909'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '910'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '910'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '911'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '911'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '912'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '912'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '913'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '913'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '914'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '914'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '915'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '915'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '916'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '916'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '917'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '917'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '918'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '918'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '919'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '919'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '920'

UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '920'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '921'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '921'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '922'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '922'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '923'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '923'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '924'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '924'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '925'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '925'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '926'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '926'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '927'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '927'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '928'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '928'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '929'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '929'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '930'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '930'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '931'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '931'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '932'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '932'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '933'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '933'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '934'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '934'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '935'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '935'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '936'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '936'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '937'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '937'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '938'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '938'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '939'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '939'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '940'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '940'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '941'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '941'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '942'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '942'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '943'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '943'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '944'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '944'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '945'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '945'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '946'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '946'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '947'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '947'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '948'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '948'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '949'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '949'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '950'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '950'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '951'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '951'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '952'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '952'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '953'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '953'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '954'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '954'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '955'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '955'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '956'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '956'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '957'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '957'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '958'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '958'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '959'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '959'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '960'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '960'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '961'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '961'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '962'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '962'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '963'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '963'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '964'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '964'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '965'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '965'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '966'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '966'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '967'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '967'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '968'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '968'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '969'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '969'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '970'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '970'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '971'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '971'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '972'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '972'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '973'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '973'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '974'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '974'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '975'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '975'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '976'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '976'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '977'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '977'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '978'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '978'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '979'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '979'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '980'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '980'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '981'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '981'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '982'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '982'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '983'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '983'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '984'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '984'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '985'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '985'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '986'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '986'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '987'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '987'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '988'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '988'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '989'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '989'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '990'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '990'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '991'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '991'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '992'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '992'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '993'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '993'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '994'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '994'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '995'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '995'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '996'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '996'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '997'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '997'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '998'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '998'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '999'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '999'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1000'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1000'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1001'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1001'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1002'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1002'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1003'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1003'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1004'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1004'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1005'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1005'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1006'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1006'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1007'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1007'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1008'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1008'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1009'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1009'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1010'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1010'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1011'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1011'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1012'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1012'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1013'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1013'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1014'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1014'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1015'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1015'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1016'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1016'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1017'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1017'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1018'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1018'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1019'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1019'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1020'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1020'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1021'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1021'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1022'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1022'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1023'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1023'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1024'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1024'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1025'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1025'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1026'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1026'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1027'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1027'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1028'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1028'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1029'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1029'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1030'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1030'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1031'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1031'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1032'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1032'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1033'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1033'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1034'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1034'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1035'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1035'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1036'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1036'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1037'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1037'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1038'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1038'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1039'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1039'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1040'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1040'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1041'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1041'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1042'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1042'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1043'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1043'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1044'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1044'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1045'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1045'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1046'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1046'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1047'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1047'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1048'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1048'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1049'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1049'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1050'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1050'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1051'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1051'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1052'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1052'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1053'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1053'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1054'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1054'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1055'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1055'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1056'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1056'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1057'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1057'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1058'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1058'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1059'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1059'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1060'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1060'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1061'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1061'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1062'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1062'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1063'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1063'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1064'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1064'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1065'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1065'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1066'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1066'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1067'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1067'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1068'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1068'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1069'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1069'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1070'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1070'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1071'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1071'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1072'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1072'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1073'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1073'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1074'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1074'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1075'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1075'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1076'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1076'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1077'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1077'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1078'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1078'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1079'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1079'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1080'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1080'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1081'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1081'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1082'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1082'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1083'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1083'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1084'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1084'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1085'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1085'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1086'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1086'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1087'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1087'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1088'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1088'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1089'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1089'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1090'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1090'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1091'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1091'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1092'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1092'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1093'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1093'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1094'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1094'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1095'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1095'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1096'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1096'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1097'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1097'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1098'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1098'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1099'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1099'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1100'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1100'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1101'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1101'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1102'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1102'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1103'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1103'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1104'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1104'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1105'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1105'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1106'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1106'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1107'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1107'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1108'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1108'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1109'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1109'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1110'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1110'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1111'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1111'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1112'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1112'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1113'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1113'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1114'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1114'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1115'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1115'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1116'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1116'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1117'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1117'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1118'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1118'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1119'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1119'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1120'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1120'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1121'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1121'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1122'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1122'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1123'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1123'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1124'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1124'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1125'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1125'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1126'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1126'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1127'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1127'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1128'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1128'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1129'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1129'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1130'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1130'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1131'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1131'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1132'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1132'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1133'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1133'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1134'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1134'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1135'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1135'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1136'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1136'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1137'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1137'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1138'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1138'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1139'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1139'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1140'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1140'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1141'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1141'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1142'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1142'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1143'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1143'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1144'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1144'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1145'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1145'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1146'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1146'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1147'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1147'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1148'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1148'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1149'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1149'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1150'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1150'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1151'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1151'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1152'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1152'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1153'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1153'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1154'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1154'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1155'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1155'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1156'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1156'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1157'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1157'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1158'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1158'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1159'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1159'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1160'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1160'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1161'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1161'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1162'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1162'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1163'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1163'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1164'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1164'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1165'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1165'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1166'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1166'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1167'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1167'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1168'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1168'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1169'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1169'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1170'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1170'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1171'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1171'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1172'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1172'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1173'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1173'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1174'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1174'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1175'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1175'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1176'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1176'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1177'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1177'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1178'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1178'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1179'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1179'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1180'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1180'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1181'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1181'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1182'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1182'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1183'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1183'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1184'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1184'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1185'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1185'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1186'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1186'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1187'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1187'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1188'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1188'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1189'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1189'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1190'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1190'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1191'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1191'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1192'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1192'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1193'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1193'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1194'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1194'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1195'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1195'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1196'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1196'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1197'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1197'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1198'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1198'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1199'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1199'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1200'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1200'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1201'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1201'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1202'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1202'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1203'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1203'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1204'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1204'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1205'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1205'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1206'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1206'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1207'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1207'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1208'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1208'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1209'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1209'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1210'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1210'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1211'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1211'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1212'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1212'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1213'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1213'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1214'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1214'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1215'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1215'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1216'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1216'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1217'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1217'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1218'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1218'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1219'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1219'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1220'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1220'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1221'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1221'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1222'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1222'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1223'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1223'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1224'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1224'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1225'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1225'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1226'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1226'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1227'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1227'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1228'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1228'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1229'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1229'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1230'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1230'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1231'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1231'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1232'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1232'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1233'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1233'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1234'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1234'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1235'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1235'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1236'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1236'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1237'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1237'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1238'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1238'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1239'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1239'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1240'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1240'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1241'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1241'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1242'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1242'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1243'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1243'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1244'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1244'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1245'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1245'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1246'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1246'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1247'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1247'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1248'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1248'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1249'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1249'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1250'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1250'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1251'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1251'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1252'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1252'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1253'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1253'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1254'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1254'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1255'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1255'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1256'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1256'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1257'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1257'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1258'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1258'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1259'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1259'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1260'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1260'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1261'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1261'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1262'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1262'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1263'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1263'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1264'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1264'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1265'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1265'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1266'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1266'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1267'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1267'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1268'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1268'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1269'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1269'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1270'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1270'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1271'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1271'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1272'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1272'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1273'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1273'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1274'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1274'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1275'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1275'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1276'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1276'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1277'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1277'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1278'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1278'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1279'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1279'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1280'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1280'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1281'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1281'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1282'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1282'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1283'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1283'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1284'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1284'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1285'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1285'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1286'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1286'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1287'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1287'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1288'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1288'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1289'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1289'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1290'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1290'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1291'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1291'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1292'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1292'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1293'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1293'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1294'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1294'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1295'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1295'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1296'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1296'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1297'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1297'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1298'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1298'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1299'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1299'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1300'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1300'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1301'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1301'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1302'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1302'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1303'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1303'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1304'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1304'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1305'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1305'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1306'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1306'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1307'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1307'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1308'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1308'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1309'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1309'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1310'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1310'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1311'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1311'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1312'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1312'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1313'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1313'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1314'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1314'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1315'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1315'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1316'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1316'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1317'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1317'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1318'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1318'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1319'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1319'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1320'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1320'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1321'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1321'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1322'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1322'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1323'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1323'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1324'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1324'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1325'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1325'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1326'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1326'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1327'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1327'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1328'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1328'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1329'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1329'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1330'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1330'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1331'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1331'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1332'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1332'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1333'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1333'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1334'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1334'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1335'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1335'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1336'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1336'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1337'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1337'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1338'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1338'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1339'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1339'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1340'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1340'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1341'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1341'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1342'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1342'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1343'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1343'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1344'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1344'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1345'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1345'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1346'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1346'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1347'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1347'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1348'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1348'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1349'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1349'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1350'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1350'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1351'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1351'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1352'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1352'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1353'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1353'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1354'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1354'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1355'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1355'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1356'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1356'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1357'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1357'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1358'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1358'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1359'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1359'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1360'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1360'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1361'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1361'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1362'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1362'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1363'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1363'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1364'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1364'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1365'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1365'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1366'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1366'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1367'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1367'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1368'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1368'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1369'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1369'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1370'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1370'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1371'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1371'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1372'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1372'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1373'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1373'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1374'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1374'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1375'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1375'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1376'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1376'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1377'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1377'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1378'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1378'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1379'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1379'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1380'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1380'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1381'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1381'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1382'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1382'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1383'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1383'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1384'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1384'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1385'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1385'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1386'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1386'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1387'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1387'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1388'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1388'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1389'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1389'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1390'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1390'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1391'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1391'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1392'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1392'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1393'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1393'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1394'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1394'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1395'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1395'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1396'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1396'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1397'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1397'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1398'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1398'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1399'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1399'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1400'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1400'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1401'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1401'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1402'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1402'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1403'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1403'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1404'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1404'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1405'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1405'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1406'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1406'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1407'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1407'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1408'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1408'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1409'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1409'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1410'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1410'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1411'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1411'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1412'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1412'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1413'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1413'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1414'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1414'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1415'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1415'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1416'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1416'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1417'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1417'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1418'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1418'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1419'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1419'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1420'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1420'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1421'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1421'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1422'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1422'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1423'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1423'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1424'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1424'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1425'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1425'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1426'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1426'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1427'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1427'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1428'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1428'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1429'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1429'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1430'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1430'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1431'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1431'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1432'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1432'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1433'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1433'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1434'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1434'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1435'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1435'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1436'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1436'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1437'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1437'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1438'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1438'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1439'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1439'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1440'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1440'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1441'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1441'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1442'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1442'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1443'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1443'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1444'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1444'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1445'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1445'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1446'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1446'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1447'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1447'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1448'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1448'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1449'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1449'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1450'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1450'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1451'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1451'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1452'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1452'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1453'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1453'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1454'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1454'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1455'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1455'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1456'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1456'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1457'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1457'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1458'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1458'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1459'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1459'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1460'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1460'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1461'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1461'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1462'

UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1462'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1463'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1463'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1464'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1464'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1465'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1465'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1466'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1466'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1467'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1467'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1468'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1468'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1469'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1469'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1470'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1470'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1471'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1471'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1472'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1472'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1473'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1473'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1474'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1474'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1475'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1475'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1476'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1476'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1477'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1477'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1478'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1478'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1479'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1479'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1480'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1480'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1481'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1481'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1482'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1482'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1483'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1483'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1484'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1484'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1485'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1485'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1486'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1486'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1487'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1487'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1488'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1488'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1489'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1489'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1490'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1490'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1491'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1491'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1492'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1492'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1493'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1493'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1494'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1494'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1495'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1495'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1496'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1496'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1497'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1497'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1498'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1498'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1499'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1499'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1500'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1500'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1501'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1501'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1502'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1502'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1503'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1503'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1504'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1504'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1505'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1505'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1506'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1506'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1507'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1507'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1508'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1508'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1509'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1509'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1510'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1510'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1511'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1511'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1512'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1512'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1513'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1513'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1514'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1514'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1515'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1515'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1516'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1516'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1517'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1517'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1518'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1518'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1519'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1519'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1520'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1520'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1521'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1521'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1522'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1522'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1523'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1523'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1524'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1524'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1525'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1525'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1526'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1526'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1527'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1527'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1528'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1528'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1529'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1529'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1530'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1530'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1531'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1531'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1532'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1532'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1533'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1533'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1534'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1534'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1535'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1535'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1536'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1536'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1537'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1537'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1538'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1538'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1539'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1539'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1540'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1540'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1541'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1541'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1542'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1542'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1543'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1543'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1544'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1544'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1545'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1545'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1546'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1546'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1547'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1547'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1548'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1548'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1549'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1549'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1550'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1550'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1551'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1551'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1552'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1552'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1553'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1553'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1554'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1554'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1555'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1555'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1556'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1556'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1557'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1557'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1558'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1558'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1559'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1559'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1560'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1560'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1561'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1561'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1562'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1562'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1563'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1563'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1564'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1564'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1565'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1565'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1566'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1566'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1567'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1567'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1568'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1568'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1569'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1569'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1570'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1570'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1571'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1571'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1572'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1572'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1573'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1573'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1574'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1574'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1575'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1575'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1576'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1576'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1577'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1577'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1578'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1578'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1579'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1579'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1580'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1580'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1581'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1581'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1582'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1582'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1583'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1583'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1584'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1584'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1585'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1585'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1586'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1586'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1587'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1587'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1588'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1588'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1589'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1589'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1590'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1590'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1591'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1591'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1592'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1592'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1593'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1593'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1594'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1594'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1595'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1595'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1596'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1596'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1597'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1597'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1598'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1598'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1599'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1599'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1600'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1600'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1601'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1601'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1602'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1602'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1603'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1603'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1604'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1604'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1605'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1605'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1606'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1606'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1607'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1607'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1608'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1608'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1609'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1609'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1610'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1610'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1611'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1611'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1612'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1612'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1613'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1613'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1614'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1614'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1615'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1615'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1616'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1616'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1617'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1617'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1618'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1618'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1619'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1619'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1620'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1620'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1621'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1621'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1622'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1622'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1623'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1623'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1624'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1624'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1625'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1625'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1626'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1626'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1627'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1627'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1628'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1628'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1629'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1629'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1630'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1630'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1631'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1631'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1632'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1632'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1633'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1633'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1634'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1634'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1635'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1635'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1636'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1636'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1637'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1637'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1638'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1638'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1639'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1639'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1640'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1640'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1641'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1641'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1642'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1642'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1643'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1643'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1644'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1644'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1645'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1645'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1646'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1646'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1647'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1647'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1648'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1648'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1649'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1649'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1650'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1650'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1651'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1651'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1652'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1652'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1653'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1653'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1654'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1654'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1655'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1655'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1656'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1656'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1657'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1657'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1658'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1658'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1659'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1659'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1660'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1660'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1661'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1661'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1662'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1662'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1663'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1663'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1664'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1664'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1665'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1665'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1666'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1666'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1667'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1667'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1668'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1668'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1669'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1669'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1670'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1670'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1671'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1671'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1672'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1672'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1673'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1673'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1674'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1674'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1675'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1675'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1676'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1676'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1677'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1677'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1678'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1678'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1679'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1679'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1680'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1680'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1681'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1681'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1682'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1682'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1683'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1683'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1684'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1684'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1685'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1685'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1686'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1686'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1687'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1687'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1688'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1688'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1689'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1689'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1690'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1690'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1691'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1691'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1692'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1692'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1693'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1693'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1694'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1694'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1695'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1695'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1696'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1696'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1697'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1697'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1698'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1698'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1699'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1699'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1700'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1700'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1701'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1701'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1702'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1702'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1703'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1703'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1704'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1704'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1705'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1705'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1706'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1706'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1707'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1707'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1708'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1708'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1709'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1709'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1710'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1710'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1711'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1711'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1712'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1712'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1713'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1713'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1714'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1714'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1715'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1715'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1716'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1716'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1717'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1717'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1718'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1718'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1719'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1719'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1720'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1720'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1721'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1721'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1722'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1722'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1723'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1723'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1724'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1724'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1725'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1725'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1726'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1726'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1727'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1727'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1728'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1728'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1729'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1729'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1730'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1730'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1731'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1731'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1732'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1732'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1733'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1733'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1734'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1734'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1735'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1735'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1736'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1736'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1737'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1737'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1738'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1738'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1739'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1739'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1740'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1740'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1741'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1741'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1742'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1742'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1743'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1743'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1744'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1744'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1745'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1745'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1746'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1746'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1747'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1747'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1748'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1748'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1749'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1749'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1750'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1750'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1751'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1751'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1752'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1752'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1753'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1753'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1754'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1754'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1755'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1755'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1756'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1756'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1757'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1757'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1758'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1758'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1759'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1759'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1760'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1760'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1761'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1761'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1762'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1762'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1763'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1763'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1764'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1764'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1765'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1765'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1766'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1766'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1767'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1767'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1768'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1768'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1769'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1769'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1770'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1770'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1771'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1771'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1772'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1772'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1773'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1773'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1774'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1774'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1775'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1775'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1776'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1776'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1777'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1777'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1778'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1778'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1779'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1779'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1780'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1780'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1781'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1781'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1782'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1782'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1783'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1783'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1784'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1784'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1785'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1785'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1786'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1786'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1787'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1787'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1788'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1788'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1789'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1789'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1790'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1790'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1791'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1791'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1792'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1792'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1793'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1793'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1794'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1794'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1795'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1795'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1796'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1796'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1797'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1797'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1798'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1798'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1799'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1799'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1800'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1800'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1801'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1801'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1802'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1802'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1803'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1803'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1804'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1804'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1805'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1805'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1806'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1806'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1807'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1807'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1808'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1808'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1809'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1809'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1810'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1810'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1811'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1811'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1812'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1812'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1813'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1813'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1814'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1814'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1815'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1815'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1816'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1816'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1817'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1817'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1818'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1818'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1819'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1819'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1820'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1820'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1821'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1821'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1822'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1822'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1823'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1823'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1824'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1824'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1825'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1825'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1826'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1826'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1827'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1827'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1828'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1828'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1829'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1829'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1830'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1830'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1831'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1831'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1832'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1832'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1833'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1833'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1834'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1834'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1835'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1835'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1836'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1836'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1837'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1837'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1838'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1838'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1839'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1839'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1840'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1840'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1841'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1841'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1842'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1842'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1843'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1843'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1844'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1844'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1845'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1845'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1846'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1846'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1847'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1847'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1848'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1848'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1849'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1849'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1850'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1850'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1851'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1851'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1852'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1852'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1853'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1853'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1854'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1854'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1855'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1855'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1856'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1856'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1857'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1857'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1858'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1858'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1859'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1859'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1860'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1860'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1861'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1861'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1862'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1862'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1863'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1863'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1864'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1864'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1865'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1865'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1866'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1866'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1867'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1867'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1868'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1868'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1869'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1869'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1870'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1870'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1871'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1871'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1872'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1872'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1873'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1873'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1874'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1874'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1875'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1875'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1876'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1876'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1877'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1877'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1878'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1878'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1879'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1879'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1880'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1880'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1881'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1881'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1882'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1882'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1883'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1883'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1884'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1884'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1885'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1885'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1886'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1886'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1887'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1887'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1888'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1888'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1889'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1889'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1890'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1890'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1891'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1891'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1892'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1892'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1893'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1893'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1894'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1894'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1895'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1895'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1896'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1896'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1897'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1897'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1898'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1898'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1899'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1899'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1900'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1900'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1901'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1901'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1902'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1902'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1903'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1903'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1904'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1904'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1905'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1905'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1906'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1906'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1907'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1907'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1908'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1908'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1909'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1909'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1910'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1910'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1911'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1911'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1912'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1912'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1913'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1913'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1914'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1914'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1915'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1915'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1916'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1916'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1917'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1917'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1918'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1918'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1919'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1919'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1920'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1920'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1921'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1921'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1922'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1922'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1923'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1923'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1924'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1924'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1925'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1925'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1926'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1926'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1927'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1927'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1928'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1928'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1929'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1929'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1930'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1930'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1931'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1931'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1932'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1932'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1933'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1933'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1934'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1934'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1935'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1935'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1936'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1936'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1937'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1937'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1938'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1938'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1939'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1939'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1940'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1940'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1941'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1941'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1942'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1942'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1943'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1943'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1944'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1944'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1945'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1945'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1946'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1946'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1947'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1947'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1948'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1948'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1949'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1949'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1950'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1950'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1951'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1951'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1952'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1952'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1953'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1953'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1954'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1954'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1955'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1955'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1956'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1956'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1957'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1957'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1958'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1958'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1959'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1959'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1960'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1960'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1961'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1961'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1962'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1962'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1963'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1963'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1964'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1964'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1965'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1965'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1966'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1966'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1967'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1967'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1968'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1968'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1969'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1969'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1970'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1970'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1971'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1971'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1972'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1972'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1973'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1973'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1974'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1974'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1975'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1975'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1976'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1976'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1977'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1977'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1978'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1978'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1979'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1979'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1980'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1980'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1981'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1981'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1982'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1982'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1983'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1983'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1984'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1984'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1985'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1985'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1986'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1986'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1987'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1987'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1988'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1988'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1989'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1989'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1990'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1990'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1991'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1991'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1992'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1992'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1993'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1993'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1994'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1994'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1995'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1995'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1996'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1996'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1997'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1997'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1998'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1998'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '1999'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '1999'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2000'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2000'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2001'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2001'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2002'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2002'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2003'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2003'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2004'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2004'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2005'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2005'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2006'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2006'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2007'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2007'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2008'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2008'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2009'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2009'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2010'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2010'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2011'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2011'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2012'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2012'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2013'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2013'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2014'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2014'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2015'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2015'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2016'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2016'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2017'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2017'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2018'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2018'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2019'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2019'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2020'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2020'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2021'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2021'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2022'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2022'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2023'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2023'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2024'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2024'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2025'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2025'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2026'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2026'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2027'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2027'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2028'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2028'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2029'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2029'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2030'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2030'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2031'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2031'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2032'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2032'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2033'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2033'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2034'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2034'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2035'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2035'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2036'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2036'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2037'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2037'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2038'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2038'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2039'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2039'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2040'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2040'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2041'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2041'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2042'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2042'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2043'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2043'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2044'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2044'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2045'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2045'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2046'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2046'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2047'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2047'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2048'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2048'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2049'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2049'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2050'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2050'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2051'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2051'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2052'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2052'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2053'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2053'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2054'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2054'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2055'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2055'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2056'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2056'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2057'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2057'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2058'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2058'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2059'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2059'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2060'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2060'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2061'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2061'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2062'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2062'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2063'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2063'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2064'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2064'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2065'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2065'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2066'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2066'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2067'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2067'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2068'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2068'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2069'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2069'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2070'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2070'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2071'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2071'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2072'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2072'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2073'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2073'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2074'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2074'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2075'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2075'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2076'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2076'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2077'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2077'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2078'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2078'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2079'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2079'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2080'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2080'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2081'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2081'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2082'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2082'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2083'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2083'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2084'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2084'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2085'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2085'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2086'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2086'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2087'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2087'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2088'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2088'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2089'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2089'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2090'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2090'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2091'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2091'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2092'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2092'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2093'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2093'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2094'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2094'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2095'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2095'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2096'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2096'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2097'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2097'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2098'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2098'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2099'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2099'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2100'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2100'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2101'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2101'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2102'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2102'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2103'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2103'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2104'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2104'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2105'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2105'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2106'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2106'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2107'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2107'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2108'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2108'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2109'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2109'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2110'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2110'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2111'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2111'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2112'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2112'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2113'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2113'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2114'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2114'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2115'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2115'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2116'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2116'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2117'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2117'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2118'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2118'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2119'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2119'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2120'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2120'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2121'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2121'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2122'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2122'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2123'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2123'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2124'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2124'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2125'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2125'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2126'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2126'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2127'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2127'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2128'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2128'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2129'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2129'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2130'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2130'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2131'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2131'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2132'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2132'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2133'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2133'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2134'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2134'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2135'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2135'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2136'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2136'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2137'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2137'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2138'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2138'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2139'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2139'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2140'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2140'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2141'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2141'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2142'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2142'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2143'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2143'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2144'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2144'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2145'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2145'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2146'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2146'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2147'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2147'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2148'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2148'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2149'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2149'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2150'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2150'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2151'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2151'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2152'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2152'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2153'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2153'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2154'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2154'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2155'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2155'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2156'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2156'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2157'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2157'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2158'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2158'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2159'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2159'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2160'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2160'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2161'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2161'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2162'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2162'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2163'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2163'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2164'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2164'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2165'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2165'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2166'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2166'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2167'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2167'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2168'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2168'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2169'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2169'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2170'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2170'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2171'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2171'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2172'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2172'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2173'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2173'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2174'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2174'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2175'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2175'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2176'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2176'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2177'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2177'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2178'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2178'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2179'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2179'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2180'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2180'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2181'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2181'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2182'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2182'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2183'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2183'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2184'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2184'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2185'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2185'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2186'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2186'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2187'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2187'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2188'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2188'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2189'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2189'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2190'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2190'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2191'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2191'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2192'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2192'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2193'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2193'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2194'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2194'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2195'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2195'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2196'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2196'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2197'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2197'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2198'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2198'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2199'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2199'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2200'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2200'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2201'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2201'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2202'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2202'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2203'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2203'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2204'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2204'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2205'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2205'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2206'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2206'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2207'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2207'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2208'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2208'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2209'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2209'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2210'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2210'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2211'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2211'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2212'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2212'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2213'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2213'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2214'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2214'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2215'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2215'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2216'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2216'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2217'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2217'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2218'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2218'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2219'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2219'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2220'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2220'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2221'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2221'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2222'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2222'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2223'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2223'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2224'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2224'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2225'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2225'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2226'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2226'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2227'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2227'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2228'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2228'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2229'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2229'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2230'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2230'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2231'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2231'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2232'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2232'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2233'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2233'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2234'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2234'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2235'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2235'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2236'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2236'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2237'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2237'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2238'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2238'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2239'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2239'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2240'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2240'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2241'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2241'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2242'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2242'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2243'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2243'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2244'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2244'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2245'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2245'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2246'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2246'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2247'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2247'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2248'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2248'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2249'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2249'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2250'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2250'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2251'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2251'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2252'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2252'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2253'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2253'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2254'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2254'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2255'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2255'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2256'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2256'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2257'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2257'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2258'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2258'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2259'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2259'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2260'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2260'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2261'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2261'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2262'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2262'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2263'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2263'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2264'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2264'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2265'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2265'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2266'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2266'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2267'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2267'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2268'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2268'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2269'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2269'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2270'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2270'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2271'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2271'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2272'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2272'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2273'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2273'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2274'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2274'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2275'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2275'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2276'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2276'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2277'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2277'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2278'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2278'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2279'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2279'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2280'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2280'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2281'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2281'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2282'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2282'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2283'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2283'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2284'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2284'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2285'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2285'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2286'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2286'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2287'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2287'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2288'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2288'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2289'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2289'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2290'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2290'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2291'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2291'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2292'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2292'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2293'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2293'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2294'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2294'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2295'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2295'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2296'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2296'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2297'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2297'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2298'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2298'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2299'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2299'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2300'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2300'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2301'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2301'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2302'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2302'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2303'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2303'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2304'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2304'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2305'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2305'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2306'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2306'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2307'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2307'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2308'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2308'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2309'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2309'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2310'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2310'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2311'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2311'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2312'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2312'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2313'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2313'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2314'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2314'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2315'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2315'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2316'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2316'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2317'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2317'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2318'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2318'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2319'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2319'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2320'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2320'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2321'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2321'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2322'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2322'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2323'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2323'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2324'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2324'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2325'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2325'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2326'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2326'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2327'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2327'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2328'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2328'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2329'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2329'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2330'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2330'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2331'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2331'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2332'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2332'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2333'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2333'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2334'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2334'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2335'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2335'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2336'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2336'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2337'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2337'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2338'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2338'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2339'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2339'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2340'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2340'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2341'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2341'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2342'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2342'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2343'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2343'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2344'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2344'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2345'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2345'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2346'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2346'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2347'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2347'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2348'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2348'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2349'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2349'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2350'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2350'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2351'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2351'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2352'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2352'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2353'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2353'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2354'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2354'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2355'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2355'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2356'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2356'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2357'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2357'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2358'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2358'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2359'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2359'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2360'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2360'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2361'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2361'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2362'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2362'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2363'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2363'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2364'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2364'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2365'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2365'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2366'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2366'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2367'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2367'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2368'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2368'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2369'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2369'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2370'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2370'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2371'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2371'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2372'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2372'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2373'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2373'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2374'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2374'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2375'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2375'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2376'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2376'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2377'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2377'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2378'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2378'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2379'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2379'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2380'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2380'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2381'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2381'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2382'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2382'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2383'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2383'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2384'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2384'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2385'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2385'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2386'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2386'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2387'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2387'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2388'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2388'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2389'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2389'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2390'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2390'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2391'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2391'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2392'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2392'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2393'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2393'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2394'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2394'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2395'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2395'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2396'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2396'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2397'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2397'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2398'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2398'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2399'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2399'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2400'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2400'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2401'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2401'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2402'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2402'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2403'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2403'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2404'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2404'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2405'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2405'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2406'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2406'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2407'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2407'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2408'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2408'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2409'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2409'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2410'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2410'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2411'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2411'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2412'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2412'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2413'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2413'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2414'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2414'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2415'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2415'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2416'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2416'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2417'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2417'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2418'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2418'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2419'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2419'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2420'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2420'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2421'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2421'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2422'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2422'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2423'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2423'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2424'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2424'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2425'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2425'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2426'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2426'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2427'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2427'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2428'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2428'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2429'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2429'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2430'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2430'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2431'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2431'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2432'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2432'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2433'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2433'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2434'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2434'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2435'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2435'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2436'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2436'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2437'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2437'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2438'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2438'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2439'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2439'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2440'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2440'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2441'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2441'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2442'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2442'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2443'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2443'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2444'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2444'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2445'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2445'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2446'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2446'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2447'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2447'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2448'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2448'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2449'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2449'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2450'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2450'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2451'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2451'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2452'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2452'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2453'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2453'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2454'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2454'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2455'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2455'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2456'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2456'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2457'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2457'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2458'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2458'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2459'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2459'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2460'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2460'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2461'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2461'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2462'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2462'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2463'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2463'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2464'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2464'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2465'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2465'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2466'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2466'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2467'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2467'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2468'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2468'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2469'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2469'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2470'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2470'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2471'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2471'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2472'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2472'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2473'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2473'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2474'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2474'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2475'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2475'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2476'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2476'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2477'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2477'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2478'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2478'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2479'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2479'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2480'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2480'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2481'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2481'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2482'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2482'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2483'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2483'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2484'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2484'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2485'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2485'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2486'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2486'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2487'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2487'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2488'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2488'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2489'

UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2489'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2490'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2490'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2491'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2491'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2492'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2492'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2493'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2493'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2494'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2494'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2495'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2495'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2496'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2496'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2497'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2497'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2498'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2498'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2499'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2499'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2500'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2500'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2501'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2501'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2502'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2502'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2503'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2503'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2504'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2504'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2505'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2505'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2506'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2506'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2507'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2507'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2508'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2508'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2509'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2509'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2510'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2510'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2511'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2511'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2512'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2512'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2513'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2513'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2514'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2514'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2515'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2515'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2516'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2516'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2517'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2517'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2518'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2518'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2519'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2519'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2520'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2520'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2521'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2521'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2522'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2522'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2523'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2523'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2524'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2524'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2525'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2525'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2526'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2526'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2527'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2527'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2528'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2528'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2529'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2529'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2530'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2530'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2531'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2531'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2532'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2532'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2533'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2533'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2534'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2534'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2535'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2535'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2536'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2536'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2537'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2537'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2538'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2538'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2539'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2539'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2540'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2540'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2541'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2541'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2542'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2542'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2543'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2543'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2544'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2544'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2545'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2545'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2546'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2546'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2547'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2547'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2548'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2548'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2549'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2549'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2550'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2550'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2551'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2551'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2552'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2552'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2553'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2553'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2554'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2554'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2555'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2555'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2556'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2556'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2557'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2557'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2558'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2558'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2559'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2559'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2560'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2560'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2561'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2561'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2562'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2562'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2563'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2563'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2564'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2564'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2565'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2565'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2566'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2566'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2567'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2567'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2568'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2568'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2569'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2569'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2570'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2570'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2571'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2571'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2572'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2572'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2573'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2573'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2574'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2574'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2575'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2575'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2576'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2576'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2577'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2577'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2578'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2578'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2579'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2579'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2580'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2580'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2581'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2581'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2582'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2582'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2583'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2583'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2584'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2584'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2585'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2585'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2586'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2586'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2587'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2587'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2588'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2588'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2589'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2589'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2590'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2590'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2591'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2591'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2592'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2592'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2593'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2593'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2594'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2594'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2595'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2595'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2596'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2596'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2597'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2597'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2598'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2598'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2599'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2599'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2600'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2600'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2601'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2601'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2602'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2602'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2603'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2603'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2604'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2604'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2605'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2605'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2606'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2606'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2607'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2607'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2608'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2608'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2609'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2609'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2610'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2610'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2611'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2611'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2612'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2612'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2613'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2613'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2614'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2614'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2615'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2615'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2616'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2616'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2617'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2617'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2618'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2618'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2619'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2619'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2620'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2620'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2621'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2621'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2622'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2622'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2623'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2623'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2624'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2624'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2625'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2625'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2626'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2626'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2627'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2627'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2628'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2628'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2629'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2629'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2630'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2630'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2631'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2631'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2632'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2632'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2633'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2633'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2634'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2634'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2635'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2635'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2636'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2636'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2637'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2637'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2638'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2638'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2639'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2639'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2640'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2640'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2641'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2641'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2642'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2642'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2643'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2643'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2644'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2644'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2645'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2645'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2646'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2646'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2647'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2647'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2648'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2648'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2649'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2649'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2650'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2650'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2651'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2651'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2652'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2652'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2653'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2653'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2654'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2654'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2655'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2655'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2656'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2656'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2657'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2657'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2658'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2658'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2659'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2659'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2660'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2660'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2661'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2661'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2662'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2662'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2663'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2663'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2664'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2664'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2665'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2665'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2666'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2666'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2667'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2667'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2668'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2668'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2669'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2669'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2670'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2670'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2671'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2671'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2672'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2672'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2673'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2673'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2674'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2674'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2675'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2675'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2676'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2676'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2677'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2677'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2678'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2678'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2679'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2679'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2680'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2680'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2681'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2681'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2682'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2682'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2683'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2683'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2684'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2684'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2685'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2685'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2686'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2686'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2687'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2687'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2688'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2688'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2689'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2689'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2690'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2690'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2691'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2691'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2692'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2692'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2693'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2693'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2694'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2694'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2695'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2695'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2696'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2696'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2697'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2697'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2698'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2698'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2699'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2699'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2700'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2700'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2701'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2701'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2702'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2702'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2703'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2703'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2704'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2704'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2705'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2705'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2706'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2706'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2707'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2707'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2708'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2708'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2709'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2709'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2710'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2710'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2711'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2711'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2712'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2712'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2713'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2713'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2714'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2714'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2715'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2715'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2716'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2716'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2717'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2717'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2718'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2718'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2719'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2719'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2720'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2720'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2721'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2721'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2722'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2722'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2723'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2723'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2724'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2724'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2725'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2725'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2726'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2726'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2727'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2727'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2728'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2728'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2729'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2729'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2730'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2730'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2731'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2731'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2732'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2732'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2733'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2733'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2734'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2734'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2735'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2735'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2736'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2736'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2737'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2737'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2738'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2738'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2739'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2739'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2740'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2740'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2741'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2741'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2742'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2742'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2743'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2743'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2744'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2744'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2745'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2745'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2746'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2746'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2747'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2747'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2748'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2748'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2749'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2749'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2750'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2750'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2751'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2751'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2752'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2752'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2753'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2753'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2754'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2754'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2755'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2755'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2756'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2756'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2757'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2757'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2758'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2758'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2759'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2759'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2760'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2760'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2761'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2761'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2762'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2762'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2763'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2763'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2764'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2764'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2765'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2765'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2766'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2766'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2767'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2767'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2768'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2768'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2769'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2769'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2770'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2770'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2771'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2771'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2772'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2772'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2773'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2773'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2774'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2774'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2775'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2775'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2776'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2776'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2777'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2777'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2778'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2778'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2779'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2779'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2780'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2780'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2781'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2781'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2782'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2782'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2783'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2783'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2784'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2784'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2785'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2785'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2786'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2786'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2787'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2787'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2788'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2788'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2789'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2789'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2790'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2790'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2791'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2791'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2792'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2792'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2793'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2793'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2794'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2794'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2795'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2795'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2796'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2796'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2797'

UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2797'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2798'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2798'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2799'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2799'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2800'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2800'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2801'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2801'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2802'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2802'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2803'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2803'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2804'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2804'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2805'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2805'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2806'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2806'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2807'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2807'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2808'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2808'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2809'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2809'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2810'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2810'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2811'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2811'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2812'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2812'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2813'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2813'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2814'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2814'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2815'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2815'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2816'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2816'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2817'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2817'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2818'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2818'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2819'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2819'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2820'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2820'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2821'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2821'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2822'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2822'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2823'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2823'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2824'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2824'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2825'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2825'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2826'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2826'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2827'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2827'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2828'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2828'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2829'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2829'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2830'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2830'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2831'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2831'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2832'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2832'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2833'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2833'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2834'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2834'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2835'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2835'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2836'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2836'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2837'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2837'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2838'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2838'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2839'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2839'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2840'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2840'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2841'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2841'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2842'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2842'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2843'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2843'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2844'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2844'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2845'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2845'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2846'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2846'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2847'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2847'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2848'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2848'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2849'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2849'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2850'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2850'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2851'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2851'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2852'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2852'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2853'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2853'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2854'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2854'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2855'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2855'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2856'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2856'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2857'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2857'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2858'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2858'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2859'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2859'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2860'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2860'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2861'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2861'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2862'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2862'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2863'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2863'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2864'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2864'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2865'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2865'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2866'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2866'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2867'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2867'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2868'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2868'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2869'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2869'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2870'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2870'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2871'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2871'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2872'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2872'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2873'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2873'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2874'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2874'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2875'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2875'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2876'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2876'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2877'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2877'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2878'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2878'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2879'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2879'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2880'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2880'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2881'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2881'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2882'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2882'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2883'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2883'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2884'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2884'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2885'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2885'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2886'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2886'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2887'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2887'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2888'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2888'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2889'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2889'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2890'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2890'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2891'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2891'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2892'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2892'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2893'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2893'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2894'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2894'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2895'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2895'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2896'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2896'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2897'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2897'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2898'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2898'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2899'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2899'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2900'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2900'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2901'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2901'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2902'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2902'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2903'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2903'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2904'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2904'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2905'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2905'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2906'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2906'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2907'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2907'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2908'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2908'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2909'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2909'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2910'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2910'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2911'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2911'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2912'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2912'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2913'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2913'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2914'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2914'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2915'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2915'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2916'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2916'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2917'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2917'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2918'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2918'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2919'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2919'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2920'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2920'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2921'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2921'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2922'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2922'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2923'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2923'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2924'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2924'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2925'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2925'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2926'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2926'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2927'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2927'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2928'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2928'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2929'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2929'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2930'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2930'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2931'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2931'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2932'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2932'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2933'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2933'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2934'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2934'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2935'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2935'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2936'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2936'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2937'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2937'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2938'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2938'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2939'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2939'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2940'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2940'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2941'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2941'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2942'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2942'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2943'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2943'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2944'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2944'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2945'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2945'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2946'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2946'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2947'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2947'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2948'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2948'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2949'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2949'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2950'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2950'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2951'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2951'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2952'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2952'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2953'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2953'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2954'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2954'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2955'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2955'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2956'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2956'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2957'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2957'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2958'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2958'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2959'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2959'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2960'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2960'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2961'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2961'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2962'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2962'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2963'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2963'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2964'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2964'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2965'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2965'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2966'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2966'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2967'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2967'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2968'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2968'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2969'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2969'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2970'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2970'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2971'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2971'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2972'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2972'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2973'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2973'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2974'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2974'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2975'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2975'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2976'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2976'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2977'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2977'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2978'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2978'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2979'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2979'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2980'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2980'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2981'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2981'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2982'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2982'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2983'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2983'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2984'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2984'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2985'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2985'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2986'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2986'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2987'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2987'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2988'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2988'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2989'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2989'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2990'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2990'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2991'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2991'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2992'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2992'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2993'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2993'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2994'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2994'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2995'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2995'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2996'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2996'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2997'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2997'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2998'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2998'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '2999'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '2999'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3000'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3000'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3001'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3001'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3002'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3002'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3003'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3003'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3004'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3004'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3005'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3005'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3006'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3006'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3007'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3007'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3008'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3008'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3009'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3009'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3010'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3010'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3011'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3011'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3012'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3012'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3013'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3013'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3014'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3014'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3015'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3015'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3016'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3016'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3017'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3017'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3018'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3018'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3019'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3019'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3020'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3020'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3021'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3021'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3022'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3022'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3023'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3023'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3024'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3024'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3025'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3025'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3026'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3026'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3027'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3027'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3028'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3028'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3029'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3029'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3030'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3030'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3031'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3031'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3032'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3032'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3033'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3033'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3034'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3034'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3035'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3035'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3036'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3036'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3037'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3037'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3038'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3038'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3039'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3039'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3040'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3040'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3041'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3041'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3042'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3042'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3043'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3043'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3044'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3044'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3045'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3045'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3046'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3046'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3047'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3047'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3048'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3048'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3049'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3049'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3050'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3050'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3051'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3051'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3052'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3052'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3053'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3053'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3054'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3054'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3055'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3055'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3056'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3056'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3057'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3057'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3058'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3058'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3059'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3059'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3060'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3060'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3061'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3061'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3062'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3062'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3063'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3063'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3064'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3064'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3065'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3065'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3066'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3066'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3067'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3067'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3068'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3068'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3069'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3069'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3070'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3070'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3071'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3071'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3072'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3072'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3073'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3073'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3074'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3074'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3075'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3075'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3076'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3076'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3077'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3077'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3078'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3078'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3079'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3079'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3080'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3080'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3081'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3081'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3082'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3082'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3083'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3083'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3084'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3084'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3085'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3085'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3086'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3086'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3087'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3087'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3088'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3088'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3089'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3089'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3090'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3090'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3091'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3091'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3092'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3092'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3093'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3093'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3094'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3094'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3095'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3095'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3096'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3096'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3097'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3097'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3098'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3098'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3099'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3099'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3100'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3100'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3101'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3101'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3102'

UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3102'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3103'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3103'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3104'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3104'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3105'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3105'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3106'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3106'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3107'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3107'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3108'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3108'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3109'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3109'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3110'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3110'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3111'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3111'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3112'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3112'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3113'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3113'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3114'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3114'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3115'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3115'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3116'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3116'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3117'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3117'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3118'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3118'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3119'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3119'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3120'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3120'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3121'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3121'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3122'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3122'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3123'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3123'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3124'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3124'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3125'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3125'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3126'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3126'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3127'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3127'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3128'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3128'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3129'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3129'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3130'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3130'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3131'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3131'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3132'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3132'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3133'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3133'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3134'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3134'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3135'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3135'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3136'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3136'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3137'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3137'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3138'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3138'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3139'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3139'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3140'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3140'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3141'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3141'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3142'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3142'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3143'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3143'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3144'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3144'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3145'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3145'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3146'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3146'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3147'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3147'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3148'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3148'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3149'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3149'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3150'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3150'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3151'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3151'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3152'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3152'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3153'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3153'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3154'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3154'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3155'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3155'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3156'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3156'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3157'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3157'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3158'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3158'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3159'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3159'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3160'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3160'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3161'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3161'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3162'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3162'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3163'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3163'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3164'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3164'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3165'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3165'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3166'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3166'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3167'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3167'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3168'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3168'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3169'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3169'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3170'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3170'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3171'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3171'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3172'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3172'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3173'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3173'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3174'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3174'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3175'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3175'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3176'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3176'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3177'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3177'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3178'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3178'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3179'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3179'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3180'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3180'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3181'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3181'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3182'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3182'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3183'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3183'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3184'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3184'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3185'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3185'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3186'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3186'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3187'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3187'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3188'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3188'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3189'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3189'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3190'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3190'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3191'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3191'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3192'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3192'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3193'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3193'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3194'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3194'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3195'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3195'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3196'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3196'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3197'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3197'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3198'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3198'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3199'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3199'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3200'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3200'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3201'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3201'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3202'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3202'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3203'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3203'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3204'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3204'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3205'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3205'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3206'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3206'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3207'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3207'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3208'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3208'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3209'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3209'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3210'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3210'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3211'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3211'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3212'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3212'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3213'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3213'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3214'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3214'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3215'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3215'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3216'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3216'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3217'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3217'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3218'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3218'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3219'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3219'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3220'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3220'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3221'

UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3221'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3222'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3222'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3223'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3223'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3224'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3224'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3225'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3225'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3226'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3226'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3227'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3227'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3228'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3228'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3229'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3229'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3230'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3230'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3231'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3231'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3232'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3232'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3233'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3233'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3234'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3234'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3235'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3235'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3236'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3236'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3237'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3237'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3238'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3238'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3239'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3239'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3240'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3240'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3241'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3241'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3242'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3242'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3243'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3243'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3244'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3244'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3245'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3245'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3246'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3246'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3247'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3247'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3248'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3248'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3249'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3249'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3250'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3250'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3251'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3251'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3252'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3252'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3253'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3253'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3254'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3254'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3255'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3255'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3256'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3256'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3257'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3257'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3258'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3258'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3259'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3259'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3260'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3260'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3261'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3261'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3262'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3262'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3263'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3263'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3264'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3264'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3265'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3265'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3266'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3266'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3267'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3267'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3268'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3268'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3269'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3269'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3270'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3270'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3271'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3271'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3272'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3272'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3273'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3273'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3274'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3274'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3275'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3275'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3276'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3276'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3277'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3277'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3278'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3278'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3279'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3279'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3280'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3280'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3281'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3281'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3282'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3282'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3283'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3283'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3284'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3284'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3285'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3285'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3286'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3286'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3287'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3287'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3288'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3288'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3289'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3289'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3290'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3290'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3291'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3291'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3292'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3292'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3293'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3293'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3294'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3294'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3295'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3295'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3296'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3296'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3297'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3297'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3298'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3298'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3299'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3299'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3300'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3300'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3301'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3301'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3302'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3302'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3303'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3303'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3304'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3304'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3305'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3305'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3306'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3306'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3307'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3307'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3308'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3308'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3309'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3309'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3310'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3310'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3311'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3311'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3312'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3312'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3313'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3313'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3314'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3314'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3315'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3315'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3316'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3316'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3317'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3317'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3318'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3318'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3319'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3319'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3320'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3320'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3321'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3321'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3322'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3322'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3323'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3323'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3324'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3324'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3325'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3325'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3326'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3326'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3327'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3327'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3328'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3328'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3329'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3329'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3330'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3330'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3331'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3331'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3332'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3332'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3333'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3333'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3334'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3334'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3335'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3335'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3336'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3336'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3337'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3337'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3338'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3338'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3339'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3339'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3340'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3340'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3341'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3341'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3342'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3342'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3343'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3343'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3344'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3344'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3345'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3345'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3346'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3346'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3347'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3347'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3348'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3348'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3349'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3349'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3350'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3350'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3351'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3351'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3352'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3352'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3353'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3353'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3354'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3354'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3355'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3355'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3356'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3356'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3357'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3357'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3358'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3358'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3359'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3359'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3360'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3360'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3361'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3361'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3362'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3362'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3363'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3363'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3364'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3364'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3365'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3365'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3366'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3366'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3367'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3367'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3368'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3368'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3369'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3369'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3370'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3370'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3371'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3371'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3372'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3372'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3373'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3373'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3374'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3374'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3375'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3375'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3376'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3376'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3377'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3377'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3378'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3378'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3379'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3379'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3380'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3380'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3381'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3381'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3382'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3382'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3383'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3383'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3384'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3384'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3385'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3385'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3386'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3386'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3387'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3387'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3388'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3388'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3389'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3389'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3390'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3390'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3391'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3391'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3392'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3392'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3393'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3393'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3394'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3394'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3395'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3395'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3396'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3396'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3397'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3397'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3398'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3398'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3399'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3399'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3400'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3400'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3401'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3401'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3402'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3402'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3403'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3403'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3404'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3404'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3405'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3405'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3406'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3406'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3407'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3407'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3408'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3408'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3409'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3409'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3410'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3410'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3411'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3411'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3412'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3412'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3413'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3413'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3414'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3414'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3415'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3415'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3416'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3416'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3417'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3417'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3418'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3418'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3419'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3419'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3420'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3420'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3421'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3421'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3422'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3422'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3423'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3423'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3424'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3424'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3425'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3425'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3426'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3426'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3427'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3427'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3428'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3428'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3429'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3429'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3430'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3430'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3431'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3431'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3432'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3432'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3433'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3433'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3434'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3434'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3435'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3435'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3436'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3436'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3437'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3437'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3438'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3438'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3439'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3439'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3440'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3440'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3441'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3441'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3442'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3442'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3443'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3443'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3444'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3444'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3445'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3445'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3446'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3446'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3447'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3447'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3448'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3448'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3449'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3449'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3450'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3450'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3451'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3451'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3452'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3452'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3453'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3453'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3454'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3454'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3455'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3455'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3456'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3456'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3457'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3457'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3458'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3458'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3459'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3459'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3460'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3460'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3461'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3461'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3462'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3462'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3463'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3463'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3464'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3464'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3465'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3465'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3466'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3466'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3467'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3467'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3468'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3468'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3469'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3469'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3470'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3470'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3471'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3471'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3472'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3472'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3473'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3473'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3474'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3474'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3475'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3475'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3476'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3476'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3477'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3477'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3478'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3478'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3479'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3479'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3480'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3480'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3481'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3481'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3482'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3482'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3483'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3483'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3484'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3484'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3485'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3485'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3486'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3486'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3487'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3487'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3488'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3488'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3489'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3489'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3490'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3490'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3491'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3491'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3492'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3492'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3493'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3493'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3494'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3494'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3495'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3495'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3496'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3496'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3497'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3497'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3498'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3498'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3499'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3499'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3500'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3500'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3501'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3501'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3502'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3502'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3503'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3503'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3504'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3504'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3505'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3505'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3506'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3506'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3507'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3507'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3508'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3508'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3509'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3509'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3510'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3510'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3511'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3511'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3512'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3512'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3513'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3513'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3514'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3514'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3515'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3515'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3516'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3516'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3517'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3517'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3518'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3518'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3519'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3519'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3520'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3520'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3521'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3521'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3522'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3522'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3523'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3523'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3524'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3524'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3525'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3525'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3526'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3526'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3527'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3527'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3528'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3528'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3529'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3529'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3530'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3530'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3531'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3531'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3532'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3532'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3533'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3533'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3534'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3534'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3535'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3535'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3536'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3536'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3537'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3537'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3538'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3538'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3539'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3539'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3540'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3540'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3541'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3541'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3542'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3542'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3543'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3543'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3544'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3544'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3545'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3545'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3546'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3546'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3547'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3547'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3548'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3548'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3549'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3549'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3550'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3550'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3551'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3551'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3552'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3552'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3553'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3553'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3554'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3554'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3555'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3555'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3556'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3556'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3557'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3557'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3558'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3558'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3559'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3559'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3560'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3560'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3561'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3561'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3562'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3562'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3563'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3563'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3564'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3564'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3565'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3565'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3566'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3566'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3567'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3567'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3568'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3568'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3569'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3569'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3570'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3570'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3571'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3571'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3572'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3572'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3573'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3573'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3574'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3574'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3575'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3575'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3576'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3576'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3577'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3577'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3578'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3578'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3579'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3579'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3580'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3580'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3581'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3581'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3582'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3582'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3583'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3583'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3584'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3584'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3585'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3585'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3586'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3586'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3587'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3587'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3588'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3588'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3589'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3589'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3590'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3590'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3591'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3591'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3592'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3592'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3593'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3593'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3594'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3594'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3595'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3595'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3596'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3596'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3597'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3597'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3598'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3598'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3599'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3599'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3600'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3600'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3601'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3601'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3602'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3602'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3603'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3603'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3604'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3604'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3605'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3605'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3606'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3606'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3607'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3607'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3608'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3608'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3609'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3609'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3610'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3610'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3611'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3611'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3612'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3612'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3613'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3613'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3614'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3614'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3615'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3615'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3616'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3616'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3617'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3617'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3618'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3618'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3619'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3619'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3620'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3620'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3621'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3621'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3622'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3622'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3623'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3623'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3624'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3624'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3625'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3625'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3626'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3626'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3627'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3627'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3628'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3628'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3629'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3629'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3630'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3630'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3631'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3631'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3632'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3632'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3633'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3633'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3634'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3634'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3635'

UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3635'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3636'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3636'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3637'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3637'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3638'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3638'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3639'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3639'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3640'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3640'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3641'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3641'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3642'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3642'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3643'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3643'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3644'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3644'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3645'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3645'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3646'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3646'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3647'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3647'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3648'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3648'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3649'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3649'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3650'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3650'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3651'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3651'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3652'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3652'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3653'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3653'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3654'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3654'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3655'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3655'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3656'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3656'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3657'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3657'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3658'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3658'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3659'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3659'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3660'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3660'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3661'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3661'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3662'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3662'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3663'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3663'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3664'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3664'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3665'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3665'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3666'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3666'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3667'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3667'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3668'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3668'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3669'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3669'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3670'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3670'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3671'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3671'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3672'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3672'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3673'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3673'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3674'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3674'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3675'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3675'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3676'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3676'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3677'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3677'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3678'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3678'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3679'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3679'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3680'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3680'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3681'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3681'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3682'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3682'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3683'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3683'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3684'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3684'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3685'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3685'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3686'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3686'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3687'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3687'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3688'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3688'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3689'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3689'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3690'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3690'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3691'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3691'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3692'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3692'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3693'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3693'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3694'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3694'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3695'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3695'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3696'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3696'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3697'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3697'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3698'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3698'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3699'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3699'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3700'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3700'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3701'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3701'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3702'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3702'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3703'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3703'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3704'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3704'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3705'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3705'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3706'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3706'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3707'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3707'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3708'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3708'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3709'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3709'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3710'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3710'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3711'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3711'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3712'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3712'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3713'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3713'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3714'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3714'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3715'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3715'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3716'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3716'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3717'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3717'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3718'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3718'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3719'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3719'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3720'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3720'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3721'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3721'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3722'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3722'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3723'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3723'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3724'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3724'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3725'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3725'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3726'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3726'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3727'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3727'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3728'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3728'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3729'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3729'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3730'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3730'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3731'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3731'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3732'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3732'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3733'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3733'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3734'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3734'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3735'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3735'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3736'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3736'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3737'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3737'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3738'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3738'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3739'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3739'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3740'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3740'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3741'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3741'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3742'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3742'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3743'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3743'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3744'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3744'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3745'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3745'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3746'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3746'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3747'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3747'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3748'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3748'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3749'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3749'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3750'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3750'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3751'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3751'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3752'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3752'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3753'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3753'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3754'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3754'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3755'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3755'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3756'

UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3756'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3757'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3757'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3758'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3758'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3759'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3759'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3760'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3760'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3761'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3761'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3762'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3762'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3763'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3763'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3764'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3764'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3765'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3765'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3766'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3766'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3767'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3767'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3768'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3768'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3769'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3769'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3770'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3770'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3771'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3771'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3772'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3772'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3773'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3773'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3774'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3774'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3775'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3775'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3776'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3776'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3777'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3777'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3778'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3778'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3779'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3779'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3780'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3780'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3781'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3781'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3782'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3782'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3783'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3783'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3784'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3784'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3785'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3785'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3786'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3786'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3787'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3787'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3788'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3788'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3789'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3789'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3790'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3790'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3791'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3791'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3792'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3792'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3793'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3793'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3794'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3794'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3795'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3795'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3796'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3796'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3797'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3797'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3798'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3798'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3799'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3799'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3800'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3800'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3801'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3801'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3802'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3802'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3803'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3803'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3804'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3804'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3805'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3805'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3806'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3806'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3807'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3807'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3808'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3808'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3809'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3809'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3810'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3810'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3811'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3811'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3812'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3812'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3813'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3813'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3814'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3814'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3815'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3815'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3816'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3816'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3817'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3817'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3818'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3818'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3819'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3819'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3820'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3820'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3821'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3821'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3822'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3822'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3823'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3823'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3824'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3824'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3825'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3825'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3826'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3826'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3827'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3827'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3828'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3828'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3829'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3829'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3830'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3830'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3831'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3831'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3832'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3832'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3833'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3833'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3834'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3834'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3835'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3835'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3836'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3836'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3837'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3837'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3838'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3838'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3839'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3839'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3840'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3840'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3841'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3841'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3842'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3842'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3843'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3843'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3844'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3844'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3845'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3845'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3846'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3846'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3847'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3847'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3848'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3848'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3849'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3849'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3850'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3850'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3851'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3851'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3852'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3852'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3853'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3853'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3854'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3854'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3855'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3855'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3856'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3856'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3857'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3857'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3858'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3858'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3859'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3859'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3860'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3860'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3861'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3861'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3862'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3862'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3863'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3863'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3864'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3864'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3865'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3865'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3866'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3866'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3867'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3867'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3868'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3868'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3869'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3869'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3870'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3870'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3871'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3871'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3872'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3872'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3873'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3873'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3874'

UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3874'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3875'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3875'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3876'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3876'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3877'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3877'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3878'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3878'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3879'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3879'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3880'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3880'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3881'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3881'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3882'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3882'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3883'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3883'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3884'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3884'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3885'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3885'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3886'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3886'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3887'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3887'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3888'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3888'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3889'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3889'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3890'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3890'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3891'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3891'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3892'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3892'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3893'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3893'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3894'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3894'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3895'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3895'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3896'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3896'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3897'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3897'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3898'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3898'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3899'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3899'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3900'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3900'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3901'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3901'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3902'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3902'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3903'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3903'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3904'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3904'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3905'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3905'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3906'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3906'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3907'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3907'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3908'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3908'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3909'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3909'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3910'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3910'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3911'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3911'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3912'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3912'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3913'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3913'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3914'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3914'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3915'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3915'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3916'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3916'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3917'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3917'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3918'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3918'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3919'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3919'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3920'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3920'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3921'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3921'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3922'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3922'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3923'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3923'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3924'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3924'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3925'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3925'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3926'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3926'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3927'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3927'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3928'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3928'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3929'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3929'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3930'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3930'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3931'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3931'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3932'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3932'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3933'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3933'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3934'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3934'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3935'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3935'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3936'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3936'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3937'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3937'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3938'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3938'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3939'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3939'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3940'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3940'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3941'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3941'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3942'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3942'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3943'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3943'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3944'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3944'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3945'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3945'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3946'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3946'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3947'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3947'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3948'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3948'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3949'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3949'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3950'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3950'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3951'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3951'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3952'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3952'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3953'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3953'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3954'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3954'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3955'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3955'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3956'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3956'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3957'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3957'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3958'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3958'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3959'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3959'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3960'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3960'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3961'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3961'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3962'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3962'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3963'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3963'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3964'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3964'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3965'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3965'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3966'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3966'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3967'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3967'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3968'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3968'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3969'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3969'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3970'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3970'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3971'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3971'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3972'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3972'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3973'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3973'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3974'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3974'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3975'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3975'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3976'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3976'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3977'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3977'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3978'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3978'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3979'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3979'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3980'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3980'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3981'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3981'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3982'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3982'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3983'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3983'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3984'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3984'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3985'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3985'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3986'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3986'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3987'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3987'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3988'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3988'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3989'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3989'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3990'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3990'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3991'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3991'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3992'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3992'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3993'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3993'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3994'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3994'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3995'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3995'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3996'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3996'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3997'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3997'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3998'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3998'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '3999'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '3999'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4000'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4000'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4001'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4001'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4002'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4002'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4003'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4003'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4004'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4004'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4005'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4005'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4006'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4006'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4007'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4007'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4008'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4008'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4009'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4009'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4010'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4010'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4011'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4011'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4012'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4012'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4013'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4013'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4014'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4014'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4015'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4015'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4016'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4016'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4017'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4017'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4018'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4018'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4019'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4019'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4020'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4020'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4021'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4021'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4022'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4022'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4023'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4023'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4024'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4024'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4025'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4025'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4026'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4026'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4027'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4027'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4028'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4028'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4029'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4029'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4030'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4030'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4031'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4031'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4032'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4032'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4033'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4033'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4034'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4034'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4035'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4035'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4036'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4036'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4037'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4037'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4038'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4038'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4039'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4039'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4040'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4040'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4041'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4041'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4042'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4042'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4043'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4043'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4044'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4044'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4045'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4045'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4046'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4046'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4047'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4047'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4048'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4048'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4049'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4049'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4050'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4050'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4051'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4051'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4052'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4052'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4053'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4053'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4054'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4054'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4055'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4055'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4056'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4056'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4057'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4057'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4058'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4058'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4059'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4059'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4060'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4060'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4061'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4061'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4062'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4062'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4063'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4063'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4064'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4064'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4065'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4065'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4066'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4066'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4067'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4067'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4068'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4068'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4069'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4069'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4070'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4070'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4071'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4071'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4072'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4072'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4073'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4073'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4074'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4074'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4075'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4075'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4076'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4076'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4077'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4077'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4078'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4078'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4079'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4079'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4080'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4080'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4081'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4081'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4082'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4082'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4083'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4083'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4084'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4084'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4085'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4085'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4086'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4086'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4087'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4087'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4088'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4088'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4089'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4089'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4090'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4090'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4091'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4091'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4092'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4092'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4093'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4093'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4094'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4094'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4095'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4095'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4096'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4096'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4097'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4097'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4098'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4098'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4099'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4099'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4100'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4100'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4101'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4101'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4102'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4102'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4103'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4103'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4104'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4104'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4105'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4105'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4106'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4106'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4107'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4107'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4108'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4108'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4109'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4109'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4110'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4110'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4111'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4111'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4112'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4112'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4113'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4113'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4114'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4114'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4115'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4115'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4116'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4116'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4117'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4117'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4118'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4118'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4119'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4119'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4120'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4120'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4121'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4121'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4122'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4122'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4123'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4123'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4124'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4124'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4125'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4125'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4126'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4126'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4127'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4127'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4128'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4128'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4129'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4129'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4130'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4130'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4131'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4131'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4132'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4132'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4133'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4133'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4134'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4134'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4135'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4135'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4136'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4136'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4137'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4137'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4138'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4138'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4139'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4139'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4140'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4140'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4141'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4141'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4142'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4142'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4143'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4143'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4144'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4144'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4145'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4145'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4146'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4146'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4147'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4147'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4148'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4148'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4149'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4149'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4150'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4150'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4151'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4151'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4152'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4152'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4153'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4153'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4154'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4154'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4155'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4155'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4156'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4156'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4157'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4157'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4158'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4158'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4159'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4159'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4160'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4160'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4161'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4161'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4162'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4162'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4163'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4163'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4164'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4164'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4165'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4165'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4166'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4166'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4167'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4167'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4168'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4168'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4169'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4169'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4170'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4170'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4171'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4171'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4172'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4172'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4173'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4173'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4174'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4174'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4175'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4175'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4176'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4176'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4177'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4177'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4178'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4178'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4179'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4179'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4180'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4180'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4181'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4181'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4182'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4182'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4183'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4183'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4184'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4184'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4185'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4185'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4186'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4186'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4187'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4187'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4188'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4188'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4189'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4189'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4190'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4190'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4191'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4191'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4192'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4192'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4193'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4193'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4194'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4194'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4195'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4195'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4196'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4196'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4197'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4197'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4198'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4198'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4199'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4199'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4200'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4200'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4201'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4201'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4202'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4202'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4203'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4203'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4204'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4204'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4205'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4205'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4206'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4206'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4207'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4207'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4208'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4208'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4209'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4209'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4210'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4210'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4211'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4211'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4212'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4212'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4213'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4213'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4214'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4214'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4215'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4215'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4216'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4216'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4217'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4217'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4218'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4218'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4219'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4219'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4220'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4220'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4221'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4221'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4222'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4222'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4223'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4223'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4224'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4224'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4225'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4225'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4226'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4226'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4227'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4227'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4228'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4228'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4229'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4229'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4230'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4230'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4231'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4231'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4232'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4232'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4233'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4233'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4234'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4234'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4235'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4235'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4236'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4236'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4237'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4237'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4238'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4238'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4239'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4239'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4240'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4240'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4241'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4241'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4242'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4242'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4243'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4243'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4244'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4244'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4245'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4245'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4246'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4246'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4247'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4247'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4248'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4248'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4249'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4249'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4250'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4250'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4251'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4251'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4252'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4252'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4253'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4253'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4254'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4254'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4255'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4255'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4256'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4256'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4257'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4257'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4258'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4258'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4259'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4259'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4260'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4260'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4261'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4261'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4262'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4262'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4263'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4263'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4264'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4264'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4265'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4265'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4266'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4266'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4267'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4267'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4268'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4268'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4269'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4269'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4270'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4270'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4271'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4271'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4272'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4272'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4273'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4273'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4274'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4274'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4275'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4275'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4276'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4276'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4277'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4277'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4278'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4278'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4279'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4279'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4280'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4280'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4281'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4281'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4282'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4282'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4283'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4283'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4284'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4284'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4285'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4285'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4286'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4286'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4287'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4287'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4288'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4288'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4289'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4289'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4290'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4290'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4291'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4291'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4292'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4292'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4293'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4293'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4294'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4294'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4295'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4295'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4296'

UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4296'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4297'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4297'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4298'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4298'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4299'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4299'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4300'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4300'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4301'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4301'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4302'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4302'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4303'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4303'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4304'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4304'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4305'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4305'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4306'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4306'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4307'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4307'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4308'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4308'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4309'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4309'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4310'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4310'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4311'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4311'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4312'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4312'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4313'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4313'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4314'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4314'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4315'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4315'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4316'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4316'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4317'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4317'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4318'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4318'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4319'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4319'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4320'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4320'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4321'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4321'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4322'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4322'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4323'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4323'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4324'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4324'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4325'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4325'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4326'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4326'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4327'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4327'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4328'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4328'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4329'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4329'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4330'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4330'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4331'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4331'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4332'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4332'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4333'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4333'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4334'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4334'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4335'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4335'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4336'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4336'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4337'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4337'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4338'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4338'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4339'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4339'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4340'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4340'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4341'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4341'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4342'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4342'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4343'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4343'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4344'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4344'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4345'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4345'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4346'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4346'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4347'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4347'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4348'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4348'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4349'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4349'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4350'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4350'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4351'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4351'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4352'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4352'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4353'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4353'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4354'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4354'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4355'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4355'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4356'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4356'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4357'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4357'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4358'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4358'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4359'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4359'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4360'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4360'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4361'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4361'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4362'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4362'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4363'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4363'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4364'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4364'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4365'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4365'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4366'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4366'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4367'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4367'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4368'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4368'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4369'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4369'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4370'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4370'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4371'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4371'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4372'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4372'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4373'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4373'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4374'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4374'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4375'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4375'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4376'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4376'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4377'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4377'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4378'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4378'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4379'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4379'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4380'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4380'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4381'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4381'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4382'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4382'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4383'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4383'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4384'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4384'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4385'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4385'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4386'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4386'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4387'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4387'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4388'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4388'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4389'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4389'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4390'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4390'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4391'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4391'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4392'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4392'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4393'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4393'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4394'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4394'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4395'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4395'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4396'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4396'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4397'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4397'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4398'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4398'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4399'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4399'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4400'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4400'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4401'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4401'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4402'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4402'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4403'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4403'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4404'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4404'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4405'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4405'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4406'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4406'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4407'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4407'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4408'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4408'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4409'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4409'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4410'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4410'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4411'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4411'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4412'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4412'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4413'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4413'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4414'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4414'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4415'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4415'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4416'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4416'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4417'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4417'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4418'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4418'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4419'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4419'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4420'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4420'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4421'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4421'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4422'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4422'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4423'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4423'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4424'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4424'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4425'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4425'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4426'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4426'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4427'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4427'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4428'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4428'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4429'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4429'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4430'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4430'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4431'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4431'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4432'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4432'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4433'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4433'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4434'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4434'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4435'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4435'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4436'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4436'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4437'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4437'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4438'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4438'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4439'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4439'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4440'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4440'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4441'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4441'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4442'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4442'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4443'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4443'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4444'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4444'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4445'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4445'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4446'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4446'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4447'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4447'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4448'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4448'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4449'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4449'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4450'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4450'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4451'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4451'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4452'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4452'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4453'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4453'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4454'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4454'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4455'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4455'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4456'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4456'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4457'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4457'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4458'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4458'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4459'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4459'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4460'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4460'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4461'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4461'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4462'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4462'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4463'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4463'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4464'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4464'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4465'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4465'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4466'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4466'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4467'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4467'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4468'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4468'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4469'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4469'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4470'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4470'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4471'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4471'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4472'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4472'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4473'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4473'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4474'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4474'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4475'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4475'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4476'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4476'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4477'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4477'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4478'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4478'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4479'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4479'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4480'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4480'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4481'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4481'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4482'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4482'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4483'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4483'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4484'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4484'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4485'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4485'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4486'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4486'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4487'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4487'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4488'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4488'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4489'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4489'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4490'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4490'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4491'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4491'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4492'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4492'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4493'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4493'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4494'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4494'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4495'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4495'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4496'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4496'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4497'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4497'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4498'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4498'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4499'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4499'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4500'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4500'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4501'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4501'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4502'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4502'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4503'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4503'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4504'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4504'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4505'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4505'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4506'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4506'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4507'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4507'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4508'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4508'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4509'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4509'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4510'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4510'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4511'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4511'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4512'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4512'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4513'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4513'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4514'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4514'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4515'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4515'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4516'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4516'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4517'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4517'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4518'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4518'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4519'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4519'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4520'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4520'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4521'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4521'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4522'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4522'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4523'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4523'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4524'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4524'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4525'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4525'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4526'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4526'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4527'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4527'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4528'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4528'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4529'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4529'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4530'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4530'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4531'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4531'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4532'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4532'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4533'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4533'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4534'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4534'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4535'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4535'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4536'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4536'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4537'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4537'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4538'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4538'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4539'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4539'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4540'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4540'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4541'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4541'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4542'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4542'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4543'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4543'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4544'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4544'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4545'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4545'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4546'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4546'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4547'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4547'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4548'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4548'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4549'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4549'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4550'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4550'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4551'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4551'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4552'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4552'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4553'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4553'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4554'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4554'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4555'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4555'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4556'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4556'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4557'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4557'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4558'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4558'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4559'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4559'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4560'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4560'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4561'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4561'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4562'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4562'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4563'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4563'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4564'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4564'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4565'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4565'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4566'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4566'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4567'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4567'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4568'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4568'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4569'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4569'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4570'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4570'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4571'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4571'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4572'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4572'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4573'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4573'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4574'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4574'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4575'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4575'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4576'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4576'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4577'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4577'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4578'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4578'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4579'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4579'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4580'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4580'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4581'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4581'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4582'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4582'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4583'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4583'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4584'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4584'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4585'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4585'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4586'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4586'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4587'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4587'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4588'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4588'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4589'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4589'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4590'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4590'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4591'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4591'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4592'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4592'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4593'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4593'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4594'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4594'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4595'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4595'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4596'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4596'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4597'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4597'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4598'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4598'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4599'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4599'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4600'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4600'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4601'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4601'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4602'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4602'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4603'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4603'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4604'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4604'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4605'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4605'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4606'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4606'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4607'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4607'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4608'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4608'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4609'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4609'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4610'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4610'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4611'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4611'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4612'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4612'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4613'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4613'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4614'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4614'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4615'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4615'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4616'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4616'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4617'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4617'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4618'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4618'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4619'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4619'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4620'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4620'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4621'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4621'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4622'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4622'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4623'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4623'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4624'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4624'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4625'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4625'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4626'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4626'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4627'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4627'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4628'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4628'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4629'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4629'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4630'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4630'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4631'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4631'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4632'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4632'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4633'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4633'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4634'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4634'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4635'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4635'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4636'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4636'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4637'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4637'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4638'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4638'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4639'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4639'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4640'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4640'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4641'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4641'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4642'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4642'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4643'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4643'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4644'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4644'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4645'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4645'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4646'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4646'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4647'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4647'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4648'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4648'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4649'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4649'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4650'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4650'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4651'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4651'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4652'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4652'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4653'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4653'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4654'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4654'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4655'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4655'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4656'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4656'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4657'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4657'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4658'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4658'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4659'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4659'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4660'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4660'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4661'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4661'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4662'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4662'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4663'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4663'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4664'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4664'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4665'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4665'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4666'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4666'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4667'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4667'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4668'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4668'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4669'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4669'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4670'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4670'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4671'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4671'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4672'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4672'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4673'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4673'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4674'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4674'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4675'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4675'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4676'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4676'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4677'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4677'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4678'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4678'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4679'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4679'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4680'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4680'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4681'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4681'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4682'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4682'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4683'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4683'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4684'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4684'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4685'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4685'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4686'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4686'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4687'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4687'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4688'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4688'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4689'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4689'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4690'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4690'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4691'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4691'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4692'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4692'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4693'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4693'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4694'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4694'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4695'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4695'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4696'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4696'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4697'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4697'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4698'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4698'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4699'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4699'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4700'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4700'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4701'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4701'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4702'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4702'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4703'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4703'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4704'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4704'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4705'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4705'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4706'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4706'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4707'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4707'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4708'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4708'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4709'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4709'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4710'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4710'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4711'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4711'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4712'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4712'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4713'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4713'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4714'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4714'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4715'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4715'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4716'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4716'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4717'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4717'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4718'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4718'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4719'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4719'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4720'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4720'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4721'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4721'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4722'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4722'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4723'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4723'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4724'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4724'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4725'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4725'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4726'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4726'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4727'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4727'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4728'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4728'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4729'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4729'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4730'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4730'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4731'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4731'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4732'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4732'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4733'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4733'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4734'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4734'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4735'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4735'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4736'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4736'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4737'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4737'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4738'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4738'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4739'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4739'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4740'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4740'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4741'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4741'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4742'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4742'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4743'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4743'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4744'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4744'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4745'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4745'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4746'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4746'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4747'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4747'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4748'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4748'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4749'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4749'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4750'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4750'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4751'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4751'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4752'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4752'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4753'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4753'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4754'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4754'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4755'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4755'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4756'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4756'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4757'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4757'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4758'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4758'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4759'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4759'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4760'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4760'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4761'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4761'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4762'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4762'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4763'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4763'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4764'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4764'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4765'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4765'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4766'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4766'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4767'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4767'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4768'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4768'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4769'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4769'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4770'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4770'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4771'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4771'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4772'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4772'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4773'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4773'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4774'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4774'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4775'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4775'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4776'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4776'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4777'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4777'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4778'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4778'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4779'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4779'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4780'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4780'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4781'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4781'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4782'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4782'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4783'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4783'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4784'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4784'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4785'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4785'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4786'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4786'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4787'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4787'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4788'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4788'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4789'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4789'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4790'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4790'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4791'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4791'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4792'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4792'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4793'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4793'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4794'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4794'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4795'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4795'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4796'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4796'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4797'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4797'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4798'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4798'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4799'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4799'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4800'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4800'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4801'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4801'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4802'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4802'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4803'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4803'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4804'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4804'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4805'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4805'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4806'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4806'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4807'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4807'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4808'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4808'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4809'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4809'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4810'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4810'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4811'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4811'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4812'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4812'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4813'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4813'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4814'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4814'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4815'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4815'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4816'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4816'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4817'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4817'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4818'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4818'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4819'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4819'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4820'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4820'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4821'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4821'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4822'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4822'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4823'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4823'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4824'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4824'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4825'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4825'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4826'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4826'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4827'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4827'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4828'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4828'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4829'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4829'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4830'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4830'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4831'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4831'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4832'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4832'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4833'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4833'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4834'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4834'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4835'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4835'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4836'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4836'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4837'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4837'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4838'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4838'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4839'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4839'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4840'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4840'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4841'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4841'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4842'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4842'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4843'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4843'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4844'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4844'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4845'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4845'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4846'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4846'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4847'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4847'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4848'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4848'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4849'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4849'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4850'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4850'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4851'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4851'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4852'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4852'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4853'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4853'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4854'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4854'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4855'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4855'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4856'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4856'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4857'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4857'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4858'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4858'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4859'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4859'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4860'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4860'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4861'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4861'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4862'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4862'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4863'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4863'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4864'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4864'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4865'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4865'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4866'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4866'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4867'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4867'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4868'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4868'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4869'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4869'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4870'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4870'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4871'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4871'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4872'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4872'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4873'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4873'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4874'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4874'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4875'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4875'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4876'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4876'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4877'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4877'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4878'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4878'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4879'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4879'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4880'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4880'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4881'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4881'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4882'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4882'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4883'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4883'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4884'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4884'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4885'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4885'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4886'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4886'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4887'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4887'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4888'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4888'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4889'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4889'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4890'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4890'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4891'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4891'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4892'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4892'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4893'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4893'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4894'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4894'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4895'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4895'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4896'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4896'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4897'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4897'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4898'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4898'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4899'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4899'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4900'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4900'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4901'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4901'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4902'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4902'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4903'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4903'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4904'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4904'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4905'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4905'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4906'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4906'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4907'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4907'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4908'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4908'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4909'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4909'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4910'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4910'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4911'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4911'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4912'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4912'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4913'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4913'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4914'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4914'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4915'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4915'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4916'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4916'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4917'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4917'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4918'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4918'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4919'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4919'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4920'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4920'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4921'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4921'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4922'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4922'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4923'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4923'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4924'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4924'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4925'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4925'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4926'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4926'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4927'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4927'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4928'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4928'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4929'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4929'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4930'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4930'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4931'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4931'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4932'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4932'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4933'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4933'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4934'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4934'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4935'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4935'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4936'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4936'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4937'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4937'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4938'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4938'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4939'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4939'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4940'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4940'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4941'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4941'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4942'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4942'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4943'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4943'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4944'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4944'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4945'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4945'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4946'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4946'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4947'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4947'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4948'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4948'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4949'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4949'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4950'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4950'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4951'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4951'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4952'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4952'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4953'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4953'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4954'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4954'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4955'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4955'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4956'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4956'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4957'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4957'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4958'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4958'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4959'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4959'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4960'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4960'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4961'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4961'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4962'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4962'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4963'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4963'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4964'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4964'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4965'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4965'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4966'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4966'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4967'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4967'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4968'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4968'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4969'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4969'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4970'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4970'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4971'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4971'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4972'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4972'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4973'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4973'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4974'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4974'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4975'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4975'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4976'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4976'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4977'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4977'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4978'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4978'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4979'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4979'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4980'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4980'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4981'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4981'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4982'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4982'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4983'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4983'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4984'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4984'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4985'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4985'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4986'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4986'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4987'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4987'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4988'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4988'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4989'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4989'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4990'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4990'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4991'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4991'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4992'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4992'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4993'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4993'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4994'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4994'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4995'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4995'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4996'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4996'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4997'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4997'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4998'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4998'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '4999'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '4999'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5000'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5000'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5001'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5001'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5002'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5002'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5003'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5003'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5004'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5004'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5005'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5005'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5006'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5006'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5007'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5007'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5008'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5008'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5009'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5009'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5010'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5010'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5011'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5011'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5012'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5012'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5013'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5013'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5014'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5014'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5015'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5015'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5016'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5016'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5017'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5017'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5018'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5018'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5019'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5019'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5020'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5020'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5021'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5021'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5022'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5022'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5023'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5023'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5024'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5024'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5025'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5025'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5026'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5026'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5027'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5027'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5028'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5028'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5029'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5029'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5030'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5030'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5031'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5031'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5032'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5032'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5033'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5033'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5034'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5034'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5035'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5035'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5036'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5036'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5037'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5037'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5038'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5038'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5039'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5039'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5040'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5040'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5041'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5041'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5042'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5042'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5043'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5043'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5044'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5044'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5045'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5045'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5046'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5046'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5047'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5047'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5048'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5048'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5049'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5049'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5050'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5050'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5051'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5051'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5052'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5052'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5053'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5053'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5054'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5054'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5055'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5055'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5056'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5056'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5057'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5057'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5058'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5058'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5059'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5059'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5060'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5060'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5061'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5061'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5062'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5062'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5063'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5063'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5064'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5064'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5065'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5065'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5066'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5066'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5067'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5067'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5068'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5068'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5069'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5069'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5070'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5070'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5071'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5071'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5072'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5072'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5073'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5073'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5074'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5074'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5075'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5075'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5076'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5076'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5077'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5077'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5078'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5078'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5079'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5079'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5080'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5080'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5081'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5081'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5082'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5082'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5083'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5083'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5084'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5084'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5085'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5085'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5086'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5086'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5087'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5087'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5088'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5088'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5089'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5089'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5090'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5090'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5091'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5091'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5092'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5092'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5093'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5093'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5094'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5094'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5095'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5095'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5096'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5096'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5097'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5097'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5098'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5098'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5099'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5099'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5100'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5100'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5101'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5101'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5102'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5102'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5103'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5103'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5104'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5104'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5105'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5105'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5106'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5106'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5107'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5107'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5108'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5108'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5109'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5109'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5110'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5110'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5111'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5111'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5112'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5112'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5113'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5113'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5114'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5114'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5115'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5115'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5116'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5116'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5117'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5117'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5118'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5118'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5119'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5119'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5120'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5120'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5121'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5121'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5122'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5122'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5123'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5123'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5124'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5124'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5125'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5125'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5126'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5126'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5127'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5127'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5128'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5128'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5129'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5129'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5130'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5130'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5131'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5131'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5132'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5132'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5133'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5133'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5134'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5134'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5135'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5135'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5136'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5136'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5137'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5137'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5138'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5138'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5139'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5139'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5140'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5140'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5141'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5141'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5142'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5142'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5143'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5143'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5144'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5144'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5145'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5145'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5146'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5146'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5147'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5147'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5148'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5148'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5149'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5149'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5150'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5150'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5151'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5151'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5152'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5152'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5153'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5153'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5154'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5154'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5155'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5155'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5156'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5156'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5157'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5157'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5158'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5158'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5159'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5159'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5160'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5160'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5161'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5161'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5162'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5162'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5163'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5163'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5164'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5164'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5165'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5165'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5166'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5166'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5167'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5167'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5168'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5168'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5169'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5169'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5170'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5170'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5171'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5171'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5172'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5172'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5173'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5173'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5174'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5174'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5175'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5175'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5176'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5176'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5177'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5177'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5178'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5178'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5179'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5179'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5180'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5180'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5181'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5181'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5182'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5182'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5183'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5183'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5184'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5184'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5185'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5185'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5186'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5186'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5187'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5187'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5188'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5188'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5189'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5189'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5190'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5190'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5191'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5191'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5192'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5192'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5193'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5193'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5194'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5194'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5195'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5195'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5196'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5196'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5197'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5197'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5198'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5198'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5199'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5199'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5200'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5200'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5201'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5201'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5202'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5202'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5203'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5203'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5204'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5204'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5205'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5205'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5206'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5206'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5207'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5207'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5208'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5208'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5209'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5209'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5210'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5210'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5211'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5211'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5212'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5212'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5213'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5213'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5214'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5214'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5215'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5215'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5216'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5216'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5217'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5217'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5218'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5218'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5219'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5219'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5220'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5220'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5221'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5221'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5222'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5222'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5223'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5223'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5224'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5224'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5225'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5225'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5226'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5226'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5227'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5227'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5228'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5228'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5229'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5229'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5230'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5230'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5231'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5231'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5232'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5232'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5233'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5233'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5234'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5234'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5235'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5235'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5236'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5236'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5237'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5237'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5238'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5238'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5239'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5239'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5240'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5240'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5241'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5241'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5242'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5242'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5243'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5243'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5244'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5244'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5245'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5245'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5246'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5246'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5247'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5247'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5248'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5248'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5249'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5249'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5250'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5250'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5251'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5251'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5252'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5252'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5253'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5253'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5254'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5254'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5255'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5255'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5256'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5256'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5257'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5257'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5258'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5258'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5259'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5259'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5260'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5260'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5261'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5261'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5262'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5262'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5263'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5263'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5264'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5264'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5265'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5265'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5266'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5266'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5267'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5267'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5268'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5268'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5269'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5269'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5270'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5270'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5271'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5271'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5272'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5272'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5273'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5273'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5274'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5274'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5275'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5275'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5276'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5276'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5277'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5277'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5278'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5278'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5279'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5279'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5280'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5280'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5281'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5281'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5282'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5282'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5283'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5283'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5284'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5284'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5285'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5285'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5286'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5286'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5287'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5287'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5288'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5288'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5289'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5289'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5290'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5290'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5291'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5291'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5292'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5292'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5293'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5293'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5294'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5294'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5295'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5295'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5296'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5296'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5297'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5297'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5298'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5298'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5299'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5299'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5300'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5300'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5301'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5301'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5302'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5302'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5303'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5303'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5304'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5304'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5305'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5305'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5306'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5306'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5307'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5307'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5308'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5308'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5309'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5309'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5310'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5310'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5311'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5311'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5312'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5312'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5313'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5313'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5314'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5314'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5315'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5315'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5316'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5316'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5317'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5317'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5318'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5318'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5319'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5319'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5320'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5320'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5321'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5321'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5322'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5322'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5323'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5323'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5324'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5324'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5325'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5325'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5326'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5326'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5327'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5327'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5328'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5328'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5329'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5329'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5330'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5330'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5331'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5331'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5332'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5332'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5333'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5333'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5334'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5334'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5335'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5335'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5336'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5336'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5337'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5337'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5338'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5338'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5339'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5339'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5340'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5340'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5341'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5341'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5342'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5342'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5343'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5343'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5344'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5344'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5345'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5345'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5346'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5346'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5347'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5347'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5348'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5348'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5349'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5349'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5350'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5350'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5351'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5351'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5352'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5352'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5353'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5353'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5354'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5354'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5355'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5355'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5356'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5356'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5357'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5357'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5358'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5358'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5359'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5359'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5360'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5360'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5361'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5361'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5362'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5362'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5363'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5363'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5364'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5364'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5365'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5365'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5366'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5366'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5367'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5367'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5368'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5368'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5369'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5369'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5370'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5370'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5371'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5371'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5372'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5372'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5373'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5373'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5374'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5374'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5375'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5375'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5376'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5376'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5377'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5377'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5378'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5378'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5379'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5379'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5380'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5380'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5381'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5381'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5382'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5382'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5383'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5383'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5384'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5384'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5385'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5385'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5386'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5386'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5387'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5387'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5388'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5388'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5389'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5389'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5390'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5390'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5391'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5391'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5392'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5392'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5393'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5393'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5394'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5394'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5395'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5395'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5396'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5396'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5397'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5397'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5398'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5398'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5399'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5399'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5400'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5400'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5401'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5401'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5402'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5402'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5403'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5403'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5404'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5404'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5405'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5405'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5406'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5406'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5407'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5407'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5408'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5408'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5409'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5409'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5410'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5410'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5411'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5411'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5412'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5412'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5413'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5413'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5414'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5414'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5415'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5415'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5416'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5416'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5417'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5417'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5418'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5418'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5419'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5419'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5420'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5420'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5421'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5421'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5422'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5422'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5423'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5423'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5424'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5424'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5425'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5425'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5426'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5426'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5427'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5427'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5428'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5428'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5429'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5429'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5430'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5430'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5431'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5431'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5432'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5432'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5433'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5433'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5434'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5434'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5435'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5435'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5436'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5436'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5437'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5437'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5438'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5438'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5439'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5439'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5440'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5440'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5441'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5441'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5442'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5442'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5443'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5443'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5444'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5444'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5445'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5445'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5446'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5446'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5447'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5447'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5448'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5448'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5449'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5449'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5450'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5450'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5451'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5451'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5452'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5452'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5453'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5453'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5454'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5454'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5455'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5455'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5456'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5456'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5457'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5457'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5458'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5458'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5459'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5459'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5460'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5460'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5461'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5461'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5462'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5462'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5463'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5463'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5464'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5464'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5465'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5465'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5466'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5466'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5467'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5467'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5468'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5468'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5469'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5469'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5470'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5470'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5471'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5471'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5472'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5472'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5473'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5473'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5474'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5474'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5475'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5475'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5476'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5476'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5477'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5477'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5478'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5478'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5479'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5479'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5480'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5480'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5481'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5481'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5482'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5482'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5483'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5483'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5484'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5484'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5485'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5485'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5486'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5486'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5487'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5487'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5488'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5488'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5489'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5489'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5490'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5490'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5491'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5491'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5492'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5492'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5493'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5493'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5494'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5494'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5495'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5495'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5496'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5496'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5497'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5497'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5498'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5498'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5499'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5499'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5500'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5500'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5501'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5501'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5502'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5502'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5503'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5503'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5504'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5504'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5505'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5505'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5506'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5506'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5507'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5507'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5508'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5508'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5509'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5509'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5510'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5510'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5511'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5511'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5512'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5512'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5513'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5513'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5514'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5514'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5515'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5515'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5516'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5516'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5517'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5517'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5518'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5518'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5519'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5519'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5520'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5520'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5521'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5521'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5522'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5522'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5523'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5523'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5524'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5524'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5525'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5525'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5526'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5526'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5527'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5527'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5528'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5528'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5529'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5529'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5530'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5530'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5531'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5531'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5532'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5532'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5533'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5533'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5534'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5534'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5535'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5535'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5536'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5536'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5537'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5537'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5538'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5538'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5539'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5539'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5540'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5540'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5541'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5541'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5542'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5542'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5543'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5543'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5544'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5544'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5545'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5545'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5546'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5546'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5547'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5547'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5548'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5548'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5549'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5549'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5550'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5550'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5551'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5551'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5552'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5552'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5553'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5553'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5554'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5554'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5555'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5555'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5556'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5556'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5557'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5557'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5558'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5558'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5559'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5559'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5560'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5560'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5561'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5561'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5562'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5562'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5563'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5563'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5564'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5564'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5565'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5565'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5566'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5566'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5567'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5567'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5568'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5568'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5569'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5569'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5570'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5570'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5571'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5571'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5572'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5572'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5573'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5573'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5574'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5574'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5575'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5575'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5576'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5576'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5577'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5577'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5578'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5578'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5579'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5579'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5580'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5580'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5581'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5581'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5582'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5582'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5583'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5583'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5584'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5584'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5585'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5585'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5586'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5586'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5587'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5587'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5588'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5588'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5589'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5589'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5590'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5590'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5591'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5591'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5592'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5592'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5593'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5593'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5594'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5594'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5595'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5595'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5596'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5596'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5597'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5597'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5598'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5598'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5599'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5599'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5600'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5600'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5601'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5601'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5602'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5602'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5603'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5603'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5604'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5604'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5605'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5605'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5606'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5606'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5607'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5607'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5608'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5608'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5609'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5609'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5610'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5610'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5611'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5611'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5612'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5612'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5613'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5613'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5614'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5614'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5615'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5615'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5616'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5616'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5617'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5617'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5618'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5618'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5619'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5619'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5620'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5620'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5621'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5621'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5622'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5622'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5623'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5623'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5624'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5624'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5625'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5625'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5626'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5626'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5627'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5627'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5628'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5628'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5629'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5629'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5630'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5630'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5631'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5631'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5632'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5632'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5633'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5633'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5634'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5634'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5635'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5635'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5636'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5636'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5637'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5637'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5638'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5638'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5639'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5639'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5640'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5640'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5641'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5641'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5642'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5642'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5643'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5643'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5644'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5644'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5645'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5645'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5646'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5646'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5647'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5647'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5648'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5648'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5649'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5649'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5650'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5650'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5651'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5651'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5652'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5652'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5653'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5653'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5654'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5654'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5655'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5655'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5656'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5656'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5657'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5657'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5658'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5658'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5659'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5659'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5660'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5660'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5661'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5661'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5662'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5662'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5663'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5663'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5664'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5664'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5665'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5665'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5666'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5666'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5667'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5667'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5668'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5668'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5669'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5669'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5670'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5670'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5671'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5671'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5672'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5672'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5673'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5673'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5674'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5674'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5675'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5675'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5676'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5676'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5677'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5677'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5678'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5678'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5679'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5679'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5680'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5680'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5681'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5681'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5682'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5682'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5683'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5683'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5684'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5684'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5685'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5685'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5686'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5686'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5687'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5687'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5688'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5688'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5689'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5689'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5690'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5690'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5691'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5691'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5692'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5692'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5693'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5693'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5694'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5694'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5695'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5695'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5696'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5696'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5697'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5697'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5698'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5698'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5699'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5699'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5700'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5700'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5701'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5701'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5702'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5702'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5703'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5703'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5704'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5704'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5705'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5705'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5706'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5706'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5707'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5707'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5708'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5708'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5709'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5709'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5710'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5710'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5711'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5711'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5712'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5712'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5713'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5713'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5714'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5714'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5715'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5715'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5716'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5716'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5717'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5717'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5718'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5718'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5719'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5719'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5720'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5720'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5721'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5721'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5722'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5722'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5723'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5723'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5724'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5724'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5725'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5725'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5726'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5726'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5727'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5727'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5728'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5728'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5729'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5729'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5730'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5730'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5731'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5731'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5732'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5732'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5733'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5733'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5734'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5734'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5735'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5735'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5736'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5736'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5737'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5737'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5738'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5738'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5739'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5739'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5740'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5740'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5741'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5741'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5742'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5742'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5743'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5743'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5744'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5744'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5745'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5745'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5746'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5746'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5747'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5747'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5748'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5748'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5749'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5749'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5750'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5750'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5751'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5751'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5752'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5752'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5753'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5753'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5754'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5754'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5755'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5755'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5756'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5756'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5757'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5757'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5758'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5758'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5759'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5759'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5760'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5760'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5761'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5761'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5762'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5762'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5763'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5763'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5764'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5764'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5765'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5765'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5766'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5766'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5767'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5767'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5768'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5768'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5769'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5769'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5770'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5770'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5771'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5771'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5772'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5772'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5773'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5773'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5774'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5774'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5775'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5775'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5776'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5776'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5777'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5777'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5778'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5778'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5779'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5779'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5780'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5780'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5781'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5781'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5782'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5782'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5783'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5783'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5784'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5784'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5785'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5785'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5786'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5786'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5787'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5787'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5788'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5788'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5789'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5789'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5790'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5790'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5791'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5791'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5792'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5792'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5793'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5793'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5794'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5794'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5795'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5795'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5796'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5796'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5797'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5797'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5798'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5798'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5799'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5799'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5800'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5800'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5801'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5801'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5802'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5802'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5803'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5803'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5804'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5804'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5805'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5805'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5806'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5806'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5807'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5807'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5808'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5808'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5809'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5809'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5810'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5810'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5811'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5811'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5812'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5812'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5813'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5813'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5814'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5814'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5815'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5815'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5816'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5816'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5817'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5817'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5818'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5818'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5819'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5819'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5820'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5820'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5821'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5821'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5822'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5822'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5823'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5823'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5824'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5824'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5825'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5825'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5826'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5826'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5827'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5827'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5828'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5828'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5829'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5829'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5830'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5830'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5831'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5831'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5832'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5832'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5833'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5833'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5834'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5834'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5835'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5835'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5836'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5836'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5837'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5837'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5838'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5838'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5839'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5839'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5840'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5840'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5841'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5841'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5842'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5842'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5843'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5843'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5844'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5844'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5845'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5845'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5846'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5846'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5847'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5847'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5848'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5848'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5849'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5849'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5850'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5850'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5851'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5851'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5852'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5852'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5853'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5853'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5854'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5854'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5855'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5855'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5856'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5856'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5857'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5857'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5858'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5858'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5859'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5859'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5860'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5860'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5861'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5861'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5862'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5862'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5863'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5863'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5864'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5864'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5865'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5865'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5866'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5866'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5867'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5867'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5868'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5868'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5869'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5869'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5870'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5870'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5871'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5871'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5872'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5872'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5873'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5873'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5874'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5874'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5875'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5875'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5876'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5876'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5877'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5877'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5878'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5878'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5879'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5879'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5880'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5880'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5881'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5881'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5882'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5882'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5883'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5883'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5884'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5884'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5885'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5885'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5886'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5886'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5887'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5887'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5888'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5888'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5889'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5889'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5890'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5890'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5891'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5891'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5892'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5892'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5893'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5893'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5894'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5894'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5895'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5895'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5896'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5896'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5897'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5897'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5898'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5898'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5899'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5899'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5900'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5900'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5901'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5901'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5902'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5902'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5903'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5903'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5904'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5904'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5905'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5905'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5906'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5906'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5907'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5907'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5908'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5908'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5909'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5909'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5910'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5910'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5911'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5911'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5912'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5912'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5913'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5913'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5914'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5914'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5915'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5915'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5916'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5916'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5917'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5917'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5918'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5918'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5919'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5919'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5920'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5920'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5921'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5921'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5922'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5922'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5923'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5923'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5924'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5924'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5925'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5925'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5926'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5926'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5927'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5927'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5928'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5928'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5929'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5929'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5930'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5930'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5931'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5931'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5932'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5932'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5933'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5933'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5934'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5934'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5935'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5935'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5936'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5936'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5937'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5937'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5938'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5938'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5939'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5939'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5940'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5940'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5941'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5941'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5942'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5942'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5943'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5943'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5944'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5944'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5945'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5945'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5946'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5946'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5947'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5947'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5948'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5948'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5949'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5949'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5950'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5950'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5951'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5951'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5952'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5952'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5953'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5953'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5954'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5954'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5955'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5955'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5956'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5956'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5957'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5957'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5958'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5958'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5959'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5959'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5960'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5960'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5961'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5961'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5962'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5962'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5963'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5963'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5964'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5964'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5965'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5965'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5966'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5966'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5967'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5967'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5968'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5968'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5969'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5969'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5970'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5970'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5971'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5971'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5972'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5972'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5973'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5973'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5974'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5974'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5975'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5975'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5976'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5976'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5977'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5977'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5978'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5978'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5979'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5979'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5980'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5980'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5981'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5981'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5982'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5982'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5983'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5983'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5984'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5984'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5985'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5985'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5986'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5986'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5987'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5987'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5988'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5988'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5989'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5989'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5990'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5990'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5991'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5991'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5992'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5992'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5993'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5993'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5994'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5994'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5995'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5995'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5996'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5996'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5997'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5997'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5998'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5998'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '5999'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '5999'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6000'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6000'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6001'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6001'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6002'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6002'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6003'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6003'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6004'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6004'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6005'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6005'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6006'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6006'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6007'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6007'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6008'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6008'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6009'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6009'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6010'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6010'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6011'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6011'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6012'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6012'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6013'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6013'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6014'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6014'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6015'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6015'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6016'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6016'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6017'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6017'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6018'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6018'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6019'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6019'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6020'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6020'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6021'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6021'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6022'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6022'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6023'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6023'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6024'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6024'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6025'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6025'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6026'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6026'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6027'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6027'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6028'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6028'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6029'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6029'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6030'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6030'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6031'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6031'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6032'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6032'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6033'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6033'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6034'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6034'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6035'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6035'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6036'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6036'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6037'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6037'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6038'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6038'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6039'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6039'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6040'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6040'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6041'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6041'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6042'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6042'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6043'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6043'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6044'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6044'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6045'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6045'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6046'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6046'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6047'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6047'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6048'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6048'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6049'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6049'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6050'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6050'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6051'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6051'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6052'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6052'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6053'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6053'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6054'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6054'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6055'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6055'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6056'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6056'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6057'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6057'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6058'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6058'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6059'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6059'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6060'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6060'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6061'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6061'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6062'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6062'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6063'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6063'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6064'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6064'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6065'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6065'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6066'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6066'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6067'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6067'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6068'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6068'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6069'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6069'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6070'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6070'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6071'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6071'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6072'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6072'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6073'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6073'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6074'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6074'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6075'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6075'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6076'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6076'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6077'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6077'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6078'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6078'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6079'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6079'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6080'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6080'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6081'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6081'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6082'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6082'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6083'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6083'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6084'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6084'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6085'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6085'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6086'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6086'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6087'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6087'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6088'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6088'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6089'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6089'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6090'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6090'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6091'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6091'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6092'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6092'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6093'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6093'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6094'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6094'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6095'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6095'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6096'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6096'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6097'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6097'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6098'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6098'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6099'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6099'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6100'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6100'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6101'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6101'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6102'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6102'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6103'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6103'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6104'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6104'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6105'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6105'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6106'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6106'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6107'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6107'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6108'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6108'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6109'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6109'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6110'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6110'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6111'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6111'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6112'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6112'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6113'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6113'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6114'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6114'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6115'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6115'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6116'

UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6116'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6117'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6117'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6118'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6118'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6119'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6119'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6120'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6120'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6121'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6121'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6122'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6122'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6123'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6123'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6124'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6124'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6125'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6125'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6126'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6126'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6127'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6127'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6128'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6128'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6129'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6129'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6130'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6130'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6131'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6131'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6132'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6132'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6133'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6133'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6134'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6134'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6135'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6135'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6136'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6136'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6137'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6137'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6138'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6138'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6139'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6139'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6140'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6140'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6141'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6141'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6142'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6142'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6143'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6143'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6144'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6144'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6145'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6145'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6146'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6146'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6147'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6147'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6148'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6148'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6149'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6149'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6150'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6150'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6151'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6151'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6152'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6152'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6153'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6153'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6154'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6154'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6155'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6155'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6156'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6156'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6157'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6157'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6158'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6158'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6159'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6159'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6160'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6160'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6161'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6161'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6162'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6162'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6163'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6163'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6164'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6164'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6165'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6165'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6166'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6166'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6167'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6167'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6168'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6168'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6169'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6169'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6170'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6170'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6171'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6171'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6172'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6172'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6173'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6173'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6174'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6174'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6175'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6175'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6176'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6176'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6177'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6177'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6178'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6178'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6179'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6179'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6180'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6180'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6181'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6181'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6182'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6182'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6183'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6183'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6184'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6184'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6185'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6185'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6186'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6186'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6187'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6187'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6188'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6188'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6189'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6189'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6190'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6190'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6191'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6191'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6192'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6192'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6193'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6193'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6194'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6194'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6195'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6195'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6196'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6196'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6197'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6197'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6198'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6198'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6199'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6199'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6200'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6200'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6201'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6201'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6202'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6202'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6203'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6203'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6204'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6204'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6205'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6205'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6206'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6206'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6207'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6207'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6208'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6208'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6209'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6209'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6210'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6210'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6211'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6211'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6212'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6212'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6213'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6213'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6214'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6214'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6215'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6215'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6216'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6216'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6217'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6217'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6218'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6218'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6219'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6219'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6220'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6220'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6221'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6221'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6222'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6222'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6223'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6223'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6224'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6224'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6225'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6225'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6226'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6226'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6227'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6227'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6228'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6228'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6229'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6229'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6230'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6230'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6231'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6231'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6232'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6232'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6233'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6233'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6234'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6234'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6235'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6235'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6236'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6236'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6237'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6237'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6238'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6238'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6239'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6239'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6240'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6240'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6241'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6241'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6242'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6242'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6243'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6243'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6244'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6244'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6245'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6245'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6246'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6246'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6247'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6247'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6248'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6248'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6249'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6249'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6250'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6250'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6251'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6251'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6252'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6252'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6253'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6253'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6254'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6254'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6255'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6255'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6256'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6256'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6257'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6257'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6258'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6258'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6259'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6259'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6260'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6260'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6261'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6261'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6262'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6262'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6263'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6263'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6264'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6264'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6265'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6265'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6266'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6266'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6267'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6267'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6268'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6268'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6269'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6269'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6270'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6270'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6271'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6271'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6272'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6272'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6273'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6273'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6274'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6274'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6275'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6275'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6276'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6276'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6277'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6277'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6278'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6278'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6279'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6279'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6280'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6280'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6281'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6281'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6282'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6282'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6283'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6283'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6284'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6284'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6285'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6285'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6286'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6286'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6287'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6287'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6288'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6288'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6289'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6289'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6290'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6290'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6291'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6291'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6292'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6292'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6293'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6293'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6294'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6294'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6295'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6295'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6296'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6296'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6297'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6297'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6298'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6298'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6299'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6299'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6300'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6300'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6301'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6301'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6302'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6302'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6303'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6303'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6304'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6304'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6305'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6305'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6306'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6306'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6307'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6307'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6308'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6308'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6309'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6309'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6310'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6310'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6311'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6311'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6312'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6312'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6313'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6313'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6314'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6314'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6315'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6315'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6316'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6316'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6317'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6317'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6318'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6318'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6319'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6319'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6320'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6320'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6321'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6321'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6322'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6322'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6323'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6323'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6324'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6324'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6325'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6325'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6326'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6326'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6327'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6327'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6328'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6328'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6329'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6329'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6330'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6330'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6331'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6331'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6332'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6332'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6333'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6333'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6334'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6334'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6335'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6335'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6336'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6336'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6337'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6337'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6338'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6338'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6339'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6339'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6340'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6340'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6341'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6341'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6342'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6342'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6343'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6343'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6344'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6344'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6345'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6345'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6346'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6346'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6347'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6347'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6348'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6348'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6349'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6349'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6350'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6350'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6351'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6351'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6352'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6352'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6353'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6353'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6354'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6354'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6355'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6355'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6356'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6356'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6357'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6357'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6358'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6358'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6359'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6359'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6360'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6360'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6361'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6361'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6362'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6362'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6363'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6363'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6364'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6364'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6365'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6365'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6366'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6366'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6367'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6367'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6368'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6368'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6369'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6369'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6370'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6370'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6371'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6371'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6372'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6372'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6373'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6373'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6374'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6374'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6375'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6375'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6376'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6376'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6377'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6377'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6378'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6378'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6379'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6379'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6380'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6380'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6381'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6381'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6382'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6382'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6383'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6383'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6384'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6384'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6385'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6385'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6386'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6386'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6387'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6387'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6388'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6388'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6389'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6389'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6390'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6390'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6391'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6391'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6392'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6392'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6393'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6393'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6394'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6394'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6395'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6395'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6396'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6396'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6397'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6397'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6398'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6398'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6399'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6399'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6400'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6400'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6401'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6401'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6402'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6402'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6403'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6403'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6404'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6404'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6405'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6405'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6406'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6406'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6407'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6407'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6408'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6408'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6409'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6409'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6410'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6410'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6411'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6411'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6412'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6412'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6413'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6413'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6414'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6414'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6415'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6415'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6416'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6416'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6417'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6417'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6418'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6418'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6419'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6419'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6420'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6420'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6421'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6421'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6422'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6422'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6423'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6423'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6424'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6424'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6425'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6425'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6426'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6426'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6427'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6427'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6428'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6428'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6429'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6429'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6430'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6430'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6431'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6431'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6432'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6432'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6433'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6433'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6434'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6434'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6435'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6435'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6436'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6436'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6437'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6437'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6438'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6438'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6439'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6439'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6440'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6440'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6441'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6441'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6442'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6442'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6443'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6443'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6444'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6444'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6445'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6445'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6446'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6446'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6447'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6447'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6448'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6448'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6449'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6449'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6450'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6450'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6451'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6451'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6452'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6452'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6453'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6453'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6454'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6454'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6455'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6455'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6456'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6456'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6457'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6457'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6458'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6458'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6459'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6459'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6460'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6460'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6461'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6461'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6462'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6462'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6463'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6463'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6464'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6464'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6465'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6465'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6466'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6466'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6467'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6467'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6468'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6468'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6469'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6469'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6470'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6470'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6471'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6471'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6472'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6472'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6473'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6473'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6474'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6474'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6475'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6475'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6476'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6476'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6477'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6477'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6478'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6478'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6479'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6479'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6480'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6480'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6481'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6481'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6482'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6482'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6483'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6483'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6484'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6484'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6485'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6485'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6486'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6486'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6487'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6487'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6488'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6488'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6489'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6489'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6490'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6490'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6491'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6491'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6492'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6492'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6493'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6493'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6494'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6494'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6495'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6495'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6496'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6496'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6497'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6497'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6498'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6498'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6499'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6499'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6500'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6500'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6501'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6501'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6502'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6502'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6503'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6503'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6504'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6504'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6505'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6505'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6506'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6506'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6507'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6507'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6508'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6508'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6509'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6509'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6510'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6510'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6511'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6511'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6512'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6512'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6513'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6513'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6514'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6514'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6515'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6515'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6516'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6516'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6517'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6517'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6518'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6518'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6519'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6519'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6520'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6520'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6521'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6521'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6522'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6522'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6523'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6523'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6524'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6524'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6525'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6525'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6526'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6526'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6527'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6527'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6528'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6528'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6529'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6529'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6530'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6530'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6531'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6531'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6532'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6532'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6533'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6533'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6534'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6534'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6535'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6535'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6536'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6536'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6537'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6537'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6538'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6538'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6539'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6539'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6540'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6540'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6541'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6541'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6542'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6542'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6543'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6543'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6544'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6544'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6545'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6545'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6546'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6546'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6547'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6547'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6548'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6548'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6549'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6549'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6550'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6550'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6551'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6551'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6552'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6552'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6553'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6553'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6554'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6554'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6555'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6555'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6556'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6556'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6557'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6557'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6558'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6558'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6559'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6559'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6560'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6560'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6561'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6561'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6562'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6562'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6563'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6563'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6564'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6564'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6565'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6565'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6566'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6566'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6567'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6567'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6568'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6568'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6569'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6569'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6570'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6570'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6571'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6571'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6572'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6572'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6573'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6573'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6574'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6574'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6575'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6575'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6576'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6576'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6577'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6577'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6578'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6578'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6579'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6579'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6580'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6580'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6581'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6581'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6582'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6582'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6583'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6583'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6584'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6584'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6585'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6585'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6586'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6586'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6587'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6587'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6588'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6588'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6589'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6589'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6590'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6590'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6591'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6591'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6592'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6592'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6593'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6593'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6594'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6594'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6595'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6595'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6596'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6596'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6597'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6597'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6598'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6598'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6599'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6599'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6600'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6600'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6601'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6601'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6602'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6602'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6603'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6603'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6604'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6604'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6605'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6605'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6606'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6606'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6607'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6607'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6608'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6608'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6609'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6609'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6610'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6610'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6611'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6611'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6612'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6612'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6613'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6613'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6614'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6614'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6615'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6615'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6616'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6616'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6617'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6617'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6618'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6618'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6619'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6619'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6620'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6620'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6621'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6621'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6622'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6622'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6623'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6623'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6624'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6624'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6625'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6625'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6626'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6626'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6627'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6627'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6628'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6628'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6629'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6629'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6630'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6630'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6631'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6631'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6632'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6632'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6633'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6633'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6634'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6634'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6635'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6635'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6636'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6636'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6637'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6637'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6638'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6638'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6639'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6639'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6640'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6640'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6641'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6641'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6642'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6642'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6643'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6643'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6644'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6644'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6645'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6645'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6646'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6646'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6647'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6647'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6648'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6648'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6649'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6649'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6650'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6650'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6651'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6651'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6652'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6652'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6653'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6653'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6654'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6654'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6655'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6655'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6656'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6656'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6657'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6657'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6658'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6658'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6659'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6659'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6660'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6660'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6661'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6661'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6662'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6662'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6663'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6663'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6664'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6664'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6665'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6665'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6666'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6666'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6667'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6667'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6668'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6668'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6669'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6669'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6670'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6670'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6671'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6671'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6672'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6672'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6673'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6673'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6674'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6674'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6675'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6675'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6676'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6676'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6677'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6677'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6678'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6678'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6679'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6679'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6680'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6680'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6681'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6681'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6682'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6682'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6683'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6683'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6684'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6684'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6685'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6685'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6686'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6686'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6687'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6687'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6688'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6688'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6689'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6689'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6690'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6690'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6691'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6691'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6692'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6692'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6693'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6693'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6694'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6694'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6695'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6695'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6696'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6696'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6697'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6697'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6698'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6698'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6699'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6699'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6700'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6700'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6701'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6701'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6702'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6702'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6703'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6703'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6704'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6704'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6705'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6705'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6706'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6706'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6707'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6707'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6708'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6708'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6709'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6709'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6710'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6710'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6711'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6711'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6712'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6712'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6713'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6713'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6714'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6714'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6715'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6715'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6716'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6716'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6717'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6717'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6718'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6718'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6719'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6719'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6720'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6720'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6721'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6721'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6722'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6722'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6723'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6723'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6724'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6724'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6725'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6725'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6726'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6726'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6727'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6727'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6728'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6728'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6729'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6729'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6730'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6730'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6731'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6731'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6732'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6732'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6733'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6733'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6734'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6734'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6735'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6735'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6736'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6736'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6737'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6737'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6738'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6738'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6739'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6739'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6740'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6740'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6741'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6741'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6742'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6742'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6743'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6743'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6744'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6744'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6745'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6745'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6746'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6746'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6747'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6747'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6748'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6748'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6749'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6749'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6750'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6750'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6751'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6751'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6752'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6752'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6753'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6753'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6754'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6754'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6755'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6755'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6756'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6756'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6757'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6757'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6758'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6758'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6759'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6759'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6760'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6760'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6761'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6761'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6762'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6762'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6763'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6763'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6764'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6764'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6765'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6765'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6766'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6766'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6767'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6767'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6768'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6768'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6769'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6769'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6770'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6770'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6771'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6771'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6772'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6772'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6773'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6773'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6774'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6774'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6775'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6775'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6776'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6776'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6777'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6777'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6778'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6778'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6779'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6779'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6780'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6780'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6781'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6781'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6782'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6782'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6783'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6783'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6784'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6784'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6785'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6785'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6786'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6786'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6787'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6787'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6788'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6788'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6789'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6789'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6790'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6790'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6791'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6791'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6792'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6792'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6793'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6793'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6794'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6794'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6795'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6795'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6796'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6796'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6797'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6797'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6798'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6798'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6799'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6799'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6800'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6800'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6801'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6801'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6802'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6802'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6803'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6803'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6804'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6804'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6805'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6805'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6806'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6806'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6807'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6807'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6808'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6808'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6809'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6809'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6810'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6810'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6811'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6811'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6812'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6812'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6813'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6813'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6814'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6814'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6815'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6815'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6816'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6816'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6817'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6817'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6818'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6818'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6819'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6819'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6820'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6820'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6821'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6821'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6822'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6822'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6823'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6823'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6824'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6824'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6825'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6825'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6826'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6826'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6827'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6827'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6828'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6828'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6829'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6829'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6830'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6830'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6831'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6831'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6832'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6832'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6833'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6833'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6834'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6834'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6835'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6835'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6836'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6836'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6837'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6837'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6838'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6838'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6839'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6839'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6840'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6840'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6841'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6841'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6842'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6842'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6843'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6843'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6844'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6844'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6845'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6845'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6846'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6846'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6847'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6847'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6848'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6848'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6849'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6849'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6850'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6850'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6851'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6851'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6852'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6852'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6853'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6853'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6854'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6854'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6855'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6855'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6856'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6856'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6857'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6857'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6858'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6858'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6859'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6859'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6860'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6860'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6861'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6861'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6862'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6862'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6863'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6863'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6864'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6864'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6865'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6865'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6866'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6866'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6867'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6867'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6868'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6868'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6869'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6869'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6870'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6870'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6871'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6871'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6872'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6872'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6873'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6873'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6874'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6874'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6875'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6875'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6876'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6876'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6877'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6877'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6878'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6878'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6879'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6879'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6880'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6880'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6881'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6881'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6882'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6882'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6883'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6883'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6884'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6884'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6885'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6885'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6886'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6886'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6887'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6887'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6888'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6888'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6889'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6889'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6890'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6890'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6891'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6891'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6892'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6892'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6893'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6893'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6894'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6894'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6895'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6895'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6896'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6896'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6897'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6897'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6898'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6898'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6899'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6899'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6900'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6900'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6901'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6901'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6902'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6902'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6903'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6903'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6904'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6904'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6905'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6905'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6906'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6906'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6907'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6907'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6908'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6908'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6909'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6909'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6910'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6910'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6911'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6911'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6912'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6912'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6913'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6913'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6914'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6914'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6915'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6915'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6916'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6916'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6917'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6917'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6918'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6918'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6919'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6919'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6920'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6920'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6921'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6921'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6922'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6922'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6923'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6923'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6924'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6924'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6925'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6925'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6926'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6926'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6927'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6927'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6928'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6928'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6929'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6929'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6930'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6930'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6931'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6931'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6932'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6932'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6933'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6933'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6934'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6934'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6935'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6935'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6936'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6936'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6937'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6937'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6938'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6938'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6939'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6939'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6940'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6940'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6941'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6941'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6942'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6942'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6943'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6943'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6944'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6944'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6945'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6945'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6946'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6946'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6947'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6947'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6948'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6948'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6949'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6949'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6950'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6950'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6951'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6951'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6952'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6952'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6953'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6953'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6954'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6954'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6955'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6955'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6956'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6956'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6957'

UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6957'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6958'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6958'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6959'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6959'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6960'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6960'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6961'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6961'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6962'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6962'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6963'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6963'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6964'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6964'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6965'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6965'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6966'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6966'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6967'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6967'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6968'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6968'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6969'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6969'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6970'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6970'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6971'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6971'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6972'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6972'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6973'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6973'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6974'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6974'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6975'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6975'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6976'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6976'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6977'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6977'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6978'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6978'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6979'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6979'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6980'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6980'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6981'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6981'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6982'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6982'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6983'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6983'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6984'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6984'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6985'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6985'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6986'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6986'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6987'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6987'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6988'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6988'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6989'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6989'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6990'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6990'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6991'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6991'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6992'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6992'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6993'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6993'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6994'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6994'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6995'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6995'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6996'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6996'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6997'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6997'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6998'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6998'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '6999'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '6999'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7000'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7000'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7001'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7001'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7002'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7002'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7003'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7003'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7004'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7004'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7005'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7005'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7006'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7006'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7007'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7007'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7008'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7008'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7009'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7009'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7010'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7010'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7011'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7011'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7012'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7012'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7013'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7013'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7014'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7014'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7015'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7015'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7016'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7016'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7017'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7017'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7018'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7018'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7019'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7019'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7020'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7020'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7021'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7021'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7022'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7022'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7023'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7023'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7024'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7024'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7025'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7025'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7026'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7026'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7027'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7027'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7028'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7028'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7029'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7029'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7030'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7030'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7031'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7031'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7032'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7032'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7033'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7033'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7034'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7034'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7035'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7035'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7036'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7036'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7037'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7037'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7038'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7038'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7039'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7039'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7040'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7040'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7041'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7041'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7042'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7042'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7043'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7043'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7044'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7044'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7045'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7045'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7046'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7046'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7047'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7047'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7048'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7048'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7049'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7049'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7050'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7050'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7051'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7051'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7052'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7052'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7053'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7053'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7054'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7054'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7055'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7055'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7056'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7056'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7057'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7057'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7058'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7058'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7059'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7059'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7060'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7060'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7061'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7061'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7062'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7062'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7063'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7063'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7064'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7064'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7065'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7065'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7066'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7066'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7067'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7067'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7068'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7068'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7069'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7069'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7070'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7070'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7071'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7071'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7072'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7072'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7073'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7073'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7074'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7074'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7075'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7075'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7076'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7076'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7077'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7077'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7078'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7078'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7079'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7079'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7080'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7080'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7081'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7081'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7082'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7082'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7083'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7083'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7084'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7084'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7085'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7085'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7086'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7086'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7087'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7087'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7088'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7088'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7089'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7089'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7090'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7090'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7091'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7091'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7092'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7092'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7093'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7093'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7094'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7094'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7095'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7095'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7096'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7096'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7097'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7097'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7098'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7098'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7099'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7099'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7100'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7100'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7101'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7101'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7102'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7102'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7103'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7103'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7104'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7104'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7105'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7105'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7106'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7106'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7107'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7107'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7108'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7108'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7109'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7109'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7110'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7110'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7111'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7111'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7112'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7112'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7113'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7113'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7114'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7114'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7115'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7115'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7116'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7116'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7117'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7117'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7118'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7118'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7119'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7119'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7120'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7120'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7121'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7121'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7122'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7122'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7123'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7123'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7124'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7124'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7125'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7125'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7126'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7126'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7127'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7127'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7128'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7128'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7129'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7129'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7130'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7130'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7131'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7131'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7132'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7132'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7133'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7133'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7134'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7134'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7135'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7135'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7136'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7136'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7137'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7137'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7138'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7138'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7139'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7139'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7140'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7140'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7141'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7141'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7142'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7142'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7143'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7143'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7144'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7144'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7145'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7145'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7146'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7146'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7147'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7147'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7148'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7148'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7149'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7149'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7150'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7150'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7151'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7151'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7152'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7152'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7153'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7153'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7154'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7154'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7155'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7155'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7156'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7156'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7157'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7157'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7158'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7158'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7159'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7159'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7160'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7160'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7161'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7161'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7162'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7162'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7163'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7163'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7164'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7164'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7165'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7165'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7166'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7166'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7167'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7167'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7168'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7168'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7169'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7169'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7170'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7170'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7171'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7171'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7172'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7172'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7173'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7173'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7174'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7174'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7175'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7175'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7176'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7176'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7177'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7177'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7178'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7178'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7179'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7179'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7180'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7180'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7181'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7181'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7182'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7182'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7183'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7183'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7184'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7184'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7185'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7185'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7186'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7186'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7187'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7187'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7188'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7188'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7189'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7189'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7190'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7190'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7191'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7191'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7192'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7192'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7193'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7193'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7194'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7194'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7195'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7195'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7196'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7196'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7197'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7197'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7198'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7198'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7199'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7199'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7200'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7200'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7201'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7201'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7202'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7202'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7203'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7203'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7204'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7204'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7205'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7205'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7206'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7206'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7207'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7207'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7208'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7208'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7209'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7209'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7210'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7210'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7211'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7211'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7212'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7212'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7213'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7213'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7214'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7214'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7215'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7215'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7216'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7216'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7217'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7217'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7218'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7218'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7219'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7219'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7220'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7220'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7221'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7221'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7222'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7222'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7223'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7223'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7224'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7224'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7225'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7225'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7226'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7226'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7227'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7227'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7228'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7228'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7229'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7229'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7230'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7230'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7231'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7231'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7232'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7232'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7233'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7233'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7234'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7234'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7235'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7235'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7236'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7236'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7237'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7237'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7238'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7238'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7239'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7239'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7240'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7240'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7241'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7241'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7242'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7242'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7243'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7243'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7244'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7244'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7245'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7245'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7246'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7246'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7247'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7247'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7248'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7248'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7249'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7249'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7250'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7250'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7251'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7251'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7252'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7252'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7253'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7253'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7254'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7254'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7255'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7255'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7256'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7256'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7257'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7257'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7258'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7258'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7259'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7259'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7260'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7260'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7261'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7261'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7262'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7262'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7263'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7263'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7264'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7264'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7265'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7265'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7266'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7266'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7267'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7267'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7268'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7268'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7269'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7269'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7270'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7270'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7271'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7271'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7272'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7272'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7273'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7273'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7274'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7274'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7275'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7275'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7276'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7276'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7277'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7277'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7278'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7278'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7279'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7279'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7280'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7280'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7281'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7281'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7282'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7282'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7283'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7283'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7284'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7284'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7285'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7285'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7286'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7286'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7287'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7287'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7288'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7288'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7289'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7289'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7290'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7290'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7291'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7291'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7292'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7292'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7293'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7293'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7294'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7294'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7295'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7295'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7296'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7296'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7297'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7297'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7298'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7298'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7299'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7299'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7300'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7300'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7301'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7301'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7302'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7302'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7303'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7303'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7304'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7304'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7305'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7305'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7306'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7306'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7307'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7307'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7308'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7308'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7309'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7309'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7310'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7310'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7311'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7311'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7312'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7312'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7313'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7313'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7314'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7314'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7315'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7315'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7316'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7316'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7317'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7317'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7318'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7318'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7319'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7319'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7320'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7320'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7321'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7321'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7322'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7322'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7323'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7323'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7324'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7324'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7325'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7325'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7326'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7326'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7327'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7327'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7328'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7328'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7329'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7329'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7330'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7330'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7331'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7331'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7332'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7332'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7333'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7333'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7334'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7334'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7335'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7335'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7336'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7336'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7337'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7337'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7338'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7338'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7339'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7339'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7340'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7340'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7341'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7341'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7342'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7342'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7343'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7343'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7344'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7344'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7345'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7345'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7346'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7346'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7347'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7347'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7348'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7348'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7349'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7349'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7350'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7350'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7351'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7351'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7352'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7352'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7353'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7353'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7354'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7354'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7355'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7355'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7356'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7356'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7357'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7357'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7358'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7358'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7359'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7359'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7360'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7360'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7361'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7361'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7362'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7362'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7363'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7363'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7364'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7364'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7365'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7365'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7366'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7366'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7367'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7367'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7368'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7368'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7369'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7369'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7370'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7370'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7371'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7371'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7372'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7372'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7373'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7373'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7374'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7374'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7375'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7375'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7376'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7376'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7377'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7377'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7378'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7378'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7379'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7379'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7380'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7380'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7381'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7381'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7382'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7382'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7383'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7383'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7384'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7384'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7385'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7385'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7386'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7386'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7387'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7387'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7388'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7388'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7389'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7389'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7390'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7390'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7391'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7391'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7392'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7392'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7393'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7393'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7394'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7394'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7395'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7395'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7396'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7396'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7397'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7397'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7398'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7398'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7399'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7399'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7400'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7400'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7401'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7401'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7402'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7402'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7403'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7403'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7404'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7404'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7405'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7405'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7406'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7406'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7407'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7407'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7408'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7408'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7409'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7409'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7410'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7410'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7411'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7411'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7412'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7412'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7413'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7413'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7414'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7414'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7415'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7415'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7416'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7416'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7417'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7417'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7418'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7418'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7419'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7419'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7420'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7420'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7421'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7421'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7422'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7422'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7423'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7423'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7424'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7424'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7425'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7425'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7426'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7426'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7427'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7427'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7428'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7428'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7429'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7429'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7430'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7430'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7431'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7431'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7432'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7432'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7433'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7433'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7434'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7434'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7435'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7435'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7436'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7436'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7437'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7437'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7438'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7438'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7439'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7439'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7440'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7440'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7441'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7441'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7442'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7442'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7443'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7443'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7444'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7444'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7445'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7445'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7446'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7446'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7447'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7447'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7448'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7448'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7449'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7449'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7450'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7450'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7451'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7451'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7452'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7452'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7453'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7453'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7454'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7454'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7455'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7455'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7456'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7456'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7457'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7457'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7458'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7458'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7459'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7459'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7460'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7460'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7461'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7461'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7462'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7462'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7463'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7463'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7464'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7464'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7465'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7465'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7466'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7466'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7467'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7467'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7468'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7468'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7469'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7469'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7470'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7470'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7471'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7471'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7472'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7472'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7473'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7473'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7474'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7474'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7475'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7475'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7476'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7476'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7477'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7477'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7478'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7478'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7479'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7479'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7480'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7480'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7481'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7481'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7482'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7482'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7483'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7483'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7484'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7484'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7485'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7485'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7486'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7486'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7487'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7487'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7488'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7488'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7489'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7489'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7490'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7490'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7491'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7491'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7492'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7492'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7493'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7493'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7494'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7494'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7495'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7495'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7496'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7496'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7497'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7497'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7498'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7498'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7499'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7499'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7500'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7500'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7501'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7501'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7502'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7502'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7503'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7503'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7504'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7504'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7505'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7505'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7506'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7506'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7507'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7507'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7508'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7508'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7509'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7509'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7510'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7510'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7511'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7511'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7512'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7512'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7513'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7513'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7514'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7514'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7515'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7515'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7516'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7516'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7517'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7517'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7518'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7518'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7519'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7519'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7520'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7520'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7521'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7521'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7522'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7522'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7523'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7523'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7524'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7524'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7525'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7525'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7526'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7526'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7527'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7527'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7528'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7528'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7529'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7529'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7530'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7530'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7531'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7531'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7532'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7532'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7533'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7533'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7534'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7534'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7535'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7535'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7536'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7536'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7537'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7537'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7538'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7538'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7539'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7539'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7540'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7540'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7541'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7541'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7542'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7542'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7543'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7543'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7544'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7544'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7545'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7545'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7546'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7546'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7547'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7547'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7548'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7548'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7549'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7549'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7550'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7550'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7551'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7551'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7552'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7552'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7553'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7553'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7554'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7554'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7555'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7555'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7556'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7556'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7557'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7557'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7558'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7558'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7559'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7559'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7560'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7560'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7561'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7561'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7562'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7562'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7563'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7563'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7564'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7564'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7565'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7565'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7566'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7566'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7567'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7567'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7568'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7568'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7569'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7569'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7570'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7570'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7571'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7571'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7572'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7572'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7573'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7573'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7574'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7574'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7575'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7575'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7576'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7576'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7577'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7577'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7578'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7578'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7579'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7579'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7580'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7580'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7581'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7581'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7582'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7582'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7583'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7583'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7584'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7584'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7585'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7585'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7586'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7586'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7587'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7587'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7588'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7588'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7589'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7589'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7590'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7590'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7591'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7591'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7592'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7592'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7593'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7593'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7594'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7594'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7595'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7595'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7596'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7596'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7597'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7597'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7598'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7598'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7599'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7599'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7600'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7600'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7601'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7601'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7602'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7602'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7603'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7603'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7604'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7604'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7605'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7605'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7606'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7606'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7607'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7607'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7608'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7608'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7609'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7609'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7610'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7610'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7611'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7611'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7612'

UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7612'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7613'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7613'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7614'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7614'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7615'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7615'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7616'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7616'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7617'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7617'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7618'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7618'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7619'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7619'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7620'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7620'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7621'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7621'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7622'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7622'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7623'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7623'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7624'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7624'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7625'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7625'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7626'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7626'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7627'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7627'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7628'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7628'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7629'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7629'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7630'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7630'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7631'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7631'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7632'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7632'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7633'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7633'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7634'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7634'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7635'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7635'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7636'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7636'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7637'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7637'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7638'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7638'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7639'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7639'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7640'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7640'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7641'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7641'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7642'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7642'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7643'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7643'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7644'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7644'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7645'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7645'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7646'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7646'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7647'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7647'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7648'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7648'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7649'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7649'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7650'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7650'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7651'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7651'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7652'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7652'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7653'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7653'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7654'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7654'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7655'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7655'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7656'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7656'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7657'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7657'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7658'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7658'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7659'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7659'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7660'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7660'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7661'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7661'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7662'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7662'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7663'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7663'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7664'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7664'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7665'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7665'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7666'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7666'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7667'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7667'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7668'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7668'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7669'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7669'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7670'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7670'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7671'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7671'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7672'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7672'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7673'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7673'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7674'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7674'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7675'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7675'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7676'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7676'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7677'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7677'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7678'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7678'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7679'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7679'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7680'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7680'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7681'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7681'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7682'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7682'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7683'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7683'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7684'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7684'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7685'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7685'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7686'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7686'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7687'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7687'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7688'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7688'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7689'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7689'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7690'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7690'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7691'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7691'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7692'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7692'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7693'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7693'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7694'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7694'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7695'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7695'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7696'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7696'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7697'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7697'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7698'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7698'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7699'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7699'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7700'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7700'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7701'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7701'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7702'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7702'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7703'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7703'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7704'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7704'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7705'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7705'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7706'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7706'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7707'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7707'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7708'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7708'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7709'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7709'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7710'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7710'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7711'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7711'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7712'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7712'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7713'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7713'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7714'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7714'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7715'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7715'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7716'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7716'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7717'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7717'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7718'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7718'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7719'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7719'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7720'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7720'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7721'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7721'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7722'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7722'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7723'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7723'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7724'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7724'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7725'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7725'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7726'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7726'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7727'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7727'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7728'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7728'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7729'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7729'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7730'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7730'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7731'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7731'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7732'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7732'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7733'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7733'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7734'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7734'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7735'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7735'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7736'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7736'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7737'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7737'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7738'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7738'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7739'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7739'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7740'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7740'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7741'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7741'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7742'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7742'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7743'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7743'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7744'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7744'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7745'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7745'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7746'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7746'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7747'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7747'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7748'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7748'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7749'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7749'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7750'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7750'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7751'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7751'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7752'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7752'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7753'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7753'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7754'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7754'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7755'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7755'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7756'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7756'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7757'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7757'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7758'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7758'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7759'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7759'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7760'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7760'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7761'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7761'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7762'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7762'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7763'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7763'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7764'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7764'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7765'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7765'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7766'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7766'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7767'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7767'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7768'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7768'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7769'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7769'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7770'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7770'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7771'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7771'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7772'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7772'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7773'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7773'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7774'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7774'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7775'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7775'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7776'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7776'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7777'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7777'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7778'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7778'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7779'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7779'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7780'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7780'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7781'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7781'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7782'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7782'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7783'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7783'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7784'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7784'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7785'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7785'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7786'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7786'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7787'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7787'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7788'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7788'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7789'

UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7789'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7790'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7790'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7791'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7791'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7792'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7792'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7793'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7793'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7794'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7794'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7795'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7795'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7796'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7796'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7797'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7797'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7798'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7798'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7799'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7799'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7800'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7800'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7801'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7801'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7802'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7802'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7803'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7803'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7804'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7804'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7805'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7805'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7806'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7806'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7807'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7807'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7808'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7808'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7809'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7809'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7810'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7810'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7811'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7811'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7812'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7812'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7813'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7813'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7814'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7814'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7815'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7815'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7816'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7816'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7817'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7817'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7818'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7818'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7819'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7819'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7820'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7820'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7821'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7821'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7822'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7822'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7823'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7823'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7824'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7824'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7825'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7825'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7826'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7826'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7827'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7827'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7828'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7828'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7829'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7829'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7830'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7830'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7831'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7831'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7832'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7832'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7833'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7833'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7834'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7834'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7835'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7835'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7836'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7836'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7837'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7837'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7838'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7838'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7839'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7839'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7840'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7840'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7841'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7841'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7842'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7842'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7843'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7843'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7844'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7844'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7845'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7845'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7846'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7846'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7847'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7847'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7848'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7848'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7849'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7849'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7850'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7850'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7851'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7851'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7852'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7852'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7853'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7853'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7854'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7854'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7855'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7855'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7856'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7856'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7857'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7857'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7858'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7858'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7859'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7859'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7860'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7860'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7861'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7861'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7862'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7862'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7863'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7863'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7864'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7864'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7865'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7865'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7866'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7866'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7867'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7867'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7868'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7868'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7869'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7869'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7870'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7870'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7871'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7871'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7872'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7872'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7873'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7873'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7874'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7874'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7875'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7875'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7876'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7876'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7877'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7877'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7878'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7878'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7879'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7879'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7880'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7880'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7881'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7881'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7882'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7882'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7883'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7883'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7884'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7884'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7885'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7885'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7886'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7886'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7887'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7887'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7888'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7888'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7889'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7889'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7890'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7890'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7891'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7891'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7892'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7892'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7893'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7893'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7894'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7894'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7895'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7895'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7896'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7896'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7897'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7897'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7898'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7898'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7899'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7899'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7900'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7900'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7901'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7901'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7902'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7902'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7903'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7903'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7904'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7904'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7905'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7905'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7906'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7906'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7907'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7907'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7908'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7908'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7909'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7909'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7910'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7910'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7911'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7911'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7912'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7912'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7913'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7913'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7914'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7914'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7915'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7915'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7916'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7916'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7917'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7917'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7918'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7918'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7919'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7919'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7920'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7920'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7921'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7921'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7922'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7922'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7923'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7923'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7924'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7924'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7925'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7925'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7926'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7926'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7927'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7927'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7928'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7928'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7929'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7929'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7930'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7930'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7931'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7931'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7932'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7932'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7933'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7933'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7934'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7934'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7935'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7935'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7936'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7936'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7937'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7937'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7938'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7938'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7939'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7939'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7940'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7940'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7941'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7941'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7942'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7942'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7943'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7943'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7944'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7944'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7945'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7945'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7946'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7946'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7947'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7947'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7948'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7948'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7949'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7949'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7950'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7950'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7951'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7951'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7952'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7952'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7953'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7953'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7954'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7954'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7955'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7955'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7956'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7956'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7957'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7957'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7958'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7958'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7959'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7959'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7960'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7960'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7961'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7961'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7962'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7962'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7963'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7963'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7964'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7964'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7965'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7965'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7966'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7966'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7967'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7967'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7968'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7968'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7969'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7969'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7970'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7970'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7971'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7971'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7972'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7972'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7973'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7973'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7974'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7974'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7975'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7975'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7976'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7976'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7977'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7977'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7978'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7978'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7979'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7979'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7980'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7980'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7981'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7981'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7982'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7982'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7983'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7983'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7984'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7984'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7985'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7985'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7986'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7986'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7987'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7987'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7988'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7988'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7989'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7989'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7990'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7990'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7991'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7991'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7992'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7992'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7993'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7993'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7994'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7994'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7995'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7995'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7996'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7996'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7997'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7997'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7998'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7998'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '7999'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '7999'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8000'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8000'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8001'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8001'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8002'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8002'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8003'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8003'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8004'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8004'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8005'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8005'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8006'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8006'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8007'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8007'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8008'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8008'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8009'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8009'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8010'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8010'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8011'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8011'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8012'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8012'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8013'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8013'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8014'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8014'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8015'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8015'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8016'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8016'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8017'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8017'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8018'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8018'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8019'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8019'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8020'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8020'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8021'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8021'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8022'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8022'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8023'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8023'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8024'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8024'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8025'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8025'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8026'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8026'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8027'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8027'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8028'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8028'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8029'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8029'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8030'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8030'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8031'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8031'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8032'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8032'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8033'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8033'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8034'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8034'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8035'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8035'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8036'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8036'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8037'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8037'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8038'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8038'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8039'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8039'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8040'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8040'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8041'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8041'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8042'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8042'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8043'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8043'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8044'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8044'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8045'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8045'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8046'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8046'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8047'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8047'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8048'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8048'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8049'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8049'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8050'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8050'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8051'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8051'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8052'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8052'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8053'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8053'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8054'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8054'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8055'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8055'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8056'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8056'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8057'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8057'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8058'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8058'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8059'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8059'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8060'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8060'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8061'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8061'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8062'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8062'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8063'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8063'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8064'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8064'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8065'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8065'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8066'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8066'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8067'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8067'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8068'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8068'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8069'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8069'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8070'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8070'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8071'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8071'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8072'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8072'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8073'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8073'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8074'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8074'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8075'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8075'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8076'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8076'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8077'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8077'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8078'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8078'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8079'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8079'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8080'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8080'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8081'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8081'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8082'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8082'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8083'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8083'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8084'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8084'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8085'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8085'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8086'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8086'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8087'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8087'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8088'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8088'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8089'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8089'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8090'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8090'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8091'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8091'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8092'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8092'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8093'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8093'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8094'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8094'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8095'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8095'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8096'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8096'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8097'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8097'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8098'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8098'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8099'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8099'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8100'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8100'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8101'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8101'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8102'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8102'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8103'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8103'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8104'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8104'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8105'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8105'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8106'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8106'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8107'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8107'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8108'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8108'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8109'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8109'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8110'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8110'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8111'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8111'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8112'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8112'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8113'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8113'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8114'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8114'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8115'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8115'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8116'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8116'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8117'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8117'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8118'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8118'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8119'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8119'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8120'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8120'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8121'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8121'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8122'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8122'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8123'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8123'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8124'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8124'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8125'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8125'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8126'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8126'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8127'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8127'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8128'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8128'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8129'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8129'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8130'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8130'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8131'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8131'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8132'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8132'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8133'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8133'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8134'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8134'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8135'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8135'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8136'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8136'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8137'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8137'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8138'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8138'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8139'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8139'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8140'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8140'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8141'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8141'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8142'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8142'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8143'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8143'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8144'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8144'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8145'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8145'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8146'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8146'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8147'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8147'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8148'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8148'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8149'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8149'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8150'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8150'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8151'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8151'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8152'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8152'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8153'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8153'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8154'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8154'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8155'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8155'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8156'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8156'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8157'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8157'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8158'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8158'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8159'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8159'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8160'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8160'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8161'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8161'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8162'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8162'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8163'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8163'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8164'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8164'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8165'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8165'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8166'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8166'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8167'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8167'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8168'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8168'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8169'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8169'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8170'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8170'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8171'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8171'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8172'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8172'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8173'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8173'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8174'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8174'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8175'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8175'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8176'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8176'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8177'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8177'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8178'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8178'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8179'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8179'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8180'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8180'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8181'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8181'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8182'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8182'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8183'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8183'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8184'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8184'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8185'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8185'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8186'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8186'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8187'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8187'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8188'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8188'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8189'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8189'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8190'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8190'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8191'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8191'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8192'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8192'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8193'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8193'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8194'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8194'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8195'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8195'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8196'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8196'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8197'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8197'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8198'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8198'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8199'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8199'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8200'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8200'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8201'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8201'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8202'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8202'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8203'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8203'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8204'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8204'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8205'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8205'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8206'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8206'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8207'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8207'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8208'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8208'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8209'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8209'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8210'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8210'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8211'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8211'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8212'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8212'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8213'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8213'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8214'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8214'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8215'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8215'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8216'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8216'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8217'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8217'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8218'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8218'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8219'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8219'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8220'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8220'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8221'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8221'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8222'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8222'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8223'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8223'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8224'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8224'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8225'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8225'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8226'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8226'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8227'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8227'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8228'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8228'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8229'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8229'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8230'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8230'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8231'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8231'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8232'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8232'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8233'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8233'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8234'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8234'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8235'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8235'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8236'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8236'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8237'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8237'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8238'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8238'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8239'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8239'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8240'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8240'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8241'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8241'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8242'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8242'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8243'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8243'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8244'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8244'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8245'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8245'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8246'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8246'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8247'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8247'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8248'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8248'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8249'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8249'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8250'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8250'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8251'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8251'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8252'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8252'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8253'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8253'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8254'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8254'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8255'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8255'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8256'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8256'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8257'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8257'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8258'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8258'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8259'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8259'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8260'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8260'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8261'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8261'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8262'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8262'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8263'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8263'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8264'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8264'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8265'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8265'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8266'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8266'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8267'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8267'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8268'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8268'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8269'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8269'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8270'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8270'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8271'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8271'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8272'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8272'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8273'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8273'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8274'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8274'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8275'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8275'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8276'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8276'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8277'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8277'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8278'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8278'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8279'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8279'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8280'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8280'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8281'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8281'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8282'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8282'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8283'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8283'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8284'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8284'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8285'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8285'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8286'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8286'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8287'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8287'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8288'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8288'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8289'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8289'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8290'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8290'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8291'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8291'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8292'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8292'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8293'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8293'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8294'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8294'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8295'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8295'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8296'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8296'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8297'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8297'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8298'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8298'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8299'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8299'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8300'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8300'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8301'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8301'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8302'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8302'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8303'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8303'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8304'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8304'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8305'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8305'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8306'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8306'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8307'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8307'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8308'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8308'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8309'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8309'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8310'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8310'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8311'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8311'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8312'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8312'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8313'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8313'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8314'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8314'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8315'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8315'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8316'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8316'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8317'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8317'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8318'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8318'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8319'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8319'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8320'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8320'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8321'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8321'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8322'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8322'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8323'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8323'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8324'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8324'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8325'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8325'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8326'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8326'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8327'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8327'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8328'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8328'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8329'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8329'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8330'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8330'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8331'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8331'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8332'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8332'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8333'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8333'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8334'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8334'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8335'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8335'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8336'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8336'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8337'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8337'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8338'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8338'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8339'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8339'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8340'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8340'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8341'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8341'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8342'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8342'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8343'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8343'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8344'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8344'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8345'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8345'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8346'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8346'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8347'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8347'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8348'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8348'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8349'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8349'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8350'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8350'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8351'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8351'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8352'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8352'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8353'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8353'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8354'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8354'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8355'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8355'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8356'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8356'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8357'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8357'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8358'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8358'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8359'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8359'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8360'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8360'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8361'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8361'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8362'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8362'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8363'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8363'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8364'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8364'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8365'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8365'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8366'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8366'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8367'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8367'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8368'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8368'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8369'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8369'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8370'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8370'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8371'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8371'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8372'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8372'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8373'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8373'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8374'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8374'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8375'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8375'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8376'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8376'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8377'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8377'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8378'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8378'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8379'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8379'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8380'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8380'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8381'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8381'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8382'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8382'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8383'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8383'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8384'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8384'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8385'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8385'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8386'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8386'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8387'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8387'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8388'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8388'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8389'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8389'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8390'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8390'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8391'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8391'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8392'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8392'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8393'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8393'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8394'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8394'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8395'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8395'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8396'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8396'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8397'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8397'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8398'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8398'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8399'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8399'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8400'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8400'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8401'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8401'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8402'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8402'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8403'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8403'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8404'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8404'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8405'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8405'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8406'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8406'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8407'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8407'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8408'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8408'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8409'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8409'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8410'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8410'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8411'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8411'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8412'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8412'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8413'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8413'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8414'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8414'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8415'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8415'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8416'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8416'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8417'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8417'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8418'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8418'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8419'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8419'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8420'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8420'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8421'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8421'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8422'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8422'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8423'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8423'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8424'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8424'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8425'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8425'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8426'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8426'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8427'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8427'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8428'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8428'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8429'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8429'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8430'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8430'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8431'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8431'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8432'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8432'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8433'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8433'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8434'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8434'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8435'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8435'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8436'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8436'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8437'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8437'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8438'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8438'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8439'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8439'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8440'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8440'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8441'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8441'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8442'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8442'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8443'

UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8443'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8444'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8444'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8445'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8445'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8446'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8446'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8447'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8447'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8448'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8448'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8449'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8449'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8450'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8450'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8451'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8451'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8452'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8452'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8453'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8453'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8454'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8454'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8455'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8455'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8456'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8456'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8457'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8457'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8458'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8458'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8459'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8459'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8460'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8460'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8461'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8461'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8462'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8462'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8463'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8463'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8464'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8464'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8465'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8465'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8466'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8466'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8467'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8467'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8468'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8468'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8469'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8469'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8470'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8470'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8471'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8471'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8472'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8472'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8473'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8473'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8474'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8474'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8475'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8475'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8476'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8476'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8477'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8477'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8478'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8478'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8479'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8479'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8480'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8480'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8481'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8481'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8482'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8482'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8483'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8483'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8484'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8484'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8485'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8485'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8486'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8486'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8487'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8487'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8488'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8488'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8489'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8489'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8490'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8490'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8491'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8491'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8492'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8492'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8493'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8493'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8494'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8494'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8495'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8495'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8496'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8496'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8497'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8497'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8498'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8498'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8499'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8499'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8500'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8500'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8501'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8501'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8502'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8502'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8503'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8503'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8504'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8504'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8505'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8505'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8506'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8506'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8507'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8507'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8508'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8508'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8509'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8509'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8510'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8510'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8511'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8511'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8512'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8512'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8513'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8513'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8514'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8514'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8515'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8515'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8516'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8516'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8517'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8517'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8518'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8518'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8519'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8519'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8520'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8520'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8521'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8521'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8522'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8522'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8523'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8523'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8524'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8524'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8525'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8525'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8526'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8526'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8527'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8527'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8528'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8528'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8529'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8529'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8530'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8530'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8531'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8531'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8532'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8532'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8533'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8533'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8534'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8534'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8535'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8535'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8536'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8536'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8537'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8537'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8538'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8538'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8539'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8539'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8540'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8540'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8541'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8541'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8542'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8542'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8543'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8543'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8544'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8544'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8545'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8545'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8546'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8546'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8547'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8547'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8548'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8548'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8549'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8549'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8550'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8550'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8551'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8551'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8552'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8552'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8553'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8553'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8554'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8554'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8555'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8555'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8556'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8556'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8557'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8557'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8558'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8558'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8559'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8559'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8560'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8560'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8561'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8561'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8562'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8562'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8563'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8563'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8564'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8564'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8565'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8565'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8566'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8566'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8567'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8567'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8568'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8568'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8569'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8569'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8570'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8570'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8571'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8571'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8572'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8572'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8573'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8573'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8574'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8574'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8575'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8575'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8576'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8576'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8577'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8577'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8578'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8578'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8579'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8579'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8580'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8580'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8581'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8581'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8582'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8582'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8583'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8583'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8584'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8584'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8585'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8585'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8586'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8586'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8587'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8587'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8588'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8588'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8589'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8589'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8590'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8590'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8591'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8591'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8592'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8592'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8593'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8593'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8594'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8594'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8595'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8595'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8596'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8596'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8597'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8597'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8598'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8598'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8599'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8599'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8600'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8600'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8601'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8601'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8602'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8602'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8603'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8603'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8604'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8604'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8605'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8605'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8606'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8606'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8607'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8607'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8608'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8608'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8609'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8609'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8610'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8610'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8611'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8611'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8612'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8612'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8613'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8613'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8614'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8614'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8615'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8615'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8616'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8616'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8617'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8617'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8618'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8618'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8619'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8619'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8620'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8620'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8621'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8621'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8622'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8622'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8623'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8623'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8624'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8624'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8625'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8625'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8626'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8626'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8627'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8627'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8628'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8628'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8629'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8629'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8630'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8630'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8631'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8631'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8632'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8632'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8633'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8633'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8634'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8634'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8635'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8635'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8636'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8636'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8637'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8637'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8638'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8638'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8639'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8639'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8640'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8640'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8641'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8641'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8642'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8642'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8643'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8643'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8644'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8644'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8645'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8645'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8646'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8646'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8647'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8647'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8648'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8648'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8649'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8649'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8650'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8650'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8651'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8651'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8652'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8652'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8653'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8653'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8654'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8654'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8655'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8655'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8656'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8656'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8657'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8657'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8658'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8658'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8659'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8659'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8660'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8660'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8661'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8661'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8662'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8662'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8663'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8663'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8664'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8664'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8665'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8665'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8666'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8666'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8667'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8667'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8668'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8668'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8669'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8669'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8670'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8670'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8671'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8671'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8672'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8672'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8673'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8673'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8674'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8674'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8675'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8675'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8676'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8676'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8677'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8677'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8678'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8678'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8679'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8679'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8680'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8680'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8681'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8681'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8682'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8682'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8683'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8683'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8684'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8684'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8685'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8685'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8686'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8686'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8687'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8687'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8688'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8688'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8689'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8689'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8690'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8690'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8691'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8691'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8692'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8692'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8693'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8693'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8694'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8694'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8695'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8695'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8696'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8696'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8697'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8697'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8698'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8698'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8699'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8699'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8700'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8700'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8701'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8701'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8702'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8702'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8703'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8703'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8704'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8704'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8705'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8705'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8706'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8706'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8707'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8707'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8708'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8708'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8709'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8709'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8710'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8710'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8711'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8711'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8712'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8712'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8713'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8713'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8714'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8714'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8715'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8715'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8716'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8716'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8717'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8717'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8718'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8718'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8719'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8719'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8720'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8720'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8721'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8721'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8722'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8722'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8723'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8723'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8724'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8724'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8725'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8725'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8726'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8726'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8727'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8727'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8728'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8728'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8729'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8729'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8730'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8730'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8731'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8731'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8732'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8732'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8733'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8733'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8734'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8734'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8735'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8735'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8736'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8736'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8737'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8737'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8738'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8738'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8739'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8739'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8740'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8740'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8741'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8741'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8742'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8742'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8743'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8743'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8744'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8744'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8745'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8745'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8746'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8746'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8747'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8747'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8748'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8748'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8749'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8749'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8750'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8750'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8751'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8751'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8752'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8752'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8753'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8753'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8754'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8754'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8755'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8755'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8756'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8756'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8757'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8757'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8758'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8758'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8759'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8759'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8760'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8760'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8761'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8761'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8762'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8762'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8763'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8763'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8764'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8764'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8765'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8765'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8766'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8766'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8767'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8767'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8768'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8768'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8769'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8769'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8770'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8770'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8771'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8771'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8772'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8772'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8773'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8773'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8774'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8774'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8775'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8775'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8776'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8776'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8777'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8777'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8778'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8778'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8779'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8779'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8780'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8780'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8781'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8781'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8782'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8782'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8783'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8783'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8784'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8784'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8785'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8785'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8786'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8786'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8787'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8787'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8788'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8788'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8789'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8789'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8790'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8790'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8791'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8791'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8792'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8792'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8793'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8793'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8794'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8794'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8795'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8795'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8796'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8796'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8797'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8797'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8798'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8798'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8799'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8799'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8800'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8800'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8801'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8801'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8802'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8802'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8803'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8803'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8804'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8804'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8805'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8805'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8806'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8806'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8807'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8807'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8808'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8808'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8809'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8809'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8810'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8810'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8811'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8811'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8812'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8812'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8813'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8813'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8814'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8814'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8815'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8815'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8816'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8816'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8817'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8817'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8818'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8818'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8819'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8819'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8820'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8820'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8821'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8821'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8822'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8822'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8823'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8823'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8824'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8824'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8825'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8825'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8826'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8826'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8827'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8827'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8828'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8828'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8829'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8829'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8830'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8830'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8831'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8831'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8832'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8832'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8833'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8833'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8834'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8834'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8835'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8835'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8836'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8836'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8837'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8837'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8838'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8838'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8839'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8839'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8840'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8840'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8841'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8841'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8842'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8842'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8843'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8843'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8844'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8844'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8845'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8845'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8846'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8846'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8847'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8847'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8848'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8848'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8849'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8849'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8850'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8850'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8851'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8851'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8852'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8852'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8853'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8853'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8854'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8854'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8855'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8855'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8856'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8856'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8857'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8857'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8858'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8858'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8859'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8859'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8860'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8860'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8861'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8861'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8862'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8862'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8863'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8863'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8864'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8864'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8865'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8865'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8866'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8866'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8867'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8867'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8868'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8868'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8869'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8869'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8870'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8870'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8871'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8871'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8872'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8872'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8873'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8873'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8874'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8874'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8875'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8875'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8876'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8876'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8877'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8877'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8878'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8878'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8879'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8879'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8880'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8880'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8881'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8881'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8882'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8882'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8883'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8883'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8884'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8884'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8885'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8885'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8886'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8886'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8887'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8887'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8888'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8888'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8889'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8889'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8890'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8890'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8891'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8891'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8892'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8892'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8893'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8893'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8894'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8894'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8895'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8895'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8896'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8896'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8897'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8897'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8898'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8898'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8899'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8899'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8900'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8900'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8901'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8901'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8902'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8902'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8903'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8903'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8904'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8904'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8905'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8905'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8906'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8906'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8907'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8907'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8908'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8908'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8909'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8909'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8910'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8910'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8911'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8911'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8912'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8912'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8913'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8913'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8914'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8914'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8915'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8915'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8916'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8916'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8917'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8917'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8918'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8918'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8919'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8919'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8920'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8920'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8921'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8921'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8922'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8922'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8923'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8923'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8924'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8924'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8925'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8925'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8926'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8926'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8927'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8927'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8928'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8928'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8929'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8929'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8930'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8930'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8931'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8931'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8932'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8932'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8933'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8933'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8934'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8934'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8935'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8935'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8936'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8936'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8937'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8937'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8938'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8938'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8939'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8939'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8940'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8940'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8941'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8941'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8942'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8942'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8943'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8943'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8944'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8944'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8945'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8945'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8946'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8946'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8947'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8947'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8948'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8948'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8949'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8949'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8950'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8950'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8951'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8951'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8952'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8952'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8953'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8953'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8954'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8954'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8955'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8955'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8956'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8956'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8957'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8957'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8958'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8958'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8959'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8959'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8960'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8960'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8961'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8961'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8962'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8962'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8963'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8963'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8964'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8964'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8965'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8965'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8966'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8966'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8967'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8967'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8968'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8968'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8969'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8969'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8970'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8970'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8971'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8971'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8972'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8972'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8973'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8973'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8974'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8974'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8975'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8975'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8976'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8976'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8977'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8977'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8978'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8978'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8979'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8979'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8980'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8980'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8981'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8981'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8982'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8982'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8983'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8983'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8984'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8984'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8985'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8985'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8986'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8986'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8987'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8987'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8988'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8988'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8989'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8989'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8990'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8990'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8991'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8991'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8992'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8992'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8993'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8993'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8994'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8994'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8995'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8995'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8996'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8996'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8997'

UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8997'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8998'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8998'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '8999'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '8999'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9000'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9000'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9001'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9001'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9002'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9002'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9003'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9003'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9004'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9004'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9005'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9005'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9006'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9006'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9007'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9007'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9008'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9008'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9009'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9009'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9010'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9010'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9011'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9011'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9012'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9012'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9013'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9013'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9014'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9014'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9015'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9015'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9016'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9016'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9017'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9017'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9018'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9018'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9019'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9019'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9020'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9020'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9021'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9021'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9022'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9022'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9023'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9023'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9024'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9024'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9025'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9025'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9026'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9026'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9027'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9027'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9028'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9028'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9029'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9029'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9030'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9030'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9031'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9031'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9032'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9032'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9033'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9033'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9034'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9034'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9035'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9035'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9036'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9036'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9037'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9037'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9038'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9038'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9039'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9039'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9040'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9040'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9041'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9041'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9042'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9042'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9043'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9043'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9044'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9044'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9045'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9045'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9046'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9046'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9047'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9047'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9048'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9048'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9049'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9049'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9050'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9050'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9051'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9051'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9052'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9052'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9053'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9053'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9054'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9054'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9055'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9055'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9056'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9056'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9057'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9057'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9058'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9058'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9059'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9059'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9060'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9060'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9061'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9061'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9062'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9062'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9063'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9063'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9064'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9064'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9065'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9065'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9066'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9066'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9067'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9067'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9068'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9068'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9069'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9069'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9070'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9070'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9071'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9071'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9072'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9072'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9073'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9073'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9074'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9074'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9075'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9075'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9076'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9076'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9077'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9077'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9078'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9078'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9079'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9079'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9080'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9080'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9081'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9081'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9082'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9082'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9083'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9083'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9084'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9084'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9085'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9085'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9086'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9086'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9087'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9087'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9088'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9088'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9089'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9089'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9090'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9090'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9091'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9091'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9092'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9092'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9093'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9093'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9094'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9094'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9095'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9095'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9096'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9096'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9097'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9097'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9098'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9098'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9099'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9099'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9100'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9100'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9101'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9101'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9102'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9102'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9103'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9103'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9104'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9104'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9105'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9105'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9106'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9106'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9107'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9107'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9108'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9108'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9109'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9109'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9110'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9110'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9111'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9111'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9112'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9112'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9113'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9113'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9114'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9114'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9115'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9115'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9116'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9116'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9117'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9117'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9118'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9118'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9119'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9119'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9120'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9120'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9121'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9121'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9122'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9122'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9123'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9123'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9124'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9124'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9125'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9125'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9126'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9126'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9127'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9127'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9128'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9128'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9129'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9129'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9130'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9130'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9131'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9131'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9132'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9132'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9133'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9133'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9134'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9134'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9135'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9135'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9136'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9136'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9137'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9137'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9138'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9138'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9139'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9139'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9140'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9140'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9141'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9141'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9142'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9142'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9143'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9143'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9144'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9144'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9145'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9145'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9146'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9146'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9147'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9147'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9148'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9148'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9149'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9149'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9150'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9150'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9151'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9151'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9152'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9152'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9153'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9153'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9154'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9154'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9155'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9155'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9156'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9156'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9157'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9157'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9158'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9158'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9159'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9159'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9160'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9160'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9161'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9161'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9162'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9162'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9163'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9163'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9164'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9164'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9165'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9165'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9166'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9166'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9167'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9167'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9168'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9168'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9169'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9169'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9170'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9170'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9171'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9171'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9172'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9172'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9173'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9173'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9174'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9174'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9175'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9175'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9176'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9176'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9177'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9177'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9178'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9178'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9179'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9179'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9180'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9180'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9181'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9181'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9182'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9182'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9183'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9183'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9184'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9184'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9185'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9185'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9186'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9186'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9187'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9187'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9188'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9188'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9189'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9189'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9190'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9190'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9191'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9191'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9192'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9192'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9193'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9193'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9194'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9194'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9195'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9195'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9196'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9196'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9197'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9197'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9198'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9198'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9199'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9199'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9200'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9200'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9201'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9201'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9202'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9202'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9203'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9203'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9204'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9204'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9205'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9205'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9206'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9206'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9207'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9207'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9208'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9208'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9209'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9209'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9210'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9210'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9211'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9211'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9212'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9212'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9213'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9213'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9214'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9214'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9215'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9215'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9216'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9216'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9217'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9217'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9218'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9218'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9219'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9219'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9220'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9220'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9221'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9221'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9222'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9222'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9223'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9223'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9224'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9224'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9225'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9225'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9226'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9226'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9227'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9227'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9228'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9228'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9229'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9229'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9230'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9230'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9231'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9231'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9232'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9232'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9233'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9233'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9234'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9234'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9235'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9235'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9236'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9236'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9237'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9237'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9238'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9238'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9239'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9239'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9240'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9240'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9241'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9241'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9242'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9242'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9243'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9243'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9244'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9244'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9245'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9245'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9246'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9246'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9247'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9247'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9248'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9248'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9249'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9249'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9250'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9250'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9251'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9251'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9252'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9252'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9253'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9253'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9254'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9254'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9255'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9255'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9256'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9256'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9257'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9257'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9258'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9258'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9259'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9259'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9260'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9260'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9261'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9261'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9262'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9262'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9263'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9263'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9264'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9264'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9265'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9265'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9266'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9266'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9267'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9267'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9268'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9268'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9269'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9269'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9270'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9270'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9271'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9271'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9272'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9272'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9273'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9273'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9274'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9274'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9275'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9275'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9276'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9276'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9277'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9277'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9278'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9278'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9279'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9279'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9280'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9280'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9281'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9281'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9282'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9282'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9283'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9283'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9284'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9284'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9285'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9285'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9286'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9286'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9287'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9287'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9288'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9288'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9289'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9289'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9290'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9290'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9291'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9291'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9292'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9292'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9293'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9293'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9294'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9294'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9295'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9295'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9296'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9296'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9297'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9297'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9298'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9298'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9299'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9299'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9300'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9300'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9301'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9301'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9302'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9302'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9303'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9303'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9304'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9304'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9305'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9305'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9306'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9306'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9307'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9307'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9308'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9308'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9309'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9309'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9310'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9310'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9311'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9311'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9312'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9312'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9313'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9313'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9314'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9314'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9315'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9315'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9316'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9316'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9317'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9317'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9318'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9318'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9319'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9319'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9320'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9320'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9321'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9321'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9322'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9322'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9323'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9323'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9324'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9324'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9325'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9325'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9326'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9326'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9327'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9327'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9328'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9328'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9329'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9329'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9330'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9330'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9331'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9331'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9332'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9332'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9333'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9333'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9334'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9334'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9335'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9335'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9336'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9336'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9337'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9337'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9338'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9338'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9339'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9339'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9340'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9340'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9341'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9341'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9342'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9342'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9343'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9343'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9344'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9344'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9345'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9345'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9346'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9346'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9347'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9347'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9348'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9348'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9349'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9349'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9350'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9350'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9351'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9351'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9352'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9352'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9353'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9353'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9354'

UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9354'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9355'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9355'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9356'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9356'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9357'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9357'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9358'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9358'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9359'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9359'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9360'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9360'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9361'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9361'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9362'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9362'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9363'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9363'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9364'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9364'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9365'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9365'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9366'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9366'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9367'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9367'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9368'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9368'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9369'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9369'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9370'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9370'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9371'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9371'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9372'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9372'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9373'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9373'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9374'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9374'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9375'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9375'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9376'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9376'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9377'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9377'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9378'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9378'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9379'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9379'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9380'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9380'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9381'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9381'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9382'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9382'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9383'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9383'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9384'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9384'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9385'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9385'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9386'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9386'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9387'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9387'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9388'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9388'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9389'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9389'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9390'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9390'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9391'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9391'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9392'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9392'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9393'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9393'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9394'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9394'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9395'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9395'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9396'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9396'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9397'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9397'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9398'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9398'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9399'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9399'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9400'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9400'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9401'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9401'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9402'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9402'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9403'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9403'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9404'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9404'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9405'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9405'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9406'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9406'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9407'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9407'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9408'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9408'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9409'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9409'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9410'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9410'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9411'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9411'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9412'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9412'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9413'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9413'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9414'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9414'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9415'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9415'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9416'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9416'

None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9417'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9417'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9418'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9418'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9419'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9419'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9420'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9420'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9421'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9421'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9422'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9422'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9423'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9423'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9424'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9424'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9425'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9425'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9426'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9426'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9427'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9427'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9428'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9428'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9429'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9429'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9430'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9430'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9431'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9431'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9432'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9432'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9433'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9433'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9434'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9434'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9435'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9435'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9436'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9436'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9437'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9437'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9438'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9438'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9439'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9439'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9440'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9440'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9441'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9441'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9442'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9442'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9443'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9443'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9444'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9444'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9445'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9445'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9446'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9446'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9447'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9447'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9448'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9448'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9449'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9449'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9450'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9450'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9451'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9451'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9452'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9452'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9453'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9453'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9454'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9454'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9455'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9455'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9456'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9456'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9457'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9457'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9458'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9458'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9459'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9459'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9460'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9460'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9461'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9461'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9462'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9462'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9463'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9463'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9464'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9464'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9465'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9465'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9466'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9466'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9467'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9467'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9468'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9468'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9469'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9469'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9470'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9470'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9471'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9471'
None
UPDATE job_vacancies SET gpa_min =  Null where raw_id = '9472'
UPDATE jobstreet_raws_rc SET gpa_min = '--extracted--'     where id = '9472'